Repository celo-org/celo-monorepo, pull requests merged in 2019-09, with the labels that each got.

#792 Aaronmgdr/social links connect
  packages/web/src/community/connect/ConnectPage.tsx
  packages/web/src/dev/DeveloperUpdates.tsx
  packages/web/src/icons/Discourse.tsx
  packages/web/src/icons/LinkedIn.tsx
  packages/web/src/shared/Developer-news.png
  packages/web/src/shared/Footer.3.tsx
  packages/web/src/shared/SocialChannels.tsx
  packages/web/src/shared/menu-items.ts
Labels: automerge

#801 [contractkit] Complete Exchange Wrapper
  .circleci/config.yml
  packages/contractkit/package.json
  packages/contractkit/src/utils/tx-signing.test.ts
  packages/contractkit/src/wrappers/BaseWrapper.ts
  packages/contractkit/src/wrappers/Exchange.test.ts
  packages/contractkit/src/wrappers/Exchange.ts
  packages/protocol/lib/test-utils.ts
  packages/protocol/package.json
  yarn.lock
Labels: automerge

#825 [wallet] Always allow users to view backup key
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/java/org/celo/mobile/MainApplication.java
  packages/mobile/android/settings.gradle
  packages/mobile/package.json
  packages/mobile/src/account/Account.tsx
  packages/mobile/src/account/reducer.ts
  packages/mobile/src/backup/Backup.test.tsx
  packages/mobile/src/backup/Backup.tsx
  packages/mobile/src/backup/BackupComplete.test.tsx
  packages/mobile/src/backup/BackupComplete.tsx
  packages/mobile/src/backup/BackupPhrase.tsx
  packages/mobile/src/backup/BackupPhraseContainer.test.tsx
  packages/mobile/src/backup/BackupPhraseContainer.tsx
  packages/mobile/src/backup/__snapshots__/Backup.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupComplete.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupPhraseContainer.test.tsx.snap
  packages/mobile/src/import/saga.ts
  packages/mobile/src/index.d.ts
  packages/mobile/src/utils/keyStore.ts
  packages/mobile/src/web3/saga.ts
  yarn.lock
Labels: automerge

#796 [CLI]Minor code improvement in CLI, remove ts-ignore-next-line
  packages/cli/src/commands/account/new.ts
Labels: automerge

#849 Kill end-to-end celo-blockchain instances with SIGINT
  packages/celotool/geth_tests/src/lib/utils.ts
Labels: automerge

#850 Use HTTPS instead of SSH for ethereumjs-vm
  packages/protocol/package.json
  yarn.lock
Labels: automerge

#827 Export geth metrics from StatefulSet tx-nodes and validators
  packages/helm-charts/testnet/templates/txnode.statefulset.yaml
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
Labels: automerge

#833 Try to prevent camera crash by only showing view on focused screen
  packages/mobile/src/qrcode/QRScanner.tsx
Labels: automerge, wallet

#851 Web Join Page One Line Text Change
  packages/web/static/locales/en/jobs.json
Labels: automerge

#858 [wallet] Fix text error in Celo Gold faucet transfer confirmation
  packages/react-components/components/MoneyAmount.tsx
Labels: automerge

#805 Fix double page opening when target passed.
  packages/web/src/header/Header.3.tsx
  packages/web/src/shared/Button.3.tsx
Labels: automerge

#859 Add fetch balance and send events for pilot analytics
  packages/mobile/src/analytics/constants.ts
  packages/mobile/src/send/saga.ts
  packages/mobile/src/tokens/saga.ts
  packages/mobile/src/transactions/saga.ts
Labels: automerge

#866 [wallet] Update libphonenumber version and properly handle MX phone numbers
  packages/cli/src/commands/lockedgold/lockup.ts
  packages/cli/src/utils/helpers.ts
  packages/contractkit/src/wrappers/BaseWrapper.ts
  packages/contractkit/src/wrappers/LockedGold.ts
  packages/contractkit/src/wrappers/Validators.ts
  packages/mobile/package.json
  packages/mobile/src/recipients/RecipientPicker.tsx
  packages/protocol/test/identity/attestations.ts
  packages/utils/.gitignore
  packages/utils/index.d.ts
  packages/utils/index.ts
  packages/utils/jest.config.js
  packages/utils/package.json
  packages/utils/src/index.ts
  packages/utils/src/phoneNumbers.ts
  packages/utils/src/types.d.ts
  packages/utils/test/phoneNumbers.test.ts
  packages/utils/tsconfig.json
  packages/verification-pool-api/package.json
  yarn.lock
Labels: automerge

#864 Deploy pilot
  .env.pilot
  packages/blockchain-api/app.pilot.yaml
  packages/notification-service/config/config.pilot.env
  packages/verification-pool-api/contracts/Attestations.ts
  packages/verification-pool-api/contracts/GoldToken.ts
  packages/verification-pool-api/contracts/StableToken.ts
  packages/verification-pool-api/src/celoEnv.ts
Labels: automerge

#867 Deploy integration
  .env.integration
  packages/helm-charts/testnet/templates/txnode.statefulset.yaml
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
  packages/mobile/package.json
  yarn.lock
Labels: automerge

#852 Whitelist issuer property in analytics calls
  packages/mobile/src/analytics/constants.ts
Labels: automerge

#862 Make gasCurrency and to optional in requestTxSignature
  packages/dappkit/src/index.ts
  packages/mobile/src/dappkit/dappkit.ts
  packages/utils/src/dappkit.ts
Labels: automerge

#863 Show the dappName in the DAppKit Screens
  packages/mobile/locales/en-US/dappkit.json
  packages/mobile/src/dappkit/DappKitAccountScreen.tsx
  packages/mobile/src/dappkit/DappKitSignTxScreen.tsx
Labels: automerge

#772 Web Minor Update to style and type
  packages/web/src/community/EcoFund.tsx
  packages/web/src/community/connect/ArticlesSection.tsx
  packages/web/src/community/connect/Contribute.tsx
  packages/web/src/community/connect/Events.tsx
  packages/web/src/dev/CoverAction.tsx
  packages/web/src/dev/FullStack.tsx
  packages/web/src/dev/Phone.tsx
  packages/web/src/download/AppStores.tsx
  packages/web/src/home/HomeBackers.tsx
  packages/web/src/home/HomeCarousel.tsx
  packages/web/src/home/HomeSystems.tsx
  packages/web/src/home/version3/HomeWork.tsx
  packages/web/src/join/ImagePanes.tsx
  packages/web/src/press/Press.tsx
  packages/web/src/shared/Button.3.tsx
  packages/web/src/shared/Card.tsx
  packages/web/src/styles.ts
  packages/web/src/terms/TermsPortal.tsx
Labels: automerge

#873 Add instrumentation for view calls and gas estimation during verification
  packages/mobile/src/analytics/constants.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/transactions/send.ts
Labels: automerge, wallet

#797 Allow validators to use any valid combination of gold commitments as stake
  packages/cli/src/commands/validator/register.ts
  packages/cli/src/commands/validatorgroup/register.ts
  packages/cli/tsconfig.json
  packages/docs/command-line-interface/validator.md
  packages/docs/command-line-interface/validatorgroup.md
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/migrations/16_elect_validators.ts
  packages/protocol/test/governance/validators.ts
Labels: automerge

#875 [wallet] Switch over to new tab bar design
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-AR/global.json
  packages/mobile/src/account/DollarEducation.tsx
  packages/mobile/src/icons/Exchange.tsx
  packages/mobile/src/icons/GoldTab.tsx
  packages/mobile/src/icons/PaymentsIcon.tsx
  packages/mobile/src/icons/Wallet.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/TabBar.tsx
  packages/mobile/src/navigator/TabNavigator.tsx
  packages/mobile/src/send/Send.tsx
  packages/mobile/src/transactions/NoActivity.tsx
Labels: automerge, wallet

#659 [wallet] Use generic icon and user thumbnails in transfer review screens
  packages/mobile/src/account/InviteReview.tsx
  packages/mobile/src/account/__snapshots__/InviteReview.test.tsx.snap
  packages/mobile/src/components/Avatar.tsx
  packages/mobile/src/paymentRequest/PaymentRequestReviewCard.tsx
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/TransferConfirmationCard.tsx
  packages/mobile/src/send/TransferReviewCard.tsx
  packages/mobile/src/send/__snapshots__/TransferConfirmationCard.test.tsx.snap
  packages/mobile/src/send/__snapshots__/TransferReviewCard.test.tsx.snap
  packages/mobile/src/transactions/TransferFeedItem.tsx
  packages/react-components/components/Avatar.tsx
  packages/react-components/components/ContactCircle.tsx
Labels: automerge, wallet

#861 [Wallet] Replaced Argentina Spanish support in favor of more general Latin American Spanish
  packages/mobile/locales/es-419/accountScreen10.json
  packages/mobile/locales/es-419/backupKeyFlow6.json
  packages/mobile/locales/es-419/dappkit.json
  packages/mobile/locales/es-419/dev.json
  packages/mobile/locales/es-419/exchangeFlow9.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/es-419/index.ts
  packages/mobile/locales/es-419/inviteFlow11.json
  packages/mobile/locales/es-419/nuxCurrencyPhoto4.json
  packages/mobile/locales/es-419/nuxNamePin1.json
  packages/mobile/locales/es-419/nuxRestoreWallet3.json
  packages/mobile/locales/es-419/nuxVerification2.json
  packages/mobile/locales/es-419/paymentRequestFlow.json
  packages/mobile/locales/es-419/receiveFlow8.json
  packages/mobile/locales/es-419/sendFlow7.json
  packages/mobile/locales/es-419/walletFlow5.json
  packages/mobile/locales/es-AR/index.ts
  packages/mobile/locales/index.ts
  packages/mobile/scripts/verify_locales.sh
  packages/mobile/src/config.ts
  packages/mobile/src/i18n.ts
  packages/mobile/src/invite/utils.test.ts
  packages/mobile/src/language/Language.tsx
  packages/mobile/src/language/__snapshots__/Language.test.tsx.snap
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/store.ts
  packages/mobile/src/send/SendAmount.test.tsx
  packages/mobile/test/schemas.ts
  packages/react-components/components/LanguageSelectUI.test.tsx
  packages/react-components/components/LanguageSelectUI.tsx
  packages/react-components/components/__snapshots__/LanguageSelectUI.test.tsx.snap
  packages/utils/src/currencies.ts
  packages/verifier/src/components/NUX/LanguageScreen.tsx
Labels: automerge, wallet

#881 [Wallet] Upgrade app version to 1.4.2
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/assets/custom/LicenseDisclaimer.txt
  packages/mobile/android/gradle.properties
  packages/mobile/ios/celo-tvOS/Info.plist
  packages/mobile/ios/celo-tvOSTests/Info.plist
  packages/mobile/ios/celo/Info.plist
  packages/mobile/ios/celoTests/Info.plist
  packages/mobile/package.json
Labels: automerge

#828 Retry to deal with flakiness of `@celo/walletkit`
  .circleci/config.yml
Labels: automerge

#657 Hash registry contract names
  packages/contractkit/src/address-registry.ts
  packages/protocol/contracts/common/Registry.sol
  packages/protocol/contracts/common/UsingRegistry.sol
  packages/protocol/contracts/common/interfaces/IRegistry.sol
  packages/protocol/lib/test-utils.ts
  packages/protocol/test/common/integration.ts
  packages/protocol/test/common/registry.ts
Labels: automerge, protocol

#829 Deploy pilotstaging
  .env.pilotstaging
  packages/blockchain-api/app.pilotstaging.yaml
  packages/notification-service/config/config.pilotstaging.env
  packages/verification-pool-api/contracts/Attestations.ts
  packages/verification-pool-api/contracts/GoldToken.ts
  packages/verification-pool-api/contracts/StableToken.ts
Labels: automerge

#891 [wallet] Update es-419 translations
  packages/mobile/locales/en-US/nuxNamePin1.json
  packages/mobile/locales/es-419/backupKeyFlow6.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/es-419/inviteFlow11.json
  packages/mobile/locales/es-419/nuxCurrencyPhoto4.json
  packages/mobile/locales/es-419/nuxNamePin1.json
  packages/mobile/locales/es-419/nuxRestoreWallet3.json
  packages/mobile/locales/es-419/nuxVerification2.json
  packages/mobile/locales/es-419/sendFlow7.json
  packages/mobile/locales/es-419/walletFlow5.json
Labels: automerge

#804 add Celo Spinner to web
  packages/web/package.json
  packages/web/src/animate/LottieBase.tsx
  packages/web/src/fauceting/MicroComponents.tsx
  packages/web/src/shared/Spinner.tsx
  packages/web/static/lottieFiles/darkSpinner.json
  packages/web/static/lottieFiles/greenSpinner.json
  packages/web/static/lottieFiles/whiteSpinner.json
  yarn.lock
Labels: automerge

#889 Generate CLI docs with typescript source references
  packages/cli/package.json
  packages/docs/command-line-interface/account.md
  packages/docs/command-line-interface/config.md
  packages/docs/command-line-interface/exchange.md
  packages/docs/command-line-interface/lockedgold.md
  packages/docs/command-line-interface/node.md
  packages/docs/command-line-interface/validator.md
  packages/docs/command-line-interface/validatorgroup.md
Labels: automerge

#337 Replace exact fractions with Fixidity
  packages/celotool/geth_tests/transfer_tests.ts
  packages/protocol/contracts/common/FixidityLib.sol
  packages/protocol/contracts/common/GasPriceMinimum.sol
  packages/protocol/contracts/common/test/FixidityTest.sol
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/governance/LockedGold.sol
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/contracts/governance/interfaces/IGovernance.sol
  packages/protocol/contracts/stability/Exchange.sol
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/contracts/stability/SortedOracles.sol
  packages/protocol/contracts/stability/StableToken.sol
  packages/protocol/contracts/stability/interfaces/IExchange.sol
  packages/protocol/contracts/stability/interfaces/IStableToken.sol
  packages/protocol/lib/fixidity.ts
  packages/protocol/lib/test-utils.ts
  packages/protocol/migrations/06_gaspriceminimum.ts
  packages/protocol/migrations/08_stabletoken.ts
  packages/protocol/migrations/09_exchange.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/runTests.js
  packages/protocol/scripts/bash/ganache.sh
  packages/protocol/test/common/fixidity.ts
  packages/protocol/test/common/gaspriceminimum.ts
  packages/protocol/test/common/integration.ts
  packages/protocol/test/governance/governance.ts
  packages/protocol/test/stability/exchange.ts
  packages/protocol/test/stability/sortedoracles.ts
  packages/protocol/test/stability/stabletoken.ts
  packages/protocol/truffle.js
Labels: automerge

#876 testnet isolated networks support
  packages/celotool/src/lib/helm_deploy.ts
  packages/helm-charts/testnet/templates/bootnode.deployment.yaml
  packages/helm-charts/testnet/templates/txnode.statefulset.yaml
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
Labels: automerge

#902 Add VM BASED param to fix faucet and invite
  .env.alfajores
  .env.alfajoresstaging
Labels: automerge

#305 Enable Solidity Coverage
  .circleci/config.yml
  .codecov.yml
  packages/protocol/.gitignore
  packages/protocol/package.json
  packages/protocol/runCoverage.js
  packages/protocol/runTests.js
  packages/protocol/test/common/proxy.ts
  packages/protocol/test/governance/bondeddeposits.ts
  packages/protocol/test/teardown.ts
  packages/protocol/truffle.js
  yarn.lock
Labels: automerge

#807 Automatic Announcements
  packages/web/env-config.js.enc
  packages/web/server-env-config.js.enc
  packages/web/server/Announcement.ts
  packages/web/server/index.ts
  packages/web/src/header/BlueBanner.tsx
  packages/web/src/header/Header.3.tsx
Labels: automerge

#908 [wallet] Fix autocomplete when searching countries in Spanish
  packages/utils/src/countries.test.ts
  packages/utils/src/countries.ts
Labels: automerge

#814 Add VM_BASED variable to envs
  .env
  .env.integrationtesting
  .env.pilotstaging
Labels: automerge

#795 [CLI]Fix CLI
  .circleci/config.yml
  packages/cli/tsconfig.json
Labels: automerge

#917 [wallet] Fix crashes due to referrer lib
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/android/app/src/main/java/org/celo/mobile/MainApplication.java
  packages/mobile/package.json
  yarn.lock
Labels: automerge, wallet

#958 [Wallet] Speed up jest tests
  packages/mobile/jest.config.js
  packages/react-components/jest.config.js
  packages/verifier/jest.config.js
Labels: automerge

#963 [contractkit] Fix tests
  packages/contractkit/src/test-utils/ganache.setup.ts
  packages/contractkit/src/wrappers/Exchange.test.ts
  packages/protocol/scripts/devchain.ts
Labels: automerge

#907 CeloCLI sorted list of Validator Groups should not include groups with zero votes
  packages/cli/package.json
  packages/contractkit/src/wrappers/Validators.ts
Labels: automerge

#989 Add README-dev.md
  README-dev.md
Labels: automerge

#1009 Pilot app config and ability to not show testnet banner
  .env.pilot
  .env.pilotstaging
  packages/mobile/.env.alfajores
  packages/mobile/.env.integration
  packages/mobile/.env.pilot
  packages/mobile/.env.pilotstaging
  packages/mobile/.env.production
  packages/mobile/.env.test
  packages/mobile/.gitignore
  packages/mobile/__mocks__/react-native-config.ts
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/pilot/google-services.json.enc
  packages/mobile/android/app/src/pilot/res/mipmap-hdpi/ic_launcher.png
  packages/mobile/android/app/src/pilot/res/mipmap-mdpi/ic_launcher.png
  packages/mobile/android/app/src/pilot/res/mipmap-xhdpi/ic_launcher.png
  packages/mobile/android/app/src/pilot/res/mipmap-xxhdpi/ic_launcher.png
  packages/mobile/android/app/src/pilot/res/mipmap-xxxhdpi/ic_launcher.png
  packages/mobile/android/app/src/pilot/res/values/strings.xml
  packages/mobile/fastlane/Fastfile
  packages/mobile/fastlane/README.md
  packages/mobile/src/config.ts
  packages/mobile/src/home/WalletHome.tsx
  scripts/key_placer.sh
Labels: automerge, wallet

#936 [wallet]Select blockchain url based on testnet
  packages/mobile/.env
  packages/mobile/src/config.ts
  packages/mobile/src/geth/network-config.ts
Labels: automerge

#991 [CircleCI]Run protocol test with and without coverage
  .circleci/config.yml
Labels: automerge

#990 [celotool] Fund Faucet accounts on network init
  packages/celotool/src/cmds/deploy/initial/contracts.ts
  packages/celotool/src/e2e-tests/utils.ts
  packages/celotool/src/lib/generate_utils.ts
  packages/protocol/migrations/08_stabletoken.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/scripts/bash/migrate.sh
Labels: automerge

#874 Expose and test validator set precompiles
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/celotool/src/e2e-tests/utils.ts
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/truffle.js
Labels: automerge

#1018 [CircleCI]Run protocol coverage once a day
  .circleci/config.yml
Labels: automerge

#952 Fix fixed fraction division underflow
  packages/contractkit/src/wrappers/Exchange.test.ts
  packages/protocol/contracts/common/FixidityLib.sol
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/stability/Exchange.sol
  packages/protocol/contracts/stability/StableToken.sol
  packages/protocol/test/stability/exchange.ts
  packages/utils/src/fixidity.ts
Labels: automerge

#941 [wip] LinkedList cycle fix
  packages/protocol/contracts/common/linkedlists/LinkedList.sol
  packages/protocol/contracts/common/test/LinkedListTest.sol
  packages/protocol/migrationsConfig.js
  packages/protocol/test/common/linkedlist.ts
Labels: automerge

#1021 [Wallet] Differentiate dollars and gold transactions
  packages/mobile/locales/en-US/exchangeFlow9.json
  packages/mobile/locales/es-419/exchangeFlow9.json
  packages/mobile/src/exchange/ExchangeHomeScreen.tsx
  packages/mobile/src/transactions/ExchangeFeedItem.test.tsx
  packages/mobile/src/transactions/ExchangeFeedItem.tsx
  packages/mobile/src/transactions/TransactionFeed.tsx
  packages/mobile/src/transactions/TransferFeedItem.test.tsx
  packages/mobile/src/transactions/TransferFeedItem.tsx
  packages/mobile/src/transactions/__snapshots__/ExchangeFeedItem.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransactionFeed.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransferFeedItem.test.tsx.snap
Labels: automerge

#1016 Persistent disks for transaction nodes
  .env
  .env.alfajores
  .env.alfajoresstaging
  .env.integration
  .env.pilot
  .env.pilotstaging
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/helm-charts/testnet/templates/txnode.statefulset.yaml
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
Labels: automerge

#984 Remove unused Reserve.burnToken function
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/contracts/stability/interfaces/IReserve.sol
Labels: automerge

#942 [cli] Check if node is synced
  packages/cli/src/base.ts
  packages/cli/src/commands/account/new.ts
  packages/cli/src/commands/account/transferdollar.ts
  packages/cli/src/commands/config/get.ts
  packages/cli/src/commands/config/set.ts
  packages/cli/src/commands/node/accounts.ts
  packages/cli/src/commands/node/synced.ts
  packages/cli/src/utils/helpers.ts
  packages/docs/command-line-interface/node.md
Labels: cli, vx

#1034 Add infura-like ingress
  packages/helm-charts/testnet/templates/infura.ingress.yaml
Labels: automerge

#1049 fixes for the testnet stateful sets
  packages/helm-charts/testnet/templates/txnode.statefulset.yaml
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
Labels: automerge

#949 Add word "Venture" to ecofund name
  packages/web/static/locales/en/community.json
Labels: automerge

#1030 Reimplement Fixidity division
  packages/protocol/contracts/common/FixidityLib.sol
  packages/protocol/test/common/fixidity.ts
Labels: automerge

#1028 Add CLI command to check if address is a validator
  packages/cli/src/commands/account/isvalidator.ts
  packages/contractkit/src/wrappers/Validators.ts
Labels: automerge

#798 [WIP][ContractKit]Add ability to do local signing
  packages/contractkit/src/kit.ts
  packages/contractkit/src/providers/celo-private-keys-subprovider.ts
  packages/contractkit/src/providers/celo-provider.ts
  packages/contractkit/src/providers/wrapping-subprovider.ts
  packages/contractkit/src/test-utils/ganache.setup.ts
  packages/contractkit/src/utils/tx-signing.test.ts
  packages/contractkit/src/utils/tx-signing.ts
  packages/contractkit/src/utils/web3-utils.ts
Labels: automerge

#1056 Update CLI docs
  packages/docs/command-line-interface/account.md
Labels: automerge

#1053 Add command to output validator set
  packages/cli/src/commands/validatorset.ts
  packages/contractkit/src/wrappers/Validators.ts
  packages/docs/command-line-interface/validatorset.md
Labels: automerge

#904 Community Page Loading +
  packages/web/server/mediumAPI.ts
  packages/web/src/community/Articles.tsx
  packages/web/src/community/connect/ArticleData.tsx
  packages/web/src/community/connect/ArticlesSection.tsx
  packages/web/src/community/connect/ConnectPage.tsx
  packages/web/src/community/connect/Contribute.tsx
  packages/web/src/community/connect/Events.tsx
  packages/web/src/community/connect/FellowSection.tsx
Labels: automerge

#1019 ContractKit Attestations Wrapper
  packages/celotool/package.json
  packages/celotool/src/cmds/account/lookup.ts
  packages/celotool/src/cmds/account/verify.ts
  packages/contractkit/src/wrappers/Attestations.ts
  packages/contractkit/src/wrappers/BaseWrapper.ts
  packages/contractkit/types/web3-utils.d.ts
  packages/utils/src/collections.ts
Labels: automerge

#1014 Added a public method to LockedGold to check if an account exists
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/protocol/contracts/governance/LockedGold.sol
  packages/protocol/test/governance/bondeddeposits.ts
Labels: automerge

#1033 Shuffle elected validators using block randomness
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/contracts/identity/test/MockRandom.sol
  packages/protocol/runTests.js
  packages/protocol/test/governance/validators.ts
  packages/protocol/truffle.js
Labels: automerge

#430 Add Quorum and Refactor Governance
  packages/protocol/contracts/common/FixidityLib.sol
  packages/protocol/contracts/common/FractionUtil.sol
  packages/protocol/contracts/common/test/FixidityTest.sol
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/governance/Proposals.sol
  packages/protocol/contracts/governance/UsingLockedGold.sol
  packages/protocol/contracts/governance/interfaces/IGovernance.sol
  packages/protocol/contracts/governance/interfaces/ILockedGold.sol
  packages/protocol/contracts/governance/test/MockLockedGold.sol
  packages/protocol/contracts/governance/test/ProposalsTest.sol
  packages/protocol/migrations/15_governance.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/scripts/python/checkBytecodeLen.py
  packages/protocol/test/common/integration.ts
  packages/protocol/test/governance/governance.ts
  packages/protocol/test/governance/proposals.ts
  packages/protocol/truffle.js
  yarn.lock
Labels: automerge, protocol

#1070 [CLI]Unlock till the geth exits
  packages/cli/src/commands/account/unlock.ts
Labels: automerge

#1084 Fix governance unit tests
  packages/protocol/test/governance/governance.ts
Labels: automerge

#1035 Group size limit
  packages/contractkit/src/wrappers/BaseWrapper.ts
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/migrations/11_validators.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/scripts/devchain.ts
  packages/protocol/test/governance/validators.ts
Labels: automerge

#1086 [celotool]Store .env config on GCS after deployment
  packages/celotool/src/cmds/deploy/initial/testnet.ts
  packages/celotool/src/cmds/deploy/upgrade/testnet.ts
  packages/celotool/src/lib/testnet-utils.ts
  packages/celotool/src/lib/utils.ts
  packages/celotool/src/lib/vm-testnet-utils.ts
Labels: automerge

#1068 Return to preview view when Fee Education is closed
  packages/mobile/src/navigator/Navigator.tsx
Labels: automerge

#1082 Exclude generated in vscode file watcher setting
  .vscode/settings.json
Labels: automerge

#1096 Fix blockscout websocket jsonrpc url env name
  packages/helm-charts/blockscout/templates/_helpers.tpl
Labels: automerge

#885 Allow validators to use any valid combination of gold commitments as stake
  packages/cli/src/commands/validator/register.ts
  packages/cli/src/commands/validatorgroup/register.ts
  packages/docs/command-line-interface/validator.md
  packages/docs/command-line-interface/validatorgroup.md
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/migrations/16_elect_validators.ts
  packages/protocol/test/governance/validators.ts
Labels: automerge

#1103 Add MetadataURL to account struct
  packages/protocol/contracts/identity/Attestations.sol
  packages/protocol/contracts/identity/interfaces/IAttestations.sol
  packages/protocol/test/identity/attestations.ts
Labels: automerge

#1050 Remove locales as website is now just in English
  packages/web/src/i18n.ts
  packages/web/static/locales/de/about.json
  packages/web/static/locales/de/applications.json
  packages/web/static/locales/de/common.json
  packages/web/static/locales/de/community.json
  packages/web/static/locales/de/home.json
  packages/web/static/locales/de/jobs.json
  packages/web/static/locales/de/technology.json
  packages/web/static/locales/es/about.json
  packages/web/static/locales/es/applications.json
  packages/web/static/locales/es/common.json
  packages/web/static/locales/es/community.json
  packages/web/static/locales/es/home.json
  packages/web/static/locales/es/jobs.json
  packages/web/static/locales/es/technology.json
  packages/web/static/locales/zh/about.json
  packages/web/static/locales/zh/applications.json
  packages/web/static/locales/zh/common.json
  packages/web/static/locales/zh/community.json
  packages/web/static/locales/zh/home.json
  packages/web/static/locales/zh/jobs.json
  packages/web/static/locales/zh/technology.json
Labels: automerge

#1088 Fix celotool dockerfile
  dockerfiles/celotool/Dockerfile
Labels: automerge

#1109 changes for the in memory discovery table
  .env
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/helm-charts/testnet/templates/txnode.statefulset.yaml
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
Labels: automerge

#1095 Updates Events to Pull from AirTable rather than Google Sheet
  packages/web/fullstack/EcoFundFields.ts
  packages/web/fullstack/EventProps.ts
  packages/web/package.json
  packages/web/server-env-config.js.enc
  packages/web/server/Announcement.ts
  packages/web/server/EventHelpers.test.ts
  packages/web/server/EventHelpers.ts
  packages/web/server/addToCRM.ts
  packages/web/server/airtable.ts
  packages/web/server/index.ts
  packages/web/src/community/connect/EventRow.tsx
  packages/web/src/shared/PlaceDate.tsx
  yarn.lock
Labels: automerge

#1031 Aaronmgdr/web phone
  packages/web/.babelrc
  packages/web/package.json
  packages/web/src/dev/Title.tsx
  packages/web/src/download/AppStores.tsx
  packages/web/src/download/Cover.tsx
  packages/web/src/download/MobileApp.tsx
  packages/web/src/fauceting/MicroComponents.tsx
  packages/web/src/fauceting/PhoneInput.tsx
  packages/web/src/fauceting/RequestFunds.tsx
  packages/web/src/fauceting/utils.ts
  packages/web/static/locales/en/faucet.json
  yarn.lock
Labels: automerge

#1112 changes for integration
  .env
  .env.integration
  packages/protocol/migrationsConfig.js
Labels: automerge

#1121 alfajores staging deployment
  .env.alfajoresstaging
Labels: automerge

#1041 [cli] show network parameters 782
  packages/cli/src/commands/network/parameters.ts
  packages/cli/src/utils/cli.ts
  packages/contractkit/src/contract-cache.ts
  packages/contractkit/src/kit.ts
  packages/contractkit/src/wrappers/Attestations.ts
  packages/contractkit/src/wrappers/Exchange.ts
  packages/contractkit/src/wrappers/GasPriceMinimum.ts
  packages/contractkit/src/wrappers/GoldTokenWrapper.ts
  packages/contractkit/src/wrappers/Governance.ts
  packages/contractkit/src/wrappers/LockedGold.ts
  packages/contractkit/src/wrappers/Reserve.ts
  packages/contractkit/src/wrappers/SortedOracles.ts
  packages/contractkit/src/wrappers/StableTokenWrapper.ts
  packages/contractkit/src/wrappers/Validators.ts
  packages/docs/command-line-interface/network.md
Labels: automerge

#1113 [Wallet] Merge back changes made for mx pilot
  packages/mobile/.env
  packages/mobile/.env.pilot
  packages/mobile/.env.pilotstaging
  packages/mobile/.env.production
  packages/mobile/.env.staging
  packages/mobile/.env.test
  packages/mobile/__mocks__/country-data.ts
  packages/mobile/android/gradle.properties
  packages/mobile/fastlane/metadata/android/es-419/full_description.txt
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/es-419/nuxVerification2.json
  packages/mobile/locales/es-419/sendFlow7.json
  packages/mobile/package.json
  packages/mobile/src/account/__snapshots__/InviteReview.test.tsx.snap
  packages/mobile/src/backup/BackupComplete.tsx
  packages/mobile/src/backup/BackupPhrase.tsx
  packages/mobile/src/backup/__snapshots__/Backup.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupComplete.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupPhrase.test.tsx.snap
  packages/mobile/src/backup/utils.ts
  packages/mobile/src/components/LineItemRow.tsx
  packages/mobile/src/escrow/ReclaimPaymentConfirmationScreen.test.tsx
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationCard.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationScreen.test.tsx.snap
  packages/mobile/src/home/CeloDollarsOverview.tsx
  packages/mobile/src/invite/__snapshots__/JoinCelo.test.tsx.snap
  packages/mobile/src/localCurrency/convert.test.ts
  packages/mobile/src/localCurrency/convert.ts
  packages/mobile/src/localCurrency/hooks.ts
  packages/mobile/src/localCurrency/selectors.ts
  packages/mobile/src/localCurrency/useLocalAmount.ts
  packages/mobile/src/paymentRequest/PaymentRequestReviewCard.tsx
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestConfirmation.test.tsx.snap
  packages/mobile/src/qrcode/QRScanner.tsx
  packages/mobile/src/send/SendAmount.test.tsx
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/TransferReviewCard.tsx
  packages/mobile/src/send/__snapshots__/SendAmount.test.tsx.snap
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/send/__snapshots__/TransferConfirmationCard.test.tsx.snap
  packages/mobile/src/send/__snapshots__/TransferReviewCard.test.tsx.snap
  packages/mobile/src/transactions/ExchangeFeedItem.tsx
  packages/mobile/src/transactions/TransferFeedItem.tsx
  packages/protocol/scripts/truffle/invite.ts
  packages/react-components/components/MoneyAmount.tsx
  packages/react-components/styles/colors.tsx
  packages/utils/src/collections.ts
  packages/utils/src/countries.ts
  packages/utils/src/inputValidation.test.ts
  yarn.lock
Labels: automerge

#960 [cli] Solution for build error contractkit on Linux 19.04 distro
  packages/cli/README.md
  packages/protocol/.solcover.js
  packages/protocol/README.md
  packages/protocol/migrations/07_reserve.ts
  packages/protocol/migrations/08_stabletoken.ts
  packages/protocol/migrations/15_governance.ts
  packages/protocol/runTests.js
  packages/protocol/scripts/bash/set_exchange_rate.sh
  packages/protocol/scripts/truffle/get_balances.ts
  packages/protocol/scripts/truffle/invite.ts
  packages/protocol/scripts/truffle/network_check.ts
  packages/protocol/scripts/truffle/revoke.ts
  packages/protocol/scripts/truffle/set_exchange_rate.ts
  packages/protocol/scripts/truffle/transfer.ts
  packages/protocol/truffle-config.js
Labels: automerge

#1115 Enable floating promises check everywhere (fix issues)
  package.json
  packages/celotool/src/lib/cloud-storage.ts
  packages/contractkit/src/providers/celo-private-keys-subprovider.ts
  packages/faucet/src/database-helper.ts
  packages/faucet/src/test-driver.ts
  packages/mobile/tslint.json
  packages/notification-service/src/exchange/exchangeQuery.ts
  packages/react-components/analytics/CeloAnalytics.tsx
  packages/typescript/package.json
  packages/typescript/tslint.json
  packages/verifier/src/App.tsx
  packages/verifier/src/components/HomeScreen/Activity.tsx
  packages/verifier/src/components/HomeScreen/HomeScreen.tsx
  packages/verifier/src/components/NUX/SetupAccountScreen.tsx
  packages/verifier/src/services/Apollo.ts
  packages/verifier/src/services/FirebaseDb.ts
  yarn.lock
Labels: automerge

#1122 Deploying latest proxy code in genesis
  packages/celotool/src/lib/generate_utils.ts
  packages/celotool/src/lib/genesis_constants.ts
Labels: automerge

#1117 Add instructions for npm publication to tag commit
  README-dev.md
Labels: automerge

#1139 integration deployment for 2019-09-29
  .env.integration
Labels: automerge

#1003 Feature/909 proxy delegatecall
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/protocol/contracts/common/MultiSig.sol
  packages/protocol/contracts/common/Proxy.sol
  packages/protocol/contracts/common/libraries/AddressesHelper.sol
  packages/protocol/contracts/governance/Proposals.sol
  packages/protocol/test/common/proxy.ts
  packages/protocol/test/governance/governance.ts
Labels: automerge
