Repository celo-org/celo-monorepo, pull requests merged in 2019-12, with the labels that each got.

#1953 Small pre-stake-off CLI cleanup
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/celotool/src/e2e-tests/sync_tests.ts
  packages/cli/src/commands/account/show.ts
  packages/cli/src/commands/election/show.ts
  packages/cli/src/commands/election/vote.ts
  packages/cli/src/commands/lockedgold/unlock.ts
  packages/cli/src/utils/checks.ts
  packages/contractkit/src/wrappers/Election.ts
  packages/docs/command-line-interface/election.md
  packages/docs/command-line-interface/introduction.md
  packages/docs/getting-started/running-a-validator.md
  packages/protocol/migrationsConfig.js
  packages/utils/src/signatureUtils.ts
Labels: automerge, betanet-blocker

#1950 Specify web deps properly
  packages/web/package.json
  packages/web/src/about/team/team-list.ts
Labels: automerge

#1994 Only allow external RPCs for tx nodes
  packages/terraform-modules/testnet/main.tf
  packages/terraform-modules/testnet/modules/tx-node/main.tf
  packages/terraform-modules/testnet/modules/validator/main.tf
Labels: automerge

#1851 Attestation Bot POC
  packages/celotool/src/cmds/account/verify.ts
  packages/celotool/src/cmds/bots.ts
  packages/celotool/src/cmds/bots/auto-verify.ts
  packages/celotool/src/cmds/deploy/destroy/attestation-bot.ts
  packages/celotool/src/cmds/deploy/initial/attestation-bot.ts
  packages/celotool/src/cmds/deploy/upgrade/attestation-bot.ts
  packages/celotool/src/lib/attestation-bot.ts
  packages/celotool/src/lib/attestation.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/twilio.ts
  packages/helm-charts/attestation-bot/Chart.yaml
  packages/helm-charts/attestation-bot/templates/configmap.yaml
  packages/helm-charts/attestation-bot/templates/deployment.yaml
  packages/helm-charts/attestation-bot/templates/secret.yaml
  packages/helm-charts/attestation-bot/values.yaml
Labels: automerge

#1999 Set default env in attestation service docker image as production
  dockerfiles/attestation-service/Dockerfile
Labels: automerge

#1997 expose signer through getValidator
  packages/contractkit/src/wrappers/Validators.ts
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/test/governance/validators.ts
Labels: betanet-blocker

#1965 DOCS correct typos
  packages/docs/getting-started/alfajores-testnet.md
  packages/docs/getting-started/faucet.md
  packages/docs/getting-started/using-the-mobile-wallet.md
Labels: automerge

#2000 Update docker image and instructions
  packages/docs/getting-started/running-attestation-service.md
Labels: automerge

#1993 Touchups for Stakeoff Leaderboard
  packages/web/env-config.js.enc
  packages/web/src/dev/Cover.tsx
  packages/web/src/dev/Engage.tsx
  packages/web/src/dev/FullStack.tsx
  packages/web/src/dev/LeaderBoard.tsx
  packages/web/src/dev/LeaderBoardApp.tsx
  packages/web/src/dev/SDK.png
  packages/web/src/dev/devEvents.png
  packages/web/src/dev/devNews.png
  packages/web/src/dev/features/custody.png
  packages/web/src/dev/features/evm.png
  packages/web/src/dev/features/gas.png
  packages/web/src/dev/features/gov.png
  packages/web/src/dev/features/pki.png
  packages/web/src/dev/features/stable.png
  packages/web/src/dev/features/stake.png
  packages/web/src/dev/features/ultra.png
  packages/web/src/home/HomeSystems.tsx
  packages/web/src/icons/chevron.tsx
  packages/web/src/join/Benefits.tsx
  packages/web/src/shared/menu-items.ts
  packages/web/static/locales/en/dev.json
Labels: automerge, betanet-blocker

#1934 Collecting more Validator UX improvements
  packages/docs/getting-started/baklava-testnet.md
  packages/docs/getting-started/running-a-validator.md
  scripts/run-docker-validator-network.sh
  scripts/validator-config.rc
Labels: betanet-blocker

#2001 Display signer in getValidator contrackit wrapper + cli commands
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/cli/src/commands/election/current.ts
  packages/cli/src/commands/election/run.ts
  packages/cli/src/commands/validator/list.ts
  packages/contractkit/package.json
  packages/contractkit/src/wrappers/Validators.ts
  packages/mobile/package.json
Labels: automerge

#2021 Rename to eventName
  packages/transaction-metrics-exporter/src/blockchain.ts
Labels: automerge

#2013 Latest integration deploy
  .env
  .env.integration
  .env.mnemonic.enc
  .env.mnemonic.integration.enc
  packages/celotool/src/cmds/deploy/upgrade/all.ts
  packages/transaction-metrics-exporter/package.json
  yarn.lock
Labels: automerge

#2024 Reformat the glossary to follow Gitbook guidelines
  packages/docs/getting-started/glossary.md
Labels: docs

#2023 Use public bootnode image in .env
  .env
  packages/helm-charts/attestation-service/charts/postgresql-6.3.10.tgz
  packages/helm-charts/cert-manager-cluster-issuers/charts/cert-manager-v0.11.0.tgz
  packages/helm-charts/load-test/charts/common-0.0.1.tgz
  packages/helm-charts/testnet/values.yaml
Labels: automerge

#1943 gold and dollar flags are required for faucet script
  packages/celotool/README.md
  packages/celotool/src/cmds/account/faucet.ts
Labels: automerge, celotool

#2019 Allocates an initial balance to the attestation bot
  packages/celotool/src/lib/generate_utils.ts
  packages/celotool/src/lib/migration-utils.ts
Labels: automerge

#2027 Fix broken links and spruce up CLI docs for accounts command
  packages/cli/src/commands/account/claim-account.ts
  packages/cli/src/commands/account/claim-attestation-service-url.ts
  packages/cli/src/commands/account/claim-domain.ts
  packages/cli/src/commands/account/claim-keybase.ts
  packages/cli/src/commands/account/claim-name.ts
  packages/cli/src/commands/account/create-metadata.ts
  packages/cli/src/commands/account/get-metadata.ts
  packages/cli/src/commands/account/register-metadata.ts
  packages/docs/README.md
  packages/docs/SUMMARY.md
  packages/docs/celo-codebase/protocol/identity/README.md
  packages/docs/celo-codebase/protocol/proof-of-stake/README.md
  packages/docs/celo-codebase/protocol/proof-of-stake/community-fund.md
  packages/docs/celo-codebase/protocol/proof-of-stake/epoch-rewards.md
  packages/docs/celo-codebase/protocol/proof-of-stake/locked-gold.md
  packages/docs/command-line-interface/account.md
  packages/docs/command-line-interface/introduction.md
  packages/docs/getting-started/alfajores-testnet.md
  packages/docs/getting-started/running-attestation-service.md
  packages/docs/getting-started/using-the-wallet.md
Labels: automerge

#2045 [Docs] Fix typos in Running a Validator docs
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#2025 changes to docs related to discovery
  packages/docs/celo-codebase/protocol/consensus/locating-nodes.md
  packages/docs/celo-codebase/protocol/consensus/locating-validators.md
Labels: automerge

#2052 Point To Updated Join Celo Video
  packages/web/src/join/FeaturedVideo.tsx
Labels: automerge

#2051 Move attestation service instructions to main page
  packages/docs/SUMMARY.md
  packages/docs/celo-codebase/protocol/consensus/locating-nodes.md
  packages/docs/celo-codebase/protocol/identity/metadata.md
  packages/docs/celo-codebase/protocol/proof-of-stake/carbon-offsetting-fund.md
  packages/docs/celo-codebase/protocol/proof-of-stake/locked-gold-rewards.md
  packages/docs/celo-codebase/protocol/proof-of-stake/penalties.md
  packages/docs/celo-codebase/protocol/proof-of-stake/validator-elections.md
  packages/docs/celo-codebase/protocol/proof-of-stake/validator-groups.md
  packages/docs/celo-codebase/protocol/proof-of-stake/validator-rewards.md
  packages/docs/getting-started/running-a-validator.md
  packages/docs/getting-started/running-attestation-service.md
Labels: automerge

#2055 Aaronmgdr/leaderboard patch
  packages/web/flags.js
  packages/web/src/dev/LeaderBoard.tsx
  packages/web/src/dev/LeaderBoardApp.tsx
Labels: automerge

#1828 Allow a specified address to disable/enable rewards distribution
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/protocol/contracts/governance/EpochRewards.sol
  packages/protocol/migrations/14_epoch_rewards.ts
  packages/protocol/test/governance/epochrewards.ts
Labels: automerge

#2057 Fix additional attestations instructions
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#2065 Adjust reference to the rewards app
  packages/web/src/privacy/FAQ.tsx
Labels: automerge

#2081 Add dev-utils README
  packages/dev-utils/README.md
Labels: automerge

#2068 Improvements to faucet for stake-off, fix celotool env check
  packages/celotool/src/cmds/account/faucet.ts
  packages/celotool/src/lib/artifacts.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/helm_deploy.ts
Labels: automerge

#2072 Fix potential hard timeouts
  packages/web/server-env-config.js.enc
  packages/web/server/EventHelpers.ts
  packages/web/server/index.ts
  packages/web/src/utils/abortableFetch.ts
Labels: automerge

#2018 Attestation Bot operational improvements
  .env
  packages/celotool/package.json
  packages/celotool/src/cmds/bots/auto-verify.ts
  packages/celotool/src/cmds/deploy/initial/contracts.ts
  packages/celotool/src/lib/attestation-bot.ts
  packages/celotool/src/lib/attestation.ts
  packages/celotool/src/lib/env-utils.ts
  packages/contractkit/src/wrappers/Attestations.ts
  packages/helm-charts/attestation-bot/templates/deployment.yaml
  packages/helm-charts/attestation-bot/templates/secret.yaml
  packages/helm-charts/attestation-service/templates/attestation.statefulset.yaml
Labels: automerge

#1798 Test that events that are emitted during block finalization are included in the blocks
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/contracts/governance/EpochRewards.sol
  packages/protocol/contracts/governance/Validators.sol
Labels: automerge

#2028 WIP: Making Twilio the default provider in the attestation service
  README.md
  packages/docs/getting-started/running-a-validator.md
  scripts/run-docker-validator-network.sh
Labels: automerge

#2064 Use forno urls everywhere
  packages/blockchain-api/.env
  packages/blockchain-api/app.alfajores.yaml
  packages/blockchain-api/app.alfajoresstaging.yaml
  packages/blockchain-api/app.integration.yaml
  packages/blockchain-api/app.pilot.yaml
  packages/blockchain-api/app.pilotstaging.yaml
  packages/mobile/README.md
  packages/mobile/src/config.ts
  packages/notification-service/config/config.alfajores.env
  packages/notification-service/config/config.alfajoresstaging.env
  packages/notification-service/config/config.integration.env
  packages/notification-service/config/config.local.env
  packages/notification-service/config/config.pilot.env
  packages/notification-service/config/config.pilotstaging.env
  packages/notification-service/config/config.test.env
Labels: automerge

#2082 Rearrange functions to avoid circular dependency
  packages/cli/src/utils/identity.ts
  packages/contractkit/src/identity/claims/account.test.ts
  packages/contractkit/src/identity/claims/claim.ts
  packages/contractkit/src/identity/claims/verify.ts
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#2102 docs: removes sleep from commands
  packages/docs/getting-started/running-a-full-node.md
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#1992 Don't build docs or web in CI
  .circleci/config.yml
Labels: automerge

#2106 Provide an endpoint that can accept POST requests
  packages/celotool/src/lib/attestation.ts
Labels: automerge

#2110 Docs SBAT specify the correct proxy ip address and port
  packages/docs/getting-started/running-a-validator.md
Labels: automerge, docs

#2113 Document the need to counter-claim accounts
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#2117 Making $HOME/.celo the default temporary folder
  scripts/run-docker-validator-network.sh
Labels: automerge

#2105 Add more logging to the attestation bot
  packages/celotool/src/cmds/bots/auto-verify.ts
  packages/celotool/src/lib/attestation.ts
  packages/contractkit/src/wrappers/Attestations.ts
Labels: automerge

#2103 Test that reserve receives epoch rewards
  packages/celotool/src/e2e-tests/governance_tests.ts
Labels: automerge

#2070 Reduce intrinsic gas cost for txs paying fees in alternative currencies
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/protocol/migrationsConfig.js
Labels: automerge

#2077 Add prettier for java
  .prettierignore
  eclipse-formatter.xml
  package.json
  packages/mobile/android/app/src/androidTest/java/org/celo/mobile/DetoxTest.java
  packages/mobile/android/app/src/main/java/org/celo/mobile/MainActivity.java
  packages/mobile/android/app/src/main/java/org/celo/mobile/MainApplication.java
  packages/mobile/android/app/src/main/java/org/celo/mobile/NdkCrashService.java
  packages/verifier/android/app/src/main/java/org/celo/verifier/MainActivity.java
  packages/verifier/android/app/src/main/java/org/celo/verifier/MainApplication.java
  packages/verifier/android/app/src/main/java/org/celo/verifier/MessageState.java
  packages/verifier/android/app/src/main/java/org/celo/verifier/PushNotificationToSMSService.java
  packages/verifier/android/app/src/main/java/org/celo/verifier/RNVerifierServiceModule.java
  packages/verifier/android/app/src/main/java/org/celo/verifier/RNVerifierServicePackage.java
  packages/verifier/android/app/src/main/java/org/celo/verifier/SMSLog.java
  packages/verifier/android/app/src/main/java/org/celo/verifier/SMSMessage.java
  packages/verifier/android/app/src/main/java/org/celo/verifier/SMSResponse.java
  packages/verifier/android/app/src/main/java/org/celo/verifier/SMSStatusBroadcastReceiver.java
  yarn.lock
Labels: automerge

#1649 Verifier release build and remove some unused env variables
  .env
  .env.alfajores
  .env.alfajoresstaging
  .env.integration
  .env.integrationtesting
  .env.pilot
  .env.pilotstaging
  packages/celotool/src/lib/env-utils.ts
  packages/mobile/android/app/src/pilot/res/values/strings.xml
  packages/mobile/src/config.ts
  packages/verifier/.env
  packages/verifier/.env.integration
  packages/verifier/.env.production
  packages/verifier/.env.staging
  packages/verifier/android/app/build.gradle
  packages/verifier/android/app/src/debug/AndroidManifest.xml
  packages/verifier/src/utils/config.ts
Labels: automerge

#2128 [Wallet] Fix cancel button position on some verification screens on iOS
  packages/mobile/ios/Podfile.lock
  packages/mobile/src/verify/VerificationInputScreen.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationInputScreen.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/VerificationLoadingScreen.test.tsx.snap
Labels: automerge

#2074 Deploy to integration
  .env.integration
Labels: automerge

#2091 Use vanity docker image
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#1949 Update glossary.md
  packages/docs/getting-started/glossary.md
Labels: automerge

#2114 Deploy CLI 0.0.30-beta9 and ContractKit 0.2.7
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/contractkit/src/identity/claims/account.test.ts
  packages/contractkit/src/identity/claims/account.ts
  packages/mobile/package.json
Labels: automerge

#2121 Update Testnet Disclaimers
  packages/docs/important-information/alfajores-testnet-disclaimer.md
  packages/docs/important-information/baklava-testnet-disclaimer.md
Labels: docs

#2137 Adjust blockscout indexer memory and CPU
  packages/helm-charts/blockscout/templates/blockscout-indexer.deployment.yaml
Labels: automerge

#2109 Heading Style Fixes
  packages/web/src/about/Team.tsx
  packages/web/src/brandkit/Color.tsx
  packages/web/src/brandkit/IconsPage.tsx
  packages/web/src/brandkit/Intro.tsx
  packages/web/src/brandkit/Logo.tsx
  packages/web/src/brandkit/Typography.tsx
  packages/web/src/brandkit/color/Palette.tsx
  packages/web/src/brandkit/common/MobileMenu.tsx
  packages/web/src/brandkit/typography/UseageExample.tsx
  packages/web/src/community/EcoFund.tsx
  packages/web/src/community/connect/EventRow.tsx
  packages/web/src/community/connect/Events.tsx
  packages/web/src/community/connect/Fellow.tsx
  packages/web/src/dev/Engage.tsx
  packages/web/src/dev/Feature.tsx
  packages/web/src/dev/StackSection.tsx
  packages/web/src/fauceting/MicroComponents.tsx
  packages/web/src/fauceting/RequestFunds.tsx
  packages/web/src/forms/EmailForm.tsx
  packages/web/src/forms/FormComponents.tsx
  packages/web/src/home/version3/HomeCover.tsx
  packages/web/src/home/version3/HomeEmail.tsx
  packages/web/src/jobs/version3/JobRows.tsx
  packages/web/src/jobs/version3/Jobs.tsx
  packages/web/src/privacy/Privacy.tsx
  packages/web/src/shared/Card.tsx
  packages/web/src/shared/SocialChannels.tsx
  packages/web/src/styles.ts
  packages/web/src/terms/Agreement.tsx
  packages/web/src/terms/StakeOffTerms.tsx
Labels: automerge

#2134 Redirect for stake off
  packages/web/server/index.ts
Labels: automerge

#2125 Testing sync again
  packages/cli/src/utils/helpers.ts
Labels: automerge

#2138 Leaderboard Improvements
  packages/web/src/dev/Cover.tsx
  packages/web/src/dev/LeaderBoard.tsx
  packages/web/src/dev/LeaderBoardApp.tsx
  packages/web/src/dev/Racer.tsx
  packages/web/src/shared/menu-items.ts
Labels: automerge

#2126 Fixing the cli for exchange
  packages/cli/src/commands/exchange/dollars.ts
  packages/cli/src/commands/exchange/gold.ts
  packages/cli/src/utils/command.ts
  packages/docs/command-line-interface/account.md
  packages/docs/command-line-interface/exchange.md
Labels: automerge

#2132 [NotificationService] Change exchange rate stored format (group by pair)
  packages/notification-service/__mocks__/@celo/contractkit.ts
  packages/notification-service/src/firebase.ts
Labels: automerge

#1810 Script for reading leaderboard data into database
  .env
  README.md
  cloudbuild.yaml
  dockerfiles/leaderboard/Dockerfile
  packages/celotool/src/cmds/deploy/destroy/leaderboard.ts
  packages/celotool/src/cmds/deploy/initial/leaderboard.ts
  packages/celotool/src/cmds/deploy/upgrade/leaderboard.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/leaderboard.ts
  packages/contractkit/src/identity/claims/verify.ts
  packages/docs/getting-started/running-a-validator.md
  packages/helm-charts/leaderboard/.helmignore
  packages/helm-charts/leaderboard/Chart.yaml
  packages/helm-charts/leaderboard/templates/leaderboard.cronjob.yaml
  packages/helm-charts/leaderboard/templates/leaderboard.secret.yaml
  packages/helm-charts/leaderboard/values.yaml
  packages/leaderboard/.gitignore
  packages/leaderboard/README.md
  packages/leaderboard/package.json
  packages/leaderboard/src/board.ts
  packages/leaderboard/tsconfig.json
  yarn.lock
Labels: automerge, betanet-blocker

#2092 Revert "Revert premature doc change"
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#2156 Updated leaderboard variables
  .env
  .env.mnemonic.baklava.enc
  packages/helm-charts/leaderboard/values.yaml
Labels: automerge

#2163 Fix typo of "Celo" in docs
  packages/docs/getting-started/baklava-testnet.md
Labels: automerge

#1707 Quickload for Homepage on low connectivity
  packages/web/package.json
  packages/web/src/about/VideoCover.tsx
  packages/web/src/header/BlueBanner.tsx
  packages/web/src/header/Header.3.tsx
  packages/web/src/home/HomeAnimation.tsx
  packages/web/src/home/HomeOracle.tsx
  packages/web/src/home/TextAnimation.tsx
  packages/web/src/home/version3/HomeCover.tsx
  packages/web/src/shared/Styles.tsx
  packages/web/src/utils/utils.ts
  yarn.lock
Labels: automerge

#2148 [cli] Exchange cleanup
  packages/cli/src/commands/account/set-name.ts
  packages/cli/src/commands/exchange/dollars.ts
  packages/cli/src/commands/exchange/gold.ts
  packages/docs/command-line-interface/account.md
  packages/docs/command-line-interface/exchange.md
Labels: automerge, cli

#2145 Make validator-exec work for different node types
  packages/celotool/src/cmds/ssh-vm-node.ts
  packages/celotool/src/cmds/validators-exec.ts
  packages/celotool/src/cmds/vm-exec.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/vm-testnet-utils.ts
Labels: automerge

#1933 Removing unused parts of LockedGold
  packages/protocol/contracts/governance/LockedGold.sol
Labels: automerge

#2165 Fixing cloudbuild - emoving whitespace that is causing gcloud builds to fail.
  cloudbuild.yaml
  packages/celotool/src/lib/leaderboard.ts
Labels: automerge

#2172 Clarify software requirements for local vs remote machines
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#2166 Allow the validator account to whitelist hotfixes
  packages/contractkit/src/wrappers/Election.ts
  packages/protocol/contracts/common/UsingPrecompiles.sol
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/governance/test/GovernanceTest.sol
  packages/protocol/contracts/identity/Attestations.sol
  packages/protocol/contracts/identity/test/TestAttestations.sol
  packages/protocol/test/governance/governance.ts
Labels: automerge

#2174 Use fluentd natively for structured logging
  .env
  packages/terraform-modules/testnet/modules/bootnode/startup.sh
  packages/terraform-modules/testnet/modules/full-node/startup.sh
  packages/terraform-modules/testnet/modules/tx-node-load-balancer/ssl-startup.sh
  packages/terraform-modules/testnet/modules/validator/startup.sh
Labels: automerge

#2173 Add Baklava phase 1.1 accounts to genesis block
  .env.baklava
  baklava_genesis_balances.json
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/generate_utils.ts
Labels: betanet-phase-1

#2179 Update documentation for Proxy IP addresses and ports
  packages/docs/getting-started/running-a-validator.md
Labels: betanet-phase-1

#2150 Fix/contractkit test flakyness
  packages/celotool/src/e2e-tests/utils.ts
  packages/contractkit/jest.config.js
  packages/contractkit/src/test-utils/AlphabeticSequencer.js
  packages/contractkit/src/test-utils/ganache.setup.ts
  packages/contractkit/src/wrappers/Accounts.test.ts
  packages/contractkit/src/wrappers/SortedOracles.test.ts
  packages/contractkit/src/wrappers/Validators.test.ts
  packages/dev-utils/src/network.ts
Labels: contractkit

#2176 VM monitoring, bigger VMs, persistent disks for full nodes, prom to sd for proxies
  packages/celotool/src/lib/prom-to-sd-utils.ts
  packages/celotool/src/lib/terraform.ts
  packages/celotool/src/lib/vm-testnet-utils.ts
  packages/terraform-modules/testnet/main.tf
  packages/terraform-modules/testnet/modules/bootnode/main.tf
  packages/terraform-modules/testnet/modules/bootnode/startup.sh
  packages/terraform-modules/testnet/modules/full-node/main.tf
  packages/terraform-modules/testnet/modules/full-node/startup.sh
  packages/terraform-modules/testnet/modules/full-node/variables.tf
  packages/terraform-modules/testnet/modules/tx-node-load-balancer/main.tf
  packages/terraform-modules/testnet/modules/validator/main.tf
  packages/terraform-modules/testnet/modules/validator/outputs.tf
  packages/terraform-modules/testnet/modules/validator/startup.sh
  packages/terraform-modules/testnet/outputs.tf
Labels: automerge

#2177 Add instructions for transitioning from phase 1.0 to phase 1.1
  .env.baklava
  packages/docs/getting-started/reconnecting-to-network.md
  packages/docs/getting-started/running-a-full-node.md
  packages/docs/getting-started/running-a-validator.md
  packages/protocol/truffle-config.js
  scripts/run-docker-validator-network.sh
  scripts/validator-config.rc
Labels: betanet-phase-1

#2195 Add attestation info for reconnecting
  packages/docs/getting-started/reconnecting-to-network.md
Labels: automerge

#2171 Changing validator group voting gold
  packages/protocol/migrations/20_elect_validators.ts
  packages/protocol/migrationsConfig.js
Labels: automerge, betanet-phase-1

#2205 Dont show this error for now
  packages/web/fullstack/sentry.ts
Labels: automerge

#2201 Overhaul readme
  README.md
Labels: automerge

#2189 Add /test_attestations endpoint on the attestation service
  packages/attestation-service/src/env.ts
  packages/attestation-service/src/index.ts
  packages/attestation-service/src/request.ts
  packages/attestation-service/src/requestHandlers/attestation.ts
  packages/attestation-service/src/requestHandlers/status.ts
  packages/attestation-service/src/requestHandlers/test_attestation.ts
  packages/cli/src/commands/identity/test-attestation-service.ts
  packages/cli/src/utils/checks.ts
  packages/cli/src/utils/command.ts
  packages/docs/command-line-interface/identity.md
  packages/utils/src/io.ts
Labels: automerge

#2194 Add Twilio and attestation bot envs
  .env.baklava
  .env.baklavastaging
  .env.mnemonic.baklava.enc
  .env.mnemonic.baklavastaging.enc
Labels: automerge

#2193 Indicate to run Twilio globally
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#2191 Check sync status of attestation service
  packages/attestation-service/src/db.ts
  packages/attestation-service/src/logger.ts
Labels: automerge

#2192 Support more than 1 attesation bot at a time
  .env
  .env.baklava
  .env.baklavastaging
  .env.integration
  packages/celotool/src/cmds/bots/auto-verify.ts
  packages/celotool/src/lib/migration-utils.ts
  packages/helm-charts/attestation-bot/templates/statefulset.yaml
Labels: automerge

#2211 Update walletkit gateway fee to fix transactions in forno mode
  packages/walletkit/src/contract-utils.ts
Labels: automerge

#2215 Minor baklava docs reconnection fixes
  packages/docs/getting-started/reconnecting-to-network.md
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#2207 Wait for only waitTime - 1 blocks
  packages/contractkit/src/wrappers/Attestations.ts
Labels: automerge

#2196 Upgrade TS version
  package.json
  packages/blockchain-api/package.json
  packages/celotool/src/cmds/deploy/upgrade/ethstats.ts
  packages/celotool/src/cmds/deploy/upgrade/leaderboard.ts
  packages/celotool/src/cmds/deploy/upgrade/testnet.ts
  packages/celotool/src/cmds/deploy/upgrade/vm-testnet.ts
  packages/cli/package.json
  packages/notification-service/package.json
  packages/react-components/analytics/wrapper.tsx
  packages/react-components/components/TextInput.tsx
  yarn.lock
Labels: automerge

#2209 Doc changes to address frequently asked questions
  packages/cli/src/commands/election/activate.ts
  packages/cli/src/utils/checks.ts
  packages/docs/SUMMARY.md
  packages/docs/celo-codebase/protocol/proof-of-stake/README.md
  packages/docs/command-line-interface/election.md
  packages/docs/getting-started/running-a-validator.md
  packages/docs/getting-started/using-the-wallet.md
Labels: automerge

#2212 Fix bignumber display in CLI
  packages/cli/package.json
  packages/cli/src/utils/cli.ts
Labels: automerge

#2155 Fix/protocol test flakyness
  .prettierignore
  packages/protocol/lib/test-utils.ts
  packages/protocol/runTests.js
  packages/protocol/test/baklava/freezable.ts
  packages/protocol/test/common/accounts.ts
  packages/protocol/test/common/gaspriceminimum.ts
  packages/protocol/test/common/linkedlist.ts
  packages/protocol/test/governance/blockchainparams.ts
  packages/protocol/test/governance/election.ts
  packages/protocol/test/governance/epochrewards.ts
  packages/protocol/test/governance/governance.ts
  packages/protocol/test/governance/lockedgold.ts
  packages/protocol/test/governance/validators.ts
  packages/protocol/test/identity/attestations.ts
  packages/protocol/test/identity/random.ts
  packages/protocol/test/stability/exchange.ts
  packages/protocol/test/stability/reserve.ts
  packages/protocol/test/stability/sortedoracles.ts
  packages/protocol/test/stability/stabletoken.ts
  packages/protocol/tsconfig.json
Labels: automerge, protocol

#2208 Improve reliability of e2e governance test
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/celotool/src/e2e-tests/utils.ts
Labels: automerge

#2130 Improvement facilitating to run a full node
  scripts/run-docker-validator-network.sh
Labels: automerge

#2182 Update documentation wrt. epoch rewards fractions
  packages/docs/celo-codebase/protocol/proof-of-stake/carbon-offsetting-fund.md
  packages/docs/celo-codebase/protocol/proof-of-stake/community-fund.md
Labels: betanet-phase-2

#2222 [Wallet] Fix crash on iOS when segment is enabled
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
Labels: automerge

#2204 [Wallet] Use Charles proxy to see eth JSON rpc calls when using forno
  packages/mobile/README.md
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/android/app/src/main/res/xml/network_security_config.xml
Labels: automerge

#2206 Remove walletkit from celotool transactions commands
  packages/celotool/src/cmds/transactions/describe.ts
  packages/celotool/src/cmds/transactions/list.ts
  packages/walletkit/index.ts
  packages/walletkit/src/abi.ts
Labels: automerge

#2200 Updates TME docker images
  .env
  .env.baklava
  .env.baklavastaging
  .env.integration
  packages/contractkit/src/explorer/log-explorer.ts
Labels: automerge

#2202 Update attestation service docker images
  .env
  .env.baklava
  .env.baklavastaging
  .env.integration
Labels: automerge

#2203 Upgrade Dependencies and get react hooks working
  packages/web/jest.config.js
  packages/web/package.json
  packages/web/src/brandkit/Color.tsx
  packages/web/src/brandkit/IconsPage.tsx
  packages/web/src/brandkit/KeyImagery.tsx
  packages/web/src/header/Header.3.tsx
  packages/web/src/home/version3/HomeWork.tsx
  packages/web/src/i18n.ts
  packages/web/src/next-i18next-aug.d.ts
  yarn.lock
Labels: automerge

#2225 [Docs] Fix typo
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#2226 Baklava phase 1.1 .env file
  .env.baklava
Labels: automerge

#2232 [Wallet] Refer to Celo Lite as "Data Saver" mode
  packages/mobile/README.md
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/locales/es-419/accountScreen10.json
  packages/mobile/src/account/Account.tsx
  packages/mobile/src/account/DataSaver.test.tsx
  packages/mobile/src/account/DataSaver.tsx
  packages/mobile/src/account/__snapshots__/Account.test.tsx.snap
  packages/mobile/src/account/__snapshots__/DataSaver.test.tsx.snap
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
Labels: automerge

#2229 adds Testing TSX /react on the web
  packages/web/jest.config.js
  packages/web/src/brandkit/common/DownloadButton.tsx
  packages/web/src/brandkit/tests/Showcase.test.tsx
  packages/web/src/brandkit/tests/__snapshots__/Showcase.test.tsx.snap
  packages/web/tsconfig.jest.json
Labels: automerge

#2249 [Wallet] Fix persisted data loss on iOS
  packages/mobile/index.js
  packages/mobile/src/apollo/index.ts
  packages/mobile/src/forceCommunityAsyncStorage.ts
Labels: automerge

#2271 Update Role on About Page
  packages/web/src/about/team/team-list.ts
Labels: automerge

#2167 [Wallet] New exchange trade screen and fix ts build in celotool
  packages/celotool/src/cmds/deploy/upgrade/all.ts
  packages/celotool/src/cmds/deploy/upgrade/blockscout.ts
  packages/mobile/locales/en-US/exchangeFlow9.json
  packages/mobile/locales/es-419/exchangeFlow9.json
  packages/mobile/src/account/__snapshots__/InviteReview.test.tsx.snap
  packages/mobile/src/components/FeeIcon.test.tsx
  packages/mobile/src/components/FeeIcon.tsx
  packages/mobile/src/components/Field.test.tsx
  packages/mobile/src/components/Field.tsx
  packages/mobile/src/components/__snapshots__/FeeIcon.test.tsx.snap
  packages/mobile/src/components/__snapshots__/Field.test.tsx.snap
  packages/mobile/src/escrow/ReclaimPaymentConfirmationCard.tsx
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationCard.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationScreen.test.tsx.snap
  packages/mobile/src/exchange/ExchangeConfirmationCard.tsx
  packages/mobile/src/exchange/ExchangeHomeScreen.tsx
  packages/mobile/src/exchange/ExchangeReview.test.tsx
  packages/mobile/src/exchange/ExchangeReview.tsx
  packages/mobile/src/exchange/ExchangeTradeScreen.test.tsx
  packages/mobile/src/exchange/ExchangeTradeScreen.tsx
  packages/mobile/src/exchange/FeeExchangeEducation.tsx
  packages/mobile/src/exchange/FeeExchangeIcon.tsx
  packages/mobile/src/exchange/__snapshots__/ExchangeConfirmationCard.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeReview.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/FeeExchangeEducation.test.tsx.snap
  packages/mobile/src/exchange/actions.ts
  packages/mobile/src/exchange/saga.ts
  packages/mobile/src/icons/InfoIcon.tsx
  packages/mobile/src/images/info-grey.png
  packages/mobile/src/navigator/Headers.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/send/FeeIcon.tsx
  packages/mobile/src/send/TransferReviewCard.tsx
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/send/__snapshots__/TransferReviewCard.test.tsx.snap
  packages/mobile/src/tokens/saga.ts
  packages/mobile/src/utils/currencyExchange.ts
Labels: automerge, wallet

#2257 Fix validatorgroup:list bug by not fetching unneeded info
  packages/contractkit/src/wrappers/Validators.ts
Labels: automerge

#2277 [Wallet] Fix non integer wei issue in exchange
  packages/mobile/src/exchange/Activity.tsx
  packages/mobile/src/exchange/ExchangeReview.tsx
  packages/mobile/src/exchange/saga.ts
  packages/mobile/src/transactions/TransactionFeed.tsx
Labels: automerge

#2096 Stop running broken end-to-end mobile test
  .circleci/config.yml
Labels: automerge

#2263 Fix/block gas limit exceeded #2
  packages/protocol/lib/web3-utils.ts
Labels: automerge, protocol

#2241 Adapting the script to the last documentation changes
  scripts/run-docker-validator-network.sh
  scripts/validator-config.rc
Labels: automerge

#1816 Audit fixes for Reserve
  packages/protocol/contracts/common/UsingRegistry.sol
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/contracts/governance/EpochRewards.sol
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/contracts/stability/interfaces/IReserve.sol
  packages/protocol/test/governance/epochrewards.ts
  packages/protocol/test/stability/reserve.ts
Labels: automerge

#2216 Update genesis value, show name in election:list, fix assertRevert
  baklava_genesis_balances.json
  packages/cli/src/commands/election/list.ts
  packages/contractkit/src/wrappers/Election.ts
  packages/contractkit/src/wrappers/Validators.test.ts
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/lib/test-utils.ts
  packages/protocol/test/governance/validators.ts
  packages/protocol/test/stability/reserve.ts
Labels: automerge

#2239 Adding slashing multiplier to validators.sol and reward calculation
  packages/dev-utils/src/ganache-setup.ts
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/contracts/governance/interfaces/IValidators.sol
  packages/protocol/contracts/governance/test/MockValidators.sol
  packages/protocol/migrations/12_validators.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/runTests.js
  packages/protocol/scripts/devchain.ts
  packages/protocol/test/governance/validators.ts
  packages/protocol/truffle-config.js
Labels: automerge

#2253 Update docs for stopping validator
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#2289 Upload bootnode info & use in docs instead of static nodes
  packages/celotool/src/cmds/deploy/initial/testnet.ts
  packages/celotool/src/lib/geth.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/celotool/src/lib/testnet-utils.ts
  packages/celotool/src/lib/vm-testnet-utils.ts
  packages/docs/getting-started/running-a-full-node.md
  packages/docs/getting-started/running-a-validator.md
  packages/terraform-modules/testnet/outputs.tf
Labels: automerge

#2296 [Wallet] Fix fail to sync issue
  packages/mobile/package.json
  yarn.lock
Labels: automerge

#2199 Upgrade web3 version in mobile, celotool, and walletkit
  packages/celotool/src/cmds/geth/trace.ts
  packages/celotool/src/cmds/geth/transfer.ts
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/celotool/src/lib/geth.ts
  packages/celotool/src/lib/transactions.ts
  packages/faucet/index.d.ts
  packages/faucet/src/protocol/signing-utils.ts
  packages/faucet/tsconfig.json
  packages/mobile/package.json
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/index.d.ts
  packages/mobile/src/web3/contracts.ts
  packages/protocol/index.d.ts
  packages/protocol/lib/signing-utils.ts
  packages/walletkit/package.json
  packages/walletkit/src/contract-utils-v2.ts
  packages/walletkit/src/contract-utils.ts
  packages/walletkit/src/index.d.ts
  packages/walletkit/src/new-web3-utils.ts
  packages/walletkit/src/transaction-utils.ts
  packages/walletkit/test/contract-utils-v2.test.ts
  yarn.lock
Labels: automerge

#2294 Reduce number of `@ts-ignore`
  packages/web/pages/_app.tsx
  packages/web/pages/_document.tsx
  packages/web/server/FellowshipApp.ts
  packages/web/src/about/Team.tsx
  packages/web/src/brandkit/common/Sidebar.tsx
  packages/web/src/community/EcoFund.tsx
  packages/web/src/community/connect/EventRow.tsx
  packages/web/src/community/connect/Events.tsx
  packages/web/src/community/connect/Tenets.tsx
  packages/web/src/dev/FullStack.tsx
  packages/web/src/forms/EmailSubscribeForm.tsx
  packages/web/src/forms/FormComponents.tsx
  packages/web/src/header/BlueBanner.tsx
  packages/web/src/header/Header.3.tsx
  packages/web/src/home/HomeCarousel.tsx
  packages/web/src/home/TextAnimation.tsx
  packages/web/src/react-native-aug.d.ts
  packages/web/src/shared/AspectRatio.tsx
  packages/web/src/shared/DropDown.tsx
  packages/web/src/shared/ResponsiveImage.tsx
  packages/web/src/shared/navigation.tsx
  packages/web/src/utils/utils.ts
  packages/web/tsconfig.json
Labels: automerge, web

#2178 Add fn groupMembershipInEpoch to validators.sol for slashing
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/test/governance/validators.ts
Labels: automerge

#2316 Remove dollar signs in bash cmds
  packages/docs/celo-codebase/protocol/identity/metadata.md
Labels: automerge

#2164 Bump @celo/utils to 0.1.5-dev
  .circleci/config.yml
  README-dev.md
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/mobile/package.json
  packages/notification-service/package.json
  packages/protocol/package.json
  packages/react-components/package.json
  packages/transaction-metrics-exporter/package.json
  packages/utils/package.json
  packages/verification-pool-api/package.json
  packages/verifier/package.json
  packages/walletkit/package.json
  packages/web/package.json
  yarn.lock
Labels: automerge

#2183 Ethstats variables as env variables
  .env
  .env.baklava
  .env.baklavastaging
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/ethstats.ts
  packages/helm-charts/ethstats/templates/ethstats.deployment.yaml
Labels: automerge

#2288 Various CLI improvements
  packages/cli/src/commands/account/unlock.ts
  packages/cli/src/commands/exchange/dollars.ts
  packages/cli/src/commands/exchange/gold.ts
  packages/docs/command-line-interface/account.md
  packages/docs/command-line-interface/exchange.md
Labels: automerge, betanet-phase-2

#2285 Add validator:status --all
  packages/cli/src/commands/validator/status.ts
  packages/docs/command-line-interface/validator.md
Labels: betanet-phase-2

#2326 [Wallet] Fix crash in release mode when navigating on iOS
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/verifier/package.json
  yarn.lock
Labels: automerge

#2319 [Wallet] Fix exchange input on iOS and feed item display
  packages/mobile/src/exchange/ExchangeTradeScreen.tsx
  packages/mobile/src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap
  packages/mobile/src/transactions/ExchangeFeedItem.tsx
  packages/mobile/src/transactions/__snapshots__/TransactionFeed.test.tsx.snap
Labels: automerge

#1182 Adding error messages to contracts
  packages/dev-utils/src/ganache-setup.ts
  packages/protocol/contracts/common/Accounts.sol
  packages/protocol/contracts/common/GasPriceMinimum.sol
  packages/protocol/contracts/common/MultiSig.sol
  packages/protocol/contracts/common/linkedlists/LinkedList.sol
  packages/protocol/contracts/common/linkedlists/SortedLinkedList.sol
  packages/protocol/contracts/common/linkedlists/SortedLinkedListWithMedian.sol
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/contracts/governance/EpochRewards.sol
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/governance/LockedGold.sol
  packages/protocol/contracts/governance/Proposals.sol
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/contracts/stability/SortedOracles.sol
  packages/protocol/contracts/stability/StableToken.sol
  packages/protocol/runTests.js
  packages/protocol/scripts/bash/ganache.sh
  packages/protocol/scripts/devchain.ts
  packages/protocol/truffle-config.js
Labels: audit, automerge

#2318 Add new and modified precompiles to UsingPrecompiles.sol
  .circleci/config.yml
  packages/protocol/contracts/common/UsingPrecompiles.sol
Labels: audit

#2139 Governance ContractKit + CLI changes
  packages/celotool/src/cmds/transactions/list.ts
  packages/cli/src/commands/governance/approve.ts
  packages/cli/src/commands/governance/approvehotfix.ts
  packages/cli/src/commands/governance/execute.ts
  packages/cli/src/commands/governance/executehotfix.ts
  packages/cli/src/commands/governance/preparehotfix.ts
  packages/cli/src/commands/governance/propose.ts
  packages/cli/src/commands/governance/upvote.ts
  packages/cli/src/commands/governance/vote.ts
  packages/cli/src/commands/governance/whitelisthotfix.ts
  packages/cli/src/utils/command.ts
  packages/cli/src/utils/governance.ts
  packages/contractkit/src/explorer/block-explorer.ts
  packages/contractkit/src/explorer/log-explorer.ts
  packages/contractkit/src/governance/index.ts
  packages/contractkit/src/governance/proposals.ts
  packages/contractkit/src/wrappers/Attestations.ts
  packages/contractkit/src/wrappers/BaseWrapper.ts
  packages/contractkit/src/wrappers/Election.ts
  packages/contractkit/src/wrappers/Exchange.ts
  packages/contractkit/src/wrappers/GasPriceMinimum.ts
  packages/contractkit/src/wrappers/GoldTokenWrapper.ts
  packages/contractkit/src/wrappers/Governance.test.ts
  packages/contractkit/src/wrappers/Governance.ts
  packages/contractkit/src/wrappers/LockedGold.test.ts
  packages/contractkit/src/wrappers/LockedGold.ts
  packages/contractkit/src/wrappers/Reserve.ts
  packages/contractkit/src/wrappers/SortedOracles.ts
  packages/contractkit/src/wrappers/StableToken.test.ts
  packages/contractkit/src/wrappers/StableTokenWrapper.ts
  packages/contractkit/src/wrappers/Validators.ts
  packages/dev-utils/src/ganache-test.ts
  packages/dev-utils/src/migration-override.json
  packages/docs/command-line-interface/governance.md
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/identity/commentKey.ts
  packages/mobile/src/import/saga.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/verify/VerificationCodeRow.tsx
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/migrations/08_stabletoken.ts
  packages/protocol/migrationsConfig.js
  packages/transaction-metrics-exporter/src/blockchain.ts
  packages/utils/src/address.ts
Labels: automerge, betanet-phase-2

#2142 Celotool command for deploying hotfixes
  packages/celotool/src/cmds/deploy/upgrade/hotfix.ts
  packages/contractkit/src/governance/proposals.ts
  packages/contractkit/src/governance/proxy.ts
  packages/contractkit/src/wrappers/Governance.ts
Labels: automerge, betanet-phase-2

#2160 cli: Add rewards:show
  packages/cli/src/base.ts
  packages/cli/src/commands/election/current.ts
  packages/cli/src/commands/election/list.ts
  packages/cli/src/commands/election/run.ts
  packages/cli/src/commands/oracle/rates.ts
  packages/cli/src/commands/rewards/show.ts
  packages/cli/src/commands/validator/list.ts
  packages/cli/src/commands/validatorgroup/list.ts
  packages/contractkit/src/kit.ts
  packages/contractkit/src/wrappers/Accounts.ts
  packages/contractkit/src/wrappers/BaseWrapper.ts
  packages/contractkit/src/wrappers/Election.ts
  packages/contractkit/src/wrappers/Validators.ts
  packages/docs/command-line-interface/rewards.md
  packages/docs/command-line-interface/validator.md
  packages/utils/src/async.ts
Labels: betanet-phase-2

#2339 Add infinite pagination to Leaderboard
  packages/web/src/dev/LeaderBoard.tsx
Labels: automerge

#1982 Limechain/16xx
  packages/protocol/contracts/common/GasPriceMinimum.sol
  packages/protocol/contracts/common/GoldToken.sol
  packages/protocol/contracts/common/MultiSig.sol
  packages/protocol/contracts/common/UsingRegistry.sol
  packages/protocol/contracts/identity/Escrow.sol
  packages/protocol/contracts/stability/Exchange.sol
  packages/protocol/contracts/stability/SortedOracles.sol
  packages/protocol/contracts/stability/test/MockStableToken.sol
  packages/protocol/migrations/06_gaspriceminimum.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/test/common/gaspriceminimum.ts
  packages/protocol/test/common/multisig.ts
  packages/protocol/test/common/multisig.ts.old
  packages/protocol/test/stability/sortedoracles.ts
Labels: audit, automerge

#2342 Fixing multisig tests
  packages/protocol/package.json
  packages/protocol/test/common/multisig.ts
  packages/protocol/test/stability/reserve.ts
Labels: automerge, bug

#2303 Added daily limit for reserve spending
  packages/protocol/contracts/common/test/MockGoldToken.sol
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/contracts/stability/interfaces/IReserve.sol
  packages/protocol/migrations/07_reserve.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/test/governance/epochrewards.ts
  packages/protocol/test/stability/reserve.ts
Labels: audit, automerge

#2267 Governance, downtime and double signing slasher contracts
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/protocol/contracts/common/UsingPrecompiles.sol
  packages/protocol/contracts/common/UsingRegistry.sol
  packages/protocol/contracts/governance/DoubleSigningSlasher.sol
  packages/protocol/contracts/governance/DowntimeSlasher.sol
  packages/protocol/contracts/governance/GovernanceSlasher.sol
  packages/protocol/contracts/governance/LockedGold.sol
  packages/protocol/contracts/governance/SlasherUtil.sol
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/contracts/governance/interfaces/ILockedGold.sol
  packages/protocol/contracts/governance/interfaces/IValidators.sol
  packages/protocol/contracts/governance/proxies/DoubleSigningSlasherProxy.sol
  packages/protocol/contracts/governance/proxies/DowntimeSlasherProxy.sol
  packages/protocol/contracts/governance/proxies/GovernanceSlasherProxy.sol
  packages/protocol/contracts/governance/test/MockLockedGold.sol
  packages/protocol/contracts/governance/test/MockUsingPrecompiles.sol
  packages/protocol/contracts/governance/test/MockValidators.sol
  packages/protocol/contracts/governance/test/TestDoubleSigningSlasher.sol
  packages/protocol/contracts/governance/test/TestDowntimeSlasher.sol
  packages/protocol/lib/registry-utils.ts
  packages/protocol/migrations/19_governance_slasher.ts
  packages/protocol/migrations/20_double_signing_slasher.ts
  packages/protocol/migrations/21_downtime_slasher.ts
  packages/protocol/migrations/22_governance.ts
  packages/protocol/migrations/23_elect_validators.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/test/common/integration.ts
  packages/protocol/test/governance/double_signing_slasher.ts
  packages/protocol/test/governance/downtime_slasher.ts
  packages/protocol/test/governance/governance_slasher.ts
  packages/protocol/test/governance/validators.ts
  packages/utils/src/address.ts
  packages/utils/src/collections.test.ts
  packages/utils/src/collections.ts
Labels: audit

#2343 Small fixes to deploy web
  packages/web/env-config.js.enc
  packages/web/package.json
Labels: automerge

#2324 1666 precompiles assembly rewrite
  packages/protocol/contracts/common/UsingPrecompiles.sol
Labels: audit, automerge
