Repository celo-org/celo-monorepo, pull requests merged in 2019-08, with the labels that each got.

#266 Disable CLI code coverage
  packages/cli/package.json
Labels: automerge

#274 Added typescript style guide to docs
  packages/docs/celo-codebase/style-guide/typescript.md
Labels: documentation

#215 Use a validating component for numbers
  packages/mobile/src/account/__snapshots__/EditProfile.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Invite.test.tsx.snap
  packages/mobile/src/invite/__snapshots__/JoinCelo.test.tsx.snap
  packages/mobile/src/pincode/Pincode.tsx
  packages/mobile/src/pincode/PincodeConfirmation.tsx
  packages/mobile/src/pincode/__snapshots__/Pincode.test.tsx.snap
  packages/mobile/src/pincode/__snapshots__/PincodeConfirmation.test.tsx.snap
  packages/mobile/src/send/LabeledTextInput.tsx
  packages/mobile/src/send/RecipientPicker.tsx
  packages/mobile/src/send/SendAmount.test.tsx
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/__snapshots__/SendAmount.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/Verify.test.tsx.snap
  packages/react-components/components/NumberInput.test.tsx
  packages/react-components/components/NumberInput.tsx
  packages/react-components/components/PhoneNumberInput.test.tsx
  packages/react-components/components/PhoneNumberInput.tsx
  packages/react-components/components/TextInput.tsx
  packages/react-components/components/ValidatedTextInput.tsx
  packages/react-components/components/__snapshots__/NumberInput.test.tsx.snap
  packages/react-components/components/__snapshots__/PhoneNumberInput.test.tsx.snap
  packages/utils/src/inputValidation.ts
  packages/utils/src/phoneNumbers.ts
  packages/utils/test/inputValidation.test.ts
  packages/verifier/src/components/__snapshots__/PhoneNumberInput.test.tsx.snap
Labels: applications, wallet

#10 Enable Reclaiming of Escrowed Payments
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-AR/global.json
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/escrow/EscrowedPaymentLineItem.tsx
  packages/mobile/src/escrow/ReclaimPaymentConfirmationCard.test.tsx
  packages/mobile/src/escrow/ReclaimPaymentConfirmationCard.tsx
  packages/mobile/src/escrow/ReclaimPaymentConfirmationScreen.test.tsx
  packages/mobile/src/escrow/ReclaimPaymentConfirmationScreen.tsx
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationCard.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationScreen.test.tsx.snap
  packages/mobile/src/escrow/actions.ts
  packages/mobile/src/escrow/reducer.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/firebase/notifications.ts
  packages/mobile/src/geth/consts.ts
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/notifications/EscrowedPaymentReminderNotification.test.tsx
  packages/mobile/src/notifications/EscrowedPaymentReminderNotification.tsx
  packages/mobile/src/notifications/__snapshots__/EscrowedPaymentReminderNotification.test.tsx.snap
  packages/mobile/src/send/selectors.ts
  packages/mobile/src/utils/formatting.ts
  packages/mobile/test/schemas.ts
  packages/mobile/test/values.ts
  packages/protocol/test/identity/escrow.ts
Labels: wallet

#288 [contractkit]Fix logging bug
  packages/contractkit/src/logger.ts
Labels: automerge

#289 [contractkit]Remve references to ABE
  packages/contractkit/index.ts
  packages/contractkit/src/contracts.ts
  packages/mobile/src/identity/commentKey.test.ts
Labels: automerge

#118 Make BondedDeposits bytecode size more manageable
  packages/celotool/geth_tests/governance_tests.ts
  packages/protocol/contracts/common/FractionUtil.sol
  packages/protocol/contracts/common/GasPriceMinimum.sol
  packages/protocol/contracts/common/Signatures.sol
  packages/protocol/contracts/common/test/FractionUtilTest.sol
  packages/protocol/contracts/governance/BondedDeposits.sol
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/governance/UsingBondedDeposits.sol
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/contracts/governance/interfaces/IBondedDeposits.sol
  packages/protocol/contracts/governance/test/MockBondedDeposits.sol
  packages/protocol/contracts/identity/Escrow.sol
  packages/protocol/contracts/stability/Exchange.sol
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/contracts/stability/SortedFractionMedianList.sol
  packages/protocol/contracts/stability/StableToken.sol
  packages/protocol/migrationsConfig.js
  packages/protocol/test/governance/bondeddeposits.ts
Labels: protocol

#276 [Wallet] Fee fixes/refactor
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-AR/global.json
  packages/mobile/package.json
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/escrow/ReclaimPaymentConfirmationCard.tsx
  packages/mobile/src/escrow/ReclaimPaymentConfirmationScreen.test.tsx
  packages/mobile/src/escrow/ReclaimPaymentConfirmationScreen.tsx
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationCard.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationScreen.test.tsx.snap
  packages/mobile/src/escrow/actions.ts
  packages/mobile/src/escrow/reducer.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/fees/CalculateFee.tsx
  packages/mobile/src/fees/EstimateFee.tsx
  packages/mobile/src/fees/actions.ts
  packages/mobile/src/fees/reducer.ts
  packages/mobile/src/fees/saga.test.ts
  packages/mobile/src/fees/saga.ts
  packages/mobile/src/fees/selectors.ts
  packages/mobile/src/firebase/notifications.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/notifications/EscrowedPaymentReminderNotification.tsx
  packages/mobile/src/paymentRequest/PaymentRequestListScreen.tsx
  packages/mobile/src/paymentRequest/PaymentRequestNotification.tsx
  packages/mobile/src/redux/reducers.ts
  packages/mobile/src/redux/sagas.ts
  packages/mobile/src/redux/store.ts
  packages/mobile/src/send/SendAmount.test.tsx
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/SendConfirmation.test.tsx
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/TransferConfirmationCard.tsx
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/send/actions.test.ts
  packages/mobile/src/send/actions.ts
  packages/mobile/src/send/reducers.ts
  packages/mobile/src/send/saga.ts
  packages/mobile/src/send/selectors.ts
  packages/mobile/src/tokens/saga.ts
  yarn.lock
Labels: applications, wallet

#283 Update Spanish PlayStore assets
  packages/mobile/fastlane/metadata/android/es-419/images/featureGraphic.jpg
  packages/mobile/fastlane/metadata/android/es-419/images/phoneScreenshots/phoneScreenshots01.jpg
  packages/mobile/fastlane/metadata/android/es-419/images/phoneScreenshots/phoneScreenshots02.jpg
  packages/mobile/fastlane/metadata/android/es-419/images/phoneScreenshots/phoneScreenshots03.jpg
  packages/mobile/fastlane/metadata/android/es-419/images/phoneScreenshots/phoneScreenshots04.jpg
  packages/mobile/fastlane/metadata/android/es-419/images/phoneScreenshots/phoneScreenshots05.jpg
  packages/mobile/fastlane/metadata/android/es-419/images/phoneScreenshots/phoneScreenshots06.jpg
  packages/mobile/fastlane/metadata/android/es-419/images/promoGraphic.png
Labels: applications, wallet

#279 Jest tests for Notification Services
  packages/blockchain-api/tsconfig.json
  packages/notification-service/.gitignore
  packages/notification-service/jest.config.js
  packages/notification-service/package.json
  packages/notification-service/src/blockscout/transfers.ts
  packages/notification-service/src/config.ts
  packages/notification-service/src/firebase.ts
  packages/notification-service/test/transfers.test.ts
  packages/notification-service/tsconfig.json
Labels: applications

#316 [Testing]Clean up end to end tests
  .circleci/config.yml
  packages/celotool/ci_test_sync_with_network.sh
  packages/celotool/geth_tests/network_sync_test.sh
Labels: automerge

#109 [Wallet] Updated balance automatically
  packages/mobile/src/components/AccountOverview.test.tsx
  packages/mobile/src/components/AccountOverview.tsx
  packages/mobile/src/components/CurrencyDisplay.tsx
  packages/mobile/src/components/__snapshots__/AccountOverview.test.tsx.snap
  packages/mobile/src/exchange/ExchangeConfirmationCard.tsx
  packages/mobile/src/home/actions.ts
  packages/mobile/src/home/saga.test.ts
  packages/mobile/src/home/saga.ts
  packages/mobile/src/redux/selectors.ts
Labels: wallet

#327 Reduces warnings around comment decrypting failing
  packages/utils/src/commentEncryption.ts
Labels: applications, automerge

#309 Remove artifact download for celotool transactions describe
  packages/celotool/src/cmds/transactions/describe.ts
Labels: automerge

#325 [Wallet] Alert banner refactor
  package.json
  packages/mobile/android/build.gradle
  packages/mobile/android/settings.gradle
  packages/mobile/jest.config.js
  packages/mobile/src/alert/AlertBanner.test.tsx
  packages/mobile/src/alert/AlertBanner.tsx
  packages/mobile/src/alert/__snapshots__/AlertBanner.test.tsx.snap
  packages/mobile/src/navigator/NavigatorWrapper.tsx
  packages/mobile/src/transactions/ExchangeFeedItem.tsx
  packages/mobile/src/transactions/TransferFeedItem.tsx
  packages/react-components/components/SmartTopAlert.test.tsx
  packages/react-components/components/SmartTopAlert.tsx
  packages/react-components/components/__snapshots__/SmartTopAlert.test.tsx.snap
  packages/react-components/package.json
  packages/verifier/android/build.gradle
  packages/verifier/android/settings.gradle
  packages/verifier/src/components/MessageBanner.test.tsx
  packages/verifier/src/components/NUX/__snapshots__/LanguageScreen.test.tsx.snap
  packages/verifier/src/components/TransactionReview/VerificationConfirmationCard.test.tsx
  packages/verifier/src/components/TransactionReview/__snapshots__/VerificationConfirmationCard.test.tsx.snap
  packages/verifier/src/components/__snapshots__/MessageBanner.test.tsx.snap
  packages/verifier/tsconfig.json
  packages/web/src/fauceting/RequestFunds.tsx
  patches/react-native-geth+0.1.0-development.patch
  patches/react-native-qrcode-svg+5.1.2.patch
  yarn.lock
Labels: applications, wallet

#100 Wait for Web3 to be ready before trying to redeem an invite
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-AR/global.json
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/invite/saga.test.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/language/Language.test.tsx
  packages/mobile/src/language/Language.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/networkInfo/saga.ts
  packages/mobile/src/stableToken/saga.test.ts
  packages/mobile/src/sync/Sync.test.tsx
  packages/mobile/src/sync/Sync.tsx
  packages/mobile/src/sync/__snapshots__/Sync.test.tsx.snap
  packages/mobile/src/web3/actions.test.ts
  packages/mobile/src/web3/actions.ts
  packages/mobile/src/web3/gas.ts
  packages/mobile/src/web3/reducer.ts
  packages/mobile/src/web3/saga.test.ts
  packages/mobile/src/web3/saga.ts
  packages/utils/src/async-helpers.ts
  packages/utils/test/async-helpers.test.ts
Labels: wallet

#416 Slight improvements to the CLI setup instructions and config
  packages/docs/SUMMARY.md
  packages/docs/command-line-interface/introduction.md
Labels: cli, documentation

#285 Remove duplicated @celo/client build
  packages/mobile/android/build.gradle
  packages/mobile/package.json
  yarn.lock
Labels: wallet

#419 Autodismiss testnet alert banner
  packages/mobile/src/account/Invite.tsx
  packages/mobile/src/account/InviteReview.tsx
  packages/mobile/src/account/actions.ts
  packages/mobile/src/config.ts
  packages/mobile/src/escrow/ReclaimPaymentConfirmationScreen.tsx
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/exchange/ExchangeTradeScreen.tsx
  packages/mobile/src/exchange/actions.ts
  packages/mobile/src/fees/CalculateFee.tsx
  packages/mobile/src/firebase/notifications.ts
  packages/mobile/src/firebase/saga.ts
  packages/mobile/src/home/WalletHome.test.tsx
  packages/mobile/src/home/WalletHome.tsx
  packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
  packages/mobile/src/invite/EnterInviteCode.tsx
  packages/mobile/src/invite/saga.test.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/pincode/Pincode.tsx
  packages/mobile/src/qrcode/utils.ts
  packages/mobile/src/send/RequestConfirmation.tsx
  packages/mobile/src/send/Send.tsx
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/saga.test.ts
  packages/mobile/src/send/saga.ts
  packages/mobile/src/tokens/saga.ts
  packages/mobile/src/transactions/saga.ts
  packages/mobile/src/verify/Verifying.tsx
  packages/mobile/src/web3/actions.test.ts
  packages/mobile/src/web3/gas.ts
Labels: applications, wallet

#432 Add .bulldozer.yml for automerge
  .bulldozer.yml
  .mergify.yml
Labels: automerge

#404 Show Celo Default Recipient only when devMode is active
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/es-AR/sendFlow7.json
  packages/mobile/src/account/Invite.test.tsx
  packages/mobile/src/account/__snapshots__/Invite.test.tsx.snap
  packages/mobile/src/recipients/RecipientPicker.tsx
  packages/mobile/src/send/Send.tsx
  packages/mobile/test/values.ts
Labels: applications, automerge, wallet

#431 Fix spelling of verification in loadingVerificationStatus
  packages/mobile/locales/en-US/sendFlow7.json
Labels: automerge

#303 [Wallet] Delete dead code from old onboarding flow
  packages/mobile/src/app/actions.ts
  packages/mobile/src/app/reducers.ts
  packages/mobile/src/invite/EnterInviteCode.tsx
  packages/mobile/src/invite/JoinCelo.tsx
  packages/mobile/src/invite/reducer.ts
  packages/mobile/src/web3/saga.ts
Labels: applications, wallet

#441 [CircleCI]Run end-to-end-geth-governance-test with 6GB of RAM
  .circleci/config.yml
Labels: automerge

#418 [faucet]Restrict writes to a particular user
  packages/faucet/.firebaserc
  packages/faucet/README.md
  packages/faucet/database-rules.bolt
  packages/faucet/package.json
  packages/web/env-config.js.enc
  packages/web/server/FirebaseClient.ts
Labels: automerge

#92 Add documentation for app network migration
  packages/mobile/README.md
Labels: automerge, documentation

#517 Fix typo in comment
  packages/protocol/contracts/stability/StableToken.sol
Labels: automerge

#461 New wallet alfajoresstaging build
  .env.alfajoresstaging
  packages/blockchain-api/app.alfajoresstaging.yaml
  packages/mobile/.env
  packages/mobile/.env.integration
  packages/mobile/.env.staging
  packages/mobile/android/app/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/fastlane/Fastfile
  packages/mobile/fastlane/README.md
  packages/mobile/ios/celo-tvOS/Info.plist
  packages/mobile/ios/celo-tvOSTests/Info.plist
  packages/mobile/ios/celo/Info.plist
  packages/mobile/ios/celoTests/Info.plist
  packages/mobile/package.json
  packages/notification-service/app.staging.yaml
  packages/notification-service/config/config.staging.env
  packages/verification-pool-api/contracts/Attestations.ts
  packages/verification-pool-api/contracts/GoldToken.ts
  packages/verification-pool-api/contracts/StableToken.ts
  packages/verification-pool-api/src/celoEnv.ts
  yarn.lock
Labels: applications, automerge, wallet

#552 Updates to CLI Doc
  packages/docs/command-line-interface/introduction.md
Labels: automerge

#445 Extract dappkit request metadata + multi-tx support
  packages/dappkit/src/index.ts
  packages/dappkit/tsconfig.json
  packages/mobile/src/account/selectors.ts
  packages/mobile/src/dappkit/DappKitAccountScreen.tsx
  packages/mobile/src/dappkit/dappkit.ts
  packages/utils/src/dappkit.ts
Labels: automerge

#550 [web]Import the auth module instead of all the Firebase modules
  packages/web/env-config.js.enc
  packages/web/server/FirebaseClient.ts
Labels: automerge, faucet, web

#562 [CircleCI]Make incremental testing work with PR from other repos
  .circleci/config.yml
  scripts/check_if_test_should_run_v2.ts
  scripts/ci_check_if_test_should_run_v2.sh
Labels: automerge

#576 [Celotool] Fixes exponent number formatting for contact decimals
  packages/protocol/scripts/truffle/transfer.ts
Labels: automerge

#590 fix the pub key check when registering the validator
  packages/cli/src/utils/command.ts
Labels: automerge

#560 Add testnet label to faucet transactions and update faucet address
  packages/blockchain-api/app.alfajores.yaml
  packages/mobile/src/transactions/TransferFeedItem.tsx
  packages/mobile/src/transactions/__snapshots__/TransferFeedItem.test.tsx.snap
Labels: applications, automerge, wallet

#462 Point to ganache-cli using renamed ganache-core
  packages/protocol/package.json
  yarn.lock
Labels: automerge

#603 [Celotool] Adds upgrade faucet command
  packages/celotool/src/cmds/deploy/upgrade/faucet.ts
Labels: celotool, infrastructure

#606 Fix Connecting to Celo Network banner regression
  packages/mobile/src/navigator/Headers.tsx
  packages/mobile/src/verify/Education.tsx
  packages/mobile/src/verify/Input.tsx
  packages/mobile/src/verify/Verifying.tsx
Labels: automerge

#609 Feature flag cleanup
  packages/web/env-config.js.enc
  packages/web/flags.js
  packages/web/pages/build/faucet.tsx
  packages/web/src/header/Header.3.tsx
  packages/web/src/utils/isVersion3.ts
Labels: automerge

#605 [CircleCI]Use larger container for end-to-end-sync-test
  .circleci/config.yml
Labels: automerge

#556 Remove currency symbol hardcoding
  packages/mobile/locales/en-US/exchangeFlow9.json
  packages/mobile/locales/en-US/nuxCurrencyPhoto4.json
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/locales/en.json
  packages/mobile/locales/es-AR/exchangeFlow9.json
  packages/mobile/locales/es-AR/nuxCurrencyPhoto4.json
  packages/mobile/locales/es-AR/walletFlow5.json
  packages/mobile/src/account/DollarEducation.tsx
  packages/mobile/src/components/AccountOverview.tsx
  packages/mobile/src/components/CurrencyDisplay.tsx
  packages/mobile/src/components/__snapshots__/AccountOverview.test.tsx.snap
  packages/mobile/src/escrow/ReclaimPaymentConfirmationCard.tsx
  packages/mobile/src/exchange/ExchangeConfirmationCard.tsx
  packages/mobile/src/exchange/ExchangeTradeScreen.tsx
  packages/mobile/src/exchange/__snapshots__/ExchangeConfirmationCard.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/home/__snapshots__/NotificationBox.test.tsx.snap
  packages/mobile/src/paymentRequest/NotificationAmount.tsx
  packages/mobile/src/paymentRequest/PaymentRequestBalance.tsx
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestListScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestNotification.test.tsx.snap
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/TransferConfirmationCard.tsx
  packages/mobile/src/transactions/ExchangeFeedItem.tsx
  packages/mobile/src/transactions/NoActivity.tsx
  packages/mobile/src/transactions/TransferFeedItem.tsx
  packages/mobile/src/transactions/__snapshots__/ExchangeFeedItem.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/NoActivity.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransactionFeed.test.tsx.snap
Labels: automerge

#446 [npm]Publish updated npm packages for @celo/walletkit and @celo/celocli
  packages/celotool/package.json
  packages/cli/package.json
  packages/dappkit/package.json
  packages/docs/command-line-interface/account.md
  packages/docs/command-line-interface/bonds.md
  packages/docs/command-line-interface/config.md
  packages/docs/command-line-interface/exchange.md
  packages/docs/command-line-interface/node.md
  packages/docs/command-line-interface/validator.md
  packages/docs/command-line-interface/validatorgroup.md
  packages/mobile/package.json
  packages/transaction-metrics-exporter/package.json
  packages/walletkit/package.json
Labels: applications, automerge

#597 Remove references to CeloLatestSyncMode
  packages/celotool/README.md
  packages/celotool/src/cmds/geth/run.ts
  packages/helm-charts/load-test/templates/statefulset.yaml
  packages/helm-charts/tracer-tool/scripts/run.sh
  packages/mobile/src/geth/consts.ts
  packages/mobile/src/geth/geth.ts
Labels: automerge

#614 [npm]Publish new @celo/walletkit and @celo/celocli for alfajores
  packages/celotool/package.json
  packages/cli/package.json
  packages/dappkit/package.json
  packages/mobile/package.json
  packages/transaction-metrics-exporter/package.json
  packages/walletkit/package.json
Labels: automerge

#584 Fix fees for accounts with low balances
  packages/mobile/src/fees/saga.ts
Labels: automerge

#607 [Wallet] Include hash in key in Transaction Feed
  packages/mobile/src/transactions/TransactionFeed.tsx
Labels: automerge

#617 Adds alfajoresstaging sync tests back
  packages/celotool/ci_test_sync_with_network.sh
Labels: automerge

#593 adds SDK info to website
  packages/web/src/dev/CoverAction.tsx
  packages/web/src/dev/CoverActions.tsx
  packages/web/src/header/BlueBanner.tsx
  packages/web/src/header/Header.3.tsx
  packages/web/src/home/HomeSystems.tsx
  packages/web/src/shared/menu-items.ts
  packages/web/static/locales/en/common.json
  packages/web/static/locales/en/dev.json
  packages/web/static/locales/en/home.json
Labels: web

#577 Aaronmgdr/eco
  packages/web/env-config.js.enc
  packages/web/fullstack/EcoFundFields.ts
  packages/web/package.json
  packages/web/server-env-config.js.enc
  packages/web/server/EcoFundApp.ts
  packages/web/server/FellowshipApp.ts
  packages/web/server/airtable.ts
  packages/web/server/index.ts
  packages/web/src/community/EcoFund.tsx
  packages/web/src/community/ah-logo.png
  packages/web/src/community/connect/ConnectPage.tsx
  packages/web/src/community/connect/Contribute.tsx
  packages/web/src/community/connect/FellowSection.tsx
  packages/web/src/community/polychain-logo.png
  packages/web/src/fauceting/RequestFunds.tsx
  packages/web/src/forms/EmailSubscribeForm.tsx
  packages/web/src/forms/Form.tsx
  packages/web/src/forms/FormComponents.tsx
  packages/web/src/logos/RingsLight.tsx
  packages/web/src/shared/Button.3.tsx
  packages/web/src/shared/navigation.tsx
  packages/web/src/styles.ts
  packages/web/static/locales/en/community.json
  yarn.lock
Labels: automerge

#627 Support proper parse and return types in dappkit
  packages/dappkit/src/index.ts
  packages/utils/src/dappkit.ts
Labels: automerge

#328 [Wallet] End-to-end test runs (1/2)
  packages/docs/celo-codebase/wallet/intro.md
  packages/mobile/.env.test
  packages/mobile/.gitignore
  packages/mobile/e2e/Transfer.spec.js
  packages/mobile/locales/en-US/dev.json
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-AR/global.json
  packages/mobile/package.json
  packages/mobile/scripts/build_e2e.sh
  packages/mobile/scripts/run_e2e.sh
  packages/mobile/scripts/start_emulator.sh
  packages/mobile/scripts/unlock.sh
  packages/mobile/src/alert/__snapshots__/AlertBanner.test.tsx.snap
  packages/mobile/src/components/DevSkipButton.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/recipients/RecipientPicker.tsx
  packages/mobile/src/send/Send.tsx
  packages/mobile/src/shared/DisconnectBanner.tsx
  packages/mobile/src/shared/__snapshots__/DisconnectBanner.test.tsx.snap
  packages/mobile/src/verify/Verify.test.tsx
  packages/mobile/src/verify/VerifyPhoneEducation.tsx
  packages/react-components/components/SmartTopAlert.tsx
  packages/react-components/components/__snapshots__/SmartTopAlert.test.tsx.snap
  packages/verifier/src/components/__snapshots__/MessageBanner.test.tsx.snap
  scripts/run_e2e.sh
  yarn.lock
Labels: wallet

#612 Add a generic unknown contact icon
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/locales/es-AR/walletFlow5.json
  packages/mobile/src/images/Images.ts
  packages/mobile/src/images/unknownUserIcon.png
  packages/mobile/src/transactions/TransferFeedItem.test.tsx
  packages/mobile/src/transactions/TransferFeedItem.tsx
  packages/mobile/src/transactions/__snapshots__/TransactionFeed.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransferFeedItem.test.tsx.snap
  packages/mobile/test/values.ts
Labels: automerge

#637 Minor typo change example.md
  packages/docs/developer-resources/contractkit/examples.md
Labels: automerge

#636 Minor change in usage.md
  packages/docs/developer-resources/dappkit/usage.md
Labels: automerge

#635 Minor minor typo error
  packages/docs/developer-resources/dappkit/setup.md
Labels: automerge

#634 minor page change
  packages/docs/developer-resources/dappkit/README.md
Labels: automerge

#263 Make reset a yargs argument in celotool deploy upgrade testnet
  packages/celotool/src/cmds/deploy/upgrade/testnet.ts
Labels: automerge

#618 [protocol] migrations: process cmdline args only once
  packages/protocol/lib/web3-utils.ts
  packages/protocol/migrations/13_attestations.ts
  packages/protocol/migrations/16_elect_validators.ts
  packages/protocol/migrationsConfig.js
Labels: protocol

#656 Delete import_contract_types_from_sdk.sh
  packages/cli/import_contract_types_from_sdk.sh
Labels: automerge

#630 DAppkit using ContractKit
  packages/contractkit/package.json
  packages/contractkit/src/contract-cache.ts
  packages/contractkit/src/wrappers/Attestations.ts
  packages/dappkit/package.json
  packages/dappkit/src/index.ts
  packages/dappkit/tsconfig.json
  packages/docs/developer-resources/dappkit/setup.md
  packages/docs/developer-resources/dappkit/usage.md
Labels: automerge

#658 App-wide currency translations
  packages/mobile/locales/en-US/backupKeyFlow6.json
  packages/mobile/locales/en-US/exchangeFlow9.json
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/en-US/inviteFlow11.json
  packages/mobile/locales/en-US/nuxCurrencyPhoto4.json
  packages/mobile/locales/en-US/nuxNamePin1.json
  packages/mobile/locales/en-US/paymentRequestFlow.json
  packages/mobile/locales/en-US/receiveFlow8.json
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/locales/en.json
  packages/mobile/locales/es-AR/backupKeyFlow6.json
  packages/mobile/locales/es-AR/exchangeFlow9.json
  packages/mobile/locales/es-AR/global.json
  packages/mobile/locales/es-AR/inviteFlow11.json
  packages/mobile/locales/es-AR/nuxCurrencyPhoto4.json
  packages/mobile/locales/es-AR/nuxNamePin1.json
  packages/mobile/locales/es-AR/paymentRequestFlow.json
  packages/mobile/locales/es-AR/receiveFlow8.json
  packages/mobile/locales/es-AR/sendFlow7.json
  packages/mobile/locales/es-AR/walletFlow5.json
  packages/mobile/src/exchange/consts.ts
  packages/mobile/src/i18n.ts
  packages/utils/src/currencies.ts
Labels: automerge

#684 Bye Jared
  packages/web/server/index.ts
  packages/web/src/about/team/jared@2x.jpg
  packages/web/src/about/team/team-list.ts
Labels: automerge

#668 [Wallet] Add yarn task to run lint and tsc and jest
  packages/mobile/package.json
Labels: automerge

#664 Update "Save Code Image" caption to "Share Code Image"
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/es-AR/sendFlow7.json
  packages/mobile/src/qrcode/QRCode.tsx
  packages/mobile/src/qrcode/__snapshots__/QRCode.test.tsx.snap
Labels: automerge

#692 Remove unused argentina production static nodes
  packages/celotool/src/argentinaproduction_static-nodes.json
Labels: automerge

#661 add #fund id to ecosystem fund area
  packages/web/src/community/EcoFund.tsx
Labels: automerge

#706 [Wallet] Added translation file that was not being used
  packages/mobile/locales/es-AR/index.ts
  packages/mobile/locales/es-AR/nuxVerification2.json
  packages/mobile/locales/es-AR/paymentRequestFlow.json
  packages/mobile/locales/es-AR/sendFlow7.json
Labels: automerge, wallet

#685 Icon updates
  packages/web/src/dev/CoverActions.tsx
  packages/web/src/dev/SDK.png
  packages/web/src/header/Header.3.tsx
Labels: automerge, web

#691 Minor: Reference new file in the comment
  dockerfiles/cli/Dockerfile
Labels: automerge

#709 [Wallet] Stop screen jumping for Wallet home screen and Verify Education screen
  packages/mobile/src/home/WalletHome.test.tsx
  packages/mobile/src/home/WalletHome.tsx
  packages/mobile/src/navigator/Headers.tsx
  packages/mobile/src/verify/VerifyPhoneEducation.tsx
  packages/mobile/src/verify/__snapshots__/Verify.test.tsx.snap
Labels: automerge

#686 add message about sms arrival on invite page
  packages/web/src/fauceting/MicroComponents.tsx
  packages/web/static/locales/en/faucet.json
Labels: automerge

#748 [wallet] Freeze account after 24 hours
  packages/mobile/locales/en-US/backupKeyFlow6.json
  packages/mobile/locales/es-AR/backupKeyFlow6.json
  packages/mobile/src/account/actions.ts
  packages/mobile/src/account/reducer.ts
  packages/mobile/src/analytics/constants.ts
  packages/mobile/src/backup/Backup.test.tsx
  packages/mobile/src/backup/Backup.tsx
  packages/mobile/src/backup/BackupIntroduction.test.tsx
  packages/mobile/src/backup/BackupIntroduction.tsx
  packages/mobile/src/backup/__snapshots__/Backup.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap
  packages/mobile/src/navigator/TabBar.tsx
  packages/mobile/src/navigator/TabNavigator.tsx
  packages/mobile/src/redux/selectors.test.ts
  packages/mobile/src/redux/selectors.ts
  packages/mobile/src/utils/time.test.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#729 [ContractKit]Add code to enable local signing of transactions
  packages/contractkit/package.json
  packages/contractkit/src/utils/signing-utils.ts
  packages/contractkit/src/utils/tx-signing.test.ts
  packages/contractkit/src/utils/tx-signing.ts
  packages/contractkit/src/utils/web3-utils.ts
Labels: automerge

#774 [CI] fix: contractkit wasn't included
  .circleci/config.yml
Labels: automerge

#776 [wallet] Fix amount input decimal max length
  packages/react-components/components/ValidatedTextInput.tsx
Labels: automerge

#779 yarn build in celotool Dockerfile
  dockerfiles/celotool/Dockerfile
Labels: automerge

#799 [wallet] Log calculate fee errors
  packages/mobile/src/fees/CalculateFee.tsx
Labels: applications, wallet
