Repository celo-org/celo-monorepo, pull requests merged in 2019-10, with the labels that each got.

#1135 [celotool]Add fast mode to celotool invite
  packages/celotool/src/cmds/account/invite.ts
  packages/protocol/scripts/bash/invite.sh
  packages/protocol/scripts/truffle/invite.ts
Labels: automerge

#1149 2019-09-30 integration deployment
  .env.integration
Labels: automerge

#1134 [CircleCI]Add a comment on how to fix lint checks
  .circleci/config.yml
Labels: automerge

#1128 Add attestation-service deploy
  .env
  .env.alfajores
  .env.alfajoresstaging
  .env.integration
  cloudbuild.yaml
  dockerfiles/attestation-service/Dockerfile
  dockerfiles/transaction-metrics-exporter/Dockerfile
  packages/celotool/src/cmds/deploy/destroy/attestation-service.ts
  packages/celotool/src/cmds/deploy/initial/attestation-service.ts
  packages/celotool/src/cmds/deploy/upgrade/attestation-service.ts
  packages/celotool/src/lib/attestation-service.ts
  packages/celotool/src/lib/env-utils.ts
  packages/helm-charts/attestation-service/Chart.yaml
  packages/helm-charts/attestation-service/README.md
  packages/helm-charts/attestation-service/templates/attestation.ingress.yaml
  packages/helm-charts/attestation-service/templates/attestation.secret.yaml
  packages/helm-charts/attestation-service/templates/attestation.service.yaml
  packages/helm-charts/attestation-service/templates/attestation.statefulset.yaml
  packages/helm-charts/attestation-service/values.yaml
Labels: automerge

#1126 Add IdentityMetadata to Contractkit
  packages/celotool/package.json
  packages/celotool/src/cmds/deploy/initial/contracts.ts
  packages/cli/package.json
  packages/cli/src/base.ts
  packages/cli/src/commands/identity/get-metadata.ts
  packages/contractkit/package.json
  packages/contractkit/src/identity/index.ts
  packages/contractkit/src/identity/metadata.ts
  packages/contractkit/src/index.ts
  packages/contractkit/src/wrappers/Attestations.ts
  packages/contractkit/tslint.json
  packages/docs/command-line-interface/identity.md
  yarn.lock
Labels: automerge

#1143 [faucet] Add custom metrics
  packages/faucet/package.json
  packages/faucet/src/celo-adapter.ts
  packages/faucet/src/database-helper.ts
  packages/faucet/src/metrics.ts
  yarn.lock
Labels: automerge

#1148 Upgrade to Node 10
  .circleci/config.yml
  .nvmrc
  README-dev.md
  SETUP.md
  dockerfiles/circleci/Dockerfile
  package.json
  packages/blockchain-api/app.alfajores.yaml
  packages/blockchain-api/app.alfajoresstaging.yaml
  packages/blockchain-api/app.dev.yaml
  packages/blockchain-api/app.integration.yaml
  packages/blockchain-api/app.pilot.yaml
  packages/blockchain-api/app.pilotstaging.yaml
  packages/blockchain-api/app.prod.yaml
  packages/blockchain-api/cloudbuild/cloudbuild.yaml
  packages/blockchain-api/deploy.sh
  packages/blockchain-api/package.json
  packages/celotool/src/cmds/deploy/initial/blockchain-api.ts
  packages/celotool/src/cmds/deploy/upgrade/blockchain-api.ts
  packages/faucet/package.json
  packages/faucet/src/celo-adapter.ts
  packages/mobile/.env
  packages/mobile/package.json
  packages/mobile/tslint.json
  packages/notification-service/app.alfajores.yaml
  packages/notification-service/app.alfajoresstaging.yaml
  packages/notification-service/app.integration.yaml
  packages/notification-service/app.pilot.yaml
  packages/notification-service/app.pilotstaging.yaml
  packages/notification-service/app.production.yaml
  packages/notification-service/package.json
  packages/notification-service/tsconfig.json
  packages/protocol/scripts/truffle/invite.ts
  packages/protocol/scripts/truffle/upgrade.ts
  packages/verification-pool-api/contracts/Attestations.ts
  packages/verification-pool-api/contracts/GoldToken.ts
  packages/verification-pool-api/contracts/StableToken.ts
  packages/verification-pool-api/package.json
  packages/verification-pool-api/src/celoEnv.ts
  packages/web/development.yaml
  packages/web/package.json
  packages/web/production.yaml
  packages/web/staging.yaml
  yarn.lock
Labels: automerge

#905 New About Page Cover
  packages/web/src/about/About.tsx
  packages/web/src/about/VideoCover.tsx
  packages/web/src/about/images/BeautifulMoneyPreview.jpg
  packages/web/src/about/images/index.ts
  packages/web/src/header/Header.3.tsx
  packages/web/src/join/FeaturedVideo.tsx
  packages/web/src/logos/LogoDarkBg.tsx
  packages/web/src/react-native-aug.d.ts
  packages/web/src/shared/PlayCircle.tsx
  packages/web/src/shared/VideoModal.tsx
  packages/web/src/utils/utils.ts
  packages/web/static/AboutPreview.jpg
  packages/web/static/locales/en/about.json
Labels: automerge

#1145 [Wallet] Network fee in transaction feed
  packages/mobile/.env.alfajores
  packages/mobile/.env.integration
  packages/mobile/.env.pilot
  packages/mobile/.env.pilotstaging
  packages/mobile/.env.production
  packages/mobile/.env.staging
  packages/mobile/.env.test
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/locales/es-419/walletFlow5.json
  packages/mobile/src/send/TransferConfirmationCard.tsx
  packages/mobile/src/transactions/TransactionFeed.test.tsx
  packages/mobile/src/transactions/TransferFeedIcon.tsx
  packages/mobile/src/transactions/TransferFeedItem.test.tsx
  packages/mobile/src/transactions/TransferFeedItem.tsx
  packages/mobile/src/transactions/__snapshots__/TransactionFeed.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransferFeedItem.test.tsx.snap
  packages/mobile/src/transactions/actions.ts
  packages/mobile/src/transactions/reducer.ts
  packages/mobile/src/transactions/transferFeedUtils.ts
  packages/mobile/src/utils/formatting.test.ts
  packages/mobile/src/utils/formatting.ts
Labels: automerge

#1167 Add CLI commands around identity metadata
  packages/cli/src/commands/identity/change-attestation-service-url.ts
  packages/cli/src/commands/identity/change-domain.ts
  packages/cli/src/commands/identity/change-name.ts
  packages/cli/src/commands/identity/create-metadata.ts
  packages/cli/src/commands/identity/get-metadata.ts
  packages/cli/src/commands/identity/register-metadata.ts
  packages/cli/src/commands/identity/show-metadata.ts
  packages/cli/src/utils/command.ts
  packages/cli/src/utils/identity.ts
  packages/contractkit/src/identity/metadata.ts
  packages/docs/command-line-interface/identity.md
Labels: automerge

#1176 Fix verification pool validation
  packages/mobile/package.json
  packages/verification-pool-api/.gitignore
  packages/verification-pool-api/package.json
  packages/verification-pool-api/src/config.ts
  packages/verification-pool-api/src/database.ts
  packages/verification-pool-api/src/validation.ts
  yarn.lock
Labels: automerge

#1147 [codecov]Fix codecov errors
  .codecov.yml
Labels: automerge

#1133 [ContractKit]Fill more fields before web3 signing
  packages/contractkit/src/providers/celo-private-keys-subprovider.ts
  packages/contractkit/src/utils/signing-utils.ts
  packages/contractkit/src/utils/tx-signing.test.ts
Labels: automerge

#1183 Move docker images to use node v10
  README-dev.md
  dockerfiles/attestation-service/Dockerfile
  dockerfiles/celotool/Dockerfile
  dockerfiles/cli/Dockerfile
  dockerfiles/cloudbuild/Dockerfile
  dockerfiles/transaction-metrics-exporter/Dockerfile
Labels: automerge

#1191 [ck] consistent send tx object in kit
  packages/contractkit/src/kit.test.ts
  packages/contractkit/src/kit.ts
  packages/contractkit/src/utils/send-tx.test.ts
  packages/contractkit/src/utils/send-tx.ts
  packages/contractkit/src/wrappers/BaseWrapper.ts
Labels: automerge

#1195 [contractkit] Document methods
  packages/contractkit/README.md
  packages/contractkit/src/address-registry.ts
  packages/contractkit/src/contract-cache.ts
  packages/contractkit/src/index.ts
  packages/contractkit/src/kit.ts
  packages/contractkit/src/utils/tx-result.ts
  packages/contractkit/src/web3-contract-cache.ts
  packages/contractkit/src/wrappers/BaseWrapper.ts
  packages/contractkit/src/wrappers/GoldTokenWrapper.ts
  packages/contractkit/src/wrappers/LockedGold.ts
  packages/contractkit/src/wrappers/StableTokenWrapper.ts
Labels: automerge

#1211 [Protocol] Fix network id for alfajores
  packages/protocol/truffle-config.js
Labels: automerge

#1200 2019-10-03 alfajores deployment
  .env.alfajores
  packages/protocol/migrationsConfig.js
Labels: automerge

#1188 [wallet]Store encrypted local signing key
  packages/mobile/src/web3/saga.test.ts
  packages/mobile/src/web3/saga.ts
Labels: automerge

#1219 [ck] Proper promise treatment to avoid UnhandledPromises
  packages/contractkit/src/utils/tx-result.ts
Labels: automerge

#1214 [Wallet] Fix disable conditions for butons on Enter Invite screen
  packages/mobile/src/invite/EnterInviteCode.tsx
  packages/mobile/src/invite/__snapshots__/EnterInviteCode.test.tsx.snap
Labels: automerge

#1210 [wallet] e2e back to green
  packages/mobile/.env.test
  packages/mobile/__mocks__/react-native-config.ts
  packages/mobile/__mocks__/src/geth/network-config.ts
  packages/mobile/e2e/Transfer.spec.js
  packages/mobile/package.json
  packages/mobile/scripts/build_e2e.sh
  packages/mobile/scripts/run_e2e.sh
  packages/mobile/scripts/start_emulator.sh
  packages/mobile/scripts/unlock.sh
  packages/mobile/src/config.ts
  packages/mobile/src/geth/geth.ts
  packages/mobile/src/geth/network-config.ts
  packages/mobile/src/web3/contracts.ts
  packages/mobile/src/web3/testnets.ts
Labels: automerge

#1223 Restore CI branch
  .circleci/config.yml
Labels: automerge

#1208 Fix integration hardcode
  packages/celotool/src/cmds/deploy/initial/contracts.ts
Labels: automerge

#1061 extracting function signatures
  packages/protocol/contracts/common/ExtractFunctionSignature.sol
  packages/protocol/contracts/common/test/ExtractFunctionSignatureTest.sol
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/test/common/extractfunctionsignature.ts
Labels: automerge

#1196 Adding `increaseAllowance` and `decreaseAllowance` methods
  packages/contractkit/src/wrappers/GoldTokenWrapper.ts
  packages/contractkit/src/wrappers/StableTokenWrapper.ts
  packages/protocol/contracts/common/GoldToken.sol
  packages/protocol/contracts/stability/StableToken.sol
  packages/protocol/test/common/goldtoken.ts
  packages/protocol/test/stability/stabletoken.ts
Labels: automerge

#1224 Updated SETUP.md with new yarn process
  SETUP.md
Labels: automerge

#1217 Fix Faucet done message
  packages/web/src/fauceting/MicroComponents.tsx
  packages/web/static/locales/en/faucet.json
Labels: automerge, faucet

#1152 Feature #909 proxy delegatecall
  packages/protocol/contracts/common/MultiSig.sol
  packages/protocol/contracts/common/Proxy.sol
  packages/protocol/contracts/common/libraries/AddressesHelper.sol
  packages/protocol/contracts/governance/Proposals.sol
  packages/protocol/test/common/proxy.ts
  packages/protocol/test/governance/governance.ts
Labels: automerge

#1175 Use ContractKit to get addresses for Blockchain API
  packages/blockchain-api/.env
  packages/blockchain-api/app.alfajores.yaml
  packages/blockchain-api/app.alfajoresstaging.yaml
  packages/blockchain-api/app.dev.yaml
  packages/blockchain-api/app.integration.yaml
  packages/blockchain-api/app.pilot.yaml
  packages/blockchain-api/app.pilotstaging.yaml
  packages/blockchain-api/package.json
  packages/blockchain-api/src/blockscout.ts
  packages/blockchain-api/src/config.ts
  packages/blockchain-api/src/utils.ts
  packages/blockchain-api/test/blockscout.test.ts
  packages/blockchain-api/test/mockTokenTxs.ts
Labels: automerge

#1081 Adding a contract to store minimum required client version
  .circleci/config.yml
  packages/celotool/ci_test_exit.sh
  packages/celotool/src/e2e-tests/exit_test.ts
  packages/protocol/contracts/governance/BlockchainParameters.sol
  packages/protocol/contracts/governance/proxies/BlockchainParametersProxy.sol
  packages/protocol/lib/proxy-utils.ts
  packages/protocol/lib/registry-utils.ts
  packages/protocol/migrations/15_blockchainparams.ts
  packages/protocol/migrations/16_governance.ts
  packages/protocol/migrations/17_elect_validators.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/test/common/linkedlist.ts
  packages/protocol/test/governance/blockchainparams.ts
Labels: automerge

#1255 Fix incremental testing script
  scripts/check_if_test_should_run_v2.ts
Labels: automerge

#1277 Fix cDollars in Gold tab Bug
  packages/blockchain-api/src/utils.ts
Labels: automerge

#1221 Wallet e2e on Circle Ci
  .circleci/config.yml
  packages/mobile/e2e/conf/avd_conf.ini
  packages/mobile/scripts/install_android_emulator_image.sh
  packages/mobile/scripts/run_e2e.sh
  packages/mobile/scripts/unlock.sh
  packages/mobile/scripts/wait_for_emulator_to_connect.sh
Labels: wallet

#1250 RetryWithBackOff for nexmo sends
  packages/attestation-service/src/attestation.ts
  packages/attestation-service/src/sms.ts
  packages/utils/src/async.ts
  packages/verification-pool-api/src/config.ts
  packages/verification-pool-api/src/verification.ts
Labels: automerge

#848 Docs with assumptions made by testnet terraform module
  packages/terraform-modules/testnet/README.md
Labels: automerge

#1263 [CircleCI]Test more npm packages
  .circleci/config.yml
Labels: automerge

#1280 Fix failing yarn builds when building docker images
  dockerfiles/transaction-metrics-exporter/Dockerfile
  packages/contractkit/src/wrappers/GoldTokenWrapper.ts
Labels: automerge

#1193 Combined Web UI Tweaks
  packages/web/server/index.ts
  packages/web/src/about/team/isabelle@2x.png
  packages/web/src/about/team/joe@2x.jpg
  packages/web/src/about/team/team-list.ts
  packages/web/src/download/Cover.tsx
  packages/web/src/header/Header.3.tsx
  packages/web/src/jobs/version3/Jobs.tsx
  packages/web/src/join/ImagePanes.tsx
  packages/web/src/join/berlinOffice.jpg
  packages/web/src/join/laurance-joe.jpg
  packages/web/src/styles.ts
  packages/web/static/locales/en/download.json
Labels: automerge

#1257 Fix typos in dev README
  README-dev.md
Labels: automerge

#1240 Remove 'bonds' from cli help and fix validatorgroup:member cmd describe message
  packages/cli/package.json
  packages/cli/src/commands/validatorgroup/member.ts
  packages/docs/command-line-interface/lockedgold.md
  packages/docs/command-line-interface/validatorgroup.md
Labels: automerge

#1259 [celotool]Use user info from gcloud tool
  packages/celotool/src/lib/testnet-utils.ts
Labels: automerge

#1281 Prevent celotool dockerfile yarn network trouble error
  dockerfiles/celotool/Dockerfile
Labels: automerge

#1278 VM Testnets cleanup, get transaction-metrics-exporter working with VM testnets
  packages/celotool/src/cmds/ssh-vm-node.ts
  packages/celotool/src/lib/blockscout.ts
  packages/celotool/src/lib/port_forward.ts
  packages/celotool/src/lib/terraform.ts
  packages/celotool/src/lib/transaction-metrics-exporter.ts
  packages/celotool/src/lib/vm-testnet-utils.ts
  packages/helm-charts/transaction-metrics-exporter/templates/deployment.yaml
  packages/helm-charts/transaction-metrics-exporter/values.yaml
  packages/terraform-modules/testnet/main.tf
  packages/terraform-modules/testnet/modules/bootnode/main.tf
  packages/terraform-modules/testnet/modules/bootnode/startup.sh
  packages/terraform-modules/testnet/modules/bootnode/variables.tf
  packages/terraform-modules/testnet/modules/tx-node/main.tf
  packages/terraform-modules/testnet/modules/tx-node/startup.sh
  packages/terraform-modules/testnet/modules/tx-node/variables.tf
  packages/terraform-modules/testnet/modules/validator/main.tf
  packages/terraform-modules/testnet/modules/validator/startup.sh
  packages/terraform-modules/testnet/modules/validator/variables.tf
  packages/terraform-modules/testnet/variables.tf
  packages/transaction-metrics-exporter/README.md
Labels: automerge

#1254 Fix fellowship form
  packages/web/fullstack/sentry.ts
  packages/web/server/FellowshipApp.ts
  packages/web/server/index.ts
  packages/web/src/community/connect/FellowshipForm.tsx
Labels: automerge

#1282 Update yarn.lock commit for websocket package to fix transaction-metrics-exporter in docker containers
  patches/websocket+1.0.24.patch
  yarn.lock
Labels: automerge

#1294 Add ability to generate addresses directly from env file in celotool
  packages/celotool/src/cmds/generate/address-from-env.ts
  packages/celotool/src/lib/generate_utils.ts
Labels: automerge

#1296 Set IN_MEMORY_DISCOVERY_TABLE=true for integration
  .env.integration
Labels: automerge

#1312 [Wallet] Add script to build sdk for env before running yarn dev
  packages/mobile/package.json
  packages/mobile/scripts/pre-dev.sh
Labels: automerge

#1313 Allow validators to specify an attestationKey with which they sign attestations
  packages/protocol/contracts/identity/Attestations.sol
  packages/protocol/contracts/identity/interfaces/IAttestations.sol
  packages/protocol/lib/signing-utils.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/test/governance/bondeddeposits.ts
  packages/protocol/test/identity/attestations.ts
  packages/utils/src/address.ts
  packages/utils/src/attestations.ts
  packages/utils/src/signatureUtils.test.ts
Labels: automerge

#1311 Add GRADLE_OPTS note to SETUP.md
  SETUP.md
Labels: automerge

#1324 [Wallet] Add check for $ENVFILE to pre-dev script
  packages/mobile/scripts/pre-dev.sh
Labels: automerge

#1317 Fix broken Discord link
  packages/docs/developer-resources/introduction.md
Labels: automerge

#1315 Integration deploy, don't overwrite genesis block if upgrading testnet
  .env.integration
  packages/celotool/src/cmds/deploy/upgrade/testnet.ts
  packages/mobile/package.json
  yarn.lock
Labels: automerge

#1215 Documentation: Fix broken Discord link
  packages/docs/developer-resources/introduction.md
Labels: automerge

#1298 Add comment about re-unlocking a validator
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#1289 Feature/909 proxy delegatecall
  packages/protocol/contracts/common/MultiSig.sol
  packages/protocol/contracts/common/Proxy.sol
  packages/protocol/contracts/common/libraries/AddressesHelper.sol
  packages/protocol/contracts/governance/Proposals.sol
  packages/protocol/test/common/proxy.ts
  packages/protocol/test/governance/governance.ts
Labels: automerge

#1333 Speed up CircleCI tests
  .circleci/config.yml
  packages/mobile/scripts/start_emulator.sh
Labels: automerge

#1338 [wallet] If an action is in the blacklist, now only logs the name (but not the payload)
  packages/mobile/src/redux/sagas.ts
Labels: automerge, wallet

#1345 [Mobile] Show Incorrect PIN error in exchange
  packages/mobile/src/exchange/actions.ts
Labels: automerge

#1346 Fix Metadata registration during contract deploy
  packages/celotool/src/cmds/deploy/initial/contracts.ts
  packages/cli/src/commands/identity/create-metadata.ts
  packages/contractkit/src/identity/metadata.ts
  packages/utils/src/async.ts
Labels: automerge

#1361 [wallet]Add documentation for ZeroSync mode
  packages/mobile/README.md
Labels: automerge

#1288 Allow most recently reporting oracle to report again
  packages/protocol/contracts/stability/SortedOracles.sol
  packages/protocol/test/stability/sortedoracles.ts
Labels: automerge

#1347 [Celotool] Update blockchain-api deploy script to automatically update faucet address
  packages/celotool/src/cmds/deploy/initial/blockchain-api.ts
  packages/celotool/src/cmds/deploy/upgrade/blockchain-api.ts
Labels: automerge

#1297 Alfajores changes & comment on unlocking accounts
  dockerfiles/cli/Dockerfile
  packages/cli/package.json
  packages/cli/start_geth.sh
  packages/docs/getting-started/running-a-full-node.md
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#1372 Point end-to-end tests back to master
  .circleci/config.yml
Labels: automerge

#1364 [wallet]Add documentation for jndcrash
  packages/mobile/README.md
Labels: automerge

#1367 [wallet]Add more documentation on ZeroSync mode
  packages/mobile/README.md
Labels: automerge

#1370 Document npm inter-repo dependencies instructions
  README-dev.md
  package.json
  scripts/check-packages.js
Labels: automerge

#1389 [Wallet] Enable push notifications on iOS
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/ios/celo/AppDelegate.m
  packages/mobile/ios/celo/Info.plist
Labels: automerge

#1398 [Wallet] New camera permission flow
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/es-419/sendFlow7.json
  packages/mobile/src/qrcode/NotAuthorizedView.test.tsx
  packages/mobile/src/qrcode/NotAuthorizedView.tsx
  packages/mobile/src/qrcode/QRScanner.tsx
  packages/mobile/src/qrcode/__snapshots__/NotAuthorizedView.test.tsx.snap
  packages/mobile/src/utils/permissions.android.ts
  packages/mobile/src/utils/permissions.ios.ts
Labels: automerge

#1417 E2E Attestations test + various e2e improvements
  .circleci/config.yml
  dockerfiles/circleci/Dockerfile
  packages/celotool/ci_test_attestations.sh
  packages/celotool/src/cmds/account/verify.ts
  packages/celotool/src/e2e-tests/attestations_tests.ts
  packages/celotool/src/e2e-tests/exit_test.ts
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/contractkit/src/wrappers/Attestations.ts
Labels: automerge

#1430 Reset pincode cache if unlock fails
  packages/mobile/src/pincode/PincodeCache.ts
  packages/mobile/src/web3/saga.ts
Labels: automerge

#1388 [wallet] Refactor leftover thunk to sagas
  packages/mobile/android/app/src/main/assets/custom/LicenseDisclaimer.txt
  packages/mobile/package.json
  packages/mobile/src/firebase/actions.ts
  packages/mobile/src/firebase/firebase.test.ts
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/firebase/notifications.ts
  packages/mobile/src/firebase/saga.ts
  packages/mobile/src/home/WalletHome.tsx
  packages/mobile/src/paymentRequest/PaymentRequestConfirmation.tsx
  packages/mobile/src/redux/reducers.ts
  packages/mobile/src/redux/sagas.ts
  packages/mobile/src/redux/store.ts
  packages/mobile/src/sentry/Sentry.ts
  packages/mobile/src/sentry/actions.ts
  packages/mobile/src/sentry/saga.ts
  packages/mobile/test/utils.ts
  yarn.lock
Labels: automerge, wallet

#1405 [contractkit] SortedOraclesWrapper + tests
  packages/contractkit/package.json
  packages/contractkit/src/test-utils/ganache-test.ts
  packages/contractkit/src/test-utils/migration-override.json
  packages/contractkit/src/wrappers/SortedOracles.test.ts
  packages/contractkit/src/wrappers/SortedOracles.ts
  packages/protocol/migrations/02_registry.ts
  packages/protocol/migrations/04_goldtoken.ts
  packages/protocol/migrations/07_reserve.ts
  packages/protocol/migrations/08_stabletoken.ts
  packages/protocol/migrations/09_exchange.ts
  packages/protocol/migrations/16_governance.ts
  packages/protocol/migrations/17_elect_validators.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/scripts/devchain.ts
Labels: automerge, contractkit

#1129 [Helm] Updated the helm package to deploy the upgraded blockscout version
  .env
  .env.integration
  packages/celotool/src/lib/blockscout.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/helm-charts/blockscout/Chart.yaml
  packages/helm-charts/blockscout/templates/_helpers.tpl
  packages/helm-charts/blockscout/templates/blockscout-indexer.deployment.yaml
  packages/helm-charts/blockscout/templates/blockscout-migration.job.yaml
  packages/helm-charts/blockscout/templates/blockscout-web.deployment.yaml
  packages/helm-charts/blockscout/templates/blockscout.secret.yaml
  packages/helm-charts/blockscout/values.yaml
Labels: automerge

#1445 [Wallet] Don't log all props, which includes i18n
  packages/mobile/src/analytics/constants.ts
  packages/mobile/src/exchange/ExchangeTradeScreen.tsx
Labels: automerge

#1454 [Wallet] Prevent error from Avatar when name is missing
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/es-419/sendFlow7.json
  packages/mobile/src/components/Avatar.tsx
  packages/react-components/__mocks__/country-data.js
  packages/react-components/components/Avatar.test.tsx
  packages/react-components/components/Avatar.tsx
  packages/react-components/components/PhoneNumberInput.test.tsx
  packages/react-components/components/__snapshots__/Avatar.test.tsx.snap
  packages/react-components/components/__snapshots__/PhoneNumberInput.test.tsx.snap
  packages/react-components/package.json
Labels: automerge

#1419 [Wallet] Wallet can switch between hosted and local node
  README-dev.md
  packages/mobile/.env
  packages/mobile/.env.alfajores
  packages/mobile/.env.integration
  packages/mobile/.env.pilot
  packages/mobile/.env.pilotstaging
  packages/mobile/.env.production
  packages/mobile/.env.staging
  packages/mobile/.env.test
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/src/account/Account.tsx
  packages/mobile/src/account/CeloLite.tsx
  packages/mobile/src/account/__snapshots__/Account.test.tsx.snap
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/config.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/geth/consts.ts
  packages/mobile/src/geth/geth.ts
  packages/mobile/src/geth/networkConfig.ts
  packages/mobile/src/geth/saga.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/transactions/send.ts
  packages/mobile/src/web3/actions.ts
  packages/mobile/src/web3/contracts.ts
  packages/mobile/src/web3/reducer.ts
  packages/mobile/src/web3/saga.ts
  packages/mobile/src/web3/selectors.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#1465 Fixes key_placer.sh when encrypting files
  scripts/key_placer.sh
Labels: automerge

#1476 Update governance end-to-end tests to work with changed precompile
  packages/celotool/src/e2e-tests/governance_tests.ts
Labels: automerge

#1463 [Wallet] Upgrade app version to v1.5.1
  packages/mobile/README.md
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/assets/custom/LicenseDisclaimer.txt
  packages/mobile/android/gradle.properties
  packages/mobile/fastlane/Fastfile
  packages/mobile/fastlane/README.md
  packages/mobile/package.json
Labels: automerge

#1480 [Wallet] Remove QR debouncing to improve responsiveness
  packages/mobile/src/qrcode/QRScanner.tsx
  packages/mobile/src/send/saga.ts
Labels: automerge

#1485 [Wallet] Add script to translate locale strings
  packages/mobile/fastlane/Fastfile
  packages/mobile/scripts/translateFile.js
Labels: automerge

#1469 Point end-to-end tests back to master
  .circleci/config.yml
Labels: automerge

#1488 Point all packages to latest ganache-cli master
  packages/attestation-service/package.json
  packages/contractkit/package.json
  packages/protocol/package.json
  yarn.lock
Labels: automerge

#1489 [Wallet] Fix wei invite bug
  packages/mobile/src/import/saga.test.ts
  packages/mobile/src/import/saga.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/tokens/saga.ts
Labels: automerge

#1197 Storing previous randomness values
  packages/protocol/contracts/identity/Random.sol
  packages/protocol/contracts/identity/test/TestRandom.sol
  packages/protocol/migrations/13_random.ts
  packages/protocol/migrations/16_governance.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/test/identity/attestations.ts
  packages/protocol/test/identity/random.ts
  packages/protocol/test/stability/stabletoken.ts
Labels: automerge

#1421 Deploy celo's image of ethstats
  .env
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/ethstats.ts
  packages/helm-charts/ethstats/values.yaml
Labels: automerge

#1482 [Wallet + Verification Pool] Add details about generating an app-signature
  packages/mobile/README.md
  packages/verification-pool-api/src/config.ts
Labels: automerge

#1500 Add spanish backup key for backup key flow
  packages/mobile/locales/es-419/backupKeyFlow6.json
  packages/mobile/locales/es-419/nuxRestoreWallet3.json
Labels: automerge

#1513 Remove ContractKit/Protocol building from Transaction Metrics Exporter Docker Image
  dockerfiles/transaction-metrics-exporter/Dockerfile
Labels: automerge

#1507 Move to forno terminology
  packages/helm-charts/testnet/templates/forno.ingress.yaml
Labels: automerge

#1495 Change android play store description copy to match ios
  packages/mobile/fastlane/metadata/android/en-US/full_description.txt
  packages/mobile/fastlane/metadata/android/es-419/full_description.txt
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/locales/en-US/nuxNamePin1.json
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/locales/es-419/accountScreen10.json
  packages/mobile/locales/es-419/nuxNamePin1.json
  packages/mobile/locales/es-419/walletFlow5.json
  packages/mobile/src/home/WalletHome.tsx
  packages/mobile/src/invite/EnterInviteCode.tsx
Labels: automerge

#1534 [Wallet] Fix yarn dev command for running android
  SETUP.md
  packages/mobile/package.json
  packages/mobile/scripts/unlock.sh
Labels: automerge

#1462 Added txpool family to geth apis. Sorted geth cmd options
  packages/helm-charts/testnet/templates/_helpers.tpl
Labels: automerge

#1511 Rename hosted node references to forno
  packages/attestation-service/config/.env.development
  packages/blockchain-api/.env
  packages/blockchain-api/app.alfajores.yaml
  packages/blockchain-api/app.alfajoresstaging.yaml
  packages/blockchain-api/app.integration.yaml
  packages/blockchain-api/app.pilot.yaml
  packages/blockchain-api/app.pilotstaging.yaml
  packages/contractkit/README.md
  packages/dappkit/README.md
  packages/docs/developer-resources/contractkit/setup.md
  packages/docs/developer-resources/dappkit/usage.md
  packages/helm-charts/attestation-service/templates/attestation.statefulset.yaml
  packages/mobile/README.md
  packages/mobile/src/config.ts
  packages/mobile/src/transactions/send.ts
  packages/mobile/src/web3/contracts.ts
  packages/notification-service/config/config.integration.env
  packages/notification-service/config/config.local.env
  packages/notification-service/config/config.test.env
  packages/verification-pool-api/src/config.ts
  packages/walletkit/src/contract-utils.ts
Labels: automerge

#1468 Validate Attestation Requests
  packages/attestation-service/config/.env.development
  packages/attestation-service/config/database.json
  packages/attestation-service/migrations/20191015211858-create-attestation.js
  packages/attestation-service/package.json
  packages/attestation-service/src/attestation.ts
  packages/attestation-service/src/db.ts
  packages/attestation-service/src/index.ts
  packages/attestation-service/src/models/attestation.ts
  packages/attestation-service/src/request.ts
  packages/celotool/src/cmds/account/verify.ts
  packages/contractkit/package.json
  packages/contractkit/src/wrappers/Attestations.ts
  packages/mobile/src/tokens/saga.ts
  packages/utils/src/async.ts
  packages/utils/src/phoneNumbers.ts
  packages/utils/src/signatureUtils.test.ts
  packages/utils/src/signatureUtils.ts
  yarn.lock
Labels: automerge

#1541 [Wallet] Implement SMS invite on iOS
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/src/invite/saga.ts
  yarn.lock
Labels: automerge

#1473 Unify to prefix messages for signing
  packages/contractkit/src/test-utils/ganache.setup.ts
  packages/contractkit/src/utils/signing.test.ts
  packages/protocol/contracts/common/Signatures.sol
  packages/protocol/contracts/identity/Attestations.sol
  packages/protocol/lib/signing-utils.ts
  packages/protocol/test/identity/attestations.ts
  packages/protocol/test/identity/escrow.ts
  packages/utils/src/signatureUtils.test.ts
  packages/utils/src/signatureUtils.ts
Labels: automerge

#1551 [Wallet] Get React Native Hot Reloading Working
  packages/mobile/package.json
  packages/mobile/src/navigator/NavigatorWrapper.tsx
  yarn.lock
Labels: automerge

#1327 Add selectIssuers Transaction
  packages/celotool/src/cmds/account/verify.ts
  packages/celotool/src/e2e-tests/attestations_tests.ts
  packages/contractkit/src/wrappers/Attestations.ts
  packages/protocol/contracts/common/SafeCast.sol
  packages/protocol/contracts/common/SafeCastTest.sol
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/contracts/identity/Attestations.sol
  packages/protocol/contracts/identity/interfaces/IAttestations.sol
  packages/protocol/contracts/identity/interfaces/IRandom.sol
  packages/protocol/contracts/identity/test/MockRandom.sol
  packages/protocol/migrations/14_attestations.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/test/common/safecast.ts
  packages/protocol/test/governance/election.ts
  packages/protocol/test/identity/attestations.ts
  packages/utils/src/attestations.ts
Labels: automerge
