Repository celo-org/celo-monorepo, pull requests merged in 2019-11, with the labels that each got.

#1562 Point e2e tests back
  .circleci/config.yml
Labels: automerge

#613 Support protocol hotfixing
  packages/contractkit/src/test-utils/ganache.setup.ts
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/governance/Proposals.sol
  packages/protocol/contracts/governance/interfaces/IGovernance.sol
  packages/protocol/contracts/governance/test/GovernanceTest.sol
  packages/protocol/migrationsConfig.js
  packages/protocol/runTests.js
  packages/protocol/scripts/devchain.ts
  packages/protocol/test/governance/governance.ts
  packages/protocol/truffle-config.js
Labels: automerge, protocol

#1560 Avoid re-encrypting key files with yarn keys:encrypt command
  scripts/key_placer.sh
Labels: automerge

#1467 Allow a specified address to disable/enable the Exchange
  packages/protocol/contracts/baklava/Freezable.sol
  packages/protocol/contracts/baklava/test/FreezableTest.sol
  packages/protocol/contracts/stability/Exchange.sol
  packages/protocol/contracts/stability/interfaces/IExchange.sol
  packages/protocol/migrations/09_exchange.ts
  packages/protocol/test/baklava/freezable.ts
  packages/protocol/test/stability/exchange.ts
Labels: automerge

#1537 Fix e2e on CI
  .circleci/config.yml
  packages/mobile/package.json
  packages/mobile/scripts/ci-e2e.sh
  packages/mobile/scripts/unlock.sh
  scripts/run_e2e.sh
Labels: automerge

#1474 Re-work locked gold requirements for validators and groups
  packages/celotool/src/e2e-tests/validator_order_tests.ts
  packages/contractkit/src/wrappers/Validators.ts
  packages/protocol/contracts/common/UsingPrecompiles.sol
  packages/protocol/contracts/common/UsingRegistry.sol
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/governance/LockedGold.sol
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/contracts/governance/interfaces/IGovernance.sol
  packages/protocol/contracts/governance/interfaces/IValidators.sol
  packages/protocol/contracts/governance/test/MockGovernance.sol
  packages/protocol/contracts/governance/test/MockValidators.sol
  packages/protocol/migrations/12_validators.ts
  packages/protocol/migrations/19_elect_validators.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/test/governance/election.ts
  packages/protocol/test/governance/governance.ts
  packages/protocol/test/governance/lockedgold.ts
  packages/protocol/test/governance/validators.ts
Labels: protocol

#1569 Increase ganache gas limit
  packages/protocol/scripts/bash/ganache.sh
Labels: automerge

#1567 Bump e2e test migrate numbers where needed
  packages/celotool/src/e2e-tests/exit_test.ts
Labels: automerge

#1310 [wallet] Added native phone picker
  packages/mobile/locales/en.json
  packages/mobile/locales/es.json
  packages/mobile/src/i18n.ts
  packages/mobile/src/invite/__snapshots__/JoinCelo.test.tsx.snap
  packages/react-components/__mocks__/country-data.ts
  packages/react-components/components/PhoneNumberInput.test.tsx
  packages/react-components/components/PhoneNumberInput.tsx
  packages/react-components/components/__snapshots__/PhoneNumberInput.test.tsx.snap
  packages/react-components/index.d.ts
  packages/react-components/package.json
  packages/verifier/src/components/PhoneNumberInput.test.tsx
  packages/verifier/src/components/__snapshots__/PhoneNumberInput.test.tsx.snap
  packages/verifier/src/index.d.ts
Labels: automerge

#1447 EU Cookies Behavior Change
  packages/web/pages/_app.tsx
  packages/web/src/analytics/analytics.ts
  packages/web/src/header/CookieConsent.tsx
  packages/web/src/header/Header.3.tsx
Labels: automerge

#1577 Fix Ethstats Docker Image reference
  .env
Labels: automerge

#1581 [BlockchainApi] Use new third party currency api
  packages/blockchain-api/.env
  packages/blockchain-api/.gitignore
  packages/blockchain-api/app.alfajores.yaml
  packages/blockchain-api/app.alfajoresstaging.yaml
  packages/blockchain-api/app.integration.yaml
  packages/blockchain-api/app.pilot.yaml
  packages/blockchain-api/app.pilotstaging.yaml
  packages/blockchain-api/jest.config.js
  packages/blockchain-api/package.json
  packages/blockchain-api/setupJest.ts
  packages/blockchain-api/src/config.ts
  packages/blockchain-api/src/currencyConversion.ts
  packages/blockchain-api/src/secrets.json.enc
  packages/blockchain-api/test/currencyConversion.test.ts
  packages/blockchain-api/tsconfig.json
  scripts/key_placer.sh
Labels: automerge

#1616 [BlockchainApi] Hotfix secrets not present when deploying to App Engine
  packages/blockchain-api/package.json
  packages/blockchain-api/src/config.ts
Labels: automerge

#1253 Adds a governable parameter controlling how much extra gas gasCurrency transactions use
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/contractkit/src/base.ts
  packages/contractkit/src/contract-cache.ts
  packages/contractkit/src/web3-contract-cache.ts
  packages/contractkit/src/wrappers/BlockchainParameters.ts
  packages/protocol/contracts/governance/BlockchainParameters.sol
  packages/protocol/migrations/17_blockchainparams.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/scripts/build.ts
  packages/protocol/test/governance/blockchainparams.ts
Labels: automerge

#1592 Alfajores & pilot deployments
  .env.alfajores
  .env.alfajoresstaging
  .env.pilot
  .env.pilotstaging
  dockerfiles/cli/Dockerfile
  packages/cli/package.json
  packages/cli/start_geth.sh
  packages/docs/getting-started/running-a-full-node.md
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#1546 Remove old argentina specific pages
  packages/web/pages/arg_privacy.tsx
  packages/web/pages/arg_tos.tsx
  packages/web/pages/argentina.tsx
  packages/web/server/index.ts
  packages/web/src/argentina/ArgentinaFAQ.tsx
  packages/web/src/argentina/ArgentinaPrivacy.tsx
  packages/web/src/argentina/ArgentinaTOS.tsx
  packages/web/src/fonts/Fonts.tsx
  packages/web/src/privacy/Privacy.tsx
  packages/web/src/shared/Styles.tsx
  packages/web/src/shared/Text.tsx
Labels: automerge

#1607 Deployment fixes for attestation-service
  .env
  .env.mnemonic.enc
  packages/celotool/src/lib/attestation-service.ts
  packages/helm-charts/attestation-service/requirements.lock
  packages/helm-charts/attestation-service/requirements.yaml
  packages/helm-charts/attestation-service/templates/attestation.secret.yaml
  packages/helm-charts/attestation-service/templates/attestation.statefulset.yaml
Labels: automerge

#1499 Disable indexer in webapp pod
  packages/helm-charts/blockscout/templates/blockscout-web.deployment.yaml
Labels: automerge

#1466 Aaronmgdr/airtable upgrade
  packages/web/server-env-config.js.enc
  packages/web/server/EventHelpers.test.ts
  packages/web/server/EventHelpers.ts
Labels: automerge

#1449 Two Performance Optimizations
  packages/web/src/home/merchant.jpg
  packages/web/src/join/Rise.tsx
  packages/web/src/lib.dom.d.ts
Labels: automerge

#1348 Aaronmgdr/invite page
  package.json
  packages/cli/package.json
  packages/faucet/README.md
  packages/faucet/database-rules.bolt
  packages/faucet/package.json
  packages/faucet/src/database-helper.ts
  packages/notification-service/package.json
  packages/verification-pool-api/package.json
  packages/web/env-config.js.enc
  packages/web/package.json
  packages/web/server/FirebaseClient.ts
  packages/web/server/FirebaseServerSide.ts
  packages/web/server/controllers.ts
  packages/web/server/index.ts
  packages/web/src/dev/Cover.tsx
  packages/web/src/dev/CoverAction.tsx
  packages/web/src/dev/CoverActions.tsx
  packages/web/src/dev/FaucetPage.tsx
  packages/web/src/download/AppStores.tsx
  packages/web/src/download/Cover.tsx
  packages/web/src/download/CoverActions.tsx
  packages/web/src/download/MobileApp.tsx
  packages/web/src/download/app-store.png
  packages/web/src/download/play-store.png
  packages/web/src/fauceting/FaucetInterfaces.ts
  packages/web/src/fauceting/MicroComponents.tsx
  packages/web/src/fauceting/RequestFunds.tsx
  packages/web/src/fauceting/utils.ts
  packages/web/src/icons/Android.tsx
  packages/web/src/icons/Apple.tsx
  packages/web/src/icons/RadioIcon.tsx
  packages/web/src/shared/Button.3.tsx
  packages/web/src/shared/menu-items.ts
  packages/web/src/styles.ts
  packages/web/src/table/table.tsx
  packages/web/static/locales/en/download.json
  packages/web/static/locales/en/faucet.json
  yarn.lock
Labels: automerge

#1583 Add iOS setup instructions
  SETUP.md
Labels: automerge

#1628 [Wallet] Enable Forno by default (zero sync mode)
  packages/mobile/.env
  packages/mobile/.env.integration
  packages/mobile/.env.pilot
  packages/mobile/.env.pilotstaging
  packages/mobile/.env.production
  packages/mobile/.env.test
  packages/mobile/src/web3/contracts.ts
Labels: automerge

#1633 [Wallet] Fix unable to redeem invite from referrer
  packages/mobile/src/invite/EnterInviteCode.test.tsx
  packages/mobile/src/invite/EnterInviteCode.tsx
  packages/mobile/src/invite/utils.test.ts
  packages/mobile/src/invite/utils.ts
Labels: automerge

#1245 Added parameter to set the block gas limit
  .circleci/config.yml
  packages/celotool/ci_test_blockchain_parameters.sh
  packages/celotool/src/e2e-tests/blockchain_parameters_tests.ts
  packages/celotool/src/e2e-tests/exit_test.ts
  packages/contractkit/src/wrappers/BlockchainParameters.ts
  packages/protocol/contracts/governance/BlockchainParameters.sol
  packages/protocol/lib/registry-utils.ts
  packages/protocol/migrations/17_blockchainparams.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/test/governance/blockchainparams.ts
Labels: automerge

#1178 Add e2e tests readme
  packages/celotool/README-e2e.md
Labels: automerge

#992 Show validator group affiliates in CLI
  packages/cli/src/commands/validatorgroup/show.ts
  packages/contractkit/src/wrappers/Validators.test.ts
  packages/contractkit/src/wrappers/Validators.ts
Labels: automerge

#1626 Add CLI command to update validator public key
  packages/cli/src/commands/validator/publicKey.ts
  packages/contractkit/src/wrappers/Validators.ts
  packages/docs/command-line-interface/validator.md
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/test/governance/validators.ts
Labels: automerge

#1645 Fix invite script by moving to contractkit
  packages/celotool/.gitignore
  packages/celotool/src/cmds/account/faucet.ts
  packages/celotool/src/cmds/account/invite.ts
  packages/celotool/src/lib/contract-utils.ts
  packages/celotool/twilio-config.enc
  packages/contractkit/src/contract-cache.ts
  packages/contractkit/src/wrappers/Escrow.ts
Labels: automerge

#1646 Various fixes for the pilot app
  packages/blockchain-api/app.pilot.yaml
  packages/blockchain-api/yarn.lock
  packages/mobile/.env
  packages/mobile/android/app/src/pilot/google-services.json.enc
  packages/mobile/src/config.ts
  packages/mobile/src/web3/actions.ts
Labels: automerge

#1635 [Wallet] Tie new verification screens into sagas and cleanup old code
  packages/mobile/locales/en-US/nuxVerification2.json
  packages/mobile/locales/es-419/nuxVerification2.json
  packages/mobile/src/account/InviteReview.test.tsx
  packages/mobile/src/app/App.tsx
  packages/mobile/src/app/saga.ts
  packages/mobile/src/components/BottomButton.test.tsx
  packages/mobile/src/components/BottomButton.tsx
  packages/mobile/src/components/__snapshots__/BottomButton.test.tsx.snap
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/icons/DancingRings.tsx
  packages/mobile/src/icons/dancingRings.json
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/contactMapping.test.ts
  packages/mobile/src/identity/contactMapping.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/import/ImportContacts.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/recipients/recipient.ts
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/store.ts
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/utils/styles.ts
  packages/mobile/src/verify/ProgressIndicator.tsx
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/VerificationFailedModal.tsx
  packages/mobile/src/verify/VerificationInputScreen.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.test.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
  packages/mobile/src/verify/VerificationSuccessScreen.test.tsx
  packages/mobile/src/verify/VerificationSuccessScreen.tsx
  packages/mobile/src/verify/Verified.tsx
  packages/mobile/src/verify/Verify.test.tsx
  packages/mobile/src/verify/VerifyPhoneEducation.tsx
  packages/mobile/src/verify/Verifying.tsx
  packages/mobile/src/verify/__snapshots__/VerificationInputScreen.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/VerificationLoadingScreen.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/VerificationSuccessScreen.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/Verify.test.tsx.snap
  packages/mobile/test/schemas.ts
  packages/react-components/components/TextButton.tsx
  packages/react-components/styles/colors.tsx
Labels: automerge

#1652 [wallet] Doesn't calculate fee on empty balance
  packages/mobile/src/fees/saga.test.ts
  packages/mobile/src/fees/saga.ts
  packages/mobile/src/stableToken/reducer.ts
Labels: wallet

#1351 Export geth metrics on VM testnet
  packages/celotool/src/cmds/deploy/destroy/vm-testnet.ts
  packages/celotool/src/cmds/deploy/initial/vm-testnet.ts
  packages/celotool/src/cmds/deploy/upgrade/vm-testnet.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/prom-to-sd-utils.ts
  packages/celotool/src/lib/vm-testnet-utils.ts
  packages/helm-charts/prometheus-to-sd/templates/deployment.yaml
  packages/helm-charts/prometheus-to-sd/values.yaml
  packages/terraform-modules/testnet/main.tf
  packages/terraform-modules/testnet/modules/bootnode/main.tf
  packages/terraform-modules/testnet/modules/tx-node/main.tf
  packages/terraform-modules/testnet/modules/tx-node/outputs.tf
  packages/terraform-modules/testnet/modules/tx-node/startup.sh
  packages/terraform-modules/testnet/modules/tx-node/variables.tf
  packages/terraform-modules/testnet/modules/validator/main.tf
  packages/terraform-modules/testnet/modules/validator/outputs.tf
  packages/terraform-modules/testnet/modules/validator/startup.sh
  packages/terraform-modules/testnet/modules/validator/variables.tf
  packages/terraform-modules/testnet/outputs.tf
  packages/terraform-modules/testnet/variables.tf
Labels: automerge

#1575 Support claim signatures and support Keybase claims
  packages/celotool/ci_test_governance.sh
  packages/celotool/src/cmds/deploy/initial/contracts.ts
  packages/cli/package.json
  packages/cli/src/commands/account/change-attestation-service-url.ts
  packages/cli/src/commands/account/change-domain.ts
  packages/cli/src/commands/account/change-name.ts
  packages/cli/src/commands/account/claim-attestation-service-url.ts
  packages/cli/src/commands/account/claim-domain.ts
  packages/cli/src/commands/account/claim-keybase.ts
  packages/cli/src/commands/account/claim-name.ts
  packages/cli/src/commands/account/claims.test.ts
  packages/cli/src/commands/account/create-metadata.ts
  packages/cli/src/commands/account/get-metadata.ts
  packages/cli/src/commands/account/register-metadata.ts
  packages/cli/src/commands/account/show-metadata.ts
  packages/cli/src/utils/cli.ts
  packages/cli/src/utils/exec.ts
  packages/cli/src/utils/identity.ts
  packages/contractkit/src/identity/claims/claim.ts
  packages/contractkit/src/identity/claims/keybase.ts
  packages/contractkit/src/identity/claims/types.ts
  packages/contractkit/src/identity/metadata.test.ts
  packages/contractkit/src/identity/metadata.ts
  packages/docs/command-line-interface/account.md
  packages/utils/src/address.ts
Labels: automerge

#1578 Optimized Attestation view calls and removal of the reveal TX
  packages/attestation-service/config/config.json
  packages/celotool/src/cmds/account/verify.ts
  packages/celotool/src/e2e-tests/attestations_tests.ts
  packages/contractkit/src/wrappers/Attestations.ts
  packages/protocol/contracts/common/Accounts.sol
  packages/protocol/contracts/common/interfaces/IAccounts.sol
  packages/protocol/contracts/identity/Attestations.sol
  packages/protocol/contracts/identity/interfaces/IAttestations.sol
  packages/protocol/test/common/accounts.ts
  packages/protocol/test/identity/attestations.ts
  packages/utils/package.json
  packages/utils/src/parsing.ts
Labels: automerge

#1558 Add EpochRewards smart contract to calculate epoch rewards and payments
  .circleci/config.yml
  packages/celotool/src/e2e-tests/blockchain_parameters_tests.ts
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/celotool/src/e2e-tests/utils.ts
  packages/celotool/src/e2e-tests/validator_order_tests.ts
  packages/contractkit/src/base.ts
  packages/contractkit/src/contract-cache.ts
  packages/contractkit/src/web3-contract-cache.ts
  packages/protocol/contracts/common/UsingRegistry.sol
  packages/protocol/contracts/common/test/MockGoldToken.sol
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/contracts/governance/EpochRewards.sol
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/contracts/governance/interfaces/IElection.sol
  packages/protocol/contracts/governance/proxies/EpochRewardsProxy.sol
  packages/protocol/contracts/governance/test/EpochRewardsTest.sol
  packages/protocol/contracts/governance/test/MockElection.sol
  packages/protocol/contracts/governance/test/ValidatorsTest.sol
  packages/protocol/contracts/stability/SortedOracles.sol
  packages/protocol/contracts/stability/test/MockSortedOracles.sol
  packages/protocol/lib/registry-utils.ts
  packages/protocol/lib/test-utils.ts
  packages/protocol/lib/web3-utils.ts
  packages/protocol/migrations/12_validators.ts
  packages/protocol/migrations/14_epoch_rewards.ts
  packages/protocol/migrations/15_random.ts
  packages/protocol/migrations/16_attestations.ts
  packages/protocol/migrations/17_escrow.ts
  packages/protocol/migrations/18_blockchainparams.ts
  packages/protocol/migrations/19_governance.ts
  packages/protocol/migrations/20_elect_validators.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/scripts/build.ts
  packages/protocol/test/governance/epochrewards.ts
  packages/protocol/test/governance/validators.ts
  packages/protocol/test/stability/exchange.ts
  packages/protocol/test/stability/reserve.ts
Labels: automerge

#1665 Point end-to-end governance test back to master
  .circleci/config.yml
Labels: automerge

#1670 [wallet] Hide invite education copy after invite was redeemed
  packages/mobile/src/invite/EnterInviteCode.tsx
Labels: automerge, wallet

#1669 [wallet] Fixed Native phone picker Use native API instead
  packages/react-components/components/PhoneNumberInput.test.tsx
  packages/react-components/components/PhoneNumberInput.tsx
Labels: automerge, wallet

#1680 Minor attestation service fixes
  cloudbuild.yaml
  packages/helm-charts/attestation-service/templates/attestation.secret.yaml
Labels: automerge

#1677 Update Dark backgrounds text color
  packages/web/src/community/connect/CoverArea.tsx
  packages/web/src/dev/BuildPage.tsx
  packages/web/src/dev/CoverAction.tsx
  packages/web/src/dev/Feature.tsx
  packages/web/src/dev/StackSection.tsx
  packages/web/src/fauceting/MicroComponents.tsx
  packages/web/src/styles.ts
Labels: automerge

#1684 [Wallet] Use the country of the phone number for determining the default local currency
  packages/mobile/src/localCurrency/selectors.test.ts
  packages/mobile/src/localCurrency/selectors.ts
Labels: automerge

#1687 Switch to correct cluster when fauceting
  packages/celotool/src/cmds/account/faucet.ts
Labels: automerge

#1698 [Wallet] Add more local currencies
  packages/mobile/src/localCurrency/__snapshots__/SelectLocalCurrency.test.tsx.snap
  packages/mobile/src/localCurrency/consts.ts
  packages/mobile/src/transactions/TransferFeedItem.tsx
  packages/mobile/src/transactions/__snapshots__/TransactionFeed.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransferFeedItem.test.tsx.snap
Labels: automerge

#1585 Adjust e2e transfer and governance tests to match new fee distribution and eliminate ProposerFraction
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/celotool/src/e2e-tests/sync_tests.ts
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/celotool/src/e2e-tests/utils.ts
  packages/contractkit/src/kit.test.ts
  packages/contractkit/src/kit.ts
  packages/contractkit/src/wrappers/GasPriceMinimum.ts
  packages/protocol/contracts/common/GasPriceMinimum.sol
  packages/protocol/migrations/06_gaspriceminimum.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/test/common/gaspriceminimum.ts
Labels: automerge

#1726 Check in spanish verification translations
  packages/mobile/locales/en-US/nuxVerification2.json
  packages/mobile/locales/es-419/nuxVerification2.json
Labels: automerge

#1708 [Wallet] Prompt user to restart app when turning off Forno a second time
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/locales/es-419/accountScreen10.json
  packages/mobile/src/account/CeloLite.tsx
  packages/mobile/src/account/__snapshots__/CeloLite.test.tsx.snap
  packages/mobile/src/app/AppLoading.tsx
  packages/mobile/src/app/ErrorScreen.tsx
  packages/mobile/src/app/saga.ts
  packages/mobile/src/exchange/FeeExchangeIcon.test.tsx
  packages/mobile/src/exchange/__snapshots__/FeeExchangeIcon.test.tsx.snap
  packages/mobile/src/geth/GethAwareButton.test.tsx
  packages/mobile/src/geth/__snapshots__/GethAwareButton.test.tsx.snap
  packages/mobile/src/geth/saga.ts
  packages/mobile/src/images/Images.ts
  packages/mobile/src/images/crowd-mobile.png
  packages/mobile/src/images/default-avatar.png
  packages/mobile/src/images/profile.jpg
  packages/mobile/src/utils/AppRestart.ts
  packages/mobile/src/web3/actions.ts
  packages/mobile/src/web3/contracts.ts
  packages/mobile/src/web3/reducer.ts
  packages/mobile/src/web3/saga.ts
  packages/mobile/src/web3/selectors.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#1706 Change the event we emit when selecting issuers
  packages/protocol/contracts/identity/Attestations.sol
  packages/protocol/test/identity/attestations.ts
Labels: automerge

#1629 [Wallet] Set default gradle properties
  .circleci/config.yml
  packages/mobile/android/gradle.properties
Labels: automerge

#1663 Add AccountClaim to Metadata
  packages/attestation-service/src/attestation.ts
  packages/attestation-service/src/request.ts
  packages/cli/src/commands/account/claim-account.ts
  packages/cli/src/commands/account/claims.test.ts
  packages/cli/src/commands/account/get-metadata.ts
  packages/cli/src/commands/account/show-metadata.ts
  packages/cli/src/utils/command.ts
  packages/cli/src/utils/identity.ts
  packages/contractkit/src/identity/claims/account.test.ts
  packages/contractkit/src/identity/claims/account.ts
  packages/contractkit/src/identity/claims/claim.ts
  packages/contractkit/src/identity/claims/types.ts
  packages/contractkit/src/identity/metadata.ts
  packages/docs/command-line-interface/account.md
  packages/utils/src/address.ts
  packages/utils/src/io.ts
Labels: automerge

#1713 Added helper function to get the list of current validators
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/protocol/contracts/governance/Election.sol
Labels: automerge

#1739 Remove end-to-end attestations test from circle
  .circleci/config.yml
Labels: automerge

#1731 Make styling more consistent in validator quick start and add password prompt to account:unlock
  packages/cli/src/commands/account/unlock.ts
  packages/cli/src/commands/node/synced.ts
  packages/docs/command-line-interface/account.md
  packages/docs/command-line-interface/node.md
  packages/docs/getting-started/running-a-full-node.md
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#1738 Support blacklisting country codes for the attestation service
  packages/attestation-service/README.md
  packages/attestation-service/config/.env.development
  packages/attestation-service/migrations/20191015211858-create-attestation.js
  packages/attestation-service/nodemon.json
  packages/attestation-service/src/attestation.ts
  packages/attestation-service/src/db.ts
  packages/attestation-service/src/index.ts
  packages/attestation-service/src/models/attestation.ts
  packages/attestation-service/src/request.ts
  packages/attestation-service/src/sms.ts
  packages/attestation-service/src/sms/base.ts
  packages/attestation-service/src/sms/index.ts
  packages/attestation-service/src/sms/nexmo.ts
  packages/utils/src/address.ts
Labels: automerge

#1725 Set up an oracle account on deployment of a network
  packages/celotool/src/cmds/deploy/initial/contracts.ts
  packages/celotool/src/lib/generate_utils.ts
Labels: celotool, protocol

#1753 Add @celo/dev-utils
  dockerfiles/attestation-service/Dockerfile
  dockerfiles/celotool/Dockerfile
  packages/cli/jest.config.js
  packages/cli/package.json
  packages/cli/src/commands/account/authorize.test.ts
  packages/cli/src/commands/account/claims.test.ts
  packages/cli/src/commands/account/register.test.ts
  packages/cli/src/test-utils/ganache.setup.ts
  packages/cli/src/test-utils/ganache.teardown.ts
  packages/contractkit/jest.config.js
  packages/contractkit/package.json
  packages/contractkit/src/identity/claims/account.test.ts
  packages/contractkit/src/identity/metadata.test.ts
  packages/contractkit/src/test-utils/ganache-test.ts
  packages/contractkit/src/test-utils/ganache.setup.ts
  packages/contractkit/src/test-utils/ganache.teardown.ts
  packages/contractkit/src/test-utils/matchers.ts
  packages/contractkit/src/utils/signing.test.ts
  packages/contractkit/src/utils/tx-signing.test.ts
  packages/contractkit/src/wrappers/Accounts.test.ts
  packages/contractkit/src/wrappers/Exchange.test.ts
  packages/contractkit/src/wrappers/GoldToken.test.ts
  packages/contractkit/src/wrappers/SortedOracles.test.ts
  packages/contractkit/src/wrappers/StableToken.test.ts
  packages/contractkit/src/wrappers/Validators.test.ts
  packages/dev-utils/.gitignore
  packages/dev-utils/package.json
  packages/dev-utils/src/ganache-setup.ts
  packages/dev-utils/src/ganache-teardown.ts
  packages/dev-utils/src/ganache-test.ts
  packages/dev-utils/src/matchers.ts
  packages/dev-utils/src/migration-override.json
  packages/dev-utils/tsconfig.json
  packages/dev-utils/tslint.json
Labels: automerge

#1754 Support Twilio in the attestation service
  packages/attestation-service/config/.env.development
  packages/attestation-service/package.json
  packages/attestation-service/src/attestation.ts
  packages/attestation-service/src/models/attestation.ts
  packages/attestation-service/src/sms/base.ts
  packages/attestation-service/src/sms/index.ts
  packages/attestation-service/src/sms/twilio.ts
Labels: automerge

#1717 [wallet] UX fixes for native phone number
  packages/react-components/components/PhoneNumberInput.test.tsx
  packages/react-components/components/PhoneNumberInput.tsx
Labels: wallet

#1761 Add attestation service status endpoint
  packages/attestation-service/package.json
  packages/attestation-service/src/env.ts
  packages/attestation-service/src/index.ts
  packages/attestation-service/src/request.ts
  packages/attestation-service/src/requestHandlers/attestation.ts
  packages/attestation-service/src/requestHandlers/status.ts
  packages/attestation-service/src/sms/base.ts
  packages/attestation-service/src/sms/index.ts
  packages/attestation-service/src/sms/nexmo.ts
  packages/attestation-service/src/sms/twilio.ts
  packages/utils/src/collections.ts
  packages/utils/src/io.ts
  yarn.lock
Labels: automerge

#1752 Explicitly wait for nodes to sync in end-to-end tests
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/celotool/src/e2e-tests/sync_tests.ts
  packages/celotool/src/e2e-tests/utils.ts
Labels: automerge

#1549 Deduplicate yarn packages
  packages/celotool/src/lib/generate_utils.ts
  packages/celotool/src/lib/utils.ts
  packages/contractkit/src/test-utils/PromiEventStub.ts
  packages/mobile/src/qrcode/QRScanner.tsx
  packages/mobile/src/verify/VerificationInputScreen.tsx
  packages/mobile/src/verify/VerificationInterstitialScreen.tsx
  packages/mobile/src/web3/saga.ts
  packages/react-components/analytics/wrapper.tsx
  packages/transaction-metrics-exporter/src/index.ts
  yarn.lock
Labels: automerge

#1770 Try CircleCI memory+ class to fix build step (6GB instead of 4GB of memory)
  .circleci/config.yml
Labels: automerge

#1779 Fix yargs import
  packages/celotool/src/cli.ts
  packages/celotool/src/cmds/account.ts
  packages/celotool/src/cmds/account/faucet.ts
  packages/celotool/src/cmds/account/revoke.ts
  packages/celotool/src/cmds/account/verify.ts
  packages/celotool/src/cmds/account/weekly_faucet.ts
  packages/celotool/src/cmds/backup.ts
  packages/celotool/src/cmds/contract_addresses.ts
  packages/celotool/src/cmds/copy_contract_artifacts.ts
  packages/celotool/src/cmds/copy_policies.ts
  packages/celotool/src/cmds/deploy.ts
  packages/celotool/src/cmds/deploy/destroy.ts
  packages/celotool/src/cmds/deploy/initial.ts
  packages/celotool/src/cmds/deploy/initial/load-test.ts
  packages/celotool/src/cmds/deploy/initial/tracer-tool.ts
  packages/celotool/src/cmds/deploy/migrate.ts
  packages/celotool/src/cmds/deploy/upgrade.ts
  packages/celotool/src/cmds/deploy/upgrade/blockscout.ts
  packages/celotool/src/cmds/deploy/upgrade/faucet.ts
  packages/celotool/src/cmds/deploy/upgrade/testnet.ts
  packages/celotool/src/cmds/fork_env.ts
  packages/celotool/src/cmds/gcp.ts
  packages/celotool/src/cmds/gcp/remove-leaked-forwarding-rules.ts
  packages/celotool/src/cmds/generate.ts
  packages/celotool/src/cmds/generate/account-address.ts
  packages/celotool/src/cmds/generate/address-from-env.ts
  packages/celotool/src/cmds/generate/bip32.ts
  packages/celotool/src/cmds/generate/genesis-file.ts
  packages/celotool/src/cmds/generate/public-key.ts
  packages/celotool/src/cmds/geth.ts
  packages/celotool/src/cmds/geth/build.ts
  packages/celotool/src/cmds/geth/create_account.ts
  packages/celotool/src/cmds/geth/get_gold_balance.ts
  packages/celotool/src/cmds/geth/init.ts
  packages/celotool/src/cmds/geth/run.ts
  packages/celotool/src/cmds/geth/simulate_client.ts
  packages/celotool/src/cmds/geth/static_nodes.ts
  packages/celotool/src/cmds/geth/trace.ts
  packages/celotool/src/cmds/geth/transfer.ts
  packages/celotool/src/cmds/monitoring.ts
  packages/celotool/src/cmds/port_forward.ts
  packages/celotool/src/cmds/restore.ts
  packages/celotool/src/cmds/ssh-vm-node.ts
  packages/celotool/src/cmds/switch.ts
  packages/celotool/src/cmds/transactions/describe.ts
  packages/celotool/src/cmds/transactions/list.ts
Labels: automerge

#1766 Sign whole metadata instead of individual claims
  packages/cli/src/commands/account/claim-keybase.ts
  packages/cli/src/utils/identity.ts
  packages/contractkit/src/identity/claims/account.test.ts
  packages/contractkit/src/identity/claims/claim.ts
  packages/contractkit/src/identity/claims/keybase.ts
  packages/contractkit/src/identity/metadata.ts
  packages/utils/src/signatureUtils.ts
Labels: automerge

#1765 [Wallet] Fix disconnecting banner overlap in wallet home
  packages/mobile/src/home/WalletHome.test.tsx
  packages/mobile/src/home/WalletHome.tsx
  packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
Labels: automerge

#1786 Update .env to point to master Geth tag and remove deprecated VERIFICATION_POOL_URL
  .env
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/celotool/src/lib/utils.ts
  packages/celotool/src/lib/vm-testnet-utils.ts
  packages/docs/getting-started/running-a-validator.md
  packages/helm-charts/testnet/scripts/create-network.sh
  packages/helm-charts/testnet/templates/_helpers.tpl
  packages/helm-charts/testnet/templates/txnode.statefulset.yaml
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
  packages/terraform-modules/testnet/main.tf
  packages/terraform-modules/testnet/modules/tx-node/main.tf
  packages/terraform-modules/testnet/modules/tx-node/startup.sh
  packages/terraform-modules/testnet/modules/tx-node/variables.tf
  packages/terraform-modules/testnet/modules/validator/main.tf
  packages/terraform-modules/testnet/modules/validator/startup.sh
  packages/terraform-modules/testnet/modules/validator/variables.tf
  packages/terraform-modules/testnet/variables.tf
  packages/verification-pool-api/README.md
Labels: automerge

#1416 Create multiple test C Labs groups during migration to satisfy max group size
  .gitignore
  packages/celotool/src/cmds/deploy/initial/contracts.ts
  packages/celotool/src/cmds/deploy/upgrade/contracts.ts
  packages/celotool/src/e2e-tests/utils.ts
  packages/celotool/src/lib/migration-utils.ts
  packages/protocol/lib/web3-utils.ts
  packages/protocol/migrations/20_elect_validators.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/scripts/bash/migrate.sh
Labels: automerge, infrastructure

#1767 Add structured logging and Prometheus events
  packages/attestation-service/README.md
  packages/attestation-service/config/.env.development
  packages/attestation-service/index.d.ts
  packages/attestation-service/package.json
  packages/attestation-service/src/db.ts
  packages/attestation-service/src/env.ts
  packages/attestation-service/src/index.ts
  packages/attestation-service/src/logger.ts
  packages/attestation-service/src/metrics.ts
  packages/attestation-service/src/request.ts
  packages/attestation-service/src/requestHandlers/attestation.ts
  yarn.lock
Labels: automerge

#1793 Support singular claim types
  packages/contractkit/src/identity/claims/attestation-service-url.test.ts
  packages/contractkit/src/identity/claims/types.ts
  packages/contractkit/src/identity/metadata.ts
Labels: automerge

#1749 Add ability to partially re-lock pending withdrawals
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/cli/src/commands/election/current.ts
  packages/cli/src/commands/election/list.ts
  packages/cli/src/commands/election/run.ts
  packages/cli/src/commands/election/show.ts
  packages/cli/src/commands/election/validatorset.ts
  packages/cli/src/commands/lockedgold/lock.ts
  packages/cli/src/commands/validator/list.ts
  packages/contractkit/src/wrappers/Accounts.ts
  packages/contractkit/src/wrappers/Election.ts
  packages/contractkit/src/wrappers/LockedGold.test.ts
  packages/contractkit/src/wrappers/LockedGold.ts
  packages/contractkit/src/wrappers/Validators.ts
  packages/docs/command-line-interface/account.md
  packages/docs/command-line-interface/election.md
  packages/docs/command-line-interface/lockedgold.md
  packages/docs/command-line-interface/validator.md
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/contracts/governance/LockedGold.sol
  packages/protocol/test/governance/lockedgold.ts
Labels: automerge, betanet-blocker

#1792 Support validating claims
  packages/attestation-service/src/requestHandlers/status.ts
  packages/celotool/src/cmds/deploy/initial/contracts.ts
  packages/cli/src/commands/account/claim-attestation-service-url.ts
  packages/cli/src/utils/identity.ts
  packages/contractkit/src/identity/claims/attestation-service-url.test.ts
  packages/contractkit/src/identity/claims/attestation-service-url.ts
  packages/contractkit/src/identity/claims/claim.ts
  packages/contractkit/src/identity/claims/types.ts
  packages/utils/src/io.ts
Labels: automerge, betanet-blocker

#1764 [Wallet] Fix Celo Lite crash for second toggle off in production builds
  packages/mobile/src/web3/saga.ts
Labels: automerge

#1540 [Celotool] Integration with truffle blockscout plugin
  packages/celotool/src/cmds/deploy/initial/verify-contracts.ts
  packages/protocol/package.json
  packages/protocol/scripts/bash/verify_contracts.sh
  packages/protocol/truffle-config.js
  yarn.lock
Labels: betanet-blocker

#1797 Attestation service deploy updates + support attestation signers
  .env
  packages/attestation-service/src/index.ts
  packages/celotool/src/cmds/account/verify.ts
  packages/celotool/src/e2e-tests/utils.ts
  packages/celotool/src/lib/migration-utils.ts
  packages/contractkit/src/wrappers/Attestations.ts
  packages/helm-charts/attestation-service/templates/attestation.statefulset.yaml
  packages/protocol/migrations/20_elect_validators.ts
  packages/protocol/migrationsConfig.js
Labels: automerge, betanet-blocker

#1817 Support re-requesting when we are outside of the randomness availability window
  packages/protocol/contracts/identity/Attestations.sol
  packages/protocol/contracts/identity/interfaces/IRandom.sol
  packages/protocol/migrationsConfig.js
  packages/protocol/test/identity/attestations.ts
Labels: automerge, betanet-blocker

#1772 Small improvements to various flaky tests
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/celotool/src/e2e-tests/sync_tests.ts
  packages/celotool/src/e2e-tests/utils.ts
  packages/protocol/test/governance/epochrewards.ts
Labels: automerge, betanet-blocker

#1763 Utilize new gateway fee structure
  .circleci/config.yml
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/celotool/src/e2e-tests/validator_order_tests.ts
  packages/celotool/src/lib/geth.ts
  packages/contractkit/README.md
  packages/contractkit/src/base.ts
  packages/contractkit/src/contract-cache.ts
  packages/contractkit/src/kit.test.ts
  packages/contractkit/src/kit.ts
  packages/contractkit/src/providers/celo-private-keys-subprovider.ts
  packages/contractkit/src/utils/signing-utils.ts
  packages/contractkit/src/utils/tx-signing.test.ts
  packages/contractkit/src/utils/tx-signing.ts
  packages/contractkit/src/web3-contract-cache.ts
  packages/contractkit/src/wrappers/BlockchainParameters.ts
  packages/contractkit/types/web3.d.ts
  packages/dappkit/README.md
  packages/dappkit/src/index.ts
  packages/docs/celo-codebase/protocol/transactions/erc20-transaction-fees.md
  packages/docs/developer-resources/contractkit/README.md
  packages/docs/developer-resources/contractkit/examples.md
  packages/docs/developer-resources/contractkit/setup.md
  packages/docs/developer-resources/dappkit/usage.md
  packages/faucet/src/protocol/signing-utils.ts
  packages/mobile/src/dappkit/dappkit.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/send/saga.ts
  packages/protocol/contracts/common/FeeCurrencyWhitelist.sol
  packages/protocol/contracts/common/UsingRegistry.sol
  packages/protocol/contracts/common/interfaces/IFeeCurrencyWhitelist.sol
  packages/protocol/contracts/common/proxies/FeeCurrencyWhitelistProxy.sol
  packages/protocol/contracts/governance/BlockchainParameters.sol
  packages/protocol/lib/registry-utils.ts
  packages/protocol/lib/signing-utils.ts
  packages/protocol/migrations/03_whitelist.ts
  packages/protocol/migrations/04_goldtoken.ts
  packages/protocol/migrations/08_stabletoken.ts
  packages/protocol/migrations/19_governance.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/scripts/build.ts
  packages/protocol/test/common/gascurrencywhitelist.ts
  packages/protocol/test/governance/blockchainparams.ts
  packages/utils/src/dappkit.ts
  packages/verification-pool-api/src/signing-utils.ts
  packages/walletkit/index.ts
  packages/walletkit/src/contract-utils-v2.ts
  packages/walletkit/src/contract-utils.ts
  packages/walletkit/src/signing-utils.ts
  packages/walletkit/src/transaction-utils.ts
  packages/walletkit/test/contract-utils-v2.test.ts
  packages/walletkit/test/transaction-utils.test.ts
Labels: automerge, betanet-blocker

#1820 Update with new istanbul lookback window size flag
  .circleci/config.yml
  .env
  packages/celotool/src/cmds/geth/run.ts
  packages/celotool/src/e2e-tests/utils.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/generate_utils.ts
Labels: betanet-blocker

#1822 Update migration config to correct protocol parameters
  packages/celotool/src/e2e-tests/utils.ts
  packages/contractkit/src/wrappers/Accounts.test.ts
  packages/contractkit/src/wrappers/SortedOracles.test.ts
  packages/contractkit/src/wrappers/Validators.test.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/scripts/devchain.ts
  packages/protocol/truffle-config.js
Labels: betanet-blocker

#1824 Point end-to-end tests back to master
  .circleci/config.yml
Labels: betanet-blocker

#1819 Minor Contractkit changes
  packages/attestation-service/src/requestHandlers/attestation.ts
  packages/contractkit/src/index.ts
  packages/contractkit/src/wrappers/Attestations.ts
  packages/contractkit/src/wrappers/BaseWrapper.ts
  packages/contractkit/src/wrappers/GasPriceMinimum.ts
Labels: automerge

#1805 Make default node URL consistent in celocli
  packages/cli/src/commands/config/set.ts
  packages/docs/command-line-interface/config.md
Labels: automerge

#1714 Deploy new version of Celostats and minnor change from celo-blockchain
  .env
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/ethstats.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/celotool/src/lib/vm-testnet-utils.ts
  packages/helm-charts/ethstats/templates/ethstats.deployment.yaml
  packages/helm-charts/ethstats/templates/ethstats.secret.yaml
  packages/helm-charts/ethstats/values.yaml
  packages/helm-charts/testnet/templates/_helpers.tpl
  packages/helm-charts/testnet/templates/ethstats.secret.yaml
  packages/helm-charts/testnet/templates/txnode.statefulset.yaml
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
Labels: betanet-blocker, vx

#1847 Fix elect validators migration, deploy integration
  .env
  .env.integration
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/celotool/src/e2e-tests/utils.ts
  packages/celotool/src/lib/ethstats.ts
  packages/celotool/src/lib/generate_utils.ts
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/migrations/19_governance.ts
  packages/protocol/migrations/20_elect_validators.ts
  packages/protocol/migrationsConfig.js
  packages/walletkit/package.json
Labels: automerge, betanet-blocker

#1844 Update faucet to pull from the reserve when possible
  packages/celotool/src/cmds/account/faucet.ts
  packages/contractkit/src/wrappers/Reserve.ts
  packages/protocol/migrations/07_reserve.ts
Labels: automerge, betanet-blocker

#1688 Validator UX docs for baklava network
  packages/attestation-service/package.json
  packages/docs/getting-started/running-a-full-node.md
  packages/docs/getting-started/running-a-validator-alfajores.md
  packages/docs/getting-started/running-a-validator-baklava.md
  packages/docs/getting-started/running-a-validator.md
  packages/docs/getting-started/running-attestation-service.md
  scripts/run-docker-validator-network.sh
Labels: betanet-blocker

#1848 Serialize to hex string
  packages/contractkit/src/providers/celo-private-keys-subprovider.ts
Labels: automerge

#1849 Validator UX docs for baklava network (#1688)
  packages/cli/package.json
  packages/cli/src/commands/account/authorize.ts
  packages/cli/src/commands/account/balance.ts
  packages/cli/src/commands/account/proof-of-possession.ts
  packages/cli/src/commands/account/register.ts
  packages/cli/src/commands/election/current.ts
  packages/cli/src/commands/election/list.ts
  packages/cli/src/commands/election/run.ts
  packages/cli/src/commands/election/show.ts
  packages/cli/src/commands/exchange/dollars.ts
  packages/cli/src/commands/exchange/gold.ts
  packages/cli/src/commands/exchange/selldollar.ts
  packages/cli/src/commands/exchange/sellgold.ts
  packages/cli/src/commands/exchange/show.ts
  packages/cli/src/commands/lockedgold/show.ts
  packages/cli/src/commands/lockedgold/unlock.ts
  packages/cli/src/commands/lockedgold/withdraw.ts
  packages/cli/src/commands/network/parameters.ts
  packages/cli/src/commands/node/accounts.ts
  packages/cli/src/commands/transfer/dollars.ts
  packages/cli/src/commands/transfer/gold.ts
  packages/cli/src/commands/validator/affiliate.ts
  packages/cli/src/commands/validator/deaffiliate.ts
  packages/cli/src/commands/validator/deregister.ts
  packages/cli/src/commands/validator/list.ts
  packages/cli/src/commands/validator/requirements.ts
  packages/cli/src/commands/validator/show.ts
  packages/cli/src/commands/validator/update-bls-public-key.ts
  packages/cli/src/commands/validatorgroup/commission.ts
  packages/cli/src/commands/validatorgroup/deregister.ts
  packages/cli/src/commands/validatorgroup/list.ts
  packages/cli/src/commands/validatorgroup/register.ts
  packages/cli/src/utils/lockedgold.ts
  packages/contractkit/src/wrappers/Accounts.ts
  packages/docs/command-line-interface/account.md
  packages/docs/command-line-interface/election.md
  packages/docs/command-line-interface/exchange.md
  packages/docs/command-line-interface/introduction.md
  packages/docs/command-line-interface/lockedgold.md
  packages/docs/command-line-interface/network.md
  packages/docs/command-line-interface/node.md
  packages/docs/command-line-interface/transfer.md
  packages/docs/command-line-interface/validator.md
  packages/docs/command-line-interface/validatorgroup.md
  packages/docs/getting-started/running-a-full-node.md
  packages/docs/getting-started/running-a-validator-alfajores.md
  packages/docs/getting-started/running-a-validator-baklava.md
  packages/docs/getting-started/running-a-validator.md
  packages/docs/getting-started/running-attestation-service.md
  packages/docs/getting-started/using-the-cli.md
  scripts/run-docker-validator-network.sh
Labels: automerge, betanet-blocker

#1818 [Wallet] Update forno dev documentation
  packages/mobile/README.md
  packages/mobile/src/web3/contracts.ts
Labels: automerge

#1855 Fix typos
  packages/protocol/contracts/common/Accounts.sol
Labels: automerge

#1864 Leaderboard app with query
  packages/web/env-config.js.template
  packages/web/src/dev/Cover.tsx
  packages/web/src/dev/LeaderBoard.tsx
  packages/web/src/dev/LeaderBoardApp.tsx
  packages/web/static/locales/en/dev.json
Labels: betanet-blocker

#1863 Negate reversed conditional in faucet command
  packages/celotool/src/cmds/account/faucet.ts
Labels: automerge

#1857 Add warning about misusing pumba
  packages/helm-charts/README.md
Labels: automerge

#1916 Add account:show CLI command
  packages/contractkit/src/wrappers/Accounts.ts
Labels: automerge

#1915 Fix bug in LockedGold.relock wrapper
  packages/cli/src/commands/lockedgold/lock.test.ts
  packages/contractkit/src/wrappers/LockedGold.ts
Labels: automerge

#1924 Use cert manager instead of lego for k8s SSL certificates
  packages/celotool/src/lib/cluster.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/helm-charts/cert-manager-cluster-issuers/Chart.yaml
  packages/helm-charts/cert-manager-cluster-issuers/README.md
  packages/helm-charts/cert-manager-cluster-issuers/requirements.lock
  packages/helm-charts/cert-manager-cluster-issuers/requirements.yaml
  packages/helm-charts/cert-manager-cluster-issuers/templates/prod.clusterissuer.yaml
  packages/helm-charts/cert-manager-cluster-issuers/templates/staging.clusterissuer.yaml
  packages/helm-charts/cert-manager-cluster-issuers/values.yaml
Labels: automerge

#1919 Allow BLS info to be passed to validator:register without 0x prefix
  packages/cli/src/commands/validator/register.test.ts
  packages/cli/src/utils/command.ts
Labels: automerge

#1913 Dedicated signing of attestation messages
  .env
  packages/attestation-service/README.md
  packages/attestation-service/src/index.ts
  packages/attestation-service/src/requestHandlers/attestation.ts
  packages/attestation-service/src/requestHandlers/status.ts
  packages/celotool/src/lib/attestation-service.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/cli/src/commands/account/proof-of-possession.ts
  packages/contractkit/src/wrappers/Attestations.ts
  packages/docs/command-line-interface/account.md
  packages/docs/getting-started/running-a-validator.md
  packages/docs/getting-started/running-attestation-service.md
  packages/helm-charts/attestation-service/templates/attestation.configmap.yaml
  packages/helm-charts/attestation-service/templates/attestation.statefulset.yaml
Labels: automerge

#1923 Display current account locked gold requirement in lockedgold:show
  packages/cli/src/commands/lockedgold/show.ts
  packages/contractkit/src/wrappers/LockedGold.ts
  packages/contractkit/src/wrappers/Validators.ts
  packages/docs/command-line-interface/lockedgold.md
  packages/protocol/contracts/governance/Validators.sol
Labels: automerge

#1865 Bugfix: actually whitelist oracle account
  packages/celotool/src/lib/migration-utils.ts
Labels: automerge

#1928 Indicate account registration
  packages/cli/src/utils/checks.ts
Labels: automerge

#1931 Generate the pop for the attestation service with geth
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#1927 Check that we have provisioned phone numbers
  packages/attestation-service/src/sms/nexmo.ts
Labels: automerge

#1917 Minor edits to full-node and other docs
  packages/docs/command-line-interface/introduction.md
  packages/docs/getting-started/faucet.md
  packages/docs/getting-started/running-a-full-node.md
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#1866 Build Page for Baklava Launch Part 1
  packages/celotool/README.md
  packages/celotool/src/lib/generate_utils.ts
  packages/contractkit/src/test-utils/PromiEventStub.ts
  packages/mobile/package.json
  packages/verifier/package.json
  packages/web/env-config.js.enc
  packages/web/env-config.js.template
  packages/web/package.json
  packages/web/pages/_app.tsx
  packages/web/src/dev/BuildPage.tsx
  packages/web/src/dev/Cover.tsx
  packages/web/src/dev/Engage.tsx
  packages/web/src/dev/Feast.png
  packages/web/src/dev/Features.tsx
  packages/web/src/dev/FullStack.tsx
  packages/web/src/dev/LayersIllo.tsx
  packages/web/src/dev/LeaderBoard.tsx
  packages/web/src/dev/LeaderBoardApp.tsx
  packages/web/src/dev/LeaderBoardError.tsx
  packages/web/src/dev/LeaderBoardLoading.tsx
  packages/web/src/dev/Racer.tsx
  packages/web/src/dev/StackSection.tsx
  packages/web/src/dev/Transceive.tsx
  packages/web/src/dev/bakeoff.png
  packages/web/src/dev/cakeLayering.jpg
  packages/web/src/dev/cakeProtector.png
  packages/web/src/dev/chefs.png
  packages/web/src/icons/blog-dark.png
  packages/web/src/icons/documentation-dark.png
  packages/web/src/icons/download-dark.png
  packages/web/src/icons/faucet-dark.png
  packages/web/src/layout/BookLayout.tsx
  packages/web/src/react-native-aug.d.ts
  packages/web/src/shared/Button.3.tsx
  packages/web/src/shared/ConnectionFooter.tsx
  packages/web/src/shared/SocialChannels.tsx
  packages/web/src/shared/menu-items.ts
  packages/web/static/locales/en/community.json
  packages/web/static/locales/en/dev.json
  yarn.lock
Labels: automerge, betanet-blocker

#1932 Fix celotool expected cluster check
  packages/celotool/src/lib/cluster.ts
Labels: automerge

#1589 Add Terms for Stakeoff
  packages/web/pages/stake-off/terms.tsx
  packages/web/src/fonts/Fonts.tsx
  packages/web/src/react-native-aug.d.ts
  packages/web/src/terms/StakeOffTerms.tsx
  packages/web/static/locales/en/terms.json
Labels: automerge

#1925 cli: Fix #1897
  packages/cli/src/commands/account/balance.ts
  packages/docs/command-line-interface/introduction.md
Labels: automerge

#1929 Support more human readable log output
  packages/attestation-service/README.md
  packages/attestation-service/config/.env.development
  packages/attestation-service/index.d.ts
  packages/attestation-service/package.json
  packages/attestation-service/src/logger.ts
  yarn.lock
Labels: automerge

#1955 Avoid `liner: function not supported in this terminal`
  packages/docs/getting-started/running-a-full-node.md
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#1945 [NotificationService] Change exchange rate stored format (number timestamp and pair)
  packages/notification-service/src/exchange/exchangeQuery.ts
  packages/notification-service/src/firebase.ts
Labels: automerge

#1958 [Wallet] Fix iOS bundle script failing with our monorepo setup
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
Labels: automerge, wallet
