Repository celo-org/celo-monorepo, pull requests merged in 2019-07, with the labels that each got.

#9 Remove Celo Default Recipient
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/es-AR/sendFlow7.json
  packages/mobile/src/account/__snapshots__/Invite.test.tsx.snap
  packages/mobile/src/send/RecipientPicker.tsx
  packages/mobile/src/send/Send.tsx
  packages/mobile/src/send/SendAmount.tsx
Labels: ph-pilot

#74 Added secrets required to build sentry
  packages/mobile/.gitignore
  packages/mobile/android/sentry.properties.enc
  packages/mobile/ios/sentry.properties.enc
  scripts/key_placer.sh
Labels: wallet

#73 [contractkit]Cleanup: reference internal files directly
  packages/contractkit/src/attestations.ts
  packages/contractkit/src/contract-utils-v2.ts
  packages/contractkit/src/contract-utils.ts
  packages/contractkit/src/erc20-utils.ts
Labels: automerge, contract kit

#79 fixed spacing between calling code and country name
  packages/react-components/components/PhoneNumberInput.tsx
Labels: applications, automerge, wallet

#71 Stub out rewards and rewardWeight bug in Bonded Deposits contract
  packages/celotool/geth_tests/governance_tests.ts
  packages/protocol/contracts/governance/BondedDeposits.sol
Labels: automerge

#119 [web] Update Top Banner for Post Alfajores
  packages/web/src/header/BlueBanner.tsx
  packages/web/static/locales/en/common.json
Labels: web

#64 [web] Faucet and Invite Improvements
  packages/web/server/FirebaseClient.ts
  packages/web/server/controllers.ts
  packages/web/server/index.ts
  packages/web/src/dev/FaucetPage.tsx
  packages/web/src/download/Cover.tsx
  packages/web/src/download/Invite.tsx
  packages/web/src/download/PhoneIllo.tsx
  packages/web/src/fauceting/MicroComponents.tsx
  packages/web/src/fauceting/RequestFunds.tsx
  packages/web/src/fauceting/utils.ts
  packages/web/src/icons/Checkmark.tsx
  packages/web/static/locales/en/faucet.json
Labels: web

#142 [Wallet] Check valid code in clipboard prior to entering Enter invite code screen
  packages/mobile/src/invite/EnterInviteCode.tsx
Labels: applications, wallet

#99 Specify verification pool for validators
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#171 [cleanup]Enable `no-floating-promises` TS lint check
  packages/blockchain-api/tslint.json
  packages/cli/src/commands/exchange/selldollar.ts
  packages/cli/src/commands/exchange/sellgold.ts
  packages/cli/tslint.json
  packages/contractkit/tslint.json
  packages/protocol/tslint.json
  packages/verification-pool-api/tslint.json
Labels: tech-debt

#172 Added more tests for Enter Invite Code screen
  packages/mobile/src/invite/EnterInviteCode.test.tsx
  packages/mobile/src/invite/utils.test.ts
Labels: applications, wallet

#196 Navigation header fixed
  packages/mobile/src/backup/BackupIntroduction.tsx
  packages/mobile/src/backup/BackupPhrase.tsx
  packages/mobile/src/backup/BackupQuestion.tsx
  packages/mobile/src/backup/__snapshots__/Backup.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap
Labels: applications, automerge, wallet

#107 Change react-sms-android to react-send-intent
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/java/org/celo/mobile/MainApplication.java
  packages/mobile/android/settings.gradle
  packages/mobile/package.json
  packages/mobile/src/index.d.ts
  packages/mobile/src/invite/saga.test.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/notifications/EscrowedPaymentReminderNotification.tsx
  yarn.lock
Labels: applications, automerge, wallet

#198 Allow selection of recipients in single taps when keyboard is up
  packages/mobile/src/account/__snapshots__/Invite.test.tsx.snap
  packages/mobile/src/send/RecipientPicker.tsx
Labels: applications, automerge, wallet

#106 [Wallet] Send/Receive from Addresses
  packages/mobile/src/account/Account.test.tsx
  packages/mobile/src/account/__snapshots__/Invite.test.tsx.snap
  packages/mobile/src/identity/contactMapping.ts
  packages/mobile/src/paymentRequest/PaymentRequestNotification.test.tsx
  packages/mobile/src/paymentRequest/PaymentRequestNotification.tsx
  packages/mobile/src/qrcode/utils.ts
  packages/mobile/src/send/RecipientItem.tsx
  packages/mobile/src/send/RecipientPicker.tsx
  packages/mobile/src/send/RequestConfirmation.tsx
  packages/mobile/src/send/Send.tsx
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/actions.ts
  packages/mobile/src/send/reducers.ts
  packages/mobile/src/send/saga.test.ts
  packages/mobile/src/send/saga.ts
  packages/mobile/src/utils/recipient.test.ts
  packages/mobile/src/utils/recipient.ts
  packages/mobile/test/values.ts
  packages/react-components/components/ContactCircle.tsx
Labels: applications, wallet

#203 [circleci]Enable more testing
  .circleci/config.yml
Labels: tech-debt

#242 Spanish tweaks
  packages/mobile/locales/es-AR/nuxVerification2.json
  packages/mobile/locales/es-AR/walletFlow5.json
Labels: automerge

#117 [web] Connect Page Data Fetching Refactor for Perf
  packages/web/fullstack/ArticleProps.ts
  packages/web/fullstack/EventProps.ts
  packages/web/server/EventHelpers.ts
  packages/web/server/index.ts
  packages/web/server/mediumAPI.ts
  packages/web/src/community/Articles.tsx
  packages/web/src/community/PastEventsPage.tsx
  packages/web/src/community/connect/ArticleData.tsx
  packages/web/src/community/connect/ArticlesSection.tsx
  packages/web/src/community/connect/ConnectPage.tsx
  packages/web/src/community/connect/EventRow.tsx
  packages/web/src/community/connect/Events.tsx
  packages/web/src/community/connect/EventsData.tsx
Labels: web
