Repository celo-org/celo-monorepo, pull requests merged in 2020-04, with the labels that each got.

#3174 Fund release gold signing keys
  packages/protocol/contracts/common/interfaces/IAccounts.sol
  packages/protocol/contracts/governance/ReleaseGold.sol
  packages/protocol/contracts/governance/interfaces/IReleaseGold.sol
  packages/protocol/scripts/truffle/releaseGoldExampleConfigs.json
  packages/protocol/test/governance/release_gold.ts
Labels: automerge

#3256 [Ledger] personal sign fix
  packages/contractkit/src/wallets/ledger-wallet.test.ts
  packages/contractkit/src/wallets/ledger-wallet.ts
  packages/docs/developer-resources/contractkit/reference/classes/_wallets_ledger_wallet_.ledgerwallet.md
  packages/docs/developer-resources/contractkit/reference/modules/_wallets_ledger_wallet_.md
Labels: automerge

#3257 [PhoneNumPriv] Fix paths for firebase configs
  packages/phone-number-privacy/package.json
  packages/phone-number-privacy/src/config.ts
Labels: automerge

#3225 Celo Papers Page
  packages/web/pages/papers.tsx
  packages/web/public/papers/Celo_Stability_Analysis.pdf
  packages/web/public/papers/celo-wp-simplified-chinese.pdf
  packages/web/public/static/locales/en/papers.json
  packages/web/server/index.ts
  packages/web/src/_page-tests/__snapshots__/papers.test.tsx.snap
  packages/web/src/_page-tests/papers.test.tsx
  packages/web/src/i18n.ts
  packages/web/src/terms/Papers.tsx
  packages/web/src/utils/i18nForTests.ts
Labels: automerge

#3228 tracking of pages
  packages/web/pages/_app.tsx
  packages/web/src/analytics/analytics.ts
Labels: automerge

#3182 Form Improvement (Errors, part 1)
  packages/web/__mocks__/cross-fetch.ts
  packages/web/jest.config.js
  packages/web/jestSetupAfter.ts
  packages/web/package.json
  packages/web/src/_page-tests/__snapshots__/alliance.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/community.test.tsx.snap
  packages/web/src/_page-tests/past-events.test.tsx
  packages/web/src/alliance/SignupForm.tsx
  packages/web/src/community/EcoFund.tsx
  packages/web/src/community/connect/EcoFund.test.tsx
  packages/web/src/community/connect/FellowshipForm.test.tsx
  packages/web/src/community/connect/FellowshipForm.tsx
  packages/web/src/forms/EmailForm.test.tsx
  packages/web/src/forms/ErrorDisplay.tsx
  packages/web/src/forms/FormComponents.tsx
  packages/web/src/forms/LabeledInput.test.tsx
  packages/web/src/forms/LabeledInput.tsx
  yarn.lock
Labels: automerge

#3254 Sentry Inspired Fixes
  packages/web/env-config.js.template
  packages/web/pages/api/bytes.ts
  packages/web/server/addToCRM.ts
  packages/web/server/index.ts
  packages/web/src/utils/utils.ts
Labels: automerge

#3226 [Wallet] Use decimal separator appropriate to localisation
  packages/mobile/__mocks__/react-native-localize.ts
  packages/mobile/package.json
  packages/mobile/src/app/App.tsx
  packages/mobile/src/app/actions.ts
  packages/mobile/src/components/CurrencyDisplay.tsx
  packages/mobile/src/exchange/CeloGoldHistoryChart.tsx
  packages/mobile/src/exchange/__snapshots__/CeloGoldHistoryChart.test.tsx.snap
  packages/mobile/src/send/SendAmount.test.tsx
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/__snapshots__/SendAmount.test.tsx.snap
  packages/mobile/src/utils/formatting.test.ts
  packages/mobile/src/utils/formatting.ts
  packages/mobile/src/utils/withDecimalSeparator.tsx
  packages/react-components/components/ValidatedTextInput.tsx
  packages/utils/src/inputValidation.test.ts
  packages/utils/src/inputValidation.ts
  packages/utils/src/parsing.ts
Labels: automerge

#3274 [M01] Incorrect value of MAX_UINT
  packages/protocol/contracts/governance/ReleaseGold.sol
Labels: audit-fix

#3277 [L15] Missing revert messages in require statements
  packages/protocol/contracts/common/libraries/ReentrancyGuard.sol
Labels: audit-fix

#3278 [L16] Unclear overwrite of commission update queue
  packages/cli/src/commands/validatorgroup/commission.ts
  packages/contractkit/src/wrappers/Validators.test.ts
  packages/contractkit/src/wrappers/Validators.ts
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_validators_.validatorswrapper.md
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/test/governance/validators.ts
Labels: audit-fix

#3276 [L14] maxDistribution can be set before the factory sends the gold
  packages/protocol/contracts/governance/ReleaseGold.sol
Labels: audit-fix

#3247 AKS prometheus deployment with celotool
  packages/celotool/src/cmds/deploy/destroy/aks-prometheus.ts
  packages/celotool/src/cmds/deploy/initial/aks-prometheus.ts
  packages/celotool/src/cmds/deploy/initial/blockscout.ts
  packages/celotool/src/lib/aks-prometheus.ts
  packages/celotool/src/lib/azure.ts
  packages/celotool/src/lib/cluster.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/celotool/src/lib/service-account-utils.ts
  packages/helm-charts/prometheus-stackdriver/Chart.yaml
  packages/helm-charts/prometheus-stackdriver/templates/configmap.yaml
  packages/helm-charts/prometheus-stackdriver/templates/deployment.yaml
  packages/helm-charts/prometheus-stackdriver/templates/gcloud-service-account-key-secret.yaml
  packages/helm-charts/prometheus-stackdriver/templates/service-account.yaml
Labels: automerge

#3281 [N04] MockReserve.sol has mintToken function
  packages/protocol/contracts/stability/test/MockReserve.sol
Labels: audit-fix

#3282 [L13] Duplicated code in updatePublicKeys
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/test/governance/validators.ts
Labels: audit-fix

#3301 Docs: new baklava part II
  packages/docs/GLOSSARY.md
  packages/docs/getting-started/running-a-full-node.md
  packages/docs/getting-started/running-a-validator-in-baklava.md
Labels: docs

#3272 [L03] Missing revert messages in require statements (update)
  packages/protocol/contracts/common/FixidityLib.sol
Labels: audit-fix

#2866 Private tx nodes for cLabs services
  .env
  .env.alfajores
  .env.alfajoresstaging
  .env.baklava
  .env.baklavastaging
  .env.integration
  .env.integrationtesting
  .env.mnemonic.integrationtesting.enc
  .env.pilot
  .env.pilotstaging
  packages/celotool/genesis_baklava.json
  packages/celotool/src/cmds/gcp/remove-leaked-forwarding-rules.ts
  packages/celotool/src/cmds/ssh-vm-node.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/geth.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/celotool/src/lib/kubernetes.ts
  packages/celotool/src/lib/oracle.ts
  packages/celotool/src/lib/vm-testnet-utils.ts
  packages/helm-charts/blockscout/values.yaml
  packages/helm-charts/testnet/templates/_helpers.tpl
  packages/helm-charts/testnet/templates/proxy.service.yaml
  packages/helm-charts/testnet/templates/proxy.statefulset.yaml
  packages/helm-charts/testnet/templates/txnode-private.service.yaml
  packages/helm-charts/testnet/templates/txnode-private.statefulset.yaml
  packages/helm-charts/testnet/templates/txnode.service.yaml
  packages/helm-charts/testnet/templates/txnode.statefulset.yaml
  packages/helm-charts/testnet/templates/validators.service.yaml
  packages/protocol/truffle-config.js
  packages/terraform-modules/testnet/main.tf
  packages/terraform-modules/testnet/modules/full-node/main.tf
  packages/terraform-modules/testnet/modules/full-node/startup.sh
  packages/terraform-modules/testnet/modules/full-node/variables.tf
  packages/terraform-modules/testnet/modules/tx-node-load-balancer/main.tf
  packages/terraform-modules/testnet/modules/tx-node-load-balancer/variables.tf
  packages/terraform-modules/testnet/modules/validator/startup.sh
  packages/terraform-modules/testnet/modules/validator/variables.tf
  packages/terraform-modules/testnet/variables.tf
  scripts/key_placer.sh
Labels: automerge

#3339 Update ContractKit doc to reflect Readme.md
  packages/docs/developer-resources/contractkit/reference/README.md
Labels: automerge

#3335 Add release gold docs
  packages/docs/SUMMARY.md
  packages/docs/celo-codebase/protocol/release-gold/README.md
Labels: automerge

#3338 Simplify PhoneNumPriv Readme text a bit
  packages/phone-number-privacy/README.md
Labels: automerge

#3346 [Wallet] Remove obsolete reference to build:sdk
  packages/mobile/fastlane/Fastfile
  packages/mobile/package.json
Labels: automerge

#3341 Fix election:vote which uses an unstable sort
  packages/cli/package.json
  packages/contractkit/src/wrappers/Election.ts
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_election_.electionwrapper.md
  packages/docs/getting-started/running-a-validator-in-baklava.md
Labels: automerge

#3297 Form Error + Loading + Success States
  packages/web/public/static/locales/en/common.json
  packages/web/public/static/locales/en/community.json
  packages/web/src/_page-tests/__snapshots__/alliance.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/community.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/developers/__snapshots__/Index.test.tsx.snap
  packages/web/src/_page-tests/validators/__snapshots__/index.test.tsx.snap
  packages/web/src/alliance/SignupForm.test.tsx
  packages/web/src/alliance/SignupForm.tsx
  packages/web/src/community/EcoFund.tsx
  packages/web/src/community/connect/CoverArea.tsx
  packages/web/src/community/connect/EcoFund.test.tsx
  packages/web/src/community/connect/FellowSection.tsx
  packages/web/src/community/connect/FellowshipForm.test.tsx
  packages/web/src/community/connect/FellowshipForm.tsx
  packages/web/src/fauceting/PhoneInput.tsx
  packages/web/src/fauceting/RequestFunds.tsx
  packages/web/src/forms/CheckboxWithLabel.tsx
  packages/web/src/forms/EmailForm.test.tsx
  packages/web/src/forms/EmailForm.tsx
  packages/web/src/forms/ErrorDisplay.tsx
  packages/web/src/forms/Form.tsx
  packages/web/src/forms/FormComponents.tsx
  packages/web/src/forms/LabeledInput.tsx
  packages/web/src/forms/MessageDisplay.tsx
  packages/web/src/forms/SubmitButton.tsx
  packages/web/src/forms/SuccessDisplay.tsx
  packages/web/src/forms/TextInput.tsx
  packages/web/src/home/version3/HomeCover.tsx
  packages/web/src/home/version3/HomeEmail.tsx
  packages/web/src/shared/Button.3.tsx
  packages/web/src/shared/ConnectionFooter.tsx
Labels: automerge

#3362 Upgrade contractkit->0.3.4-dev and celocli->0.0.38-dev
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/leaderboard/package.json
  packages/mobile/package.json
Labels: automerge

#3365 Added new dependencies to Dockerfile. Fix build
  dockerfiles/cli/Dockerfile
Labels: automerge

#3347 New oracle helm chart
  .env
  .env.alfajores
  .env.alfajoresstaging
  .env.baklava
  .env.baklavastaging
  .env.integration
  .env.rc0
  packages/celotool/src/cmds/deploy/destroy/mock-oracle.ts
  packages/celotool/src/cmds/deploy/destroy/oracle.ts
  packages/celotool/src/cmds/deploy/initial/mock-oracle.ts
  packages/celotool/src/cmds/deploy/initial/oracle.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/generate_utils.ts
  packages/celotool/src/lib/mock-oracle.ts
  packages/celotool/src/lib/oracle.ts
  packages/helm-charts/mock-oracle/.helmignore
  packages/helm-charts/mock-oracle/Chart.yaml
  packages/helm-charts/mock-oracle/templates/oracle.cronjob.yaml
  packages/helm-charts/mock-oracle/templates/oracle.secret.yaml
  packages/helm-charts/oracle/Chart.yaml
  packages/helm-charts/oracle/templates/_helper.tpl
  packages/helm-charts/oracle/templates/statefulset.yaml
Labels: automerge

#3343 Fix blockscout syncing issues
  .env.baklavastaging
  packages/celotool/src/lib/blockscout.ts
  packages/helm-charts/testnet/templates/_helpers.tpl
  packages/helm-charts/testnet/templates/txnode-private.statefulset.yaml
  packages/helm-charts/testnet/templates/txnode.statefulset.yaml
  packages/terraform-modules/testnet/main.tf
  packages/terraform-modules/testnet/modules/full-node/main.tf
  packages/terraform-modules/testnet/modules/full-node/startup.sh
  packages/terraform-modules/testnet/modules/full-node/variables.tf
Labels: automerge

#3363 Updated celostats commits
  .env
Labels: automerge

#3352 Web Scripts
  .circleci/config.yml
  packages/web/package.json
  packages/web/src/_page-tests/validators/__snapshots__/index.test.tsx.snap
  packages/web/src/dev/DeveloperUpdates.tsx
  packages/web/src/dev/Engage.tsx
Labels: automerge

#3345 Improve UI of Validator Explorer
  packages/web/src/_page-tests/validators/__snapshots__/explore.test.tsx.snap
  packages/web/src/dev/ValidatorsList.tsx
  packages/web/src/dev/ValidatorsListRow.tsx
Labels: automerge

#3360 Add revokeAllActive to Election contract
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/contracts/governance/interfaces/IElection.sol
  packages/protocol/contracts/governance/test/MockElection.sol
Labels: automerge

#3371 [celocli] Add ledger options for addresses retrieve
  packages/cli/src/base.ts
Labels: automerge

#3351 Improved unit tests
  packages/protocol/test/common/multisig.ts
  packages/protocol/test/identity/escrow.ts
Labels: audit-fix, automerge

#3381 [Doc] Unlock an account on proxy and new celostats address on baklava
  packages/docs/getting-started/running-a-validator-in-baklava.md
Labels: docs

#3373 [Wallet] Fix invite redemption gas handling and gas price calculation
  packages/mobile/src/config.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/fees/saga.test.ts
  packages/mobile/src/invite/saga.test.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/send/saga.ts
  packages/mobile/src/tokens/saga.ts
  packages/mobile/src/transactions/contract-utils.ts
  packages/mobile/src/web3/gas.test.ts
  packages/mobile/src/web3/gas.ts
  packages/mobile/src/web3/utils.ts
Labels: automerge

#3369 [Wallet] Protect initial view of a backup key with PIN
  packages/mobile/src/backup/BackupIntroduction.tsx
Labels: automerge

#3376 Design Iteration on h3 size
  packages/web/src/_page-tests/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/styles.ts
Labels: automerge

#3386 Fix bug in exchange CLI
  packages/cli/src/commands/exchange/dollars.ts
  packages/cli/src/commands/exchange/gold.ts
  packages/contractkit/src/wrappers/Exchange.test.ts
  packages/contractkit/src/wrappers/Exchange.ts
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_exchange_.exchangewrapper.md
Labels: automerge

#3377 Gastonponti/ledger address validation
  packages/contractkit/src/wallets/ledger-wallet.test.ts
  packages/contractkit/src/wallets/ledger-wallet.ts
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/classes/_wallets_ledger_wallet_.ledgerwallet.md
  packages/docs/developer-resources/contractkit/reference/enums/_wallets_ledger_wallet_.addressvalidation.md
  packages/docs/developer-resources/contractkit/reference/modules/_wallets_ledger_wallet_.md
Labels: automerge

#3370 Pulsing Dots with less
  SETUP.md
  packages/mobile/src/verify/VerificationInterstitialScreen.tsx
  packages/react-components/components/PulsingDot.tsx
Labels: automerge

#3404 Fixes typo for addressPayment on rewards:show
  packages/cli/src/commands/rewards/show.ts
Labels: automerge

#2954 Remove GoldToken as a FeeCurrencyWhitelist
  packages/protocol/migrations/04_goldtoken.ts
Labels: RC1

#3406 [ReleaseGold] Fix bug in RG.transfer_dollars
  packages/cli/src/commands/releasegold/transfer-dollars.ts
  packages/protocol/contracts/common/MultiSig.sol
Labels: automerge

#3266 Adjust migrationsConfig for RC1
  packages/contractkit/src/wrappers/SortedOracles.test.ts
  packages/dev-utils/src/migration-override.json
  packages/protocol/migrations/24_governance.ts
  packages/protocol/migrations/26_governance_setup.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/test/common/integration.ts
Labels: RC1, automerge

#3367 [contractkit] SortedOracles: check for and remove expired reports
  packages/contractkit/src/wrappers/SortedOracles.test.ts
  packages/contractkit/src/wrappers/SortedOracles.ts
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_sortedoracles_.sortedoracleswrapper.md
Labels: automerge

#3401 New Community Page Cover
  packages/web/package.json
  packages/web/pages/community.tsx
  packages/web/src/_page-tests/__snapshots__/community.test.tsx.snap
  packages/web/src/animate/LottieBase.tsx
  packages/web/src/community/CommunityPage.tsx
  packages/web/src/community/connect/CeloRoles.tsx
  packages/web/src/community/connect/CoverArea.tsx
  packages/web/src/community/lottie/all.json
  packages/web/src/header/Header.3.tsx
  packages/web/src/shared/Spinner.tsx
  packages/web/src/styles.ts
Labels: automerge

#3156 Adding contractKit and cli domain claims support
  packages/cli/src/commands/account/claim-domain.ts
  packages/cli/src/utils/identity.ts
  packages/contractkit/src/identity/claims/claim.ts
  packages/contractkit/src/identity/claims/domain.test.ts
  packages/contractkit/src/identity/claims/types.ts
  packages/contractkit/src/identity/claims/verify.ts
  packages/contractkit/src/identity/metadata.ts
  packages/docs/developer-resources/contractkit/reference/classes/_identity_metadata_.identitymetadatawrapper.md
  packages/docs/developer-resources/contractkit/reference/modules/_identity_claims_claim_.md
  packages/docs/developer-resources/contractkit/reference/modules/_identity_claims_types_.md
  packages/docs/developer-resources/contractkit/reference/modules/_identity_claims_verify_.md
  packages/docs/developer-resources/contractkit/reference/modules/_identity_metadata_.md
  packages/metadata-crawler/README.md
  packages/metadata-crawler/index.d.ts
  packages/metadata-crawler/package.json
  packages/metadata-crawler/src/crawler.ts
  packages/metadata-crawler/src/env.ts
  packages/metadata-crawler/src/logger.ts
  packages/metadata-crawler/tsconfig.json
  yarn.lock
Labels: automerge

#3403 [ContractKit] Ledger token data
  packages/contractkit/src/wallets/ledger-utils/data.ts
  packages/contractkit/src/wallets/ledger-utils/tokens.ts
  packages/contractkit/src/wallets/ledger-wallet.test.ts
  packages/contractkit/src/wallets/ledger-wallet.ts
  packages/contractkit/types/hw-app-eth.d.ts
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/classes/_wallets_ledger_wallet_.ledgerwallet.md
  packages/docs/developer-resources/contractkit/reference/enums/_wallets_ledger_wallet_.addressvalidation.md
  packages/docs/developer-resources/contractkit/reference/globals.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wallets_ledger_utils_tokens_.api.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wallets_ledger_utils_tokens_.tokeninfo.md
  packages/docs/developer-resources/contractkit/reference/modules/_wallets_ledger_utils_data_.md
  packages/docs/developer-resources/contractkit/reference/modules/_wallets_ledger_utils_tokens_.md
  packages/docs/developer-resources/contractkit/reference/modules/_wallets_ledger_wallet_.md
Labels: automerge

#3413 Update Velocity Paper
  packages/web/public/papers/CBDC_Velocity_Copic-Franke.pdf
  packages/web/public/papers/cLabs_CBDC_Velocity_v2_04-2020.pdf
  packages/web/server/index.ts
Labels: automerge

#3415 [ReleaseGold] Making set-beneficiary better and adding tests
  packages/cli/src/commands/releasegold/set-beneficiary.test.ts
  packages/cli/src/commands/releasegold/set-beneficiary.ts
  packages/cli/src/commands/releasegold/set-max-distribution.ts
  packages/cli/src/commands/releasegold/transfer-dollars.test.ts
  packages/cli/src/utils/checks.ts
  packages/docs/command-line-interface/releasegold.md
Labels: automerge

#3332 Icon Search
  packages/web/fullstack/AssetProps.ts
  packages/web/package.json
  packages/web/public/static/locales/en/brand.json
  packages/web/server/AssetBase.test.ts
  packages/web/server/AssetBase.ts
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
  packages/web/src/_page-tests/experience/icons.test.tsx
  packages/web/src/_page-tests/experience/key-imagery.test.tsx
  packages/web/src/brandkit/Explorer.test.tsx
  packages/web/src/brandkit/Explorer.tsx
  packages/web/src/brandkit/IconsPage.tsx
  packages/web/src/brandkit/KeyImagery.tsx
  packages/web/src/brandkit/Search.tsx
  packages/web/src/brandkit/common/Showcase.tsx
  packages/web/src/forms/TextInput.tsx
  yarn.lock
Labels: automerge

#3397 Add oracle:remove-expired-reports CLI command
  packages/cli/src/commands/oracle/remove-expired-reports.ts
  packages/cli/src/commands/oracle/reports.ts
  packages/contractkit/src/wrappers/Exchange.ts
  packages/contractkit/src/wrappers/SortedOracles.ts
  packages/docs/command-line-interface/oracle.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_exchange_.exchangewrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_sortedoracles_.sortedoracleswrapper.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_exchange_.exchangeconfig.md
Labels: automerge

#3408 Release celocli 0.0.40 and bump version numbers
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/leaderboard/package.json
  packages/metadata-crawler/package.json
  packages/mobile/package.json
  packages/protocol/package.json
  packages/react-components/package.json
  packages/transaction-metrics-exporter/package.json
  packages/utils/package.json
  packages/verifier/package.json
Labels: automerge

#3427 Bump contractkit dev version to 0.3.7-dev in preparation for publishing 0.3.6
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/leaderboard/package.json
  packages/metadata-crawler/package.json
  packages/mobile/package.json
Labels: automerge

#3412 Add claimed domains on validator explorer
  packages/web/src/_page-tests/validators/__snapshots__/explore.test.tsx.snap
  packages/web/src/_page-tests/validators/explore.test.tsx
  packages/web/src/dev/ValidatorsList.tsx
  packages/web/src/dev/ValidatorsListApp.tsx
  packages/web/src/dev/ValidatorsListRow.tsx
  packages/web/src/dev/ValidatorsListStyles.tsx
Labels: automerge

#3380 Fixes and config updates from Alfajores network upgrade and Wallet v1.7.0
  .env.alfajores
  .env.alfajoresstaging
  .env.mnemonic.alfajores.enc
  dockerfiles/cli/Dockerfile
  packages/blockchain-api/.env
  packages/blockchain-api/app.alfajores.yaml
  packages/blockchain-api/package.json
  packages/blockchain-api/src/blockscout.ts
  packages/blockchain-api/src/index.ts
  packages/blockchain-api/src/utils.ts
  packages/blockchain-api/test/blockscout.test.ts
  packages/blockchain-api/test/mockTokenTxs.ts
  packages/celotool/src/cmds/deploy/upgrade/blockscout.ts
  packages/celotool/src/lib/blockscout.ts
  packages/cli/start_geth.sh
  packages/helm-charts/attestation-service/templates/attestation.statefulset.yaml
  packages/mobile/Gemfile.lock
  packages/mobile/__mocks__/@celo/contractkit/index.ts
  packages/mobile/__mocks__/react-native-secure-randombytes.ts
  packages/mobile/android/.settings/org.eclipse.buildship.core.prefs
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/res/xml/backup_rules.xml
  packages/mobile/android/gradle.properties
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo-tvOS/Info.plist
  packages/mobile/ios/celo-tvOSTests/Info.plist
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/ios/celo/Info.plist
  packages/mobile/ios/celoTests/Info.plist
  packages/mobile/package.json
  packages/mobile/src/account/Account.tsx
  packages/mobile/src/account/__snapshots__/Account.test.tsx.snap
  packages/mobile/src/escrow/actions.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/exchange/saga.ts
  packages/mobile/src/flags.ts
  packages/mobile/src/geth/geth.ts
  packages/mobile/src/index.d.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/transactions/send.ts
  packages/mobile/src/verify/VerificationInputScreen.tsx
  packages/mobile/src/web3/saga.test.ts
  packages/mobile/src/web3/saga.ts
  packages/notification-service/package.json
  packages/protocol/migrationsConfig.js
  packages/protocol/package.json
  packages/protocol/truffle-config.js
  yarn.lock
Labels: automerge

#3440 [Docs] Update ledger instructions to list only one address
  packages/docs/operations-manual/using-a-ledger-wallet.md
Labels: automerge, docs

#3031 Blockscout package fixes
  packages/celotool/src/cmds/deploy/destroy/blockscout.ts
  packages/celotool/src/cmds/deploy/initial/blockscout.ts
  packages/celotool/src/cmds/deploy/migrate/blockscout.ts
  packages/celotool/src/cmds/deploy/switch/blockscout.ts
  packages/celotool/src/cmds/deploy/upgrade/blockscout.ts
  packages/celotool/src/lib/blockscout.ts
  packages/celotool/src/lib/cluster.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/helm-charts/blockscout/templates/blockscout-indexer.deployment.yaml
  packages/helm-charts/blockscout/templates/blockscout-migration.job.yaml
  packages/helm-charts/blockscout/templates/blockscout-web.deployment.yaml
  packages/helm-charts/blockscout/values.yaml
  packages/terraform-modules/testnet/main.tf
  packages/terraform-modules/testnet/modules/tx-node-load-balancer/variables.tf
Labels: automerge

#3364 Oracle MVP infrastructure
  .env.alfajoresstaging
  .env.rc0
  packages/celotool/src/lib/oracle.ts
  packages/helm-charts/oracle/templates/pkey-secret.yaml
  packages/helm-charts/oracle/templates/statefulset.yaml
Labels: automerge

#3411 Updated initial reserve target allocation
  packages/protocol/migrationsConfig.js
Labels: RC1

#3428 Parse revert reason from failed contractkit txs
  packages/contractkit/src/kit.ts
  packages/contractkit/src/utils/tx-params-normalizer.ts
  packages/contractkit/src/utils/web3-utils.ts
  packages/docs/developer-resources/contractkit/reference/classes/_kit_.contractkit.md
  packages/docs/developer-resources/contractkit/reference/classes/_utils_tx_params_normalizer_.txparamsnormalizer.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_kit_.kitoptions.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_kit_.networkconfig.md
  packages/docs/developer-resources/contractkit/reference/modules/_kit_.md
  packages/docs/developer-resources/contractkit/reference/modules/_utils_web3_utils_.md
Labels: automerge

#3449 Reducing initial reserveFraction.
  packages/protocol/migrationsConfig.js
Labels: RC1

#3444 [cli] Add account:list command
  packages/cli/src/commands/account/list.ts
  packages/cli/src/commands/node/accounts.ts
  packages/docs/command-line-interface/account.md
  packages/docs/operations-manual/using-a-ledger-wallet.md
Labels: automerge

#3430 Adding BucketsUpdated event.
  packages/protocol/contracts/stability/Exchange.sol
  packages/protocol/test/stability/exchange.ts
Labels: RC1

#3443 [utils] Add Account generation util functions
  packages/celotool/package.json
  packages/celotool/src/lib/generate_utils.ts
  packages/cli/package.json
  packages/cli/src/commands/account/new.ts
  packages/cli/src/utils/key_generator.test.ts
  packages/cli/src/utils/key_generator.ts
  packages/contractkit/src/wallets/ledger-wallet.ts
  packages/docs/command-line-interface/account.md
  packages/docs/developer-resources/contractkit/reference/classes/_wallets_ledger_wallet_.ledgerwallet.md
  packages/docs/developer-resources/contractkit/reference/enums/_wallets_ledger_wallet_.addressvalidation.md
  packages/docs/developer-resources/contractkit/reference/modules/_wallets_ledger_wallet_.md
  packages/metadata-crawler/.gitignore
  packages/utils/package.json
  packages/utils/src/account.test.ts
  packages/utils/src/account.ts
  packages/utils/src/index.ts
  yarn.lock
Labels: automerge

#3445 [cli] Change Ledger defaults
  packages/cli/src/base.ts
  packages/docs/operations-manual/using-a-ledger-wallet.md
Labels: automerge

#3454 [ReleaseGold] Set beneficiary updates the multisig owners
  packages/cli/src/commands/releasegold/set-beneficiary.test.ts
  packages/cli/src/commands/releasegold/set-beneficiary.ts
  packages/contractkit/src/wrappers/MultiSig.ts
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_multisig_.multisigwrapper.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_multisig_.transactiondata.md
Labels: automerge

#3417 Setters for the tobin tax
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/migrations/08_reserve.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/test/governance/epochrewards.ts
  packages/protocol/test/stability/reserve.ts
Labels: RC1, do not merge

#3457 [upgrade] utils -> 0.1.11-dev, contractkit -> 0.3.8-dev, celocli-> 0.0.43-dev
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/leaderboard/package.json
  packages/metadata-crawler/package.json
  packages/mobile/package.json
  packages/protocol/package.json
  packages/react-components/package.json
  packages/transaction-metrics-exporter/package.json
  packages/utils/package.json
  packages/verifier/package.json
Labels: automerge

#3431 [Wallet] Gold tab UI + decimal input with , fix
  packages/mobile/src/exchange/CeloGoldHistoryChart.test.tsx
  packages/mobile/src/exchange/CeloGoldHistoryChart.tsx
  packages/mobile/src/exchange/ExchangeTradeScreen.tsx
  packages/mobile/src/exchange/__snapshots__/CeloGoldHistoryChart.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/utils/formatting.test.ts
  packages/mobile/src/utils/formatting.ts
  packages/mobile/src/utils/withDecimalSeparator.tsx
  packages/utils/src/parsing.test.ts
  packages/utils/src/parsing.ts
Labels: automerge

#3421 Add server initiated errors to Forms
  packages/web/public/static/locales/en/common.json
  packages/web/src/_page-tests/__snapshots__/alliance.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/community.test.tsx.snap
  packages/web/src/alliance/SignupForm.test.tsx
  packages/web/src/alliance/SignupForm.tsx
  packages/web/src/community/EcoFund.tsx
  packages/web/src/community/connect/FellowshipForm.test.tsx
  packages/web/src/community/connect/FellowshipForm.tsx
  packages/web/src/forms/EmailForm.tsx
  packages/web/src/forms/ErrorDisplay.tsx
  packages/web/src/forms/Form.tsx
  packages/web/src/forms/LabeledInput.tsx
Labels: automerge

#3468 New Kicks
  packages/web/public/static/locales/en/common.json
  packages/web/src/_page-tests/__snapshots__/alliance.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/community.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/developers/__snapshots__/Index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/_page-tests/validators/__snapshots__/index.test.tsx.snap
  packages/web/src/alliance/Main.tsx
  packages/web/src/community/CommunityPage.tsx
  packages/web/src/dev/BuildPage.tsx
  packages/web/src/dev/DevelopersPage.tsx
  packages/web/src/header/Header.3.tsx
  packages/web/src/home/Home.tsx
  packages/web/src/home/version3/HomeEmail.tsx
  packages/web/src/layout/GridRow.tsx
  packages/web/src/shared/ChangeStory.tsx
  packages/web/src/shared/ConnectionFooter.tsx
  packages/web/src/shared/Footer.test.tsx
  packages/web/src/shared/Footer.tsx
  packages/web/src/shared/FooterColumn.tsx
  packages/web/src/shared/MobileMenu.tsx
  packages/web/src/shared/__snapshots__/Footer.test.tsx.snap
  packages/web/src/shared/menu-items.ts
Labels: automerge

#3466 RC1 Documentation
  packages/docs/SUMMARY.md
  packages/docs/getting-started/rc1.md
  packages/docs/getting-started/running-a-validator-in-rc1.md
Labels: RC1, docs

#3489 [cli] Fix types for cli
  packages/cli/src/base.ts
  packages/docs/command-line-interface/account.md
  packages/docs/command-line-interface/election.md
  packages/docs/command-line-interface/exchange.md
  packages/docs/command-line-interface/governance.md
  packages/docs/command-line-interface/identity.md
  packages/docs/command-line-interface/lockedgold.md
  packages/docs/command-line-interface/node.md
  packages/docs/command-line-interface/oracle.md
  packages/docs/command-line-interface/releasegold.md
  packages/docs/command-line-interface/reserve.md
  packages/docs/command-line-interface/transfer.md
  packages/docs/command-line-interface/validator.md
  packages/docs/command-line-interface/validatorgroup.md
Labels: automerge

#3480 Update Accounts.sol
  packages/protocol/contracts/common/Accounts.sol
Labels: RC1

#3488 Docs: Correct Baklava typo (Firts vs. First)
  packages/docs/getting-started/running-a-validator-in-baklava.md
Labels: automerge

#3496 Improvements & Fixes for RC1 Documentation
  packages/docs/getting-started/running-a-validator-in-rc1.md
Labels: RC1, docs

#3497 Update running-a-validator-in-rc1.md
  packages/docs/getting-started/running-a-validator-in-rc1.md
Labels: RC1, docs

#3475 Add differentiating slashing events
  packages/protocol/contracts/governance/DoubleSigningSlasher.sol
  packages/protocol/contracts/governance/DowntimeSlasher.sol
  packages/protocol/contracts/governance/GovernanceSlasher.sol
  packages/protocol/test/governance/double_signing_slasher.ts
  packages/protocol/test/governance/downtime_slasher.ts
  packages/protocol/test/governance/governance_slasher.ts
Labels: RC1, automerge

#3503 RC1 Docs Fixes
  packages/docs/getting-started/running-a-validator-in-rc1.md
Labels: RC1, docs

#3494 [Wallet] Replace QR scanner screen instead of keeping it in stack
  packages/mobile/.flowconfig
  packages/mobile/__mocks__/src/navigator/NavigationService.ts
  packages/mobile/src/navigator/NavigationService.ts
  packages/mobile/src/qrcode/QRScanner.tsx
  packages/mobile/src/qrcode/utils.ts
  packages/mobile/src/send/saga.test.ts
Labels: automerge

#3414 Rate Limit POST requests (ANTI-SPAM Part 1)
  packages/web/package.json
  packages/web/server/index.ts
  packages/web/server/rateLimit.ts
  yarn.lock
Labels: automerge

#3446 Show different networks on validator explorer
  packages/web/env-config.js.enc
  packages/web/env-config.js.template
  packages/web/pages/validators/explore.tsx
  packages/web/pages/validators/explore/baklava.tsx
  packages/web/pages/validators/explore/baklavastaging.tsx
  packages/web/pages/validators/explore/index.tsx
  packages/web/src/_page-tests/validators/__snapshots__/explore.test.tsx.snap
  packages/web/src/dev/ValidatorsList.tsx
  packages/web/src/dev/ValidatorsListApp.tsx
  packages/web/src/dev/ValidatorsListRow.tsx
  packages/web/src/dev/ValidatorsListStyles.tsx
  packages/web/src/header/Header.3.tsx
  packages/web/src/shared/menu-items.ts
  packages/web/src/shared/navigation.tsx
Labels: automerge

#3511 Fix verification issue in mobile app
  packages/contractkit/src/wrappers/Attestations.ts
Labels: automerge

#3422 Update reserve spenders and governance approver for RC1
  packages/protocol/migrationsConfig.js
Labels: RC1

#3478 Lower the block gas limit after deploying contracts
  packages/celotool/src/e2e-tests/blockchain_parameters_tests.ts
  packages/celotool/src/e2e-tests/validator_order_tests.ts
  packages/protocol/migrations/19_blockchainparams.ts
  packages/protocol/migrations/24_governance.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/package.json
  packages/protocol/runTests.js
  packages/protocol/scripts/bash/init_network.sh
  packages/protocol/scripts/bash/set_block_gas_limit.sh
  packages/protocol/scripts/devchain.ts
  packages/protocol/scripts/truffle/set_block_gas_limit.ts
  packages/protocol/truffle-config.js
Labels: RC1

#3510 Add cli identity:current-attestation-services
  packages/cli/src/commands/identity/current-attestation-services.ts
  packages/cli/src/commands/identity/test-attestation-service.ts
  packages/contractkit/src/wrappers/Accounts.ts
  packages/docs/command-line-interface/identity.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_accounts_.accountswrapper.md
Labels: automerge

#3359 [ReleaseGold] Updating deploy script
  packages/protocol/.gitignore
  packages/protocol/scripts/bash/deploy_release_contracts.sh
  packages/protocol/scripts/devchain.ts
  packages/protocol/scripts/truffle/deploy_release_contracts.ts
  packages/protocol/scripts/truffle/deployedGrants.json
  packages/protocol/scripts/truffle/releaseGoldExampleConfigs.json
Labels: RC1

#2817 Add useful information to understand governance proposals
  packages/cli/src/commands/governance/approve.ts
  packages/cli/src/commands/governance/approvehotfix.ts
  packages/cli/src/commands/governance/executehotfix.ts
  packages/cli/src/commands/governance/hashhotfix.ts
  packages/cli/src/commands/governance/preparehotfix.ts
  packages/cli/src/commands/governance/revokeupvote.ts
  packages/cli/src/commands/governance/view.ts
  packages/cli/src/commands/governance/viewhotfix.ts
  packages/cli/src/utils/checks.ts
  packages/contractkit/src/governance/proposals.ts
  packages/contractkit/src/wrappers/Governance.ts
  packages/contractkit/src/wrappers/Validators.ts
  packages/docs/command-line-interface/governance.md
  packages/docs/developer-resources/contractkit/reference/classes/_governance_proposals_.proposalbuilder.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_governance_.governancewrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_validators_.validatorswrapper.md
  packages/docs/developer-resources/contractkit/reference/enums/_wrappers_governance_.proposalstage.md
  packages/docs/developer-resources/contractkit/reference/enums/_wrappers_governance_.votevalue.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_governance_proposals_.proposaltransactionjson.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_governance_.governanceconfig.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_governance_.hotfixrecord.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_governance_.participationparameters.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_governance_.proposalmetadata.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_governance_.proposalrecord.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_governance_.proposalstagedurations.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_governance_.upvoterecord.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_governance_.votes.md
  packages/docs/developer-resources/contractkit/reference/modules/_governance_proposals_.md
  packages/docs/developer-resources/contractkit/reference/modules/_wrappers_governance_.md
  packages/protocol/contracts/governance/DowntimeSlasher.sol
Labels: automerge

#3501 Updating and reorganizing the setup instructions for the monorepo and wallet
  SETUP.md
  packages/mobile/README.md
Labels: automerge

#3525 [Docs] Update Attestation Service Requirement for Foundation Voting
  packages/docs/operations-manual/celo-foundation-voting-policy.md
Labels: automerge

#3527 Use contract deployer address as owner instead of account[0]
  packages/protocol/lib/web3-utils.ts
Labels: RC1

#3530 Removing grant start time check
  packages/protocol/contracts/governance/ReleaseGold.sol
Labels: RC1

#3521 ReleaseGold deployment script handles shards
  packages/protocol/scripts/truffle/deploy_release_contracts.ts
Labels: RC1

#3499 RC1 oracle addresses
  packages/protocol/migrationsConfig.js
Labels: RC1, automerge

#3533 Allow minting of zero value for GoldToken and StableToken
  packages/protocol/contracts/common/GoldToken.sol
  packages/protocol/contracts/stability/StableToken.sol
  packages/protocol/test/stability/stabletoken.ts
Labels: RC1, automerge

#3518 Change Mainnet name to Release Candidate
  packages/web/src/_page-tests/validators/__snapshots__/explore.test.tsx.snap
  packages/web/src/dev/ValidatorsList.tsx
  packages/web/src/dev/ValidatorsListApp.tsx
  packages/web/src/dev/ValidatorsListStyles.tsx
Labels: automerge

#3536 Minor adjustments to RG deploy script
  packages/protocol/scripts/devchain.ts
  packages/protocol/scripts/truffle/deploy_release_contracts.ts
  packages/protocol/scripts/truffle/releaseGoldExampleConfigs.json
Labels: RC1

#3522 Final migrationsConfig adjustments for RC1
  packages/protocol/migrationsConfig.js
Labels: RC1

#3545 Add RC1 truffle config
  packages/protocol/truffle-config.js
Labels: RC1

#3469 [phone-number-privacy] refactor and handle network/db errors with consistent logging for alerts
  packages/phone-number-privacy/src/common/error-utils.ts
  packages/phone-number-privacy/src/database/database.ts
  packages/phone-number-privacy/src/database/wrappers/account.ts
  packages/phone-number-privacy/src/database/wrappers/number-pairs.ts
  packages/phone-number-privacy/src/index.ts
  packages/phone-number-privacy/src/match-making/get-contact-matches.ts
  packages/phone-number-privacy/src/salt-generation/bls-salt.ts
  packages/phone-number-privacy/src/salt-generation/get-salt.ts
  packages/phone-number-privacy/src/salt-generation/query-quota.ts
  packages/phone-number-privacy/test/index.test.ts
  packages/phone-number-privacy/test/salt-generation/query-quota.test.ts
Labels: automerge

#3550 Add missing other reserve address
  packages/protocol/migrationsConfig.js
Labels: automerge

#3551 Add additional oracles for RC1
  packages/protocol/migrationsConfig.js
Labels: automerge

#3552 Lower gas price by 10x
  packages/protocol/truffle-config.js
Labels: RC1

#3476 [Wallet] Account creation using the Celo derivation path
  packages/cli/package.json
  packages/cli/src/commands/account/new.ts
  packages/mobile/android/app/build.gradle
  packages/mobile/package.json
  packages/mobile/src/backup/utils.test.ts
  packages/mobile/src/backup/utils.ts
  packages/mobile/src/import/saga.ts
  packages/mobile/src/web3/saga.ts
  packages/utils/package-lock.json
  packages/utils/package.json
  packages/utils/src/account.test.ts
  packages/utils/src/account.ts
  yarn.lock
Labels: automerge

#3556 [Ledger] Reset contract info to handle data field in the ledger
  packages/contractkit/src/wallets/ledger-utils/data.ts
Labels: automerge

#3516 [Wallet] Improve support flow
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/locales/es-419/accountScreen10.json
  packages/mobile/src/account/SupportContact.test.tsx
  packages/mobile/src/account/SupportContact.tsx
  packages/mobile/src/navigator/Navigator.tsx
Labels: automerge

#3524 [ContractKit] Add secret retrieval capability to AzureKeyVaultClient
  packages/contractkit/package.json
  packages/contractkit/src/utils/azure-key-vault-client.ts
  packages/contractkit/src/wallets/azure-hsm-wallet.test.ts
  packages/contractkit/src/wallets/azure-hsm-wallet.ts
  packages/contractkit/src/wallets/signers/azure-hsm-signer.ts
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/classes/_utils_azure_key_vault_client_.azurekeyvaultclient.md
  packages/docs/developer-resources/contractkit/reference/classes/_utils_azure_key_vault_client_.signature.md
  packages/docs/developer-resources/contractkit/reference/classes/_wallets_signers_azure_hsm_signer_.azurehsmsigner.md
  packages/docs/developer-resources/contractkit/reference/classes/_wallets_signers_azure_key_vault_client_.azurekeyvaultclient.md
  packages/docs/developer-resources/contractkit/reference/classes/_wallets_signers_azure_key_vault_client_.signature.md
  packages/docs/developer-resources/contractkit/reference/globals.md
  packages/docs/developer-resources/contractkit/reference/modules/_utils_azure_key_vault_client_.md
  packages/docs/developer-resources/contractkit/reference/modules/_wallets_signers_azure_key_vault_client_.md
  yarn.lock
Labels: automerge

#3563 Some cleanup
  packages/cli/src/commands/account/unlock.ts
  packages/docs/command-line-interface/account.md
Labels: automerge

#3537 Run tests and linting for phone-number-privacy svc
  .circleci/config.yml
Labels: automerge

#3526 [phone-number-privacy] update to use new BLS signature
  packages/phone-number-privacy/package.json
  packages/phone-number-privacy/src/common/error-utils.ts
  packages/phone-number-privacy/src/config.ts
  packages/phone-number-privacy/src/index.ts
  packages/phone-number-privacy/src/match-making/get-contact-matches.ts
  packages/phone-number-privacy/src/salt-generation/bls-salt.ts
  packages/phone-number-privacy/src/salt-generation/bls-signature.ts
  packages/phone-number-privacy/src/salt-generation/get-salt.ts
  packages/phone-number-privacy/test/index.test.ts
  packages/phone-number-privacy/test/salt-generation/bls-salt.test.ts
  packages/phone-number-privacy/test/salt-generation/bls-signature.test.ts
  yarn.lock
Labels: automerge

#3566 Footer and BrandKit Fixes
  packages/web/pages/_app.tsx
  packages/web/public/static/locales/en/brand.json
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/brandkit/common/Page.tsx
  packages/web/src/brandkit/common/TopBar.tsx
  packages/web/src/react-native-aug.d.ts
  packages/web/src/shared/Footer.tsx
  packages/web/src/shared/__snapshots__/Footer.test.tsx.snap
Labels: automerge

#3291 Update dependencies
  .circleci/config.yml
  package.json
  packages/attestation-service/package.json
  packages/attestation-service/src/index.ts
  packages/blockchain-api/package.json
  packages/blockchain-api/src/index.ts
  packages/celotool/package.json
  packages/cli/package.json
  packages/faucet/package.json
  packages/leaderboard/src/board.ts
  packages/leaderboard/src/upload.ts
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/src/apollo/index.ts
  packages/mobile/src/apollo/types.ts
  packages/mobile/src/app/App.tsx
  packages/mobile/src/fragmentTypes.json
  packages/mobile/src/home/WalletHome.tsx
  packages/mobile/src/recipients/RecipientPicker.tsx
  packages/mobile/src/transactions/TransactionsList.test.tsx
  packages/mobile/src/transactions/TransactionsList.tsx
  packages/mobile/src/transactions/__snapshots__/TransactionsList.test.tsx.snap
  packages/moonpay-auth/package.json
  packages/moonpay-auth/src/index.ts
  packages/notification-service/package.json
  packages/notification-service/src/blockscout/decode.ts
  packages/phone-number-privacy/package.json
  packages/protocol/package.json
  packages/transaction-metrics-exporter/package.json
  packages/transaction-metrics-exporter/src/blockchain.ts
  packages/verification-pool-api/package.json
  packages/web/package.json
  packages/web/server/rateLimit.ts
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/brandkit/Explorer.test.tsx
  packages/web/src/brandkit/Explorer.tsx
  packages/web/src/dev/ValidatorsListApp.tsx
  packages/web/src/fauceting/PhoneInput.test.tsx
  yarn.lock
Labels: automerge

#3564 Utils->0.1.13-dev ContractKit->0.4.1-dev Celocli->0.0.45-dev
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/leaderboard/package.json
  packages/metadata-crawler/package.json
  packages/mobile/package.json
  packages/protocol/package.json
  packages/react-components/package.json
  packages/transaction-metrics-exporter/package.json
  packages/utils/package.json
  packages/verifier/package.json
Labels: automerge

#3571 Bump dev version of contractkit to 0.4.2 and cli to 0.0.46
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/leaderboard/package.json
  packages/metadata-crawler/package.json
  packages/mobile/package.json
Labels: automerge

#3565 [BlockchainApi] Fix exchange transactions
  packages/blockchain-api/.env
  packages/blockchain-api/app.alfajores.yaml
  packages/blockchain-api/app.alfajoresstaging.yaml
  packages/blockchain-api/app.baklavastaging.yaml
  packages/blockchain-api/app.integration.yaml
  packages/blockchain-api/app.pilot.yaml
  packages/blockchain-api/app.pilotstaging.yaml
  packages/blockchain-api/src/blockscout.ts
  packages/blockchain-api/src/schema.ts
  packages/blockchain-api/src/utils.ts
  packages/blockchain-api/test/blockscout.test.ts
  packages/blockchain-api/test/mockTokenTxs.ts
Labels: automerge

#3320 [Wallet] Upgrade to firebase v6
  packages/mobile/__mocks__/@react-native-firebase/dynamic-links.ts
  packages/mobile/__mocks__/react-native-firebase.ts
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/android/app/src/main/java/org/celo/mobile/MainApplication.java
  packages/mobile/index.js
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/ios/celo/AppDelegate.m
  packages/mobile/jest.config.js
  packages/mobile/package.json
  packages/mobile/src/firebase/dynamicLinks.test.ts
  packages/mobile/src/firebase/dynamicLinks.ts
  packages/mobile/src/firebase/firebase.test.ts
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/firebase/notifications.ts
  packages/mobile/src/firebase/saga.ts
  packages/mobile/src/invite/EnterInviteCode.test.tsx
  packages/mobile/src/invite/utils.test.ts
  packages/mobile/src/invite/utils.ts
  packages/mobile/src/utils/LogUploader.ts
  yarn.lock
Labels: automerge

#3575 Add 0x in attestation service a-validator-in-rc1
  packages/docs/getting-started/running-a-validator-in-rc1.md
Labels: automerge

#3574 Bumping local cli to 47-dev
  packages/cli/package.json
Labels: automerge

#3583 [BlockchainApi] Fix transfers processing when gateway fee recipient is null
  packages/blockchain-api/src/blockscout.ts
  packages/blockchain-api/test/mockTokenTxs.ts
Labels: automerge

#3585 Change default name of a validator group
  packages/web/src/dev/ValidatorsListRow.tsx
Labels: automerge

#3587 [cli] Verify Proof of Possession
  packages/cli/src/commands/account/authorize.ts
  packages/cli/src/commands/account/verify-proof-of-possession.ts
  packages/cli/src/commands/releasegold/authorize.ts
  packages/cli/src/utils/command.ts
  packages/docs/command-line-interface/account.md
  packages/docs/command-line-interface/releasegold.md
  packages/utils/src/signatureUtils.ts
Labels: automerge

#3570 [phone-number-privacy] add ratelimiting to matchmaking, update salt/bls references
  packages/phone-number-privacy/src/bls/bls-signature.ts
  packages/phone-number-privacy/src/common/error-utils.ts
  packages/phone-number-privacy/src/config.ts
  packages/phone-number-privacy/src/database/models/account.ts
  packages/phone-number-privacy/src/database/models/numberPair.ts
  packages/phone-number-privacy/src/database/wrappers/account.ts
  packages/phone-number-privacy/src/database/wrappers/number-pairs.ts
  packages/phone-number-privacy/src/index.ts
  packages/phone-number-privacy/src/match-making/get-contact-matches.ts
  packages/phone-number-privacy/src/salt-generation/get-salt.ts
  packages/phone-number-privacy/src/salt-generation/query-quota.ts
  packages/phone-number-privacy/test/index.test.ts
  packages/phone-number-privacy/test/salt-generation/bls-signature.test.ts
  packages/phone-number-privacy/test/salt-generation/query-quota.test.ts
Labels: automerge

#3598 Bump wallet to 1.7.1
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/assets/custom/LicenseDisclaimer.txt
  packages/mobile/android/gradle.properties
  packages/mobile/circle_deploy.sh
  packages/mobile/ios/celo-tvOS/Info.plist
  packages/mobile/ios/celo-tvOSTests/Info.plist
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/ios/celo/Info.plist
  packages/mobile/ios/celoTests/Info.plist
  packages/mobile/package.json
Labels: automerge

#3586 Update mergify to use PR title and body as commit message
  .github/pull_request_template.md
  .mergify.yml
Labels: automerge

#3328 Add tx-node-private support to vm-exec
  packages/celotool/src/cmds/vm-exec.ts
Labels: automerge

#3507 HSM support + aad-pod-identity for oracles
  packages/celotool/src/lib/azure.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/oracle.ts
  packages/helm-charts/aad-pod-identity/Chart.yaml
  packages/helm-charts/aad-pod-identity/templates/azure-assigned-identity-crd.yaml
  packages/helm-charts/aad-pod-identity/templates/azure-identity-binding-crd.yaml
  packages/helm-charts/aad-pod-identity/templates/azure-identity-crd.yaml
  packages/helm-charts/aad-pod-identity/templates/azure-pod-identity-exception-crd.yaml
  packages/helm-charts/aad-pod-identity/templates/mic-cluster-role-binding.yaml
  packages/helm-charts/aad-pod-identity/templates/mic-cluster-role.yaml
  packages/helm-charts/aad-pod-identity/templates/mic-deployment.yaml
  packages/helm-charts/aad-pod-identity/templates/mic-service-account.yaml
  packages/helm-charts/aad-pod-identity/templates/nmi-cluster-role-binding.yaml
  packages/helm-charts/aad-pod-identity/templates/nmi-cluster-role.yaml
  packages/helm-charts/aad-pod-identity/templates/nmi-daemonset.yaml
  packages/helm-charts/aad-pod-identity/templates/nmi-service-account.yaml
  packages/helm-charts/aad-pod-identity/values.yaml
  packages/helm-charts/oracle-rbac/Chart.yaml
  packages/helm-charts/oracle-rbac/templates/_helper.tpl
  packages/helm-charts/oracle-rbac/templates/role.yaml
  packages/helm-charts/oracle-rbac/templates/rolebinding.yaml
  packages/helm-charts/oracle-rbac/templates/service-account.yaml
  packages/helm-charts/oracle-rbac/values.yaml
  packages/helm-charts/oracle/templates/_helper.tpl
  packages/helm-charts/oracle/templates/azure-identity-binding.yaml
  packages/helm-charts/oracle/templates/azure-identity.yaml
  packages/helm-charts/oracle/templates/statefulset.yaml
  packages/helm-charts/oracle/values.yaml
Labels: automerge

#3595 Add account:lock and duration flag to account:unlock
  packages/cli/src/commands/account/lock.ts
  packages/cli/src/commands/account/unlock.ts
  packages/contractkit/src/kit.ts
  packages/docs/command-line-interface/account.md
  packages/docs/developer-resources/contractkit/reference/classes/_kit_.contractkit.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_kit_.kitoptions.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_kit_.networkconfig.md
  packages/docs/developer-resources/contractkit/reference/modules/_kit_.md
Labels: automerge

#3606 fix links in documentation
  packages/docs/getting-started/running-a-validator-in-baklava.md
  packages/docs/getting-started/running-a-validator-in-rc1.md
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#3567 Add full node documentation to RC1
  .gitbook.yaml
  packages/docs/SUMMARY.md
  packages/docs/getting-started/running-a-full-node-in-baklava.md
  packages/docs/getting-started/running-a-full-node-in-rc1.md
  packages/docs/getting-started/running-a-validator-in-rc1.md
Labels: RC1, docs

#3603 [Phone Number Privacy] Restructure query quota and improve logging
  packages/phone-number-privacy/package.json
  packages/phone-number-privacy/src/bls/bls-signature.ts
  packages/phone-number-privacy/src/common/error-utils.ts
  packages/phone-number-privacy/src/common/identity.ts
  packages/phone-number-privacy/src/common/logger.ts
  packages/phone-number-privacy/src/config.ts
  packages/phone-number-privacy/src/database/wrappers/account.ts
  packages/phone-number-privacy/src/database/wrappers/number-pairs.ts
  packages/phone-number-privacy/src/index.ts
  packages/phone-number-privacy/src/match-making/get-contact-matches.ts
  packages/phone-number-privacy/src/salt-generation/get-salt.ts
  packages/phone-number-privacy/src/salt-generation/query-quota.ts
  packages/phone-number-privacy/test/salt-generation/query-quota.test.ts
  packages/phone-number-privacy/test/utils.ts
  packages/phone-number-privacy/test/values.ts
  packages/phone-number-privacy/tslint.json
  yarn.lock
Labels: automerge

#3616 Clarify Test Wallet is Fake
  packages/web/public/static/locales/en/dev.json
  packages/web/public/static/locales/en/download.json
  packages/web/public/static/locales/en/faucet.json
  packages/web/server/index.ts
  packages/web/src/_page-tests/developers/__snapshots__/Index.test.tsx.snap
  packages/web/src/_page-tests/developers/__snapshots__/wallet.test.tsx.snap
  packages/web/src/_page-tests/validators/__snapshots__/index.test.tsx.snap
  packages/web/src/download/Cover.tsx
  packages/web/src/download/MobileApp.tsx
Labels: automerge

#3591 Test signatures that need canonicalization
  packages/contractkit/src/utils/signing-utils.ts
  packages/contractkit/src/wallets/azure-hsm-wallet.test.ts
  packages/contractkit/src/wallets/ledger-wallet.test.ts
  packages/contractkit/src/wallets/local-wallet.test.ts
  packages/docs/developer-resources/contractkit/reference/modules/_utils_signing_utils_.md
Labels: automerge

#3621 Add more info to signature error message
  packages/contractkit/src/identity/claims/domain.test.ts
  packages/contractkit/src/identity/claims/verify.ts
  packages/contractkit/src/identity/metadata.ts
  packages/docs/developer-resources/contractkit/reference/classes/_identity_metadata_.identitymetadatawrapper.md
  packages/docs/developer-resources/contractkit/reference/modules/_identity_claims_verify_.md
  packages/metadata-crawler/src/crawler.ts
  packages/utils/src/signatureUtils.ts
Labels: automerge

#3619 Increase web test coverage back to 80%
  packages/web/src/brandkit/common/Fetch.tsx
  packages/web/src/brandkit/common/MobileMenu.test.tsx
  packages/web/src/header/CookieConsent.test.tsx
  packages/web/src/header/CookieConsent.tsx
  packages/web/src/shared/FlowerCoin.tsx
  packages/web/src/shared/MobileMenu.test.tsx
  packages/web/src/shared/SocialChannels.tsx
  packages/web/src/shared/TinyHollowCoin.tsx
  packages/web/src/shared/__snapshots__/MobileMenu.test.tsx.snap
Labels: automerge

#3611 Use the correct account in releasegold:locked-gold
  packages/cli/src/commands/releasegold/locked-gold.ts
Labels: cli

#3434 [wallet] new Terms Screen
  packages/mobile/__mocks__/react-i18next.js
  packages/mobile/e2e/Transfer.spec.js
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/en-US/nuxNamePin1.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/es-419/nuxNamePin1.json
  packages/mobile/src/account/actions.ts
  packages/mobile/src/account/reducer.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/registration/JoinCelo.test.tsx
  packages/mobile/src/registration/JoinCelo.tsx
  packages/mobile/src/registration/RegulatoryTerms.test.tsx
  packages/mobile/src/registration/RegulatoryTerms.tsx
  packages/mobile/src/registration/__snapshots__/JoinCelo.test.tsx.snap
  packages/mobile/src/registration/__snapshots__/RegulatoryTerms.test.tsx.snap
  packages/mobile/test/schemas.ts
Labels: automerge

#3407 Small e2e transfer test fix
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/celotool/src/e2e-tests/sync_tests.ts
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/contractkit/src/base.ts
  packages/contractkit/src/contract-cache.ts
  packages/contractkit/src/wrappers/Freezer.ts
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/classes/_contract_cache_.wrappercache.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_basewrapper_.basewrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_freezer_.freezerwrapper.md
  packages/docs/developer-resources/contractkit/reference/globals.md
  packages/docs/developer-resources/contractkit/reference/modules/_base_.md
  packages/docs/developer-resources/contractkit/reference/modules/_contract_cache_.md
  packages/docs/developer-resources/contractkit/reference/modules/_wrappers_freezer_.md
Labels: automerge

#3437 Update Attestations.request natspec
  packages/protocol/contracts/identity/Attestations.sol
Labels: audit-fix

#3508 Use KeyVault client for retrieving BLS key
  packages/phone-number-privacy/package.json
  packages/phone-number-privacy/src/bls/bls-cryptography-client.ts
  packages/phone-number-privacy/src/bls/bls-signature.ts
  packages/phone-number-privacy/src/config.ts
  packages/phone-number-privacy/src/salt-generation/get-salt.ts
  packages/phone-number-privacy/test/index.test.ts
  packages/phone-number-privacy/test/salt-generation/bls-signature.test.ts
  yarn.lock
Labels: automerge

#3630 Update documentation for validatorgroup:commission command
  packages/cli/src/commands/validatorgroup/commission.ts
  packages/contractkit/src/wrappers/Validators.ts
  packages/docs/command-line-interface/validatorgroup.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_validators_.validatorswrapper.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_validators_.groupmembership.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_validators_.membershiphistoryextradata.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_validators_.validatorsconfig.md
  packages/docs/package.json
  packages/protocol/contracts/governance/Validators.sol
Labels: automerge

#3626 [Wallet] Fix failed to sync regression on iOS
  packages/mobile/README.md
  packages/mobile/__mocks__/src/web3/testnets.ts
  packages/mobile/package.json
  packages/mobile/src/config.ts
  packages/mobile/src/geth/consts.ts
  packages/mobile/src/geth/geth.ts
  yarn.lock
Labels: automerge

#3648 [Wallet] Hardcode cGLD chart to cUSD instead of local currency
  packages/mobile/src/exchange/CeloGoldHistoryChart.tsx
  packages/mobile/src/exchange/__snapshots__/CeloGoldHistoryChart.test.tsx.snap
Labels: automerge, wallet

#3649 [Wallet] Fix Accept button on Terms screen
  packages/mobile/src/registration/RegulatoryTerms.tsx
  packages/mobile/src/registration/__snapshots__/RegulatoryTerms.test.tsx.snap
Labels: automerge

#3670 [Wallet] Update README.md
  packages/mobile/README.md
Labels: automerge

#3447 Metadatacrawler k8s
  .env
  .env.rc1
  cloudbuild.yaml
  dockerfiles/metadata-crawler/Dockerfile
  packages/celotool/src/cmds/deploy/upgrade/load-test.ts
  packages/celotool/src/lib/blockscout.ts
  packages/celotool/src/lib/celostats.ts
  packages/celotool/src/lib/env-utils.ts
  packages/helm-charts/blockscout/templates/blockscout-metadata-crawler.cronjob.yaml
  packages/helm-charts/blockscout/values.yaml
  packages/metadata-crawler/lib/crawler.d.ts
  packages/metadata-crawler/lib/crawler.js
  packages/metadata-crawler/lib/crawler.js.map
  packages/metadata-crawler/lib/env.d.ts
  packages/metadata-crawler/lib/env.js
  packages/metadata-crawler/lib/env.js.map
  packages/metadata-crawler/lib/logger.d.ts
  packages/metadata-crawler/lib/logger.js
  packages/metadata-crawler/lib/logger.js.map
  packages/metadata-crawler/package.json
Labels: automerge

#3639 Docs: say that a full node can serve celocli
  packages/docs/getting-started/running-a-full-node-in-rc1.md
Labels: automerge

#3650 [Wallet] Fix Firebase regressions on iOS
  packages/mobile/firebase.json
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/src/firebase/firebase.test.ts
  packages/mobile/src/firebase/firebase.ts
  patches/@react-native-firebase/database+6.7.1.patch
  yarn.lock
Labels: automerge

#3617 [phone-number-privacy] min balance for unverified salt callers, require verification for matchmake
  packages/phone-number-privacy/src/common/error-utils.ts
  packages/phone-number-privacy/src/common/identity.ts
  packages/phone-number-privacy/src/config.ts
  packages/phone-number-privacy/src/index.ts
  packages/phone-number-privacy/src/match-making/get-contact-matches.ts
  packages/phone-number-privacy/src/salt-generation/get-salt.ts
  packages/phone-number-privacy/src/salt-generation/query-quota.ts
  packages/phone-number-privacy/test/index.test.ts
  packages/phone-number-privacy/test/salt-generation/query-quota.test.ts
  packages/phone-number-privacy/test/utils.ts
Labels: automerge
