Repository celo-org/celo-monorepo, pull requests merged in 2020-01, with the labels that each got.

#2302 [Slashing] Allow voting gold to be slashable
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/test/governance/election.ts
Labels: audit, automerge

#2317 [Slashing] Slash locked gold
  packages/protocol/contracts/governance/LockedGold.sol
  packages/protocol/contracts/governance/interfaces/IElection.sol
  packages/protocol/contracts/governance/test/MockElection.sol
  packages/protocol/contracts/governance/test/MockGovernance.sol
  packages/protocol/migrations/19_governance_slasher.ts
  packages/protocol/test/governance/lockedgold.ts
  packages/protocol/test/governance/validators.ts
Labels: audit, automerge

#2350 Remove rep sentence from brand kit page
  packages/web/static/locales/en/brand.json
Labels: automerge

#2353 Remove Rewards page from web
  packages/web/pages/rewards.tsx
Labels: automerge, web

#2346 Fixes needed to make slashing work
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/test/governance/validators.ts
Labels: automerge

#2295 Adding a command to the docker script allowing to stop validating
  scripts/run-docker-validator-network.sh
Labels: automerge

#2354 Switch to using native pbkdf to fix hanging on older devices
  packages/mobile/__mocks__/react-native-fast-crypto.ts
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/java/org/celo/mobile/MainApplication.java
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/src/backup/utils.test.ts
  packages/mobile/src/import/saga.ts
  packages/mobile/src/web3/saga.ts
  yarn.lock
Labels: automerge

#2356 Add docs on how to generate sms retriever hash
  packages/mobile/README.md
Labels: automerge

#2362 Update to latest blockchain with select issuers fix
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  yarn.lock
Labels: automerge

#2369 Turn on Emit
  packages/web/tsconfig.json
Labels: automerge

#2357 Make the same hotfix proposal executable with unique salts
  packages/celotool/src/cmds/deploy/upgrade/hotfix.ts
  packages/cli/src/commands/governance/executehotfix.ts
  packages/contractkit/src/governance/proposals.ts
  packages/contractkit/src/utils/web3-utils.ts
  packages/contractkit/src/wrappers/Governance.ts
  packages/docs/command-line-interface/governance.md
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/test/governance/governance.ts
Labels: automerge

#1954 Update blockscout for alfajores and pilot envs
  .env.alfajores
  .env.pilot
  .env.pilotstaging
Labels: automerge

#2352 Optimize Bundles
  packages/web/fullstack/sentry.ts
  packages/web/next.config.js
  packages/web/pages/_app.tsx
  packages/web/pages/_document.tsx
  packages/web/server/Announcement.ts
  packages/web/server/EventHelpers.ts
  packages/web/server/FirebaseServerSide.ts
  packages/web/server/addToCRM.ts
  packages/web/server/index.ts
  packages/web/server/mediumAPI.ts
  packages/web/server/sentry.ts
  packages/web/src/_page-tests/__snapshots__/about.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/animation/__snapshots__/rise.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/analytics/analytics.ts
  packages/web/src/animate/LottieBase.tsx
  packages/web/src/forms/FormComponents.tsx
  packages/web/src/header/BlueBanner.tsx
  packages/web/src/header/CookieConsent.tsx
  packages/web/src/header/Header.3.tsx
  packages/web/src/home/HomeCarousel.tsx
  packages/web/src/home/HomeSystems.tsx
  packages/web/src/join/Benefits.tsx
  packages/web/src/logos/Logo.tsx
  packages/web/src/logos/LogoDarkBg.tsx
  packages/web/src/logos/LogoLightBg.tsx
  packages/web/src/privacy/Privacy.tsx
  packages/web/src/shared/Spinner.tsx
  packages/web/src/shared/darkSpinner.json
  packages/web/src/shared/greenSpinner.json
  packages/web/src/shared/whiteSpinner.json
  packages/web/src/utils/sentry.ts
  packages/web/static/locales/en/brand.json
Labels: automerge

#2375 [Docs] Update Contributing guide with links to good first issues
  packages/docs/community/contributing.md
Labels: automerge, docs

#2372 Change "not syncing" to "not synced"
  packages/attestation-service/src/db.ts
Labels: automerge

#2376 Aaronmgdr/about followup
  .github/CONTRIBUTING.md
  packages/web/public/audio/celo-pronunce.mp3
  packages/web/public/audio/celo-pronunce.ogg
  packages/web/src/_page-tests/__snapshots__/about.test.tsx.snap
  packages/web/src/about/About.tsx
  packages/web/src/about/AudioIcon.tsx
  packages/web/src/about/Backers.tsx
  packages/web/src/about/Team.tsx
  packages/web/src/about/Tetris.tsx
  packages/web/src/community/connect/FullCircle.tsx
  packages/web/src/react-native-aug.d.ts
  packages/web/static/locales/en/about.json
Labels: automerge

#2290 [Wallet] Fix slow activity feed tx confirmations
  packages/mobile/src/apollo/__mockData__.ts
  packages/mobile/src/apollo/types.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/exchange/saga.ts
  packages/mobile/src/home/TransactionsList.tsx
  packages/mobile/src/stableToken/saga.test.ts
  packages/mobile/src/tokens/saga.ts
  packages/mobile/src/transactions/ExchangeFeedItem.test.tsx
  packages/mobile/src/transactions/TransactionFeed.test.tsx
  packages/mobile/src/transactions/TransactionFeed.tsx
  packages/mobile/src/transactions/TransferFeedItem.test.tsx
  packages/mobile/src/transactions/__snapshots__/TransactionFeed.test.tsx.snap
  packages/mobile/src/transactions/reducer.ts
  packages/walletkit/src/contract-utils.ts
Labels: automerge

#2268 Blockscout logs patch for json format
  .env
  packages/helm-charts/blockscout/templates/blockscout-indexer.deployment.yaml
  packages/helm-charts/blockscout/templates/blockscout-web.deployment.yaml
Labels: automerge

#2380 Fix circle not being started
  packages/web/src/_page-tests/__snapshots__/about.test.tsx.snap
  packages/web/src/about/Team.tsx
  packages/web/src/community/connect/FullCircle.tsx
Labels: automerge

#2377 Accelerate time based parameters
  packages/protocol/migrationsConfig.js
Labels: automerge

#2388 The validator/full-node docker script should use bootnodes file
  scripts/run-docker-validator-network.sh
Labels: automerge

#2397 Integration deploy
  .env.integration
  packages/helm-charts/testnet/templates/_helpers.tpl
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
Labels: automerge

#2118 [cli] Showing summed up balances for claimed accounts
  packages/cli/src/commands/account/balance.ts
  packages/cli/src/commands/account/show-claimed-accounts.ts
  packages/contractkit/src/kit.ts
  packages/docs/command-line-interface/account.md
Labels: automerge, betanet-phase-2, cli, vx

#2379 Freeze exchange and epoch rewards on initialize
  packages/celotool/src/e2e-tests/utils.ts
  packages/dev-utils/src/migration-override.json
  packages/protocol/migrations/09_exchange.ts
  packages/protocol/migrations/14_epoch_rewards.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/test/common/integration.ts
Labels: automerge

#2406 Upload static nodes as JSON
  packages/celotool/src/lib/testnet-utils.ts
Labels: automerge

#2401 Baklava & baklavastaging changes
  .env.baklava
  .env.baklavastaging
  packages/celotool/src/cmds/vm-exec.ts
Labels: automerge

#2394 Cache Third party Calls +fix medium
  packages/web/server/AssetBase.ts
  packages/web/server/EventHelpers.ts
  packages/web/server/cache.test.ts
  packages/web/server/cache.ts
  packages/web/server/mediumAPI.ts
Labels: automerge

#2410 Fixes #2409 Firefox exception
  packages/web/src/utils/utils.ts
Labels: automerge

#2400 Serve papers from celo.org
  packages/web/public/papers/CBDC_Velocity_Copic-Franke.pdf
  packages/web/public/papers/Celo_A_Multi_Asset_Cryptographic_Protocol_for_Decentralized_Social_Payments.pdf
  packages/web/public/papers/Celo_Stability_Analysis.pdf
  packages/web/src/_page-tests/__snapshots__/index.test.tsx.snap
  packages/web/src/home/HomeSystems.tsx
Labels: automerge

#2407 Remove references to OG infrastructure
  .env
  .env.alfajores
  .env.alfajoresstaging
  .env.integration
  .env.integrationtesting
  .env.pilot
  .env.pilotstaging
  package.json
  packages/celotool/src/lib/geth.ts
  packages/celotool/src/lib/kubernetes.ts
  packages/celotool/src/lib/port_forward.ts
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
Labels: automerge

#2341 e2e tests for slashing contracts
  .circleci/config.yml
  packages/celotool/ci_test_slashing.sh
  packages/celotool/src/e2e-tests/slashing_tests.ts
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/celotool/tslint.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/contractkit/src/base.ts
  packages/contractkit/src/web3-contract-cache.ts
  packages/protocol/contracts/common/UsingRegistry.sol
  packages/protocol/contracts/governance/SlasherUtil.sol
  packages/protocol/migrations/20_double_signing_slasher.ts
  packages/protocol/migrations/21_downtime_slasher.ts
  packages/protocol/migrations/23_elect_validators.ts
  packages/protocol/package.json
  packages/protocol/scripts/build.ts
  packages/protocol/test/common/integration.ts
  packages/protocol/test/governance/lockedgold.ts
  yarn.lock
Labels: automerge

#1771 Add first version of public terraform module.
  packages/terraform-modules-public/.gitignore
  packages/terraform-modules-public/README.md
  packages/terraform-modules-public/example/README.md
  packages/terraform-modules-public/example/main.tf
  packages/terraform-modules-public/example/outputs.tf
  packages/terraform-modules-public/example/variables.tf
  packages/terraform-modules-public/testnet/main.tf
  packages/terraform-modules-public/testnet/modules/attestation-service/main.tf
  packages/terraform-modules-public/testnet/modules/attestation-service/startup.sh
  packages/terraform-modules-public/testnet/modules/attestation-service/variables.tf
  packages/terraform-modules-public/testnet/modules/proxy/main.tf
  packages/terraform-modules-public/testnet/modules/proxy/outputs.tf
  packages/terraform-modules-public/testnet/modules/proxy/startup.sh
  packages/terraform-modules-public/testnet/modules/proxy/variables.tf
  packages/terraform-modules-public/testnet/modules/tx-node/main.tf
  packages/terraform-modules-public/testnet/modules/tx-node/outputs.tf
  packages/terraform-modules-public/testnet/modules/tx-node/startup.sh
  packages/terraform-modules-public/testnet/modules/tx-node/variables.tf
  packages/terraform-modules-public/testnet/modules/validator/main.tf
  packages/terraform-modules-public/testnet/modules/validator/outputs.tf
  packages/terraform-modules-public/testnet/modules/validator/startup.sh
  packages/terraform-modules-public/testnet/modules/validator/variables.tf
  packages/terraform-modules-public/testnet/outputs.tf
  packages/terraform-modules-public/testnet/variables.tf
Labels: automerge, infrastructure

#2347 [Slashing] Adding whitelist checks for onlySlasher to Validators.sol
  packages/protocol/contracts/common/Registry.sol
  packages/protocol/contracts/common/UsingRegistry.sol
  packages/protocol/contracts/common/interfaces/IRegistry.sol
  packages/protocol/contracts/governance/LockedGold.sol
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/contracts/governance/interfaces/ILockedGold.sol
  packages/protocol/contracts/governance/test/MockLockedGold.sol
  packages/protocol/migrations/19_governance_slasher.ts
  packages/protocol/migrations/20_double_signing_slasher.ts
  packages/protocol/migrations/21_downtime_slasher.ts
  packages/protocol/test/governance/lockedgold.ts
  packages/protocol/test/governance/validators.ts
Labels: automerge

#2408 Adjustment to home banner / mobile menu
  packages/web/src/header/Header.3.tsx
  packages/web/src/home/HomeAnimation.tsx
  packages/web/src/home/version3/HomeCover.tsx
Labels: automerge

#2230 Make attestation opt-in
  packages/celotool/src/lib/attestation-service.ts
  packages/protocol/contracts/common/Accounts.sol
  packages/protocol/contracts/common/interfaces/IAccounts.sol
  packages/protocol/contracts/identity/Attestations.sol
  packages/protocol/test/common/accounts.ts
  packages/protocol/test/identity/attestations.ts
Labels: audit, automerge

#2417 Sort on correct vote amount in validator election migration
  packages/protocol/migrations/23_elect_validators.ts
Labels: automerge

#2416 Update genesis block accounts config to be correct for phase 2
  baklava_genesis_balances.json
Labels: automerge

#2404 Fix documentation link
  README.md
Labels: automerge

#2402 Upload correct bootnode IP address on internal testnet
  packages/celotool/src/lib/geth.ts
  packages/celotool/src/lib/helm_deploy.ts
Labels: automerge

#2430 Use bootnodes for the local machine
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#2426 Fix verify-contracts file dependency missing
  package.json
Labels: automerge

#2433 Add unfreeze-contracts command to celotool
  packages/celotool/src/cmds/unfreeze_contracts.ts
Labels: automerge

#2432 Catch exceptions during polling
  packages/transaction-metrics-exporter/src/blockchain.ts
Labels: automerge

#2340 Add unit tests and cli checks for validator hotfix interaction
  packages/celotool/src/cmds/deploy/upgrade/hotfix.ts
  packages/cli/src/commands/governance/approve.ts
  packages/cli/src/commands/governance/approvehotfix.ts
  packages/cli/src/commands/governance/execute.ts
  packages/cli/src/commands/governance/executehotfix.ts
  packages/cli/src/commands/governance/preparehotfix.ts
  packages/cli/src/commands/governance/propose.ts
  packages/cli/src/commands/governance/upvote.ts
  packages/cli/src/commands/governance/vote.ts
  packages/cli/src/commands/governance/whitelisthotfix.ts
  packages/cli/src/commands/validator/list.ts
  packages/cli/src/utils/checks.ts
  packages/contractkit/src/wrappers/Accounts.ts
  packages/protocol/contracts/common/Accounts.sol
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/test/governance/governance.ts
  packages/web/src/header/Header.3.tsx
  packages/web/src/shared/darkSpinner.json
  packages/web/src/shared/greenSpinner.json
  packages/web/src/shared/whiteSpinner.json
  packages/web/static/locales/en/about.json
  packages/web/static/locales/en/brand.json
Labels: automerge

#2439 [Wallet] Cleanup unused StateProps references
  packages/mobile/src/account/Invite.tsx
  packages/mobile/src/escrow/EscrowedPaymentListItem.tsx
  packages/mobile/src/escrow/EscrowedPaymentListScreen.tsx
  packages/mobile/src/escrow/ReclaimPaymentConfirmationScreen.tsx
  packages/mobile/src/escrow/__mocks__.ts
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationScreen.test.tsx.snap
  packages/mobile/src/escrow/actions.ts
  packages/mobile/src/send/Send.tsx
  packages/mobile/test/values.ts
Labels: automerge

#2418 Slashing params for stake off phase 2
  packages/celotool/src/e2e-tests/slashing_tests.ts
  packages/celotool/src/e2e-tests/utils.ts
  packages/dev-utils/src/migration-override.json
  packages/protocol/migrationsConfig.js
  packages/protocol/runTests.js
  packages/protocol/scripts/devchain.ts
Labels: automerge

#2428 Make governance CLI more usable
  packages/cli/package.json
  packages/cli/src/commands/governance/approve.ts
  packages/cli/src/commands/governance/approvehotfix.ts
  packages/cli/src/commands/governance/execute.ts
  packages/cli/src/commands/governance/executehotfix.ts
  packages/cli/src/commands/governance/list.ts
  packages/cli/src/commands/governance/preparehotfix.ts
  packages/cli/src/commands/governance/propose.ts
  packages/cli/src/commands/governance/upvote.ts
  packages/cli/src/commands/governance/view.ts
  packages/cli/src/commands/governance/viewhotfix.ts
  packages/cli/src/commands/governance/vote.ts
  packages/cli/src/commands/governance/whitelisthotfix.ts
  packages/cli/src/utils/cli.ts
  packages/contractkit/src/wrappers/Governance.ts
  packages/contractkit/src/wrappers/Validators.ts
  packages/docs/command-line-interface/governance.md
Labels: automerge

#2441 Fix coin colors
  packages/web/src/_page-tests/__snapshots__/about.test.tsx.snap
  packages/web/src/community/connect/FullCircle.tsx
Labels: automerge

#2421 Baklava and baklavastaging deploys
  .env.baklava
  .env.baklavastaging
  packages/celotool/src/lib/blockscout.ts
  packages/celotool/src/lib/testnet-utils.ts
  packages/docs/getting-started/reconnecting-to-network.md
  packages/docs/getting-started/running-a-full-node.md
  packages/docs/getting-started/running-a-validator.md
  packages/helm-charts/blockscout/templates/_helpers.tpl
  packages/protocol/truffle-config.js
  packages/terraform-modules-public/example/variables.tf
  scripts/run-docker-validator-network.sh
  scripts/validator-config.rc
Labels: automerge

#2454 Change order of profile info
  packages/web/src/about/Team.tsx
  packages/web/src/react-native-aug.d.ts
Labels: automerge

#2468 Update copyright year + inline button
  packages/web/src/_page-tests/__snapshots__/about.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/code-of-conduct.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/community.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/faq.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/past-events.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/user-agreement.test.tsx.snap
  packages/web/src/_page-tests/build/__snapshots__/faucet.test.tsx.snap
  packages/web/src/_page-tests/build/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/_page-tests/stake-off/__snapshots__/terms.test.tsx.snap
  packages/web/src/shared/Button.3.tsx
  packages/web/src/shared/Footer.3.tsx
  packages/web/static/locales/en/common.json
Labels: automerge

#2458 Add callouts to serve text messages in regions
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#2415 collect coverage on web
  .circleci/config.yml
  .codecov.yml
  packages/web/package.json
Labels: automerge

#2437 Add react-testing-utils + Fix Analytics
  packages/web/__mocks__/@segment/in-eu.ts
  packages/web/__mocks__/load-segment.ts
  packages/web/package.json
  packages/web/src/_page-tests/__snapshots__/about.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/community.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/jobs.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/past-events.test.tsx.snap
  packages/web/src/about/Team.test.tsx
  packages/web/src/about/Team.tsx
  packages/web/src/analytics/analytics.test.ts
  packages/web/src/analytics/analytics.ts
  packages/web/src/brandkit/common/MobileMenu.test.tsx
  packages/web/src/brandkit/common/MobileMenu.tsx
  packages/web/src/community/connect/Events.test.tsx
  packages/web/src/header/BlueBanner.test.tsx
  packages/web/src/header/BlueBanner.tsx
  packages/web/src/home/HomeSystems.tsx
  packages/web/src/icons/RedditLogo.tsx
  packages/web/src/join/Benefits.tsx
  packages/web/src/join/JoinPage.tsx
  packages/web/src/privacy/Privacy.tsx
  packages/web/src/shared/Spinner.tsx
  packages/web/src/shared/Triangle.tsx
  packages/web/src/utils/utils.ts
  yarn.lock
Labels: automerge, web

#2450 Configure the time to wait for text messages
  packages/celotool/src/cmds/bots/auto-verify.ts
Labels: automerge

#2453 Fix Logo + backers number change
  packages/web/src/_page-tests/__snapshots__/about.test.tsx.snap
  packages/web/src/_page-tests/animation/__snapshots__/rise.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/about/Backers.tsx
  packages/web/src/about/backers/backers.ts
  packages/web/src/about/backers/valor.jpg
  packages/web/src/logos/Logo.tsx
  packages/web/static/locales/en/about.json
Labels: automerge

#2420 Bump @celo/celocli version to 0.0.34
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/leaderboard/package.json
  packages/mobile/package.json
  packages/notification-service/package.json
  packages/protocol/package.json
  packages/react-components/package.json
  packages/transaction-metrics-exporter/package.json
  packages/utils/package.json
  packages/verification-pool-api/package.json
  packages/verifier/package.json
  packages/walletkit/package.json
  packages/web/package.json
  yarn.lock
Labels: automerge

#2456 Add validator:signed-blocks command and fix validator:status bug
  packages/cli/src/commands/validator/signed-blocks.ts
  packages/cli/src/commands/validator/status.ts
  packages/cli/src/utils/election.ts
  packages/docs/command-line-interface/validator.md
Labels: automerge

#2482 Fixes governance CLI bugs encountered while running election contract upgrade
  packages/cli/src/commands/governance/approve.ts
  packages/cli/src/commands/governance/approvehotfix.ts
  packages/cli/src/commands/governance/execute.ts
  packages/cli/src/commands/governance/executehotfix.ts
  packages/cli/src/commands/governance/list.ts
  packages/cli/src/commands/governance/preparehotfix.ts
  packages/cli/src/commands/governance/upvote.ts
  packages/cli/src/commands/governance/vote.ts
  packages/cli/src/commands/governance/whitelisthotfix.ts
  packages/cli/src/utils/checks.ts
  packages/cli/src/utils/cli.ts
  packages/contractkit/src/explorer/block-explorer.ts
  packages/contractkit/src/utils/web3-utils.ts
  packages/contractkit/src/wrappers/Governance.ts
Labels: automerge

#2495 [Wallet] Fix integration build firebase db url on Android
  packages/mobile/android/app/src/integration/google-services.json.enc
Labels: automerge

#2488 add celo.org/about#contributors id
  packages/web/src/_page-tests/__snapshots__/about.test.tsx.snap
  packages/web/src/about/About.test.tsx
  packages/web/src/about/Team.tsx
Labels: automerge

#1492 [Wallet] Fetch tobin tax for exchanges
  packages/mobile/src/exchange/ExchangeConfirmationCard.tsx
  packages/mobile/src/exchange/ExchangeReview.tsx
  packages/mobile/src/exchange/__snapshots__/ExchangeConfirmationCard.test.tsx.snap
  packages/mobile/src/exchange/actions.ts
  packages/mobile/src/exchange/reducer.ts
  packages/mobile/src/exchange/saga.test.ts
  packages/mobile/src/exchange/saga.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#2502 new academic papers + minor fix to web events
  packages/web/development.yaml
  packages/web/production.yaml
  packages/web/public/papers/Celo_A_Multi_Asset_Cryptographic_Protocol_for_Decentralized_Social_Payments.pdf
  packages/web/public/papers/Celo_Stability_Analysis.pdf
  packages/web/server/EventHelpers.ts
  packages/web/staging.yaml
Labels: automerge

#2504 remove deprecated --account flag from unlock command
  packages/docs/getting-started/running-a-validator.md
Labels: automerge

#2489 Require Consent for tracking globally
  packages/web/package.json
  packages/web/src/analytics/analytics.test.ts
  packages/web/src/analytics/analytics.ts
  yarn.lock
Labels: automerge

#2500 [Wallet] Navigate to wallet home after payment request
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.tsx
Labels: automerge

#2501 Fix celotool testnet deploy
  packages/celotool/src/lib/migration-utils.ts
  packages/helm-charts/testnet/templates/_helpers.tpl
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
  packages/helm-charts/testnet/values.yaml
Labels: automerge

#2480 Added ingress resource for celostats DNS
  .env
  .env.baklava
  .env.baklavastaging
  packages/helm-charts/ethstats/templates/celostats.ingress.yaml
  packages/helm-charts/ethstats/templates/ethstats.ingress.yaml
Labels: automerge, celostats, infrastructure

#2510 [Wallet] Fix incorrect empty state on the gold tab
  packages/mobile/src/transactions/TransactionsList.tsx
Labels: automerge

#2506 handle error while playing home video
  packages/web/fullstack/sentry.ts
  packages/web/src/home/HomeAnimation.tsx
  packages/web/src/home/home-animation.json
  packages/web/src/home/version3/HomeCover.tsx
Labels: automerge

#2321 a human readable description for governance proposals added + unit te…
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/governance/Proposals.sol
  packages/protocol/test/governance/governance.ts
Labels: audit

#2436 Downtime slashing when epoch changes
  packages/protocol/contracts/governance/DowntimeSlasher.sol
  packages/protocol/test/governance/downtime_slasher.ts
Labels: automerge

#2539 [Wallet] Fix missing spanish translation
  .env.alfajoresstaging
  packages/mobile/locales/es-419/accountScreen10.json
  packages/mobile/src/redux/sagas.ts
Labels: automerge

#2543 cli: Fix voter rewards presentation
  packages/contractkit/src/wrappers/Election.ts
  packages/contractkit/src/wrappers/Validators.ts
  packages/utils/src/address.ts
Labels: automerge

#2527 Micro Improvement to web tests
  .codecov.yml
  packages/web/src/dev/LeaderBoard.test.tsx
  packages/web/src/home/MissionText.tsx
  packages/web/src/utils/abortableFetch.test.ts
Labels: automerge

#2491 Added more CLI checks for registering validators and groups
  packages/cli/src/commands/lockedgold/unlock.ts
  packages/cli/src/commands/validator/deregister.ts
  packages/cli/src/commands/validator/register.test.ts
  packages/cli/src/commands/validator/register.ts
  packages/cli/src/commands/validatorgroup/register.ts
  packages/cli/src/utils/checks.ts
  packages/contractkit/src/wrappers/Validators.ts
Labels: automerge

#2550 Deployed integration
  .env.integration
Labels: automerge

#2551 [Wallet] Bump @celo/client to 0.0.266
  packages/mobile/package.json
  yarn.lock
Labels: automerge

#2540 Fix rounding error in Election.sol
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/test/governance/election.ts
Labels: automerge

#2556 Add Youtube to Footer +
  packages/web/pages/_app.tsx
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/brandkit/common/Page.tsx
  packages/web/src/header/Header.3.tsx
  packages/web/src/icons/YouTube.tsx
  packages/web/src/shared/Footer.tsx
  packages/web/src/shared/menu-items.ts
Labels: automerge

#2554 ✅ add test for phone Input component
  packages/web/src/_page-tests/test-utils.ts
  packages/web/src/brandkit/common/MobileMenu.test.tsx
  packages/web/src/fauceting/PhoneInput.test.tsx
  packages/web/src/fauceting/PhoneInput.tsx
Labels: automerge

#2559 Fix off-by-one error in attributing signatures to blocks in CLI
  packages/celotool/src/lib/port_forward.ts
  packages/cli/src/commands/validator/signed-blocks.ts
  packages/cli/src/commands/validator/status.ts
  packages/cli/src/utils/election.ts
Labels: automerge

#2552 Add explicit gas to exchange transactions to prevent errors
  packages/cli/src/commands/exchange/dollars.ts
  packages/cli/src/commands/exchange/gold.ts
Labels: automerge

#2545 Add readable proposals to governance:view command
  packages/cli/src/commands/governance/view.ts
  packages/contractkit/src/governance/proposals.ts
  packages/contractkit/src/wrappers/Governance.ts
  packages/docs/command-line-interface/governance.md
Labels: automerge

#2562 🧹Web cleanup (readme + static dir)
  packages/web/README.md
  packages/web/package.json
  packages/web/public/assets/CeloColorLogo.zip
  packages/web/public/assets/CeloColorLogoReverse.zip
  packages/web/public/assets/CeloGlyphs.zip
  packages/web/public/assets/CeloLogoPackage.zip
  packages/web/public/assets/CeloMonochromeLogo.zip
  packages/web/public/assets/CeloMonochromeLogoReverse.zip
  packages/web/public/images/AboutPreview.jpg
  packages/web/public/static/favicon.ico
  packages/web/public/static/locales/en/about.json
  packages/web/public/static/locales/en/applications.json
  packages/web/public/static/locales/en/brand.json
  packages/web/public/static/locales/en/codeofconduct.json
  packages/web/public/static/locales/en/common.json
  packages/web/public/static/locales/en/community.json
  packages/web/public/static/locales/en/dev.json
  packages/web/public/static/locales/en/download.json
  packages/web/public/static/locales/en/faq.json
  packages/web/public/static/locales/en/faucet.json
  packages/web/public/static/locales/en/home.json
  packages/web/public/static/locales/en/jobs.json
  packages/web/public/static/locales/en/technology.json
  packages/web/public/static/locales/en/terms.json
  packages/web/public/static/normalize.css
  packages/web/src/_page-tests/__snapshots__/about.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/about/VideoCover.tsx
  packages/web/src/brandkit/Logo.tsx
  packages/web/src/community/CodeOfConduct.tsx
  yarn.lock
Labels: automerge

#2544 Add tests for wrong index being passed in Governance
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/lib/test-utils.ts
  packages/protocol/test/governance/governance.ts
  packages/protocol/test/governance/validators.ts
Labels: automerge

#2586 [Wallet] Hide "Sell" on exchange screen when users have no gold
  packages/mobile/src/exchange/ExchangeHomeScreen.tsx
Labels: automerge

#2587 [Wallet] Fix Exchange parsing for comma languages
  packages/mobile/src/exchange/ExchangeReview.tsx
Labels: automerge

#2591 [Wallet] Fix gold charts staying in loading state when USD is the selected currency
  packages/mobile/src/exchange/CeloGoldHistoryChart.tsx
  packages/mobile/src/exchange/CeloGoldOverview.tsx
Labels: automerge

#2596 Fix spelling of word explicit in comment
  packages/cli/src/commands/exchange/dollars.ts
  packages/cli/src/commands/exchange/gold.ts
Labels: automerge

#2600 Fix typo in error message of validatorgroup:member
  packages/contractkit/src/wrappers/Validators.ts
Labels: automerge

#2553 Fix full video playback for about Video on iOS
  packages/web/src/_page-tests/__snapshots__/about.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/jobs.test.tsx.snap
  packages/web/src/about/About.tsx
  packages/web/src/shared/VideoModal.tsx
  packages/web/src/utils/abortableFetch.ts
Labels: automerge

#2569 Voting bot can exclude groups from its consideration
  .env.baklava
  .env.baklavastaging
  packages/celotool/src/cmds/bots/auto-vote.ts
  packages/celotool/src/cmds/deploy/initial/voting-bot.ts
  packages/celotool/src/lib/voting-bot.ts
  packages/helm-charts/voting-bot/templates/voting-bot.cronjob.yaml
Labels: automerge

#2558 vesting smart contracts and related ts configs only (#2537)
  packages/celotool/src/e2e-tests/blockchain_parameters_tests.ts
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/celotool/src/e2e-tests/validator_order_tests.ts
  packages/cli/package.json
  packages/contractkit/package.json
  packages/protocol/contracts/common/UsingRegistry.sol
  packages/protocol/contracts/common/interfaces/IAccounts.sol
  packages/protocol/contracts/governance/VestingFactory.sol
  packages/protocol/contracts/governance/VestingInstance.sol
  packages/protocol/contracts/governance/interfaces/IElection.sol
  packages/protocol/contracts/governance/interfaces/ILockedGold.sol
  packages/protocol/contracts/governance/interfaces/IVestingFactory.sol
  packages/protocol/contracts/governance/interfaces/IVestingInstance.sol
  packages/protocol/contracts/governance/proxies/VestingFactoryProxy.sol
  packages/protocol/contracts/governance/test/MockElection.sol
  packages/protocol/contracts/governance/test/MockLockedGold.sol
  packages/protocol/lib/registry-utils.ts
  packages/protocol/migrations/11_vesting_factory.ts
  packages/protocol/migrations/12_lockedgold.ts
  packages/protocol/migrations/13_validators.ts
  packages/protocol/migrations/14_election.ts
  packages/protocol/migrations/15_epoch_rewards.ts
  packages/protocol/migrations/16_random.ts
  packages/protocol/migrations/17_attestations.ts
  packages/protocol/migrations/18_escrow.ts
  packages/protocol/migrations/19_blockchainparams.ts
  packages/protocol/migrations/20_governance_slasher.ts
  packages/protocol/migrations/21_double_signing_slasher.ts
  packages/protocol/migrations/22_downtime_slasher.ts
  packages/protocol/migrations/23_governance.ts
  packages/protocol/migrations/24_elect_validators.ts
  packages/protocol/scripts/build.ts
  packages/protocol/test/governance/vesting.ts
Labels: automerge

#2610 Fix build / lint issue
  packages/web/src/brandkit/IconsPage.tsx
Labels: automerge

#2609 💬 Fix text for brand icon
  packages/web/public/static/locales/en/common.json
  packages/web/src/_page-tests/__snapshots__/community.test.tsx.snap
  packages/web/src/_page-tests/build/__snapshots__/index.test.tsx.snap
  packages/web/src/i18n.ts
  packages/web/src/shared/SocialChannels.tsx
Labels: automerge

#2512 Running local testnet from celotool
  packages/celotool/ci_test_attestations.sh
  packages/celotool/ci_test_blockchain_parameters.sh
  packages/celotool/ci_test_governance.sh
  packages/celotool/ci_test_slashing.sh
  packages/celotool/ci_test_sync.sh
  packages/celotool/ci_test_transfers.sh
  packages/celotool/ci_test_validator_order.sh
  packages/celotool/src/cmds/geth/start.ts
  packages/celotool/src/e2e-tests/attestations_tests.ts
  packages/celotool/src/e2e-tests/blockchain_parameters_tests.ts
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/celotool/src/e2e-tests/slashing_tests.ts
  packages/celotool/src/e2e-tests/sync_tests.ts
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/celotool/src/e2e-tests/utils.ts
  packages/celotool/src/e2e-tests/validator_order_tests.ts
  packages/celotool/src/lib/generate_utils.ts
  packages/celotool/src/lib/genesis_constants.ts
  packages/celotool/src/lib/geth.ts
  packages/celotool/src/lib/interfaces/genesis-config.ts
  packages/celotool/src/lib/interfaces/geth-instance-config.ts
  packages/celotool/src/lib/interfaces/geth-run-config.ts
  packages/celotool/src/lib/utils.ts
Labels: celostats, vx
