Repository celo-org/celo-monorepo, pull requests merged in 2020-11, with the labels that each got.

#5664 [BlockchainApi] Rotate currencylayer key
  packages/blockchain-api/app.alfajoresstaging.yaml
  packages/blockchain-api/app.baklavastaging.yaml
  packages/blockchain-api/app.integration.yaml
  packages/blockchain-api/app.pilot.yaml
  packages/blockchain-api/app.pilotstaging.yaml
  packages/blockchain-api/src/secrets.json.enc
  packages/blockchain-api/src/secrets.json.template
Labels: automerge

#5582 Helm upgrade v2->v3
  packages/celotool/src/cmds/deploy/destroy/blockscout.ts
  packages/celotool/src/cmds/deploy/destroy/chaoskube.ts
  packages/celotool/src/cmds/deploy/destroy/pumba.ts
  packages/celotool/src/cmds/deploy/upgrade/blockscout.ts
  packages/celotool/src/lib/attestation-bot.ts
  packages/celotool/src/lib/attestation-service.ts
  packages/celotool/src/lib/blockscout.ts
  packages/celotool/src/lib/celostats.ts
  packages/celotool/src/lib/cluster.ts
  packages/celotool/src/lib/eksportisto.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/celotool/src/lib/k8s-cluster/aks.ts
  packages/celotool/src/lib/k8s-cluster/base.ts
  packages/celotool/src/lib/k8s-fullnode/base.ts
  packages/celotool/src/lib/leaderboard.ts
  packages/celotool/src/lib/load-test.ts
  packages/celotool/src/lib/mock-oracle.ts
  packages/celotool/src/lib/oracle.ts
  packages/celotool/src/lib/prometheus.ts
  packages/celotool/src/lib/tracer-tool.ts
  packages/celotool/src/lib/transaction-metrics-exporter.ts
  packages/celotool/src/lib/voting-bot.ts
  packages/helm-charts/attestation-service/Chart.yaml
  packages/helm-charts/attestation-service/requirements.lock
  packages/helm-charts/attestation-service/requirements.yaml
  packages/helm-charts/attestation-service/templates/attestation.ingress.yaml
  packages/helm-charts/blockscout/templates/blockscout-web.ingress.yaml
  packages/helm-charts/celo-fullnode/Chart.yaml
  packages/helm-charts/celo-fullnode/requirements.lock
  packages/helm-charts/celo-fullnode/requirements.yaml
  packages/helm-charts/celo-fullnode/templates/ingress.yaml
  packages/helm-charts/celostats/README.md
  packages/helm-charts/celostats/templates/celostats-frontend.ingress.yaml
  packages/helm-charts/celostats/templates/celostats-server.ingress.yaml
  packages/helm-charts/celostats/templates/ethstats.ingress.yaml
  packages/helm-charts/cert-manager-cluster-issuers/Chart.yaml
  packages/helm-charts/cert-manager-cluster-issuers/requirements.lock
  packages/helm-charts/cert-manager-cluster-issuers/requirements.yaml
  packages/helm-charts/load-test/Chart.yaml
  packages/helm-charts/load-test/requirements.lock
  packages/helm-charts/load-test/requirements.yaml
  packages/helm-charts/oracle/Chart.yaml
  packages/helm-charts/oracle/requirements.lock
  packages/helm-charts/oracle/requirements.yaml
  packages/helm-charts/prometheus-stackdriver/templates/deployment.yaml
  packages/helm-charts/testnet/Chart.yaml
  packages/helm-charts/testnet/requirements.lock
  packages/helm-charts/testnet/requirements.yaml
  packages/helm-charts/testnet/templates/forno.ingress.yaml
Labels: automerge

#5645 Stable Paper Routes
  packages/web/development.yaml
  packages/web/production.yaml
  packages/web/staging.yaml
Labels: automerge

#5591 [Wallet] Fix handling deep links
  packages/mobile/android/app/src/main/java/org/celo/mobile/MainActivity.java
  packages/mobile/android/build.gradle
  packages/mobile/e2e/src/DeepLink.spec.js
  packages/mobile/e2e/src/usecases/HandleDeepLinkSend.js
  packages/mobile/scripts/adb-deep-link.sh
  packages/mobile/scripts/ios-deep-link.sh
  packages/mobile/src/app/App.tsx
  packages/mobile/src/app/saga.ts
Labels: automerge, wallet

#5668 add link to forno docs
  packages/docs/developer-resources/contractkit/setup.md
  packages/docs/developer-resources/forno/README.md
Labels: automerge, devX, docs

#5673 [Docs] Update Technical blog posts link
  packages/docs/README.md
Labels: automerge, devX, docs

#5674 Don't dereference env name for testnets
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
Labels: automerge

#5662 [Wallet] Don't allow phone numbers from sanctioned countries
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/flags.ts
  packages/mobile/src/onboarding/registration/NameAndNumber.test.tsx
  packages/mobile/src/onboarding/registration/NameAndNumber.tsx
  packages/mobile/src/utils/countryFeatures.test.ts
  packages/mobile/src/utils/countryFeatures.ts
Labels: automerge, wallet

#5672 Compare master against v2.pre-audit
  .circleci/config.yml
  packages/protocol/scripts/bash/check-versions.sh
Labels: automerge

#5606 Update rc1 eksportisto deployment
  .env.rc1
Labels: automerge

#5396 [Wallet] Don't start transactions until the PIN is correctly input
  packages/mobile/src/alert/actions.ts
  packages/mobile/src/alert/reducer.ts
  packages/mobile/src/exchange/WithdrawCeloReviewScreen.tsx
  packages/mobile/src/exchange/actions.ts
  packages/mobile/src/exchange/reducer.ts
  packages/mobile/src/exchange/saga.ts
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/pincode/PincodeEnter.test.tsx
  packages/mobile/src/pincode/PincodeEnter.tsx
  packages/mobile/src/pincode/authentication.ts
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/saga.ts
  packages/mobile/src/transactions/reducer.ts
  packages/mobile/test/schemas.ts
  packages/react-components/components/ReviewFrame.tsx
Labels: automerge, wallet

#5678 Simplex cUSD integration in Valora
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/locales/es-419/fiatExchangeFlow.json
  packages/mobile/src/account/FiatExchange.tsx
  packages/mobile/src/config.ts
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/fiatExchanges/Simplex.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeOptions.test.tsx.snap
  packages/mobile/src/images/Images.ts
  packages/mobile/src/images/simplex.png
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
Labels: automerge, wallet

#5315 [Wallet] Report to analytics reveal statuses from validators
  packages/attestation-proxy/src/index.ts
  packages/contractkit/src/wrappers/Attestations.ts
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_attestations_.attestationswrapper.md
  packages/docs/developer-resources/contractkit/reference/enums/_wrappers_attestations_.attestationservicestatusstate.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.attestationservicestatusresponse.md
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/analytics/ValoraAnalytics.ts
  packages/mobile/src/flags.ts
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/contactMapping.ts
  packages/mobile/src/identity/saga.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/invite/saga.ts
Labels: automerge, wallet

#5651 Verify initialization Data in verify-release
  packages/docs/community/release-process/smart-contracts.md
  packages/protocol/lib/compatibility/verify-bytecode.ts
  packages/protocol/scripts/bash/verify-release.sh
  packages/protocol/scripts/truffle/verify-bytecode.ts
Labels: automerge

#5685 Add CI release testing
  .circleci/config.yml
  packages/protocol/migrationsConfig.js
  packages/protocol/package.json
  packages/protocol/scripts/bash/release-on-devchain.sh
  packages/protocol/scripts/devchain.ts
Labels: automerge

#5029 Adds replica e2e tests and docs
  .circleci/config.yml
  packages/celotool/ci_test_replicas.sh
  packages/celotool/src/e2e-tests/replica_tests.ts
  packages/celotool/src/lib/geth.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/celotool/src/lib/interfaces/geth-instance-config.ts
  packages/docs/operations-manual/node-upgrades.md
  packages/helm-charts/testnet/templates/secondaries.service.yaml
  packages/helm-charts/testnet/templates/secondaries.statefulset.yaml
Labels: automerge

#4948 Update validator group voting docs
  packages/docs/SUMMARY.md
  packages/docs/celo-holder-guide/quick-start.md
  packages/docs/celo-holder-guide/voting-validators.md
  packages/docs/developer-resources/integrations/checklist.md
Labels: automerge

#5659 KomenciKit - Client-side un/blinding
  .vscode/launch.json
  packages/komencikit/examples/attestation-flow.ts
  packages/komencikit/src/actions.ts
  packages/komencikit/src/kit.spec.ts
  packages/komencikit/src/kit.ts
Labels: automerge

#5643 Add v1 of env-tests
  .circleci/config.yml
  dependency-graph.json
  packages/docs/community/release-process/smart-contracts.md
  packages/env-tests/.gitignore
  packages/env-tests/jest.config.js
  packages/env-tests/package.json
  packages/env-tests/src/monorepoRun.ts
  packages/env-tests/src/scaffold.ts
  packages/env-tests/src/tests/exchange.ts
  packages/env-tests/src/tests/transfer.ts
  packages/env-tests/tsconfig.json
  packages/env-tests/tslint.json
  packages/utils/src/account.test.ts
  packages/utils/src/account.ts
  yarn.lock
Labels: automerge

#5675 [Wallet] Update copy on the onboarding screens
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/onboarding.json
Labels: automerge, wallet

#5515 Allows wallet users to be able to withdraw CELO from Valora using a deep link
  packages/mobile/src/qrcode/QRGenTests/QRGen.test.tsx
  packages/mobile/src/qrcode/schema.ts
  packages/mobile/src/send/utils.test.ts
  packages/mobile/src/send/utils.ts
  packages/mobile/test/values.ts
Labels: automerge, wallet

#5704 chore: relax helm version to v3 instead of exactly v3.3
  packages/celotool/src/lib/helm_deploy.ts
Labels: automerge

#5691 Proxy docs
  packages/docs/operations-manual/proxy.md
Labels: automerge

#5676 Multiproxy doc changes for baklava network
  packages/docs/getting-started/running-a-validator-in-baklava.md
Labels: automerge

#5677 Multiproxy doc changes for mainnet network
  packages/docs/getting-started/running-a-validator-in-mainnet.md
Labels: automerge

#5717 Add new gpg key
  developer_key_publishing.md
  packages/web/openpgpkey/clabs.co/hu/44ki5f3bkanunj4czd4o97ciig6uuiux
Labels: automerge

#5714 Add proxy docs link to homepage
  packages/docs/SUMMARY.md
Labels: automerge

#5693 Only release contracts with Proxies
  packages/protocol/scripts/truffle/make-release.ts
Labels: automerge

#5716 Fix dynamic require to use static import
  packages/contractkit/src/explorer/block-explorer.ts
  packages/contractkit/src/governance/proposals.ts
  packages/contractkit/src/governance/proxy.ts
  packages/docs/developer-resources/contractkit/reference/modules/_governance_proxy_.md
Labels: automerge

#5708 [Wallet] Add Japan to restricted CP-DOTO countries
  packages/mobile/src/flags.ts
  packages/mobile/src/utils/countryFeatures.test.ts
Labels: automerge, wallet

#5718 Add blockchain client 1.2.0
  packages/docs/operations-manual/node-upgrades.md
Labels: automerge

#5596 Add authorized signers to release gold show
  packages/cli/src/commands/releasegold/show.ts
Labels: automerge

#5074 remove reference to a timeline
  packages/docs/getting-started/choosing-a-network.md
Labels: automerge

#5723 Remove line break
  packages/docs/getting-started/running-a-validator-in-baklava.md
Labels: automerge

#5670 [Wallet] Changes to work with Xcode 12
  .circleci/config.yml
  packages/mobile/Gemfile.lock
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
Labels: automerge, wallet

#5719 KomenciKit fix to setAccount
  packages/komencikit/examples/attestation-flow.ts
  packages/komencikit/src/kit.ts
Labels: automerge

#5690 [Wallet] Add shake to Contact screen
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/src/index.d.ts
  packages/mobile/src/navigator/NavigatorWrapper.tsx
  yarn.lock
Labels: automerge, wallet

#5679 Use hard-coded gas values in the verifications flow
  packages/mobile/src/identity/verification.ts
Labels: automerge, wallet

#5702 [Wallet] Show a message on the verification screen to encourage not closing the app
  packages/mobile/locales/en-US/nuxVerification2.json
  packages/mobile/locales/es-419/nuxVerification2.json
  packages/mobile/src/verify/AlternatingText.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
Labels: automerge, wallet

#5700 [Wallet] Retry if geth fails to init because of no internet
  packages/mobile/src/geth/saga.test.ts
  packages/mobile/src/geth/saga.ts
Labels: automerge, wallet

#5701 [Wallet] Add correct decimal separator on CELO Withdrawal
  packages/mobile/src/exchange/WithdrawCeloScreen.test.tsx
  packages/mobile/src/exchange/WithdrawCeloScreen.tsx
Labels: automerge, wallet

#5656 [Wallet] Fix account timeout issue during verification
  packages/mobile/e2e/src/usecases/RestoreAccountOnboarding.js
  packages/mobile/src/geth/consts.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/saga.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/web3/saga.ts
Labels: automerge, wallet

#5725 Fix typo
  packages/protocol/scripts/check-backward.ts
Labels: automerge

#5734 [Wallet] Remove force unlock from initial onboarding flow
  packages/mobile/e2e/src/usecases/RestoreAccountOnboarding.js
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/saga.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/verify/VerificationEducationScreen.tsx
Labels: automerge, wallet

#5618 Remove LocalCommand and pass through cli table flags where applicable
  packages/cli/CHANGELOG.md
  packages/cli/src/base.ts
  packages/cli/src/commands/account/get-metadata.ts
  packages/cli/src/commands/account/new.ts
  packages/cli/src/commands/account/register-metadata.ts
  packages/cli/src/commands/account/show-metadata.ts
  packages/cli/src/commands/config/get.ts
  packages/cli/src/commands/config/set.ts
  packages/cli/src/commands/election/current.ts
  packages/cli/src/commands/election/list.ts
  packages/cli/src/commands/election/run.ts
  packages/cli/src/commands/governance/list.ts
  packages/cli/src/commands/identity/current-attestation-services.ts
  packages/cli/src/commands/oracle/reports.ts
  packages/cli/src/commands/rewards/show.ts
  packages/cli/src/commands/validator/list.ts
  packages/cli/src/commands/validator/status.ts
  packages/cli/src/commands/validatorgroup/list.ts
  packages/cli/src/utils/identity.ts
  packages/docs/command-line-interface/account.md
  packages/docs/command-line-interface/config.md
  packages/docs/command-line-interface/dkg.md
  packages/docs/command-line-interface/election.md
  packages/docs/command-line-interface/exchange.md
  packages/docs/command-line-interface/governance.md
  packages/docs/command-line-interface/identity.md
  packages/docs/command-line-interface/lockedgold.md
  packages/docs/command-line-interface/multisig.md
  packages/docs/command-line-interface/network.md
  packages/docs/command-line-interface/node.md
  packages/docs/command-line-interface/oracle.md
  packages/docs/command-line-interface/releasegold.md
  packages/docs/command-line-interface/reserve.md
  packages/docs/command-line-interface/rewards.md
  packages/docs/command-line-interface/transfer.md
  packages/docs/command-line-interface/validator.md
  packages/docs/command-line-interface/validatorgroup.md
Labels: automerge

#5739 [Wallet] Bump version/build number + licenses from 1.3.0 release branch
  packages/mobile/android/app/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/src/account/LicenseDisclaimer.txt
Labels: automerge, wallet

#5692 [attestation-proxy] add firebase-admin as a dependency
  packages/attestation-proxy/package.json
Labels: automerge

#5737 Update full-nodes helm chart
  packages/helm-charts/celo-fullnode/templates/service.yaml
  packages/helm-charts/celo-fullnode/templates/statefulset.yaml
  packages/helm-charts/celo-fullnode/values.yaml
Labels: automerge

#3384 Create development-chain.md
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/walkthroughs/development-chain.md
Labels: automerge, docs

#5568 Simplify registry address mapping fetch
  packages/cli/src/commands/network/contracts.ts
  packages/cli/src/utils/cli.ts
  packages/contractkit/CHANGELOG.md
  packages/contractkit/src/address-registry.ts
  packages/docs/developer-resources/contractkit/reference/classes/_address_registry_.addressregistry.md
Labels: automerge

#5697 Upgrade our bip39 to TS version
  .circleci/config.yml
  package.json
  packages/blockchain-api/package.json
  packages/blockchain-api/setupJest.ts
  packages/celotool/src/lib/geth.ts
  packages/mobile/__mocks__/react-native-secure-randombytes.ts
  packages/mobile/__mocks__/react-native-securerandom.ts
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/jest.config.js
  packages/mobile/package.json
  packages/mobile/src/fees/CalculateFee.tsx
  packages/mobile/src/index.d.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/pincode/authentication.ts
  patches/bn.js+4.11.9.patch
  patches/react-native-secure-randombytes+3.0.2.patch
  yarn.lock
Labels: automerge, wallet

#5681 KomenciKit function bind issue
  packages/komencikit/src/kit.ts
  packages/komencikit/src/retry.spec.ts
  packages/komencikit/src/retry.ts
Labels: automerge

#5732 Switch Valora escrow expiry to 1 hour
  packages/mobile/src/config.ts
Labels: automerge, wallet

#5712 add back alfajores developer wallet links
  packages/web/public/static/locales/en/download.json
  packages/web/src/_page-tests/__snapshots__/user-agreement.test.tsx.snap
  packages/web/src/_page-tests/developers/__snapshots__/wallet.test.tsx.snap
  packages/web/src/download/AppStores.tsx
  packages/web/src/download/Cover.tsx
  packages/web/src/download/MobileApp.tsx
  packages/web/src/shared/menu-items.ts
  packages/web/src/terms/Agreement.tsx
Labels: automerge

#5750 [Docs] Update Attestation Service releases list
  packages/docs/operations-manual/attestation-service.md
Labels: automerge

#5724 Add bytecode SHA3 for integrity check
  packages/komencikit/package.json
  packages/komencikit/scripts/proxy-bytecode-sha3.js
  packages/komencikit/src/verifyWallet.ts
  yarn.lock
Labels: automerge

#5660 [Wallet] Change Invite Send flow and add invite to drawer
  packages/mobile/branding/celo/src/images/invite-modal.png
  packages/mobile/locales/en-US/inviteFlow11.json
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/es-419/inviteFlow11.json
  packages/mobile/locales/es-419/sendFlow7.json
  packages/mobile/scripts/sync_branding.sh
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/app/actions.ts
  packages/mobile/src/app/reducers.ts
  packages/mobile/src/components/Dialog.tsx
  packages/mobile/src/images/Images.ts
  packages/mobile/src/invite/InviteFriendModal.tsx
  packages/mobile/src/invite/saga.test.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/navigator/DrawerNavigator.tsx
  packages/mobile/src/navigator/NavigatorWrapper.tsx
  packages/mobile/src/send/SendConfirmation.test.tsx
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/verify/VerificationEducationScreen.test.tsx
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
  packages/mobile/test/schemas.ts
  packages/mobile/test/values.ts
Labels: automerge, wallet

#5751 [Docs] Add Virtual Hive's community monitoring tool
  packages/docs/operations-manual/monitoring.md
Labels: automerge

#5698 [Attestation Service] supply Nexmo callback URL so multiple services can share account, use application only to filter numbers
  packages/attestation-service/config/.env.development
  packages/attestation-service/src/sms/index.ts
  packages/attestation-service/src/sms/nexmo.ts
  packages/docs/operations-manual/attestation-service.md
Labels: automerge

#5622 Komenci <> Valora Integration: contact mapping + DEK/wallet registration and querying
  package.json
  packages/base/src/address.ts
  packages/mobile/__mocks__/@celo/react-native-fast-crypto.ts
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/contactMapping.test.ts
  packages/mobile/src/identity/contactMapping.ts
  packages/mobile/src/identity/matchmaking.ts
  packages/mobile/src/identity/privateHashing.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/secureSend.ts
  packages/mobile/src/web3/actions.ts
  packages/mobile/src/web3/dataEncryptionKey.ts
  packages/mobile/src/web3/reducer.ts
  packages/mobile/src/web3/saga.ts
  packages/mobile/src/web3/selectors.ts
  packages/mobile/test/schemas.ts
  packages/mobile/test/values.ts
  yarn.lock
Labels: automerge, fee-less onboarding, wallet

#5752 [Wallet] Improve on the e2e flakiness
  packages/mobile/e2e/src/usecases/SecureSend.js
Labels: e2e testing, wallet

#5740 Update dependencies from alerts
  package.json
  yarn.lock
Labels: automerge

#5722 s/--celostats/--ethstats
  packages/docs/getting-started/running-a-validator-in-mainnet.md
Labels: automerge

#5720 Update Attestation Docs for Celo Blockchain 1.1.0
  packages/docs/operations-manual/attestation-service.md
Labels: automerge

#5756 Update @celo/client version
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  yarn.lock
Labels: automerge

#5755 KomenciKit Datacenter Affinity
  packages/komencikit/src/actions.ts
  packages/komencikit/src/client.ts
  packages/komencikit/src/kit.spec.ts
  packages/komencikit/src/kit.ts
Labels: automerge

#5747 Update running-a-validator-in-mainnet.md
  packages/docs/getting-started/running-a-validator-in-mainnet.md
Labels: automerge, docs

#5748 Update running-a-validator-in-baklava.md
  packages/docs/getting-started/running-a-validator-in-baklava.md
Labels: automerge, docs

#4724 New blockscout variables and routes
  packages/celotool/src/lib/blockscout.ts
  packages/helm-charts/blockscout/templates/_helpers.tpl
  packages/helm-charts/blockscout/templates/blockscout-web.ingress.yaml
Labels: automerge

#5683 MTWD remove state mapping and permissions
  packages/contractkit/src/wrappers/MetaTransactionWalletDeployer.test.ts
  packages/contractkit/src/wrappers/MetaTransactionWalletDeployer.ts
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_metatransactionwalletdeployer_.metatransactionwalletdeployerwrapper.md
  packages/protocol/contracts/common/MetaTransactionWalletDeployer.sol
  packages/protocol/contracts/common/interfaces/IMetaTransactionWalletDeployer.sol
  packages/protocol/test/common/metatransactionwalletdeployer.ts
Labels: automerge, contractkit, protocol, protocol-test

#5709 Add CUSD transfer to MTW
  packages/contractkit/src/wrappers/MetaTransactionWallet.ts
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_metatransactionwallet_.metatransactionwalletwrapper.md
  packages/docs/developer-resources/contractkit/reference/modules/_wrappers_metatransactionwallet_.md
  packages/protocol/contracts/common/MetaTransactionWallet.sol
  packages/protocol/test/common/metatransactionwallet.ts
Labels: automerge

#5766 [Wallet] Fix translation of Home text in Spanish
  packages/mobile/locales/es-419/global.json
Labels: automerge, wallet

#5746 Add text explaining exchange rate estimates
  packages/mobile/locales/en-US/exchangeFlow9.json
  packages/mobile/locales/es-419/exchangeFlow9.json
  packages/mobile/src/exchange/ExchangeTradeScreen.tsx
  packages/mobile/src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap
Labels: automerge, wallet

#5650 Celo docs navigation update
  .gitbook.yaml
  packages/docs/README.md
  packages/docs/SUMMARY.md
  packages/docs/celo-codebase/protocol/proof-of-stake/validator-groups.md
  packages/docs/celo-holder-guide/cusd.md
  packages/docs/celo-holder-guide/voting-validators.md
  packages/docs/command-line-interface/commands.md
  packages/docs/developer-resources/integrations/custody.md
  packages/docs/developer-resources/overview.md
  packages/docs/developer-resources/start.md
  packages/docs/developer-resources/walkthroughs/hellocelo.md
  packages/docs/getting-started/running-a-validator-in-baklava.md
  packages/docs/getting-started/running-a-validator-in-mainnet.md
  packages/docs/validator-guide/attestation-service.md
  packages/docs/validator-guide/celo-foundation-voting-policy.md
  packages/docs/validator-guide/key-management/detailed.md
  packages/docs/validator-guide/key-management/key-rotation.md
  packages/docs/validator-guide/key-management/summary.md
  packages/docs/validator-guide/monitoring.md
  packages/docs/validator-guide/node-upgrades.md
  packages/docs/validator-guide/overview.md
  packages/docs/validator-guide/proxy.md
  packages/docs/validator-guide/securing-nodes-and-services.md
  packages/docs/validator-guide/validator-explorer.md
Labels: automerge, devX, docs

#5767 [Wallet] Remove name in invite text
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/es-419/sendFlow7.json
  packages/mobile/src/invite/saga.test.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/navigator/NavigatorWrapper.tsx
Labels: automerge, wallet

#5768 Re-include an added page to the docs
  packages/docs/SUMMARY.md
  packages/docs/validator-guide/overview.md
Labels: automerge

#5769 [Wallet] Update some spanish texts
  packages/mobile/locales/es-419/accountScreen10.json
  packages/mobile/locales/es-419/fiatExchangeFlow.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/es-419/goldEducation.json
  packages/mobile/locales/es-419/nuxVerification2.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/locales/es-419/sendFlow7.json
Labels: automerge, wallet

#5757 [Wallet] UI changes for CICO
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-419/accountScreen10.json
  packages/mobile/locales/es-419/fiatExchangeFlow.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/locales/es-419/walletFlow5.json
  packages/mobile/src/account/FiatExchange.tsx
  packages/mobile/src/account/__snapshots__/FiatExchange.test.tsx.snap
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/app/actions.ts
  packages/mobile/src/app/reducers.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/app/selectors.ts
  packages/mobile/src/config.ts
  packages/mobile/src/exchange/ExchangeHomeScreen.test.tsx
  packages/mobile/src/exchange/ExchangeHomeScreen.tsx
  packages/mobile/src/exchange/WithdrawCeloReviewScreen.test.tsx
  packages/mobile/src/exchange/WithdrawCeloReviewScreen.tsx
  packages/mobile/src/exchange/WithdrawCeloScreen.test.tsx
  packages/mobile/src/exchange/WithdrawCeloScreen.tsx
  packages/mobile/src/exchange/actions.ts
  packages/mobile/src/exchange/reducer.ts
  packages/mobile/src/exchange/saga.ts
  packages/mobile/src/fiatExchanges/ExternalExchanges.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.test.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/fiatExchanges/FundingEducationDialog.tsx
  packages/mobile/src/fiatExchanges/LocalProviderCashOut.tsx
  packages/mobile/src/fiatExchanges/Spend.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeAmount.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeOptions.test.tsx.snap
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/flags.ts
  packages/mobile/src/icons/InfoIcon.tsx
  packages/mobile/src/icons/RadioIcon.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/redux/sagas.ts
  packages/mobile/src/send/utils.test.ts
  packages/mobile/src/send/utils.ts
  packages/mobile/src/utils/countryFeatures.test.ts
  packages/mobile/test/schemas.ts
Labels: automerge, wallet

#5663 Komenci <> Valora Integration: feeless verification
  dependency-graph.json
  packages/docs/command-line-interface/commands.md
  packages/komencikit/src/verifyWallet.ts
  packages/mobile/babel.config.js
  packages/mobile/e2e/src/NewAccount.spec.js
  packages/mobile/metro.config.js
  packages/mobile/package.json
  packages/mobile/src/account/__snapshots__/Settings.test.tsx.snap
  packages/mobile/src/app/selectors.test.ts
  packages/mobile/src/app/selectors.ts
  packages/mobile/src/escrow/utils.ts
  packages/mobile/src/flags.ts
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/contactMapping.test.ts
  packages/mobile/src/identity/feelessVerification.ts
  packages/mobile/src/identity/feelessVerificationErrors.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/revoke.ts
  packages/mobile/src/identity/saga.ts
  packages/mobile/src/identity/utils.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/invite/saga.test.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/pincode/authentication.ts
  packages/mobile/src/verify/VerificationEducationScreen.test.tsx
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/VerificationInputScreen.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
  packages/mobile/src/web3/actions.ts
  packages/mobile/src/web3/dataEncryptionKey.ts
  packages/mobile/src/web3/reducer.ts
  packages/mobile/test/schemas.ts
  packages/mobile/tsconfig.json
  yarn.lock
Labels: automerge, wallet

#5699 [ContractKit] Add retry and backoff around fetch metadata
  packages/base/src/async.ts
  packages/contractkit/src/identity/claims/verify.ts
  packages/contractkit/src/identity/metadata.ts
  packages/contractkit/src/wrappers/Attestations.ts
  packages/docs/developer-resources/contractkit/reference/classes/_identity_metadata_.identitymetadatawrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_attestations_.attestationswrapper.md
  packages/docs/developer-resources/contractkit/reference/enums/_wrappers_attestations_.attestationservicestatusstate.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.attestationservicestatusresponse.md
  packages/docs/developer-resources/contractkit/reference/modules/_identity_claims_verify_.md
  packages/docs/developer-resources/contractkit/reference/modules/_identity_metadata_.md
Labels: automerge, contractkit

#5774 Upgrades the react native webview package to fix SSL issue
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  yarn.lock
Labels: automerge, wallet-release

#5742 Komenci <> Valora Integration: invites and escrow
  packages/contractkit/src/wrappers/Attestations.ts
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_attestations_.attestationswrapper.md
  packages/docs/developer-resources/contractkit/reference/enums/_wrappers_attestations_.attestationservicestatusstate.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.attestationservicestatusresponse.md
  packages/komencikit/src/kit.ts
  packages/mobile/e2e/src/usecases/NewAccountOnboarding.js
  packages/mobile/e2e/src/usecases/RestoreAccountOnboarding.js
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/secrets.json.enc
  packages/mobile/src/account/actions.ts
  packages/mobile/src/account/saga.ts
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/components/FeeDrawer.tsx
  packages/mobile/src/config.ts
  packages/mobile/src/escrow/actions.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/escrow/utils.ts
  packages/mobile/src/flags.ts
  packages/mobile/src/geth/networkConfig.ts
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/feelessVerification.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/revoke.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/invite/EnterInviteCode.test.tsx
  packages/mobile/src/invite/EnterInviteCode.tsx
  packages/mobile/src/invite/__snapshots__/EnterInviteCode.test.tsx.snap
  packages/mobile/src/invite/actions.ts
  packages/mobile/src/invite/reducer.ts
  packages/mobile/src/invite/saga.test.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/pincode/PincodeSet.test.tsx
  packages/mobile/src/pincode/PincodeSet.tsx
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/transactions/contract-utils.ts
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/web3/dataEncryptionKey.ts
  packages/mobile/src/web3/utils.ts
  packages/mobile/test/schemas.ts
  packages/utils/src/account.ts
Labels: automerge, fee-less onboarding, wallet

#5772 Add new analytics
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/android/build.gradle
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/src/analytics/ValoraAnalytics.ts
  patches/@segment+analytics-react-native+1.3.2.patch
  patches/@segment+analytics-react-native-appsflyer+1.3.2.patch
  patches/@segment/analytics-react-native-firebase+1.1.1-beta.2.patch
  yarn.lock
Labels: automerge, wallet

#5776 Reduce indent from the CK script linkdocs
  packages/contractkit/scripts/linkdocs.ts
  packages/docs/SUMMARY.md
Labels: automerge

#5777 [Wallet] Bump version/build number + licenses from 1.4.0 release branch
  packages/mobile/android/app/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/src/account/LicenseDisclaimer.txt
Labels: automerge, wallet

#5775 [Wallet] Update help link in CICO flow
  packages/mobile/branding/celo/src/brandingConfig.ts
  packages/mobile/scripts/sync_branding.sh
  packages/mobile/src/fiatExchanges/FundingEducationDialog.tsx
Labels: automerge, wallet

#5715 Check if contracts need to relink libraries
  packages/protocol/lib/compatibility/ast-code.ts
  packages/protocol/lib/compatibility/categorizer.ts
  packages/protocol/lib/compatibility/change.ts
  packages/protocol/lib/compatibility/library-linking.ts
  packages/protocol/lib/compatibility/report.ts
  packages/protocol/lib/compatibility/utils.ts
  packages/protocol/lib/contract-dependencies.ts
  packages/protocol/scripts/truffle/make-release.ts
  packages/protocol/test/compatibility/ast-code.ts
  packages/protocol/test/compatibility/library-linking.ts
Labels: automerge

#5778 Update instructions for running celo-blockchain
  packages/docs/developer-resources/integrations/general.md
  packages/docs/getting-started/running-a-full-node-in-mainnet.md
  packages/docs/getting-started/running-a-validator-in-baklava.md
  packages/docs/getting-started/running-a-validator-in-mainnet.md
  packages/docs/getting-started/validator-troubleshooting-faq.md
  packages/docs/validator-guide/attestation-service.md
  packages/docs/validator-guide/node-upgrades.md
Labels: automerge, docs

#5745 Env test logging
  packages/contractkit/src/kit.ts
  packages/contractkit/src/utils/web3-utils.ts
  packages/docs/developer-resources/contractkit/reference/classes/_kit_.contractkit.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_kit_.kitoptions.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_kit_.networkconfig.md
  packages/docs/developer-resources/contractkit/reference/modules/_kit_.md
  packages/docs/developer-resources/contractkit/reference/modules/_utils_web3_utils_.md
  packages/env-tests/index.d.ts
  packages/env-tests/package.json
  packages/env-tests/src/context.ts
  packages/env-tests/src/env.ts
  packages/env-tests/src/logger.ts
  packages/env-tests/src/monorepoRun.ts
  packages/env-tests/src/scaffold.ts
  packages/env-tests/src/tests/exchange.ts
  packages/env-tests/src/tests/transfer.ts
  packages/env-tests/tsconfig.json
  yarn.lock
Labels: automerge

#5781 [Wallet] Fix empty verification code for komenci
  packages/mobile/src/identity/reducer.ts
Labels: automerge

#5780 Add requirements.lock of attestation-service helm chart
  packages/helm-charts/attestation-service/requirements.lock
Labels: automerge

#5782 [Wallet] Ingore YellowBox warning to run e2e successfully
  packages/mobile/src/app/App.tsx
Labels: automerge

#5794 Indicate to run from packages/protocol
  packages/docs/community/release-process/smart-contracts.md
Labels: automerge

#5793 Symlink Mainnet with RC1 in truffle config
  packages/protocol/truffle-config.js
Labels: automerge

#5809 Categorize library linking changes
  packages/protocol/contracts/common/Accounts.sol
  packages/protocol/contracts/governance/LockedGold.sol
  packages/protocol/contracts/identity/Attestations.sol
  packages/protocol/contracts/identity/Escrow.sol
  packages/protocol/lib/compatibility/report.ts
  packages/protocol/scripts/truffle/make-release.ts
Labels: automerge

#5813 Provide initial value for reduce
  packages/protocol/lib/compatibility/library-linking.ts
Labels: automerge

#5817 even more relative links
  packages/docs/README.md
Labels: automerge

#5760 upgrade celo blockchain to v1.1.0
  packages/terraform-modules-public/gcp/example/README.md
  packages/terraform-modules-public/gcp/example/variables.tf
  packages/terraform-modules-public/gcp/testnet/modules/proxy/startup.sh
  packages/terraform-modules-public/gcp/testnet/modules/tx-node/startup.sh
  packages/terraform-modules-public/gcp/testnet/modules/validator/startup.sh
Labels: automerge

#3846 allow AzureKeyVaultClient to take in custom credential
  packages/contractkit/src/utils/azure-key-vault-client.ts
  packages/docs/developer-resources/contractkit/reference/classes/_utils_azure_key_vault_client_.azurekeyvaultclient.md
Labels: automerge, contractkit

#5827 Fix payments to unverified numbers
  packages/mobile/src/invite/saga.ts
Labels: automerge, wallet

#5608 AWS Oracle Infrastructure
  .env.alfajores
  .env.baklava
  .env.oracledev
  .env.rc1
  packages/celotool/src/cmds/deploy/destroy/oracle.ts
  packages/celotool/src/cmds/deploy/initial/oracle.ts
  packages/celotool/src/cmds/deploy/upgrade/oracle.ts
  packages/celotool/src/lib/aws.ts
  packages/celotool/src/lib/azure.ts
  packages/celotool/src/lib/cmd-utils.ts
  packages/celotool/src/lib/context-utils.ts
  packages/celotool/src/lib/endpoints.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/fullnodes.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/celotool/src/lib/k8s-cluster/aks.ts
  packages/celotool/src/lib/k8s-cluster/aws.ts
  packages/celotool/src/lib/k8s-cluster/utils.ts
  packages/celotool/src/lib/k8s-fullnode/aks.ts
  packages/celotool/src/lib/k8s-fullnode/aws.ts
  packages/celotool/src/lib/k8s-fullnode/base.ts
  packages/celotool/src/lib/k8s-fullnode/utils.ts
  packages/celotool/src/lib/k8s-oracle/aks-hsm.ts
  packages/celotool/src/lib/k8s-oracle/aws-hsm.ts
  packages/celotool/src/lib/k8s-oracle/base.ts
  packages/celotool/src/lib/k8s-oracle/pkey.ts
  packages/celotool/src/lib/k8s-oracle/rbac.ts
  packages/celotool/src/lib/oracle.ts
  packages/helm-charts/celo-fullnode/requirements.lock
  packages/helm-charts/celo-fullnode/templates/statefulset.yaml
  packages/helm-charts/oracle/requirements.lock
  packages/helm-charts/oracle/templates/statefulset.yaml
  packages/helm-charts/oracle/values.yaml
  packages/helm-charts/testnet/templates/_helpers.tpl
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
Labels: automerge

#5821 Update node-upgrades.md
  packages/docs/validator-guide/node-upgrades.md
Labels: automerge

#5833 Submit attestation `complete` transactions sequentially
  packages/mobile/src/identity/feelessVerification.ts
  packages/mobile/src/identity/reducer.ts
Labels: automerge, wallet

#5826 Fix bug causing users to get stuck on Contact Matching screen
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx
Labels: automerge

#5790 Protect against beneficiaries that are smart contracts
  packages/protocol/scripts/truffle/deploy_release_contracts.ts
Labels: automerge

#5795 Adjust migrations for Testnet contract deploys
  .env
  packages/celotool/src/cmds/deploy/initial/contracts.ts
  packages/celotool/src/cmds/deploy/upgrade/contracts.ts
  packages/celotool/src/e2e-tests/blockchain_parameters_tests.ts
  packages/celotool/src/lib/attestation-service.ts
  packages/celotool/src/lib/migration-utils.ts
  packages/protocol/migrationsConfig.js
Labels: automerge

#5754 Switch away from release-v2
  .circleci/config.yml
Labels: automerge

#5851 [Wallet] Change Simplex whitelist for blacklist
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/flags.ts
  packages/mobile/src/utils/countryFeatures.test.ts
Labels: automerge, wallet

#5839 [Wallet] Update copy for send and invite flow
  packages/mobile/locales/en-US/inviteFlow11.json
  packages/mobile/locales/es-419/inviteFlow11.json
  packages/mobile/src/invite/InviteAndSendModal.tsx
  packages/mobile/src/send/SendConfirmation.test.tsx
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
Labels: automerge, wallet

#5796 Expose dailySpendingRatio on ReserveWrapper
  packages/contractkit/src/wrappers/Reserve.ts
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_reserve_.reservewrapper.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_reserve_.reserveconfig.md
Labels: automerge

#5847 Extract governance:build-proposal command
  packages/cli/src/commands/governance/build-proposal.ts
  packages/cli/src/commands/governance/propose.ts
  packages/contractkit/src/governance/proposals.ts
  packages/docs/command-line-interface/governance.md
Labels: automerge

#5857 [Wallet] Spanish copy update
  packages/mobile/locales/es-419/inviteFlow11.json
Labels: automerge, wallet

#5854 Fix check of previously verified accounts when in feeless flow
  packages/mobile/src/identity/feelessVerification.ts
Labels: automerge, wallet

#5858 Update known issues file
  yarn-audit-known-issues
Labels: automerge

#5632 Add commands for slashing down validators using DowntimeSlasherv2
  packages/celotool/src/e2e-tests/slashing_tests.ts
  packages/cli/CHANGELOG.md
  packages/cli/src/commands/network/info.ts
  packages/cli/src/commands/validator/downtime-slash.ts
  packages/cli/src/commands/validator/set-bitmaps.ts
  packages/cli/src/commands/validator/signed-blocks.ts
  packages/cli/src/utils/command.ts
  packages/contractkit/src/wrappers/BaseSlasher.ts
  packages/contractkit/src/wrappers/DoubleSigningSlasher.ts
  packages/contractkit/src/wrappers/DowntimeSlasher.ts
  packages/contractkit/src/wrappers/Validators.ts
  packages/docs/SUMMARY.md
  packages/docs/command-line-interface/network.md
  packages/docs/command-line-interface/validator.md
  packages/docs/developer-resources/contractkit/reference/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_baseslasher_.baseslasher.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_basewrapper_.basewrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_doublesigningslasher_.doublesigningslasherwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_downtimeslasher_.downtimeslasherwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_validators_.validatorswrapper.md
  packages/docs/developer-resources/contractkit/reference/globals.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_downtimeslasher_.downtimeslasherconfig.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_downtimeslasher_.downtimewindow.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_downtimeslasher_.interval.md
  packages/docs/developer-resources/contractkit/reference/modules/_wrappers_baseslasher_.md
  packages/docs/developer-resources/contractkit/reference/modules/_wrappers_downtimeslasher_.md
Labels: automerge

#5855 [Wallet] Changes to Simplex cash in
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/locales/es-419/fiatExchangeFlow.json
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/fiatExchanges/Simplex.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeOptions.test.tsx.snap
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/types.tsx
Labels: automerge, wallet

#5837 Upgrade lib to fix pixel email issue
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/src/account/SupportContact.test.tsx
  packages/mobile/src/account/SupportContact.tsx
  yarn.lock
Labels: automerge, wallet

#5791 Avoid compiling contracts when building release scripts
  packages/protocol/scripts/bash/make-release.sh
  packages/protocol/scripts/bash/verify-deployed.sh
Labels: automerge

#5873 Use published version of @celo/utils in packages/protocol
  packages/protocol/package.json
Labels: automerge

#5872 Reduce the number of validators in the validator order e2e test.
  packages/celotool/src/e2e-tests/validator_order_tests.ts
Labels: automerge

#5877 [Wallet] Change the method used to get account addresses from phone numbers
  packages/mobile/src/identity/commentEncryption.test.ts
  packages/mobile/src/identity/commentEncryption.ts
  packages/mobile/src/identity/contactMapping.test.ts
  packages/mobile/src/identity/contactMapping.ts
Labels: automerge, wallet

#5881 Log Komenci session token
  packages/mobile/src/identity/feelessVerification.ts
Labels: automerge, wallet

#5844 Clarify context of release scripts in docs
  packages/docs/community/release-process/smart-contracts.md
  packages/protocol/scripts/bash/check-versions.sh
  packages/protocol/scripts/bash/verify-deployed.sh
  packages/protocol/scripts/bash/verify-release.sh
Labels: automerge

#5875 Support absolute paths for proposal
  packages/protocol/scripts/bash/verify-release.sh
Labels: automerge

#5885 Rename build-proposal flag
  packages/cli/src/commands/governance/build-proposal.ts
  packages/docs/command-line-interface/governance.md
Labels: automerge

#5880 [Attestation Service] Config to randomize provider selection, tune health check
  packages/attestation-service/config/.env.development
  packages/attestation-service/package.json
  packages/attestation-service/src/db.ts
  packages/attestation-service/src/sms/index.ts
  packages/docs/validator-guide/attestation-service.md
  yarn.lock
Labels: automerge

#5889 Use Set instead of Array for Secure Send + don't allow re-verification if an EOA is verified
  packages/mobile/src/identity/contactMapping.ts
  packages/mobile/src/verify/VerificationEducationScreen.tsx
Labels: automerge, wallet

#5860 Komenci SouthEastAsia Region
  .env.rc1
  packages/celotool/src/lib/endpoints.ts
  packages/celotool/src/lib/komenci.ts
  packages/komencikit/examples/attestation-flow.ts
Labels: automerge

#5859 [Attestation Bot] Fix choice of number, and US number creation
  .env.baklava
  packages/celotool/package.json
  packages/celotool/src/cmds/bots/auto-verify.ts
  packages/celotool/src/lib/attestation-bot.ts
  packages/celotool/src/lib/attestation.ts
  packages/helm-charts/attestation-bot/templates/secret.yaml
  packages/helm-charts/attestation-bot/templates/statefulset.yaml
Labels: automerge

#5895 Update DApp gallery
  packages/docs/developer-resources/celo-dapp-gallery.md
Labels: automerge, docs

#5884 Remove unnecesary postgres in komenci deployment
  .env.alfajores
  .env.rc1
  packages/helm-charts/komenci/Chart.yaml
  packages/helm-charts/komenci/requirements.lock
Labels: infrastructure

#5892 Updated forno URL
  packages/blockchain-api/app.mainnet.yaml
Labels: automerge

#5883 CeloTool simplify contexts
  .env.alfajores
  .env.baklava
  .env.rc1
  packages/celotool/src/cmds/deploy/destroy/fullnodes.ts
  packages/celotool/src/cmds/deploy/destroy/komenci.ts
  packages/celotool/src/cmds/deploy/destroy/oracle.ts
  packages/celotool/src/cmds/deploy/initial/fullnodes.ts
  packages/celotool/src/cmds/deploy/initial/komenci.ts
  packages/celotool/src/cmds/deploy/initial/oracle.ts
  packages/celotool/src/cmds/deploy/upgrade/fullnodes.ts
  packages/celotool/src/cmds/deploy/upgrade/komenci.ts
  packages/celotool/src/cmds/deploy/upgrade/oracle.ts
  packages/celotool/src/lib/context-utils.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/forno.ts
  packages/celotool/src/lib/fullnodes.ts
  packages/celotool/src/lib/komenci.ts
  packages/helm-charts/komenci/values.yaml
Labels: automerge

#5902 Switch to new forno link
  packages/protocol/truffle-config.js
Labels: automerge

#5797 Add Oracle/Reserve/Attestation to env-tests
  packages/env-tests/package.json
  packages/env-tests/src/context.ts
  packages/env-tests/src/env.ts
  packages/env-tests/src/monorepoRun.ts
  packages/env-tests/src/scaffold.ts
  packages/env-tests/src/shared/attestation.ts
  packages/env-tests/src/tests/attestation.ts
  packages/env-tests/src/tests/exchange.ts
  packages/env-tests/src/tests/oracle.ts
  packages/env-tests/src/tests/reserve.ts
  packages/env-tests/src/tests/transfer.ts
Labels: automerge

#5638 [Docs] Attestation Service Release Process
  packages/attestation-service/package.json
  packages/docs/SUMMARY.md
  packages/docs/community/release-process/README.md
  packages/docs/community/release-process/attestation-service.md
Labels: automerge, docs

#5906 Fixed wrong syntax for docker ports on the docs
  packages/docs/validator-guide/monitoring.md
Labels: automerge

#5862 Add AUD in Valora
  packages/mobile/src/localCurrency/__snapshots__/SelectLocalCurrency.test.tsx.snap
  packages/mobile/src/localCurrency/consts.ts
Labels: automerge, wallet

#5909 Handle SIGTERM properly in the indexer
  .env.alfajores
  .env.alfajoresstaging
  .env.baklava
  .env.baklavastaging
  .env.rc1
  packages/helm-charts/blockscout/templates/_helpers.tpl
  packages/helm-charts/blockscout/templates/blockscout-api.deployment.yaml
  packages/helm-charts/blockscout/templates/blockscout-indexer.deployment.yaml
  packages/helm-charts/blockscout/templates/blockscout-web.deployment.yaml
Labels: automerge

#5900 [Wallet] Fix Cancel and Edit buttons on withdraw when coming from Deep Link
  packages/mobile/src/exchange/WithdrawCeloReviewScreen.tsx
  packages/mobile/src/exchange/WithdrawCeloScreen.test.tsx
  packages/mobile/src/exchange/WithdrawCeloScreen.tsx
  packages/mobile/src/navigator/types.tsx
Labels: automerge, wallet

#5916 Move "Sending custom transactions" section of the docs
  packages/docs/developer-resources/contractkit/contracts-wrappers-registry.md
  packages/docs/developer-resources/contractkit/usage.md
Labels: automerge, docs

#5542 Update contractkit wrappers to match release 1 contracts.
  packages/contractkit/src/wrappers/Attestations.ts
  packages/contractkit/src/wrappers/Exchange.test.ts
  packages/contractkit/src/wrappers/Exchange.ts
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_attestations_.attestationswrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_exchange_.exchangewrapper.md
  packages/docs/developer-resources/contractkit/reference/enums/_wrappers_attestations_.attestationservicestatusstate.md
  packages/docs/developer-resources/contractkit/reference/enums/_wrappers_attestations_.attestationstate.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.actionableattestation.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.attesationservicerevealrequest.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.attestationsconfig.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.attestationservicestatusresponse.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.attestationstat.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.attestationstateforissuer.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.attestationstoken.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.unselectedrequest.md
  packages/docs/developer-resources/contractkit/reference/modules/_wrappers_attestations_.md
Labels: automerge

#5918 Baklava forno 2.0
  .env.baklava
  .env.rc1
  packages/celotool/src/lib/context-utils.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/fullnodes.ts
Labels: automerge

#5825 [Wallet] Restore mnemonics in any language if default fails
  packages/mobile/src/import/saga.test.ts
  packages/mobile/src/import/saga.ts
  packages/utils/src/account.test.ts
  packages/utils/src/account.ts
Labels: automerge, wallet

#5911 [Wallet] Fix `yarn dev:ios` unable to install app with iOS 14
  .circleci/config.yml
  packages/mobile/README.md
  packages/mobile/package.json
  yarn.lock
Labels: automerge, wallet

#5915 Assume root account only has cUSD balance
  packages/env-tests/src/scaffold.ts
Labels: automerge

#5896 [Wallet] Upgrade react-navigation libraries
  packages/mobile/e2e/src/DeepLinkDappkit.spec.js
  packages/mobile/e2e/src/DeepLinkSend.spec.js
  packages/mobile/e2e/src/usecases/HandleDeepLinkDappkit.js
  packages/mobile/e2e/src/usecases/HandleDeepLinkSend.js
  packages/mobile/package.json
  packages/mobile/scripts/adb-dappkit.sh
  packages/mobile/src/dappkit/DappKitSignTxScreen.tsx
  packages/mobile/src/navigator/DrawerNavigator.tsx
  packages/mobile/src/navigator/Navigator.tsx
  yarn.lock
Labels: automerge, wallet

#5687 Use migrationsConfig from release branch
  packages/protocol/scripts/bash/make-release.sh
Labels: automerge

#5917 fix logic bug in wasValidatorDownForIntervals
  packages/contractkit/src/wrappers/DowntimeSlasher.ts
Labels: automerge

#5736 Move Celo foundation terms to Contentful
  packages/web/pages/api/page/[slug].ts
  packages/web/public/static/locales/en/terms.json
  packages/web/src/_page-tests/__snapshots__/user-agreement.test.tsx.snap
  packages/web/src/_page-tests/user-agreement.test.tsx
  packages/web/src/experience/contentful/getServerSideProps.ts
  packages/web/src/faq/getFAQData.ts
  packages/web/src/terms/Agreement.tsx
  packages/web/src/utils/contentful.ts
Labels: automerge
