Repository celo-org/celo-monorepo, pull requests merged in 2020-07, with the labels that each got.

#4274 [Wallet] Help tab redesign
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/locales/es-419/accountScreen10.json
  packages/mobile/src/account/Support.test.tsx
  packages/mobile/src/account/Support.tsx
  packages/mobile/src/account/SupportContact.tsx
  packages/mobile/src/account/__snapshots__/Support.test.tsx.snap
  packages/mobile/src/account/__snapshots__/SupportContact.test.tsx.snap
Labels: automerge

#4281 [Wallet] Turn off analytics logging for dev builds
  packages/mobile/src/analytics/ValoraAnalytics.ts
Labels: automerge

#4283 Notification copy changes
  packages/mobile/locales/en-US/backupKeyFlow6.json
  packages/mobile/locales/en-US/exchangeFlow9.json
  packages/mobile/locales/en-US/inviteFlow11.json
  packages/mobile/locales/en-US/nuxVerification2.json
  packages/mobile/locales/es-419/backupKeyFlow6.json
  packages/mobile/locales/es-419/exchangeFlow9.json
  packages/mobile/locales/es-419/inviteFlow11.json
  packages/mobile/locales/es-419/nuxVerification2.json
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/home/__snapshots__/NotificationBox.test.tsx.snap
Labels: automerge

#4285 [Wallet] Proxy reveal requests through a firebase function
  packages/contractkit/src/wrappers/Attestations.ts
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_attestations_.attesationservicerevealrequest.md
  packages/docs/developer-resources/contractkit/reference/modules/_contractkit_src_wrappers_attestations_.md
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/identity/verification.ts
  yarn.lock
Labels: automerge

#4287 [Wallet] ignore SIGPIPE
  packages/mobile/ios/celo/AppDelegate.m
Labels: wallet, wallet-quality

#4203 Close ipc connection when toggling forno
  packages/mobile/__mocks__/src/transactions/actions.ts
  packages/mobile/__mocks__/src/web3/contracts.ts
  packages/mobile/__mocks__/web3.js
  packages/mobile/package.json
  packages/mobile/src/account/Settings.tsx
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/fees/saga.ts
  packages/mobile/src/geth/geth.ts
  packages/mobile/src/geth/saga.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/redux/selectors.ts
  packages/mobile/src/transactions/actions.ts
  packages/mobile/src/web3/contracts.ts
  packages/mobile/src/web3/saga.ts
  yarn.lock
Labels: automerge

#4263 Show badges on Validator Explorer
  packages/web/public/images/badges/1st-proposer.svg
  packages/web/public/images/badges/1st-transaction.svg
  packages/web/public/images/badges/attestation.svg
  packages/web/public/images/badges/founder-validator.svg
  packages/web/public/images/badges/genesis-validator.svg
  packages/web/public/images/badges/master-validator.svg
  packages/web/public/images/badges/vote-recipient.svg
  packages/web/src/_page-tests/validators/__snapshots__/explore.test.tsx.snap
  packages/web/src/dev/ValidatorsListBadges.tsx
  packages/web/src/dev/ValidatorsListRow.tsx
Labels: automerge

#4292 Basic attestation-proxy
  dependency-graph.json
  packages/attestation-proxy/.firebaserc
  packages/attestation-proxy/.gitignore
  packages/attestation-proxy/README.md
  packages/attestation-proxy/firebase.json
  packages/attestation-proxy/package.json
  packages/attestation-proxy/src/index.ts
  packages/attestation-proxy/tsconfig.json
  packages/attestation-proxy/tslint.json
Labels: automerge

#4295 fix missing zip files
  packages/web/public/assets/CeloColorLogo.zip
  packages/web/public/assets/CeloColorLogoReverse.zip
  packages/web/public/assets/CeloGlyphs.zip
  packages/web/public/assets/CeloLogoPackage.zip
  packages/web/public/assets/CeloMarketplaceIcons.zip
  packages/web/public/assets/CeloMonochromeLogo.zip
  packages/web/public/assets/CeloMonochromeLogoReverse.zip
Labels: automerge

#4290 Added mnemonic type tx_node_private
  packages/celotool/src/lib/generate_utils.ts
  packages/helm-charts/testnet/templates/txnode-private.statefulset.yaml
Labels: automerge

#4301 Rely upon SSL config value
  packages/phone-number-privacy/combiner/src/config.ts
Labels: automerge

#4278 Create common PGPNP lib
  dependency-graph.json
  packages/phone-number-privacy/common/.gitignore
  packages/phone-number-privacy/common/package.json
  packages/phone-number-privacy/common/src/index.ts
  packages/phone-number-privacy/common/src/interfaces/SignMessageResponse.ts
  packages/phone-number-privacy/common/src/interfaces/error-utils.ts
  packages/phone-number-privacy/common/src/utils/config-utils.ts
  packages/phone-number-privacy/common/tsconfig.json
  packages/phone-number-privacy/common/tslint.json
Labels: automerge

#4302 Use update RN-bip39 lib to fix mnemonic derivations
  packages/mobile/package.json
  packages/mobile/src/identity/verification.ts
  yarn.lock
Labels: automerge

#4316 [Wallet] Various small fixes
  packages/mobile/.env.mainnet
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/src/app/App.tsx
  packages/mobile/src/pincode/Pincode.tsx
Labels: automerge

#4314 [Wallet] Fix Keyboard overlapping issue on SendConfirmation screen
  packages/mobile/src/account/__snapshots__/InviteReview.test.tsx.snap
  packages/mobile/src/components/CommentTextInput.tsx
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationScreen.test.tsx.snap
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeAmount.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestConfirmation.test.tsx.snap
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/react-components/components/ReviewFrame.tsx
  packages/react-components/components/__snapshots__/ReviewFrame.test.tsx.snap
Labels: automerge

#4313 Attestation Service 1.0.1
  dockerfiles/attestation-service/Dockerfile
  packages/attestation-service/package.json
  packages/attestation-service/src/db.ts
  packages/attestation-service/src/index.ts
  packages/attestation-service/src/request.ts
  packages/attestation-service/src/requestHandlers/liveness.ts
  packages/attestation-service/src/requestHandlers/status.ts
  packages/attestation-service/tsconfig.json
  packages/cli/src/commands/identity/test-attestation-service.ts
  packages/contractkit/src/wrappers/Attestations.ts
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wrappers_attestations_.attestationswrapper.md
  packages/docs/developer-resources/contractkit/reference/enums/_contractkit_src_wrappers_attestations_.attestationstate.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_attestations_.actionableattestation.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_attestations_.attesationservicerevealrequest.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_attestations_.attestationsconfig.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_attestations_.attestationstat.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_attestations_.attestationstateforissuer.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_attestations_.attestationstoken.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_attestations_.unselectedrequest.md
  packages/docs/developer-resources/contractkit/reference/modules/_contractkit_src_wrappers_attestations_.md
  packages/utils/src/index.ts
  packages/utils/src/io.ts
  packages/utils/src/string.ts
Labels: automerge

#4328 Some deploy updates
  .env.alfajores
  .env.rc1
  packages/helm-charts/eksportisto/templates/configmap.yaml
  packages/helm-charts/eksportisto/templates/statefulset.yaml
Labels: automerge

#4327 Catch all reveal errors
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/identity/verification.ts
Labels: automerge

#4326 Update attestation service docs with new image and remove country list
  packages/docs/getting-started/running-a-validator-in-mainnet.md
Labels: automerge

#4329 Adjust .env.development
  packages/attestation-service/config/.env.development
Labels: automerge

#4330 Crawl attestation service version
  packages/contractkit/src/wrappers/Attestations.ts
  packages/metadata-crawler/src/crawler.ts
Labels: automerge

#4305 [Wallet] Move signal handling to main
  packages/mobile/ios/celo/AppDelegate.m
  packages/mobile/ios/celo/main.m
Labels: automerge, wallet, wallet-quality

#4343 Change Test Faucet/ invite Link in App
  packages/mobile/branding/celo/src/brandingConfig.ts
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/onboarding.json
Labels: automerge

#4273 monitor full node health
  packages/helm-charts/celo-fullnode/templates/_helpers.tpl
  packages/helm-charts/celo-fullnode/templates/statefulset.yaml
  packages/helm-charts/celo-fullnode/values.yaml
  packages/helm-charts/common/templates/_helpers.tpl
Labels: automerge

#4333 Remove /app redirect
  packages/web/server/index.ts
Labels: automerge

#4336 [Wallet] Payment limit bug fix
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.test.tsx
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/store.ts
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/actions.ts
  packages/mobile/src/send/reducers.ts
  packages/mobile/src/send/saga.ts
  packages/mobile/src/send/utils.ts
Labels: automerge, wallet

#4346 Adds link to reserve from celo home page
  packages/web/public/static/locales/en/home.json
  packages/web/src/_page-tests/__snapshots__/index.test.tsx.snap
  packages/web/src/home/TwoAssets.tsx
Labels: automerge

#4335 [Wallet] Fix ContractKit init issues causing Pincode entry errors
  packages/contractkit/src/wallets/signers/rpc-signer.ts
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_signers_rpc_signer_.rpcsigner.md
  packages/mobile/__mocks__/src/web3/contracts.ts
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/app/saga.test.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/dappkit/dappkit.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/geth/geth.ts
  packages/mobile/src/geth/saga.ts
  packages/mobile/src/geth/selectors.ts
  packages/mobile/src/import/saga.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/localCurrency/saga.ts
  packages/mobile/src/networkInfo/saga.ts
  packages/mobile/src/pincode/authentication.ts
  packages/mobile/src/redux/persist-helper.ts
  packages/mobile/src/redux/sagas.ts
  packages/mobile/src/redux/selectors.ts
  packages/mobile/src/storage/keychain.tsx
  packages/mobile/src/utils/generators.ts
  packages/mobile/src/web3/actions.ts
  packages/mobile/src/web3/contracts.ts
  packages/mobile/src/web3/providers.ts
  packages/mobile/src/web3/reducer.ts
  packages/mobile/src/web3/saga.test.ts
  packages/mobile/src/web3/saga.ts
  packages/mobile/src/web3/selectors.ts
  packages/mobile/src/web3/utils.ts
  packages/react-components/services/ReactNativeLogger.ts
Labels: automerge

#4342 Fix double slash
  packages/contractkit/src/wrappers/Attestations.ts
Labels: automerge

#4344 [Wallet] Add onboarding education
  packages/mobile/branding/celo/src/icons/Logo.v2.tsx
  packages/mobile/branding/celo/src/images/onboarding-education-1.png
  packages/mobile/branding/celo/src/images/onboarding-education-2.png
  packages/mobile/branding/celo/src/images/onboarding-education-3.png
  packages/mobile/e2e/Transfer.spec.js
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/scripts/sync_branding.sh
  packages/mobile/src/account/AccountKeyEducation.tsx
  packages/mobile/src/account/Education.test.tsx
  packages/mobile/src/account/Education.tsx
  packages/mobile/src/account/GoldEducation.tsx
  packages/mobile/src/account/Settings.tsx
  packages/mobile/src/account/__snapshots__/AccountKeyEducation.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Education.test.tsx.snap
  packages/mobile/src/account/__snapshots__/GoldEducation.test.tsx.snap
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/app/reducers.ts
  packages/mobile/src/backup/BackupSocial.tsx
  packages/mobile/src/backup/__snapshots__/DelayButton.test.tsx.snap
  packages/mobile/src/components/Carousel.tsx
  packages/mobile/src/home/__snapshots__/NotificationBox.test.tsx.snap
  packages/mobile/src/i18n.ts
  packages/mobile/src/images/Images.ts
  packages/mobile/src/language/Language.test.tsx
  packages/mobile/src/language/Language.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/TopBarButton.v2.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/onboarding/LanguageButton.tsx
  packages/mobile/src/onboarding/TopBarTextButtonOnboarding.tsx
  packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx
  packages/mobile/src/onboarding/education/OnboardingEducationScreen.tsx
  packages/mobile/src/verify/VerificationInputScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationLoadingScreen.test.tsx.snap
  packages/react-components/components/Button.v2.tsx
  packages/react-components/styles/colors.v2.tsx
  packages/react-components/styles/progressDots.ts
Labels: automerge

#4348 [Wallet] Verification Balance Check Bug
  packages/mobile/locales/en-US/nuxVerification2.json
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/nuxVerification2.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/src/identity/types.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/VerificationFailedModal.tsx
Labels: automerge, wallet

#4340 Remove react-devtool package
  packages/mobile/package.json
  yarn.lock
Labels: automerge

#4349 Fix e2e mobile test on iOS
  .circleci/config.yml
Labels: automerge

#4350 [Wallet] Skip revoke verification if account is not verified
  packages/mobile/src/identity/revoke.ts
Labels: automerge

#4351 [Wallet] Allow to pay fee in Celo
  packages/mobile/src/account/__snapshots__/FiatExchange.test.tsx.snap
  packages/mobile/src/account/__snapshots__/GoldEducation.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Invite.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Settings.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Support.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap
  packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
  packages/mobile/src/navigator/DrawerTopBar.tsx
  packages/mobile/src/transactions/contract-utils.ts
  packages/mobile/src/transactions/send.ts
Labels: automerge

#4337 Add blockNumber to signer response
  packages/phone-number-privacy/common/package.json
  packages/phone-number-privacy/common/src/index.ts
  packages/phone-number-privacy/common/src/interfaces/SignMessageResponse.ts
  packages/phone-number-privacy/common/src/interfaces/error-utils.ts
Labels: automerge

#4356 Cody/pgpnp common interface success
  packages/phone-number-privacy/common/package.json
  packages/phone-number-privacy/common/src/index.ts
  packages/phone-number-privacy/common/src/interfaces/sign-message-response.ts
Labels: automerge

#4299 Specify a context when deploying oracles, add 3rd mainnet cluster
  .env.baklava
  .env.oracledev
  .env.rc1
  packages/celotool/src/cmds/deploy/destroy/oracle-fullnode.ts
  packages/celotool/src/cmds/deploy/destroy/oracle.ts
  packages/celotool/src/cmds/deploy/initial/oracle-fullnode.ts
  packages/celotool/src/cmds/deploy/initial/oracle.ts
  packages/celotool/src/cmds/deploy/upgrade/oracle-fullnode.ts
  packages/celotool/src/cmds/deploy/upgrade/oracle.ts
  packages/celotool/src/lib/aks-fullnode.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/oracle-fullnode.ts
  packages/celotool/src/lib/oracle.ts
  packages/celotool/src/lib/prometheus.ts
Labels: automerge

#4361 [Wallet][ReDesign] Onboarding sucess screen
  .watchmanconfig
  packages/mobile/branding/celo/src/icons/Logo.v2.tsx
  packages/mobile/branding/celo/src/images/background.jpg
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/scripts/sync_branding.sh
  packages/mobile/src/images/Images.ts
  packages/mobile/src/onboarding/success/OnboardingSuccessScreen.tsx
Labels: automerge

#4236 add sub-page links
  packages/docs/developer-resources/integrations/integrations.md
Labels: automerge, docs

#4332 Create celo-for-eth-devs.md
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/celo-for-eth-devs.md
Labels: automerge, docs

#4325 [Wallet] Fix Celo/cUSD rates
  packages/blockchain-api/src/blockscout.ts
  packages/blockchain-api/src/currencyConversion/CurrencyConversionAPI.test.ts
  packages/blockchain-api/src/currencyConversion/CurrencyConversionAPI.ts
  packages/blockchain-api/src/currencyConversion/GoldExchangeRateAPI.ts
  packages/blockchain-api/src/schema.ts
  packages/blockchain-api/test/blockscout.test.ts
  packages/mobile/src/exchange/ExchangeHomeScreen.tsx
  packages/mobile/src/exchange/saga.ts
Labels: automerge

#4253 fix typo
  packages/docs/celo-codebase/wallet/intro.md
Labels: automerge

#4385 Design Critique with Cory
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/src/account/__snapshots__/AccountKeyEducation.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Education.test.tsx.snap
  packages/mobile/src/account/__snapshots__/FiatExchange.test.tsx.snap
  packages/mobile/src/account/__snapshots__/GoldEducation.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Invite.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Settings.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Support.test.tsx.snap
  packages/mobile/src/account/__snapshots__/SupportContact.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupPhrase.test.tsx.snap
  packages/mobile/src/components/AccountNumber.tsx
  packages/mobile/src/components/TotalLineItem.tsx
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationCard.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationScreen.test.tsx.snap
  packages/mobile/src/exchange/ExchangeTradeScreen.tsx
  packages/mobile/src/exchange/__snapshots__/ExchangeConfirmationCard.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeReview.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeAmount.test.tsx.snap
  packages/mobile/src/home/SendOrRequestBar.tsx
  packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
  packages/mobile/src/import/__snapshots__/ImportWallet.test.tsx.snap
  packages/mobile/src/navigator/DrawerTopBar.tsx
  packages/mobile/src/onboarding/contacts/__snapshots__/ImportContactsScreen.test.tsx.snap
  packages/mobile/src/onboarding/registration/__snapshots__/JoinCelo.test.tsx.snap
  packages/mobile/src/onboarding/registration/__snapshots__/RegulatoryTerms.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestConfirmation.test.tsx.snap
  packages/mobile/src/recipients/RecipientItem.tsx
  packages/mobile/src/recipients/RecipientPicker.tsx
  packages/mobile/src/recipients/__snapshots__/RecipientItem.test.tsx.snap
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/send/__snapshots__/ValidateRecipientAccount.test.tsx.snap
  packages/mobile/src/transactions/NoActivity.tsx
  packages/mobile/src/transactions/__snapshots__/TransactionFeed.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
  packages/react-components/components/Button.v2.tsx
  packages/react-components/components/__snapshots__/Button.v2.test.tsx.snap
  packages/react-components/styles/fonts.v2.tsx
Labels: automerge

#4191 Update 003-stake-off-master-validator.md
  packages/web/validator-badges/003-stake-off-master-validator.md
Labels: automerge, docs

#4394 Don't expose debug RPC API on celo-fullnode chart
  .env.oracledev
  packages/celotool/src/lib/aks-fullnode.ts
  packages/helm-charts/celo-fullnode/templates/statefulset.yaml
  packages/helm-charts/celo-fullnode/values.yaml
Labels: automerge

#4384 fix language in faucet page.
  packages/web/public/static/locales/en/faucet.json
  packages/web/src/_page-tests/developers/__snapshots__/faucet.test.tsx.snap
Labels: automerge

#4386 Small changes to PNP docs
  packages/docs/celo-codebase/protocol/identity/phone-number-privacy.md
Labels: automerge

#4398 Job page Buenos Aires vs Remote Fix
  packages/web/src/jobs/version3/Jobs.tsx
Labels: automerge

#4364 [Wallet] Secure Send Payment Request Bugs
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/contactMapping.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.test.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListScreen.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestSummaryNotification.tsx
  packages/mobile/src/paymentRequest/PaymentRequestConfirmation.tsx
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/utils.ts
  packages/mobile/src/qrcode/QRScanner.tsx
  packages/mobile/src/qrcode/utils.ts
  packages/mobile/src/send/SendAmount.test.tsx
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/ValidateRecipientAccount.tsx
  packages/mobile/src/send/ValidateRecipientIntro.tsx
  packages/mobile/src/send/__snapshots__/ValidateRecipientIntro.test.tsx.snap
  packages/mobile/src/send/actions.ts
  packages/mobile/src/send/saga.test.ts
  packages/mobile/src/send/saga.ts
  packages/mobile/test/schemas.ts
  packages/react-components/components/CallToActionsBar.tsx
Labels: automerge, wallet

#4417 [Wallet] Instrument geth and contractkit initialization analytics
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/geth/geth.ts
  packages/mobile/src/web3/contracts.ts
Labels: automerge

#4432 Added footer variable with the commit
  packages/helm-charts/blockscout/templates/_helpers.tpl
Labels: automerge

#4418 [Wallet] Bugs when receiving payment request from unverified phone number
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/contactMapping.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/saga.ts
  packages/mobile/src/identity/secureSend.ts
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.test.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.tsx
  packages/mobile/src/qrcode/QRScanner.tsx
  packages/mobile/src/qrcode/utils.ts
  packages/mobile/src/send/ValidateRecipientAccount.tsx
  packages/mobile/src/send/ValidateRecipientIntro.tsx
  packages/mobile/src/send/actions.ts
  packages/mobile/src/send/saga.ts
  packages/mobile/src/send/utils.ts
  packages/mobile/test/schemas.ts
Labels: automerge, wallet

#4453 [Wallet] QR Request Bug + Android Activity Monitor Bug
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentListItem.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentReminderSummaryNotification.test.tsx.snap
  packages/mobile/src/home/SendOrRequestBar.tsx
  packages/mobile/src/home/__snapshots__/NotificationBox.test.tsx.snap
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/notifications/__snapshots__/SummaryNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.test.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.tsx
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestSummaryNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestSummaryNotification.test.tsx.snap
  packages/mobile/src/qrcode/utils.ts
  packages/mobile/src/send/Send.tsx
  packages/mobile/src/send/SendAmount.test.tsx
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/saga.ts
  packages/react-components/components/CallToActionsBar.tsx
Labels: automerge, wallet

#4451 [Wallet] Remove jndcrash since we are using sentry
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/proguard-rules.pro
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/android/app/src/main/java/org/celo/mobile/MainApplication.java
  packages/mobile/android/app/src/main/java/org/celo/mobile/NdkCrashService.java
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/src/sentry/Sentry.ts
  yarn.lock
Labels: automerge, wallet, wallet-quality

#4334 Signer DB Discrepancy Detection
  .env
  .vscode/launch.json
  dependency-graph.json
  dockerfiles/phone-number-privacy/Dockerfile
  packages/phone-number-privacy/combiner/package.json
  packages/phone-number-privacy/combiner/src/bls/bls-cryptography-client.ts
  packages/phone-number-privacy/combiner/src/common/constants.ts
  packages/phone-number-privacy/combiner/src/common/error-utils.ts
  packages/phone-number-privacy/combiner/src/config.ts
  packages/phone-number-privacy/combiner/src/database/wrappers/account.ts
  packages/phone-number-privacy/combiner/src/database/wrappers/number-pairs.ts
  packages/phone-number-privacy/combiner/src/match-making/get-contact-matches.ts
  packages/phone-number-privacy/combiner/src/salt-generation/get-threshold-salt.ts
  packages/phone-number-privacy/combiner/test/end-to-end/get-blinded-salt.test.ts
  packages/phone-number-privacy/combiner/test/end-to-end/get-contact-matches.test.ts
  packages/phone-number-privacy/combiner/test/index.test.ts
  packages/phone-number-privacy/combiner/test/salt-generation/bls-signature.test.ts
  packages/phone-number-privacy/common/package.json
  packages/phone-number-privacy/common/src/interfaces/error-utils.ts
  packages/phone-number-privacy/signer/package.json
  packages/phone-number-privacy/signer/src/bls/bls-cryptography-client.ts
  packages/phone-number-privacy/signer/src/common/constants.ts
  packages/phone-number-privacy/signer/src/common/error-utils.ts
  packages/phone-number-privacy/signer/src/common/identity.ts
  packages/phone-number-privacy/signer/src/config.ts
  packages/phone-number-privacy/signer/src/database/wrappers/account.ts
  packages/phone-number-privacy/signer/src/key-management/aws-key-provider.ts
  packages/phone-number-privacy/signer/src/key-management/azure-key-provider.ts
  packages/phone-number-privacy/signer/src/key-management/google-key-provider.ts
  packages/phone-number-privacy/signer/src/salt-generation/get-salt.ts
  packages/phone-number-privacy/signer/src/salt-generation/query-quota.ts
  packages/phone-number-privacy/signer/src/server.ts
  packages/phone-number-privacy/signer/src/web3/contracts.ts
  packages/phone-number-privacy/signer/test/end-to-end/get-blinded-salt.test.ts
  packages/phone-number-privacy/signer/test/index.test.ts
  packages/phone-number-privacy/signer/test/salt-generation/query-quota.test.ts
  yarn.lock
Labels: automerge

#4458 Update Celotool/attestation bot image
  .env.rc1
Labels: automerge

#4193 [Validator Badge] moonli.me 0xc8A81D473992c7c6D3F469A8263F24914625709d.md
  packages/web/validator-badges/003-stake-off-master-validator.md
Labels: automerge, docs

#4463 [Docs] Fix typo
  packages/docs/celo-holder-guide/quick-start.md
Labels: automerge

#4186 [Validator Badge] Staking Fund 0xFaa0b40645Ee5E8D9AE38393e8cDF8e5baA71d13
  packages/web/validator-badges/003-stake-off-master-validator.md
Labels: automerge, docs

#4355 Configure migration parameters for Alfajores reset
  .env.alfajores
  .env.alfajoresstaging
  dockerfiles/cli-standalone/Dockerfile
  dockerfiles/cli/Dockerfile
  packages/celotool/src/cmds/generate/bootnode-enode.ts
  packages/cli/start_geth.sh
  packages/docs/developer-resources/integrations/general.md
  packages/docs/developer-resources/walkthroughs/hello-contract-remote-node.md
  packages/docs/developer-resources/walkthroughs/hello-mobile-dapp.md
  packages/docs/developer-resources/walkthroughs/hellocontracts.md
  packages/docs/getting-started/running-a-full-node-in-alfajores.md
  packages/faucet/README.md
  packages/protocol/lib/proxy-utils.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/truffle-config.js
Labels: automerge

#4472 More accurate exchange rate estimate stored in firebase for CELO chart in wallet
  packages/notification-service/src/exchange/exchangeQuery.ts
Labels: automerge

#4188 [Validator Badge] DSRV CeloWhale.com 0xF83C93ea360B66DDCD532960304948…
  packages/web/validator-badges/003-stake-off-master-validator.md
Labels: automerge, docs

#4189 [Validator Badge] Censusworks 0x0d4f8cEA48cDaDEAe345431577a64983c0535B12
  packages/web/validator-badges/003-stake-off-master-validator.md
Labels: automerge, docs

#4222 [Validator Badge] Masternode24.de 0x95aE59515915D6c493a846aE022F93726…
  packages/web/validator-badges/003-stake-off-master-validator.md
Labels: automerge, docs

#4429 [Wallet] Implement explanations of the fees and use fee drawer on exchanges
  packages/mobile/src/account/InviteReview.tsx
  packages/mobile/src/account/__snapshots__/InviteReview.test.tsx.snap
  packages/mobile/src/components/FeeDrawer.tsx
  packages/mobile/src/components/FeeIcon.test.tsx
  packages/mobile/src/components/FeeIcon.tsx
  packages/mobile/src/components/__snapshots__/FeeIcon.test.tsx.snap
  packages/mobile/src/escrow/ReclaimPaymentConfirmationCard.tsx
  packages/mobile/src/escrow/ReclaimPaymentConfirmationScreen.test.tsx
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationCard.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationScreen.test.tsx.snap
  packages/mobile/src/exchange/ExchangeConfirmationCard.tsx
  packages/mobile/src/exchange/ExchangeReview.tsx
  packages/mobile/src/exchange/FeeExchangeEducation.test.tsx
  packages/mobile/src/exchange/FeeExchangeEducation.tsx
  packages/mobile/src/exchange/__snapshots__/ExchangeConfirmationCard.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeReview.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/FeeExchangeEducation.test.tsx.snap
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/send/FeeEducation.test.tsx
  packages/mobile/src/send/FeeEducation.tsx
  packages/mobile/src/send/__snapshots__/FeeEducation.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransferConfirmationCard.test.tsx.snap
  packages/mobile/src/utils/formatting.ts
Labels: automerge

#4268 [Validator Badge] Tango 0x98c62d86634bB0E3f818EFC550e2F33369Eae7F3
  packages/web/validator-badges/006-genesis-1st-transaction.md
Labels: automerge, docs

#4288 Add syncnode for master validator badge
  packages/web/validator-badges/003-stake-off-master-validator.md
Labels: automerge, docs

#4501 Pretoria research lab badge
  packages/web/validator-badges/003-stake-off-master-validator.md
Labels: automerge, docs

#4502 [Wallet] Fix sync branding script with git 2.27
  packages/mobile/scripts/sync_branding.sh
Labels: automerge

#2721 Certora Lockedgold and Accounts verification
  .circleci/config.yml
  packages/protocol/contracts/common/Accounts.sol
  packages/protocol/contracts/governance/LockedGold.sol
  packages/protocol/specs/accounts.spec
  packages/protocol/specs/harnesses/AccountsHarness.sol
  packages/protocol/specs/harnesses/GoldTokenHarness.sol
  packages/protocol/specs/harnesses/IRegistryExtended.sol
  packages/protocol/specs/harnesses/LockedGoldHarness.sol
  packages/protocol/specs/harnesses/RegistryHarness.sol
  packages/protocol/specs/lockedGold.spec
  packages/protocol/specs/locked_gold_linked.spec
Labels: automerge

#4503 Document MultiSig limitations
  packages/protocol/contracts/common/MultiSig.sol
Labels: automerge

#4489 [Wallet] Secure Send Navigation Bug Fix
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/send/ValidateRecipientAccount.test.tsx
  packages/mobile/src/send/ValidateRecipientAccount.tsx
  packages/mobile/test/schemas.ts
Labels: automerge, wallet

#4483 [Wallet][ReDesign] Verification progress screen
  packages/mobile/__mocks__/@react-navigation/native.ts
  packages/mobile/__mocks__/react-native-safe-area-context.ts
  packages/mobile/branding/celo/src/images/circular-progress-big.png
  packages/mobile/branding/celo/src/images/circular-progress-big@1.5x.png
  packages/mobile/branding/celo/src/images/circular-progress-big@2x.png
  packages/mobile/branding/celo/src/images/circular-progress-big@3x.png
  packages/mobile/branding/celo/src/images/circular-progress-big@4x.png
  packages/mobile/branding/celo/src/images/verification-education-1.png
  packages/mobile/branding/celo/src/images/verification-education-2.png
  packages/mobile/branding/celo/src/images/verification-education-3.png
  packages/mobile/branding/celo/src/images/verification-education-4.png
  packages/mobile/locales/en-US/nuxVerification2.json
  packages/mobile/locales/es-419/nuxVerification2.json
  packages/mobile/package.json
  packages/mobile/scripts/sync_branding.sh
  packages/mobile/src/account/__snapshots__/AccountKeyEducation.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Education.test.tsx.snap
  packages/mobile/src/account/__snapshots__/GoldEducation.test.tsx.snap
  packages/mobile/src/components/Carousel.tsx
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/home/__snapshots__/NotificationBox.test.tsx.snap
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/images/Images.ts
  packages/mobile/src/index.d.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/utils/reanimated.ts
  packages/mobile/src/utils/useBackHandler.ts
  packages/mobile/src/verify/VerificationCountdown.tsx
  packages/mobile/src/verify/VerificationFailedModal.tsx
  packages/mobile/src/verify/VerificationInterstitialScreen.test.tsx
  packages/mobile/src/verify/VerificationInterstitialScreen.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.test.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationInterstitialScreen.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/VerificationLoadingScreen.test.tsx.snap
  packages/mobile/src/verify/backgroundAnim.json
  packages/react-components/components/Pagination.tsx
  packages/react-components/components/PulsingDot.tsx
  packages/react-components/icons/UpHandle.tsx
  packages/react-components/styles/progressDots.ts
  yarn.lock
Labels: automerge

#4508 [Wallet] Allow users to buy CELO on mainnet through Moonpay
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/locales/es-419/fiatExchangeFlow.json
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.tsx
  packages/mobile/src/fiatExchanges/MoonPay.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeAmount.test.tsx.snap
  packages/mobile/src/flags.ts
  packages/mobile/src/geth/networkConfig.ts
  packages/moonpay-auth/.env.enc
  packages/moonpay-auth/.firebaserc
  packages/moonpay-auth/package.json
  packages/moonpay-auth/src/config.ts
  packages/moonpay-auth/src/index.ts
Labels: automerge

#4510 Add asdf support in the iOS React Native build phase
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
Labels: automerge

#4511 [Wallet] Fix NaN subtotal on Celo exchange, when no connection
  packages/mobile/src/utils/currencyExchange.ts
Labels: automerge

#4504 [Wallet] Fix DAppKit
  packages/dappkit/README.md
  packages/mobile/locales/en-US/dappkit.json
  packages/mobile/locales/es-419/dappkit.json
  packages/mobile/package.json
  packages/mobile/src/app/actions.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/dappkit/DappKitAccountScreen.tsx
  packages/mobile/src/dappkit/DappKitSignTxScreen.tsx
  packages/mobile/src/dappkit/DappKitTxDataScreen.tsx
  packages/mobile/src/navigator/NavigationService.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/utils/linking.ts
  yarn.lock
Labels: automerge

#4284 Add Conclave group address to list of master validators
  packages/web/validator-badges/003-stake-off-master-validator.md
Labels: automerge, docs

#4495 [Wallet] Fix last Celo rate in the chart
  packages/mobile/src/exchange/saga.ts
  packages/notification-service/src/exchange/exchangeQuery.ts
  packages/utils/src/celoHistory.ts
Labels: automerge

#4485 [Verification] Verification flow improvements
  packages/attestation-service/src/requestHandlers/attestation.ts
  packages/contractkit/src/wrappers/Attestations.ts
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wrappers_attestations_.attestationswrapper.md
  packages/mobile/locales/en-US/nuxVerification2.json
  packages/mobile/locales/es-419/nuxVerification2.json
  packages/mobile/src/escrow/ReclaimPaymentConfirmationCard.tsx
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationCard.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationScreen.test.tsx.snap
  packages/mobile/src/identity/types.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestConfirmation.test.tsx.snap
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/verify/VerificationFailedModal.tsx
  packages/protocol/contracts/identity/Attestations.sol
  packages/react-components/components/ReviewFrame.tsx
Labels: automerge

#4519 [Wallet] Fix push permission never asked on iOS
  packages/mobile/src/firebase/firebase.test.ts
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/utils/typescript.ts
Labels: automerge

#4520 [Wallet] Fix bug because of untyped yield take action
  packages/mobile/src/geth/actions.ts
  packages/mobile/src/geth/saga.ts
  packages/mobile/src/qrcode/utils.ts
  packages/mobile/src/send/actions.ts
  packages/mobile/src/send/saga.ts
  packages/mobile/src/web3/saga.ts
Labels: automerge, wallet

#4473 [Wallet] Visual refinement 2
  packages/mobile/src/account/Profile.tsx
  packages/mobile/src/account/__snapshots__/FiatExchange.test.tsx.snap
  packages/mobile/src/account/__snapshots__/GoldEducation.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Invite.test.tsx.snap
  packages/mobile/src/account/__snapshots__/InviteReview.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Profile.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Settings.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Support.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap
  packages/mobile/src/components/AccountNumber.tsx
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationCard.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationScreen.test.tsx.snap
  packages/mobile/src/exchange/ExchangeReview.tsx
  packages/mobile/src/exchange/ExchangeTradeScreen.tsx
  packages/mobile/src/exchange/__snapshots__/ExchangeReview.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap
  packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
  packages/mobile/src/language/Language.tsx
  packages/mobile/src/localCurrency/SelectLocalCurrency.tsx
  packages/mobile/src/localCurrency/__snapshots__/SelectLocalCurrency.test.tsx.snap
  packages/mobile/src/navigator/DrawerNavigator.tsx
  packages/mobile/src/navigator/DrawerTopBar.tsx
  packages/mobile/src/paymentRequest/PaymentRequestConfirmation.tsx
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestConfirmation.test.tsx.snap
  packages/mobile/src/qrcode/__snapshots__/QRCode.test.tsx.snap
  packages/react-components/components/PhoneNumberWithFlag.tsx
  packages/react-components/components/__snapshots__/Avatar.test.tsx.snap
Labels: automerge

#4174 Make Election.revokeAllActive callable by removing prohibitive reentrancy check
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/test/governance/election.ts
Labels: automerge

#4462 Update developer key doc to only suggest using clabs.co domain
  developer_key_publishing.md
Labels: automerge

#4471 Add mariano@clabs.co gpg key to the website
  packages/web/openpgpkey/README.md
  packages/web/openpgpkey/clabs.co/hu/qu8o7gthfqer78nrk7ah5ufuh58dhup8
Labels: automerge

#4516 docs: update docker imgs for 1.0.1 release
  packages/docs/community/release-process/blockchain-client.md
  packages/docs/developer-resources/walkthroughs/hellocontracts.md
  packages/docs/getting-started/faucet.md
  packages/docs/getting-started/running-a-full-node-in-alfajores.md
  packages/docs/getting-started/running-a-full-node-in-baklava.md
  packages/docs/getting-started/running-a-full-node-in-mainnet.md
  packages/docs/getting-started/running-a-validator-in-baklava.md
  packages/docs/getting-started/running-a-validator-in-mainnet.md
  packages/docs/operations-manual/monitoring.md
  packages/docs/operations-manual/node-upgrades.md
Labels: automerge

#4522 Remove Dev Wallet & cGLD
  packages/web/public/static/locales/en/alliance.json
  packages/web/public/static/locales/en/brand.json
  packages/web/public/static/locales/en/dev.json
  packages/web/public/static/locales/en/download.json
  packages/web/public/static/locales/en/faucet.json
  packages/web/src/_page-tests/__snapshots__/alliance.test.tsx.snap
  packages/web/src/_page-tests/developers/__snapshots__/Index.test.tsx.snap
  packages/web/src/_page-tests/developers/__snapshots__/wallet.test.tsx.snap
  packages/web/src/_page-tests/validators/__snapshots__/index.test.tsx.snap
  packages/web/src/download/Cover.tsx
  packages/web/src/download/MobileApp.tsx
Labels: automerge

#4531 Update setup guide
  SETUP.md
Labels: automerge

#4533 [Wallet] Update Cash In for CELO purchases
  packages/mobile/.env
  packages/mobile/.env.mainnet
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-419/fiatExchangeFlow.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/secrets.json.enc
  packages/mobile/src/account/FiatExchange.tsx
  packages/mobile/src/account/__snapshots__/FiatExchange.test.tsx.snap
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/config.ts
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.test.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/fiatExchanges/MoonPay.test.tsx
  packages/mobile/src/fiatExchanges/MoonPay.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeAmount.test.tsx.snap
  packages/mobile/src/flags.ts
  packages/mobile/src/navigator/types.tsx
Labels: automerge

#4512 Change DEK derivation scheme and register DEK for all wallet users
  packages/cli/src/commands/account/new.ts
  packages/contractkit/src/wallets/ledger-wallet.ts
  packages/docs/command-line-interface/account.md
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/es-419/sendFlow7.json
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/components/CommentTextInput.tsx
  packages/mobile/src/components/FeeDrawer.tsx
  packages/mobile/src/components/FeeIcon.tsx
  packages/mobile/src/fees/CalculateFee.tsx
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/commentEncryption.test.ts
  packages/mobile/src/identity/commentEncryption.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/saga.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/import/saga.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestConfirmation.test.tsx.snap
  packages/mobile/src/redux/sagas.ts
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/send/saga.ts
  packages/mobile/src/transactions/TransactionFeed.tsx
  packages/mobile/src/web3/actions.ts
  packages/mobile/src/web3/dataEncryptionKey.ts
  packages/mobile/src/web3/reducer.ts
  packages/mobile/src/web3/saga.ts
  packages/mobile/src/web3/selectors.ts
  packages/mobile/test/schemas.ts
  packages/react-components/components/ReviewFrame.tsx
  packages/utils/package.json
  packages/utils/src/account.test.ts
  packages/utils/src/account.ts
  packages/utils/src/commentEncryption.test.ts
  packages/utils/src/commentEncryption.ts
  packages/utils/src/dataEncryptionKey.test.ts
  packages/utils/src/dataEncryptionKey.ts
  packages/utils/src/index.ts
  packages/utils/src/types.d.ts
Labels: automerge

#4461 Add wiggle room to locked gold requirements
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/test/governance/validators.ts
Labels: automerge

#4521 [web] Kit Fixes/ updates
  packages/web/server/index.ts
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/exchange-icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/experience/common/MobileKitMenu.test.tsx
  packages/web/src/experience/common/MobileKitMenu.tsx
  packages/web/src/experience/common/Page.tsx
  packages/web/src/experience/common/TopBar.tsx
  packages/web/src/header/Hamburger.tsx
  packages/web/src/header/Header.3.tsx
  packages/web/src/icons/prosper-light-bg.png
  packages/web/src/shared/Footer.tsx
  packages/web/src/shared/MobileMenu.test.tsx
  packages/web/src/shared/MobileMenu.tsx
  packages/web/src/shared/__snapshots__/Footer.test.tsx.snap
  packages/web/src/shared/menu-items.ts
  packages/web/src/utils/useBooleanToggle.ts
Labels: automerge, web

#4538 Updated for a typo
  packages/docs/overview.md
Labels: automerge

#4474 Update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge

#4543 Update Terms to latest version
  packages/mobile/locales/en-US/nuxNamePin1.json
  packages/mobile/locales/es-419/nuxNamePin1.json
Labels: automerge

#4546 Remove unnecessary dependency from contractkit
  packages/contractkit/package.json
Labels: automerge

#4524 Update blockchain client release docs to reflect recent progress
  packages/docs/community/release-process/blockchain-client.md
Labels: automerge

#4550 [Wallet] Some minor cleanup
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/locales/es-419/walletFlow5.json
  packages/mobile/src/account/actions.ts
  packages/mobile/src/account/reducer.ts
  packages/mobile/src/config.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/fees/CalculateFee.tsx
  packages/mobile/src/flags.ts
  packages/mobile/src/home/NotificationBox.test.tsx
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/home/WalletHome.test.tsx
  packages/mobile/src/home/selectors.ts
  packages/mobile/src/identity/contactMapping.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/missingGlobals.ts
  packages/mobile/src/utils/Logger.ts
  packages/mobile/src/utils/linking.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#4557 [Wallet] fix attestation codes being wrongly set as completed
  packages/mobile/locales/en-US/nuxVerification2.json
  packages/mobile/locales/es-419/nuxVerification2.json
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/store.ts
  packages/mobile/src/verify/VerificationFailedModal.tsx
Labels: automerge

#4556 [Wallet] Fix "User did not share" error
  packages/mobile/src/qrcode/utils.ts
  packages/mobile/src/send/saga.ts
Labels: automerge

#4545 [Wallet] Add new onboarding Welcome screen
  packages/mobile/__mocks__/@react-navigation/native.ts
  packages/mobile/branding/celo/src/images/welcome-background.png
  packages/mobile/e2e/Transfer.spec.js
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/scripts/run_e2e.sh
  packages/mobile/scripts/sync_branding.sh
  packages/mobile/scripts/verify_locales.sh
  packages/mobile/src/account/actions.ts
  packages/mobile/src/account/reducer.ts
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/images/Images.ts
  packages/mobile/src/import/ImportWallet.tsx
  packages/mobile/src/invite/EnterInviteCode.tsx
  packages/mobile/src/invite/__snapshots__/EnterInviteCode.test.tsx.snap
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/onboarding/UseBackToWelcomeScreen.tsx
  packages/mobile/src/onboarding/education/OnboardingEducationScreen.tsx
  packages/mobile/src/onboarding/registration/NameAndNumber.test.tsx
  packages/mobile/src/onboarding/registration/NameAndNumber.tsx
  packages/mobile/src/onboarding/registration/RegulatoryTerms.test.tsx
  packages/mobile/src/onboarding/registration/RegulatoryTerms.tsx
  packages/mobile/src/onboarding/registration/SelectCountry.tsx
  packages/mobile/src/onboarding/registration/__snapshots__/NameAndNumber.test.tsx.snap
  packages/mobile/src/onboarding/welcome/Welcome.test.tsx
  packages/mobile/src/onboarding/welcome/Welcome.tsx
  packages/mobile/src/pincode/PincodeSet.tsx
  packages/mobile/test/schemas.ts
Labels: automerge

#4568 Add transaction confirmed event
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/transactions/send.ts
Labels: automerge

#4553 Add instructions for setting gas price to pay fees in cUSD
  packages/contractkit/README.md
  packages/docs/developer-resources/contractkit/reference/README.md
Labels: automerge

#4574 [NotificationService] Rename "Celo Gold" -> "CELO" in push notifications
  packages/notification-service/locales/en.json
  packages/notification-service/locales/es.json
Labels: automerge

#4549 update lockedgold spec for new Certora prover
  packages/protocol/contracts/common/Accounts.sol
  packages/protocol/specs/lockedGold.spec
Labels: automerge

#4582 [Wallet] Add title to Terms & Conditions
  packages/mobile/locales/en-US/nuxNamePin1.json
  packages/mobile/locales/es-419/nuxNamePin1.json
  packages/mobile/src/onboarding/registration/RegulatoryTerms.tsx
  packages/mobile/src/onboarding/registration/__snapshots__/RegulatoryTerms.test.tsx.snap
Labels: automerge

#4586 Typo
  packages/docs/developer-resources/contractkit/usage.md
Labels: automerge

#4525 [Wallet] Add transitions to some screens on iOS
  packages/mobile/src/account/AccountKeyEducation.tsx
  packages/mobile/src/account/Education.tsx
  packages/mobile/src/account/GoldEducation.tsx
  packages/mobile/src/account/__snapshots__/AccountKeyEducation.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Education.test.tsx.snap
  packages/mobile/src/account/__snapshots__/GoldEducation.test.tsx.snap
  packages/mobile/src/language/Language.tsx
  packages/mobile/src/navigator/DrawerNavigator.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/QRNavigator.tsx
  packages/mobile/src/onboarding/registration/RegulatoryTerms.tsx
  packages/mobile/src/onboarding/registration/SelectCountry.tsx
  packages/mobile/src/pincode/PincodeEnter.tsx
  packages/mobile/src/send/Send.tsx
Labels: automerge, wallet

#4594 flake tracker fix
  packages/flake-tracker/src/github.js
  packages/flake-tracker/src/utils.js
Labels: automerge

#4298 Allow signer to invoke Attestations withdraw function for fee collection
  packages/protocol/contracts/identity/Attestations.sol
  packages/protocol/test/identity/attestations.ts
Labels: automerge
