Repository celo-org/celo-monorepo, pull requests merged in 2020-12, with the labels that each got.

#5977 Added readiness and liveness probes for blockscout web and API compon…
  .env.alfajores
  .env.baklava
  .env.rc1
  packages/helm-charts/blockscout/templates/blockscout-api.deployment.yaml
  packages/helm-charts/blockscout/templates/blockscout-indexer.deployment.yaml
  packages/helm-charts/blockscout/templates/blockscout-web.deployment.yaml
Labels: automerge

#5979 Added rolling update configs for blockscout
  packages/helm-charts/blockscout/templates/blockscout-api.deployment.yaml
  packages/helm-charts/blockscout/templates/blockscout-indexer.deployment.yaml
  packages/helm-charts/blockscout/templates/blockscout-service-account.yaml
  packages/helm-charts/blockscout/templates/blockscout-web.deployment.yaml
Labels: automerge

#5982 Revert "Add CUSD transfer to MTW (#5709)"
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_metatransactionwallet_.metatransactionwalletwrapper.md
  packages/docs/developer-resources/contractkit/reference/modules/_wrappers_metatransactionwallet_.md
  packages/protocol/contracts/common/MetaTransactionWallet.sol
  packages/protocol/test/common/metatransactionwallet.ts
  packages/sdk/contractkit/src/wrappers/MetaTransactionWallet.ts
Labels: automerge

#5990 Added change cause annotation to blockscout deployments
  packages/celotool/src/lib/blockscout.ts
  packages/celotool/src/lib/gcloud_utils.ts
  packages/helm-charts/blockscout/templates/_helpers.tpl
  packages/helm-charts/blockscout/templates/blockscout-api.deployment.yaml
  packages/helm-charts/blockscout/templates/blockscout-indexer.deployment.yaml
  packages/helm-charts/blockscout/templates/blockscout-web.deployment.yaml
Labels: automerge

#5997 Add contractkit placeholder directory
  packages/contractkit/README.md
Labels: automerge, devX

#3162 Update docs for authorize signer key methods in ReleaseGold
  packages/protocol/contracts/governance/ReleaseGold.sol
Labels: automerge, docs

#5988 Fix revoked accounts appearing as verified
  package.json
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/locales/en-US/nuxVerification2.json
  packages/mobile/locales/es-419/accountScreen10.json
  packages/mobile/locales/es-419/nuxVerification2.json
  packages/mobile/src/account/Settings.tsx
  packages/mobile/src/account/__snapshots__/Settings.test.tsx.snap
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/identity/contactMapping.ts
  packages/mobile/src/identity/feelessVerification.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/revoke.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
Labels: automerge, wallet

#6001 Update voting criteria with notes on vote weighing
  packages/docs/validator-guide/celo-foundation-voting-policy.md
Labels: automerge

#5981 [Wallet] Fix download link on invite text in spanish
  packages/mobile/locales/es-419/sendFlow7.json
Labels: automerge, wallet

#6007 Plumo Espero Ceremony Page
  packages/web/jest.config.js
  packages/web/pages/_app.tsx
  packages/web/pages/plumo.tsx
  packages/web/public/static/locales/en/plumo.json
  packages/web/src/_page-tests/__snapshots__/plumo.test.tsx.snap
  packages/web/src/_page-tests/plumo.test.tsx
  packages/web/src/interfaces.d.ts
  packages/web/src/plumo/FeatherPoint.tsx
  packages/web/src/plumo/Landing.tsx
  packages/web/src/plumo/feather-triangle.svg
  packages/web/src/plumo/feather1.svg
  packages/web/src/plumo/feather2.svg
  packages/web/src/plumo/feather3.svg
  packages/web/src/plumo/phone-outline.svg
  packages/web/src/plumo/plumo-open-graph.jpg
  packages/web/src/plumo/plumo-sky-mobile.svg
  packages/web/src/plumo/plumo-sky.svg
  packages/web/src/shared/menu-items.ts
Labels: automerge

#5996 Remove multiproxy guide on mainnet
  packages/docs/getting-started/running-a-validator-in-mainnet.md
Labels: automerge

#6015 Fix the devchain generation for tests in ci
  .circleci/config.yml
Labels: automerge

#6056 remove unnecessary check in vote function
  packages/sdk/contractkit/src/wrappers/Election.ts
Labels: automerge

#6128 Add Categories to Alliance
  packages/web/pages/api/alliance.ts
  packages/web/public/static/locales/en/alliance.json
  packages/web/src/_page-tests/__snapshots__/alliance.test.tsx.snap
  packages/web/src/alliance/CategoryEnum.ts
  packages/web/src/alliance/Members.tsx
Labels: automerge

#6131 Update Plumo docs and landing page
  packages/docs/celo-codebase/protocol/plumo.md
  packages/web/public/static/locales/en/plumo.json
Labels: automerge

#6118 Fix listing links
  packages/docs/developer-resources/integrations/listings.md
Labels: automerge

#6174 Merge Audit 2.0 fixes
  packages/protocol/contracts/common/MetaTransactionWallet.sol
  packages/protocol/contracts/common/MetaTransactionWalletDeployer.sol
  packages/protocol/test/common/metatransactionwallet.ts
Labels: automerge

#6144 Certora - aligning package
  .circleci/config.yml
Labels: automerge

#6182 Update typechain generation version
  packages/komencikit/src/kit.ts
  packages/protocol/package.json
  yarn.lock
Labels: automerge

#6177 Leftover SDK refactor issues in KomenciKit
  packages/komencikit/examples/attestation-flow.ts
Labels: automerge

#6181 [Wallet] Use names and pictures from known addresses
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/saga.ts
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/store.ts
  packages/mobile/src/transactions/TransferAvatars.tsx
  packages/mobile/src/transactions/TransferFeedIcon.tsx
  packages/mobile/src/transactions/TransferFeedItem.test.tsx
  packages/mobile/src/transactions/TransferFeedItem.tsx
  packages/mobile/src/transactions/UserSection.tsx
  packages/mobile/src/transactions/transferFeedUtils.ts
Labels: automerge, wallet

#6125 Add ability to specify per token expiry in sorted oracles
  packages/protocol/contracts/stability/SortedOracles.sol
  packages/protocol/test/stability/sortedoracles.ts
  packages/sdk/contractkit/src/wrappers/SortedOracles.ts
Labels: automerge, protocol

#6176 Add ability to withdraw attestation rewards via CLI
  packages/cli/src/commands/identity/withdraw-attestation-rewards.ts
  packages/docs/command-line-interface/identity.md
  packages/sdk/contractkit/src/wrappers/Attestations.ts
Labels: automerge

#6212 [Wallet] <BigNumber>.toString() almost never return exponential notation
  packages/mobile/src/app/App.tsx
  packages/mobile/src/exchange/saga.ts
Labels: automerge

#6226 add redirect for broken dev overview link
  .gitbook.yaml
Labels: automerge, docs

#6234 [Wallet] Bump build numbers to 1.6
  packages/mobile/android/app/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/src/account/LicenseDisclaimer.txt
Labels: automerge

#6230 [Wallet] Fix "Shake-to-Contact" triggered while app is in background
  packages/mobile/src/navigator/NavigatorWrapper.tsx
Labels: automerge, wallet

#6237 Allow import to continue if wallet exists in Geth keystore
  packages/mobile/src/web3/saga.ts
Labels: automerge, wallet

#6178 Treat null receipt in Connection.getTransactionReceipt
  packages/mobile/src/web3/utils.ts
  packages/sdk/connect/src/connection.ts
  packages/sdk/connect/src/utils/formatter.ts
  packages/sdk/explorer/src/log-explorer.ts
Labels: automerge

#5240 Added fees to the activity feed
  packages/blockchain-api/.env
  packages/blockchain-api/package.json
  packages/blockchain-api/src/blockscout.ts
  packages/blockchain-api/src/config.ts
  packages/blockchain-api/src/events/Any.ts
  packages/blockchain-api/src/events/ContractCall.ts
  packages/blockchain-api/src/events/EscrowContractCall.ts
  packages/blockchain-api/src/events/EscrowReceived.ts
  packages/blockchain-api/src/events/EscrowSent.ts
  packages/blockchain-api/src/events/ExchangeCeloToToken.ts
  packages/blockchain-api/src/events/ExchangeContractCall.ts
  packages/blockchain-api/src/events/ExchangeTokenToCelo.ts
  packages/blockchain-api/src/events/Faucet.ts
  packages/blockchain-api/src/events/RegisterAccountDekContractCall.ts
  packages/blockchain-api/src/events/TokenReceived.ts
  packages/blockchain-api/src/events/TokenSent.ts
  packages/blockchain-api/src/events/Verification.ts
  packages/blockchain-api/src/events/index.ts
  packages/blockchain-api/src/helpers/EventBuilder.ts
  packages/blockchain-api/src/helpers/Input.ts
  packages/blockchain-api/src/helpers/InputDecoder.ts
  packages/blockchain-api/src/schema.ts
  packages/blockchain-api/src/transaction/Transaction.ts
  packages/blockchain-api/src/transaction/TransactionAggregator.ts
  packages/blockchain-api/src/transaction/TransactionClassifier.ts
  packages/blockchain-api/src/transaction/TransactionType.ts
  packages/blockchain-api/src/transaction/TransferCollection.ts
  packages/blockchain-api/src/transaction/TransfersNavigator.ts
  packages/blockchain-api/src/utils.ts
  packages/blockchain-api/test/InputDecoder.test.ts
  packages/blockchain-api/test/blockscout.test.ts
  packages/blockchain-api/test/mockTokenTxs.ts
Labels: do not merge

#6002 [Wallet] Handle back button when entering PIN
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/escrow/saga.test.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/exchange/actions.ts
  packages/mobile/src/exchange/reducer.ts
  packages/mobile/src/exchange/saga.test.ts
  packages/mobile/src/exchange/saga.ts
  packages/mobile/src/identity/privateHashing.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/navigator/DrawerNavigator.tsx
  packages/mobile/src/pincode/PincodeSet.test.tsx
  packages/mobile/src/pincode/PincodeSet.tsx
  packages/mobile/src/pincode/authentication.test.ts
  packages/mobile/src/pincode/authentication.ts
  packages/mobile/src/send/saga.test.ts
  packages/mobile/src/send/saga.ts
  packages/mobile/src/tokens/saga.ts
  packages/mobile/src/web3/saga.ts
Labels: automerge, wallet

#6257 Enable forno as default network setting
  packages/mobile/.env.alfajores
  packages/mobile/.env.alfajoresdev
  packages/mobile/.env.mainnet
  packages/mobile/.env.mainnetdev
  packages/mobile/src/config.ts
Labels: automerge, wallet

#6213 feat(plumo docs): add attestation details
  packages/docs/celo-codebase/protocol/plumo.md
Labels: automerge, docs

#5952 Updated doc removing reference to 1 wei lock bug
  packages/docs/getting-started/running-a-validator-in-mainnet.md
Labels: automerge, docs

#6261 [Wallet] Enable forno by default for e2e tests
  packages/mobile/.env.test
Labels: automerge, wallet

#6264 fix: add id field to eth_sign and eth_signTypedData calls
  packages/sdk/connect/src/connection.ts
Labels: automerge

#5998 Update homepage and repository
  packages/sdk/contractkit/package.json
Labels: automerge, devX

#6266 Update plumo.md
  packages/docs/celo-codebase/protocol/plumo.md
Labels: automerge

#6240 Show more descriptive errors when gas estimation fails after QR scan
  packages/mobile/src/fees/CalculateFee.tsx
  packages/mobile/src/fees/saga.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/send/SendConfirmation.test.tsx
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/send/saga.ts
Labels: automerge, wallet

#6265 Update public key publishing instructions to point to website repo.
  developer_key_publishing.md
Labels: automerge

#6259 [Wallet] Upgrade react-native-webview to 11.0.2
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/src/account/__snapshots__/Licenses.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
  yarn-audit-known-issues
  yarn.lock
Labels: automerge, wallet

#6275 Show error modal when feeless verification flow encounters an error
  packages/mobile/src/identity/reducer.ts
Labels: automerge, wallet

#6281 Update README.md
  packages/docs/celo-codebase/protocol/identity/README.md
Labels: automerge

#6272 Fix hanging escrow reclaim loading indicator
  packages/mobile/src/escrow/ReclaimPaymentConfirmationScreen.test.tsx
  packages/mobile/src/escrow/ReclaimPaymentConfirmationScreen.tsx
  packages/mobile/src/escrow/actions.ts
  packages/mobile/src/escrow/reducer.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/navigator/types.tsx
Labels: automerge, wallet

#6286 ODIS metrics patch
  packages/phone-number-privacy/signer/azure-templates/prometheus-parameters.json
  packages/phone-number-privacy/signer/azure-templates/prometheus.yaml
  packages/phone-number-privacy/signer/src/common/metrics.ts
  packages/phone-number-privacy/signer/test/end-to-end/get-blinded-sig.test.ts
Labels: automerge

#6285 [Wallet] Remove a bunch of unused strings
  packages/mobile/fastlane/metadata/android/en-US/full_description.txt
  packages/mobile/locales/en-US/backupKeyFlow6.json
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/en-US/index.ts
  packages/mobile/locales/en-US/nuxNamePin1.json
  packages/mobile/locales/en-US/nuxRestoreWallet3.json
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/locales/es-419/backupKeyFlow6.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/es-419/index.ts
  packages/mobile/locales/es-419/nuxNamePin1.json
  packages/mobile/locales/es-419/nuxRestoreWallet3.json
  packages/mobile/locales/es-419/walletFlow5.json
  packages/mobile/src/i18n.ts
Labels: automerge, wallet

#6290 Remove the manual install of lerna from the SETUP guide
  SETUP.md
Labels: automerge

#6298 Fix chain restore wipe & enable on mainnet forno
  .env.rc1
  packages/helm-charts/celo-fullnode/templates/statefulset.yaml
  packages/helm-charts/common/templates/_helpers.tpl
Labels: automerge

#6288 [Wallet] Always prevent taking screenshots to Account Key on Android
  packages/mobile/src/backup/BackupIntroduction.tsx
  packages/mobile/src/backup/BackupPhraseContainer.tsx
  packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupPhrase.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupPhraseContainer.test.tsx.snap
  packages/mobile/src/backup/utils.ts
Labels: automerge, wallet

#6302 ODIS combiner patch
  packages/phone-number-privacy/combiner/src/signing/get-threshold-signature.ts
  packages/phone-number-privacy/combiner/test/end-to-end/get-blinded-sig.test.ts
  packages/phone-number-privacy/signer/azure-templates/README.md
  packages/phone-number-privacy/signer/azure-templates/prometheus-alfajores.yaml
  packages/phone-number-privacy/signer/azure-templates/prometheus-mainnet.yaml
  packages/phone-number-privacy/signer/azure-templates/prometheus-parameters.json
  packages/phone-number-privacy/signer/azure-templates/prometheus-staging.yaml
Labels: automerge

#6300 [Wallet] Upgrade react-native-reanimated to 2.0.0-rc.1
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  patches/react-native-reanimated+2.0.0-rc.1.patch
  yarn.lock
Labels: automerge, wallet

#6291 Use large machine on CircleCI to avoid ENOMEM error
  .circleci/config.yml
  package.json
Labels: automerge

#6280 [Wallet] Upgrade sentry/react-native to 2.1.0
  package.json
  packages/mobile/android/app/src/main/java/org/celo/mobile/MainApplication.java
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/src/sentry/Sentry.ts
  yarn.lock
Labels: automerge, wallet

#6294 Add @celo/connect as dependency of @celo/protocol
  dependency-graph.json
  packages/protocol/package.json
Labels: automerge

#6303 [Wallet] Tweak android emulator for speed
  packages/mobile/e2e/conf/avd_conf.ini
Labels: automerge

#6305 [Wallet] Try to fix flaky e2e test that reopens the app with a deep link
  packages/mobile/e2e/src/DeepLinkDappkit.spec.js
  packages/mobile/e2e/src/usecases/HandleDeepLinkDappkit.js
  packages/mobile/e2e/src/usecases/HandleDeepLinkSend.js
Labels: automerge, wallet

#6273 [Wallet] Change redux storage implementation to file system
  packages/mobile/__mocks__/redux-persist-fs-storage.ts
  packages/mobile/package.json
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/app/App.tsx
  packages/mobile/src/firebase/saga.ts
  packages/mobile/src/index.d.ts
  packages/mobile/src/redux/sagas.ts
  packages/mobile/src/redux/store.ts
  packages/mobile/src/utils/accountChecker.ts
  packages/mobile/src/web3/saga.ts
  yarn.lock
Labels: automerge, wallet

#6310 [Wallet] Bump version to 1.7.0 and update licenses
  packages/mobile/android/app/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/src/account/LicenseDisclaimer.txt
Labels: automerge, wallet

#6317 [Wallet] Fix redux store persistence
  packages/mobile/package.json
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/redux/store.ts
  yarn.lock
Labels: automerge, wallet

#6263 [Wallet] Upgrade react-native-sms-retriever to fix multiple SMS imports
  packages/mobile/package.json
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/react-components/package.json
  yarn.lock
Labels: automerge

#6279 [Wallet] Don't allow going back after wallet is imported successfully
  packages/mobile/__mocks__/src/navigator/NavigationService.ts
  packages/mobile/src/import/saga.ts
  packages/mobile/src/navigator/NavigationService.ts
  packages/mobile/src/onboarding/UseBackToWelcomeScreen.tsx
  packages/mobile/src/pincode/PincodeSet.test.tsx
  packages/mobile/src/pincode/PincodeSet.tsx
Labels: automerge, wallet

#6325 [Wallet] Fix last alert banner redisplayed on re-render
  packages/mobile/jest_setup.ts
  packages/mobile/src/account/__snapshots__/FiatExchange.test.tsx.snap
  packages/mobile/src/account/__snapshots__/GoldEducation.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Settings.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Support.test.tsx.snap
  packages/mobile/src/alert/AlertBanner.tsx
  packages/mobile/src/alert/__snapshots__/AlertBanner.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeHomeScreen.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/WithdrawCeloScreen.test.tsx.snap
  packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
  packages/mobile/src/verify/VerificationLoadingScreen.test.tsx
  packages/mobile/src/verify/__snapshots__/VerificationLoadingScreen.test.tsx.snap
  packages/react-components/components/SmartTopAlert.test.tsx
  packages/react-components/components/SmartTopAlert.tsx
  packages/react-components/components/__snapshots__/CircleButton.test.tsx.snap
  packages/react-components/components/__snapshots__/ReviewFrame.test.tsx.snap
  packages/react-components/components/__snapshots__/SmartTopAlert.test.tsx.snap
  packages/react-components/components/__snapshots__/TextInputWithButtons.test.tsx.snap
  packages/react-components/jest_setup.js
Labels: automerge

#6321 Add or@clabs.co to celo-blockchain dev key list, and sort list alphabetically
  packages/docs/community/release-process/blockchain-client.md
Labels: automerge

#6324 [Wallet] Bump version to 1.7.1 and update licenses
  packages/mobile/android/app/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/src/account/LicenseDisclaimer.txt
Labels: automerge, wallet

#6347 Show phone number on SendConfirmation Screen when contact display name is not available
  packages/mobile/src/recipients/recipient.ts
Labels: automerge, wallet

#4757 [DOCS] - Add Cauldron to Validator Group third-party tooling list
  packages/docs/celo-holder-guide/voting-validators.md
Labels: automerge, docs
