Repository celo-org/celo-monorepo, pull requests merged in 2020-05, with the labels that each got.

#3694 Security Audits Page
  packages/web/pages/audits.tsx
  packages/web/public/static/locales/en/audits.json
  packages/web/src/_page-tests/__snapshots__/audits.test.tsx.snap
  packages/web/src/_page-tests/audits.test.tsx
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/i18n.ts
  packages/web/src/shared/Footer.tsx
  packages/web/src/shared/__snapshots__/Footer.test.tsx.snap
  packages/web/src/shared/menu-items.ts
  packages/web/src/terms/Audits.tsx
  packages/web/src/utils/i18nForTests.ts
Labels: automerge

#3695 [docs] Gold Holder quick guide additions
  packages/docs/celo-gold-holder-guide/quick-start.md
Labels: automerge

#3699 Fix failing wallet e2e test and put PGPNP behind a feature flag
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/src/config.ts
  packages/mobile/src/identity/privacy.test.ts
  packages/mobile/src/identity/verification.ts
  packages/protocol/test/identity/attestations.ts
  packages/utils/src/phoneNumbers.test.ts
  packages/utils/src/phoneNumbers.ts
Labels: automerge

#3303 Create develop-on-windows.md
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/develop-on-windows.md
Labels: automerge

#3211 blockscout ingress block /admin
  packages/helm-charts/blockscout/templates/blockscout-web.ingress.yaml
Labels: automerge

#3702 Fix some tip containers in gold holders Quick Start guide
  packages/docs/celo-gold-holder-guide/quick-start.md
Labels: automerge

#3538 Add celo protocol tx URI scheme and qr codes to contractkit
  packages/contractkit/package.json
  packages/contractkit/src/utils/tx-uri.test.ts
  packages/contractkit/src/utils/tx-uri.ts
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/globals.md
  packages/docs/developer-resources/contractkit/reference/modules/_utils_tx_uri_.md
  yarn.lock
Labels: automerge

#3543 New env variables for transaction metric exporter
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/transaction-metrics-exporter.ts
  packages/helm-charts/transaction-metrics-exporter/templates/deployment.yaml
Labels: automerge

#3717 [Wallet] Disable manual setting of nonce in transactions
  packages/mobile/src/transactions/contract-utils.ts
  packages/mobile/src/transactions/saga.ts
  packages/mobile/src/transactions/send.ts
Labels: automerge

#3720 Bump version numbers for CLI deploy
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/leaderboard/package.json
  packages/metadata-crawler/package.json
  packages/mobile/package.json
  packages/protocol/package.json
  packages/react-components/package.json
  packages/transaction-metrics-exporter/package.json
  packages/utils/package.json
  packages/verifier/package.json
Labels: automerge

#3719 Update instructions for key rotation and add info about Governance
  packages/docs/celo-codebase/protocol/governance.md
  packages/docs/operations-manual/key-management/key-rotation.md
Labels: automerge

#3689 Move libusb dependency to dev env
  dockerfiles/attestation-service/Dockerfile
  dockerfiles/celotool/Dockerfile
  dockerfiles/leaderboard/Dockerfile
  packages/contractkit/DEVELOP.md
  packages/contractkit/package.json
Labels: automerge

#3725 Update contractkit ver to 4.5
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/leaderboard/package.json
  packages/metadata-crawler/package.json
  packages/mobile/package.json
Labels: automerge

#3672 Move vscode launch files to monorepo root
  .vscode/launch.json
  packages/contractkit/.vscode/launch.json
  packages/contractkit/package.json
  yarn.lock
Labels: automerge

#3691 [ReDesign] colors, fonts, Buttons
  packages/mobile/android/app/src/main/assets/fonts/Inter-Medium.ttf
  packages/mobile/android/app/src/main/assets/fonts/Inter-Regular.ttf
  packages/mobile/android/app/src/main/assets/fonts/Inter-SemiBold.ttf
  packages/mobile/fonts/Inter-Medium.ttf
  packages/mobile/fonts/Inter-Regular.ttf
  packages/mobile/fonts/Inter-SemiBold.ttf
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/ios/celo/Info.plist
  packages/react-components/components/Button.v2.test.tsx
  packages/react-components/components/Button.v2.tsx
  packages/react-components/components/__snapshots__/Button.v2.test.tsx.snap
  packages/react-components/styles/colors.v2.tsx
  packages/react-components/styles/fonts.v2.tsx
Labels: automerge

#3593 Add autocomplete and update warning plugins to celocli
  packages/cli/package.json
  packages/docs/command-line-interface/autocomplete.md
  packages/docs/command-line-interface/introduction.md
  yarn.lock
Labels: automerge

#3715 Oracle prometheus metrics, HSM wallet init retries, update aad-pod-identity
  packages/celotool/src/lib/oracle.ts
  packages/helm-charts/aad-pod-identity/templates/mic-deployment.yaml
  packages/helm-charts/aad-pod-identity/values.yaml
  packages/helm-charts/oracle/templates/_helper.tpl
  packages/helm-charts/oracle/templates/azure-identity-binding.yaml
  packages/helm-charts/oracle/templates/azure-identity.yaml
  packages/helm-charts/oracle/templates/statefulset.yaml
  packages/helm-charts/oracle/values.yaml
Labels: automerge

#3730 note on website that validator elections are started
  packages/web/src/_page-tests/__snapshots__/index.test.tsx.snap
  packages/web/src/home/roadmap/milestones.ts
Labels: automerge

#3735 [NotificationService] Fix notifications
  packages/mobile/src/firebase/firebase.ts
  packages/notification-service/src/blockscout/blockscout.d.ts
  packages/notification-service/src/blockscout/decode.ts
  packages/notification-service/src/blockscout/transfers.ts
  packages/notification-service/src/util/utils.ts
  packages/notification-service/test/decode.test.ts
  packages/notification-service/test/transfers.test.ts
Labels: automerge

#3700 [Wallet] Wait for rehydrate to fix DataSaver restart issue
  packages/mobile/__mocks__/src/web3/contracts.ts
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/locales/es-419/accountScreen10.json
  packages/mobile/src/account/DataSaver.tsx
  packages/mobile/src/account/__snapshots__/Account.test.tsx.snap
  packages/mobile/src/account/__snapshots__/DataSaver.test.tsx.snap
  packages/mobile/src/app/saga.ts
  packages/mobile/src/dappkit/dappkit.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/exchange/ExchangeReview.tsx
  packages/mobile/src/exchange/saga.ts
  packages/mobile/src/fees/saga.ts
  packages/mobile/src/flags.ts
  packages/mobile/src/geth/saga.ts
  packages/mobile/src/identity/commentKey.test.ts
  packages/mobile/src/identity/commentKey.ts
  packages/mobile/src/identity/contactMapping.test.ts
  packages/mobile/src/identity/contactMapping.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/import/saga.ts
  packages/mobile/src/invite/saga.test.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/pincode/utils.ts
  packages/mobile/src/redux/selectors.ts
  packages/mobile/src/tokens/saga.ts
  packages/mobile/src/transactions/actions.ts
  packages/mobile/src/web3/actions.ts
  packages/mobile/src/web3/contracts.ts
  packages/mobile/src/web3/gas.ts
  packages/mobile/src/web3/reducer.ts
  packages/mobile/src/web3/saga.test.ts
  packages/mobile/src/web3/saga.ts
  packages/mobile/src/web3/selectors.ts
  packages/mobile/src/web3/utils.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#3721 [docs] Voting guide
  packages/docs/SUMMARY.md
  packages/docs/celo-codebase/protocol/proof-of-stake/validator-groups.md
  packages/docs/celo-gold-holder-guide/ledger.md
  packages/docs/celo-gold-holder-guide/quick-start.md
  packages/docs/celo-gold-holder-guide/voting-validators.md
  packages/docs/command-line-interface/introduction.md
  packages/docs/operations-manual/key-management/detailed.md
Labels: automerge, docs

#3482 [web] Upgrade next.js
  packages/web/package.json
  yarn.lock
Labels: automerge

#3750 [Bug Fix] Explicitly adding the context for the lookupIdentifiers method in contactMapping.ts
  packages/mobile/src/identity/contactMapping.ts
Labels: automerge, wallet

#3754 Remove default margin from ButtonV2
  packages/react-components/components/Button.v2.tsx
  packages/react-components/components/__snapshots__/Button.v2.test.tsx.snap
Labels: automerge

#3758 Adding fullnode statefulset
  packages/helm-charts/celo-fullnode/templates/statefulset.yaml
Labels: automerge

#3756 Remove enzyme as a testing library
  packages/mobile/README.md
  packages/mobile/e2e/Transfer.spec.js
  packages/mobile/jest_setup.ts
  packages/mobile/package.json
  packages/mobile/src/app/App.test.tsx
  packages/mobile/src/registration/__snapshots__/JoinCelo.test.tsx.snap
  packages/react-components/components/BaseNotification.test.tsx
  packages/react-components/components/Button.test.tsx
  packages/react-components/components/CircleButton.test.tsx
  packages/react-components/components/ContactCircle.test.tsx
  packages/react-components/components/FullscreenCTA.test.tsx
  packages/react-components/components/PhoneNumberInput.test.tsx
  packages/react-components/components/PhoneNumberInput.tsx
  packages/react-components/components/ReviewFrame.test.tsx
  packages/react-components/components/ReviewHeader.test.tsx
  packages/react-components/components/SettingsItem.test.tsx
  packages/react-components/components/SmallButton.test.tsx
  packages/react-components/components/SummaryNotification.test.tsx
  packages/react-components/components/__snapshots__/Button.test.tsx.snap
  packages/react-components/components/__snapshots__/PhoneNumberInput.test.tsx.snap
  packages/react-components/jest_setup.js
  packages/react-components/package.json
  yarn.lock
Labels: automerge

#3753 [phone-number-privacy][attestation] update attestation service to store hashed identifiers and dynamically purge expired records
  packages/attestation-service/migrations/20200506234935-attestation-v2.js
  packages/attestation-service/src/db.ts
  packages/attestation-service/src/models/attestation.ts
  packages/attestation-service/src/requestHandlers/attestation.ts
Labels: automerge

#3612 Include invite code in SMS when user reminds invitee of escrowed funds
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/locales/es-419/walletFlow5.json
  packages/mobile/src/account/__snapshots__/Invite.test.tsx.snap
  packages/mobile/src/escrow/EscrowedPaymentListItem.test.tsx
  packages/mobile/src/escrow/EscrowedPaymentListItem.tsx
  packages/mobile/src/escrow/EscrowedPaymentListScreen.tsx
  packages/mobile/src/escrow/EscrowedPaymentReminderSummaryNotification.test.tsx
  packages/mobile/src/escrow/EscrowedPaymentReminderSummaryNotification.tsx
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentListItem.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentReminderSummaryNotification.test.tsx.snap
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/home/__snapshots__/NotificationBox.test.tsx.snap
  packages/mobile/src/invite/actions.ts
  packages/mobile/src/invite/reducer.ts
  packages/mobile/src/invite/saga.test.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/notifications/__snapshots__/SimpleNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestSummaryNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestSummaryNotification.test.tsx.snap
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/store.ts
  packages/mobile/src/send/saga.test.ts
  packages/mobile/src/send/saga.ts
  packages/mobile/src/transactions/TransactionFeed.tsx
  packages/mobile/src/transactions/TransferFeedItem.test.tsx
  packages/mobile/src/transactions/TransferFeedItem.tsx
  packages/mobile/src/transactions/transferFeedUtils.ts
  packages/mobile/test/schemas.ts
  packages/mobile/test/values.ts
  packages/react-components/components/BaseNotification.tsx
  packages/react-components/components/__snapshots__/BaseNotification.test.tsx.snap
Labels: automerge, wallet

#3769 [Docs] Update Truffle Box title to be more Dapp focused.
  .gitbook.yaml
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/start.md
  packages/docs/developer-resources/walkthroughs/hello-mobile-dapp.md
Labels: automerge, docs

#3766 updates to font sizes from cory
  packages/react-components/components/__snapshots__/Button.v2.test.tsx.snap
  packages/react-components/styles/fonts.v2.tsx
Labels: automerge

#3748 Audits Page 1.1
  packages/web/public/static/locales/en/audits.json
  packages/web/src/_page-tests/__snapshots__/audits.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/papers.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/terms.test.tsx.snap
  packages/web/src/terms/Audits.tsx
  packages/web/src/terms/HelpfullLink.tsx
  packages/web/src/terms/Papers.tsx
  packages/web/src/terms/TermsPortal.tsx
Labels: automerge

#3776 [Wallet] Fix bg and header border in RN navigation
  packages/mobile/src/navigator/Navigator.tsx
Labels: automerge

#3771 Unsubscribe to further transactions confirmations after the first
  packages/mobile/src/transactions/contract-utils.ts
  packages/mobile/src/transactions/send.ts
Labels: automerge

#3772 [refresh] Components for wallet
  packages/mobile/src/components/CancelButton.v2.test.tsx
  packages/mobile/src/components/CancelButton.v2.tsx
  packages/mobile/src/navigator/TopBarButton.v2.test.tsx
  packages/mobile/src/navigator/TopBarButton.v2.tsx
  packages/react-components/components/BorderlessButton.v2.tsx
  packages/react-components/components/TextButton.v2.tsx
  packages/react-components/styles/styles.v2.ts
Labels: automerge

#3770 [docs] Fix to quick start guide command. Typos. Nano X lockup warning.
  packages/docs/celo-gold-holder-guide/ledger.md
  packages/docs/celo-gold-holder-guide/quick-start.md
Labels: automerge

#3783 [Wallet] Put contact lookups behind the PGPNP feature flag
  packages/mobile/src/identity/contactMapping.test.ts
  packages/mobile/src/identity/contactMapping.ts
Labels: automerge

#3789 [Wallet] Fix APK build after RN 0.62 upgrade
  packages/mobile/README.md
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/react.gradle
  packages/mobile/fastlane/Fastfile
Labels: automerge

#3761 (WIP) build: better selection of tests run in CI
  .circleci/config.yml
  dependency-graph.json
  packages/celotool/package.json
  packages/celotool/src/cmds/account/faucet.ts
  packages/celotool/src/cmds/account/invite.ts
  packages/celotool/src/cmds/account/revoke.ts
  packages/celotool/src/cmds/account/weekly_faucet.ts
  packages/celotool/src/cmds/backup.ts
  packages/celotool/src/cmds/deploy/destroy/blockscout.ts
  packages/celotool/src/cmds/deploy/initial/blockchain-api.ts
  packages/celotool/src/cmds/deploy/initial/contracts.ts
  packages/celotool/src/cmds/deploy/initial/notification-service.ts
  packages/celotool/src/cmds/deploy/initial/tracer-tool.ts
  packages/celotool/src/cmds/deploy/initial/verify-contracts.ts
  packages/celotool/src/cmds/deploy/upgrade/blockscout.ts
  packages/celotool/src/cmds/deploy/upgrade/contracts.ts
  packages/celotool/src/cmds/deploy/upgrade/faucet.ts
  packages/celotool/src/cmds/gcp/remove-leaked-forwarding-rules.ts
  packages/celotool/src/cmds/geth/build.ts
  packages/celotool/src/cmds/geth/create_account.ts
  packages/celotool/src/cmds/geth/get_gold_balance.ts
  packages/celotool/src/cmds/geth/init.ts
  packages/celotool/src/cmds/links.ts
  packages/celotool/src/cmds/restore.ts
  packages/celotool/src/cmds/vm-exec.ts
  packages/celotool/src/e2e-tests/utils.ts
  packages/celotool/src/lib/aks-fullnode.ts
  packages/celotool/src/lib/aks-prometheus.ts
  packages/celotool/src/lib/artifacts.ts
  packages/celotool/src/lib/attestation-bot.ts
  packages/celotool/src/lib/attestation-service.ts
  packages/celotool/src/lib/azure.ts
  packages/celotool/src/lib/blockscout.ts
  packages/celotool/src/lib/celostats.ts
  packages/celotool/src/lib/cluster.ts
  packages/celotool/src/lib/cmd-utils.ts
  packages/celotool/src/lib/gcloud_utils.ts
  packages/celotool/src/lib/geth.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/celotool/src/lib/kubernetes.ts
  packages/celotool/src/lib/leaderboard.ts
  packages/celotool/src/lib/oracle.ts
  packages/celotool/src/lib/policies.ts
  packages/celotool/src/lib/port_forward.ts
  packages/celotool/src/lib/prom-to-sd-utils.ts
  packages/celotool/src/lib/service-account-utils.ts
  packages/celotool/src/lib/terraform.ts
  packages/celotool/src/lib/testnet-utils.ts
  packages/celotool/src/lib/tracer-tool.ts
  packages/celotool/src/lib/transaction-metrics-exporter.ts
  packages/celotool/src/lib/utils.ts
  packages/celotool/src/lib/vm-testnet-utils.ts
  scripts/check_dependency_graph_changed.ts
  scripts/check_if_test_should_run_v2.ts
  scripts/ci_check_dependency_graph_changed.sh
  scripts/ci_check_if_test_should_run_v2.sh
  scripts/dependency-graph-utils.ts
  scripts/update-dependency-graph.ts
Labels: automerge

#3790 Catch fetch error
  packages/cli/src/commands/identity/current-attestation-services.ts
Labels: automerge

#3780 Make DowntimeSlasher easier to use from contractkit
  packages/contractkit/src/wrappers/DowntimeSlasher.ts
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_downtimeslasher_.downtimeslasherwrapper.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_downtimeslasher_.downtimeslasherconfig.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_downtimeslasher_.downtimewindow.md
  packages/docs/developer-resources/contractkit/reference/modules/_wrappers_downtimeslasher_.md
Labels: automerge

#3768 PGPNP: Server-side && Client-side authentication check
  .env
  .vscode/launch.json
  packages/mobile/README.md
  packages/mobile/__mocks__/web3.js
  packages/mobile/src/config.ts
  packages/mobile/src/identity/privacy.ts
  packages/phone-number-privacy/package.json
  packages/phone-number-privacy/src/common/constants.ts
  packages/phone-number-privacy/src/common/error-utils.ts
  packages/phone-number-privacy/src/common/identity.ts
  packages/phone-number-privacy/src/common/input-validation.ts
  packages/phone-number-privacy/src/index.ts
  packages/phone-number-privacy/src/match-making/get-contact-matches.ts
  packages/phone-number-privacy/src/salt-generation/get-salt.ts
  packages/phone-number-privacy/test/end-to-end/get-blinded-salt.test.ts
  packages/phone-number-privacy/test/utils.ts
  yarn.lock
Labels: automerge

#3793 [Wallet] Fix navigation title alignment after RN navigation update
  packages/mobile/src/navigator/Headers.tsx
  packages/react-components/styles/styles.ts
Labels: automerge

#3787 changes to the /validators page
  packages/web/public/static/locales/en/dev.json
  packages/web/src/_page-tests/validators/__snapshots__/index.test.tsx.snap
  packages/web/src/dev/Cover.tsx
  packages/web/src/dev/Engage.tsx
Labels: automerge, web

#3349 Governance CLI changes
  packages/cli/src/commands/governance/dequeue.ts
  packages/cli/src/commands/governance/show.ts
  packages/cli/src/commands/governance/vote.test.ts
  packages/cli/src/commands/governance/withdraw.test.ts
  packages/cli/src/commands/governance/withdraw.ts
  packages/cli/src/utils/checks.ts
  packages/contractkit/src/wrappers/Governance.test.ts
  packages/contractkit/src/wrappers/Governance.ts
  packages/docs/SUMMARY.md
  packages/docs/command-line-interface/governance.md
  packages/docs/developer-resources/contractkit/reference/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_governance_.governancewrapper.md
  packages/docs/developer-resources/contractkit/reference/enums/_wrappers_governance_.proposalstage.md
  packages/docs/developer-resources/contractkit/reference/enums/_wrappers_governance_.votevalue.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_governance_.governanceconfig.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_governance_.hotfixrecord.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_governance_.participationparameters.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_governance_.proposalmetadata.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_governance_.proposalrecord.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_governance_.proposalstagedurations.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_governance_.upvoterecord.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_governance_.voter.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_governance_.voterecord.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_governance_.votes.md
  packages/docs/developer-resources/contractkit/reference/modules/_wrappers_governance_.md
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/test/governance/governance.ts
Labels: automerge

#3802 Filter kube label metrics for AKS prometheus
  packages/celotool/src/lib/aks-prometheus.ts
  packages/helm-charts/prometheus-stackdriver/templates/deployment.yaml
Labels: automerge

#3797 Remove Coinlist form Celo.org
  packages/web/src/_page-tests/index.test.tsx
  packages/web/src/home/Home.test.tsx
  packages/web/src/home/Home.tsx
Labels: automerge

#3801 Fix download button position on Exchange icons page
  packages/web/src/_page-tests/experience/__snapshots__/exchange-icons.test.tsx.snap
  packages/web/src/brandkit/IconsExchangePage.tsx
Labels: automerge

#3782 Amyslawson/pnp concurrency db
  packages/phone-number-privacy/src/common/error-utils.ts
  packages/phone-number-privacy/src/common/identity.ts
  packages/phone-number-privacy/src/common/input-validation.ts
  packages/phone-number-privacy/src/database/database.ts
  packages/phone-number-privacy/src/database/wrappers/account.ts
  packages/phone-number-privacy/src/salt-generation/get-salt.ts
  packages/phone-number-privacy/src/salt-generation/query-quota.ts
  packages/phone-number-privacy/test/index.test.ts
  packages/phone-number-privacy/test/salt-generation/query-quota.test.ts
Labels: automerge

#3811 [Wallet] Update Moonpay currency code with CUSD
  packages/mobile/src/account/FiatExchange.tsx
Labels: automerge

#3774 fix rare bug in Azure HSM Wallet implementation. issue: #3498
  packages/contractkit/src/utils/azure-key-vault-client.ts
  packages/docs/developer-resources/contractkit/reference/classes/_utils_azure_key_vault_client_.signature.md
Labels: automerge

#3814 Enable CORS on forno ingress
  packages/helm-charts/testnet/templates/forno.ingress.yaml
Labels: automerge

#3798 Added field timestamp to the testnet config
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/generate_utils.ts
  packages/celotool/src/lib/interfaces/genesis-config.ts
Labels: automerge

#3805 Adds per module geth verbosity to env deploys
  .env
  packages/celotool/src/lib/helm_deploy.ts
  packages/helm-charts/common/templates/_helpers.tpl
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
Labels: automerge

#3809 Fetch Milestones from Airtable
  packages/web/pages/api/milestones.ts
  packages/web/public/static/locales/en/home.json
  packages/web/server/fetchMilestones.ts
  packages/web/src/_page-tests/index.test.tsx
  packages/web/src/home/Home.tsx
  packages/web/src/home/roadmap/Timeline.tsx
  packages/web/src/home/roadmap/milestones.ts
Labels: automerge

#3813 Update dappkit CODEOWNERS
  .github/CODEOWNERS
Labels: automerge

#3815 [Wallet][ReDesign] Transaction feed and Send/Request bottom bar
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/locales/es-419/walletFlow5.json
  packages/mobile/src/home/SendOrRequestBar.tsx
  packages/mobile/src/home/WalletHome.tsx
  packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
  packages/mobile/src/transactions/ExchangeFeedItem.tsx
  packages/mobile/src/transactions/TransactionFeed.tsx
  packages/mobile/src/transactions/TransactionFeedItem.tsx
  packages/mobile/src/transactions/TransferFeedItem.tsx
  packages/mobile/src/transactions/__snapshots__/ExchangeFeedItem.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransactionFeed.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransactionsList.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransferFeedItem.test.tsx.snap
  packages/mobile/src/transactions/transferFeedUtils.ts
  packages/react-components/components/SectionHeadNew.test.tsx
  packages/react-components/components/SectionHeadNew.tsx
  packages/react-components/components/__snapshots__/SectionHeadNew.test.tsx.snap
  packages/react-components/icons/QRCodeBorderless.tsx
Labels: automerge

#3823 Move domain claim to supported
  packages/docs/celo-codebase/protocol/identity/metadata.md
Labels: automerge

#3818 Add Celo Foundation to the About Page
  packages/web/public/static/locales/en/about.json
  packages/web/src/_page-tests/__snapshots__/about.test.tsx.snap
  packages/web/src/about/About.tsx
Labels: automerge

#3795 redesign account key (Part 1 - Core Flow)
  packages/mobile/locales/en-US/backupKeyFlow6.json
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-419/backupKeyFlow6.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/src/account/Account.tsx
  packages/mobile/src/backup/BackupComplete.tsx
  packages/mobile/src/backup/BackupIntroduction.test.tsx
  packages/mobile/src/backup/BackupIntroduction.tsx
  packages/mobile/src/backup/BackupPhrase.tsx
  packages/mobile/src/backup/BackupPhraseContainer.tsx
  packages/mobile/src/backup/BackupQuiz.tsx
  packages/mobile/src/backup/DelayButton.test.tsx
  packages/mobile/src/backup/DelayButton.tsx
  packages/mobile/src/backup/QuizzBottom.tsx
  packages/mobile/src/backup/__snapshots__/BackupComplete.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupPhrase.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupPhraseContainer.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupQuiz.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupSocial.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/DelayButton.test.tsx.snap
  packages/mobile/src/backup/utils.ts
  packages/mobile/src/components/CancelButton.v2.tsx
  packages/mobile/src/icons/Logo.v2.tsx
  packages/mobile/src/import/__snapshots__/ImportWallet.test.tsx.snap
  packages/mobile/src/import/__snapshots__/ImportWalletSocial.test.tsx.snap
  packages/react-components/components/Switch.v2.tsx
  packages/react-components/styles/styles.v2.ts
Labels: automerge

#3355 [ContractKit] CeloProvider delegates subscriptions
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/contractkit/src/providers/celo-provider.ts
  packages/docs/developer-resources/contractkit/reference/classes/_providers_celo_provider_.celoprovider.md
Labels: automerge

#3820 Reintroducing Ripple Buttons on Android
  packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupPhrase.test.tsx.snap
  packages/mobile/src/components/CancelButton.v2.tsx
  packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
  packages/react-components/components/Button.v2.tsx
  packages/react-components/components/__snapshots__/Button.v2.test.tsx.snap
  packages/react-components/styles/colors.v2.tsx
Labels: automerge

#3546 [Wallet] Adding recent payments to the state so we can check for 24 hour limit
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/src/alert/actions.ts
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/config.ts
  packages/mobile/src/send/SendAmount.test.tsx
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/actions.ts
  packages/mobile/src/send/reducers.ts
  packages/mobile/src/send/selectors.ts
  packages/mobile/src/send/utils.test.ts
  packages/mobile/src/send/utils.ts
  packages/mobile/src/utils/time.ts
  packages/mobile/test/schemas.ts
Labels: automerge, wallet

#3828 Update Validators Image + org name change
  packages/web/README.md
  packages/web/pages/validators/index.tsx
  packages/web/public/static/locales/en/community.json
  packages/web/public/static/locales/en/jobs.json
  packages/web/src/_page-tests/__snapshots__/jobs.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/privacy.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/user-agreement.test.tsx.snap
  packages/web/src/_page-tests/validators/index.test.tsx
  packages/web/src/community/PastEventsPage.tsx
  packages/web/src/dev/ValidatorPage.tsx
  packages/web/src/dev/opengraph.jpg
  packages/web/src/join/ImagePanes.tsx
  packages/web/src/privacy/Privacy.tsx
  packages/web/src/terms/Agreement.tsx
Labels: automerge

#3827 Ledger instructions updated for 1.0.3. Single Ledger in quick start.
  packages/docs/celo-gold-holder-guide/ledger.md
  packages/docs/celo-gold-holder-guide/quick-start.md
Labels: automerge

#3778 [docs] Monitoring docs
  packages/attestation-service/src/metrics.ts
  packages/docs/SUMMARY.md
  packages/docs/operations-manual/monitoring.md
Labels: automerge, docs

#3831 [docs] Add link to RG deployment mapping for wave 2
  packages/docs/celo-gold-holder-guide/quick-start.md
Labels: automerge

#3837 Fix Headers
  packages/mobile/src/backup/BackupIntroduction.tsx
  packages/mobile/src/backup/BackupPhrase.tsx
  packages/mobile/src/backup/BackupQuiz.tsx
  packages/mobile/src/navigator/Headers.v2.tsx
  packages/mobile/src/navigator/Navigator.tsx
Labels: automerge

#3836 Mainnet Graduation Time 🎓
  packages/web/public/static/locales/en/dev.json
  packages/web/src/_page-tests/validators/__snapshots__/index.test.tsx.snap
  packages/web/src/dev/ValidatorsListApp.tsx
Labels: automerge

#3839 [docs] Change "Release Candidate 1" references to Mainnet
  .gitbook.yaml
  packages/docs/GLOSSARY.md
  packages/docs/SUMMARY.md
  packages/docs/celo-codebase/protocol/proof-of-stake/validator-groups.md
  packages/docs/celo-gold-holder-guide/quick-start.md
  packages/docs/celo-gold-holder-guide/voting-governance.md
  packages/docs/celo-gold-holder-guide/voting-validators.md
  packages/docs/command-line-interface/introduction.md
  packages/docs/developer-resources/contractkit/setup.md
  packages/docs/developer-resources/forno/README.md
  packages/docs/getting-started/alfajores-testnet.md
  packages/docs/getting-started/choosing-a-network.md
  packages/docs/getting-started/mainnet.md
  packages/docs/getting-started/rc1.md
  packages/docs/getting-started/running-a-full-node-in-mainnet.md
  packages/docs/getting-started/running-a-validator-in-baklava.md
  packages/docs/getting-started/running-a-validator-in-mainnet.md
  packages/docs/important-information/mainnet-network-disclaimer.md
  packages/docs/operations-manual/key-management/key-rotation.md
  packages/docs/operations-manual/monitoring.md
  packages/docs/operations-manual/node-upgrades.md
Labels: automerge

#3764 [Wallet] Gold screen redesign
  packages/mobile/locales/en-US/exchangeFlow9.json
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/locales/es-419/exchangeFlow9.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/es-419/walletFlow5.json
  packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupPhrase.test.tsx.snap
  packages/mobile/src/components/LineItemRow.v2.tsx
  packages/mobile/src/components/TotalLineItem.v2.tsx
  packages/mobile/src/exchange/CeloGoldHistoryChart.tsx
  packages/mobile/src/exchange/CeloGoldOverview.tsx
  packages/mobile/src/exchange/ExchangeConfirmationCard.test.tsx
  packages/mobile/src/exchange/ExchangeConfirmationCard.tsx
  packages/mobile/src/exchange/ExchangeHomeScreen.tsx
  packages/mobile/src/exchange/ExchangeReview.tsx
  packages/mobile/src/exchange/ExchangeTradeScreen.tsx
  packages/mobile/src/exchange/__snapshots__/CeloGoldHistoryChart.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/CeloGoldOverview.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeConfirmationCard.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeReview.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap
  packages/mobile/src/navigator/Headers.tsx
  packages/mobile/src/navigator/Headers.v2.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/transactions/GoldTransactionFeedItem.test.tsx
  packages/mobile/src/transactions/GoldTransactionFeedItem.tsx
  packages/mobile/src/transactions/TransactionFeed.tsx
  packages/mobile/src/transactions/TransactionReview.tsx
  packages/mobile/src/transactions/__snapshots__/GoldTransactionFeedItem.test.tsx.snap
  packages/mobile/src/transactions/actions.ts
  packages/mobile/src/utils/time.ts
  packages/react-components/components/Button.v2.tsx
  packages/react-components/components/ItemSeparator.tsx
  packages/react-components/components/SectionHeadGold.test.tsx
  packages/react-components/components/SectionHeadGold.tsx
  packages/react-components/components/__snapshots__/Button.v2.test.tsx.snap
  packages/react-components/components/__snapshots__/ItemSeparator.test.tsx.snap
  packages/react-components/components/__snapshots__/SectionHeadGold.test.tsx.snap
  packages/react-components/styles/fonts.v2.tsx
Labels: automerge

#3821 Oracle upgrade and readiness probe
  packages/celotool/src/cmds/deploy/upgrade/oracle.ts
  packages/celotool/src/lib/oracle.ts
  packages/helm-charts/oracle/templates/statefulset.yaml
Labels: automerge

#3777 Enable PGPNP and increment wallet version
  .env.alfajores
  .env.alfajoresstaging
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/assets/custom/LicenseDisclaimer.txt
  packages/mobile/android/gradle.properties
  packages/mobile/fastlane/Fastfile
  packages/mobile/ios/celo-tvOS/Info.plist
  packages/mobile/ios/celo-tvOSTests/Info.plist
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/ios/celo/Info.plist
  packages/mobile/ios/celoTests/Info.plist
  packages/mobile/locales/en-US/nuxVerification2.json
  packages/mobile/locales/es-419/nuxVerification2.json
  packages/mobile/package.json
  packages/mobile/src/analytics/constants.ts
  packages/mobile/src/config.ts
  packages/mobile/src/geth/networkConfig.ts
  packages/mobile/src/identity/PhoneNumberLookupQuotaScreen.test.tsx
  packages/mobile/src/identity/PhoneNumberLookupQuotaScreen.tsx
  packages/mobile/src/identity/__snapshots__/PhoneNumberLookupQuotaScreen.test.tsx.snap
  packages/mobile/src/identity/commentKey.ts
  packages/mobile/src/identity/contactMapping.test.ts
  packages/mobile/src/identity/contactMapping.ts
  packages/mobile/src/identity/privacy.test.ts
  packages/mobile/src/identity/privacy.ts
  packages/mobile/src/navigator/Headers.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/pincode/PincodeEnter.tsx
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/sagas.ts
  packages/mobile/src/redux/store.ts
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/transactions/actions.ts
  packages/mobile/src/transactions/saga.ts
  packages/mobile/src/verify/VerificationInputScreen.tsx
  packages/mobile/src/verify/VerificationInterstitialScreen.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
  packages/phone-number-privacy/package.json
  packages/phone-number-privacy/scripts/createBlsKeyPair.ts
  packages/phone-number-privacy/src/salt-generation/query-quota.ts
  packages/phone-number-privacy/test/salt-generation/query-quota.test.ts
  packages/protocol/test/governance/epochrewards.ts
  packages/utils/src/phoneNumbers.test.ts
  packages/utils/src/phoneNumbers.ts
Labels: automerge

#3854 Audits, Velocity, Copyright
  packages/web/public/papers/cLabs_CBDC_Velocity_v2_04-2020.pdf
  packages/web/public/papers/cLabs_CBDC_Velocity_v3.pdf
  packages/web/public/static/locales/en/common.json
  packages/web/server/index.ts
  packages/web/src/_page-tests/__snapshots__/audits.test.tsx.snap
  packages/web/src/shared/__snapshots__/Footer.test.tsx.snap
  packages/web/src/terms/Audits.tsx
Labels: automerge

#3800 Validator Explorer feedback and improvements
  packages/web/src/_page-tests/validators/__snapshots__/explore.test.tsx.snap
  packages/web/src/dev/ValidatorsList.tsx
  packages/web/src/dev/ValidatorsListRow.tsx
  packages/web/src/dev/ValidatorsListStyles.tsx
  packages/web/src/utils/utils.ts
Labels: automerge

#3842 A New Story
  packages/web/package.json
  packages/web/public/static/locales/en/home.json
  packages/web/src/_page-tests/__snapshots__/index.test.tsx.snap
  packages/web/src/animate/LottieBase.tsx
  packages/web/src/community/connect/CeloRoles.tsx
  packages/web/src/forms/EmailForm.tsx
  packages/web/src/header/Header.3.tsx
  packages/web/src/home/Home.tsx
  packages/web/src/home/HomeBackers.tsx
  packages/web/src/home/TextAnimation.tsx
  packages/web/src/home/change-story/ChangeStory.tsx
  packages/web/src/home/change-story/animation.json
  packages/web/src/home/version3/HomeCover.tsx
  packages/web/src/home/version3/HomeHero.tsx
  packages/web/src/interfaces.d.ts
  packages/web/src/shared/Spinner.tsx
  yarn.lock
Labels: automerge

#3829 [contractKit][mobile] add percent of attestations completed as part of heuristic for phone number validation (will also be used in PGPNP)
  packages/contractkit/src/wrappers/Attestations.test.ts
  packages/contractkit/src/wrappers/Attestations.ts
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_attestations_.attestationswrapper.md
  packages/docs/developer-resources/contractkit/reference/enums/_wrappers_attestations_.attestationstate.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.actionableattestation.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.attestationsconfig.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.attestationsstatus.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.attestationstat.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.attestationstateforissuer.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.attestationstoken.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.unselectedrequest.md
  packages/docs/developer-resources/contractkit/reference/modules/_wrappers_attestations_.md
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/phone-number-privacy/src/salt-generation/get-salt.ts
Labels: automerge

#3791 [Wallet] Secure Send
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/es-419/sendFlow7.json
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/components/SingleDigitInput.tsx
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/contactMapping.test.ts
  packages/mobile/src/identity/contactMapping.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/saga.test.ts
  packages/mobile/src/identity/saga.ts
  packages/mobile/src/identity/secureSend.ts
  packages/mobile/src/invite/EnterInviteCode.test.tsx
  packages/mobile/src/invite/EnterInviteCode.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.test.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListScreen.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestSummaryNotification.tsx
  packages/mobile/src/paymentRequest/PaymentRequestConfirmation.test.tsx
  packages/mobile/src/paymentRequest/PaymentRequestConfirmation.tsx
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestConfirmation.test.tsx.snap
  packages/mobile/src/paymentRequest/utils.ts
  packages/mobile/src/qrcode/QRScanner.tsx
  packages/mobile/src/qrcode/utils.ts
  packages/mobile/src/recipients/recipient.ts
  packages/mobile/src/send/SendAmount.test.tsx
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/SendConfirmation.test.tsx
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/ValidateRecipientAccount.test.tsx
  packages/mobile/src/send/ValidateRecipientAccount.tsx
  packages/mobile/src/send/ValidateRecipientInfo.test.tsx
  packages/mobile/src/send/ValidateRecipientIntro.tsx
  packages/mobile/src/send/__snapshots__/SendAmount.test.tsx.snap
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/send/__snapshots__/ValidateRecipientAccount.test.tsx.snap
  packages/mobile/src/send/__snapshots__/ValidateRecipientInfo.test.tsx.snap
  packages/mobile/src/send/actions.ts
  packages/mobile/src/send/reducers.ts
  packages/mobile/src/send/saga.test.ts
  packages/mobile/src/send/saga.ts
  packages/mobile/src/send/utils.ts
  packages/mobile/src/transactions/actions.ts
  packages/mobile/src/utils/formatting.ts
  packages/mobile/test/schemas.ts
  packages/mobile/test/values.ts
Labels: automerge, wallet, wallet-feature-complete

#3862 [docs] Add wave 2b link, lock 10000.1 cGLD
  packages/docs/celo-gold-holder-guide/quick-start.md
  packages/docs/getting-started/running-a-validator-in-baklava.md
  packages/docs/getting-started/running-a-validator-in-mainnet.md
Labels: automerge

#3872 Temp Hide Uptime
  packages/web/src/_page-tests/validators/__snapshots__/explore.test.tsx.snap
  packages/web/src/dev/ValidatorsList.tsx
  packages/web/src/dev/ValidatorsListRow.tsx
  packages/web/src/dev/ValidatorsListStyles.tsx
Labels: automerge

#3840 [Wallet][ReDesign] Notifications
  packages/mobile/__mocks__/react-i18next.js
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/en-US/inviteFlow11.json
  packages/mobile/locales/en-US/paymentRequestFlow.json
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/es-419/inviteFlow11.json
  packages/mobile/locales/es-419/paymentRequestFlow.json
  packages/mobile/locales/es-419/walletFlow5.json
  packages/mobile/src/escrow/EscrowedPaymentLineItem.tsx
  packages/mobile/src/escrow/EscrowedPaymentListItem.test.tsx
  packages/mobile/src/escrow/EscrowedPaymentListItem.tsx
  packages/mobile/src/escrow/EscrowedPaymentReminderSummaryNotification.tsx
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentLineItem.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentListItem.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentReminderSummaryNotification.test.tsx.snap
  packages/mobile/src/home/NotificationBox.test.tsx
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/home/__snapshots__/NotificationBox.test.tsx.snap
  packages/mobile/src/notifications/SimpleNotification.test.tsx
  packages/mobile/src/notifications/SimpleNotification.tsx
  packages/mobile/src/notifications/SummaryNotification.test.tsx
  packages/mobile/src/notifications/SummaryNotification.tsx
  packages/mobile/src/notifications/__snapshots__/SimpleNotification.test.tsx.snap
  packages/mobile/src/notifications/__snapshots__/SummaryNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.test.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestSummaryNotification.tsx
  packages/mobile/src/paymentRequest/OutgoingPaymentRequestListItem.tsx
  packages/mobile/src/paymentRequest/OutgoingPaymentRequestSummaryNotification.tsx
  packages/mobile/src/paymentRequest/PaymentRequestNotificationInner.test.tsx
  packages/mobile/src/paymentRequest/PaymentRequestNotificationInner.tsx
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestSummaryNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestSummaryNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestNotificationInner.test.tsx.snap
  packages/mobile/src/paymentRequest/utils.ts
  packages/react-components/components/AggregatedRequestsMessagingCard.test.tsx
  packages/react-components/components/AggregatedRequestsMessagingCard.tsx
  packages/react-components/components/CallToActionsBar.tsx
  packages/react-components/components/Card.tsx
  packages/react-components/components/MessagingCard.tsx
  packages/react-components/components/RequestMessagingCard.test.tsx
  packages/react-components/components/RequestMessagingCard.tsx
  packages/react-components/components/SimpleMessagingCard.test.tsx
  packages/react-components/components/SimpleMessagingCard.tsx
Labels: automerge

#3856 Update voting-validators.md and add celovote.com/scores in it
  packages/docs/celo-gold-holder-guide/voting-validators.md
Labels: automerge

#3882 Fix broken link on /validators
  packages/web/src/_page-tests/validators/__snapshots__/index.test.tsx.snap
  packages/web/src/dev/Engage.tsx
Labels: automerge, web

#3883 [Wallet] Increment version to 1.8.2 and fix Geth crash on android
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/proguard-rules.pro
  packages/mobile/android/app/src/main/assets/custom/LicenseDisclaimer.txt
  packages/mobile/android/gradle.properties
  packages/mobile/ios/celo-tvOS/Info.plist
  packages/mobile/ios/celo-tvOSTests/Info.plist
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/ios/celo/Info.plist
  packages/mobile/ios/celoTests/Info.plist
  packages/mobile/package.json
  packages/mobile/src/firebase/firebase.ts
  yarn.lock
Labels: automerge

#3877 [Wallet] Secure Send Pt 2
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/es-419/sendFlow7.json
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/contactMapping.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/saga.test.ts
  packages/mobile/src/identity/saga.ts
  packages/mobile/src/identity/secureSend.ts
  packages/mobile/src/paymentRequest/utils.ts
  packages/mobile/src/qrcode/utils.ts
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/SendConfirmation.test.tsx
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/TransferConfirmationCard.test.tsx
  packages/mobile/src/send/TransferConfirmationCard.tsx
  packages/mobile/src/send/TransferReviewCard.tsx
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/send/__snapshots__/TransferConfirmationCard.test.tsx.snap
  packages/mobile/src/transactions/TransactionReview.test.tsx
  packages/mobile/src/transactions/TransactionReview.tsx
  packages/mobile/src/transactions/TransferFeedItem.tsx
Labels: automerge, wallet, wallet-feature-complete

#3875 Fixes to Oracle deployment
  packages/celotool/src/lib/azure.ts
  packages/celotool/src/lib/oracle.ts
  packages/celotool/src/lib/testnet-utils.ts
  packages/celotool/src/lib/utils.ts
Labels: automerge

#3891 [Wallet] Fix outdated Podfile.lock
  packages/mobile/ios/Podfile.lock
Labels: automerge

#3876 fix: protocol has a missing explicit dependency on the dev-utils package
  dependency-graph.json
  packages/celotool/package.json
  yarn.lock
Labels: automerge

#3880 [Wallet] Type safe navigate
  packages/mobile/src/account/Account.test.tsx
  packages/mobile/src/account/Account.tsx
  packages/mobile/src/account/DataSaver.test.tsx
  packages/mobile/src/account/Invite.test.tsx
  packages/mobile/src/account/InviteReview.test.tsx
  packages/mobile/src/account/Profile.test.tsx
  packages/mobile/src/account/Profile.tsx
  packages/mobile/src/account/saga.ts
  packages/mobile/src/backup/BackupQuiz.test.tsx
  packages/mobile/src/backup/BackupSocialIntro.test.tsx
  packages/mobile/src/components/DevSkipButton.tsx
  packages/mobile/src/components/FeeIcon.tsx
  packages/mobile/src/escrow/ReclaimPaymentConfirmationScreen.test.tsx
  packages/mobile/src/exchange/ExchangeReview.test.tsx
  packages/mobile/src/exchange/ExchangeTradeScreen.test.tsx
  packages/mobile/src/firebase/notifications.ts
  packages/mobile/src/identity/PhoneNumberLookupQuotaScreen.test.tsx
  packages/mobile/src/import/ImportWallet.test.tsx
  packages/mobile/src/import/ImportWallet.tsx
  packages/mobile/src/import/ImportWalletEmpty.test.tsx
  packages/mobile/src/navigator/NavigationService.ts
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.tsx
  packages/mobile/src/paymentRequest/PaymentRequestConfirmation.test.tsx
  packages/mobile/src/pincode/PincodeEnter.test.tsx
  packages/mobile/src/qrcode/QRScanner.tsx
  packages/mobile/src/send/SendAmount.test.tsx
  packages/mobile/src/send/SendConfirmation.test.tsx
  packages/mobile/src/send/ValidateRecipientAccount.test.tsx
  packages/mobile/src/transactions/actions.ts
  packages/mobile/test/utils.ts
Labels: automerge

#3871 Home 4.1 (new design part 2)
  packages/web/public/static/locales/en/home.json
  packages/web/src/_page-tests/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/jobs.test.tsx.snap
  packages/web/src/home/Home.tsx
  packages/web/src/home/HomeBenefits.tsx
  packages/web/src/home/ImagePanes.tsx
  packages/web/src/home/TwoAssets.tsx
  packages/web/src/home/about-us.jpg
  packages/web/src/home/applications.jpg
  packages/web/src/home/earn-micro-work.jpg
  packages/web/src/home/growing-business.jpg
  packages/web/src/home/prosper-mexico.jpg
  packages/web/src/home/technology.jpg
  packages/web/src/icons/ExchangeIconCGLD.tsx
  packages/web/src/icons/ExchangeIconCUSD.tsx
  packages/web/src/icons/non-profit-dark-bg.png
  packages/web/src/icons/non-profit-light-bg.png
  packages/web/src/icons/sent-to-phone_dark-bg.png
  packages/web/src/icons/sent-to-phone_light-bg.png
  packages/web/src/join/ImagePanes.tsx
  packages/web/src/press/Press.tsx
  packages/web/src/press/coindesk-logo-white.png
  packages/web/src/press/drive-download-20200521T210507Z-001/coindesk-logo.png
  packages/web/src/press/drive-download-20200521T210507Z-001/fortune.png
  packages/web/src/press/drive-download-20200521T210507Z-001/venture-beat-logo.png
  packages/web/src/press/drive-download-20200521T210507Z-001/wsj-logo-transparent.png
  packages/web/src/press/forbes-logo-white.png
  packages/web/src/press/fortune-white.png
  packages/web/src/press/techcrunch-logo-white.png
  packages/web/src/press/venture-beat-logo-white.png
  packages/web/src/press/wsj-logo-white.png
  packages/web/src/shared/ImagePanes.tsx
Labels: automerge

#3885 Fix Screen width Jumping Eratically
  packages/web/src/shared/ChangeStory.tsx
  packages/web/src/shared/Footer.tsx
Labels: automerge

#3879 [Wallet] Redesign numerical keypad
  packages/mobile/src/pincode/Pincode.tsx
  packages/mobile/src/pincode/__snapshots__/PincodeEnter.test.tsx.snap
  packages/mobile/src/pincode/__snapshots__/PincodeLock.test.tsx.snap
  packages/mobile/src/pincode/__snapshots__/PincodeSet.test.tsx.snap
  packages/react-components/components/NumberKeypad.test.tsx
  packages/react-components/components/NumberKeypad.tsx
  packages/react-components/components/__snapshots__/NumberKeypad.test.tsx.snap
  packages/react-components/icons/Backspace.tsx
Labels: automerge

#3884 [Wallet] Account Key Analytics ++
  packages/mobile/src/analytics/constants.ts
  packages/mobile/src/backup/BackupIntroduction.tsx
  packages/mobile/src/backup/BackupPhrase.tsx
  packages/mobile/src/backup/BackupQuiz.test.tsx
  packages/mobile/src/backup/BackupQuiz.tsx
  packages/mobile/src/backup/__snapshots__/BackupQuiz.test.tsx.snap
  packages/mobile/src/navigator/Headers.v2.tsx
Labels: automerge

#3867 [Wallet] Account Key Cancel Confirmation
  packages/mobile/locales/en-US/backupKeyFlow6.json
  packages/mobile/locales/es-419/backupKeyFlow6.json
  packages/mobile/src/analytics/constants.ts
  packages/mobile/src/backup/BackupPhrase.tsx
  packages/mobile/src/backup/BackupQuiz.tsx
  packages/mobile/src/backup/CancelConfirm.tsx
Labels: wallet-redesign

#3906 Helm chart for eksportisto
  .env
  .env.baklava
  .env.rc1
  packages/celotool/src/cmds/deploy/destroy/eksportisto.ts
  packages/celotool/src/cmds/deploy/initial/eksportisto.ts
  packages/celotool/src/cmds/deploy/upgrade/eksportisto.ts
  packages/celotool/src/lib/eksportisto.ts
  packages/celotool/src/lib/env-utils.ts
  packages/helm-charts/eksportisto/Chart.yaml
  packages/helm-charts/eksportisto/templates/statefulset.yaml
  packages/helm-charts/eksportisto/values.yaml
Labels: automerge

#3863 [Wallet] Dialog Component
  packages/mobile/locales/en-US/backupKeyFlow6.json
  packages/mobile/locales/es-419/backupKeyFlow6.json
  packages/mobile/src/analytics/constants.ts
  packages/mobile/src/backup/BackupPhrase.tsx
  packages/mobile/src/backup/BackupQuiz.tsx
  packages/mobile/src/backup/CancelConfirm.tsx
  packages/mobile/src/components/Dialog.tsx
  packages/mobile/src/components/Modal.tsx
Labels: automerge, wallet-redesign

#3915 [Wallet] Allow QR scan to circumvent Secure Send check
  packages/mobile/src/send/SendAmount.tsx
Labels: automerge, wallet, wallet-feature-complete

#3914 Align unlock gold check to the smart contract implementation
  packages/cli/src/commands/lockedgold/unlock.test.ts
  packages/cli/src/commands/validator/affiliate.ts
  packages/cli/src/commands/validatorgroup/member.ts
  packages/cli/src/utils/checks.ts
  packages/docs/command-line-interface/validator.md
  packages/docs/command-line-interface/validatorgroup.md
Labels: automerge

#3910 [Wallet][ReDesign] Transactions drilldown
  packages/mobile/locales/en-US/receiveFlow8.json
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/locales/es-419/receiveFlow8.json
  packages/mobile/locales/es-419/sendFlow7.json
  packages/mobile/locales/es-419/walletFlow5.json
  packages/mobile/src/app/App.tsx
  packages/mobile/src/components/AccountNumber.tsx
  packages/mobile/src/components/ContactCircleSelf.tsx
  packages/mobile/src/components/Expandable.tsx
  packages/mobile/src/components/TotalLineItem.v2.tsx
  packages/mobile/src/exchange/ExchangeTradeScreen.tsx
  packages/mobile/src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap
  packages/mobile/src/icons/CircleArrowIcon.tsx
  packages/mobile/src/icons/DownArrowIcon.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/send/TransferConfirmationCard.tsx
  packages/mobile/src/send/__snapshots__/TransferConfirmationCard.test.tsx.snap
  packages/mobile/src/transactions/BottomText.tsx
  packages/mobile/src/transactions/CommentSection.tsx
  packages/mobile/src/transactions/TransactionReview.test.tsx
  packages/mobile/src/transactions/TransactionReview.tsx
  packages/mobile/src/transactions/TransferAvatars.tsx
  packages/mobile/src/transactions/TransferConfirmationCard.test.tsx
  packages/mobile/src/transactions/TransferConfirmationCard.tsx
  packages/mobile/src/transactions/UserSection.tsx
  packages/mobile/src/transactions/__snapshots__/TransferConfirmationCard.test.tsx.snap
  packages/mobile/src/transactions/actions.ts
  packages/react-components/components/RequestMessagingCard.tsx
  packages/react-components/styles/fonts.v2.tsx
  packages/utils/src/address.test.ts
  packages/utils/src/address.ts
  packages/utils/src/phoneNumbers.ts
Labels: automerge

#3923 [docs] ReleaseGold Wave 3 link
  packages/docs/celo-gold-holder-guide/quick-start.md
Labels: automerge

#3833 Cloud HSM usage guide (and small fixes to validator guide)
  README-dev.md
  packages/docs/SUMMARY.md
  packages/docs/celo-gold-holder-guide/quick-start.md
  packages/docs/developer-resources/integrations/cloud-hsm.md
  packages/docs/getting-started/running-a-validator-in-baklava.md
  packages/docs/getting-started/running-a-validator-in-mainnet.md
  packages/docs/getting-started/validator-troubleshooting-faq.md
Labels: automerge

#3895 [Wallet] Redesign of "Chose recipient" and "Enter amount" screens
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/src/account/__snapshots__/Invite.test.tsx.snap
  packages/mobile/src/components/CancelButton.v2.tsx
  packages/mobile/src/fees/selectors.ts
  packages/mobile/src/home/SendOrRequestBar.tsx
  packages/mobile/src/navigator/Headers.v2.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/TabNavigator.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/pincode/__snapshots__/PincodeEnter.test.tsx.snap
  packages/mobile/src/pincode/__snapshots__/PincodeLock.test.tsx.snap
  packages/mobile/src/pincode/__snapshots__/PincodeSet.test.tsx.snap
  packages/mobile/src/recipients/RecipientItem.tsx
  packages/mobile/src/recipients/RecipientPicker.tsx
  packages/mobile/src/recipients/__snapshots__/RecipientItem.test.tsx.snap
  packages/mobile/src/send/Send.tsx
  packages/mobile/src/send/SendAmount.test.tsx
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/__snapshots__/SendAmount.test.tsx.snap
  packages/react-components/components/NumberKeypad.tsx
  packages/react-components/components/__snapshots__/NumberKeypad.test.tsx.snap
  packages/react-components/icons/Times.tsx
Labels: automerge

#3928 remove sandbox from dev page as it does not work
  packages/web/src/_page-tests/developers/__snapshots__/Index.test.tsx.snap
  packages/web/src/dev/DevelopersPage.tsx
Labels: automerge, web

#3896 Improve BackupQuiz Account Key Fetching
  packages/mobile/src/analytics/constants.ts
  packages/mobile/src/backup/BackupPhrase.test.tsx
  packages/mobile/src/backup/BackupPhrase.tsx
  packages/mobile/src/backup/BackupQuiz.test.tsx
  packages/mobile/src/backup/BackupQuiz.tsx
  packages/mobile/src/backup/BackupSocial.tsx
  packages/mobile/src/backup/__snapshots__/BackupPhrase.test.tsx.snap
  packages/mobile/src/backup/utils.ts
  packages/mobile/src/navigator/types.tsx
Labels: automerge

#3930 [Wallet] Fix wrong navigation to Language page
  packages/mobile/src/language/Language.tsx
Labels: automerge

#3926 Refactor/dependency graph with package names
  .circleci/config.yml
  dependency-graph.json
  scripts/check_if_test_should_run_v2.ts
  scripts/dependency-graph-utils.ts
Labels: automerge
