Repository celo-org/celo-monorepo, pull requests merged in 2020-02, with the labels that each got.

#2525 Human readable description for governance proposals
  packages/cli/src/commands/governance/propose.ts
  packages/contractkit/src/wrappers/Governance.test.ts
  packages/contractkit/src/wrappers/Governance.ts
  packages/docs/command-line-interface/governance.md
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/governance/Proposals.sol
  packages/protocol/test/common/integration.ts
  packages/protocol/test/governance/governance.ts
Labels: automerge

#2606 [Wallet] Fix Pay & Decline buttons when open app from notification
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/es-419/sendFlow7.json
  packages/mobile/src/escrow/EscrowedPaymentListScreen.tsx
  packages/mobile/src/firebase/actions.ts
  packages/mobile/src/firebase/notifications.ts
  packages/mobile/src/firebase/saga.ts
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.test.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListScreen.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestSummaryNotification.tsx
  packages/mobile/src/paymentRequest/OutgoingPaymentRequestListItem.test.tsx
  packages/mobile/src/paymentRequest/OutgoingPaymentRequestListItem.tsx
  packages/mobile/src/paymentRequest/OutgoingPaymentRequestListScreen.tsx
  packages/mobile/src/paymentRequest/OutgoingPaymentRequestSummaryNotification.tsx
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/actions.ts
  packages/mobile/src/send/saga.ts
  packages/notification-service/src/firebase.ts
  packages/notification-service/src/handlers.ts
Labels: automerge

#2395 Add isReserveLow function
  packages/protocol/contracts/governance/EpochRewards.sol
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/contracts/stability/interfaces/IReserve.sol
  packages/protocol/test/governance/epochrewards.ts
  packages/protocol/test/stability/reserve.ts
Labels: automerge

#2328 Community reward via governable fraction
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/protocol/contracts/governance/EpochRewards.sol
  packages/protocol/migrations/15_epoch_rewards.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/test/governance/epochrewards.ts
Labels: automerge

#2645 Support issuer selection under key rotation
  packages/protocol/contracts/identity/Attestations.sol
  packages/protocol/test/identity/attestations.ts
Labels: automerge

#2651 [WalletKit] Fix using incorrect gcs bucket for downloading production artifacts
  packages/walletkit/bin/build-sdk.js
  packages/walletkit/package.json
Labels: automerge

#2697 [Wallet] Fix empty contacts on iOS 13
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/react-components/package.json
  yarn.lock
Labels: automerge

#2686 [Wallet] A few missing things from the 1.6.0 deployment
  packages/mobile/Gemfile.lock
  packages/mobile/android/gradle.properties
Labels: automerge

#2405 contractkit: add slashing wrappers
  packages/cli/src/commands/rewards/show.ts
  packages/cli/src/commands/validator/status.ts
  packages/contractkit/src/contract-cache.ts
  packages/contractkit/src/kit.ts
  packages/contractkit/src/wrappers/DoubleSigningSlasher.ts
  packages/contractkit/src/wrappers/DowntimeSlasher.ts
  packages/contractkit/src/wrappers/Election.ts
  packages/contractkit/src/wrappers/LockedGold.ts
  packages/contractkit/src/wrappers/Validators.ts
  packages/docs/celo-codebase/protocol/proof-of-stake/penalties.md
  packages/docs/command-line-interface/rewards.md
  packages/docs/command-line-interface/validator.md
  packages/utils/src/address.ts
Labels: automerge

#2614 Adjust governance proposal CLI and refactor contract based on baklava feedback
  packages/cli/src/commands/governance/executehotfix.ts
  packages/cli/src/commands/governance/list.ts
  packages/cli/src/commands/governance/propose.ts
  packages/cli/src/utils/checks.ts
  packages/cli/src/utils/governance.ts
  packages/contractkit/src/wrappers/Governance.ts
  packages/protocol/contracts/governance/Governance.sol
Labels: automerge

#2699 [Wallet] Add missing photos permission on iOS
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo/Info.plist
Labels: automerge

#2709 Increment @celo/utils, @celo/contractkit, and @celo/celocli version numbers
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/leaderboard/package.json
  packages/mobile/package.json
  packages/protocol/package.json
  packages/react-components/package.json
  packages/transaction-metrics-exporter/package.json
  packages/utils/package.json
  packages/verifier/package.json
  packages/walletkit/package.json
Labels: automerge

#2715 Fix minor verification typo
  packages/mobile/locales/en-US/nuxVerification2.json
Labels: automerge

#2722 Move the faucet to use ContractKit
  packages/faucet/.gitignore
  packages/faucet/package.json
  packages/faucet/scripts/test-celo-adapter.ts
  packages/faucet/scripts/transfer-funds.ts
  packages/faucet/src/celo-adapter.ts
  packages/faucet/src/contracts/Escrow.ts
  packages/faucet/src/contracts/GoldToken.ts
  packages/faucet/src/contracts/StableToken.ts
  packages/faucet/src/contracts/types/Escrow.d.ts
  packages/faucet/src/contracts/types/GoldToken.d.ts
  packages/faucet/src/contracts/types/StableToken.d.ts
  packages/faucet/src/database-helper.ts
  packages/faucet/src/index.ts
  packages/faucet/src/protocol/signing-utils.ts
  packages/faucet/src/test-driver.ts
  packages/faucet/src/tx.ts
  packages/faucet/yarn.lock
  yarn.lock
Labels: automerge

#2724 reword strings to clarify tone in spanish
  packages/mobile/locales/es-419/nuxNamePin1.json
  packages/mobile/locales/es-419/sendFlow7.json
Labels: automerge

#2710 [Wallet] Add funds with Moonpay widget
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/locales/es-419/accountScreen10.json
  packages/mobile/src/account/Account.tsx
  packages/mobile/src/account/FiatExchange.test.tsx
  packages/mobile/src/account/FiatExchange.tsx
  packages/mobile/src/account/__snapshots__/FiatExchange.test.tsx.snap
  packages/mobile/src/flags.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
Labels: automerge

#2751 Improve language of cookie/privacy consent banner
  packages/web/public/static/locales/en/common.json
  packages/web/src/header/BlueBanner.tsx
  packages/web/src/header/CookieConsent.tsx
Labels: automerge

#2750 Fix broken translations
  packages/web/public/static/locales/en/common.json
  packages/web/public/static/locales/en/community.json
  packages/web/src/shared/ConnectionFooter.tsx
Labels: automerge

#2753 [Wallet] Allow small gold transactions on Exchange Screen
  packages/mobile/src/exchange/ExchangeTradeScreen.tsx
Labels: automerge

#2749 Add Moonpay auth package for signing Moonpay requests
  packages/moonpay-auth/.env.enc
  packages/moonpay-auth/.firebaserc
  packages/moonpay-auth/.gitignore
  packages/moonpay-auth/README.md
  packages/moonpay-auth/firebase.json
  packages/moonpay-auth/package.json
  packages/moonpay-auth/src/config.ts
  packages/moonpay-auth/src/index.ts
  packages/moonpay-auth/tsconfig.json
  packages/moonpay-auth/tslint.json
  packages/moonpay-auth/yarn.lock
  scripts/key_placer.sh
  yarn.lock
Labels: automerge

#2747 Change `C-Labs || C Labs` to `cLabs`
  packages/docs/celo-codebase/protocol/privacy.md
  packages/docs/getting-started/glossary.md
  packages/docs/getting-started/running-a-validator.md
  packages/terraform-modules/testnet/README.md
  packages/web/public/static/locales/en/codeofconduct.json
  packages/web/public/static/locales/en/common.json
  packages/web/src/_page-tests/__snapshots__/community.test.tsx.snap
  packages/web/src/_page-tests/stake-off/__snapshots__/terms.test.tsx.snap
  packages/web/src/community/connect/FellowViewer.tsx
  packages/web/src/terms/StakeOffTerms.tsx
  scripts/key_placer.sh
Labels: automerge

#2622 [Wallet] Run E2E test on iOS
  .circleci/config.yml
  packages/mobile/.env.test
  packages/mobile/.gitignore
  packages/mobile/Gemfile
  packages/mobile/Gemfile.lock
  packages/mobile/e2e/Transfer.spec.js
  packages/mobile/e2e/init.js
  packages/mobile/e2e/utils.js
  packages/mobile/index.js
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/ios/celo/AppDelegate.m
  packages/mobile/ios/sentry.properties.template
  packages/mobile/package.json
  packages/mobile/scripts/run_e2e.sh
  packages/mobile/src/setupE2eEnv.e2e.ts
  packages/mobile/src/setupE2eEnv.ts
  packages/utils/src/parsing.test.ts
  packages/utils/src/parsing.ts
Labels: automerge

#2650 Added DISABLE_WEBAPP to blockscout indexer
  packages/helm-charts/blockscout/templates/blockscout-indexer.deployment.yaml
  packages/helm-charts/blockscout/templates/blockscout-web.deployment.yaml
Labels: automerge

#2770 [Wallet] Fix React Native packager failing
  packages/moonpay-auth/package.json
  yarn.lock
Labels: automerge

#2759 Remove --bail flag from e2e tests
  packages/celotool/ci_test_attestations.sh
  packages/celotool/ci_test_blockchain_parameters.sh
  packages/celotool/ci_test_governance.sh
  packages/celotool/ci_test_slashing.sh
  packages/celotool/ci_test_sync.sh
  packages/celotool/ci_test_transfers.sh
  packages/celotool/ci_test_validator_order.sh
Labels: automerge

#2775 Updates twitter handle
  packages/web/src/_page-tests/__snapshots__/community.test.tsx.snap
  packages/web/src/_page-tests/build/__snapshots__/index.test.tsx.snap
  packages/web/src/header/OpenGraph.tsx
  packages/web/src/shared/SocialChannels.tsx
Labels: automerge

#2746 Add docs about securing nodes and services
  packages/docs/SUMMARY.md
  packages/docs/operations-manual/securing-nodes-and-services.md
Labels: automerge

#2791 [Wallet] Add null check to import screen nav prop
  packages/mobile/src/import/ImportWallet.tsx
Labels: automerge

#2774 Bump invite fee higher
  packages/mobile/android/gradle.properties
  packages/mobile/src/account/__snapshots__/InviteReview.test.tsx.snap
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/send/__snapshots__/TransferReviewCard.test.tsx.snap
Labels: automerge, wallet

#2777 Address flaky docker builds
  cloudbuild.yaml
  packages/walletkit/bin/build-sdk.js
Labels: automerge

#2808 [C02] Any owner of the Multisig can execute unconfirmed transactions
  packages/protocol/contracts/common/MultiSig.sol
Labels: audit-fix, automerge

#2800 Use Geth1.9 on e2e tests
  .circleci/config.yml
  dockerfiles/circleci/Dockerfile
  packages/celotool/src/cmds/geth/run.ts
  packages/celotool/src/e2e-tests/blockchain_parameters_tests.ts
  packages/celotool/src/e2e-tests/sync_tests.ts
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/celotool/src/lib/genesis_constants.ts
  packages/celotool/src/lib/geth.ts
  packages/protocol/contracts/common/Proxy.sol
Labels: automerge

#2809 [L03] Missing revert messages in require statements
  packages/protocol/contracts/baklava/Freezable.sol
  packages/protocol/contracts/common/FixidityLib.sol
  packages/protocol/contracts/common/FractionUtil.sol
  packages/protocol/contracts/common/Initializable.sol
  packages/protocol/contracts/common/UsingPrecompiles.sol
Labels: audit-fix, automerge

#2798 Fix yarn install cache miss on CircleCI
  .circleci/config.yml
Labels: automerge

#2811 [L08] Unused events
  packages/protocol/contracts/governance/Validators.sol
Labels: audit-fix, automerge

#2789 Retrieve revert reason if transaction reverted
  packages/celotool/src/cmds/transactions/describe.ts
Labels: automerge

#2815 Changes to Validator list page
  packages/web/pages/validators/explore.tsx
  packages/web/server/index.ts
  packages/web/src/dev/ValidatorsListApp.tsx
  packages/web/src/shared/menu-items.ts
Labels: automerge

#2769 Reserve spender can only transfer gold to specified addresses
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/stability/Exchange.sol
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/contracts/stability/interfaces/IReserve.sol
  packages/protocol/contracts/stability/test/MockReserve.sol
  packages/protocol/migrations/09_exchange.ts
  packages/protocol/test/stability/reserve.ts
Labels: automerge

#2755 Fixing address comparison when getting affiliates
  packages/cli/src/commands/validator/status.ts
  packages/contractkit/src/identity/claims/verify.ts
  packages/contractkit/src/identity/metadata.ts
  packages/contractkit/src/wrappers/Validators.ts
  packages/docs/developer-resources/contractkit/reference/classes/_identity_metadata_.identitymetadatawrapper.md
  packages/docs/developer-resources/contractkit/reference/modules/_identity_claims_verify_.md
  packages/docs/developer-resources/contractkit/reference/modules/_identity_metadata_.md
Labels: automerge

#2797 [C01] Funds of the Escrow contract can be locked by anyone
  packages/protocol/contracts/identity/Escrow.sol
Labels: audit-fix, automerge

#2795 [M08] The reveal process can get stuck for a proposer
  packages/protocol/contracts/identity/Random.sol
  packages/protocol/contracts/identity/test/TestRandom.sol
  packages/protocol/test/identity/random.ts
Labels: audit-fix, automerge

#2576 add link to list of contributors to docs
  packages/docs/community/contributing.md
Labels: docs

#2806 [N01] Unnecessary variable assignment
  packages/protocol/contracts/identity/Random.sol
  packages/protocol/test/identity/attestations.ts
Labels: audit-fix, automerge

#2807 [M06] Lack of input validations
  packages/protocol/contracts/common/Accounts.sol
  packages/protocol/contracts/common/GoldToken.sol
  packages/protocol/contracts/common/Proxy.sol
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/stability/StableToken.sol
Labels: audit-fix, automerge

#2771 Atomic validator key update
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/cli/src/commands/account/authorize.test.ts
  packages/cli/src/commands/account/authorize.ts
  packages/contractkit/src/wrappers/Accounts.test.ts
  packages/contractkit/src/wrappers/Accounts.ts
  packages/docs/command-line-interface/account.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_accounts_.accountswrapper.md
  packages/protocol/contracts/common/Accounts.sol
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/contracts/governance/interfaces/IValidators.sol
  packages/protocol/contracts/governance/test/MockValidators.sol
  packages/protocol/test/governance/validators.ts
Labels: automerge

#2844 [Wallet] Fix android e2e test
  packages/mobile/android/app/build.gradle
  packages/mobile/package.json
  packages/mobile/scripts/run_app.sh
  packages/mobile/scripts/run_e2e.sh
Labels: automerge

#2399 Reading data to leaderboard sheet
  .env.baklavastaging
  .env.mnemonic.baklavastaging.enc
  dockerfiles/leaderboard/Dockerfile
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/leaderboard.ts
  packages/contractkit/src/kit.ts
  packages/docs/developer-resources/contractkit/reference/classes/_kit_.contractkit.md
  packages/helm-charts/leaderboard/templates/leaderboard.cronjob.yaml
  packages/helm-charts/leaderboard/templates/leaderboard.secret.yaml
  packages/helm-charts/leaderboard/values.yaml
  packages/leaderboard/package.json
  packages/leaderboard/src/board.ts
  packages/leaderboard/src/upload.ts
  yarn.lock
Labels: automerge

#2845 Update codecov
  package.json
  yarn.lock
Labels: automerge

#2613 Add .env vars for geth&migration options differing on developer/production testnets
  .env
  .env.baklava
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/celotool/src/lib/migration-utils.ts
  packages/helm-charts/testnet/templates/_helpers.tpl
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
Labels: automerge

#2617 Vesting contract revamp
  packages/cli/package.json
  packages/contractkit/package.json
  packages/protocol/contracts/common/UsingRegistry.sol
  packages/protocol/contracts/common/interfaces/IAccounts.sol
  packages/protocol/contracts/governance/ReleaseGoldFactory.sol
  packages/protocol/contracts/governance/ReleaseGoldInstance.sol
  packages/protocol/contracts/governance/VestingFactory.sol
  packages/protocol/contracts/governance/VestingInstance.sol
  packages/protocol/contracts/governance/interfaces/IReleaseGoldFactory.sol
  packages/protocol/contracts/governance/interfaces/IReleaseGoldInstance.sol
  packages/protocol/contracts/governance/proxies/VestingFactoryProxy.sol
  packages/protocol/lib/registry-utils.ts
  packages/protocol/migrations/11_lockedgold.ts
  packages/protocol/migrations/11_vesting_factory.ts
  packages/protocol/migrations/12_validators.ts
  packages/protocol/migrations/13_election.ts
  packages/protocol/migrations/14_epoch_rewards.ts
  packages/protocol/migrations/15_random.ts
  packages/protocol/migrations/16_attestations.ts
  packages/protocol/migrations/17_escrow.ts
  packages/protocol/migrations/18_blockchainparams.ts
  packages/protocol/migrations/19_governance_slasher.ts
  packages/protocol/migrations/20_double_signing_slasher.ts
  packages/protocol/migrations/21_downtime_slasher.ts
  packages/protocol/migrations/22_governance.ts
  packages/protocol/migrations/23_elect_validators.ts
  packages/protocol/scripts/build.ts
  packages/protocol/test/governance/release_gold.ts
  packages/protocol/test/governance/vesting.ts
Labels: automerge

#2837 Fix graphic not showing and links incorrectly having an underline
  packages/web/public/static/normalize.css
  packages/web/src/_page-tests/__snapshots__/about.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/code-of-conduct.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/community.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/faq.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/past-events.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/user-agreement.test.tsx.snap
  packages/web/src/_page-tests/build/__snapshots__/faucet.test.tsx.snap
  packages/web/src/_page-tests/build/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/developers/__snapshots__/Index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/_page-tests/stake-off/__snapshots__/terms.test.tsx.snap
  packages/web/src/dev/Engage.tsx
  packages/web/src/shared/Button.3.tsx
Labels: automerge

#2838 Use the last address attested in the wallet
  packages/mobile/src/identity/contactMapping.ts
Labels: automerge, wallet

#2856 fix issue with file in static not being served from app engine due to…
  packages/web/development.yaml
  packages/web/pages/_document.tsx
  packages/web/production.yaml
  packages/web/public/favicon.ico
  packages/web/public/normalize.css
  packages/web/staging.yaml
Labels: automerge

#2748 On-chain governance constitution
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/governanceConstitution.js
Labels: automerge

#2796 [L02] Inconsistent quorum calculation
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/cli/src/commands/governance/viewhotfix.ts
  packages/contractkit/src/wrappers/Governance.ts
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_governance_.governancewrapper.md
  packages/protocol/contracts/common/UsingPrecompiles.sol
  packages/protocol/contracts/governance/DoubleSigningSlasher.sol
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/governance/test/GovernanceTest.sol
Labels: audit-fix, automerge

#2816 [web] Fix the links to the developer guide
  packages/web/src/_page-tests/developers/__snapshots__/Index.test.tsx.snap
  packages/web/src/shared/menu-items.ts
Labels: automerge

#2854 🔁 redirect build/* to developers/* + devs
  packages/web/pages/developers/faucet.tsx
  packages/web/pages/developers/wallet.tsx
  packages/web/server/index.ts
  packages/web/src/_page-tests/developers/__snapshots__/Index.test.tsx.snap
  packages/web/src/_page-tests/developers/__snapshots__/faucet.test.tsx.snap
  packages/web/src/_page-tests/developers/__snapshots__/wallet.test.tsx.snap
  packages/web/src/_page-tests/developers/faucet.test.tsx
  packages/web/src/_page-tests/developers/wallet.test.tsx
  packages/web/src/_page-tests/validators/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/validators/index.test.tsx
  packages/web/src/shared/menu-items.ts
Labels: automerge

#2830 [contractKit] Fix ganache-core failing in unit tests
  packages/cli/.gitignore
  packages/cli/.npmignore
  packages/cli/package.json
  packages/cli/src/test-utils/ganache.setup.ts
  packages/contractkit/.gitignore
  packages/contractkit/.npmignore
  packages/contractkit/package.json
  packages/contractkit/src/test-utils/ganache.setup.ts
  packages/dev-utils/package.json
  packages/dev-utils/src/ganache-setup.ts
  packages/protocol/scripts/devchain.ts
  yarn.lock
Labels: automerge

#2857 [Wallet] Prevent duplicates in mnemonic
  packages/mobile/src/web3/saga.ts
Labels: automerge

#2435 Developers SBAT know that the oldest oracle report used by CP-DOTO hasn't expired #299
  packages/protocol/contracts/stability/Exchange.sol
  packages/protocol/contracts/stability/SortedOracles.sol
  packages/protocol/contracts/stability/interfaces/ISortedOracles.sol
  packages/protocol/contracts/stability/test/MockSortedOracles.sol
  packages/protocol/test/stability/sortedoracles.ts
Labels: audit

#2864 [N11] Unnecessary modifier in mint function
  packages/protocol/contracts/stability/StableToken.sol
Labels: audit, automerge

#2862 [N04] Misleading and incomplete comments
  packages/protocol/contracts/common/FixidityLib.sol
  packages/protocol/contracts/common/Signatures.sol
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/test/common/fixidity.ts
Labels: audit, automerge

#2863 [N09] Lack of explicit return case
  packages/protocol/contracts/common/MultiSig.sol
Labels: audit, automerge

#2850 Add election view function with set size as parameter
  packages/protocol/contracts/governance/Election.sol
Labels: audit, automerge

#2865 [N20] Unnecessary checks
  packages/protocol/contracts/common/FixidityLib.sol
Labels: audit, automerge

#2813 [L10] Inconsistent validation of variables
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/governance/LockedGold.sol
  packages/protocol/contracts/stability/SortedOracles.sol
  packages/protocol/contracts/stability/StableToken.sol
Labels: audit, audit-fix, automerge

#2889 [L07] The minimum gas price calculation differs from documentation
  packages/docs/celo-codebase/protocol/transactions/gas-pricing.md
Labels: audit, audit-fix, automerge

#2895 [M04] Undocumented assembly blocks
  packages/protocol/contracts/common/Proxy.sol
Labels: audit, audit-fix, automerge

#2907 [L09] Lack of indexed parameters in events
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/contracts/stability/SortedOracles.sol
Labels: audit, audit-fix, automerge

#2891 [L21] Lack of assert statement may produce unexpected slash
  packages/protocol/contracts/governance/SlasherUtil.sol
Labels: audit, audit-fix, automerge

#2648 [Wallet] Lock the whole wallet with PIN
  packages/mobile/android/app/src/main/java/org/celo/mobile/MainActivity.java
  packages/mobile/ios/celo/AppDelegate.m
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/locales/es-419/accountScreen10.json
  packages/mobile/src/account/Account.tsx
  packages/mobile/src/account/Security.tsx
  packages/mobile/src/account/saga.ts
  packages/mobile/src/app/Background.test.tsx
  packages/mobile/src/app/Background.tsx
  packages/mobile/src/app/__snapshots__/Background.test.tsx.snap
  packages/mobile/src/app/actions.ts
  packages/mobile/src/app/reducers.ts
  packages/mobile/src/app/saga.test.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/app/selectors.ts
  packages/mobile/src/geth/saga.ts
  packages/mobile/src/navigator/NavigationService.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/NavigatorWrapper.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/pincode/PincodeConfirmation.tsx
  packages/mobile/test/schemas.ts
  packages/mobile/test/values.ts
Labels: automerge

#2782 [Wallet]: Invite text message link support for iOS
  packages/mobile/__mocks__/react-native-device-info.ts
  packages/mobile/__mocks__/react-native-firebase.ts
  packages/mobile/__mocks__/react-native-version-check.ts
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/java/org/celo/mobile/MainApplication.java
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/xcshareddata/xcschemes/celo.xcscheme
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/es-419/sendFlow7.json
  packages/mobile/src/account/InviteReview.test.tsx
  packages/mobile/src/account/InviteReview.tsx
  packages/mobile/src/firebase/dynamicLinks.test.ts
  packages/mobile/src/firebase/dynamicLinks.ts
  packages/mobile/src/invite/EnterInviteCode.tsx
  packages/mobile/src/invite/actions.ts
  packages/mobile/src/invite/saga.test.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/invite/utils.ts
  packages/mobile/src/send/saga.ts
  packages/mobile/src/utils/appstore.ts
  packages/mobile/src/utils/dynamicLink.ts
Labels: automerge

#2909 Fix cloudbuild OOM by using machine with more CPU
  cloudbuild.yaml
Labels: automerge

#2892 [L15] Failure of `ecrecover` function does not revert
  packages/protocol/contracts/common/Signatures.sol
Labels: audit, audit-fix, automerge

#2882 Support key rotation after whitelisting hotfix
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/test/governance/governance.ts
Labels: audit, automerge

#2902 [N19] Docs incorrect regarding proposal deposits
  packages/docs/celo-codebase/protocol/governance.md
Labels: audit, audit-fix, automerge

#2893 [L16] Not using the SafeMath library
  packages/protocol/contracts/common/MultiSig.sol
  packages/protocol/contracts/common/Registry.sol
  packages/protocol/contracts/common/linkedlists/AddressLinkedList.sol
  packages/protocol/contracts/common/linkedlists/AddressSortedLinkedList.sol
  packages/protocol/contracts/common/linkedlists/AddressSortedLinkedListWithMedian.sol
  packages/protocol/contracts/common/linkedlists/IntegerSortedLinkedList.sol
  packages/protocol/contracts/common/linkedlists/LinkedList.sol
  packages/protocol/contracts/common/linkedlists/SortedLinkedList.sol
  packages/protocol/contracts/common/linkedlists/SortedLinkedListWithMedian.sol
  packages/protocol/contracts/governance/DoubleSigningSlasher.sol
  packages/protocol/contracts/governance/DowntimeSlasher.sol
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/governance/LockedGold.sol
  packages/protocol/contracts/governance/test/MockValidators.sol
  packages/protocol/contracts/identity/Attestations.sol
  packages/protocol/contracts/identity/Random.sol
  packages/protocol/contracts/stability/Exchange.sol
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/contracts/stability/SortedOracles.sol
Labels: audit, audit-fix, automerge

#2901 [N17] Different address nomenclature for precompiled contracts
  packages/protocol/contracts/common/GoldToken.sol
Labels: audit, audit-fix, automerge

#2685 Adding lastEpochBlock to random.sol
  packages/protocol/contracts/identity/Random.sol
  packages/protocol/test/identity/random.ts
Labels: audit, automerge

#2888 Don't update exchange buckets if the oldest oracle report is expired
  packages/protocol/contracts/stability/Exchange.sol
  packages/protocol/contracts/stability/SortedOracles.sol
  packages/protocol/contracts/stability/interfaces/ISortedOracles.sol
  packages/protocol/contracts/stability/test/MockSortedOracles.sol
  packages/protocol/test/stability/exchange.ts
  packages/protocol/test/stability/sortedoracles.ts
Labels: audit, automerge

#2900 [N14] Broken links in comments
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/stability/StableToken.sol
Labels: audit, audit-fix, automerge

#2897 [N06] Lack of consistency
  packages/protocol/contracts/common/Accounts.sol
Labels: audit, audit-fix, automerge

#2778 [N12] Incomplete docstrings
  packages/protocol/contracts/common/Accounts.sol
  packages/protocol/contracts/common/FeeCurrencyWhitelist.sol
  packages/protocol/contracts/common/GasPriceMinimum.sol
  packages/protocol/contracts/common/GoldToken.sol
  packages/protocol/contracts/common/Registry.sol
  packages/protocol/contracts/common/linkedlists/AddressLinkedList.sol
  packages/protocol/contracts/common/linkedlists/AddressSortedLinkedList.sol
  packages/protocol/contracts/common/linkedlists/AddressSortedLinkedListWithMedian.sol
  packages/protocol/contracts/common/linkedlists/IntegerSortedLinkedList.sol
  packages/protocol/contracts/common/linkedlists/LinkedList.sol
  packages/protocol/contracts/common/linkedlists/SortedLinkedList.sol
  packages/protocol/contracts/common/linkedlists/SortedLinkedListWithMedian.sol
  packages/protocol/contracts/governance/BlockchainParameters.sol
  packages/protocol/contracts/governance/DoubleSigningSlasher.sol
  packages/protocol/contracts/governance/DowntimeSlasher.sol
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/contracts/governance/EpochRewards.sol
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/governance/GovernanceSlasher.sol
  packages/protocol/contracts/governance/LockedGold.sol
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/contracts/identity/Attestations.sol
  packages/protocol/contracts/identity/Escrow.sol
  packages/protocol/contracts/identity/Random.sol
  packages/protocol/contracts/stability/Exchange.sol
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/contracts/stability/SortedOracles.sol
Labels: audit, audit-fix, automerge

#2623 Correct epoch definitions in protocol and contractkit
  packages/contractkit/src/kit.ts
  packages/docs/developer-resources/contractkit/reference/classes/_kit_.contractkit.md
  packages/protocol/contracts/common/UsingPrecompiles.sol
  packages/protocol/contracts/governance/DowntimeSlasher.sol
  packages/protocol/contracts/governance/test/MockUsingPrecompiles.sol
  packages/protocol/lib/test-utils.ts
  packages/protocol/test/governance/downtime_slasher.ts
  packages/protocol/test/governance/validators.ts
Labels: audit

#2894 [L22] Not following the fail-loudly principle
  packages/protocol/contracts/common/MultiSig.sol
  packages/protocol/test/common/multisig.ts
Labels: audit, audit-fix

#2577 Freeze initial reserve gold
  packages/protocol/contracts/stability/Exchange.sol
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/contracts/stability/interfaces/IReserve.sol
  packages/protocol/contracts/stability/test/MockReserve.sol
  packages/protocol/migrations/07_reserve.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/test/governance/epochrewards.ts
  packages/protocol/test/stability/reserve.ts
Labels: audit

#2896 [N05] Typos
  packages/protocol/contracts/common/Accounts.sol
  packages/protocol/contracts/common/UsingPrecompiles.sol
  packages/protocol/contracts/common/linkedlists/SortedLinkedList.sol
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/contracts/stability/SortedOracles.sol
Labels: audit, audit-fix, automerge

#2905 [N23] Unused code
  packages/protocol/contracts/common/FixidityLib.sol
  packages/protocol/contracts/stability/Reserve.sol
Labels: audit, audit-fix, automerge

#2903 [N21] Inconsistent use of onlyVm modifier
  packages/protocol/contracts/common/CalledByVm.sol
  packages/protocol/contracts/common/GasPriceMinimum.sol
  packages/protocol/contracts/common/GoldToken.sol
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/contracts/governance/EpochRewards.sol
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/contracts/identity/Random.sol
  packages/protocol/contracts/stability/StableToken.sol
  packages/protocol/contracts/stability/interfaces/IStableToken.sol
Labels: audit, audit-fix

#2930 Fix dappkit in the wallet
  packages/dappkit/package.json
  packages/mobile/src/dappkit/DappKitSignTxScreen.tsx
  yarn.lock
Labels: automerge

#2890 [L13] Fraction reduction is not applied in all methods, [L18] Lack of checks for denominator
  packages/protocol/contracts/common/FractionUtil.sol
  packages/protocol/contracts/common/test/FractionUtilTest.sol
  packages/protocol/contracts/stability/Exchange.sol
Labels: audit, audit-fix, automerge

#2898 [N08] Trust assumptions on hotfixes
  packages/docs/celo-codebase/protocol/governance.md
Labels: audit, audit-fix

#2871 Sets governance thresholds during migration
  packages/protocol/governanceConstitution.js
  packages/protocol/lib/web3-utils.ts
  packages/protocol/migrations/22_governance.ts
  packages/protocol/test/common/integration.ts
Labels: audit

#2883 Allow specifying different requirement for internal multisig txs
  packages/protocol/contracts/common/MultiSig.sol
  packages/protocol/test/common/multisig.ts
Labels: audit, automerge

#2914 [cli] Validator group reorder to first place
  packages/cli/src/commands/validatorgroup/member.ts
Labels: automerge

#2904 [N22] Not using EIP 1967: Standard Proxy Storage Slots
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/celotool/src/lib/genesis_constants.ts
  packages/protocol/contracts/common/Proxy.sol
Labels: audit, audit-fix, automerge

#2885 Move sorted oracles to fixidity
  packages/cli/src/commands/oracle/report.ts
  packages/contractkit/src/wrappers/SortedOracles.test.ts
  packages/contractkit/src/wrappers/SortedOracles.ts
  packages/docs/command-line-interface/oracle.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_sortedoracles_.sortedoracleswrapper.md
  packages/docs/developer-resources/contractkit/reference/enums/_wrappers_sortedoracles_.medianrelation.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_sortedoracles_.medianrate.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_sortedoracles_.oraclerate.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_sortedoracles_.sortedoraclesconfig.md
  packages/protocol/contracts/stability/SortedOracles.sol
  packages/protocol/contracts/stability/interfaces/ISortedOracles.sol
  packages/protocol/migrations/08_stabletoken.ts
  packages/protocol/scripts/truffle/set_exchange_rate.ts
  packages/protocol/test/stability/sortedoracles.ts
Labels: audit, automerge

#2756 Add prompt when registering validators or groups
  packages/cli/package.json
  packages/cli/src/commands/account/authorize.test.ts
  packages/cli/src/commands/validator/register.test.ts
  packages/cli/src/commands/validator/register.ts
  packages/cli/src/commands/validatorgroup/register.ts
  packages/cli/src/utils/cli.ts
  packages/docs/command-line-interface/validator.md
  packages/docs/command-line-interface/validatorgroup.md
  yarn.lock
Labels: automerge

#2931 [L06] Lack of validation may produce unexpected state in the distribution of epoch rewards
  packages/protocol/contracts/governance/Validators.sol
Labels: audit, audit-fix, automerge

#2941 [Wallet] Upgrade version to 1.6.1
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/assets/custom/LicenseDisclaimer.txt
  packages/mobile/android/gradle.properties
  packages/mobile/ios/celo-tvOS/Info.plist
  packages/mobile/ios/celo-tvOSTests/Info.plist
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/ios/celo/Info.plist
  packages/mobile/ios/celoTests/Info.plist
  packages/mobile/package.json
Labels: automerge

#2949 [Wallet] Fix iOS blocking view
  packages/mobile/ios/celo/AppDelegate.m
Labels: automerge

#2910 [protocol] add multisig to governance approver and reserve spender
  packages/celotool/src/e2e-tests/blockchain_parameters_tests.ts
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/celotool/src/e2e-tests/validator_order_tests.ts
  packages/cli/package.json
  packages/contractkit/package.json
  packages/contractkit/src/wrappers/Governance.ts
  packages/dev-utils/src/migration-override.json
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_governance_.governancewrapper.md
  packages/protocol/contracts/common/proxies/MultiSigProxy.sol
  packages/protocol/contracts/governance/GovernanceApproverMultiSig.sol
  packages/protocol/contracts/governance/proxies/GovernanceApproverMultiSigProxy.sol
  packages/protocol/contracts/stability/ReserveSpenderMultiSig.sol
  packages/protocol/contracts/stability/proxies/ReserveSpenderMultiSigProxy.sol
  packages/protocol/lib/registry-utils.ts
  packages/protocol/lib/web3-utils.ts
  packages/protocol/migrations/07_reserve_spender_multisig.ts
  packages/protocol/migrations/08_reserve.ts
  packages/protocol/migrations/09_stabletoken.ts
  packages/protocol/migrations/10_exchange.ts
  packages/protocol/migrations/11_accounts.ts
  packages/protocol/migrations/12_lockedgold.ts
  packages/protocol/migrations/13_validators.ts
  packages/protocol/migrations/14_election.ts
  packages/protocol/migrations/15_epoch_rewards.ts
  packages/protocol/migrations/16_random.ts
  packages/protocol/migrations/17_attestations.ts
  packages/protocol/migrations/18_escrow.ts
  packages/protocol/migrations/19_blockchainparams.ts
  packages/protocol/migrations/20_governance_slasher.ts
  packages/protocol/migrations/21_double_signing_slasher.ts
  packages/protocol/migrations/22_downtime_slasher.ts
  packages/protocol/migrations/23_governance_approver_multisig.ts
  packages/protocol/migrations/24_governance.ts
  packages/protocol/migrations/25_elect_validators.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/runTests.js
  packages/protocol/scripts/build.ts
  packages/protocol/test/common/integration.ts
Labels: audit

#2906 [M12] There is no security policy
  SECURITY.md
Labels: audit, audit-fix

#2877 [M10] Not using OpenZeppelin contracts
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/protocol/contracts/common/Accounts.sol
  packages/protocol/contracts/common/GoldToken.sol
  packages/protocol/contracts/common/MultiSig.sol
  packages/protocol/contracts/common/Proxy.sol
  packages/protocol/contracts/common/SafeCast.sol
  packages/protocol/contracts/common/SafeCastTest.sol
  packages/protocol/contracts/common/Signatures.sol
  packages/protocol/contracts/common/UsingRegistry.sol
  packages/protocol/contracts/common/interfaces/IERC20Token.sol
  packages/protocol/contracts/common/libraries/AddressesHelper.sol
  packages/protocol/contracts/common/libraries/ReentrancyGuard.sol
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/governance/LockedGold.sol
  packages/protocol/contracts/governance/Proposals.sol
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/contracts/identity/Attestations.sol
  packages/protocol/contracts/identity/Escrow.sol
  packages/protocol/contracts/stability/Exchange.sol
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/contracts/stability/StableToken.sol
  packages/protocol/contracts/stability/test/MockReserve.sol
  packages/protocol/migrationsConfig.js
  packages/protocol/package.json
  packages/protocol/test/common/safecast.ts
  yarn.lock
Labels: audit, audit-fix

#2705 Monorepo changes for geth 1.9
  packages/celotool/src/cmds/geth/run.ts
  packages/celotool/src/e2e-tests/utils.ts
  packages/celotool/src/lib/genesis_constants.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/helm-charts/testnet/templates/_helpers.tpl
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
Labels: automerge

#2948 Wallet design polish
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/src/account/Account.tsx
  packages/mobile/src/account/__snapshots__/Account.test.tsx.snap
  packages/mobile/src/components/Carousel.tsx
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentListItem.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentReminderSummaryNotification.test.tsx.snap
  packages/mobile/src/home/__snapshots__/NotificationBox.test.tsx.snap
  packages/mobile/src/notifications/__snapshots__/SimpleNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestSummaryNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestSummaryNotification.test.tsx.snap
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationLoadingScreen.test.tsx.snap
  packages/react-components/components/BaseNotification.tsx
  packages/react-components/components/__snapshots__/BaseNotification.test.tsx.snap
  packages/react-components/jest_setup.js
  packages/react-components/services/ReactNativeLogger.ts
  yarn.lock
Labels: automerge

#2874 Animate Line + some minor cleanup
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/brandkit/common/Page.tsx
  packages/web/src/brandkit/common/TopBar.tsx
  packages/web/src/react-native-aug.d.ts
  packages/web/src/shared/Button.3.tsx
  packages/web/src/shared/Footer.tsx
Labels: automerge

#2913 [H02] Commissions can deceive members of a validator group
  packages/celotool/src/lib/migration-utils.ts
  packages/cli/src/commands/validatorgroup/commission.test.ts
  packages/cli/src/commands/validatorgroup/commission.ts
  packages/cli/src/utils/checks.ts
  packages/contractkit/src/wrappers/BaseWrapper.ts
  packages/contractkit/src/wrappers/Validators.test.ts
  packages/contractkit/src/wrappers/Validators.ts
  packages/dev-utils/src/ganache-test.ts
  packages/dev-utils/src/migration-override.json
  packages/docs/command-line-interface/validatorgroup.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_accounts_.accountswrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_attestations_.attestationswrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_basewrapper_.basewrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_basewrapper_.celotransactionobject.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_blockchainparameters_.blockchainparameterswrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_doublesigningslasher_.doublesigningslasherwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_downtimeslasher_.downtimeslasherwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_election_.electionwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_escrow_.escrowwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_exchange_.exchangewrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_gaspriceminimum_.gaspriceminimumwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_goldtokenwrapper_.goldtokenwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_governance_.governancewrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_lockedgold_.lockedgoldwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_reserve_.reservewrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_sortedoracles_.sortedoracleswrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_stabletokenwrapper_.stabletokenwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_validators_.validatorswrapper.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_validators_.groupmembership.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_validators_.lockedgoldrequirements.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_validators_.membershiphistoryextradata.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_validators_.validator.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_validators_.validatorgroup.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_validators_.validatorreward.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_validators_.validatorsconfig.md
  packages/docs/developer-resources/contractkit/reference/modules/_wrappers_basewrapper_.md
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/migrations/13_validators.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/test/governance/validators.ts
Labels: audit, audit-fix

#2924 🌏 Change the Story
  packages/web/jest.config.js
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/brandkit/KeyImagery.tsx
  packages/web/src/dev/Engage.tsx
  packages/web/src/layout/ScreenSize.tsx
  packages/web/src/shared/ChangeStory.tsx
  packages/web/src/shared/Footer.tsx
  packages/web/src/shared/world-spin.gif
Labels: automerge

#2403 Geo-Blacklist Announcements
  packages/web/server-env-config.js.enc
  packages/web/server/Announcement.ts
  packages/web/server/announcement.test.ts
  packages/web/server/geoip.ts
  packages/web/server/index.ts
  packages/web/src/_page-tests/__snapshots__/privacy.test.tsx.snap
  packages/web/src/privacy/Privacy.tsx
Labels: automerge

#2927 Allow ReleaseGoldInstance beneficiary to transfer beneficiary
  packages/protocol/contracts/governance/ReleaseGoldInstance.sol
  packages/protocol/test/governance/release_gold.ts
Labels: audit

#2926 [M06] Prove control of walletAddress
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/cli/src/commands/account/proof-of-possession.ts
  packages/contractkit/src/wrappers/Accounts.test.ts
  packages/contractkit/src/wrappers/Accounts.ts
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_accounts_.accountswrapper.md
  packages/protocol/contracts/common/Accounts.sol
  packages/protocol/contracts/common/interfaces/IAccounts.sol
  packages/protocol/contracts/governance/ReleaseGoldInstance.sol
  packages/protocol/contracts/governance/interfaces/IReleaseGoldInstance.sol
  packages/protocol/test/common/accounts.ts
  packages/protocol/test/governance/release_gold.ts
  packages/protocol/test/identity/attestations.ts
Labels: audit, audit-fix

#2956 [N07] Add docs about SIM swaps
  packages/docs/celo-codebase/protocol/identity/README.md
Labels: audit, audit-fix

#2946 Add asset allocations to Reserve.initialize
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/contracts/stability/interfaces/IReserve.sol
  packages/protocol/migrations/08_reserve.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/test/governance/epochrewards.ts
  packages/protocol/test/stability/reserve.ts
Labels: audit

#2925 Release Gold migration script
  packages/protocol/contracts/governance/ReleaseGold.sol
  packages/protocol/contracts/governance/ReleaseGoldFactory.sol
  packages/protocol/contracts/governance/ReleaseGoldMultiSig.sol
  packages/protocol/contracts/governance/interfaces/IReleaseGold.sol
  packages/protocol/contracts/governance/interfaces/IReleaseGoldFactory.sol
  packages/protocol/contracts/governance/proxies/ReleaseGoldMultiSigProxy.sol
  packages/protocol/contracts/governance/proxies/ReleaseGoldProxy.sol
  packages/protocol/lib/registry-utils.ts
  packages/protocol/lib/web3-utils.ts
  packages/protocol/scripts/bash/deploy_release_contracts.sh
  packages/protocol/scripts/build.ts
  packages/protocol/scripts/truffle/deploy_release_contracts.ts
  packages/protocol/scripts/truffle/releaseGoldContracts.json
  packages/protocol/test/governance/release_gold.ts
Labels: audit

#2881 Adjust migrations for mainnet, make freezability governable
  .circleci/config.yml
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/celotool/src/e2e-tests/slashing_tests.ts
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/celotool/src/e2e-tests/utils.ts
  packages/dev-utils/src/ganache-setup.ts
  packages/dev-utils/src/migration-override.json
  packages/protocol/contracts/baklava/Freezable.sol
  packages/protocol/contracts/baklava/test/FreezableTest.sol
  packages/protocol/contracts/common/Freezable.sol
  packages/protocol/contracts/common/Freezer.sol
  packages/protocol/contracts/common/GoldToken.sol
  packages/protocol/contracts/common/UsingRegistry.sol
  packages/protocol/contracts/common/interfaces/IFreezer.sol
  packages/protocol/contracts/common/proxies/FreezerProxy.sol
  packages/protocol/contracts/governance/EpochRewards.sol
  packages/protocol/contracts/stability/Exchange.sol
  packages/protocol/contracts/stability/StableToken.sol
  packages/protocol/contracts/stability/interfaces/IExchange.sol
  packages/protocol/lib/registry-utils.ts
  packages/protocol/lib/test-utils.ts
  packages/protocol/migrations/03_freezer.ts
  packages/protocol/migrations/04_goldtoken.ts
  packages/protocol/migrations/08_reserve.ts
  packages/protocol/migrations/09_stabletoken.ts
  packages/protocol/migrations/10_exchange.ts
  packages/protocol/migrations/15_epoch_rewards.ts
  packages/protocol/migrations/24_governance.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/package.json
  packages/protocol/runTests.js
  packages/protocol/scripts/bash/network_check.sh
  packages/protocol/scripts/truffle/network_check.ts
  packages/protocol/test/baklava/freezable.ts
  packages/protocol/test/common/goldtoken.ts
  packages/protocol/test/common/integration.ts
  packages/protocol/test/common/migration.ts
  packages/protocol/test/governance/epochrewards.ts
  packages/protocol/test/governance/release_gold.ts
  packages/protocol/test/stability/exchange.ts
  packages/protocol/test/stability/stabletoken.ts
Labels: audit

#2959 [L19] Expand explanation of properties of signer keys
  packages/docs/operations-manual/key-management.md
Labels: audit-fix, automerge, docs

#2960 Fix transfer e2e tests
  packages/celotool/src/e2e-tests/utils.ts
Labels: automerge

#2794 [M05] Missing counter addition
  packages/protocol/contracts/identity/Attestations.sol
  packages/protocol/contracts/identity/Escrow.sol
  packages/protocol/contracts/identity/interfaces/IAttestations.sol
  packages/protocol/contracts/identity/test/MockAttestations.sol
  packages/protocol/migrations/17_attestations.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/test/identity/attestations.ts
Labels: audit, audit-fix, automerge

#2781 Elect validators optimization
  packages/protocol/contracts/common/libraries/Heap.sol
  packages/protocol/contracts/common/test/HeapTest.sol
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/test/common/heap.ts
  packages/protocol/test/governance/election.ts
Labels: audit, automerge

#2805 [M02] Functions in StableToken do not emit Transfer event
  .circleci/config.yml
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/protocol/contracts/stability/StableToken.sol
  packages/protocol/contracts/stability/interfaces/IStableToken.sol
Labels: audit, audit-fix, automerge

#2964 Added --proxy.allowprivateip to validators opts for k8s testnet
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
Labels: automerge

#2953 Add TransferWhitelist contract
  packages/protocol/contracts/common/TransferWhitelist.sol
  packages/protocol/contracts/governance/LockedGold.sol
  packages/protocol/contracts/governance/ReleaseGold.sol
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/contracts/stability/interfaces/IReserve.sol
  packages/protocol/migrations/03_transferwhitelist.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/runTests.js
  packages/protocol/test/common/transferwhitelist.ts
  packages/protocol/test/stability/reserve.ts
Labels: audit

#2947 Remove codecov for protocol until coverage working again
  .codecov.yml
Labels: automerge

#2987 Fix PIN code on enabling Forno mode
  packages/mobile/src/app/Background.tsx
  packages/mobile/src/pincode/PincodeConfirmation.tsx
Labels: automerge

#2976 Fix report issue on iOS
  packages/mobile/src/account/Account.tsx
  packages/mobile/src/utils/Logger.ts
Labels: automerge

#2880 Add custody docs
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/integrations/custody.md
  packages/docs/developer-resources/integrations/general.md
  packages/docs/developer-resources/integrations/integrations.md
  packages/docs/developer-resources/walkthroughs/hellocontracts.md
Labels: automerge

#2962 Deploy/upgrade testnet with existing genesis file
  packages/celotool/src/cmds/deploy/initial/testnet.ts
  packages/celotool/src/cmds/deploy/initial/vm-testnet.ts
  packages/celotool/src/cmds/deploy/migrate/blockscout.ts
  packages/celotool/src/cmds/deploy/upgrade/all.ts
  packages/celotool/src/cmds/deploy/upgrade/testnet.ts
  packages/celotool/src/cmds/deploy/upgrade/vm-testnet.ts
  packages/celotool/src/cmds/geth/run.ts
  packages/celotool/src/lib/attestation-service.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/celotool/src/lib/load-test.ts
  packages/celotool/src/lib/testnet-utils.ts
  packages/celotool/src/lib/vm-testnet-utils.ts
  packages/helm-charts/testnet/scripts/create-network.sh
  packages/helm-charts/testnet/templates/_helpers.tpl
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
  packages/terraform-modules-public/testnet/modules/tx-node/startup.sh
  packages/terraform-modules/testnet/modules/full-node/startup.sh
Labels: automerge

#2995 TGSCO--Final board
  packages/web/public/static/locales/en/dev.json
  packages/web/src/_page-tests/validators/__snapshots__/index.test.tsx.snap
  packages/web/src/dev/Cover.tsx
  packages/web/src/dev/LeaderBoard.tsx
  packages/web/src/dev/tgsco-final.json
Labels: automerge

#2999 Fix Twitter Link
  packages/web/src/_page-tests/__snapshots__/community.test.tsx.snap
  packages/web/src/_page-tests/developers/__snapshots__/Index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/_page-tests/validators/__snapshots__/index.test.tsx.snap
  packages/web/src/icons/TwitterLogo.tsx
  packages/web/src/shared/SocialChannels.tsx
  packages/web/src/shared/menu-items.ts
Labels: automerge

#3002 update celoHQ to celoOrg
  packages/web/server/mediumAPI.ts
  packages/web/src/_page-tests/__snapshots__/about.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/community.test.tsx.snap
  packages/web/src/_page-tests/developers/__snapshots__/Index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/_page-tests/validators/__snapshots__/index.test.tsx.snap
  packages/web/src/about/About.tsx
  packages/web/src/brandkit/Typography.tsx
  packages/web/src/community/connect/ArticlesSection.tsx
  packages/web/src/community/connect/Contribute.tsx
  packages/web/src/dev/Engage.tsx
  packages/web/src/icons/MediumLogo.tsx
  packages/web/src/press/Press.tsx
  packages/web/src/shared/ConnectionFooter.tsx
  packages/web/src/shared/menu-items.ts
Labels: automerge
