Repository celo-org/celo-monorepo, pull requests merged in 2020-09, with the labels that each got.

#4904 [Wallet] Fix linking errors on iOS with latest @celo/client and release builds
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/xcshareddata/xcschemes/celo-alfajores.xcscheme
  packages/mobile/ios/celo.xcodeproj/xcshareddata/xcschemes/celo-dev.xcscheme
  packages/mobile/ios/celo.xcodeproj/xcshareddata/xcschemes/celo-integration.xcscheme
  packages/mobile/ios/celo.xcodeproj/xcshareddata/xcschemes/celo-mainnet.xcscheme
  packages/mobile/ios/celo.xcodeproj/xcshareddata/xcschemes/celo-pilot.xcscheme
Labels: automerge, wallet

#4903 [Wallet] Add daily limit to CELO withdrawals
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/exchange/WithdrawCeloScreen.tsx
  packages/mobile/src/exchange/__snapshots__/WithdrawCeloScreen.test.tsx.snap
  packages/mobile/src/exchange/saga.ts
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.test.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeAmount.tsx
  packages/mobile/src/send/SendAmount.test.tsx
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/utils.test.ts
  packages/mobile/src/send/utils.ts
Labels: automerge, wallet

#4909 Fix changes that lead account:get-metadata to fail
  packages/attestation-service/src/requestHandlers/status.ts
  packages/contractkit/src/wrappers/Attestations.ts
  packages/utils/src/io.ts
Labels: automerge

#4930 Upgrade oracles to use Coinbase Pro
  .env.baklava
  .env.rc1
  packages/helm-charts/oracle/values.yaml
Labels: automerge

#4931 [Wallet] Only paste addresses on Withdraw CELO flow
  packages/mobile/src/account/utils.ts
  packages/mobile/src/components/ClipboardAwarePasteIcon.tsx
  packages/mobile/src/exchange/WithdrawCeloScreen.tsx
Labels: automerge

#4872 [Wallet] Reorganize and add e2e tests
  packages/mobile/e2e/README.md
  packages/mobile/e2e/TestsRunner.spec.js
  packages/mobile/e2e/Transfer.spec.js
  packages/mobile/e2e/src/Onboarding.js
  packages/mobile/e2e/src/ResetAccount.js
  packages/mobile/e2e/src/Send.js
  packages/mobile/e2e/src/Withdraw.js
  packages/mobile/e2e/src/utils/banners.js
  packages/mobile/e2e/src/utils/consts.js
  packages/mobile/e2e/src/utils/utils.js
  packages/mobile/scripts/run_e2e.sh
  packages/mobile/src/account/Settings.tsx
  packages/mobile/src/account/__snapshots__/Settings.test.tsx.snap
  packages/mobile/src/account/saga.ts
  packages/mobile/src/backup/BackupPhrase.tsx
  packages/mobile/src/backup/BackupQuiz.tsx
  packages/mobile/src/backup/__snapshots__/BackupPhrase.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupQuiz.test.tsx.snap
Labels: automerge, wallet

#4793 Dappkit Redesign
  packages/mobile/locales/en-US/dappkit.json
  packages/mobile/locales/es-419/dappkit.json
  packages/mobile/src/dappkit/DappKitAccountScreen.tsx
  packages/mobile/src/dappkit/DappKitSignTxScreen.tsx
  packages/mobile/src/dappkit/DappKitTxDataScreen.tsx
Labels: automerge, wallet, wallet-redesign

#4805 Prevent accidental rotation of ECDSA validator key without BLS key
  packages/cli/src/commands/account/authorize.test.ts
  packages/cli/src/commands/account/authorize.ts
  packages/cli/src/commands/governance/propose.ts
  packages/cli/src/commands/lockedgold/lock.ts
  packages/cli/src/commands/releasegold/authorize.test.ts
  packages/cli/src/commands/releasegold/authorize.ts
  packages/cli/src/commands/releasegold/locked-gold.ts
  packages/cli/src/commands/transfer/celo.ts
  packages/cli/src/commands/validator/update-bls-public-key.ts
  packages/cli/src/utils/checks.ts
  packages/docs/command-line-interface/account.md
  packages/docs/command-line-interface/validator.md
Labels: automerge

#4920 [Wallet] Split doVerification saga and UI changes to verification
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/src/app/selectors.ts
  packages/mobile/src/config.ts
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/home/__snapshots__/NotificationBox.test.tsx.snap
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/saga.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/import/saga.ts
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/send/Send.tsx
  packages/mobile/src/verify/VerificationEducationScreen.test.tsx
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.test.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
  packages/mobile/test/schemas.ts
  packages/mobile/test/values.ts
Labels: automerge

#4938 update TOS Link to be a parameter from brandingConfig
  packages/mobile/locales/en-US/nuxNamePin1.json
  packages/mobile/locales/es-419/nuxNamePin1.json
  packages/mobile/scripts/sync_branding.sh
  packages/mobile/src/i18n.ts
Labels: automerge

#4762 ODIS Docs
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/contractkit/README.md
  packages/docs/developer-resources/contractkit/data-encryption-key.md
  packages/docs/developer-resources/contractkit/odis.md
Labels: automerge

#4949 fixes cli tests
  packages/cli/src/commands/account/authorize.test.ts
Labels: automerge

#4933 update code of conduct
  packages/web/src/content/code-of-conduct.md
Labels: automerge

#4925 Display articles in all user languages on Press page
  packages/web/src/press/PressPage.tsx
  packages/web/src/utils/languages.ts
Labels: automerge

#4945 Add Copy Fixes to Spanish per requested typos
  packages/mobile/fastlane/metadata/android/es-419/full_description.txt
  packages/mobile/locales/es-419/accountScreen10.json
  packages/mobile/locales/es-419/backupKeyFlow6.json
  packages/mobile/locales/es-419/exchangeFlow9.json
  packages/mobile/locales/es-419/fiatExchangeFlow.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/es-419/nuxNamePin1.json
  packages/mobile/locales/es-419/nuxRestoreWallet3.json
  packages/mobile/locales/es-419/nuxVerification2.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/locales/es-419/paymentRequestFlow.json
  packages/mobile/locales/es-419/sendFlow7.json
  packages/mobile/locales/es-419/walletFlow5.json
Labels: automerge, wallet

#4956 [Wallet] Send Amount Loading Spinner pt 2
  packages/mobile/src/send/SendAmount.test.tsx
  packages/mobile/src/send/SendAmount.tsx
Labels: automerge, wallet

#4932 [Wallet] Build number changes from 1.0.1 release
  packages/mobile/android/app/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/fastlane/Fastfile
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/ios/celo/Info.plist
Labels: automerge, wallet

#4918 [cli,contractkit] improvements to identity/current-attestation-services
  packages/cli/src/commands/identity/current-attestation-services.ts
  packages/contractkit/src/wrappers/Attestations.ts
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_attestations_.attestationswrapper.md
  packages/docs/developer-resources/contractkit/reference/enums/_wrappers_attestations_.attestationservicestatusstate.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.attestationservicestatusresponse.md
  packages/docs/developer-resources/contractkit/reference/modules/_wrappers_attestations_.md
Labels: automerge

#4680 Mobile discovery
  packages/mobile/.env
  packages/mobile/.env.alfajores
  packages/mobile/.env.integration
  packages/mobile/.env.mainnet
  packages/mobile/.env.pilot
  packages/mobile/.env.test
  packages/mobile/README.md
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/src/config.ts
  packages/mobile/src/geth/geth.ts
  packages/mobile/src/geth/networkConfig.ts
  packages/mobile/src/geth/saga.test.ts
  yarn.lock
Labels: automerge

#4927 [Wallet] Fix blank license screen on iOS (take 2)
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/src/account/Licenses.tsx
  packages/mobile/src/account/__snapshots__/Licenses.test.tsx.snap
  yarn.lock
Labels: automerge, wallet

#4719 Aaronmgdr/enable modern on reserve site
  packages/reserve-site/next.config.js
Labels: automerge

#4955 Changed to google analytics
  packages/web/package.json
  packages/web/pages/_app.tsx
  packages/web/src/analytics/analytics.test.ts
  packages/web/src/analytics/analytics.ts
  packages/web/src/experience/brandkit/tracking.ts
  packages/web/src/experience/eventkit/tracking.ts
  yarn.lock
Labels: automerge

#4959 add GA KEY ; remove segment
  packages/web/env-config.js.enc
Labels: automerge

#4922 Fix group attestation scores
  packages/web/src/dev/ValidatorsList.tsx
Labels: automerge

#4967 Use new celo-blockchain build in mobile for 64 bit fix
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  yarn.lock
Labels: automerge

#4974 Base->0.0.3-dev,Utils->0.1.20-dev,CK->0.4.14-dev,cli->0.0.57-dev
  packages/attestation-service/package.json
  packages/base/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/metadata-crawler/package.json
  packages/mobile/package.json
  packages/phone-number-privacy/common/package.json
  packages/protocol/package.json
  packages/react-components/package.json
  packages/utils/package.json
Labels: automerge

#4943 make attestation wrapper selectIssuers throw error on timeout
  packages/celotool/src/e2e-tests/attestations_tests.ts
  packages/celotool/src/lib/attestation.ts
  packages/contractkit/src/wrappers/Attestations.ts
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_attestations_.attestationswrapper.md
  packages/docs/developer-resources/contractkit/reference/enums/_wrappers_attestations_.attestationservicestatusstate.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.attestationservicestatusresponse.md
Labels: automerge

#4973 [Wallet] Payment requests must use lowercase addresses
  packages/mobile/src/paymentRequest/PaymentRequestConfirmation.tsx
  packages/mobile/src/recipients/RecipientItem.tsx
Labels: automerge, wallet

#4897 Update attestation service to v1.0.3
  packages/terraform-modules-public/gcp/example/variables.tf
  packages/terraform-modules-public/gcp/testnet/main.tf
  packages/terraform-modules-public/gcp/testnet/modules/attestation-service/main.tf
  packages/terraform-modules-public/gcp/testnet/modules/attestation-service/startup.sh
  packages/terraform-modules-public/gcp/testnet/modules/attestation-service/variables.tf
  packages/terraform-modules-public/gcp/testnet/variables.tf
Labels: automerge

#4969 Add Coinbase Earn page to Celo.org
  packages/web/pages/coinbase-earn.tsx
  packages/web/public/static/locales/en/cbe.json
  packages/web/src/_page-tests/__snapshots__/cbe.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/cbe.test.tsx
  packages/web/src/coinbase-earn/Cover.tsx
  packages/web/src/coinbase-earn/Landing.tsx
  packages/web/src/coinbase-earn/Learn_Light.png
  packages/web/src/coinbase-earn/hero-mobile.png
  packages/web/src/coinbase-earn/hero.png
  packages/web/src/coinbase-earn/lesson1.jpg
  packages/web/src/coinbase-earn/lesson2.jpg
  packages/web/src/coinbase-earn/lesson3.jpg
  packages/web/src/header/Header.3.tsx
  packages/web/src/home/Adventure.tsx
  packages/web/src/home/HomeBenefits.tsx
  packages/web/src/i18n.ts
  packages/web/src/icons/valora-icon.png
  packages/web/src/shared/menu-items.ts
Labels: automerge

#4971 upgrade i18n lib for celo.org
  packages/web/package.json
  packages/web/public/static/locales/en/applications.json
  packages/web/public/static/locales/en/technology.json
  packages/web/server/index.ts
  packages/web/src/fauceting/PhoneInput.test.tsx
  packages/web/src/i18n.ts
  packages/web/src/utils/i18nForTests.ts
  yarn.lock
Labels: automerge

#4979 [Wallet] Fix payment request comments decryption
  packages/mobile/src/paymentRequest/saga.ts
  packages/mobile/src/paymentRequest/utils.test.ts
  packages/mobile/src/paymentRequest/utils.ts
  packages/mobile/src/recipients/RecipientItem.tsx
  packages/mobile/src/recipients/RecipientPicker.tsx
Labels: automerge, wallet

#4985 Removes css processors we dont need
  packages/web/.babelrc
  packages/web/package.json
  yarn.lock
Labels: automerge

#4987 removes Timeline from celo.org.
  packages/web/public/static/locales/en/home.json
  packages/web/src/_page-tests/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/index.test.tsx
  packages/web/src/home/Home.tsx
Labels: automerge

#4982 [Wallet] Fix incorrect verification screen buttons in some cases
  packages/mobile/src/app/selectors.ts
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/privateHashing.test.ts
  packages/mobile/src/identity/privateHashing.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/verify/VerificationEducationScreen.test.tsx
  packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
  packages/mobile/test/schemas.ts
  packages/mobile/test/values.ts
Labels: automerge, wallet

#4977 [Wallet] Fix bug to allow users to skip invite redemption after canceling
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/invite/EnterInviteCode.tsx
  packages/mobile/src/invite/__snapshots__/EnterInviteCode.test.tsx.snap
  packages/mobile/src/invite/actions.ts
  packages/mobile/src/invite/reducer.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/invite/utils.test.ts
  packages/mobile/src/invite/utils.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/test/schemas.ts
Labels: automerge, wallet

#4990 [Wallet] Send attestation messages sequentially on Android
  packages/mobile/.env
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
Labels: automerge, wallet

#5000 [Wallet] Fix user seeing the enter invite code screen after upgrading to 1.1.0
  packages/mobile/src/invite/saga.test.ts
  packages/mobile/src/invite/saga.ts
Labels: automerge

#5002 [Wallet] Add migration to set redeemComplete to true if account exists
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/store.ts
Labels: automerge, wallet

#4991 AWS Terraform: Support attestation service 1.0.3
  packages/terraform-modules-public/aws/examples/mainnet/main.tf
  packages/terraform-modules-public/aws/examples/mainnet/variables.tf
  packages/terraform-modules-public/aws/examples/testnet/main.tf
  packages/terraform-modules-public/aws/examples/testnet/variables.tf
  packages/terraform-modules-public/aws/testnet/main.tf
  packages/terraform-modules-public/aws/testnet/modules/attestation-service/main.tf
  packages/terraform-modules-public/aws/testnet/modules/attestation-service/variables.tf
  packages/terraform-modules-public/aws/testnet/modules/startup-scripts/run-attestation-service.sh
  packages/terraform-modules-public/aws/testnet/variables.tf
Labels: automerge

#5016 Add yarn resolution for `bl` because of security vulnerability
  package.json
  yarn.lock
Labels: automerge

#4963 [Attestation Service] Default unsupported geos
  packages/attestation-service/config/.env.development
Labels: automerge

#5012 [Wallet] Fix SendAmount Activity Indicator bug
  packages/mobile/src/send/SendAmount.test.tsx
  packages/mobile/src/send/SendAmount.tsx
Labels: automerge, wallet

#4976 Adds ODIS identifier query to celocli
  packages/cli/package.json
  packages/cli/src/commands/identity/identifier.ts
  packages/cli/src/utils/checks.ts
  packages/contractkit/src/identity/odis/bls-blinding-client.ts
  packages/contractkit/src/identity/odis/query.ts
  packages/contractkit/src/wrappers/Validators.test.ts
  packages/docs/command-line-interface/identity.md
  packages/docs/developer-resources/contractkit/reference/classes/_identity_odis_bls_blinding_client_.wasmblsblindingclient.md
  packages/docs/developer-resources/contractkit/reference/modules/_identity_odis_query_.md
  packages/mobile/__mocks__/@celo/contractkit/index.ts
  packages/mobile/src/geth/networkConfig.ts
  packages/mobile/src/identity/matchmaking.test.ts
  packages/mobile/src/identity/privateHashing.test.ts
Labels: automerge

#5024 Increment dappkit version to 0.10.0
  packages/dappkit/package.json
Labels: automerge

#5028 [Wallet] Add link to additional funding options
  packages/mobile/branding/celo/src/brandingConfig.ts
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/locales/es-419/fiatExchangeFlow.json
  packages/mobile/scripts/sync_branding.sh
  packages/mobile/src/account/FiatExchange.tsx
  packages/mobile/src/account/__snapshots__/FiatExchange.test.tsx.snap
Labels: automerge, wallet

#5037 [Wallet] Add BRL and CVE local currencies
  packages/mobile/src/localCurrency/__snapshots__/SelectLocalCurrency.test.tsx.snap
  packages/mobile/src/localCurrency/consts.ts
Labels: automerge

#5039 [Wallet] Fix escrow failing randomly with local currency
  packages/mobile/.env
  packages/mobile/.env.alfajores
  packages/mobile/src/localCurrency/convert.test.ts
  packages/mobile/src/localCurrency/convert.ts
  packages/mobile/src/send/SendAmount.test.tsx
Labels: automerge, wallet

#4912 Attestations Service: Support Nexmo applications
  packages/attestation-service/config/.env.development
  packages/attestation-service/package.json
  packages/attestation-service/src/sms/nexmo.ts
  packages/docs/operations-manual/attestation-service.md
Labels: automerge

#5063 Fix getting languages on Press page for client side
  packages/web/src/press/PressPage.tsx
Labels: automerge

#4951 [Wallet] Ability to send events from native ios to react
  packages/mobile/android/app/src/main/java/org/celo/mobile/MainActivity.java
  packages/mobile/ios/AnalyticsManager.h
  packages/mobile/ios/AnalyticsManager.m
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/src/app/App.tsx
Labels: wallet

#5075 Revert "[Wallet] Ability to send events from native ios to react"
  packages/mobile/android/app/src/main/java/org/celo/mobile/MainActivity.java
  packages/mobile/ios/AnalyticsManager.h
  packages/mobile/ios/AnalyticsManager.m
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/src/app/App.tsx
Labels: automerge, wallet

#5062 [Wallet] Fix unable to send transactions after upgrading to 1.1.0 on Android (internal)
  packages/mobile/package.json
  yarn.lock
Labels: automerge

#5071 Migrate authentication logic and export test methods
  dependency-graph.json
  packages/phone-number-privacy/combiner/test/end-to-end/get-blinded-sig.test.ts
  packages/phone-number-privacy/combiner/test/end-to-end/resources.ts
  packages/phone-number-privacy/common/package.json
  packages/phone-number-privacy/common/src/index.ts
  packages/phone-number-privacy/common/src/test/index.ts
  packages/phone-number-privacy/common/src/test/utils.ts
  packages/phone-number-privacy/common/src/test/values.ts
  packages/phone-number-privacy/common/src/utils/authentication.ts
  packages/phone-number-privacy/common/src/utils/logger.ts
  packages/phone-number-privacy/signer/test/end-to-end/get-blinded-sig.test.ts
  packages/phone-number-privacy/signer/test/signing/query-quota.test.ts
Labels: automerge

#5088 Adds Twilio support to atttestation service helm charts
  .env.alfajores
  .env.alfajoresstaging
  packages/helm-charts/attestation-service/templates/attestation.statefulset.yaml
  packages/helm-charts/cert-manager-cluster-issuers/requirements.lock
  packages/protocol/truffle-config.js
Labels: automerge

#5090 [Wallet] Bug fix for QR scan of Secure Send
  packages/mobile/src/qrcode/utils.ts
  packages/mobile/src/send/saga.test.ts
Labels: automerge, wallet

#5076 [Wallet] Log app load time using props instead of events
  packages/mobile/android/app/src/main/java/org/celo/mobile/MainActivity.java
  packages/mobile/ios/celo/AppDelegate.m
  packages/mobile/src/app/App.tsx
Labels: automerge, wallet

#5027 Use Modern JS Option on Celo.org
  packages/web/next.config.js
Labels: automerge

#5092 [Wallet] Fixing fatal error when escrow gas estimation fails
  packages/mobile/src/fees/CalculateFee.tsx
Labels: automerge, wallet

#5042 [Wallet] Remove fee calculation for CELO withdrawals
  packages/mobile/src/exchange/WithdrawCeloSummary.tsx
  packages/mobile/src/exchange/__snapshots__/WithdrawCeloReviewScreen.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/WithdrawCeloSummary.test.tsx.snap
Labels: automerge, wallet

#4964 Fix _getBuyAndSellBuckets comment in Exchange.sol
  packages/protocol/contracts/stability/Exchange.sol
Labels: automerge

#5100 [Web] Fix minor bugs on celo.org
  packages/web/pages/_app.tsx
  packages/web/pages/_document.tsx
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/exchange-icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/home/Home.tsx
  packages/web/src/shared/Footer.tsx
  packages/web/src/shared/Progress.tsx
  packages/web/src/shared/__snapshots__/Footer.test.tsx.snap
Labels: automerge

#5046 [Wallet] Withdraw art
  packages/mobile/branding/celo/src/images/fiat-exchange.png
  packages/mobile/src/account/FiatExchange.tsx
  packages/mobile/src/account/__snapshots__/FiatExchange.test.tsx.snap
  packages/mobile/src/images/Images.ts
Labels: wallet, wallet-redesign

#5043 upgrade React-native-web to 13
  packages/web/package.json
  packages/web/src/_page-tests/__snapshots__/_error.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/about.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/alliance.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/audits.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/cbe.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/code-of-conduct.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/community.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/faq.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/jobs.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/papers.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/past-events.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/privacy.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/terms.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/user-agreement.test.tsx.snap
  packages/web/src/_page-tests/developers/__snapshots__/Index.test.tsx.snap
  packages/web/src/_page-tests/developers/__snapshots__/faucet.test.tsx.snap
  packages/web/src/_page-tests/developers/__snapshots__/wallet.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/exchange-icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/_page-tests/stake-off/__snapshots__/terms.test.tsx.snap
  packages/web/src/_page-tests/test-utils.tsx
  packages/web/src/_page-tests/validators/__snapshots__/explore.test.tsx.snap
  packages/web/src/_page-tests/validators/__snapshots__/index.test.tsx.snap
  packages/web/src/about/VideoCover.tsx
  packages/web/src/community/connect/FellowshipForm.test.tsx
  packages/web/src/dev/ValidatorsList.tsx
  packages/web/src/dev/ValidatorsListRow.tsx
  packages/web/src/experience/common/MobileKitMenu.test.tsx
  packages/web/src/fauceting/PhoneInput.test.tsx
  packages/web/src/forms/CheckboxWithLabel.tsx
  packages/web/src/forms/EmailForm.test.tsx
  packages/web/src/forms/EmailForm.tsx
  packages/web/src/forms/Form.tsx
  packages/web/src/forms/FormComponents.tsx
  packages/web/src/forms/LabeledInput.tsx
  packages/web/src/home/HomeAnimation.tsx
  packages/web/src/shared/AspectRatio.tsx
  packages/web/src/shared/__snapshots__/Footer.test.tsx.snap
  packages/web/src/shared/__snapshots__/MobileMenu.test.tsx.snap
  packages/web/src/shared/svg.tsx
  yarn.lock
Labels: automerge

#5114 revert trying modern. came across some breakages that i missed before
  packages/web/next.config.js
Labels: automerge

#5101 adds nexmo applications to attestations-service helm chart
  .env.alfajores
  .env.alfajoresstaging
  packages/celotool/src/lib/attestation-service.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/helm-charts/attestation-service/templates/attestation.statefulset.yaml
Labels: automerge

#5108 Bring FAQ to Contentful
  packages/web/pages/faq.tsx
  packages/web/src/_page-tests/__snapshots__/faq.test.tsx.snap
  packages/web/src/_page-tests/faq.test.tsx
  packages/web/src/experience/contentful/nodes.tsx
  packages/web/src/faq/FAQ.tsx
  packages/web/src/faq/getFAQData.ts
  packages/web/src/privacy/FAQ.tsx
  packages/web/src/utils/contentful.ts
  packages/web/tsconfig.jest.json
Labels: automerge

#4989 [Wallet] Add e2e tests and improve flakiness
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/androidTest/java/org/celo/mobile/DetoxTest.java
  packages/mobile/android/build.gradle
  packages/mobile/e2e/README.md
  packages/mobile/e2e/TestsRunner.spec.js
  packages/mobile/e2e/config.json
  packages/mobile/e2e/src/FundedAccount.spec.js
  packages/mobile/e2e/src/NewAccount.spec.js
  packages/mobile/e2e/src/ResetAccount.js
  packages/mobile/e2e/src/Withdraw.js
  packages/mobile/e2e/src/usecases/ExchangeCelo.js
  packages/mobile/e2e/src/usecases/NewAccountCeloScreen.js
  packages/mobile/e2e/src/usecases/NewAccountOnboarding.js
  packages/mobile/e2e/src/usecases/ResetAccount.js
  packages/mobile/e2e/src/usecases/RestoreAccountOnboarding.js
  packages/mobile/e2e/src/usecases/Send.js
  packages/mobile/e2e/src/usecases/SetAccountKey.js
  packages/mobile/e2e/src/utils/celoEducation.js
  packages/mobile/e2e/src/utils/utils.js
  packages/mobile/package.json
  packages/mobile/scripts/run_e2e.sh
  packages/mobile/src/backup/BackupIntroduction.tsx
  packages/mobile/src/backup/BackupPhraseContainer.tsx
  packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupPhraseContainer.test.tsx.snap
  packages/mobile/src/components/CommentTextInput.tsx
  packages/mobile/src/components/DevSkipButton.tsx
  packages/mobile/src/exchange/CeloExchangeButtons.tsx
  packages/mobile/src/exchange/CeloGoldOverview.tsx
  packages/mobile/src/exchange/ExchangeReview.tsx
  packages/mobile/src/exchange/__snapshots__/CeloExchangeButtons.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/CeloGoldOverview.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeReview.test.tsx.snap
  packages/mobile/src/invite/EnterInviteCode.tsx
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestConfirmation.test.tsx.snap
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  yarn.lock
Labels: automerge, wallet

#5124 Fixes backward compatibility issues in cli
  packages/cli/src/utils/config.ts
Labels: devX

#5143 Fixes flakey tests caused by missing await
  packages/mobile/e2e/src/usecases/NewAccountCeloScreen.js
Labels: automerge

#3008 Adds an interactive prompt for forming proposals from Celo registry contracts and functions
  packages/cli/package.json
  packages/cli/src/commands/governance/propose.ts
  packages/contractkit/package.json
  packages/contractkit/src/governance/proposals.ts
  packages/docs/SUMMARY.md
  packages/docs/command-line-interface/governance.md
  packages/docs/developer-resources/contractkit/reference/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/classes/_governance_proposals_.interactiveproposalbuilder.md
  packages/docs/developer-resources/contractkit/reference/classes/_governance_proposals_.proposalbuilder.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_governance_proposals_.proposaltransactionjson.md
  packages/docs/developer-resources/contractkit/reference/modules/_governance_proposals_.md
  yarn.lock
Labels: automerge

#5110 Websites Release Docs
  packages/reserve-site/README.md
  packages/reserve-site/RELEASE.MD
  packages/reserve-site/dispatch.yaml
  packages/reserve-site/package.json
  packages/reserve-site/stage.yaml
  packages/web/README.md
  packages/web/RELEASE.md
  packages/web/package.json
Labels: automerge

#5135 Fixed Blockchain API deployment
  packages/blockchain-api/package.json
Labels: automerge

#4961 Add script to fund e2e tests account when balance is low
  packages/mobile/scripts/fund_e2e_account.sh
Labels: automerge

#5151 Added linting + deleted unused style properties
  packages/mobile/package.json
  packages/mobile/src/account/FiatExchange.tsx
  packages/mobile/src/account/InviteReview.tsx
  packages/mobile/src/account/Support.tsx
  packages/mobile/src/account/SupportContact.tsx
  packages/mobile/src/backup/BackupComplete.tsx
  packages/mobile/src/backup/BackupPhraseContainer.tsx
  packages/mobile/src/backup/BackupQuiz.tsx
  packages/mobile/src/backup/BackupSocialIntro.tsx
  packages/mobile/src/components/Styles.tsx
  packages/mobile/src/dappkit/DappKitSignTxScreen.tsx
  packages/mobile/src/escrow/EscrowedPaymentListItem.tsx
  packages/mobile/src/exchange/CeloGoldHistoryChart.tsx
  packages/mobile/src/exchange/CeloGoldOverview.tsx
  packages/mobile/src/exchange/ExchangeConfirmationCard.tsx
  packages/mobile/src/exchange/ExchangeHomeScreen.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/home/CeloDollarsOverview.tsx
  packages/mobile/src/home/WalletHome.tsx
  packages/mobile/src/import/ImportWallet.tsx
  packages/mobile/src/onboarding/registration/RegulatoryTerms.tsx
  packages/mobile/src/qrcode/QRScanner.tsx
  packages/mobile/src/recipients/RecipientItem.tsx
  packages/mobile/src/shared/DisconnectBanner.tsx
  packages/mobile/src/transactions/ExchangeFeedItem.tsx
  packages/mobile/src/transactions/GoldTransactionFeedItem.tsx
  packages/mobile/src/transactions/NoActivity.tsx
  packages/mobile/tslint.json
  yarn.lock
Labels: automerge, wallet

#5106 [Wallet] Group activity feed items by date
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/locales/es-419/walletFlow5.json
  packages/mobile/src/home/WalletHome.tsx
  packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
  packages/mobile/src/transactions/TransactionFeed.tsx
  packages/mobile/src/transactions/TransactionsList.test.tsx
  packages/mobile/src/transactions/TransactionsList.tsx
  packages/mobile/src/transactions/__snapshots__/TransactionFeed.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransactionsList.test.tsx.snap
  packages/mobile/src/transactions/utils.test.ts
  packages/mobile/src/transactions/utils.ts
  packages/mobile/src/utils/time.test.ts
  packages/mobile/src/utils/time.ts
Labels: automerge, wallet

#5169 [Wallet] e2e tests configuration
  packages/mobile/android/app/src/main/res/xml/network_security_config.xml
  packages/mobile/e2e/src/usecases/ExchangeCelo.js
  packages/mobile/e2e/src/usecases/ResetAccount.js
  packages/mobile/e2e/src/utils/celoEducation.js
  packages/mobile/scripts/run_e2e.sh
Labels: wallet

#5178 [Wallet] Fix Race condition with fetching verification state and balances
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/redux/sagas-helpers.ts
  packages/mobile/src/tokens/saga.ts
Labels: automerge

#5007 [Wallet] keep awake verification loading screen + fix upgrade screen
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/src/app/UpgradeScreen.tsx
  packages/mobile/src/app/__snapshots__/ErrorScreen.test.tsx.snap
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/utils/linking.ts
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationLoadingScreen.test.tsx.snap
  packages/react-components/components/FullscreenCTA.tsx
  packages/react-components/components/__snapshots__/FullscreenCTA.test.tsx.snap
Labels: automerge, wallet

#5177 [Wallet] Go back to VerificationEducation screen without updating the state
  packages/mobile/src/verify/VerificationEducationScreen.tsx
Labels: automerge

#5121 [Wallet] Update Clipboard for iOS 14
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/src/app/Debug.tsx
  packages/mobile/src/backup/BackupPhraseContainer.tsx
  packages/mobile/src/components/AccountNumber.tsx
  packages/mobile/src/components/ClipboardAwarePasteButton.tsx
  packages/mobile/src/components/CodeInput.tsx
  packages/mobile/src/components/SessionId.tsx
  packages/mobile/src/invite/EnterInviteCode.test.tsx
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/utils/useClipboard.ts
  packages/react-components/components/WithPasteAware.tsx
  packages/react-components/components/utils/IosVersionUtils.ts
  yarn.lock
Labels: automerge, wallet

#5149 Expand forno docs page
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/forno/README.md
  packages/docs/developer-resources/overview.md
Labels: automerge, docs

#5194 Cherry-pick "Script to deploy smart contract changes to a network via governance" into "oz-prerelease"
  .circleci/config.yml
  packages/contractkit/src/base.ts
  packages/docs/developer-resources/contractkit/reference/modules/_contractkit_src_base_.md
  packages/protocol/contracts/common/Accounts.sol
  packages/protocol/contracts/common/FixidityLib.sol
  packages/protocol/contracts/common/GasPriceMinimum.sol
  packages/protocol/contracts/common/Signatures.sol
  packages/protocol/contracts/common/linkedlists/AddressLinkedList.sol
  packages/protocol/contracts/common/linkedlists/AddressSortedLinkedList.sol
  packages/protocol/contracts/common/linkedlists/AddressSortedLinkedListWithMedian.sol
  packages/protocol/contracts/common/linkedlists/IntegerSortedLinkedList.sol
  packages/protocol/contracts/common/linkedlists/LinkedList.sol
  packages/protocol/contracts/common/linkedlists/SortedLinkedList.sol
  packages/protocol/contracts/common/linkedlists/SortedLinkedListWithMedian.sol
  packages/protocol/contracts/common/proxies/AddressLinkedListProxy.sol
  packages/protocol/contracts/common/proxies/AddressSortedLinkedListProxy.sol
  packages/protocol/contracts/common/proxies/AddressSortedLinkedListWithMedianProxy.sol
  packages/protocol/contracts/common/proxies/FixidityLibProxy.sol
  packages/protocol/contracts/common/proxies/IntegerSortedLinkedListProxy.sol
  packages/protocol/contracts/common/proxies/SignaturesProxy.sol
  packages/protocol/contracts/governance/Proposals.sol
  packages/protocol/contracts/governance/proxies/ProposalsProxy.sol
  packages/protocol/contracts/identity/Escrow.sol
  packages/protocol/contracts/identity/test/AttestationsTest.sol
  packages/protocol/contracts/identity/test/RandomTest.sol
  packages/protocol/contracts/stability/StableToken.sol
  packages/protocol/migrationsConfig.js
  packages/protocol/package.json
  packages/protocol/scripts/bash/check-versions.sh
  packages/protocol/scripts/bash/make-release.sh
  packages/protocol/scripts/truffle/make-release.ts
  packages/protocol/test/identity/attestations.ts
  packages/protocol/test/identity/random.ts
  packages/protocol/truffle-config.js
Labels: automerge

#5197 Correct documentation on the validator and validator group deregister
  packages/cli/src/commands/validator/deregister.ts
  packages/cli/src/commands/validatorgroup/deregister.ts
  packages/docs/command-line-interface/validator.md
  packages/docs/command-line-interface/validatorgroup.md
Labels: automerge

#5213 Allow ignoring known vulnerabilities
  .circleci/config.yml
  scripts/ci_check_vulnerabilities.sh
  yarn-audit-known-issues
Labels: wallet

#5195 [Wallet] Add exchanges to Cash In / Out options
  packages/mobile/.gitignore
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/locales/es-419/fiatExchangeFlow.json
  packages/mobile/src/account/FiatExchange.tsx
  packages/mobile/src/account/__snapshots__/FiatExchange.test.tsx.snap
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/components/AccountNumber.tsx
  packages/mobile/src/config.ts
  packages/mobile/src/fiatExchanges/ExternalExchanges.tsx
  packages/mobile/src/icons/LinkArrow.tsx
  packages/mobile/src/images/link-arrow.png
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/send/__snapshots__/ValidateRecipientAccount.test.tsx.snap
Labels: automerge, wallet

#5134 [Wallet] Add resend button to VerificationInputScreen
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/config.ts
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/types.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/verify/VerificationCountdown.tsx
  packages/mobile/src/verify/VerificationEducationScreen.test.tsx
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/VerificationFailedModal.tsx
  packages/mobile/src/verify/VerificationInputScreen.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/VerificationInputScreen.test.tsx.snap
  packages/mobile/test/schemas.ts
  packages/mobile/test/values.ts
Labels: automerge, wallet

#5198 [Wallet] Validate mnemonic in the app's language
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/src/import/saga.test.ts
  packages/mobile/src/import/saga.ts
Labels: automerge, wallet

#5211 [Wallet] Merge 1.1 release changes
  packages/mobile/Gemfile
  packages/mobile/Gemfile.lock
  packages/mobile/README.md
  packages/mobile/android/app/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/e2e/README.md
  packages/mobile/fastlane/Pluginfile
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/scripts/pre-deploy.sh
  packages/mobile/src/account/LicenseDisclaimer.txt
Labels: automerge, wallet

#5232 [Wallet] Fix invite flow and i18n texts
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/src/invite/saga.ts
Labels: automerge, wallet

#5203 Add e2e tests for Secure Send
  packages/mobile/e2e/src/FundedAccount.spec.js
  packages/mobile/e2e/src/usecases/SecureSend.js
  packages/mobile/src/components/SingleDigitInput.tsx
  packages/mobile/src/send/ValidateRecipientAccount.tsx
  packages/mobile/src/send/__snapshots__/ValidateRecipientAccount.test.tsx.snap
Labels: automerge, wallet

#5239 update mainnet forno endpoints
  packages/docs/developer-resources/forno/README.md
Labels: automerge, docs

#5241 ODIS Common: Add missing dependencies
  packages/phone-number-privacy/common/package.json
Labels: automerge

#4996 Verify source code matches deployed or proposed bytecode
  .circleci/config.yml
  packages/protocol/example-initialize-data.json
  packages/protocol/lib/bytecode.ts
  packages/protocol/lib/compatibility/ast-code.ts
  packages/protocol/lib/compatibility/verify-bytecode.ts
  packages/protocol/lib/registry-utils.ts
  packages/protocol/lib/test-utils.ts
  packages/protocol/package.json
  packages/protocol/scripts/truffle/make-release.ts
  packages/protocol/scripts/truffle/verify-bytecode.ts
  packages/protocol/test/compatibility/verify-bytecode.ts
  packages/protocol/test/resources/compatibility/contracts_linked_libraries/LinkedLibrary1.sol
  packages/protocol/test/resources/compatibility/contracts_linked_libraries/LinkedLibrary2.sol
  packages/protocol/test/resources/compatibility/contracts_linked_libraries/LinkedLibrary3.sol
  packages/protocol/test/resources/compatibility/contracts_linked_libraries/Migrations.sol
  packages/protocol/test/resources/compatibility/contracts_linked_libraries/TestContract.sol
  packages/protocol/test/resources/compatibility/contracts_linked_libraries_upgraded_contract/LinkedLibrary1.sol
  packages/protocol/test/resources/compatibility/contracts_linked_libraries_upgraded_contract/LinkedLibrary2.sol
  packages/protocol/test/resources/compatibility/contracts_linked_libraries_upgraded_contract/LinkedLibrary3.sol
  packages/protocol/test/resources/compatibility/contracts_linked_libraries_upgraded_contract/Migrations.sol
  packages/protocol/test/resources/compatibility/contracts_linked_libraries_upgraded_contract/TestContract.sol
  packages/protocol/test/resources/compatibility/contracts_linked_libraries_upgraded_lib/LinkedLibrary1.sol
  packages/protocol/test/resources/compatibility/contracts_linked_libraries_upgraded_lib/LinkedLibrary2.sol
  packages/protocol/test/resources/compatibility/contracts_linked_libraries_upgraded_lib/LinkedLibrary3.sol
  packages/protocol/test/resources/compatibility/contracts_linked_libraries_upgraded_lib/Migrations.sol
  packages/protocol/test/resources/compatibility/contracts_linked_libraries_upgraded_lib/TestContract.sol
  packages/protocol/tslint.json
  yarn.lock
Labels: automerge
