Repository celo-org/celo-monorepo, pull requests merged in 2020-06, with the labels that each got.

#3936 Fix geth resource indentation
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
Labels: automerge

#3937 Fix celostat blockscout link
  .env.alfajores
  packages/helm-charts/celostats/templates/celostats-frontend.deployment.yaml
Labels: automerge

#3907 Make all possible oracle values easily configured, upgrade oracle infra
  packages/celotool/src/cmds/deploy/initial/oracle.ts
  packages/celotool/src/cmds/deploy/upgrade/oracle.ts
  packages/celotool/src/lib/aks-fullnode.ts
  packages/celotool/src/lib/endpoints.ts
  packages/celotool/src/lib/oracle.ts
  packages/helm-charts/celo-fullnode/templates/_helpers.tpl
  packages/helm-charts/celo-fullnode/templates/service.yaml
  packages/helm-charts/celo-fullnode/values.yaml
  packages/helm-charts/common/templates/_helpers.tpl
  packages/helm-charts/oracle/requirements.lock
  packages/helm-charts/oracle/requirements.yaml
  packages/helm-charts/oracle/templates/statefulset.yaml
  packages/helm-charts/oracle/values.yaml
Labels: automerge

#3929 improvements to rate limiting
  packages/web/server/rateLimit.ts
Labels: automerge

#3931 [Wallet] Add analytics for Gold screens + Send Part 1 redesigned screens
  packages/mobile/src/analytics/constants.ts
  packages/mobile/src/components/CancelButton.v2.tsx
  packages/mobile/src/exchange/ExchangeHomeScreen.tsx
  packages/mobile/src/exchange/ExchangeReview.tsx
  packages/mobile/src/exchange/ExchangeTradeScreen.tsx
  packages/mobile/src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap
  packages/mobile/src/exchange/saga.ts
  packages/mobile/src/navigator/Headers.v2.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/TopBarButton.v2.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/send/Send.tsx
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/transactions/GoldTransactionFeedItem.tsx
Labels: automerge

#3894 Switch wallet to drawer navigation
  packages/mobile/__mocks__/@react-navigation/native.ts
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/package.json
  packages/mobile/src/account/Account.tsx
  packages/mobile/src/account/FiatExchange.tsx
  packages/mobile/src/account/Invite.tsx
  packages/mobile/src/account/Support.tsx
  packages/mobile/src/account/__snapshots__/Account.test.tsx.snap
  packages/mobile/src/account/__snapshots__/FiatExchange.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Invite.test.tsx.snap
  packages/mobile/src/account/__snapshots__/InviteReview.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Support.test.tsx.snap
  packages/mobile/src/backup/BackupIntroduction.tsx
  packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap
  packages/mobile/src/components/Avatar.tsx
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationCard.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationScreen.test.tsx.snap
  packages/mobile/src/exchange/ExchangeHomeScreen.tsx
  packages/mobile/src/home/WalletHome.tsx
  packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
  packages/mobile/src/icons/navigator/AccountKey.tsx
  packages/mobile/src/icons/navigator/AddWithdraw.tsx
  packages/mobile/src/icons/navigator/Gold.tsx
  packages/mobile/src/icons/navigator/Help.tsx
  packages/mobile/src/icons/navigator/Home.tsx
  packages/mobile/src/icons/navigator/Invite.tsx
  packages/mobile/src/icons/navigator/Settings.tsx
  packages/mobile/src/language/Language.tsx
  packages/mobile/src/localCurrency/hooks.ts
  packages/mobile/src/navigator/DrawerNavigator.tsx
  packages/mobile/src/navigator/DrawerTopBar.tsx
  packages/mobile/src/navigator/Hamburger.tsx
  packages/mobile/src/navigator/NavigationService.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/TabNavigator.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestConfirmation.test.tsx.snap
  packages/mobile/src/qrcode/__snapshots__/QRCode.test.tsx.snap
  packages/mobile/src/send/__snapshots__/TransferReviewCard.test.tsx.snap
  packages/mobile/test/values.ts
  packages/react-components/components/PhoneNumberWithFlag.tsx
  packages/react-components/components/__snapshots__/Avatar.test.tsx.snap
  packages/utils/src/phoneNumbers.ts
  yarn.lock
Labels: automerge

#3945 Add to custodian docs
  packages/docs/developer-resources/integrations/custody.md
Labels: automerge

#3932 Add eth_gasPriceInFeeCurrency to tx params population
  packages/contractkit/src/kit.test.ts
  packages/contractkit/src/kit.ts
  packages/contractkit/src/utils/tx-params-normalizer.test.ts
  packages/contractkit/src/utils/tx-params-normalizer.ts
  packages/docs/developer-resources/contractkit/reference/classes/_kit_.contractkit.md
Labels: automerge

#3943 [PGPNP] Added Combiner Logic for Threshold Signatures
  packages/celotool/package.json
  packages/notification-service/package.json
  packages/phone-number-privacy/combiner/package.json
  packages/phone-number-privacy/combiner/scripts/createBlsKeyPair.ts
  packages/phone-number-privacy/combiner/scripts/createThresholdBlsKeys.ts
  packages/phone-number-privacy/combiner/src/bls/bls-cryptography-client.ts
  packages/phone-number-privacy/combiner/src/common/error-utils.ts
  packages/phone-number-privacy/combiner/src/config.ts
  packages/phone-number-privacy/combiner/src/index.ts
  packages/phone-number-privacy/combiner/src/salt-generation/get-salt.ts
  packages/phone-number-privacy/combiner/src/salt-generation/get-threshold-salt.ts
  packages/phone-number-privacy/combiner/test/index.test.ts
  packages/phone-number-privacy/combiner/test/salt-generation/bls-signature.test.ts
  packages/phone-number-privacy/combiner/test/utils.ts
  packages/phone-number-privacy/signer/.firebaserc
  packages/phone-number-privacy/signer/firebase.json
  packages/phone-number-privacy/signer/scripts/createBlsKeyPair.ts
  packages/phone-number-privacy/signer/src/bls/bls-cryptography-client.ts
  packages/phone-number-privacy/signer/src/config.ts
  packages/phone-number-privacy/signer/test/salt-generation/bls-signature.test.ts
  packages/phone-number-privacy/signer/test/utils.ts
  packages/protocol/package.json
Labels: automerge

#3975 [Wallet] Add import contact onboarding screen
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/en-US/index.ts
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/es-419/index.ts
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/src/i18n.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/onboarding/contacts/ImportContactsScreen.test.tsx
  packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx
  packages/mobile/src/onboarding/contacts/__snapshots__/ImportContactsScreen.test.tsx.snap
Labels: automerge

#3953 [Wallet Redesign ] Payment Request and Invite Redesign
  packages/mobile/locales/en-US/paymentRequestFlow.json
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/es-419/paymentRequestFlow.json
  packages/mobile/locales/es-419/sendFlow7.json
  packages/mobile/src/account/InviteReview.tsx
  packages/mobile/src/account/__snapshots__/InviteReview.test.tsx.snap
  packages/mobile/src/analytics/constants.ts
  packages/mobile/src/components/CommentTextInput.tsx
  packages/mobile/src/components/InviteOptionsModal.tsx
  packages/mobile/src/home/SendOrRequestBar.tsx
  packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/paymentRequest/PaymentRequestConfirmation.test.tsx
  packages/mobile/src/paymentRequest/PaymentRequestConfirmation.tsx
  packages/mobile/src/paymentRequest/PaymentRequestReviewCard.tsx
  packages/mobile/src/paymentRequest/PaymentRequestUnavailable.test.tsx
  packages/mobile/src/paymentRequest/PaymentRequestUnavailable.tsx
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestConfirmation.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestUnavailable.test.tsx.snap
  packages/mobile/src/send/SendAmount.test.tsx
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/SendConfirmation.test.tsx
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/TransferReviewCard.test.tsx
  packages/mobile/src/send/TransferReviewCard.tsx
  packages/mobile/src/send/ValidateRecipientAccount.tsx
  packages/mobile/src/send/ValidateRecipientIntro.tsx
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/send/__snapshots__/TransferReviewCard.test.tsx.snap
  packages/mobile/src/send/__snapshots__/ValidateRecipientAccount.test.tsx.snap
  packages/mobile/src/send/__snapshots__/ValidateRecipientIntro.test.tsx.snap
  packages/mobile/src/utils/formatting.ts
Labels: automerge, wallet, wallet-redesign

#3941 [PGPNP] Remove matchmaking from signer and de-dupe test utils
  packages/phone-number-privacy/combiner/src/database/models/account.ts
  packages/phone-number-privacy/combiner/src/database/models/model.ts
  packages/phone-number-privacy/combiner/src/database/models/numberPair.ts
  packages/phone-number-privacy/combiner/test/end-to-end/get-blinded-salt.test.ts
  packages/phone-number-privacy/combiner/test/index.test.ts
  packages/phone-number-privacy/combiner/test/salt-generation/query-quota.test.ts
  packages/phone-number-privacy/common/test/utils.ts
  packages/phone-number-privacy/common/test/values.ts
  packages/phone-number-privacy/signer/migrations/20200330212301_create-number-pairs-table.ts
  packages/phone-number-privacy/signer/src/database/models/account.ts
  packages/phone-number-privacy/signer/src/database/models/model.ts
  packages/phone-number-privacy/signer/src/database/models/numberPair.ts
  packages/phone-number-privacy/signer/src/database/wrappers/number-pairs.ts
  packages/phone-number-privacy/signer/src/index.ts
  packages/phone-number-privacy/signer/src/match-making/get-contact-matches.ts
  packages/phone-number-privacy/signer/test/end-to-end/get-blinded-salt.test.ts
  packages/phone-number-privacy/signer/test/index.test.ts
  packages/phone-number-privacy/signer/test/salt-generation/query-quota.test.ts
  packages/phone-number-privacy/signer/test/utils.ts
  packages/phone-number-privacy/signer/test/values.ts
Labels: automerge

#3935 PGPNP Docs
  packages/docs/celo-codebase/protocol/identity/phone-number-privacy.md
Labels: automerge

#3909 [utils/cli] Generate addresses using custom mnemonics and derivationPaths
  packages/cli/src/commands/account/new.ts
  packages/docs/command-line-interface/account.md
  packages/utils/src/account.ts
Labels: automerge

#3990 CeloCLI oracle:list command
  packages/cli/src/commands/oracle/list.ts
  packages/docs/command-line-interface/oracle.md
Labels: automerge

#3938 Add readiness probe to full nodes, use exec for long running processes in containers ran from sh/bash
  packages/helm-charts/attestation-bot/templates/statefulset.yaml
  packages/helm-charts/attestation-service/templates/attestation.statefulset.yaml
  packages/helm-charts/blockscout/templates/blockscout-indexer.deployment.yaml
  packages/helm-charts/blockscout/templates/blockscout-web.deployment.yaml
  packages/helm-charts/celo-fullnode/templates/statefulset.yaml
  packages/helm-charts/celo-fullnode/values.yaml
  packages/helm-charts/celostats/templates/celostats-frontend.deployment.yaml
  packages/helm-charts/celostats/templates/celostats-server.deployment.yaml
  packages/helm-charts/common/templates/_helpers.tpl
  packages/helm-charts/load-test/templates/load-test.statefulset.yaml
  packages/helm-charts/oracle/templates/statefulset.yaml
  packages/helm-charts/testnet/templates/bootnode.deployment.yaml
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
Labels: automerge

#3947 make _activate private because it has a nice accessor already
  packages/contractkit/src/wrappers/Election.ts
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_election_.electionwrapper.md
Labels: automerge

#4021 white paper link updates
  packages/docs/README.md
Labels: automerge

#4024 Config changes to ship the integration app
  packages/mobile/.env.integration
  packages/mobile/android/gradle.properties
  packages/mobile/fastlane/Fastfile
  packages/mobile/fastlane/README.md
Labels: automerge

#3927 validator badge collection
  packages/web/validator-badges/001-stake-off-founder-validator.md
  packages/web/validator-badges/002-stake-off-attestation-maven.md
  packages/web/validator-badges/003-stake-off-master-validator.md
  packages/web/validator-badges/004-genesis-validator.md
  packages/web/validator-badges/005-genesis-1st-proposer.md
  packages/web/validator-badges/006-genesis-1st-transaction.md
  packages/web/validator-badges/007-celo-foundation-vote-recipient.md
  packages/web/validator-badges/README.md
Labels: web

#3976 Feat/eksportisto sensitive accounts
  packages/celotool/src/lib/eksportisto.ts
  packages/helm-charts/eksportisto/Chart.yaml
  packages/helm-charts/eksportisto/templates/configmap.yaml
  packages/helm-charts/eksportisto/templates/statefulset.yaml
Labels: automerge

#3944 [PGPNP] Convert Signer to be an express app
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/metadata-crawler/package.json
  packages/notification-service/package.json
  packages/phone-number-privacy/combiner/test/index.test.ts
  packages/phone-number-privacy/common/test/utils.ts
  packages/phone-number-privacy/signer/.env
  packages/phone-number-privacy/signer/.gitignore
  packages/phone-number-privacy/signer/jest.config.js
  packages/phone-number-privacy/signer/package.json
  packages/phone-number-privacy/signer/src/config.ts
  packages/phone-number-privacy/signer/src/index.ts
  packages/phone-number-privacy/signer/src/salt-generation/get-salt.ts
  packages/phone-number-privacy/signer/src/server.ts
  packages/phone-number-privacy/signer/test/index.test.ts
  yarn.lock
Labels: automerge

#4025 Update dependency versions
  package.json
  packages/blockchain-api/package.json
  packages/contractkit/src/utils/tx-uri.ts
  packages/docs/developer-resources/contractkit/reference/modules/_utils_tx_uri_.md
  packages/faucet/package.json
  yarn.lock
Labels: automerge

#4037 Fix status of current-attestation-services
  packages/cli/src/commands/identity/current-attestation-services.ts
Labels: automerge

#4039 Remove analytics package
  .dockerignore
  .github/CODEOWNERS
  README.md
  packages/analytics/.gitignore
  packages/analytics/README.md
  packages/analytics/celo_analytics/__init__.py
  packages/analytics/celo_analytics/transforms.py
  packages/analytics/client_log_exporter.py
  packages/analytics/requirements.txt
  packages/analytics/segment_data_exporter.py
  packages/analytics/setup.py
  packages/analytics/timing_metrics.py
Labels: automerge

#4040 [PGPNP] Update combiner config to work with local signer express app, remove firebase stuff for signer
  packages/phone-number-privacy/combiner/src/config.ts
  packages/phone-number-privacy/signer/.firebaserc
  packages/phone-number-privacy/signer/firebase.json
Labels: automerge

#4026 [Web] EventKit
  packages/web/next.config.js
  packages/web/package.json
  packages/web/pages/api/experience/assets/[asset].ts
  packages/web/pages/experience/events/ambassador.tsx
  packages/web/pages/experience/events/examples.tsx
  packages/web/pages/experience/events/flavor.tsx
  packages/web/pages/experience/events/index.tsx
  packages/web/pages/experience/events/resources.tsx
  packages/web/server/EventKit.ts
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/exchange-icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/experience/Markdown.tsx
  packages/web/src/experience/common/TopBar.tsx
  packages/web/src/experience/eventkit/AmbassadorPage.tsx
  packages/web/src/experience/eventkit/ExamplesPage.tsx
  packages/web/src/experience/eventkit/FlavorPage.tsx
  packages/web/src/experience/eventkit/Intro.tsx
  packages/web/src/experience/eventkit/Page.tsx
  packages/web/src/experience/eventkit/PlanningDocs.tsx
  packages/web/src/experience/eventkit/ResourcesPage.tsx
  packages/web/src/experience/eventkit/Section.tsx
  packages/web/src/experience/eventkit/Tenents.tsx
  packages/web/src/experience/eventkit/content/circles/overview.md
  packages/web/src/experience/eventkit/content/circles/sponsorship.md
  packages/web/src/experience/eventkit/content/examples/examples.md
  packages/web/src/experience/eventkit/content/examples/slide-decks.md
  packages/web/src/experience/eventkit/content/examples/videos.md
  packages/web/src/experience/eventkit/content/flavor/code-of-conduct.md
  packages/web/src/experience/eventkit/content/flavor/foster.md
  packages/web/src/experience/eventkit/content/flavor/overview.md
  packages/web/src/experience/eventkit/content/flavor/rituals.md
  packages/web/src/experience/eventkit/content/flavor/tenets.md
  packages/web/src/experience/eventkit/content/flavor/unique-gifts.md
  packages/web/src/experience/eventkit/content/intro/overview.md
  packages/web/src/experience/eventkit/content/meta.md
  packages/web/src/experience/eventkit/content/resources/overview.md
  packages/web/src/experience/eventkit/content/resources/planning.md
  packages/web/src/experience/eventkit/content/resources/quick-tips.md
  packages/web/src/experience/eventkit/content/resources/social-media.md
  packages/web/src/experience/eventkit/content/tenents/design-for-all.md
  packages/web/src/experience/eventkit/content/tenents/design-for-all.png
  packages/web/src/experience/eventkit/content/tenents/embodying-humility.md
  packages/web/src/experience/eventkit/content/tenents/embodying-humility.png
  packages/web/src/experience/eventkit/content/tenents/innovating-on-money.md
  packages/web/src/experience/eventkit/content/tenents/innovating-on-money.png
  packages/web/src/experience/eventkit/content/tenents/striving-for-beauty.md
  packages/web/src/experience/eventkit/content/tenents/striving-for-beauty.png
  packages/web/src/experience/eventkit/tracking.ts
  packages/web/src/interfaces.d.ts
  packages/web/src/shared/Footer.tsx
  packages/web/src/shared/__snapshots__/Footer.test.tsx.snap
  packages/web/src/shared/menu-items.ts
  yarn.lock
Labels: automerge

#3920 [contractKit] Add condition for MultiSig wrapper to resubmit a transaction if it was already executed
  packages/contractkit/src/wrappers/MultiSig.ts
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_multisig_.multisigwrapper.md
Labels: automerge

#4034 [Wallet + PGPNP] Add matchmaking experience to wallet (Part 2)
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/src/analytics/constants.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/commentEncryption.test.ts
  packages/mobile/src/identity/commentEncryption.ts
  packages/mobile/src/identity/contactMapping.test.ts
  packages/mobile/src/identity/contactMapping.ts
  packages/mobile/src/identity/matchmaking.test.ts
  packages/mobile/src/identity/matchmaking.ts
  packages/mobile/src/identity/phoneNumPrivacyService.ts
  packages/mobile/src/identity/privateHashing.test.ts
  packages/mobile/src/identity/privateHashing.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/identity/types.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx
  packages/mobile/src/onboarding/contacts/__snapshots__/ImportContactsScreen.test.tsx.snap
  packages/mobile/src/onboarding/success/OnboardingSuccessScreen.tsx
  packages/mobile/src/recipients/recipient.ts
  packages/mobile/src/redux/sagas.ts
  packages/mobile/src/send/ContactSyncBanner.test.tsx
  packages/mobile/src/send/ContactSyncBanner.tsx
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/__snapshots__/ContactSyncBanner.test.tsx.snap
  packages/mobile/src/send/utils.ts
  packages/mobile/src/verify/VerificationFailedModal.tsx
  packages/mobile/src/verify/VerificationInputScreen.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.test.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
  packages/mobile/src/verify/VerificationSuccessScreen.tsx
  packages/mobile/test/schemas.ts
  packages/phone-number-privacy/combiner/src/common/input-validation.ts
  packages/phone-number-privacy/combiner/src/match-making/get-contact-matches.ts
  packages/phone-number-privacy/combiner/src/salt-generation/get-threshold-salt.ts
  packages/phone-number-privacy/signer/src/salt-generation/get-salt.ts
Labels: automerge

#4017 [Wallet][ReDesign] QR Code / Scan screens
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/es-419/sendFlow7.json
  packages/mobile/package.json
  packages/mobile/src/components/__snapshots__/Dialog.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentListItem.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentReminderSummaryNotification.test.tsx.snap
  packages/mobile/src/home/SendOrRequestBar.tsx
  packages/mobile/src/home/__snapshots__/NotificationBox.test.tsx.snap
  packages/mobile/src/index.d.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/QRNavigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/notifications/__snapshots__/SummaryNotification.test.tsx.snap
  packages/mobile/src/onboarding/contacts/__snapshots__/ImportContactsScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestSummaryNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestSummaryNotification.test.tsx.snap
  packages/mobile/src/qrcode/NotAuthorizedView.tsx
  packages/mobile/src/qrcode/QRCode.test.tsx
  packages/mobile/src/qrcode/QRCode.tsx
  packages/mobile/src/qrcode/QRGen.tsx
  packages/mobile/src/qrcode/QRGenTests/QRGen.test.tsx
  packages/mobile/src/qrcode/QRScanner.tsx
  packages/mobile/src/qrcode/QRTabBar.tsx
  packages/mobile/src/qrcode/__snapshots__/NotAuthorizedView.test.tsx.snap
  packages/mobile/src/qrcode/__snapshots__/QRCode.test.tsx.snap
  packages/mobile/src/send/QRCodeIcon.tsx
  packages/mobile/src/send/ValidateRecipientIntro.test.tsx
  packages/mobile/src/send/ValidateRecipientIntro.tsx
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/send/__snapshots__/ValidateRecipientIntro.test.tsx.snap
  packages/react-components/components/BorderlessButton.v2.tsx
  packages/react-components/components/Link.tsx
  packages/react-components/components/SegmentedControl.test.tsx
  packages/react-components/components/SegmentedControl.tsx
  packages/react-components/components/TextButton.tsx
  packages/react-components/components/TextButton.v2.tsx
  packages/react-components/components/Touchable.tsx
  packages/react-components/components/interpolateColors.ts
  packages/react-components/icons/Share.tsx
  packages/react-components/icons/Times.tsx
  patches/react-native-tab-view+2.14.4.patch
  yarn.lock
Labels: automerge

#4038 Remove transaction-metrics-exporter
  .github/CODEOWNERS
  README.md
  cloudbuild.yaml
  dependency-graph.json
  dockerfiles/transaction-metrics-exporter/Dockerfile
  packages/transaction-metrics-exporter/.gitignore
  packages/transaction-metrics-exporter/README.md
  packages/transaction-metrics-exporter/cloudbuild.yaml
  packages/transaction-metrics-exporter/package.json
  packages/transaction-metrics-exporter/src/blockchain.ts
  packages/transaction-metrics-exporter/src/index.ts
  packages/transaction-metrics-exporter/src/metrics.ts
  packages/transaction-metrics-exporter/tsconfig.json
  packages/transaction-metrics-exporter/tslint.json
Labels: automerge

#4050 [Wallet] Track verification attempt from start
  packages/mobile/src/analytics/constants.ts
  packages/mobile/src/identity/verification.ts
Labels: automerge

#4018 Add tooltips on Validator explorer
  packages/web/src/_page-tests/validators/__snapshots__/explore.test.tsx.snap
  packages/web/src/dev/ValidatorsList.tsx
  packages/web/src/dev/ValidatorsListApp.tsx
  packages/web/src/dev/ValidatorsListRow.tsx
  packages/web/src/dev/ValidatorsListStyles.tsx
Labels: automerge

#3666 [Wallet] Updating e2e tests
  .circleci/config.yml
  packages/mobile/.env.test
  packages/mobile/e2e/Transfer.spec.js
  packages/mobile/e2e/conf/avd_conf.ini
  packages/mobile/e2e/utils.js
  packages/mobile/scripts/run_e2e.sh
  packages/mobile/src/account/__snapshots__/Invite.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationScreen.test.tsx.snap
  packages/mobile/src/home/CeloDollarsOverview.tsx
  packages/mobile/src/home/SendOrRequestBar.tsx
  packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
  packages/mobile/src/invite/EnterInviteCode.tsx
  packages/mobile/src/invite/__snapshots__/EnterInviteCode.test.tsx.snap
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/localCurrency/saga.ts
  packages/mobile/src/localCurrency/selectors.ts
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestConfirmation.test.tsx.snap
  packages/mobile/src/recipients/RecipientItem.tsx
  packages/mobile/src/recipients/__snapshots__/RecipientItem.test.tsx.snap
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
  packages/react-components/components/Button.v2.tsx
  packages/react-components/components/NumberKeypad.tsx
  packages/react-components/components/ReviewFrame.tsx
Labels: automerge, wallet, wallet-quality

#4043 Oracle optional in memory signing infra, baklava deployment
  .env.baklava
  packages/celotool/src/lib/endpoints.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/oracle.ts
  packages/helm-charts/oracle/templates/azure-identity-binding.yaml
  packages/helm-charts/oracle/templates/azure-identity.yaml
  packages/helm-charts/oracle/templates/pkey-secret.yaml
  packages/helm-charts/oracle/templates/statefulset.yaml
  packages/helm-charts/oracle/values.yaml
Labels: automerge

#4049 fix: set default block time to 5 seconds
  .env
Labels: automerge

#4051 [PGPNP] Update configs/readme for distributed partners to run signer service
  packages/phone-number-privacy/signer/.env
  packages/phone-number-privacy/signer/README.md
  packages/phone-number-privacy/signer/src/config.ts
Labels: automerge

#4065 Code of Conduct Update / markify
  packages/web/__mocks__/MarkdownStub.ts
  packages/web/jest.config.js
  packages/web/public/static/locales/en/codeofconduct.json
  packages/web/src/_page-tests/__snapshots__/code-of-conduct.test.tsx.snap
  packages/web/src/community/CodeOfConduct.tsx
  packages/web/src/content/code-of-conduct.md
  packages/web/src/i18n.ts
  packages/web/src/utils/i18nForTests.ts
Labels: automerge

#4047 [Wallet][ReDesign] Language selection
  packages/mobile/__mocks__/src/i18n.ts
  packages/mobile/e2e/Transfer.spec.js
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/locales/es-419/accountScreen10.json
  packages/mobile/src/language/Language.test.tsx
  packages/mobile/src/language/Language.tsx
  packages/mobile/src/language/__snapshots__/Language.test.tsx.snap
  packages/mobile/src/localCurrency/SelectLocalCurrency.tsx
  packages/mobile/src/localCurrency/__snapshots__/SelectLocalCurrency.test.tsx.snap
  packages/react-components/components/LanguageSelectUI.test.tsx
  packages/react-components/components/LanguageSelectUI.tsx
  packages/react-components/components/SelectionOption.test.tsx
  packages/react-components/components/SelectionOption.tsx
  packages/react-components/components/__snapshots__/LanguageSelectUI.test.tsx.snap
  packages/react-components/components/__snapshots__/SelectionOption.test.tsx.snap
  packages/react-components/icons/CheckCircle.tsx
Labels: automerge

#4071 Add group affiliation to current-attestation-services
  packages/cli/src/commands/identity/current-attestation-services.ts
Labels: automerge

#3949 made getPastEvents public to enable listening to events when on http providers
  packages/contractkit/src/wrappers/BaseWrapper.ts
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_accounts_.accountswrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_attestations_.attestationswrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_basewrapper_.basewrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_blockchainparameters_.blockchainparameterswrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_doublesigningslasher_.doublesigningslasherwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_downtimeslasher_.downtimeslasherwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_election_.electionwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_escrow_.escrowwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_exchange_.exchangewrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_freezer_.freezerwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_gaspriceminimum_.gaspriceminimumwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_goldtokenwrapper_.goldtokenwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_governance_.governancewrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_lockedgold_.lockedgoldwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_multisig_.multisigwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_releasegold_.releasegoldwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_reserve_.reservewrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_sortedoracles_.sortedoracleswrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_stabletokenwrapper_.stabletokenwrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_validators_.validatorswrapper.md
Labels: automerge

#4067 Support OpenPGP WKD serving from @celo/web
  packages/web/openpgpkey/celo.org/policy
  packages/web/openpgpkey/clabs.co/policy
  packages/web/openpgpkey/dev.celo.org/policy
  packages/web/openpgpkey/staging.celo.org/policy
  packages/web/server/index.ts
Labels: automerge

#4068 [Wallet] Fix data saver bug
  packages/mobile/src/account/Account.tsx
Labels: automerge

#4041 [Wallet] Analytics Retooling + Analytics for Send & Request
  packages/mobile/__mocks__/react-native-reanimated.js
  packages/mobile/src/account/Education.tsx
  packages/mobile/src/analytics/CeloAnalytics.ts
  packages/mobile/src/analytics/constants.ts
  packages/mobile/src/app/App.tsx
  packages/mobile/src/exchange/saga.ts
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/identity/saga.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/paymentRequest/PaymentRequestConfirmation.tsx
  packages/mobile/src/paymentRequest/PaymentRequestUnavailable.tsx
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestUnavailable.test.tsx.snap
  packages/mobile/src/qrcode/utils.ts
  packages/mobile/src/send/Send.tsx
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/ValidateRecipientAccount.tsx
  packages/mobile/src/send/ValidateRecipientIntro.tsx
  packages/mobile/src/send/saga.ts
  packages/react-components/analytics/CeloAnalytics.test.tsx
  packages/react-components/analytics/CeloAnalytics.tsx
Labels: automerge, wallet

#4057 [Wallet] Balance check on VerificationEducationScreen and PhoneNumberLookupQuotaScreen
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/components/ErrorMessageInline.tsx
  packages/mobile/src/identity/PhoneNumberLookupQuotaScreen.tsx
  packages/mobile/src/identity/__snapshots__/PhoneNumberLookupQuotaScreen.test.tsx.snap
  packages/mobile/src/identity/privateHashing.ts
  packages/mobile/src/identity/utils.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/send/saga.ts
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
Labels: automerge, wallet

#4064 [PGPNP] Create dockerfile for PGPNP signer
  .dockerignore
  cloudbuild.yaml
  dockerfiles/phone-number-privacy/Dockerfile
  packages/phone-number-privacy/signer/.env
  packages/phone-number-privacy/signer/README.md
  packages/phone-number-privacy/signer/package.json
  packages/phone-number-privacy/signer/src/common/error-utils.ts
  packages/phone-number-privacy/signer/src/common/identity.ts
  packages/phone-number-privacy/signer/src/config.ts
Labels: automerge

#4055 [Wallet] Remove lots of empty string handling
  packages/mobile/src/account/Account.tsx
  packages/mobile/src/account/EditProfile.tsx
  packages/mobile/src/account/FiatExchange.tsx
  packages/mobile/src/account/Invite.tsx
  packages/mobile/src/account/Profile.tsx
  packages/mobile/src/account/SupportContact.tsx
  packages/mobile/src/account/reducer.ts
  packages/mobile/src/account/types.ts
  packages/mobile/src/app/Debug.tsx
  packages/mobile/src/components/Avatar.tsx
  packages/mobile/src/components/AvatarSelf.tsx
  packages/mobile/src/escrow/ReclaimPaymentConfirmationScreen.tsx
  packages/mobile/src/invite/reducer.ts
  packages/mobile/src/localCurrency/selectors.ts
  packages/mobile/src/navigator/DrawerNavigator.tsx
  packages/mobile/src/paymentRequest/PaymentRequestConfirmation.tsx
  packages/mobile/src/paymentRequest/utils.ts
  packages/mobile/src/recipients/RecipientPicker.tsx
  packages/mobile/src/registration/JoinCelo.tsx
  packages/mobile/src/send/Send.tsx
  packages/mobile/src/verify/VerificationInputScreen.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
  packages/react-components/components/Avatar.tsx
  packages/react-components/components/PhoneNumberWithFlag.tsx
  packages/utils/src/phoneNumbers.ts
Labels: automerge, wallet

#4076 [Docs] Fix build issue
  package.json
  packages/docs/package.json
  yarn.lock
Labels: automerge

#3830 Add local flag to account:list command to avoid needing an external node
  packages/cli/src/commands/account/list.ts
  packages/docs/command-line-interface/account.md
Labels: automerge

#4060 Overhaul metadata crawler logging
  packages/contractkit/src/identity/claims/verify.ts
  packages/docs/developer-resources/contractkit/reference/modules/_identity_claims_verify_.md
  packages/helm-charts/blockscout/templates/blockscout-metadata-crawler.cronjob.yaml
  packages/metadata-crawler/src/crawler.ts
  packages/metadata-crawler/src/logger.ts
Labels: automerge

#4082 Update Exchange Ticker Icons
  packages/web/public/assets/CeloMarketplaceIcons.zip
  packages/web/public/assets/marketplace-icons/icon-celo-dollar-black.zip
  packages/web/public/assets/marketplace-icons/icon-celo-dollar-white.zip
  packages/web/public/assets/marketplace-icons/icon-celo-gold-black.zip
  packages/web/public/assets/marketplace-icons/icon-celo-gold-color.zip
  packages/web/public/assets/marketplace-icons/icon-celo-gold-white.zip
  packages/web/public/images/marketplace-icons/icon-celo-CELO-color-f.svg
  packages/web/public/images/marketplace-icons/icon-celo-CELO-mono-f.svg
  packages/web/public/images/marketplace-icons/icon-celo-CELO-reverse-f.svg
  packages/web/public/images/marketplace-icons/icon-celo-dollar-mono-f.svg
  packages/web/public/images/marketplace-icons/icon-celo-dollar-reverse-f.svg
  packages/web/public/images/marketplace-icons/icon-celo-gold-black-f.svg
  packages/web/public/images/marketplace-icons/icon-celo-gold-color-f.svg
  packages/web/public/images/marketplace-icons/icon-celo-gold-white-f.svg
  packages/web/public/static/locales/en/brand.json
  packages/web/src/_page-tests/experience/__snapshots__/exchange-icons.test.tsx.snap
  packages/web/src/experience/brandkit/IconsExchangePage.tsx
  packages/web/src/experience/brandkit/content/exchange-icons.md
Labels: automerge

#4079 Celo.org Homepage 4.3
  packages/web/public/static/locales/en/home.json
  packages/web/src/_page-tests/__snapshots__/index.test.tsx.snap
  packages/web/src/community/EcoFund.tsx
  packages/web/src/dev/ValidatorsListApp.tsx
  packages/web/src/experience/common/TopBar.tsx
  packages/web/src/home/Home.tsx
  packages/web/src/home/Involvement.tsx
  packages/web/src/home/TwoAssets.tsx
  packages/web/src/home/involvement/build.jpg
  packages/web/src/home/involvement/connect.jpg
  packages/web/src/home/involvement/grow.jpg
  packages/web/src/home/involvement/partner.jpg
  packages/web/src/home/involvement/preview.png
  packages/web/src/home/involvement/validate.png
  packages/web/src/home/involvement/work.jpg
  packages/web/src/shared/Navigation.tsx
Labels: automerge, web

#4083 [Wallet] Created and placed FeeDrawer component
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/es-419/sendFlow7.json
  packages/mobile/src/components/FeeDrawer.tsx
  packages/mobile/src/send/SendConfirmation.test.tsx
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/transactions/TransferConfirmationCard.tsx
  packages/mobile/src/transactions/__snapshots__/TransferConfirmationCard.test.tsx.snap
Labels: automerge, wallet-redesign

#4081 Correctly propagate error message when sending an RPC
  dockerfiles/attestation-service/Dockerfile
  dockerfiles/celotool/Dockerfile
  dockerfiles/leaderboard/Dockerfile
  dockerfiles/metadata-crawler/Dockerfile
  packages/contractkit/src/utils/rpc-caller.test.ts
  packages/contractkit/src/utils/rpc-caller.ts
  patches/web3-core-helpers+1.2.4.patch
Labels: automerge

#4075 chore: allow passing migration overrides file to celotooljs geth start
  packages/celotool/src/cmds/geth/start.ts
Labels: automerge

#4090 [PGPNP] Add support for Google Secret Manager to signer
  packages/phone-number-privacy/signer/.env
  packages/phone-number-privacy/signer/.gitignore
  packages/phone-number-privacy/signer/README.md
  packages/phone-number-privacy/signer/package.json
  packages/phone-number-privacy/signer/src/bls/bls-cryptography-client.ts
  packages/phone-number-privacy/signer/src/common/error-utils.ts
  packages/phone-number-privacy/signer/src/config.ts
  packages/phone-number-privacy/signer/src/index.ts
  packages/phone-number-privacy/signer/src/key-management/azure-key-provider.ts
  packages/phone-number-privacy/signer/src/key-management/google-key-provider.ts
  packages/phone-number-privacy/signer/src/key-management/key-provider-base.ts
  packages/phone-number-privacy/signer/src/key-management/key-provider.ts
  packages/phone-number-privacy/signer/src/salt-generation/get-salt.ts
  packages/phone-number-privacy/signer/test/index.test.ts
  packages/phone-number-privacy/signer/test/salt-generation/bls-signature.test.ts
  yarn.lock
Labels: automerge

#4102 [Wallet] Remove onPress delay in Touchable
  packages/mobile/src/language/Language.test.tsx
  packages/react-components/components/Button.test.tsx
  packages/react-components/components/SegmentedControl.test.tsx
  packages/react-components/components/Touchable.tsx
Labels: automerge

#4107 [PGPNP] Temporarily remove transaction (concurrency management)
  packages/phone-number-privacy/signer/src/database/wrappers/account.ts
  packages/phone-number-privacy/signer/src/salt-generation/get-salt.ts
  packages/phone-number-privacy/signer/src/salt-generation/query-quota.ts
  packages/phone-number-privacy/signer/test/salt-generation/query-quota.test.ts
Labels: automerge

#4110 Utils->0.1.16-dev ContractKit->0.4.7-dev Celocli->0.0.50-dev
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/leaderboard/package.json
  packages/metadata-crawler/package.json
  packages/mobile/package.json
  packages/protocol/package.json
  packages/react-components/package.json
  packages/utils/package.json
Labels: automerge

#4113 feat: allow passing initial accounts file to celotooljs geth start
  packages/celotool/src/cmds/geth/start.ts
Labels: automerge

#4119 [Wallet] Add revealed attestation event
  packages/mobile/src/identity/verification.ts
Labels: automerge

#4019 [Wallet] Animated balance in the Gold screen header
  packages/mobile/src/account/__snapshots__/Account.test.tsx.snap
  packages/mobile/src/account/__snapshots__/FiatExchange.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Invite.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Support.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap
  packages/mobile/src/exchange/CeloGoldHistoryChart.test.tsx
  packages/mobile/src/exchange/CeloGoldHistoryChart.tsx
  packages/mobile/src/exchange/ExchangeHomeScreen.tsx
  packages/mobile/src/exchange/__snapshots__/CeloGoldHistoryChart.test.tsx.snap
  packages/mobile/src/exchange/actions.ts
  packages/mobile/src/exchange/reducer.ts
  packages/mobile/src/firebase/saga.ts
  packages/mobile/src/home/WalletHome.tsx
  packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
  packages/mobile/src/navigator/DrawerTopBar.tsx
  packages/mobile/test/schemas.ts
  packages/react-components/components/ScrollContainer.tsx
  packages/react-components/icons/Hamburger.tsx
Labels: automerge

#4080 Update setup to match go version and ndk version
  SETUP.md
Labels: automerge

#4098 [Wallet] Fixing navigation related bugs
  packages/mobile/src/account/Account.tsx
  packages/mobile/src/account/EditProfile.tsx
  packages/mobile/src/account/Invite.tsx
  packages/mobile/src/account/__snapshots__/Account.test.tsx.snap
  packages/mobile/src/account/__snapshots__/FiatExchange.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Invite.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Support.test.tsx.snap
  packages/mobile/src/account/actions.ts
  packages/mobile/src/account/reducer.ts
  packages/mobile/src/backup/BackupIntroduction.test.tsx
  packages/mobile/src/backup/BackupIntroduction.tsx
  packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap
  packages/mobile/src/components/AccountNumber.tsx
  packages/mobile/src/components/AccountNumberCard.tsx
  packages/mobile/src/components/CancelButton.v2.tsx
  packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
  packages/mobile/src/icons/Hamburger.tsx
  packages/mobile/src/icons/HamburgerCard.tsx
  packages/mobile/src/icons/MenuBurger.tsx
  packages/mobile/src/identity/PhoneNumberLookupQuotaScreen.tsx
  packages/mobile/src/language/Language.test.tsx
  packages/mobile/src/language/Language.tsx
  packages/mobile/src/navigator/DrawerNavigator.tsx
  packages/mobile/src/navigator/DrawerTopBar.tsx
  packages/mobile/src/navigator/Headers.v2.tsx
  packages/mobile/src/navigator/NavigationService.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/send/ValidateRecipientAccount.tsx
  packages/mobile/src/send/__snapshots__/ValidateRecipientAccount.test.tsx.snap
  packages/mobile/src/transactions/TransactionFeedItem.tsx
  packages/mobile/src/transactions/UserSection.tsx
  packages/mobile/src/transactions/__snapshots__/ExchangeFeedItem.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransactionFeed.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransactionsList.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransferFeedItem.test.tsx.snap
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationLoadingScreen.test.tsx.snap
Labels: automerge, wallet, wallet-quality

#4123 [Wallet] Fix failed escrow payment fetch right after verification
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/geth/saga.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/web3/utils.ts
Labels: automerge

#4115 [PGPNP] Support for AWS Secrets Manager
  packages/phone-number-privacy/signer/README.md
  packages/phone-number-privacy/signer/package.json
  packages/phone-number-privacy/signer/src/config.ts
  packages/phone-number-privacy/signer/src/key-management/aws-key-provider.ts
  packages/phone-number-privacy/signer/src/key-management/key-provider.ts
  yarn.lock
Labels: automerge

#4109 [PGPNP] Fixes for signer and combiner
  packages/attestation-service/package.json
  packages/phone-number-privacy/combiner/migrations/20200330212224_create-accounts-table.ts
  packages/phone-number-privacy/combiner/package.json
  packages/phone-number-privacy/combiner/scripts/createThresholdBlsKeys.ts
  packages/phone-number-privacy/combiner/scripts/runMigrations.ts
  packages/phone-number-privacy/combiner/src/bls/bls-cryptography-client.ts
  packages/phone-number-privacy/combiner/src/common/error-utils.ts
  packages/phone-number-privacy/combiner/src/config.ts
  packages/phone-number-privacy/combiner/src/database/models/account.ts
  packages/phone-number-privacy/combiner/src/database/wrappers/account.ts
  packages/phone-number-privacy/combiner/src/salt-generation/get-threshold-salt.ts
  packages/phone-number-privacy/combiner/src/salt-generation/query-quota.ts
  packages/phone-number-privacy/combiner/test/index.test.ts
  packages/phone-number-privacy/combiner/test/salt-generation/bls-signature.test.ts
  packages/phone-number-privacy/combiner/test/salt-generation/query-quota.test.ts
  packages/phone-number-privacy/signer/.env
  packages/phone-number-privacy/signer/README.md
  packages/phone-number-privacy/signer/package.json
  packages/phone-number-privacy/signer/scripts/runMigrations.ts
  packages/phone-number-privacy/signer/src/bls/bls-cryptography-client.ts
  packages/phone-number-privacy/signer/src/config.ts
  packages/phone-number-privacy/signer/src/salt-generation/get-salt.ts
  packages/phone-number-privacy/signer/test/salt-generation/bls-signature.test.ts
  yarn.lock
Labels: automerge

#3319 Remove buggy total balance from CLI
  .github/CODEOWNERS
  cloudbuild.yaml
  dependency-graph.json
  packages/cli/src/commands/account/show-claimed-accounts.ts
  packages/contractkit/src/kit.ts
  packages/docs/developer-resources/contractkit/reference/classes/_kit_.contractkit.md
  packages/leaderboard/.gitignore
  packages/leaderboard/README.md
  packages/leaderboard/package.json
  packages/leaderboard/src/board.ts
  packages/leaderboard/src/upload.ts
  packages/leaderboard/tsconfig.json
  packages/metadata-crawler/lib/crawler.d.ts
  packages/metadata-crawler/lib/crawler.js
  packages/metadata-crawler/lib/crawler.js.map
  packages/metadata-crawler/lib/env.d.ts
  packages/metadata-crawler/lib/env.js
  packages/metadata-crawler/lib/env.js.map
  packages/metadata-crawler/lib/logger.d.ts
  packages/metadata-crawler/lib/logger.js
  packages/metadata-crawler/lib/logger.js.map
  yarn.lock
Labels: automerge

#4129 Update privacy related docs
  packages/docs/SUMMARY.md
  packages/docs/celo-codebase/protocol/README.md
  packages/docs/celo-codebase/protocol/identity/README.md
  packages/docs/celo-codebase/protocol/identity/phone-number-privacy.md
  packages/docs/celo-codebase/protocol/identity/privacy-research.md
  packages/docs/celo-codebase/protocol/privacy.md
Labels: automerge

#4133 [PGPNP] Add status endpoint to signer
  packages/phone-number-privacy/signer/package.json
  packages/phone-number-privacy/signer/src/config.ts
  packages/phone-number-privacy/signer/src/server.ts
Labels: automerge

#4134 Remove from Navigator.tsx screens defined DrawerNavigator.tsx
  packages/mobile/src/navigator/Navigator.tsx
Labels: automerge

#4089 Add OpenPGP keys for victor@clabs.co and add publishing guide
  developer_key_publishing.md
  packages/web/openpgpkey/celo.org/hu/td7ee519tko3tbrmh7zbixqmxi7rfww1
  packages/web/openpgpkey/clabs.co/hu/td7ee519tko3tbrmh7zbixqmxi7rfww1
  packages/web/openpgpkey/dev.celo.org/hu/td7ee519tko3tbrmh7zbixqmxi7rfww1
  packages/web/openpgpkey/staging.celo.org/hu/td7ee519tko3tbrmh7zbixqmxi7rfww1
Labels: automerge

#4124 [Wallet] Transaction feed improvements
  packages/mobile/src/escrow/reducer.ts
  packages/mobile/src/home/WalletHome.test.tsx
  packages/mobile/src/home/WalletHome.tsx
  packages/mobile/src/transactions/TransactionFeed.tsx
  packages/mobile/src/transactions/TransferFeedItem.test.tsx
  packages/mobile/src/transactions/TransferFeedItem.tsx
  packages/mobile/src/transactions/__snapshots__/TransferFeedItem.test.tsx.snap
  packages/mobile/src/transactions/actions.ts
  packages/mobile/src/transactions/reducer.ts
  packages/mobile/src/transactions/saga.ts
  packages/mobile/src/transactions/transferFeedUtils.ts
  packages/mobile/test/schemas.ts
Labels: automerge, wallet, wallet-quality

#4142 [pgpnp] fix combiner index tests
  packages/phone-number-privacy/combiner/test/index.test.ts
Labels: automerge

#4056 Mainnet Oracle env vars
  .env.baklava
  .env.rc1
  packages/celotool/src/lib/azure.ts
  packages/celotool/src/lib/oracle.ts
  packages/celotool/src/lib/utils.ts
Labels: automerge

#4141 [PGPNP] Add basic SSL support to signer and other improvements
  dockerfiles/phone-number-privacy/Dockerfile
  packages/phone-number-privacy/combiner/package.json
  packages/phone-number-privacy/combiner/scripts/createBlsKeyPair.ts
  packages/phone-number-privacy/combiner/scripts/createThresholdBlsKeys.ts
  packages/phone-number-privacy/combiner/scripts/run-migrations.ts
  packages/phone-number-privacy/combiner/scripts/runMigrations.ts
  packages/phone-number-privacy/signer/.env
  packages/phone-number-privacy/signer/.gitignore
  packages/phone-number-privacy/signer/README.md
  packages/phone-number-privacy/signer/package.json
  packages/phone-number-privacy/signer/scripts/create-bls-keys.ts
  packages/phone-number-privacy/signer/scripts/create-ssl-cert.sh
  packages/phone-number-privacy/signer/scripts/createBlsKeyPair.ts
  packages/phone-number-privacy/signer/scripts/run-migrations.ts
  packages/phone-number-privacy/signer/scripts/runMigrations.ts
  packages/phone-number-privacy/signer/src/common/logger.ts
  packages/phone-number-privacy/signer/src/config.ts
  packages/phone-number-privacy/signer/src/index.ts
  packages/phone-number-privacy/signer/src/server.ts
  packages/phone-number-privacy/signer/test/index.test.ts
  yarn.lock
Labels: automerge

#4143 Add promisifyGenerator and getContractKitAsync
  packages/mobile/__mocks__/src/web3/contracts.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/identity/contactMapping.test.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/invite/saga.test.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/pincode/utils.ts
  packages/mobile/src/tokens/saga.ts
  packages/mobile/src/utils/generators.ts
  packages/mobile/src/web3/contracts.ts
  packages/mobile/src/web3/gas.ts
  packages/mobile/src/web3/saga.test.ts
  packages/mobile/src/web3/utils.ts
Labels: automerge

#4148 updated rc1 and baklava env with latest docker tag post oracle upgrade
  .env.baklava
  .env.rc1
Labels: automerge

#4151 Alfajoresstaging deploy of eksportisto
  .env.alfajoresstaging
  packages/celotool/src/lib/eksportisto.ts
Labels: automerge

#4155 [PGPNP] Add support for MySql and MSSql to Signer
  packages/attestation-service/package.json
  packages/phone-number-privacy/signer/README.md
  packages/phone-number-privacy/signer/package.json
  packages/phone-number-privacy/signer/scripts/run-migrations.ts
  packages/phone-number-privacy/signer/src/config.ts
  packages/phone-number-privacy/signer/src/database/database.ts
  packages/phone-number-privacy/signer/src/index.ts
  packages/phone-number-privacy/signer/test/index.test.ts
  yarn.lock
Labels: automerge

#4145 [Wallet][ReDesign] Invite code screen
  packages/mobile/__mocks__/@react-navigation/native.ts
  packages/mobile/e2e/Transfer.spec.js
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/en-US/nuxNamePin1.json
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/es-419/nuxNamePin1.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/src/account/__snapshots__/AccountKeyEducation.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Education.test.tsx.snap
  packages/mobile/src/account/__snapshots__/GoldEducation.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupComplete.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupPhrase.test.tsx.snap
  packages/mobile/src/components/ClipboardAwarePasteButton.tsx
  packages/mobile/src/components/CodeInput.test.tsx
  packages/mobile/src/components/CodeInput.tsx
  packages/mobile/src/components/__snapshots__/CodeInput.test.tsx.snap
  packages/mobile/src/components/__snapshots__/CodeRow.test.tsx.snap
  packages/mobile/src/components/__snapshots__/Dialog.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentListItem.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentReminderSummaryNotification.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationScreen.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeReview.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeAmount.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeOptions.test.tsx.snap
  packages/mobile/src/home/__snapshots__/NotificationBox.test.tsx.snap
  packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
  packages/mobile/src/invite/EnterInviteCode.test.tsx
  packages/mobile/src/invite/EnterInviteCode.tsx
  packages/mobile/src/invite/__snapshots__/EnterInviteCode.test.tsx.snap
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/notifications/__snapshots__/SummaryNotification.test.tsx.snap
  packages/mobile/src/onboarding/contacts/__snapshots__/ImportContactsScreen.test.tsx.snap
  packages/mobile/src/onboarding/registration/__snapshots__/JoinCelo.test.tsx.snap
  packages/mobile/src/onboarding/registration/__snapshots__/RegulatoryTerms.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestListScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestSummaryNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListItem.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListScreen.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestSummaryNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestConfirmation.test.tsx.snap
  packages/mobile/src/send/Send.tsx
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/send/__snapshots__/ValidateRecipientAccount.test.tsx.snap
  packages/mobile/src/utils/useClipboard.ts
  packages/mobile/src/verify/__snapshots__/VerificationCodeRow.test.tsx.snap
  packages/react-components/components/Button.v2.tsx
  packages/react-components/components/Card.tsx
  packages/react-components/components/__snapshots__/Button.v2.test.tsx.snap
  packages/react-components/icons/Checkmark.tsx
  packages/react-components/styles/styles.v2.ts
Labels: automerge

#4162 [Wallet][ReDesign] Verification start screen
  packages/mobile/__mocks__/@react-navigation/stack.ts
  packages/mobile/__mocks__/react-native-safe-area-view.ts
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/verify/VerificationEducationScreen.test.tsx
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/VerificationLearnMoreDialog.tsx
  packages/mobile/src/verify/VerificationLearnMoreScreen.test.tsx
  packages/mobile/src/verify/VerificationLearnMoreScreen.tsx
  packages/mobile/src/verify/VerificationSkipDialog.tsx
  packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/VerificationLearnMoreScreen.test.tsx.snap
Labels: automerge

#4167 [Wallet] Fix e2e test
  packages/mobile/.env.test
  packages/mobile/e2e/Transfer.spec.js
  packages/mobile/src/components/Dialog.tsx
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/VerificationSkipDialog.tsx
  packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
Labels: automerge

#4171 [Wallet] Design changes from audit
  packages/mobile/android/app/src/main/assets/fonts/Jost-Book.ttf
  packages/mobile/android/app/src/main/assets/fonts/Jost-Medium.ttf
  packages/mobile/fonts/Jost-Book.ttf
  packages/mobile/fonts/Jost-Medium.ttf
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/ios/celo/Info.plist
  packages/mobile/react-native.config.js
  packages/mobile/src/account/__snapshots__/Account.test.tsx.snap
  packages/mobile/src/account/__snapshots__/AccountKeyEducation.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Education.test.tsx.snap
  packages/mobile/src/account/__snapshots__/FiatExchange.test.tsx.snap
  packages/mobile/src/account/__snapshots__/GoldEducation.test.tsx.snap
  packages/mobile/src/account/__snapshots__/InviteReview.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupPhrase.test.tsx.snap
  packages/mobile/src/components/Avatar.tsx
  packages/mobile/src/components/AvatarSelf.tsx
  packages/mobile/src/components/__snapshots__/Dialog.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/EscrowedPaymentReminderSummaryNotification.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationCard.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationScreen.test.tsx.snap
  packages/mobile/src/exchange/ExchangeHomeScreen.tsx
  packages/mobile/src/exchange/__snapshots__/CeloGoldOverview.test.tsx.snap
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeOptions.test.tsx.snap
  packages/mobile/src/home/__snapshots__/NotificationBox.test.tsx.snap
  packages/mobile/src/navigator/DrawerNavigator.tsx
  packages/mobile/src/navigator/Headers.v2.tsx
  packages/mobile/src/notifications/__snapshots__/SummaryNotification.test.tsx.snap
  packages/mobile/src/onboarding/contacts/__snapshots__/ImportContactsScreen.test.tsx.snap
  packages/mobile/src/onboarding/registration/__snapshots__/RegulatoryTerms.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/IncomingPaymentRequestSummaryNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestSummaryNotification.test.tsx.snap
  packages/mobile/src/paymentRequest/__snapshots__/PaymentRequestUnavailable.test.tsx.snap
  packages/mobile/src/qrcode/QRCode.tsx
  packages/mobile/src/qrcode/__snapshots__/NotAuthorizedView.test.tsx.snap
  packages/mobile/src/qrcode/__snapshots__/QRCode.test.tsx.snap
  packages/mobile/src/send/__snapshots__/ValidateRecipientAccount.test.tsx.snap
  packages/mobile/src/send/__snapshots__/ValidateRecipientIntro.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
  packages/react-components/components/AggregatedRequestsMessagingCard.tsx
  packages/react-components/components/Avatar.tsx
  packages/react-components/components/__snapshots__/Avatar.test.tsx.snap
  packages/react-components/components/__snapshots__/Button.v2.test.tsx.snap
  packages/react-components/components/__snapshots__/SectionHeadGold.test.tsx.snap
  packages/react-components/styles/colors.v2.tsx
  packages/react-components/styles/fonts.v2.tsx
Labels: automerge, wallet-redesign

#4172 [PGPNP] Add azure templates to facilitate deployments
  packages/phone-number-privacy/signer/azure-templates/README.md
  packages/phone-number-privacy/signer/azure-templates/container-parameters.json
  packages/phone-number-privacy/signer/azure-templates/container-template.json
  packages/phone-number-privacy/signer/azure-templates/db-parameters.json
  packages/phone-number-privacy/signer/azure-templates/db-template.json
  packages/phone-number-privacy/signer/azure-templates/frontdoor-template.json
Labels: automerge

#4176 [Wallet] Fix redundant logic found by Deepscan
  packages/mobile/index.js
  packages/mobile/src/backup/utils.ts
  packages/mobile/src/networkInfo/saga.ts
  packages/mobile/src/paymentRequest/utils.ts
  packages/mobile/src/pincode/Pincode.tsx
Labels: automerge

#4122 Update alfajoresstaging env and helm chart memory value
  .env.alfajoresstaging
  packages/celotool/src/lib/blockscout.ts
  packages/helm-charts/testnet/values.yaml
Labels: automerge

#4153 [PGPNP] Add timeout/logging for combiner request to signers
  packages/phone-number-privacy/combiner/src/common/error-utils.ts
  packages/phone-number-privacy/combiner/src/config.ts
  packages/phone-number-privacy/combiner/src/match-making/get-contact-matches.ts
  packages/phone-number-privacy/combiner/src/salt-generation/get-threshold-salt.ts
  packages/phone-number-privacy/combiner/test/end-to-end/get-blinded-salt.test.ts
  packages/phone-number-privacy/combiner/test/index.test.ts
  packages/phone-number-privacy/common/test/utils.ts
  packages/phone-number-privacy/signer/.env
  packages/phone-number-privacy/signer/README.md
  packages/phone-number-privacy/signer/src/config.ts
  packages/phone-number-privacy/signer/src/key-management/key-provider.ts
  packages/phone-number-privacy/signer/src/key-management/mock-key-provider.ts
  packages/phone-number-privacy/signer/src/salt-generation/get-salt.ts
  packages/phone-number-privacy/signer/test/index.test.ts
Labels: automerge

#4179 [Wallet][ReDesign] Verification input screen
  packages/mobile/locales/en-US/nuxVerification2.json
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/nuxVerification2.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/src/components/ClipboardAwarePasteButton.tsx
  packages/mobile/src/components/CodeInput.tsx
  packages/mobile/src/components/Dialog.tsx
  packages/mobile/src/components/__snapshots__/CodeInput.test.tsx.snap
  packages/mobile/src/invite/__snapshots__/EnterInviteCode.test.tsx.snap
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/verify/VerificationCodeInput.test.tsx
  packages/mobile/src/verify/VerificationCodeInput.tsx
  packages/mobile/src/verify/VerificationInputHelpDialog.tsx
  packages/mobile/src/verify/VerificationInputScreen.test.tsx
  packages/mobile/src/verify/VerificationInputScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationCodeInput.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/VerificationCodeRow.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/VerificationInputScreen.test.tsx.snap
Labels: automerge

#4173 Exchange Icons Fix / Gold Rename
  .gitignore
  packages/web/public/assets/CeloColorLogo.zip
  packages/web/public/assets/CeloColorLogoReverse.zip
  packages/web/public/assets/CeloGlyphs.zip
  packages/web/public/assets/CeloLogoPackage.zip
  packages/web/public/assets/CeloMarketplaceIcons.zip
  packages/web/public/assets/CeloMonochromeLogo.zip
  packages/web/public/assets/CeloMonochromeLogoReverse.zip
  packages/web/public/assets/marketplace-icons/CeloMarketplaceIcons.zip
  packages/web/public/assets/marketplace-icons/icon-CELO-color.zip
  packages/web/public/assets/marketplace-icons/icon-CELO-monochrome.zip
  packages/web/public/assets/marketplace-icons/icon-CELO-reverse-monochrome.zip
  packages/web/public/assets/marketplace-icons/icon-celo-dollar-color.zip
  packages/web/public/assets/marketplace-icons/icon-celo-dollar-full-color.zip
  packages/web/public/assets/marketplace-icons/icon-celo-dollar-monochrome.zip
  packages/web/public/assets/marketplace-icons/icon-celo-dollar-reverse-monochrome.zip
  packages/web/public/images/marketplace-icons/icon-celo-CELO-color-f.svg
  packages/web/public/papers/Celo_A_Multi_Asset_Cryptographic_Protocol_for_Decentralized_Social_Payments.pdf
  packages/web/public/papers/Celo_Stability_Analysis.pdf
  packages/web/public/papers/cLabs_CBDC_Velocity_v3.pdf
  packages/web/public/static/locales/en/brand.json
  packages/web/src/_page-tests/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/exchange-icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
  packages/web/src/experience/Markdown.tsx
  packages/web/src/experience/brandkit/IconsExchangePage.tsx
  packages/web/src/experience/brandkit/content/exchange-icons.md
  packages/web/src/experience/common/CCLicense.tsx
  packages/web/src/experience/eventkit/Tenents.tsx
  packages/web/src/home/TwoAssets.tsx
  packages/web/src/icons/ExchangeIconCELO.tsx
  packages/web/src/icons/ExchangeIconCGLD.tsx
Labels: automerge

#4202 Fix corrupt PDF + add henry as validator badge owner
  .github/CODEOWNERS
  packages/web/public/papers/Celo_A_Multi_Asset_Cryptographic_Protocol_for_Decentralized_Social_Payments.pdf
  packages/web/public/papers/Celo__A_Multi_Asset_Cryptographic_Protocol_for_Decentralized_Social_Payments.pdf
  packages/web/server/index.ts
Labels: automerge

#4177 [Wallet] [Redesign] New search text input
  packages/mobile/locales/en-US/sendFlow7.json
  packages/mobile/locales/es-419/sendFlow7.json
  packages/mobile/src/account/Invite.tsx
  packages/mobile/src/account/__snapshots__/Account.test.tsx.snap
  packages/mobile/src/account/__snapshots__/FiatExchange.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Invite.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Support.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap
  packages/mobile/src/home/SendOrRequestBar.tsx
  packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
  packages/mobile/src/icons/Search.tsx
  packages/mobile/src/navigator/DrawerNavigator.tsx
  packages/mobile/src/navigator/DrawerTopBar.tsx
  packages/mobile/src/pincode/PincodeEnter.test.tsx
  packages/mobile/src/pincode/PincodeEnter.tsx
  packages/mobile/src/pincode/PincodeLock.test.tsx
  packages/mobile/src/pincode/PincodeLock.tsx
  packages/mobile/src/send/Send.tsx
  packages/mobile/src/send/SendCallToAction.tsx
  packages/mobile/src/send/SendSearchInput.tsx
  packages/mobile/src/send/__snapshots__/SendCallToAction.test.tsx.snap
  packages/react-components/components/TextInput.v2.tsx
  packages/react-components/components/WithTextInputLabeling.tsx
Labels: automerge

#4078 [Wallet] Show errors during emulator installation
  .circleci/config.yml
  packages/mobile/android/build.gradle
  packages/mobile/e2e/conf/avd_conf.ini
  packages/mobile/package.json
  packages/mobile/scripts/install-android-tools.sh
  packages/mobile/scripts/install_android_emulator_image.sh
  packages/mobile/scripts/run_e2e.sh
  yarn.lock
Labels: automerge, wallet, wallet-quality

#4185 [Wallet Redesign] ImportContactsScreen redesign
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/onboarding/contacts/ImportContactsScreen.test.tsx
  packages/mobile/src/onboarding/contacts/ImportContactsScreen.tsx
  packages/mobile/src/onboarding/contacts/__snapshots__/ImportContactsScreen.test.tsx.snap
Labels: automerge, wallet, wallet-redesign

#4209 [Wallet] Add balance and contact tracking
  packages/mobile/src/analytics/constants.ts
  packages/mobile/src/identity/contactMapping.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/tokens/saga.ts
Labels: automerge

#4157 Replace Celo Gold with CELO and add warning about using Ethereum wallets
  packages/docs/GLOSSARY.md
  packages/docs/developer-resources/integrations/custody.md
  packages/docs/overview.md
Labels: automerge

#4169 Update running-a-validator-in-mainnet.md
  packages/docs/getting-started/running-a-validator-in-mainnet.md
Labels: docs

#4204 Simplify the validator badge claiming process
  packages/web/validator-badges/README.md
Labels: automerge, docs

#4201 [Wallet] Restore Account Key screen redesign
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/en-US/nuxRestoreWallet3.json
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/es-419/nuxRestoreWallet3.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/src/components/CodeInput.tsx
  packages/mobile/src/import/ImportWallet.test.tsx
  packages/mobile/src/import/ImportWallet.tsx
  packages/mobile/src/import/__snapshots__/ImportWallet.test.tsx.snap
  packages/mobile/src/navigator/Navigator.tsx
  packages/react-components/components/TextInput.v2.tsx
Labels: automerge

#4210 Upgrade oracles on mainnet & baklava to use OKCoin, improve upgrading process
  .env.baklava
  .env.oracledev
  .env.rc1
  packages/celotool/src/lib/aks-fullnode.ts
  packages/celotool/src/lib/azure.ts
  packages/celotool/src/lib/oracle.ts
  packages/helm-charts/oracle/values.yaml
Labels: automerge

#4117 [PGPNP] Signer cloud deployment documentation
  packages/phone-number-privacy/signer/docs/deploy-on-aws.md
  packages/phone-number-privacy/signer/docs/images/fargate-container-definition.png
  packages/phone-number-privacy/signer/docs/images/fargate-service-definition.png
  packages/phone-number-privacy/signer/docs/images/fargate-task-definition.png
  packages/phone-number-privacy/signer/src/config.ts
  packages/phone-number-privacy/signer/src/key-management/aws-key-provider.ts
Labels: automerge

#4072 Slim down the attestation service docker image
  dependency-graph.json
  dockerfiles/attestation-service/Dockerfile
  packages/attestation-service/package.json
  packages/dev-utils/package.json
  yarn.lock
Labels: automerge

#4213 [Wallet] Various onboarding fixes
  packages/mobile/src/components/Carousel.tsx
  packages/mobile/src/import/__snapshots__/ImportWallet.test.tsx.snap
  packages/mobile/src/invite/__snapshots__/EnterInviteCode.test.tsx.snap
  packages/mobile/src/navigator/Headers.v2.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/onboarding/contacts/__snapshots__/ImportContactsScreen.test.tsx.snap
  packages/mobile/src/onboarding/registration/__snapshots__/JoinCelo.test.tsx.snap
  packages/mobile/src/onboarding/registration/__snapshots__/RegulatoryTerms.test.tsx.snap
  packages/mobile/src/onboarding/success/OnboardingSuccessScreen.tsx
  packages/mobile/src/pincode/__snapshots__/PincodeSet.test.tsx.snap
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/VerificationInterstitialScreen.tsx
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/VerificationInputScreen.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/VerificationInterstitialScreen.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/VerificationLoadingScreen.test.tsx.snap
  packages/react-components/styles/colors.v2.tsx
Labels: automerge

#4219 [Wallet] Fix end to end test (search bar test id)
  packages/mobile/e2e/Transfer.spec.js
Labels: wallet, wallet-quality

#4208 [Wallet] Various bug fixes
  packages/mobile/ios/celo/Info.plist
  packages/mobile/locales/en-US/backupKeyFlow6.json
  packages/mobile/locales/en-US/inviteFlow11.json
  packages/mobile/locales/en-US/nuxVerification2.json
  packages/mobile/locales/es-419/backupKeyFlow6.json
  packages/mobile/locales/es-419/inviteFlow11.json
  packages/mobile/locales/es-419/nuxVerification2.json
  packages/mobile/package.json
  packages/mobile/src/account/SupportContact.tsx
  packages/mobile/src/components/AccountNumber.tsx
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/flags.ts
  packages/mobile/src/home/NotificationBox.test.tsx
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/home/__snapshots__/NotificationBox.test.tsx.snap
  packages/mobile/src/language/Language.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/__snapshots__/ValidateRecipientAccount.test.tsx.snap
  yarn.lock
Labels: automerge, wallet, wallet-quality

#4228 Deploy eksportisto on baklava
  .env.baklava
Labels: automerge

#4180 Celo Reserve Foundation Site
  .github/CODEOWNERS
  README.md
  dependency-graph.json
  packages/reserve-site/.env.local.enc
  packages/reserve-site/.gcloudignore
  packages/reserve-site/.gitignore
  packages/reserve-site/README.md
  packages/reserve-site/development.yaml
  packages/reserve-site/dispatch.yaml
  packages/reserve-site/next-env.d.ts
  packages/reserve-site/next.config.js
  packages/reserve-site/package.json
  packages/reserve-site/production.yaml
  packages/reserve-site/public/assets/CELO.png
  packages/reserve-site/public/assets/CUSD.png
  packages/reserve-site/public/assets/NCCExecutiveSummary.pdf
  packages/reserve-site/public/assets/open-graph.png
  packages/reserve-site/public/assets/stability-mech-illo.svg
  packages/reserve-site/public/assets/world-spin.gif
  packages/reserve-site/public/favicon.ico
  packages/reserve-site/src/components/Amount.tsx
  packages/reserve-site/src/components/Button.tsx
  packages/reserve-site/src/components/ChangeStory.tsx
  packages/reserve-site/src/components/Chevron.tsx
  packages/reserve-site/src/components/CopyIcon.tsx
  packages/reserve-site/src/components/Footer.tsx
  packages/reserve-site/src/components/Head.tsx
  packages/reserve-site/src/components/Heading.tsx
  packages/reserve-site/src/components/Holdings.tsx
  packages/reserve-site/src/components/Markdown.tsx
  packages/reserve-site/src/components/Navbar.tsx
  packages/reserve-site/src/components/ReserveAddresses.tsx
  packages/reserve-site/src/components/Section.tsx
  packages/reserve-site/src/components/TargetGraph.tsx
  packages/reserve-site/src/components/colors.ts
  packages/reserve-site/src/components/styles.tsx
  packages/reserve-site/src/content/home/about.md
  packages/reserve-site/src/content/home/attestations.md
  packages/reserve-site/src/content/home/initial-target.md
  packages/reserve-site/src/content/home/intro.md
  packages/reserve-site/src/content/meta-description.md
  packages/reserve-site/src/interfaces.d.ts
  packages/reserve-site/src/next-env.d.ts
  packages/reserve-site/src/pages/index.tsx
  packages/reserve-site/src/service/Data.ts
  packages/reserve-site/src/service/addresses.ts
  packages/reserve-site/src/service/airtable.ts
  packages/reserve-site/src/service/holdings.ts
  packages/reserve-site/tsconfig.json
  packages/web/src/_page-tests/__snapshots__/about.test.tsx.snap
  packages/web/src/about/VideoCover.tsx
  packages/web/src/shared/EX.tsx
  scripts/ci_check_dependency_graph_changed.sh
  scripts/key_placer.sh
  yarn.lock
Labels: automerge, web

#4212 [Wallet] Protect account key from Drawer Menu
  packages/mobile/src/navigator/DrawerNavigator.tsx
  packages/mobile/src/navigator/NavigationService.ts
Labels: automerge

#4161 [Wallet] [Redesign] Settings screen
  packages/mobile/android/app/src/main/assets/fonts/Jost-Regular.ttf
  packages/mobile/fonts/Jost-Regular.ttf
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/en-US/nuxNamePin1.json
  packages/mobile/locales/es-419/accountScreen10.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/es-419/nuxNamePin1.json
  packages/mobile/src/account/Account.tsx
  packages/mobile/src/account/Analytics.test.tsx
  packages/mobile/src/account/Analytics.tsx
  packages/mobile/src/account/DataSaver.test.tsx
  packages/mobile/src/account/DataSaver.tsx
  packages/mobile/src/account/EditProfile.test.tsx
  packages/mobile/src/account/FiatExchange.tsx
  packages/mobile/src/account/Profile.test.tsx
  packages/mobile/src/account/Profile.tsx
  packages/mobile/src/account/Security.tsx
  packages/mobile/src/account/Settings.test.tsx
  packages/mobile/src/account/Settings.tsx
  packages/mobile/src/account/SettingsItem.tsx
  packages/mobile/src/account/Support.tsx
  packages/mobile/src/account/__snapshots__/Account.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Analytics.test.tsx.snap
  packages/mobile/src/account/__snapshots__/DataSaver.test.tsx.snap
  packages/mobile/src/account/__snapshots__/EditProfile.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Invite.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Profile.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Settings.test.tsx.snap
  packages/mobile/src/account/__snapshots__/Support.test.tsx.snap
  packages/mobile/src/backup/BackupIntroduction.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/geth/saga.ts
  packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
  packages/mobile/src/language/Language.test.tsx
  packages/mobile/src/language/Language.tsx
  packages/mobile/src/localCurrency/SelectLocalCurrency.tsx
  packages/mobile/src/localCurrency/__snapshots__/SelectLocalCurrency.test.tsx.snap
  packages/mobile/src/navigator/DrawerNavigator.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/web3/saga.ts
  packages/react-components/components/ListItem.test.tsx
  packages/react-components/components/ListItem.tsx
  packages/react-components/components/SectionHeadNew.tsx
  packages/react-components/components/SelectionOption.tsx
  packages/react-components/components/SettingsItem.test.tsx
  packages/react-components/components/SettingsItem.tsx
  packages/react-components/components/SettingsSwitchItem.tsx
  packages/react-components/components/__snapshots__/ListItem.test.tsx.snap
  packages/react-components/components/__snapshots__/SectionHeadNew.test.tsx.snap
  packages/react-components/components/__snapshots__/SettingsItem.test.tsx.snap
  packages/react-components/icons/ForwardChevron.tsx
Labels: automerge

#4156 Add config files and commands for App Engine Dispatch Routes
  packages/web/dispatch-celo-testnet-production.yaml
  packages/web/dispatch-celo-testnet.yaml
  packages/web/package.json
Labels: automerge, web

#4218 [PGPNP] Log improvements for monitoring
  packages/phone-number-privacy/combiner/src/bls/bls-cryptography-client.ts
  packages/phone-number-privacy/combiner/src/common/constants.ts
  packages/phone-number-privacy/combiner/src/common/error-utils.ts
  packages/phone-number-privacy/combiner/src/common/identity.ts
  packages/phone-number-privacy/combiner/src/database/wrappers/account.ts
  packages/phone-number-privacy/combiner/src/database/wrappers/number-pairs.ts
  packages/phone-number-privacy/combiner/src/match-making/get-contact-matches.ts
  packages/phone-number-privacy/combiner/src/salt-generation/get-threshold-salt.ts
  packages/phone-number-privacy/signer/azure-templates/README.md
  packages/phone-number-privacy/signer/azure-templates/container-parameters.json
  packages/phone-number-privacy/signer/azure-templates/container-template.json
  packages/phone-number-privacy/signer/azure-templates/db-parameters.json
  packages/phone-number-privacy/signer/docs/deploy-on-azure.md
  packages/phone-number-privacy/signer/docs/images/fargate-container-definition.png
  packages/phone-number-privacy/signer/package.json
  packages/phone-number-privacy/signer/src/bls/bls-cryptography-client.ts
  packages/phone-number-privacy/signer/src/common/constants.ts
  packages/phone-number-privacy/signer/src/common/error-utils.ts
  packages/phone-number-privacy/signer/src/common/identity.ts
  packages/phone-number-privacy/signer/src/database/wrappers/account.ts
  packages/phone-number-privacy/signer/src/key-management/aws-key-provider.ts
  packages/phone-number-privacy/signer/src/key-management/azure-key-provider.ts
  packages/phone-number-privacy/signer/src/key-management/google-key-provider.ts
  packages/phone-number-privacy/signer/src/salt-generation/get-salt.ts
Labels: automerge

#4235 add mainnet links for forno & blockscout
  packages/docs/developer-resources/integrations/general.md
Labels: automerge, docs

#4233 Fix typo in Service Definition link
  packages/phone-number-privacy/signer/docs/deploy-on-aws.md
Labels: automerge

#4238 Utils->0.1.17-dev ContractKit->0.4.9-dev Celocli->0.0.52-dev
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/metadata-crawler/package.json
  packages/mobile/package.json
  packages/protocol/package.json
  packages/react-components/package.json
  packages/utils/package.json
Labels: automerge

#4220 [PGPNP] changes to support mainnet combiner
  packages/phone-number-privacy/combiner/package.json
  packages/phone-number-privacy/combiner/src/config.ts
  packages/phone-number-privacy/combiner/src/salt-generation/get-threshold-salt.ts
  packages/phone-number-privacy/combiner/test/salt-generation/bls-signature.test.ts
Labels: automerge

#4255 [contractkit] Fix gas price backwards compatibility
  packages/contractkit/src/utils/tx-params-normalizer.test.ts
  packages/contractkit/src/utils/tx-params-normalizer.ts
Labels: automerge

#4257 ContractKit->0.4.10-dev Celocli->0.0.53-dev
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/metadata-crawler/package.json
  packages/mobile/package.json
Labels: automerge

#4258 [cli] Fix exchange warning
  packages/cli/src/utils/exchange.ts
Labels: automerge

#4259 [cli] Celocli->0.0.54-dev
  packages/cli/package.json
Labels: automerge

#4229 Deploy eksportisto mainnet
  .env.baklava
  .env.rc1
Labels: automerge

#4237 [Wallet] Improve reliability for android end to end test (restore wallet screen)
  packages/mobile/e2e/Transfer.spec.js
Labels: automerge, wallet, wallet-quality

#4261 Copy change: Celo Gold -> CELO
  packages/mobile/locales/en-US/backupKeyFlow6.json
  packages/mobile/locales/en-US/exchangeFlow9.json
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/en-US/goldEducation.json
  packages/mobile/locales/en-US/inviteFlow11.json
  packages/mobile/locales/en-US/nuxNamePin1.json
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/locales/es-419/backupKeyFlow6.json
  packages/mobile/locales/es-419/exchangeFlow9.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/es-419/goldEducation.json
  packages/mobile/locales/es-419/inviteFlow11.json
  packages/mobile/locales/es-419/nuxNamePin1.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/locales/es-419/walletFlow5.json
  packages/mobile/src/account/GoldEducation.tsx
  packages/mobile/src/account/__snapshots__/GoldEducation.test.tsx.snap
  packages/mobile/src/analytics/constants.ts
Labels: automerge

#4260 [PGPNP] Update DB defaults
  packages/phone-number-privacy/signer/azure-templates/README.md
Labels: automerge

#4234 Reserve Web Legal Pages
  packages/reserve-site/development.yaml
  packages/reserve-site/package.json
  packages/reserve-site/production.yaml
  packages/reserve-site/public/assets/unique.png
  packages/reserve-site/src/components/Footer.tsx
  packages/reserve-site/src/components/Head.tsx
  packages/reserve-site/src/components/Updated.tsx
  packages/reserve-site/src/components/styles.tsx
  packages/reserve-site/src/content/home/about.md
  packages/reserve-site/src/content/home/intro.md
  packages/reserve-site/src/content/legal/privacy.md
  packages/reserve-site/src/content/legal/terms.md
  packages/reserve-site/src/content/meta-description.md
  packages/reserve-site/src/pages/404.tsx
  packages/reserve-site/src/pages/index.tsx
  packages/reserve-site/src/pages/legal/[doc].tsx
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/exchange-icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/shared/Footer.tsx
  packages/web/src/shared/__snapshots__/Footer.test.tsx.snap
  packages/web/src/shared/menu-items.ts
  yarn.lock
Labels: automerge, web

#4267 [Wallet][PGPNP] Fix wallet mainnet pgpnp configs and add combiner logs
  packages/mobile/src/geth/networkConfig.ts
  packages/phone-number-privacy/combiner/src/salt-generation/get-threshold-salt.ts
Labels: automerge

#4272 Update cohort 3 deadline
  packages/docs/operations-manual/celo-foundation-voting-policy.md
Labels: docs

#4271 Add amount to Moonpay window
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/fiatExchanges/MoonPay.test.tsx
  packages/mobile/src/fiatExchanges/MoonPay.tsx
  packages/mobile/src/navigator/types.tsx
  packages/moonpay-auth/src/index.ts
Labels: automerge

#4270 [Wallet] Empty wallet + some bugfix
  packages/mobile/__mocks__/src/navigator/NavigationService.ts
  packages/mobile/locales/en-US/nuxRestoreWallet3.json
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/locales/es-419/nuxRestoreWallet3.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/src/account/AccountKeyEducation.tsx
  packages/mobile/src/backup/BackupSocialIntro.tsx
  packages/mobile/src/components/Dialog.tsx
  packages/mobile/src/exchange/ExchangeHomeScreen.tsx
  packages/mobile/src/exchange/reducer.ts
  packages/mobile/src/exchange/saga.ts
  packages/mobile/src/firebase/saga.ts
  packages/mobile/src/import/ImportWallet.tsx
  packages/mobile/src/import/ImportWalletEmpty.test.tsx
  packages/mobile/src/import/ImportWalletEmpty.tsx
  packages/mobile/src/import/__snapshots__/ImportWallet.test.tsx.snap
  packages/mobile/src/import/__snapshots__/ImportWalletEmpty.test.tsx.snap
  packages/mobile/src/import/actions.ts
  packages/mobile/src/import/reducer.ts
  packages/mobile/src/import/saga.test.ts
  packages/mobile/src/import/saga.ts
  packages/mobile/src/invite/EnterInviteCode.tsx
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/navigator/NavigationService.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/transactions/NoActivity.tsx
  packages/mobile/src/transactions/__snapshots__/NoActivity.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransactionFeed.test.tsx.snap
Labels: automerge

#4265 Update mainnet westus cluster
  .env.rc1
Labels: automerge

#4276 [PGPNP] Fix aws keystore response handling and add a test
  packages/phone-number-privacy/signer/README.md
  packages/phone-number-privacy/signer/src/config.ts
  packages/phone-number-privacy/signer/src/key-management/aws-key-provider.ts
  packages/phone-number-privacy/signer/src/key-management/key-provider-base.ts
  packages/phone-number-privacy/signer/test/key-management/aws-key-provider.test.ts
Labels: automerge
