Repository celo-org/celo-monorepo, pull requests merged in 2020-10, with the labels that each got.

#5227 Changes to doc for release 1.1.0
  packages/docs/getting-started/running-a-full-node-in-baklava.md
  packages/docs/getting-started/running-a-validator-in-baklava.md
Labels: automerge

#5246 Image fix for iOS 14
  package.json
  patches/react-native+0.62.2.patch
  yarn.lock
Labels: automerge, wallet

#5247 Celo Flowers missing Link
  packages/web/src/flower/SideBar.tsx
Labels: automerge

#5226 Update README.md
  packages/docs/README.md
Labels: automerge

#5254 Fix Contract versioning CI checks on master
  .circleci/config.yml
  packages/protocol/contracts/common/Signatures.sol
  packages/protocol/package.json
Labels: automerge

#5253 Add docs link to Attestation Service 1.0.5
  packages/docs/operations-manual/attestation-service.md
Labels: automerge

#5263 [Wallet] Include phone number in DappKit auth
  packages/mobile/locales/en-US/dappkit.json
  packages/mobile/locales/es-419/dappkit.json
  packages/mobile/src/dappkit/DappKitAccountScreen.tsx
Labels: automerge

#5272 celo.org SEO
  packages/web/public/static/locales/en/terms.json
  packages/web/src/_page-tests/__snapshots__/about.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/jobs.test.tsx.snap
  packages/web/src/about/VideoCover.tsx
  packages/web/src/content/brand-policy.md
  packages/web/src/experience/Markdown.tsx
  packages/web/src/header/OpenGraph.tsx
  packages/web/src/join/JoinPage.tsx
  packages/web/src/terms/BrandPolicy.tsx
  packages/web/src/utils/utils.ts
Labels: automerge

#5284 Update "monetary system" to "financial system"
  packages/web/public/static/locales/en/community.json
  packages/web/public/static/locales/en/jobs.json
  packages/web/src/_page-tests/__snapshots__/community.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/jobs.test.tsx.snap
  packages/web/src/community/CommunityPage.tsx
  packages/web/src/join/FeaturedVideo.tsx
  packages/web/src/join/JoinPage.tsx
Labels: automerge

#5238 Validator Explorer Improvements
  packages/web/README.md
  packages/web/public/images/marketplace-icons/icon-celo-CELO-mono-f.svg
  packages/web/public/images/marketplace-icons/icon-celo-CELO-reverse-f.svg
  packages/web/src/_page-tests/validators/__snapshots__/explore.test.tsx.snap
  packages/web/src/_page-tests/validators/explore.test.tsx
  packages/web/src/dev/ValidatorsList.tsx
  packages/web/src/dev/ValidatorsListApp.tsx
  packages/web/src/dev/ValidatorsListRow.tsx
  packages/web/src/dev/ValidatorsListStyles.tsx
  packages/web/src/utils/validators.ts
Labels: automerge

#5282 cli->0.0.59-dev & Utils->0.1.22-dev & ContractKit->0.4.16-dev
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/metadata-crawler/package.json
  packages/mobile/package.json
  packages/phone-number-privacy/common/package.json
  packages/protocol/package.json
  packages/react-components/package.json
  packages/utils/package.json
Labels: devX

#5111 Scripts for verifying bytecodes
  .circleci/config.yml
  packages/cli/src/commands/governance/show.ts
  packages/contractkit/src/explorer/block-explorer.ts
  packages/contractkit/src/governance/proxy.ts
  packages/docs/celo-codebase/protocol/governance.md
  packages/docs/command-line-interface/governance.md
  packages/docs/community/release-process/smart-contracts.md
  packages/docs/developer-resources/contractkit/reference/modules/_governance_proxy_.md
  packages/protocol/package.json
  packages/protocol/scripts/bash/check-versions.sh
  packages/protocol/scripts/bash/console.sh
  packages/protocol/scripts/bash/make-release.sh
  packages/protocol/scripts/bash/verify-deployed.sh
  packages/protocol/scripts/bash/verify-release.sh
  packages/protocol/scripts/check-backward.ts
  packages/protocol/scripts/truffle/verify-bytecode.ts
  packages/protocol/truffle-config.js
Labels: automerge

#5094 [Wallet] Adding Geth connectivity checks as part of getContractKit
  packages/mobile/__mocks__/redux-persist.ts
  packages/mobile/src/geth/saga.ts
  packages/mobile/src/tokens/saga.ts
  packages/mobile/src/web3/contracts.ts
  packages/mobile/src/web3/saga.test.ts
  packages/mobile/src/web3/saga.ts
  packages/mobile/src/web3/utils.ts
Labels: automerge, wallet

#5299 Language/Timezone Bug Fix
  packages/mobile/src/utils/time.ts
Labels: automerge, wallet

#5304 Build wallet command that builds with relevant dependencies only
  package.json
Labels: automerge, wallet

#5302 Removing some dead code from Valora
  packages/mobile/locales/en-US/backupKeyFlow6.json
  packages/mobile/locales/en-US/inviteFlow11.json
  packages/mobile/locales/en-US/nuxRestoreWallet3.json
  packages/mobile/locales/es-419/backupKeyFlow6.json
  packages/mobile/locales/es-419/inviteFlow11.json
  packages/mobile/locales/es-419/nuxRestoreWallet3.json
  packages/mobile/src/account/Invite.test.tsx
  packages/mobile/src/account/Invite.tsx
  packages/mobile/src/account/InviteReview.test.tsx
  packages/mobile/src/account/InviteReview.tsx
  packages/mobile/src/account/__snapshots__/Invite.test.tsx.snap
  packages/mobile/src/account/__snapshots__/InviteReview.test.tsx.snap
  packages/mobile/src/account/actions.ts
  packages/mobile/src/account/reducer.ts
  packages/mobile/src/account/saga.ts
  packages/mobile/src/account/selectors.ts
  packages/mobile/src/backup/BackupComplete.test.tsx
  packages/mobile/src/backup/BackupComplete.tsx
  packages/mobile/src/backup/BackupPhraseContainer.test.tsx
  packages/mobile/src/backup/BackupPhraseContainer.tsx
  packages/mobile/src/backup/BackupSocial.test.tsx
  packages/mobile/src/backup/BackupSocial.tsx
  packages/mobile/src/backup/BackupSocialIntro.test.tsx
  packages/mobile/src/backup/BackupSocialIntro.tsx
  packages/mobile/src/backup/__snapshots__/BackupComplete.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupPhraseContainer.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupSocial.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupSocialIntro.test.tsx.snap
  packages/mobile/src/backup/utils.ts
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/home/WalletHome.test.tsx
  packages/mobile/src/home/WalletHome.tsx
  packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
  packages/mobile/src/import/ImportWalletSocial.test.tsx
  packages/mobile/src/import/ImportWalletSocial.tsx
  packages/mobile/src/import/__snapshots__/ImportWalletSocial.test.tsx.snap
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
Labels: automerge, wallet

#5292 [Wallet] Fix fetching verification state during onboarding
  packages/mobile/src/import/saga.ts
  packages/mobile/src/verify/VerificationEducationScreen.tsx
Labels: automerge, wallet

#5290 [Wallet] Fix empty completed Attestations
  packages/mobile/src/identity/reducer.ts
Labels: automerge

#5205 doc: Create Listings Guide
  packages/docs/developer-resources/integrations/listings.md
Labels: automerge

#5301 Fix network:contracts CLI command
  packages/cli/package.json
  packages/cli/src/commands/network/contracts.ts
  packages/contractkit/src/address-registry.ts
  packages/docs/command-line-interface/network.md
  packages/docs/command-line-interface/registry.md
  packages/docs/developer-resources/contractkit/reference/classes/_address_registry_.addressregistry.md
Labels: automerge

#5154 [Wallet] Add display names of scanned QRs to cache
  packages/mobile/__mocks__/react-i18next.js
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/send/utils.ts
  packages/mobile/src/transactions/TransferFeedItem.test.tsx
  packages/mobile/src/transactions/TransferFeedItem.tsx
  packages/mobile/src/transactions/__snapshots__/TransferFeedItem.test.tsx.snap
  packages/mobile/src/transactions/transferFeedUtils.ts
  packages/mobile/test/schemas.ts
Labels: automerge, wallet

#5313 [web] Kit Fixes
  packages/web/src/experience/contentful/getServerSideProps.ts
  packages/web/src/utils/contentful.ts
Labels: automerge

#5316 [celotool] Add celostats config for multiproxy
  packages/helm-charts/common/templates/_helpers.tpl
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
Labels: automerge

#5206 doc: Update Standard Criteria with Performance Score
  packages/docs/operations-manual/celo-foundation-voting-policy.md
Labels: automerge

#4688 added cUSD documentation
  packages/docs/SUMMARY.md
  packages/docs/celo-holder-guide/cusd.md
Labels: automerge, docs

#5314 Add gpg key
  packages/docs/community/release-process/blockchain-client.md
  packages/web/openpgpkey/README.md
  packages/web/openpgpkey/clabs.co/hu/44ki5f3bkanunj4czd4o97ciig6uuiux
Labels: automerge

#5327 doc: Update alfajores full node doc
  packages/docs/getting-started/running-a-full-node-in-alfajores.md
Labels: automerge

#5332 Fix typo in brand.json
  packages/web/public/static/locales/en/brand.json
Labels: automerge

#5319 Add blockchain parameters to kit network config
  packages/celotool/src/e2e-tests/blockchain_parameters_tests.ts
  packages/contractkit/src/kit.ts
  packages/contractkit/src/wrappers/BlockchainParameters.ts
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/classes/_kit_.contractkit.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_blockchainparameters_.blockchainparameterswrapper.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_kit_.kitoptions.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_kit_.networkconfig.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_blockchainparameters_.blockchainparametersconfig.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_blockchainparameters_.clientversion.md
  packages/docs/developer-resources/contractkit/reference/modules/_kit_.md
  packages/docs/developer-resources/contractkit/reference/modules/_wrappers_blockchainparameters_.md
Labels: automerge

#5337 Allow user to use AWS HSM Wallet without having DescribeKey permission for all keys
  packages/contractkit/src/wallets/aws-hsm-wallet.test.ts
  packages/contractkit/src/wallets/aws-hsm-wallet.ts
  packages/contractkit/src/wallets/signers/aws-hsm-signer.ts
  packages/docs/developer-resources/contractkit/reference/classes/_wallets_aws_hsm_wallet_.awshsmwallet.md
Labels: automerge

#5346 Exclude unversioned contracts
  packages/protocol/migrationsConfig.js
  packages/protocol/scripts/bash/check-versions.sh
Labels: automerge

#5340 Remove version numbers from wrong contracts/libraries
  packages/protocol/contracts/common/FixidityLib.sol
  packages/protocol/contracts/common/UsingPrecompiles.sol
  packages/protocol/contracts/common/proxies/FixidityLibProxy.sol
  packages/protocol/contracts/governance/SlasherUtil.sol
Labels: automerge

#5266 Select static node based on region resolved from timezone
  packages/celotool/src/lib/fullnodes.ts
  packages/contractkit/scripts/fetch_timezones.ts
  packages/contractkit/src/network-utils/static-node-utils.test.ts
  packages/contractkit/src/network-utils/static-node-utils.ts
  packages/contractkit/src/utils/timezone.ts
  packages/contractkit/src/utils/timezones.json
  packages/contractkit/tsconfig.json
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/classes/_network_utils_static_node_utils_.staticnodeutils.md
  packages/docs/developer-resources/contractkit/reference/globals.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_utils_timezone_.coordinates.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_utils_timezone_.timezone.md
  packages/docs/developer-resources/contractkit/reference/modules/_utils_timezone_.md
  packages/mobile/__mocks__/@celo/contractkit/index.ts
  packages/mobile/__mocks__/react-native-localize.ts
  packages/mobile/scripts/run_app.sh
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/geth/geth.ts
  packages/mobile/src/geth/saga.test.ts
  packages/mobile/src/web3/saga.ts
Labels: automerge

#5347 Fix make-release args
  packages/docs/community/release-process/smart-contracts.md
  packages/protocol/scripts/bash/make-release.sh
Labels: automerge

#5398 Add positive output to the verify-bytecodes script
  packages/protocol/lib/compatibility/verify-bytecode.ts
  packages/protocol/scripts/truffle/verify-bytecode.ts
Labels: automerge

#5413 [Wallet] Support push notifications with an "open url" semantic
  packages/mobile/src/alert/AlertBanner.test.tsx
  packages/mobile/src/alert/AlertBanner.tsx
  packages/mobile/src/alert/__snapshots__/AlertBanner.test.tsx.snap
  packages/mobile/src/alert/actions.ts
  packages/mobile/src/alert/reducer.ts
  packages/mobile/src/app/actions.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/firebase/notifications.test.ts
  packages/mobile/src/firebase/notifications.ts
  packages/mobile/src/home/WalletHome.test.tsx
  packages/mobile/src/home/WalletHome.tsx
  packages/mobile/src/send/SendAmount.test.tsx
  packages/mobile/src/shared/__snapshots__/BackupPrompt.test.tsx.snap
  packages/react-components/components/SmartTopAlert.tsx
  packages/react-components/components/__snapshots__/SmartTopAlert.test.tsx.snap
Labels: automerge

#5418 Suppress dependent output in verify-bytecode/check-versions/verify-release
  packages/protocol/scripts/bash/check-versions.sh
  packages/protocol/scripts/bash/make-release.sh
  packages/protocol/scripts/bash/verify-deployed.sh
  packages/protocol/scripts/bash/verify-release.sh
  packages/protocol/scripts/check-backward.ts
Labels: automerge

#5415 [Wallet] Allow up to 1% difference on exchange rate for exchanging CELO
  packages/mobile/src/exchange/saga.ts
Labels: automerge, wallet

#5419 Fix the make-release script
  packages/protocol/scripts/bash/make-release.sh
  packages/protocol/scripts/truffle/make-release.ts
Labels: automerge

#5422 Metadata crawler posts to Discord
  .env.mnemonic.rc1.enc
  .env.rc1
  packages/celotool/src/lib/blockscout.ts
  packages/celotool/src/lib/env-utils.ts
  packages/helm-charts/blockscout/templates/blockscout-metadata-crawler.cronjob.yaml
  packages/metadata-crawler/src/crawler.ts
Labels: automerge

#5423 Return to original commit before running script in check-versions
  packages/protocol/scripts/bash/check-versions.sh
Labels: automerge

#5441 Add flag to verify-deployed
  packages/protocol/scripts/bash/verify-deployed.sh
Labels: automerge

#5440 Deploy Attestation Service 1.0.5 to cLabs validators on baklava
  .env.baklava
  .env.mnemonic.baklava.enc
  packages/celotool/src/lib/attestation-service.ts
  packages/helm-charts/attestation-service/templates/attestation.secret.yaml
Labels: automerge

#5438 [Wallet] Allow skipping verification if ODIS is down
  packages/mobile/src/verify/VerificationEducationScreen.test.tsx
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
Labels: automerge, wallet

#5345 Add fee estimation for Withdrawing CELO and pay for Withdrawing and Selling CELO fees in CELO
  packages/mobile/src/components/CeloAmountInput.tsx
  packages/mobile/src/exchange/WithdrawCeloReviewScreen.test.tsx
  packages/mobile/src/exchange/WithdrawCeloReviewScreen.tsx
  packages/mobile/src/exchange/WithdrawCeloScreen.test.tsx
  packages/mobile/src/exchange/WithdrawCeloScreen.tsx
  packages/mobile/src/exchange/WithdrawCeloSummary.test.tsx
  packages/mobile/src/exchange/WithdrawCeloSummary.tsx
  packages/mobile/src/exchange/__snapshots__/WithdrawCeloReviewScreen.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/WithdrawCeloSummary.test.tsx.snap
  packages/mobile/src/exchange/saga.ts
  packages/mobile/src/fees/CalculateFee.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/saga.ts
  packages/mobile/src/transactions/saga.ts
  packages/mobile/src/transactions/send.ts
Labels: automerge, wallet

#5293 Adding changelogs to cli, utils, dappkit, contractkit, and base packages & publishing a release process
  packages/base/CHANGELOG.md
  packages/cli/CHANGELOG.md
  packages/contractkit/CHANGELOG.md
  packages/dappkit/CHANGELOG.md
  packages/docs/community/release-process/README.md
  packages/docs/community/release-process/base-cli-contractkit-dappkit-utils.md
  packages/docs/community/release-process/blockchain-client.md
  packages/utils/CHANGELOG.md
Labels: devX, docs

#5482 Grant Kit part 2
  packages/web/src/experience/contentful/nodes.tsx
  packages/web/src/experience/grants/IdeaReadiness.tsx
  packages/web/src/experience/grants/JourneySteps.tsx
Labels: automerge

#5430 [Wallet] Prevent exiting force update screen
  packages/mobile/src/app/UpgradeScreen.tsx
  packages/mobile/src/app/__snapshots__/ErrorScreen.test.tsx.snap
  packages/mobile/src/app/actions.ts
  packages/mobile/src/app/reducers.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/navigator/NavigatorWrapper.tsx
  packages/mobile/src/redux/sagas.ts
  packages/mobile/test/schemas.ts
  packages/react-components/components/FullscreenCTA.tsx
  packages/react-components/components/__snapshots__/FullscreenCTA.test.tsx.snap
Labels: automerge, wallet

#5481 Make initialization of the proxy part of the governance proposal
  packages/contractkit/src/governance/proposals.ts
  packages/docs/developer-resources/contractkit/reference/classes/_governance_proposals_.interactiveproposalbuilder.md
  packages/docs/developer-resources/contractkit/reference/classes/_governance_proposals_.proposalbuilder.md
  packages/protocol/lib/compatibility/verify-bytecode.ts
  packages/protocol/scripts/bash/make-release.sh
  packages/protocol/scripts/truffle/make-release.ts
  packages/protocol/test/compatibility/verify-bytecode.ts
  packages/protocol/truffle-config.js
Labels: automerge

#5500 add a redirect for grantKit for convienence
  packages/web/server/index.ts
Labels: automerge

#5449 Fix upgrade proposal decoding
  packages/contractkit/src/address-registry.ts
  packages/contractkit/src/base.ts
  packages/contractkit/src/explorer/base.ts
  packages/contractkit/src/explorer/block-explorer.ts
  packages/contractkit/src/governance/proposals.ts
  packages/contractkit/src/governance/proxy.ts
  packages/contractkit/src/web3-contract-cache.ts
  packages/docs/developer-resources/contractkit/reference/classes/_explorer_block_explorer_.blockexplorer.md
  packages/docs/developer-resources/contractkit/reference/classes/_governance_proposals_.interactiveproposalbuilder.md
  packages/docs/developer-resources/contractkit/reference/classes/_governance_proposals_.proposalbuilder.md
  packages/docs/developer-resources/contractkit/reference/classes/_web3_contract_cache_.web3contractcache.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_explorer_block_explorer_.calldetails.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_explorer_block_explorer_.parsedblock.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_explorer_block_explorer_.parsedtx.md
  packages/docs/developer-resources/contractkit/reference/modules/_base_.md
  packages/docs/developer-resources/contractkit/reference/modules/_explorer_base_.md
  packages/docs/developer-resources/contractkit/reference/modules/_explorer_block_explorer_.md
  packages/docs/developer-resources/contractkit/reference/modules/_governance_proxy_.md
Labels: automerge

#5501 Add developer tools overview to docs
  packages/docs/developer-resources/overview.md
  packages/docs/developer-resources/start.md
Labels: automerge, devX, docs

#5495 Add details from fix #5301 to CLI and ContractKit ChangeLog
  packages/cli/CHANGELOG.md
  packages/contractkit/CHANGELOG.md
Labels: automerge

#5490 [Wallet] Fix packager not opening in new window when using default Terminal app on OSX
  packages/mobile/scripts/launch_packager.command
  packages/mobile/scripts/run_app.sh
Labels: automerge

#5489 Update attestation bot for ODIS
  .env.baklava
  packages/celotool/src/cmds/account/verify.ts
  packages/celotool/src/cmds/bots/auto-verify.ts
  packages/celotool/src/lib/attestation.ts
  packages/celotool/src/lib/env-utils.ts
  packages/helm-charts/attestation-bot/templates/statefulset.yaml
Labels: automerge

#5507 Defer setImplementation to proposal execution time
  packages/contractkit/src/explorer/base.ts
  packages/contractkit/src/explorer/block-explorer.ts
  packages/contractkit/src/governance/proposals.ts
  packages/contractkit/src/governance/proxy.ts
  packages/contractkit/src/web3-contract-cache.ts
  packages/docs/developer-resources/contractkit/reference/classes/_explorer_block_explorer_.blockexplorer.md
  packages/docs/developer-resources/contractkit/reference/classes/_governance_proposals_.interactiveproposalbuilder.md
  packages/docs/developer-resources/contractkit/reference/classes/_governance_proposals_.proposalbuilder.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_explorer_block_explorer_.calldetails.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_explorer_block_explorer_.parsedblock.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_explorer_block_explorer_.parsedtx.md
  packages/docs/developer-resources/contractkit/reference/modules/_explorer_base_.md
  packages/docs/developer-resources/contractkit/reference/modules/_explorer_block_explorer_.md
  packages/docs/developer-resources/contractkit/reference/modules/_governance_proposals_.md
  packages/docs/developer-resources/contractkit/reference/modules/_governance_proxy_.md
  packages/protocol/scripts/truffle/make-release.ts
Labels: automerge

#5519 Fix path casing leading to decryption failure on Linux
  packages/mobile/android/app/src/mainnetdev/google-services.json.enc
Labels: automerge

#5156 MetaTransactionWallet ContractKit wrapper
  packages/contractkit/src/base.ts
  packages/contractkit/src/contract-cache.ts
  packages/contractkit/src/kit.test.ts
  packages/contractkit/src/kit.ts
  packages/contractkit/src/web3-contract-cache.ts
  packages/contractkit/src/wrappers/MetaTransactionWallet.test.ts
  packages/contractkit/src/wrappers/MetaTransactionWallet.ts
  packages/contractkit/tsconfig.json
  packages/contractkit/types/web3-celo.d.ts
  packages/dev-utils/src/ganache-setup.ts
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/classes/_contract_cache_.wrappercache.md
  packages/docs/developer-resources/contractkit/reference/classes/_kit_.contractkit.md
  packages/docs/developer-resources/contractkit/reference/classes/_web3_contract_cache_.web3contractcache.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_basewrapper_.basewrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_metatransactionwallet_.metatransactionwalletwrapper.md
  packages/docs/developer-resources/contractkit/reference/enums/_base_.celocontract.md
  packages/docs/developer-resources/contractkit/reference/globals.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_kit_.kitoptions.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_kit_.networkconfig.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_metatransactionwallet_.rawtransaction.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_metatransactionwallet_.transactionobjectwithvalue.md
  packages/docs/developer-resources/contractkit/reference/modules/_base_.md
  packages/docs/developer-resources/contractkit/reference/modules/_contract_cache_.md
  packages/docs/developer-resources/contractkit/reference/modules/_kit_.md
  packages/docs/developer-resources/contractkit/reference/modules/_web3_contract_cache_.md
  packages/docs/developer-resources/contractkit/reference/modules/_wrappers_metatransactionwallet_.md
  packages/protocol/scripts/build.ts
Labels: automerge

#5517 Change CLI outputs from red to yellow keys
  packages/cli/src/utils/cli.ts
Labels: automerge

#5336 Fix celocli's attestation service test result output
  packages/cli/src/commands/identity/test-attestation-service.ts
Labels: automerge

#5523 Remove MTW from CK registered contracts
  packages/contractkit/src/base.ts
  packages/docs/developer-resources/contractkit/reference/modules/_base_.md
Labels: automerge

#5445 Update Docs for Datadirectory on Testnets
  packages/docs/getting-started/running-a-full-node-in-alfajores.md
  packages/docs/getting-started/running-a-full-node-in-baklava.md
  packages/docs/getting-started/running-a-validator-in-baklava.md
Labels: automerge

#5518 ContractKit contract caching doesn't work for non-singleton contracts
  packages/contractkit/src/contract-cache.test.ts
  packages/contractkit/src/contract-cache.ts
Labels: automerge

#5512 Update Governance documentation to reflect Mainnet
  packages/docs/GLOSSARY.md
  packages/docs/celo-codebase/protocol/governance.md
Labels: automerge

#5535 Upgrade node-fetch
  packages/attestation-proxy/package.json
  packages/celotool/package.json
  packages/notification-service/package.json
  packages/phone-number-privacy/combiner/package.json
  packages/protocol/package.json
  yarn.lock
Labels: automerge

#5529 Add check for valid transactions to verify release
  packages/protocol/lib/compatibility/verify-bytecode.ts
  packages/protocol/test/compatibility/verify-bytecode.ts
Labels: automerge

#5539 [Wallet] Fix Play Store upload
  packages/mobile/fastlane/Fastfile
Labels: automerge, wallet

#5540 [Wallet] Bump app number to latest released version (v1.2.0)
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
Labels: automerge

#5112 Display currency of payment request without changing local currency settings
  packages/mobile/src/components/CurrencyDisplay.tsx
  packages/mobile/src/components/FeeDrawer.tsx
  packages/mobile/src/components/TotalLineItem.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/selectors.ts
  packages/mobile/src/send/utils.ts
Labels: automerge, wallet

#5569 Update contractkit and cli CHANGELOGs
  packages/cli/CHANGELOG.md
  packages/contractkit/CHANGELOG.md
Labels: automerge

#5511 Update CHANGELOG.md to reflect AWS HSM wallet changes
  packages/contractkit/CHANGELOG.md
Labels: automerge

#5571 ContractKit->0.4.17-dev, CLI->0.0.60-dev
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/CHANGELOG.md
  packages/cli/package.json
  packages/contractkit/CHANGELOG.md
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/metadata-crawler/package.json
  packages/mobile/package.json
  packages/phone-number-privacy/common/package.json
Labels: automerge

#5583 Updated all DevX packages' codeowners
  .github/CODEOWNERS
Labels: automerge

#5594 Actually call toString in oracle report CLI
  packages/cli/src/commands/oracle/report.ts
Labels: automerge

#5586 Unproxy/unversion linked libraries
  packages/protocol/contracts/common/proxies/AddressLinkedListProxy.sol
  packages/protocol/contracts/common/proxies/AddressSortedLinkedListProxy.sol
  packages/protocol/contracts/common/proxies/AddressSortedLinkedListWithMedianProxy.sol
  packages/protocol/contracts/common/proxies/IntegerSortedLinkedListProxy.sol
  packages/protocol/contracts/common/proxies/SignaturesProxy.sol
  packages/protocol/contracts/governance/proxies/ProposalsProxy.sol
  packages/protocol/lib/compatibility/ast-version.ts
  packages/protocol/lib/compatibility/verify-bytecode.ts
  packages/protocol/scripts/bash/check-versions.sh
  packages/protocol/scripts/bash/verify-deployed.sh
  packages/protocol/scripts/truffle/make-release.ts
  packages/protocol/scripts/truffle/verify-bytecode.ts
  packages/protocol/test/compatibility/verify-bytecode.ts
Labels: automerge

#5522 Add manual checklist testing to the process
  packages/docs/community/release-process/smart-contracts.md
Labels: automerge

#5326 Use parsed deposit for value
  packages/cli/src/commands/governance/propose.ts
Labels: automerge

#5599 [cli] Require --force with account:claim-attestation-service-url for non-TLS urls
  packages/cli/src/commands/account/claim-attestation-service-url.ts
  packages/docs/command-line-interface/account.md
Labels: automerge

#5605 Metadata crawler schedule upgrade and forno WS backend timeout increase
  .env.rc1
  packages/terraform-modules/forno/main.tf
  packages/terraform-modules/forno/modules/backends/main.tf
  packages/terraform-modules/forno/modules/backends/variables.tf
Labels: automerge

#5600 Attestation Bot: Add check for expired attestation
  packages/celotool/src/lib/attestation.ts
Labels: automerge

#5602 ContractKit->0.4.18-dev, CLI->0.0.61-dev
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/CHANGELOG.md
  packages/cli/package.json
  packages/contractkit/CHANGELOG.md
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/metadata-crawler/package.json
  packages/mobile/package.json
  packages/phone-number-privacy/common/package.json
Labels: automerge, devX

#5270 Attestation Service 1.1.0: Verification security codes
  packages/attestation-service/migrations/20201005185559-attestation-v5.js
  packages/attestation-service/migrations/20201006231054-attestation-v6.js
  packages/attestation-service/package.json
  packages/attestation-service/src/db.ts
  packages/attestation-service/src/models/attestation.ts
  packages/attestation-service/src/request.ts
  packages/attestation-service/src/requestHandlers/attestation.ts
  packages/attestation-service/src/requestHandlers/get_attestation.ts
  packages/attestation-service/src/requestHandlers/status.ts
  packages/attestation-service/src/requestHandlers/test_attestation.ts
  packages/attestation-service/src/sms/index.ts
  packages/contractkit/src/wrappers/Attestations.ts
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_attestations_.attestationswrapper.md
  packages/docs/developer-resources/contractkit/reference/enums/_wrappers_attestations_.attestationservicestatusstate.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.attesationservicerevealrequest.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.attestationservicestatusresponse.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.unselectedrequest.md
  packages/docs/developer-resources/contractkit/reference/modules/_wrappers_attestations_.md
  packages/docs/operations-manual/attestation-service.md
  packages/utils/src/io.ts
Labels: automerge

#5603 Release process fixes
  packages/docs/community/release-process/smart-contracts.md
  packages/protocol/scripts/bash/verify-deployed.sh
Labels: automerge

#5533 Deploy Attestation Service pre1.1.0 to alfajores
  .env.alfajores
  .env.mnemonic.alfajores.enc
Labels: automerge

#5513 Update Attestation Service on baklava to 1.1.0
  .env.baklava
  packages/celotool/src/lib/attestation-bot.ts
  packages/helm-charts/attestation-bot/templates/statefulset.yaml
Labels: automerge

#5593 Updated blockscout image tag hashes
  .env.alfajores
  .env.alfajoresstaging
  .env.baklava
  .env.baklavastaging
  .env.integration
  .env.pilot
  .env.pilotstaging
  .env.rc0
  .env.rc1
Labels: automerge

#5612 Remove old upgrade script
  packages/protocol/scripts/bash/upgrade.sh
  packages/protocol/scripts/truffle/upgrade.ts
Labels: automerge

#5604 Add initialziation data process + release 1 data
  packages/docs/community/release-process/smart-contracts.md
  packages/protocol/releaseData/initializationData/release1.json
Labels: automerge

#5607 [docs] Fix link and explain tags on Attestation Service page
  packages/docs/operations-manual/attestation-service.md
Labels: automerge

#5619 add section for websocket event listener
  packages/docs/developer-resources/forno/README.md
Labels: automerge, devX

#5572 [Wallet] Use CELO to pay for gas when selling CELO
  packages/mobile/__mocks__/@celo/contractkit/index.ts
  packages/mobile/src/exchange/saga.test.ts
  packages/mobile/src/exchange/saga.ts
Labels: automerge, wallet

#5613 [Wallet] Country feature flags and changes for countries where CP-DOTO is restricted
  packages/mobile/__mocks__/react-native-reanimated.js
  packages/mobile/__mocks__/react-native-safe-area-context.ts
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/src/components/CurrencyDisplay.tsx
  packages/mobile/src/exchange/CeloExchangeButtons.tsx
  packages/mobile/src/exchange/CeloGoldOverview.tsx
  packages/mobile/src/exchange/ExchangeHomeScreen.test.tsx
  packages/mobile/src/exchange/ExchangeHomeScreen.tsx
  packages/mobile/src/exchange/RestrictedCeloExchange.test.tsx
  packages/mobile/src/exchange/RestrictedCeloExchange.tsx
  packages/mobile/src/exchange/__snapshots__/CeloExchangeButtons.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeHomeScreen.test.tsx.snap
  packages/mobile/src/flags.ts
  packages/mobile/src/navigator/DrawerNavigator.test.tsx
  packages/mobile/src/navigator/DrawerNavigator.tsx
  packages/mobile/src/utils/countryFeatures.test.ts
  packages/mobile/src/utils/countryFeatures.ts
  yarn.lock
Labels: automerge

#5624 Alexbharley/cip8 compressed keys
  packages/contractkit/src/identity/offchain-data-wrapper.test.ts
  packages/utils/src/address.ts
  packages/utils/src/ecdh.ts
Labels: automerge

#5614 Add generateDeterministicInviteCode
  packages/utils/src/account.ts
Labels: automerge

#5634 WS support for forno in k8s-based testnets
  packages/helm-charts/testnet/templates/forno.ingress.yaml
Labels: automerge

#5595 doc: Update mainnet docs for client release 1.1.0
  packages/docs/community/release-process/blockchain-client.md
  packages/docs/developer-resources/walkthroughs/hellocontracts.md
  packages/docs/getting-started/faucet.md
  packages/docs/getting-started/running-a-full-node-in-alfajores.md
  packages/docs/getting-started/running-a-full-node-in-baklava.md
  packages/docs/getting-started/running-a-full-node-in-mainnet.md
  packages/docs/getting-started/running-a-validator-in-baklava.md
  packages/docs/getting-started/running-a-validator-in-mainnet.md
  packages/docs/operations-manual/node-upgrades.md
Labels: automerge

#5633 Deploy fixes to baklava attestation bot
  .env.baklava
  packages/helm-charts/attestation-bot/templates/statefulset.yaml
Labels: automerge

#5587 remove duplicate events and reinstated original criteria for firing `verification_reveal_all_attestations_complete`
  packages/mobile/src/identity/verification.ts
Labels: automerge, wallet

#5636 Resolve Listings Guide Not Displaying Bug
  packages/docs/SUMMARY.md
Labels: automerge

#5629 [Attestation Bot] Use salted identifier in choosing number. UK/US numbers only.
  packages/celotool/src/cmds/bots/auto-verify.ts
  packages/celotool/src/lib/attestation.ts
Labels: automerge

#5616 [Attestation Service] MessageBird provider
  packages/attestation-service/config/.env.development
  packages/attestation-service/package.json
  packages/attestation-service/src/index.ts
  packages/attestation-service/src/sms/base.ts
  packages/attestation-service/src/sms/index.ts
  packages/attestation-service/src/sms/messagebird.ts
  packages/attestation-service/src/sms/nexmo.ts
  packages/attestation-service/src/sms/twilio.ts
  packages/docs/operations-manual/attestation-service.md
  yarn.lock
Labels: automerge

#5609 Updates for celo-blockchain 1.1.0
  .env.alfajores
  .env.baklava
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
  packages/terraform-modules/testnet/modules/full-node/main.tf
  packages/terraform-modules/testnet/modules/full-node/startup.sh
  packages/terraform-modules/testnet/modules/validator/main.tf
  packages/terraform-modules/testnet/modules/validator/startup.sh
Labels: automerge

#5620 Mitigate transaction timeout issues due to backgrounding and slow networks
  packages/mobile/src/geth/GethNativeBridgeWallet.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/redux/selectors.ts
  packages/mobile/src/transactions/send.ts
Labels: automerge, wallet

#5621 ODIS Client Update
  packages/contractkit/CHANGELOG.md
  packages/contractkit/src/identity/odis/phone-number-identifier.test.ts
  packages/contractkit/src/identity/odis/phone-number-identifier.ts
  packages/contractkit/src/identity/odis/query.ts
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/enums/_identity_odis_query_.authenticationmethod.md
  packages/docs/developer-resources/contractkit/reference/enums/_identity_odis_query_.errormessages.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_identity_odis_query_.customsigner.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_identity_odis_query_.matchmakingrequest.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_identity_odis_query_.matchmakingresponse.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_identity_odis_query_.phonenumberprivacyrequest.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_identity_odis_query_.servicecontext.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_identity_odis_query_.signmessagerequest.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_identity_odis_query_.signmessageresponse.md
  packages/docs/developer-resources/contractkit/reference/modules/_identity_odis_phone_number_identifier_.md
  packages/docs/developer-resources/contractkit/reference/modules/_identity_odis_query_.md
Labels: automerge

#5652 ContractKit v0.4.18 Release
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/CHANGELOG.md
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/komencikit/package.json
  packages/metadata-crawler/package.json
  packages/mobile/package.json
  packages/phone-number-privacy/common/package.json
Labels: automerge

#5653 [Attestation Service] configurable rate limit
  packages/attestation-service/config/.env.development
  packages/attestation-service/src/index.ts
  packages/docs/operations-manual/attestation-service.md
Labels: automerge

#5630 [Wallet] Add reCaptcha verification behind feature flag
  .circleci/config.yml
  packages/mobile/android/app/src/main/res/values/strings.xml
  packages/mobile/android/settings.gradle
  packages/mobile/branding/celo/src/brandingConfig.ts
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/package.json
  packages/mobile/scripts/sync_branding.sh
  packages/mobile/secrets.json.enc
  packages/mobile/src/config.ts
  packages/mobile/src/flags.ts
  packages/mobile/src/index.d.ts
  packages/mobile/src/onboarding/registration/__snapshots__/NameAndNumber.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransferConfirmationCard.test.tsx.snap
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
  packages/mobile/src/verify/safety/GoogleReCaptcha.tsx
  packages/mobile/src/verify/safety/SafetyNet.ts
  packages/react-components/components/Expandable.tsx
  packages/react-components/components/PhoneNumberInput.tsx
  packages/react-components/components/__snapshots__/PhoneNumberInput.test.tsx.snap
  yarn.lock
Labels: automerge, wallet

#5655 Update base and utils package versions
  packages/attestation-service/package.json
  packages/base/CHANGELOG.md
  packages/base/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/komencikit/package.json
  packages/metadata-crawler/package.json
  packages/mobile/package.json
  packages/phone-number-privacy/common/package.json
  packages/protocol/package.json
  packages/react-components/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
Labels: automerge
