Repository celo-org/celo-monorepo, pull requests merged in 2020-08, with the labels that each got.

#4589 [Wallet] Fix empty license page on iOS
  packages/mobile/android/.gitignore
  packages/mobile/jest.config.js
  packages/mobile/metro.config.js
  packages/mobile/package.json
  packages/mobile/scripts/copy_license_to_android_assets.sh
  packages/mobile/src/account/LicenseDisclaimer.txt
  packages/mobile/src/account/Licenses.tsx
  packages/mobile/src/navigator/Navigator.tsx
Labels: automerge

#4593 Forbid LinkedList contract changes
  .circleci/config.yml
  packages/protocol/scripts/bash/check-versions.sh
Labels: audit

#4583 Add transferAttestationMapping to Attestations.sol
  packages/protocol/contracts/identity/Attestations.sol
  packages/protocol/contracts/identity/interfaces/IAttestations.sol
  packages/protocol/test/identity/attestations.ts
Labels: audit, automerge

#4580 Add sell & buy functions to Exchange.sol, deprecate exchange function
  packages/protocol/contracts/stability/Exchange.sol
  packages/protocol/contracts/stability/interfaces/IExchange.sol
  packages/protocol/lib/test-utils.ts
  packages/protocol/test/common/integration.ts
  packages/protocol/test/stability/exchange.ts
Labels: audit, automerge

#4601 Add function to verify the number of attestation requests matches expectations
  packages/protocol/contracts/identity/Attestations.sol
  packages/protocol/contracts/identity/interfaces/IAttestations.sol
  packages/protocol/test/identity/attestations.ts
Labels: audit

#4605 Require transfer approver to be one of the two parties
  packages/protocol/contracts/identity/Attestations.sol
  packages/protocol/test/identity/attestations.ts
Labels: audit

#4587 Add MetaTransactionWallet contract
  packages/contractkit/package.json
  packages/contractkit/src/types.d.ts
  packages/contractkit/src/utils/signing-utils.ts
  packages/contractkit/src/wallets/remote-wallet.ts
  packages/contractkit/src/wallets/signers/ledger-signer.ts
  packages/contractkit/src/wallets/wallet.ts
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_azure_hsm_wallet_.azurehsmwallet.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_ledger_wallet_.ledgerwallet.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_local_wallet_.localwallet.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_remote_wallet_.remotewallet.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_rpc_wallet_.rpcwallet.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_signers_ledger_signer_.ledgersigner.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_wallet_.walletbase.md
  packages/docs/developer-resources/contractkit/reference/globals.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_utils_sign_typed_data_utils_.eip712object.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_utils_sign_typed_data_utils_.eip712parameter.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_utils_sign_typed_data_utils_.eip712typeddata.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_utils_sign_typed_data_utils_.eip712types.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wallets_wallet_.wallet.md
  packages/docs/developer-resources/contractkit/reference/modules/_contractkit_src_utils_sign_typed_data_utils_.md
  packages/docs/developer-resources/contractkit/reference/modules/_contractkit_src_utils_signing_utils_.md
  packages/protocol/contracts/common/ExternalCall.sol
  packages/protocol/contracts/common/MetaTransactionWallet.sol
  packages/protocol/contracts/common/MultiSig.sol
  packages/protocol/contracts/common/interfaces/IMetaTransactionWallet.sol
  packages/protocol/contracts/governance/Proposals.sol
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/contracts/stability/SortedOracles.sol
  packages/protocol/lib/compatibility/ast-code.ts
  packages/protocol/lib/proxy-utils.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/scripts/bash/check-versions.sh
  packages/protocol/scripts/check-backward.ts
  packages/protocol/test/common/metatransactionwallet.ts
  packages/protocol/truffle-config.js
  packages/utils/package.json
  packages/utils/src/sign-typed-data-utils.ts
  yarn.lock
Labels: audit

#4577 Support decryption in ContractKit's wallet/signer interface
  packages/contractkit/src/wallets/local-wallet.test.ts
  packages/contractkit/src/wallets/signers/azure-hsm-signer.ts
  packages/contractkit/src/wallets/signers/ledger-signer.ts
  packages/contractkit/src/wallets/signers/local-signer.ts
  packages/contractkit/src/wallets/signers/rpc-signer.ts
  packages/contractkit/src/wallets/signers/signer.ts
  packages/contractkit/src/wallets/wallet.ts
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_azure_hsm_wallet_.azurehsmwallet.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_ledger_wallet_.ledgerwallet.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_local_wallet_.localwallet.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_remote_wallet_.remotewallet.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_rpc_wallet_.rpcwallet.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_signers_azure_hsm_signer_.azurehsmsigner.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_signers_ledger_signer_.ledgersigner.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_signers_local_signer_.localsigner.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_signers_rpc_signer_.rpcsigner.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_wallet_.walletbase.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wallets_signers_signer_.signer.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wallets_wallet_.wallet.md
Labels: automerge

#4598 [Wallet] Don't reset pin on onboarding
  packages/mobile/src/onboarding/UseBackToWelcomeScreen.tsx
Labels: automerge, wallet

#4607 Do not let a ReleaseGold contract self-destruct with a cUSD balance
  packages/cli/src/commands/releasegold/withdraw.test.ts
  packages/cli/src/commands/releasegold/withdraw.ts
Labels: automerge

#4611 Adding more Valora analytics events and parameters
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/analytics/ValoraAnalytics.ts
  packages/mobile/src/app/App.tsx
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/exchange/ExchangeReview.tsx
  packages/mobile/src/exchange/saga.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/saga.ts
Labels: automerge

#4572 Headless CMS thru contentful for Experience Kits
  packages/web/env-config.js.enc
  packages/web/package.json
  packages/web/pages/experience/[kit]/[kitPage].tsx
  packages/web/pages/experience/[kit]/index.tsx
  packages/web/server-env-config.js.enc
  packages/web/server/index.ts
  packages/web/src/_page-tests/experience/__snapshots__/exchange-icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
  packages/web/src/_page-tests/experience/key-imagery.test.tsx
  packages/web/src/download/MobileApp.tsx
  packages/web/src/experience/brandkit/common/Page.tsx
  packages/web/src/experience/common/MobileKitMenu.tsx
  packages/web/src/experience/common/Page.tsx
  packages/web/src/experience/common/Showcase.tsx
  packages/web/src/experience/common/Sidebar.tsx
  packages/web/src/experience/common/TopBar.tsx
  packages/web/src/experience/contentful/ContentfulKit.tsx
  packages/web/src/experience/contentful/getServerSideProps.ts
  packages/web/src/experience/contentful/nodes.tsx
  packages/web/src/experience/eventkit/Page.tsx
  packages/web/src/header/OpenGraph.tsx
  packages/web/src/utils/contentful.ts
  yarn.lock
Labels: automerge

#4616 Update Alfajores PGPNP config and fix combiner deployment error
  packages/mobile/src/geth/networkConfig.ts
  packages/phone-number-privacy/combiner/package.json
Labels: automerge

#4614 adds fake build script to flake-tracker
  packages/flake-tracker/package.json
  packages/flake-tracker/src/github.js
Labels: automerge

#4615 [Wallet] Account key UI changes for better visibility on small screens
  packages/mobile/locales/en-US/backupKeyFlow6.json
  packages/mobile/locales/es-419/backupKeyFlow6.json
  packages/mobile/src/backup/BackupIntroduction.tsx
  packages/mobile/src/backup/BackupPhrase.tsx
  packages/mobile/src/backup/BackupPhraseContainer.tsx
  packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupPhrase.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupPhraseContainer.test.tsx.snap
  packages/mobile/src/backup/__snapshots__/BackupSocial.test.tsx.snap
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/import/__snapshots__/ImportWalletSocial.test.tsx.snap
Labels: automerge

#4623 [docs] Git is required to install some cli dependencies
  packages/docs/command-line-interface/introduction.md
Labels: automerge

#4617 [ODIS] Trim BLS Key
  packages/phone-number-privacy/signer/src/key-management/key-provider-base.ts
Labels: automerge

#4624 Reenable Hermes
  packages/mobile/android/app/build.gradle
  packages/mobile/fastlane/Fastfile
  packages/mobile/fastlane/README.md
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/src/missingGlobals.ts
  packages/web/package.json
  yarn.lock
Labels: automerge

#4581 Upgrade oracle image to use 0 minAggregatedVolume
  .env.rc1
Labels: automerge

#4628 Remove await from log upload on Geth creation
  packages/mobile/src/geth/geth.ts
  packages/mobile/src/utils/LogUploader.ts
Labels: automerge

#4599 Add network events to mobile Analytics package
  packages/mobile/__mocks__/web3.js
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/analytics/ValoraAnalytics.ts
  packages/mobile/src/geth/actions.ts
  packages/mobile/src/geth/geth.ts
  packages/mobile/src/geth/reducer.ts
  packages/mobile/src/geth/saga.ts
  packages/mobile/src/geth/selectors.ts
  packages/mobile/src/transactions/contract-utils.ts
  packages/mobile/src/transactions/send.ts
  packages/mobile/src/web3/saga.test.ts
  packages/mobile/src/web3/saga.ts
  packages/mobile/src/web3/utils.ts
  packages/mobile/test/schemas.ts
Labels: automerge

#4627 fixes celo-blockchain build
  packages/flake-tracker/src/config.js
Labels: automerge

#4636 [Wallet] Fix for measuring app load time
  packages/mobile/android/app/src/main/java/org/celo/mobile/MainActivity.java
  packages/mobile/src/app/App.tsx
Labels: automerge, wallet

#4626 Enable PNP DEK Auth
  packages/mobile/src/flags.ts
Labels: do not merge

#4632 [Wallet] Explicitly passing country name along with country code for analytics
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/analytics/ValoraAnalytics.ts
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/onboarding/registration/NameAndNumber.tsx
  packages/mobile/src/onboarding/registration/SelectCountry.tsx
Labels: automerge

#4362 [Wallet] Encrypt payment requests and refactor related code
  packages/mobile/src/account/actions.ts
  packages/mobile/src/account/reducer.ts
  packages/mobile/src/account/selectors.ts
  packages/mobile/src/account/types.ts
  packages/mobile/src/alert/AlertBanner.tsx
  packages/mobile/src/firebase/actions.ts
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/firebase/notifications.ts
  packages/mobile/src/firebase/saga.ts
  packages/mobile/src/home/NotificationBox.test.tsx
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/home/selectors.ts
  packages/mobile/src/identity/commentEncryption.ts
  packages/mobile/src/notifications/types.ts
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListScreen.test.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListScreen.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestSummaryNotification.tsx
  packages/mobile/src/paymentRequest/OutgoingPaymentRequestListItem.tsx
  packages/mobile/src/paymentRequest/OutgoingPaymentRequestListScreen.test.tsx
  packages/mobile/src/paymentRequest/OutgoingPaymentRequestListScreen.tsx
  packages/mobile/src/paymentRequest/OutgoingPaymentRequestSummaryNotification.tsx
  packages/mobile/src/paymentRequest/PaymentRequestConfirmation.tsx
  packages/mobile/src/paymentRequest/__mocks__.ts
  packages/mobile/src/paymentRequest/actions.ts
  packages/mobile/src/paymentRequest/reducer.ts
  packages/mobile/src/paymentRequest/saga.ts
  packages/mobile/src/paymentRequest/selectors.test.ts
  packages/mobile/src/paymentRequest/selectors.ts
  packages/mobile/src/paymentRequest/types.ts
  packages/mobile/src/paymentRequest/utils.test.ts
  packages/mobile/src/paymentRequest/utils.ts
  packages/mobile/src/redux/migrations.test.ts
  packages/mobile/src/redux/migrations.ts
  packages/mobile/src/redux/reducers.ts
  packages/mobile/src/redux/sagas.ts
  packages/mobile/src/redux/selectors.ts
  packages/mobile/src/redux/store.ts
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/saga.ts
  packages/mobile/src/shared/BackupPrompt.tsx
  packages/mobile/src/web3/reducer.ts
  packages/mobile/src/web3/selectors.ts
  packages/mobile/test/schemas.ts
  packages/mobile/test/values.ts
  packages/react-components/components/SmartTopAlert.test.tsx
  packages/react-components/components/SmartTopAlert.tsx
Labels: automerge

#4638 move flake tracker to peer dep to fix gcp cloud build deployment
  packages/web/package.json
Labels: automerge

#4536 Add payment processing options to QRs and deep links
  packages/mobile/package.json
  packages/mobile/src/account/__snapshots__/Invite.test.tsx.snap
  packages/mobile/src/apollo/types.ts
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/app/saga.test.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/fees/CalculateFee.tsx
  packages/mobile/src/qrcode/QRCode.tsx
  packages/mobile/src/qrcode/QRGenTests/QRGen.test.tsx
  packages/mobile/src/qrcode/__snapshots__/QRCode.test.tsx.snap
  packages/mobile/src/qrcode/schema.test.ts
  packages/mobile/src/qrcode/schema.ts
  packages/mobile/src/qrcode/utils.ts
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/saga.test.ts
  packages/mobile/src/send/utils.test.ts
  packages/mobile/src/send/utils.ts
  packages/mobile/test/values.ts
  packages/utils/package.json
Labels: automerge

#4639 fixes external pr build error
  packages/flake-tracker/src/config.js
Labels: automerge

#4532 Adds docs for metrics PR
  packages/docs/operations-manual/monitoring.md
Labels: automerge

#4542 AWS Terraform: Cloudwatch, EIPs, image updates, and bugfixes
  packages/terraform-modules-public/aws/examples/mainnet/main.tf
  packages/terraform-modules-public/aws/examples/mainnet/outputs.tf
  packages/terraform-modules-public/aws/examples/mainnet/variables.tf
  packages/terraform-modules-public/aws/examples/testnet/main.tf
  packages/terraform-modules-public/aws/examples/testnet/outputs.tf
  packages/terraform-modules-public/aws/examples/testnet/variables.tf
  packages/terraform-modules-public/aws/testnet/main.tf
  packages/terraform-modules-public/aws/testnet/modules/attestation-service/main.tf
  packages/terraform-modules-public/aws/testnet/modules/attestation-service/variables.tf
  packages/terraform-modules-public/aws/testnet/modules/bastion/main.tf
  packages/terraform-modules-public/aws/testnet/modules/bastion/variables.tf
  packages/terraform-modules-public/aws/testnet/modules/proxy/main.tf
  packages/terraform-modules-public/aws/testnet/modules/proxy/outputs.tf
  packages/terraform-modules-public/aws/testnet/modules/proxy/variables.tf
  packages/terraform-modules-public/aws/testnet/modules/startup-scripts/install-cloudwatch-agent.sh
  packages/terraform-modules-public/aws/testnet/modules/startup-scripts/run-attestation-service.sh
  packages/terraform-modules-public/aws/testnet/modules/startup-scripts/run-proxy-node.sh
  packages/terraform-modules-public/aws/testnet/modules/startup-scripts/run-validator-node.sh
  packages/terraform-modules-public/aws/testnet/modules/validator/main.tf
  packages/terraform-modules-public/aws/testnet/modules/validator/variables.tf
  packages/terraform-modules-public/aws/testnet/outputs.tf
  packages/terraform-modules-public/aws/testnet/variables.tf
Labels: automerge

#4641 [Wallet] Add Paste button to Search Input
  packages/mobile/src/send/SendSearchInput.tsx
  packages/react-components/components/WithPasteAware.tsx
  packages/react-components/components/WithTextInputPasteAware.tsx
  packages/react-components/components/WithTextSearchPasteAware.tsx
  packages/react-components/icons/Paste.tsx
Labels: automerge

#4651 flakey protocol test beforeEach fix
  packages/protocol/test/customHooks.ts
  packages/protocol/test/identity/attestations.ts
Labels: automerge

#4518 CIP8: Add Storage claims
  packages/cli/src/commands/account/claim-storage.ts
  packages/cli/src/utils/command.ts
  packages/cli/src/utils/identity.ts
  packages/cli/src/utils/off-chain-data.ts
  packages/contractkit/package.json
  packages/contractkit/src/identity/claims/claim.ts
  packages/contractkit/src/identity/claims/types.ts
  packages/contractkit/src/identity/metadata.ts
  packages/contractkit/src/identity/offchain-data-wrapper.test.ts
  packages/contractkit/src/identity/offchain-data-wrapper.ts
  packages/contractkit/src/identity/offchain/schema-utils.ts
  packages/contractkit/src/identity/offchain/schemas.ts
  packages/contractkit/src/identity/offchain/storage-writers.ts
  packages/docs/SUMMARY.md
  packages/docs/command-line-interface/account.md
  packages/docs/developer-resources/contractkit/reference/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_identity_metadata_.identitymetadatawrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_identity_offchain_data_wrapper_.offchaindatawrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_identity_offchain_schema_utils_.singleschema.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_identity_offchain_schemas_.authorizedsigneraccessor.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_identity_offchain_schemas_.nameaccessor.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_identity_offchain_storage_writers_.gitstoragewriter.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_identity_offchain_storage_writers_.localstoragewriter.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_identity_offchain_storage_writers_.mockstoragewriter.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_identity_offchain_storage_writers_.storagewriter.md
  packages/docs/developer-resources/contractkit/reference/enums/_contractkit_src_identity_claims_types_.claimtypes.md
  packages/docs/developer-resources/contractkit/reference/globals.md
  packages/docs/developer-resources/contractkit/reference/modules/_contractkit_src_identity_claims_claim_.md
  packages/docs/developer-resources/contractkit/reference/modules/_contractkit_src_identity_claims_types_.md
  packages/docs/developer-resources/contractkit/reference/modules/_contractkit_src_identity_metadata_.md
  packages/docs/developer-resources/contractkit/reference/modules/_contractkit_src_identity_offchain_data_wrapper_.md
  packages/docs/developer-resources/contractkit/reference/modules/_contractkit_src_identity_offchain_schema_utils_.md
  packages/docs/developer-resources/contractkit/reference/modules/_contractkit_src_identity_offchain_schemas_.md
  packages/docs/developer-resources/contractkit/reference/modules/_contractkit_src_identity_offchain_storage_writers_.md
  yarn.lock
Labels: automerge

#4539 Update key rotation doc
  packages/docs/operations-manual/key-management/key-rotation.md
Labels: automerge

#4654 Add decrypt to RPCSigner
  packages/contractkit/package.json
  packages/contractkit/src/wallets/rpc-wallet.test.ts
  packages/contractkit/src/wallets/signers/rpc-signer.ts
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_signers_rpc_signer_.rpcsigner.md
  packages/protocol/package.json
  yarn.lock
Labels: automerge

#4667 [Wallet] fix flaky test in checkWeb3SyncProgress
  packages/mobile/src/web3/saga.test.ts
Labels: automerge

#3888 Significant refactor of the GCP Terraform code for deploying validators on mainnet
  packages/terraform-modules-public/gcp/README.md
  packages/terraform-modules-public/gcp/example/README.md
  packages/terraform-modules-public/gcp/example/bootstrap.sh
  packages/terraform-modules-public/gcp/example/dashboards/hud.json
  packages/terraform-modules-public/gcp/example/dashboards/readme.md
  packages/terraform-modules-public/gcp/example/gcloud.env.example
  packages/terraform-modules-public/gcp/example/main.tf
  packages/terraform-modules-public/gcp/example/metrics.md
  packages/terraform-modules-public/gcp/example/terraform.tfvars.example
  packages/terraform-modules-public/gcp/example/variables.tf
  packages/terraform-modules-public/gcp/testnet/main.tf
  packages/terraform-modules-public/gcp/testnet/modules/attestation-service/main.tf
  packages/terraform-modules-public/gcp/testnet/modules/attestation-service/startup.sh
  packages/terraform-modules-public/gcp/testnet/modules/attestation-service/variables.tf
  packages/terraform-modules-public/gcp/testnet/modules/proxy/main.tf
  packages/terraform-modules-public/gcp/testnet/modules/proxy/startup.sh
  packages/terraform-modules-public/gcp/testnet/modules/proxy/variables.tf
  packages/terraform-modules-public/gcp/testnet/modules/tx-node/main.tf
  packages/terraform-modules-public/gcp/testnet/modules/tx-node/startup.sh
  packages/terraform-modules-public/gcp/testnet/modules/tx-node/variables.tf
  packages/terraform-modules-public/gcp/testnet/modules/validator/main.tf
  packages/terraform-modules-public/gcp/testnet/modules/validator/startup.sh
  packages/terraform-modules-public/gcp/testnet/modules/validator/variables.tf
  packages/terraform-modules-public/gcp/testnet/variables.tf
Labels: automerge

#4648 PGPNP to ODIS rename Part 1 [Docs]
  packages/docs/celo-codebase/protocol/identity/phone-number-privacy.md
Labels: automerge

#4674 Add resolution for serialize-javascript due to vulnerability alert
  package.json
  yarn.lock
Labels: automerge

#4625 Replace 'lodash.range' references to remove lodash dependency from contractkit
  packages/contractkit/src/utils/array.ts
  packages/contractkit/src/utils/tx-uri.ts
  packages/contractkit/src/wallets/ledger-wallet.ts
  packages/contractkit/src/wrappers/Election.ts
  packages/contractkit/src/wrappers/Governance.ts
  packages/contractkit/src/wrappers/Validators.ts
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_ledger_wallet_.ledgerwallet.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wrappers_governance_.governancewrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wrappers_validators_.validatorswrapper.md
  packages/docs/developer-resources/contractkit/reference/enums/_contractkit_src_wallets_ledger_wallet_.addressvalidation.md
  packages/docs/developer-resources/contractkit/reference/enums/_contractkit_src_wrappers_governance_.proposalstage.md
  packages/docs/developer-resources/contractkit/reference/enums/_contractkit_src_wrappers_governance_.votevalue.md
  packages/docs/developer-resources/contractkit/reference/globals.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_governance_.governanceconfig.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_governance_.hotfixrecord.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_governance_.participationparameters.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_governance_.proposalmetadata.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_governance_.proposalrecord.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_governance_.proposalstagedurations.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_governance_.upvoterecord.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_governance_.voter.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_governance_.voterecord.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_governance_.votes.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_validators_.groupmembership.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_validators_.lockedgoldrequirements.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_validators_.membershiphistoryextradata.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_validators_.validator.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_validators_.validatorgroup.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_validators_.validatorreward.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_validators_.validatorsconfig.md
  packages/docs/developer-resources/contractkit/reference/modules/_contractkit_src_utils_array_.md
  packages/docs/developer-resources/contractkit/reference/modules/_contractkit_src_wallets_ledger_wallet_.md
  packages/docs/developer-resources/contractkit/reference/modules/_contractkit_src_wrappers_governance_.md
Labels: automerge

#4635 Signer replay attack prevention
  packages/phone-number-privacy/combiner/package.json
  packages/phone-number-privacy/combiner/src/common/constants.ts
  packages/phone-number-privacy/combiner/src/database/wrappers/account.ts
  packages/phone-number-privacy/combiner/src/match-making/get-contact-matches.ts
  packages/phone-number-privacy/combiner/src/salt-generation/get-threshold-salt.ts
  packages/phone-number-privacy/combiner/test/end-to-end/get-blinded-salt.test.ts
  packages/phone-number-privacy/combiner/test/end-to-end/get-contact-matches.test.ts
  packages/phone-number-privacy/combiner/test/index.test.ts
  packages/phone-number-privacy/common/package.json
  packages/phone-number-privacy/common/src/index.ts
  packages/phone-number-privacy/common/src/utils/constants.ts
  packages/phone-number-privacy/common/src/utils/input-validation.ts
  packages/phone-number-privacy/common/test/utils.ts
  packages/phone-number-privacy/signer/migrations/20200811163913_create_requests_table.ts
  packages/phone-number-privacy/signer/package.json
  packages/phone-number-privacy/signer/src/common/input-validation.ts
  packages/phone-number-privacy/signer/src/database/models/request.ts
  packages/phone-number-privacy/signer/src/database/wrappers/account.ts
  packages/phone-number-privacy/signer/src/database/wrappers/request.ts
  packages/phone-number-privacy/signer/src/salt-generation/get-salt.ts
  packages/phone-number-privacy/signer/src/salt-generation/query-quota.ts
  packages/phone-number-privacy/signer/src/server.ts
  packages/phone-number-privacy/signer/src/web3/contracts.ts
  packages/phone-number-privacy/signer/test/end-to-end/get-blinded-salt.test.ts
  packages/phone-number-privacy/signer/test/index.test.ts
  yarn.lock
Labels: automerge

#4642 [cli] Recover 32byte Valora accounts
  packages/cli/src/commands/account/recover-old.ts
  packages/docs/command-line-interface/account.md
  packages/utils/src/account.ts
Labels: automerge

#4679 Including Language screen in nux navigation stack
  packages/mobile/src/navigator/Navigator.tsx
  packages/web/package.json
Labels: automerge, wallet

#4649 PGPNP to ODIS rename Part 2 [Signer and Combiner]
  .env
  packages/docs/celo-codebase/protocol/identity/phone-number-privacy.md
  packages/phone-number-privacy/README.md
  packages/phone-number-privacy/combiner/README.md
  packages/phone-number-privacy/combiner/package.json
  packages/phone-number-privacy/combiner/src/config.ts
  packages/phone-number-privacy/combiner/src/index.ts
  packages/phone-number-privacy/combiner/src/signing/get-threshold-signature.ts
  packages/phone-number-privacy/combiner/test/end-to-end/get-blinded-sig.test.ts
  packages/phone-number-privacy/combiner/test/end-to-end/get-contact-matches.test.ts
  packages/phone-number-privacy/combiner/test/index.test.ts
  packages/phone-number-privacy/combiner/test/signing/bls-signature.test.ts
  packages/phone-number-privacy/common/src/interfaces/error-utils.ts
  packages/phone-number-privacy/signer/README.md
  packages/phone-number-privacy/signer/docs/deploy-on-aws.md
  packages/phone-number-privacy/signer/package.json
  packages/phone-number-privacy/signer/src/config.ts
  packages/phone-number-privacy/signer/src/database/models/request.ts
  packages/phone-number-privacy/signer/src/database/wrappers/request.ts
  packages/phone-number-privacy/signer/src/server.ts
  packages/phone-number-privacy/signer/src/signing/get-partial-signature.ts
  packages/phone-number-privacy/signer/src/signing/query-quota.ts
  packages/phone-number-privacy/signer/test/end-to-end/get-blinded-sig.test.ts
  packages/phone-number-privacy/signer/test/index.test.ts
  packages/phone-number-privacy/signer/test/signing/bls-signature.test.ts
  packages/phone-number-privacy/signer/test/signing/query-quota.test.ts
Labels: automerge

#4678 Prevent nonce assignment collisions when sending multiple transactions
  package.json
  packages/contractkit/src/providers/celo-provider.ts
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_providers_celo_provider_.celoprovider.md
  packages/mobile/src/geth/geth.ts
  packages/mobile/src/transactions/contract-utils.ts
  packages/utils/src/lock.test.ts
  packages/utils/src/lock.ts
Labels: automerge

#4690 Add note to @celo/utils Lock about reentrancy and reject on throw error
  packages/utils/src/lock.ts
Labels: automerge

#3589 ReleaseGold deployed contract verification script
  packages/protocol/scripts/bash/verify_release_gold_contracts.sh
  packages/protocol/scripts/truffle/verify_release_gold_contracts.ts
Labels: automerge

#4691 Add usdGas flag to base command
  packages/cli/src/base.ts
  packages/contractkit/src/kit.test.ts
  packages/contractkit/src/kit.ts
  packages/docs/command-line-interface/account.md
  packages/docs/command-line-interface/dkg.md
  packages/docs/command-line-interface/election.md
  packages/docs/command-line-interface/exchange.md
  packages/docs/command-line-interface/governance.md
  packages/docs/command-line-interface/identity.md
  packages/docs/command-line-interface/lockedgold.md
  packages/docs/command-line-interface/multisig.md
  packages/docs/command-line-interface/network.md
  packages/docs/command-line-interface/node.md
  packages/docs/command-line-interface/oracle.md
  packages/docs/command-line-interface/releasegold.md
  packages/docs/command-line-interface/reserve.md
  packages/docs/command-line-interface/rewards.md
  packages/docs/command-line-interface/transfer.md
  packages/docs/command-line-interface/validator.md
  packages/docs/command-line-interface/validatorgroup.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_kit_.contractkit.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_kit_.kitoptions.md
Labels: automerge

#4698 [Wallet] SetClock bugfix
  packages/mobile/src/set-clock/SetClock.tsx
  packages/mobile/src/utils/time.ts
Labels: automerge

#4697 Documentation Improvements
  packages/docs/operations-manual/celo-foundation-voting-policy.md
  packages/docs/operations-manual/validator-explorer.md
Labels: docs

#4695 adds warnings to ODIS signer response
  packages/phone-number-privacy/combiner/package.json
  packages/phone-number-privacy/common/package.json
  packages/phone-number-privacy/common/src/interfaces/error-utils.ts
  packages/phone-number-privacy/signer/package.json
  packages/phone-number-privacy/signer/src/database/wrappers/request.ts
  packages/phone-number-privacy/signer/src/signing/get-partial-signature.ts
  packages/phone-number-privacy/signer/test/index.test.ts
  yarn.lock
Labels: automerge

#4689 adds timestamp and retries to ODIS salt request in contractkit and wallet
  packages/base/src/async.test.ts
  packages/base/src/async.ts
  packages/contractkit/src/utils/phone-number-lookup/phone-number-identifier.ts
  packages/contractkit/src/utils/phone-number-lookup/phone-number-lookup.ts
  packages/docs/developer-resources/contractkit/reference/enums/_contractkit_src_utils_phone_number_lookup_phone_number_lookup_.authenticationmethod.md
  packages/docs/developer-resources/contractkit/reference/enums/_contractkit_src_utils_phone_number_lookup_phone_number_lookup_.errormessages.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_utils_phone_number_lookup_phone_number_lookup_.encryptionkeysigner.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_utils_phone_number_lookup_phone_number_lookup_.matchmakingrequest.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_utils_phone_number_lookup_phone_number_lookup_.matchmakingresponse.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_utils_phone_number_lookup_phone_number_lookup_.phonenumberprivacyrequest.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_utils_phone_number_lookup_phone_number_lookup_.servicecontext.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_utils_phone_number_lookup_phone_number_lookup_.signmessagerequest.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_utils_phone_number_lookup_phone_number_lookup_.signmessageresponse.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_utils_phone_number_lookup_phone_number_lookup_.walletkeysigner.md
  packages/docs/developer-resources/contractkit/reference/modules/_contractkit_src_utils_phone_number_lookup_phone_number_identifier_.md
  packages/docs/developer-resources/contractkit/reference/modules/_contractkit_src_utils_phone_number_lookup_phone_number_lookup_.md
  packages/utils/src/async.test.ts
  packages/utils/src/async.ts
Labels: automerge

#4700 Bump eksportisto image to latest deployment
  .env.baklava
  .env.rc1
Labels: automerge

#4702 Remove all references as possible to celo/utils
  packages/base/src/lock.test.ts
  packages/base/src/lock.ts
  packages/contractkit/src/explorer/log-explorer.ts
  packages/contractkit/src/identity/claims/attestation-service-url.ts
  packages/contractkit/src/identity/claims/keybase.ts
  packages/contractkit/src/identity/claims/verify.ts
  packages/contractkit/src/identity/metadata.ts
  packages/contractkit/src/identity/offchain-data-wrapper.ts
  packages/contractkit/src/providers/celo-provider.ts
  packages/contractkit/src/utils/azure-key-vault-client.ts
  packages/contractkit/src/utils/phone-number-lookup/phone-number-lookup.ts
  packages/contractkit/src/utils/signing-utils.ts
  packages/contractkit/src/wallets/local-wallet.ts
  packages/contractkit/src/wallets/signers/local-signer.ts
  packages/contractkit/src/wallets/signers/rpc-signer.ts
  packages/contractkit/src/wallets/wallet.ts
  packages/contractkit/src/wrappers/Accounts.ts
  packages/contractkit/src/wrappers/ReleaseGold.ts
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/SUMMARY.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_identity_metadata_.identitymetadatawrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_identity_offchain_data_wrapper_.offchaindatawrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wallets_local_wallet_.localwallet.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wrappers_accounts_.accountswrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_contractkit_src_wrappers_releasegold_.releasegoldwrapper.md
  packages/docs/developer-resources/contractkit/reference/globals.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_releasegold_.balancestate.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_contractkit_src_wrappers_releasegold_.releasegoldinfo.md
  packages/docs/developer-resources/contractkit/reference/modules/_base_src_address_.md
  packages/docs/developer-resources/contractkit/reference/modules/_contractkit_src_identity_metadata_.md
  packages/docs/developer-resources/contractkit/reference/modules/_utils_src_address_.md
Labels: automerge

#4509 [Wallet] Implement remove account feature
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-419/accountScreen10.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/src/account/Settings.tsx
  packages/mobile/src/account/__snapshots__/Settings.test.tsx.snap
  packages/mobile/src/account/actions.ts
  packages/mobile/src/account/saga.ts
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/analytics/ValoraAnalytics.ts
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/backup/BackupComplete.test.tsx
  packages/mobile/src/backup/BackupComplete.tsx
  packages/mobile/src/backup/BackupIntroduction.tsx
  packages/mobile/src/backup/BackupPhrase.test.tsx
  packages/mobile/src/backup/BackupPhrase.tsx
  packages/mobile/src/backup/BackupQuiz.tsx
  packages/mobile/src/backup/utils.ts
  packages/mobile/src/components/WarningModal.tsx
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/geth/geth.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/pincode/authentication.ts
  packages/mobile/src/redux/reducers.ts
  packages/mobile/src/storage/keychain.tsx
  packages/mobile/src/utils/AppRestart.ts
  packages/mobile/src/verify/VerificationFailedModal.tsx
  packages/mobile/src/verify/__snapshots__/VerificationLoadingScreen.test.tsx.snap
  packages/react-components/components/SettingsItem.tsx
Labels: automerge, wallet

#4705 [Wallet] Fix Language screen transitions
  packages/mobile/src/language/Language.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/onboarding/LanguageButton.tsx
Labels: automerge

#4677 upgrade next.js for celo.org and reserve.org
  package.json
  packages/reserve-site/next-env.d.ts
  packages/reserve-site/package.json
  packages/reserve-site/src/pages/404.tsx
  packages/reserve-site/src/pages/index.tsx
  packages/reserve-site/tsconfig.json
  packages/web/package.json
  packages/web/src/_page-tests/__snapshots__/_error.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/about.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/alliance.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/audits.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/community.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/faq.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/jobs.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/papers.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/past-events.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/privacy.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/terms.test.tsx.snap
  packages/web/src/_page-tests/__snapshots__/user-agreement.test.tsx.snap
  packages/web/src/_page-tests/developers/__snapshots__/Index.test.tsx.snap
  packages/web/src/_page-tests/developers/__snapshots__/faucet.test.tsx.snap
  packages/web/src/_page-tests/developers/__snapshots__/wallet.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/exchange-icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/_page-tests/stake-off/__snapshots__/terms.test.tsx.snap
  packages/web/src/_page-tests/validators/__snapshots__/index.test.tsx.snap
  packages/web/src/shared/Link.tsx
  packages/web/src/shared/__snapshots__/Footer.test.tsx.snap
  packages/web/src/shared/__snapshots__/MobileMenu.test.tsx.snap
  yarn.lock
Labels: automerge, web

#4669 Celo Standards Checklist
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/integrations/checklist.md
Labels: automerge

#4703 fix: hash the raw transaction to get txhash not rlpencoded tx
  packages/contractkit/src/utils/signing-utils.ts
  packages/docs/developer-resources/contractkit/reference/modules/_utils_signing_utils_.md
Labels: automerge

#4711 Ensure every transaction has a unique ID for logging
  packages/mobile/__mocks__/src/transactions/actions.ts
  packages/mobile/__mocks__/src/transactions/types.ts
  packages/mobile/package.json
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/escrow/actions.ts
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/exchange/saga.ts
  packages/mobile/src/goldToken/actions.ts
  packages/mobile/src/identity/privateHashing.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/invite/saga.test.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/send/saga.ts
  packages/mobile/src/stableToken/actions.ts
  packages/mobile/src/stableToken/saga.test.ts
  packages/mobile/src/tokens/saga.ts
  packages/mobile/src/transactions/TransactionsList.test.tsx
  packages/mobile/src/transactions/actions.ts
  packages/mobile/src/transactions/reducer.ts
  packages/mobile/src/transactions/saga.ts
  packages/mobile/src/transactions/send.ts
  packages/mobile/src/transactions/types.ts
  packages/mobile/src/web3/dataEncryptionKey.ts
  yarn.lock
Labels: automerge

#4699 [Wallet] Fixed performance tracking bug for Android
  packages/mobile/android/app/src/main/java/org/celo/mobile/MainActivity.java
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/app/App.tsx
Labels: automerge, wallet

#4405 Support for interactive population of templates in RG deployment
  packages/protocol/scripts/bash/deploy_release_contracts.sh
  packages/protocol/scripts/truffle/deploy_release_contracts.ts
Labels: automerge

#4714 [Wallet] Hide CELO buy button when there's no dollar balance
  packages/mobile/src/exchange/CeloExchangeButtons.test.tsx
  packages/mobile/src/exchange/CeloExchangeButtons.tsx
  packages/mobile/src/exchange/ExchangeHomeScreen.tsx
  packages/mobile/src/exchange/__snapshots__/CeloExchangeButtons.test.tsx.snap
  packages/mobile/src/goldToken/selectors.ts
Labels: automerge

#4730 [Phone Number Privacy] Include celo utils as explicit dependency
  dependency-graph.json
  packages/phone-number-privacy/common/package.json
Labels: automerge

#4723 Switch to use 64 bit emulator
  .circleci/config.yml
  packages/docs/celo-codebase/wallet/intro.md
  packages/mobile/e2e/README.md
  packages/mobile/e2e/Transfer.spec.js
  packages/mobile/e2e/conf/avd_conf.ini
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/scripts/install-android-tools.sh
  packages/mobile/scripts/run_e2e.sh
  packages/mobile/scripts/sync_branding.sh
  yarn.lock
Labels: automerge

#4715 usdGas flag warning and fixes
  packages/cli/src/base.ts
  packages/contractkit/src/kit.ts
  packages/docs/developer-resources/contractkit/reference/classes/_kit_.contractkit.md
Labels: automerge

#4737 Bump versions for @celo/base, utils, contractkit, and cli release
  packages/attestation-service/package.json
  packages/base/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/metadata-crawler/package.json
  packages/mobile/package.json
  packages/phone-number-privacy/common/package.json
  packages/protocol/package.json
  packages/react-components/package.json
  packages/utils/package.json
Labels: automerge

#4743 utils 0.1.18-dev to 0.1.19-dev (previous published version (0.1.17) was not bumped)
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/contractkit/package.json
  packages/dappkit/package.json
  packages/metadata-crawler/package.json
  packages/mobile/package.json
  packages/phone-number-privacy/common/package.json
  packages/protocol/package.json
  packages/react-components/package.json
  packages/utils/package.json
Labels: automerge

#4740 [Wallet] Witdraw CELO QR scan fixes
  packages/mobile/src/exchange/WithdrawCeloQrScannerScreen.tsx
  packages/mobile/src/exchange/WithdrawCeloScreen.tsx
  packages/mobile/src/exchange/reducer.ts
  packages/mobile/src/qrcode/utils.ts
  packages/mobile/src/send/saga.test.ts
Labels: automerge, wallet

#4672 [Validator Badge] Celo.Works 0x3C86b6A27a074c1c4CC904d8808A1C33078DB4E6
  packages/web/validator-badges/007-celo-foundation-vote-recipient.md
Labels: automerge, docs

#4726 Add docs for recovering CELO from an ETH wallet
  packages/docs/SUMMARY.md
  packages/docs/celo-holder-guide/eth-recovery.md
Labels: automerge, docs

#4744 [Wallet] Add 'Confirm Phone Number' option to settings
  packages/mobile/locales/en-US/accountScreen10.json
  packages/mobile/locales/es-419/accountScreen10.json
  packages/mobile/src/account/Settings.tsx
  packages/mobile/src/account/__snapshots__/Settings.test.tsx.snap
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/verify/VerificationEducationScreen.tsx
Labels: automerge, wallet

#4733 [Wallet] Make invitation links use vlra.app domain
  packages/mobile/.env
  packages/mobile/.env.alfajores
  packages/mobile/.env.mainnet
  packages/mobile/ios/celo/Info.plist
  packages/mobile/ios/celo/celo.entitlements
  packages/mobile/src/config.ts
  packages/mobile/src/firebase/dynamicLinks.ts
  packages/mobile/src/geth/networkConfig.ts
  packages/mobile/src/invite/saga.test.ts
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/utils/appstore.ts
Labels: automerge

#4749 CLI 0.0.55-dev -> 0.0.56-dev
  packages/cli/package.json
Labels: automerge

#4753 [Wallet] Revert dev config change
  packages/mobile/.env
Labels: automerge

#4760 [Wallet] Add back trigger for enabling dev mode in setting menu
  packages/mobile/src/account/Settings.tsx
  packages/mobile/src/account/__snapshots__/Settings.test.tsx.snap
  packages/mobile/src/account/reducer.ts
Labels: automerge

#4761 [Wallet] Add iOS simulator instructions for e2e iOS tests
  packages/mobile/README.md
  packages/mobile/e2e/README.md
Labels: automerge

#4772 Fix ODIS url in mainnet bug from rename
  packages/mobile/src/geth/networkConfig.ts
Labels: automerge

#4766 Lower min balance && support CELO min balance
  packages/phone-number-privacy/common/test/utils.ts
  packages/phone-number-privacy/signer/src/config.ts
  packages/phone-number-privacy/signer/src/signing/query-quota.ts
  packages/phone-number-privacy/signer/test/signing/query-quota.test.ts
Labels: automerge

#4776 Web readme update
  packages/web/README.md
Labels: automerge

#4738 Add Press Page to Celo.org
  packages/web/jestSetup.js
  packages/web/package.json
  packages/web/pages/api/press.ts
  packages/web/pages/press.tsx
  packages/web/public/static/locales/en/press.json
  packages/web/server/fetchPress.ts
  packages/web/src/_page-tests/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/exchange-icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/i18n.ts
  packages/web/src/press/Press.tsx
  packages/web/src/press/PressPage.test.ts
  packages/web/src/press/PressPage.tsx
  packages/web/src/shared/Footer.tsx
  packages/web/src/shared/__snapshots__/Footer.test.tsx.snap
  packages/web/src/shared/menu-items.ts
  packages/web/src/utils/languages.ts
Labels: automerge

#4498 celocli validator:status improvements
  packages/cli/package.json
  packages/cli/src/commands/validator/status.ts
  packages/docs/command-line-interface/validator.md
  yarn.lock
Labels: automerge

#4742 Web Touchups
  packages/web/public/static/locales/en/about.json
  packages/web/src/_page-tests/__snapshots__/about.test.tsx.snap
  packages/web/src/logos/cLabs-logo.png
Labels: automerge

#4774 [Wallet] Show correct app icon on older Android devices
  packages/mobile/android/app/src/main/AndroidManifest.xml
Labels: automerge

#4706 Script to deploy smart contract changes to a network via governance
  .circleci/config.yml
  packages/contractkit/src/base.ts
  packages/docs/developer-resources/contractkit/reference/modules/_base_.md
  packages/protocol/contracts/common/Accounts.sol
  packages/protocol/contracts/common/FixidityLib.sol
  packages/protocol/contracts/common/GasPriceMinimum.sol
  packages/protocol/contracts/common/Signatures.sol
  packages/protocol/contracts/common/linkedlists/AddressLinkedList.sol
  packages/protocol/contracts/common/linkedlists/AddressSortedLinkedList.sol
  packages/protocol/contracts/common/linkedlists/AddressSortedLinkedListWithMedian.sol
  packages/protocol/contracts/common/linkedlists/IntegerSortedLinkedList.sol
  packages/protocol/contracts/common/linkedlists/LinkedList.sol
  packages/protocol/contracts/common/linkedlists/SortedLinkedList.sol
  packages/protocol/contracts/common/linkedlists/SortedLinkedListWithMedian.sol
  packages/protocol/contracts/common/proxies/AddressLinkedListProxy.sol
  packages/protocol/contracts/common/proxies/AddressSortedLinkedListProxy.sol
  packages/protocol/contracts/common/proxies/AddressSortedLinkedListWithMedianProxy.sol
  packages/protocol/contracts/common/proxies/FixidityLibProxy.sol
  packages/protocol/contracts/common/proxies/IntegerSortedLinkedListProxy.sol
  packages/protocol/contracts/common/proxies/SignaturesProxy.sol
  packages/protocol/contracts/governance/Proposals.sol
  packages/protocol/contracts/governance/proxies/ProposalsProxy.sol
  packages/protocol/contracts/identity/Escrow.sol
  packages/protocol/contracts/identity/test/AttestationsTest.sol
  packages/protocol/contracts/identity/test/RandomTest.sol
  packages/protocol/contracts/stability/StableToken.sol
  packages/protocol/migrationsConfig.js
  packages/protocol/package.json
  packages/protocol/scripts/bash/check-versions.sh
  packages/protocol/scripts/bash/make-release.sh
  packages/protocol/scripts/truffle/make-release.ts
  packages/protocol/test/identity/attestations.ts
  packages/protocol/test/identity/random.ts
  packages/protocol/truffle-config.js
Labels: automerge

#4777 Add ODIS db migrations to signer init
  packages/base/src/async.test.ts
  packages/base/src/async.ts
  packages/contractkit/src/identity/odis/query.ts
  packages/docs/developer-resources/contractkit/reference/enums/_identity_odis_query_.errormessages.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_identity_odis_query_.servicecontext.md
  packages/docs/developer-resources/contractkit/reference/modules/_identity_odis_query_.md
  packages/phone-number-privacy/signer/migrations/20200330212224_create-accounts-table.ts
  packages/phone-number-privacy/signer/migrations/20200811163913_create_requests_table.ts
  packages/phone-number-privacy/signer/package.json
  packages/phone-number-privacy/signer/scripts/run-migrations.ts
  packages/phone-number-privacy/signer/src/database/database.ts
  packages/phone-number-privacy/signer/src/migrations/20200330212224_create-accounts-table.ts
  packages/phone-number-privacy/signer/src/migrations/20200811163913_create_requests_table.ts
Labels: automerge

#4794 [Wallet] Add deactivated debug mode message
  packages/mobile/src/account/reducer.ts
Labels: automerge

#4857 fix ODIS errs caused by missing timestamp
  packages/phone-number-privacy/signer/src/database/wrappers/request.ts
Labels: automerge

#4861 adds tests for missing timestamp, fix log error
  packages/phone-number-privacy/signer/src/database/wrappers/account.ts
  packages/phone-number-privacy/signer/test/end-to-end/get-blinded-sig.test.ts
Labels: automerge

#4798 Added Spanish Velocity paper
  packages/web/public/papers/cLabs_CBDC_Velocity_Spanish.pdf
  packages/web/public/static/locales/en/papers.json
  packages/web/server/index.ts
  packages/web/src/_page-tests/__snapshots__/papers.test.tsx.snap
  packages/web/src/press/PressPage.tsx
  packages/web/src/terms/Audits.tsx
  packages/web/src/terms/HelpfulLink.tsx
  packages/web/src/terms/Papers.tsx
  packages/web/src/terms/TermsPortal.tsx
Labels: automerge

#4720 add no-track analytics to celoreserve.org
  packages/reserve-site/.env.local.enc
  packages/reserve-site/next.config.js
  packages/reserve-site/package.json
  packages/reserve-site/src/pages/_app.tsx
  yarn.lock
Labels: automerge

#4845 [Docs] Add link to CIP repo
  packages/docs/community/contributing.md
Labels: automerge

#4863 Update Celo reference to the App Name in CELO Education
  packages/mobile/locales/en-US/goldEducation.json
  packages/mobile/locales/es-419/goldEducation.json
Labels: automerge, wallet

#4736 Update emulator install instructions
  packages/mobile/README.md
  packages/mobile/e2e/conf/avd_conf.ini
  packages/mobile/scripts/install_android_emulator_image.sh
Labels: automerge, wallet

#4871 [web] Typescript and Timelines
  packages/web/public/static/locales/en/home.json
  packages/web/src/_page-tests/__snapshots__/index.test.tsx.snap
  packages/web/tsconfig.server.json
Labels: automerge, web

#4741 Migrate and extend ODIS tests from mobile to ContractKit
  .env
  packages/contractkit/DEVELOP.md
  packages/contractkit/src/identity/odis/bls-blinding-client.ts
  packages/contractkit/src/identity/odis/matchmaking.test.ts
  packages/contractkit/src/identity/odis/phone-number-identifier.test.ts
  packages/contractkit/src/identity/odis/phone-number-identifier.ts
  packages/contractkit/src/identity/odis/query.ts
  packages/docs/developer-resources/contractkit/reference/interfaces/_identity_odis_phone_number_identifier_.phonenumberhashdetails.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_identity_odis_query_.matchmakingrequest.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_identity_odis_query_.phonenumberprivacyrequest.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_identity_odis_query_.signmessagerequest.md
  packages/docs/developer-resources/contractkit/reference/modules/_identity_odis_phone_number_identifier_.md
  packages/mobile/src/identity/matchmaking.test.ts
  packages/mobile/src/identity/privateHashing.test.ts
  packages/phone-number-privacy/combiner/jest.config.js
  packages/phone-number-privacy/combiner/jest_setup.ts
  packages/phone-number-privacy/combiner/package.json
  packages/phone-number-privacy/combiner/test/end-to-end/get-blinded-sig.test.ts
  packages/phone-number-privacy/combiner/test/end-to-end/get-contact-matches.test.ts
  packages/phone-number-privacy/combiner/test/end-to-end/resources.ts
  packages/phone-number-privacy/common/test/utils.ts
  packages/phone-number-privacy/signer/package.json
  yarn.lock
Labels: automerge

#4875 [Wallet] Fix revoke verification and add back dev settings for it
  packages/mobile/src/account/Settings.tsx
  packages/mobile/src/account/__snapshots__/Settings.test.tsx.snap
  packages/mobile/src/account/saga.ts
  packages/mobile/src/identity/revoke.ts
  packages/mobile/src/identity/saga.ts
Labels: automerge, wallet

#4859 [Wallet] Make the dismiss Gold Education button work
  packages/mobile/src/account/actions.ts
  packages/mobile/src/account/reducer.ts
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/test/schemas.ts
Labels: automerge, wallet

#4850 [Wallet] Hide CTAs with verification when insufficient balance
  packages/contractkit/src/identity/odis/phone-number-identifier.test.ts
  packages/contractkit/src/identity/odis/phone-number-identifier.ts
  packages/docs/developer-resources/contractkit/reference/interfaces/_identity_odis_phone_number_identifier_.phonenumberhashdetails.md
  packages/docs/developer-resources/contractkit/reference/modules/_identity_odis_phone_number_identifier_.md
  packages/mobile/src/account/Settings.test.tsx
  packages/mobile/src/account/Settings.tsx
  packages/mobile/src/account/__snapshots__/Settings.test.tsx.snap
  packages/mobile/src/app/selectors.test.ts
  packages/mobile/src/app/selectors.ts
  packages/mobile/src/exchange/CeloExchangeButtons.tsx
  packages/mobile/src/goldToken/selectors.ts
  packages/mobile/src/home/NotificationBox.test.tsx
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/identity/privateHashing.test.ts
  packages/mobile/src/identity/privateHashing.ts
  packages/mobile/src/send/Send.tsx
  packages/mobile/test/schemas.ts
Labels: automerge, wallet

#4884 updates ODIS README and migrations script
  packages/phone-number-privacy/signer/README.md
  packages/phone-number-privacy/signer/scripts/run-migrations.ts
Labels: automerge

#4885 Fix QR scan for requests
  packages/mobile/src/qrcode/utils.ts
  packages/mobile/src/send/utils.ts
Labels: automerge, wallet

#4822 Update Attestation cost parameters
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/src/account/__snapshots__/InviteReview.test.tsx.snap
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/invite/saga.test.ts
  packages/mobile/src/invite/saga.ts
Labels: automerge, wallet

#4858 [Wallet] Prevent getting stuck on PIN screen
  packages/mobile/src/navigator/DrawerNavigator.tsx
  packages/mobile/src/navigator/NavigatorWrapper.tsx
Labels: automerge, wallet

#4780 [Wallet] Reduce invite redemption time
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/src/analytics/Events.tsx
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/analytics/ValoraAnalytics.ts
  packages/mobile/src/import/ImportWallet.tsx
  packages/mobile/src/invite/EnterInviteCode.tsx
  packages/mobile/src/invite/saga.ts
  packages/mobile/src/onboarding/UseBackToWelcomeScreen.tsx
  packages/mobile/src/utils/time.ts
  packages/mobile/src/web3/dataEncryptionKey.ts
Labels: automerge, wallet

#4765 Enable usdGas + useLedger and refactor usdGas to gasCurrency
  packages/cli/src/base.ts
  packages/cli/src/commands/account/authorize.ts
  packages/cli/src/commands/account/register-metadata.ts
  packages/cli/src/commands/account/register.ts
  packages/cli/src/commands/config/set.ts
  packages/cli/src/commands/election/activate.ts
  packages/cli/src/commands/election/revoke.ts
  packages/cli/src/commands/election/vote.ts
  packages/cli/src/commands/exchange/celo.ts
  packages/cli/src/commands/exchange/dollars.ts
  packages/cli/src/commands/governance/withdraw.ts
  packages/cli/src/commands/lockedgold/unlock.ts
  packages/cli/src/commands/oracle/remove-expired-reports.ts
  packages/cli/src/commands/transfer/dollars.ts
  packages/cli/src/commands/validator/affiliate.ts
  packages/cli/src/commands/validator/deaffiliate.ts
  packages/cli/src/commands/validator/deregister.ts
  packages/cli/src/commands/validator/force-deaffiliate.ts
  packages/cli/src/commands/validator/register.ts
  packages/cli/src/commands/validator/update-bls-public-key.ts
  packages/cli/src/commands/validatorgroup/commission.ts
  packages/cli/src/commands/validatorgroup/deregister.ts
  packages/cli/src/commands/validatorgroup/member.ts
  packages/cli/src/commands/validatorgroup/register.ts
  packages/cli/src/utils/config.ts
  packages/docs/command-line-interface/account.md
  packages/docs/command-line-interface/config.md
  packages/docs/command-line-interface/dkg.md
  packages/docs/command-line-interface/election.md
  packages/docs/command-line-interface/exchange.md
  packages/docs/command-line-interface/governance.md
  packages/docs/command-line-interface/identity.md
  packages/docs/command-line-interface/lockedgold.md
  packages/docs/command-line-interface/multisig.md
  packages/docs/command-line-interface/network.md
  packages/docs/command-line-interface/node.md
  packages/docs/command-line-interface/oracle.md
  packages/docs/command-line-interface/releasegold.md
  packages/docs/command-line-interface/reserve.md
  packages/docs/command-line-interface/rewards.md
  packages/docs/command-line-interface/transfer.md
  packages/docs/command-line-interface/validator.md
  packages/docs/command-line-interface/validatorgroup.md
Labels: automerge

#4873 [docs] Single list of ReleaseGold deployments
  packages/docs/celo-holder-guide/quick-start.md
Labels: automerge

#4908 [Docs] Update Attestation Service docs for 1.0.3
  packages/docs/operations-manual/attestation-service.md
Labels: automerge
