Repository celo-org/celo-monorepo, pull requests merged in 2021-01, with the labels that each got.

#6319 Fix param order on account:new internal call
  packages/cli/src/commands/account/new.ts
Labels: automerge

#6363 Updated celotool documentation
  packages/celotool/README.md
Labels: automerge

#6367 [Wallet] Update test snapshot for 2021
  packages/mobile/src/transactions/__snapshots__/TransactionsList.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/color.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/composition.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/exchange-icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/icons.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/index.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/key-imagery.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/logo.test.tsx.snap
  packages/web/src/_page-tests/experience/__snapshots__/typography.test.tsx.snap
  packages/web/src/shared/__snapshots__/Footer.test.tsx.snap
Labels: automerge, wallet

#6332 [Wallet] Bump version to 1.7.2 and update licenses
  packages/mobile/android/app/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/src/account/LicenseDisclaimer.txt
Labels: automerge, wallet

#6383 Fix typo in docs: '10-18' should be '10^-18'
  packages/docs/command-line-interface/introduction.md
Labels: automerge

#6304 ODIS signer patch
  packages/phone-number-privacy/signer/src/server.ts
Labels: automerge

#6380 [Wallet] Use known names on CELO feed
  packages/mobile/__mocks__/react-i18next.js
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/locales/es-419/walletFlow5.json
  packages/mobile/locales/pt-BR/walletFlow5.json
  packages/mobile/src/transactions/CeloTransferFeedItem.test.tsx
  packages/mobile/src/transactions/CeloTransferFeedItem.tsx
  packages/mobile/src/transactions/__snapshots__/CeloTransferFeedItem.test.tsx.snap
Labels: automerge, wallet

#6393 Env-test fixes for staging
  .env.mnemonic.staging.enc
  .env.staging
  packages/env-tests/package.json
  packages/env-tests/src/context.ts
  packages/env-tests/src/env.ts
  packages/env-tests/src/monorepoRun.ts
  packages/env-tests/src/shared/attestation.ts
  packages/env-tests/src/tests/oracle.ts
  packages/env-tests/src/tests/reserve.ts
  scripts/key_placer.sh
Labels: automerge

#6388 [Wallet] Add TransactionReview screen for CELO rewards
  packages/mobile/branding/celo/src/brandingConfig.ts
  packages/mobile/locales/en-US/walletFlow5.json
  packages/mobile/locales/es-419/walletFlow5.json
  packages/mobile/locales/pt-BR/walletFlow5.json
  packages/mobile/scripts/sync_branding.sh
  packages/mobile/src/app/WebViewScreen.tsx
  packages/mobile/src/firebase/notifications.test.ts
  packages/mobile/src/firebase/notifications.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/transactions/CeloTransferFeedItem.tsx
  packages/mobile/src/transactions/TransferConfirmationCard.test.tsx
  packages/mobile/src/transactions/TransferConfirmationCard.tsx
  packages/mobile/src/transactions/TransferFeedItem.tsx
  packages/mobile/src/transactions/UserSection.tsx
  packages/mobile/src/transactions/__snapshots__/TransferConfirmationCard.test.tsx.snap
  packages/mobile/src/transactions/actions.ts
Labels: automerge, consumer incentives, wallet

#6391 [Wallet] Add dynamic notification to tray from Firebase
  packages/mobile/branding/celo/src/images/remote-notification.png
  packages/mobile/scripts/sync_branding.sh
  packages/mobile/src/firebase/db-rules.json
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/home/__snapshots__/NotificationBox.test.tsx.snap
  packages/mobile/src/home/actions.ts
  packages/mobile/src/home/reducers.ts
  packages/mobile/src/home/saga.ts
  packages/mobile/src/images/Images.ts
  packages/mobile/src/redux/reducers.ts
  packages/mobile/src/redux/store.ts
  packages/mobile/test/schemas.ts
  packages/react-components/components/CallToActionsBar.tsx
  packages/react-components/components/SimpleMessagingCard.tsx
Labels: automerge, consumer incentives, wallet

#6399 [Wallet] Add deep links for Cash In screen
  packages/mobile/src/app/WebViewScreen.tsx
  packages/mobile/src/app/saga.ts
Labels: automerge, consumer incentives, wallet

#6405 [Wallet] Allow opening WebView or external browser from push notification
  packages/mobile/src/app/actions.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/firebase/notifications.ts
Labels: automerge, consumer incentives, wallet

#6372 Mnemonic validation flexibility within Valora
  packages/cli/src/commands/account/new.ts
  packages/cli/src/commands/account/recover-old.ts
  packages/mobile/src/backup/utils.test.ts
  packages/mobile/src/import/saga.ts
  packages/sdk/base/src/string.ts
  packages/sdk/utils/src/account.test.ts
  packages/sdk/utils/src/account.ts
  packages/sdk/utils/src/string.ts
Labels: automerge, wallet

#6407 [Wallet] Ask pincode when opening Account Key screen from notification
  packages/mobile/src/home/NotificationBox.tsx
Labels: automerge, wallet

#6384 Don't serve LES clients for oracle full nodes, other various fixes
  .env.alfajores
  .env.baklava
  .env.oracledev
  .env.rc1
  packages/celotool/src/lib/endpoints.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/celotool/src/lib/k8s-cluster/aks.ts
  packages/celotool/src/lib/k8s-fullnode/aks.ts
  packages/celotool/src/lib/k8s-fullnode/base.ts
  packages/celotool/src/lib/prometheus.ts
  packages/helm-charts/celo-fullnode/templates/statefulset.yaml
  packages/helm-charts/celo-fullnode/values.yaml
  packages/helm-charts/common/templates/_helpers.tpl
Labels: automerge

#6373 Run CI against contracts v2
  .circleci/config.yml
Labels: automerge

#6417 [Wallet] Add host of URI as title to WebViewScreen and fix deep links
  packages/mobile/src/app/WebViewScreen.tsx
  packages/mobile/src/transactions/TransferConfirmationCard.tsx
Labels: automerge, wallet

#6350 Show the international format when displaying phone numbers in Valora
  packages/cli/package-lock.json
  packages/mobile/package.json
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationCard.test.tsx.snap
  packages/mobile/src/escrow/__snapshots__/ReclaimPaymentConfirmationScreen.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeConfirmationCard.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeReview.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/WithdrawCeloReviewScreen.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/WithdrawCeloSummary.test.tsx.snap
  packages/mobile/src/onboarding/registration/NameAndNumber.tsx
  packages/mobile/src/onboarding/registration/__snapshots__/NameAndNumber.test.tsx.snap
  packages/mobile/src/qrcode/__snapshots__/QRCode.test.tsx.snap
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransferConfirmationCard.test.tsx.snap
  packages/mobile/src/verify/VerificationEducationScreen.tsx
  packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
  packages/moonpay-auth/yarn.lock
  packages/react-components/components/Expandable.tsx
  packages/react-components/components/PhoneNumberInput.test.tsx
  packages/react-components/components/PhoneNumberInput.tsx
  packages/react-components/components/PhoneNumberWithFlag.tsx
  packages/react-components/components/__snapshots__/Avatar.test.tsx.snap
  packages/react-components/components/__snapshots__/PhoneNumberInput.test.tsx.snap
  packages/sdk/utils/package.json
  yarn.lock
Labels: automerge, wallet

#6414 Add from address option in make release
  packages/protocol/scripts/bash/make-release.sh
  packages/protocol/scripts/truffle/make-release.ts
Labels: automerge

#6401 Extend SortedOraclesWrapper to support reporting for arbitrary currency pairs
  packages/dev-utils/src/describeEach.ts
  packages/sdk/contractkit/src/wrappers/SortedOracles.test.ts
  packages/sdk/contractkit/src/wrappers/SortedOracles.ts
Labels: automerge, sdk

#6209 EIP712 signature over attestation security code
  dependency-graph.json
  dockerfiles/celotool/Dockerfile
  packages/attestation-service/scripts/generate-signed-code.ts
  packages/attestation-service/src/requestHandlers/get_attestation.ts
  packages/celotool/package.json
  packages/celotool/src/cmds/account/verify.ts
  packages/celotool/src/cmds/bots/auto-verify.ts
  packages/celotool/src/lib/attestation.ts
  packages/env-tests/src/shared/attestation.ts
  packages/env-tests/src/tests/attestation.ts
  packages/mobile/src/identity/securityCode.test.ts
  packages/mobile/src/identity/securityCode.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/verify/VerificationCodeInput.tsx
  packages/mobile/src/verify/VerificationInputScreen.tsx
  packages/sdk/contractkit/src/wrappers/Attestations.ts
  packages/sdk/utils/src/attestations.test.ts
  packages/sdk/utils/src/attestations.ts
  packages/sdk/utils/src/index.ts
  packages/sdk/utils/src/signatureUtils.ts
  packages/sdk/utils/src/typed-data-constructors.ts
Labels: automerge

#6415 Remove broken header links in generated CLI docs
  packages/cli/generate_docs.sh
  packages/cli/package.json
  packages/docs/.gitignore
  packages/docs/command-line-interface/account.md
  packages/docs/command-line-interface/autocomplete.md
  packages/docs/command-line-interface/commands.md
  packages/docs/command-line-interface/config.md
  packages/docs/command-line-interface/dkg.md
  packages/docs/command-line-interface/election.md
  packages/docs/command-line-interface/exchange.md
  packages/docs/command-line-interface/governance.md
  packages/docs/command-line-interface/help.md
  packages/docs/command-line-interface/identity.md
  packages/docs/command-line-interface/lockedgold.md
  packages/docs/command-line-interface/multisig.md
  packages/docs/command-line-interface/network.md
  packages/docs/command-line-interface/node.md
  packages/docs/command-line-interface/oracle.md
  packages/docs/command-line-interface/releasegold.md
  packages/docs/command-line-interface/reserve.md
  packages/docs/command-line-interface/rewards.md
  packages/docs/command-line-interface/transfer.md
  packages/docs/command-line-interface/validator.md
  packages/docs/command-line-interface/validatorgroup.md
  packages/docs/developer-resources/utils/reference/modules/_packages_sdk_utils_src_string_.md
Labels: automerge

#6435 CLI->1.0.0-dev + updated changelog
  packages/cli/CHANGELOG.md
  packages/cli/package.json
Labels: automerge

#6432 chore: pinning version of secp256k1
  packages/sdk/wallets/wallet-hsm-aws/package.json
  packages/sdk/wallets/wallet-hsm-azure/package.json
  packages/sdk/wallets/wallet-hsm/package.json
  yarn.lock
Labels: automerge

#6333 Replaced Verification Flow Images in Docs with Links
  packages/docs/celo-codebase/wallet/how-the-wallet-works/verification.md
Labels: automerge

#6440 Updated blockscout commit hash
  .env.alfajores
  .env.baklava
  .env.rc1
  packages/helm-charts/blockscout/templates/blockscout-indexer.deployment.yaml
  packages/helm-charts/blockscout/values.yaml
Labels: automerge

#6422 clarifies where to run command when building wallet
  packages/mobile/README.md
Labels: automerge

#6445 Add quicktest command
  packages/protocol/package.json
  packages/protocol/scripts/bash/backupmigrations.sh
  packages/protocol/scripts/bash/quicktest.sh
Labels: automerge

#6438 Wallet: Update subtitles for adding and withdrawal
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/locales/es-419/fiatExchangeFlow.json
  packages/mobile/locales/pt-BR/fiatExchangeFlow.json
Labels: automerge, wallet

#6437 [Wallet] Enable 8 digit code verification and ignore attestation services below 1.1.0
  packages/env-tests/src/shared/attestation.ts
  packages/mobile/src/firebase/firebase.test.ts
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/flags.ts
  packages/mobile/src/identity/securityCode.ts
  packages/mobile/src/identity/verification.test.ts
  packages/mobile/src/identity/verification.ts
  packages/mobile/src/navigator/NavigatorWrapper.tsx
  packages/mobile/src/utils/versionCheck.test.ts
  packages/mobile/src/utils/versionCheck.ts
  packages/sdk/contractkit/src/wrappers/Attestations.ts
  packages/sdk/utils/src/attestations.ts
Labels: automerge, wallet

#6450 Update README.md
  packages/sdk/contractkit/README.md
Labels: automerge, contractkit, devX, docs

#6456 Update pre-deploy script
  packages/mobile/package.json
Labels: automerge, wallet

#6449 chore: attestation-service-v1.2.0
  .env.alfajores
  .env.baklava
  packages/attestation-service/package.json
Labels: automerge

#6458 Retry Firebase connection upon failure
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/pt-BR/global.json
  packages/mobile/src/firebase/saga.ts
Labels: automerge, wallet

#6468 add kit.connection.web3...
  packages/sdk/contractkit/README.md
Labels: automerge

#6466 add install instructions for CLI readme
  packages/cli/README.md
Labels: automerge

#6452 Update Governance voting docs and add reminder for Ledger users
  packages/docs/celo-holder-guide/voting-governance.md
Labels: automerge

#6478 [Wallet] Ask PIN immediately on BackupForceScreen
  packages/mobile/src/backup/BackupForceScreen.tsx
Labels: automerge, wallet

#6375 [N01, N05, N06] Cleanup bash scripts
  packages/protocol/scripts/bash/release-on-devchain.sh
  packages/protocol/scripts/bash/verify-deployed.sh
Labels: automerge

#6377 [N04] Fix typos
  packages/protocol/lib/compatibility/version.ts
  packages/protocol/scripts/truffle/verify-bytecode.ts
Labels: automerge

#6379 [L02] Don't overwrite logfile
  packages/protocol/scripts/bash/check-versions.sh
  packages/protocol/scripts/bash/generate-old-devchain-and-build.sh
  packages/protocol/scripts/bash/verify-deployed.sh
  packages/protocol/scripts/bash/verify-release.sh
Labels: automerge

#6381 [L01] Use only one definition of the Registry's address
  packages/protocol/scripts/truffle/deploy_release_contracts.ts
  packages/protocol/scripts/truffle/make-release.ts
Labels: automerge

#6382 [M01] Match exact number of bytes for bytecode metadata
  packages/protocol/lib/bytecode.ts
Labels: automerge

#6409 [N03] Remove ToDos
  packages/protocol/lib/registry-utils.ts
  packages/protocol/scripts/bash/verify-deployed.sh
Labels: automerge

#6448 Remove old typeform application link
  packages/docs/validator-guide/celo-foundation-voting-policy.md
Labels: automerge

#6479 Fix phone number search on Send Screen
  packages/mobile/src/recipients/recipient.ts
Labels: automerge, wallet

#6338 Fix sporadic payment request hang
  packages/mobile/src/identity/actions.ts
  packages/mobile/src/identity/contactMapping.ts
  packages/mobile/src/identity/reducer.ts
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.test.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.tsx
Labels: automerge, wallet

#6493 Add dynamic download link to Valora invite texts
  packages/mobile/.env.alfajores
  packages/mobile/.env.alfajoresdev
  packages/mobile/.env.mainnet
  packages/mobile/.env.mainnetdev
  packages/mobile/src/config.ts
  packages/mobile/src/invite/saga.ts
Labels: automerge, wallet

#6496 Fix @ledgerhq package version in CK and CLI
  packages/cli/package.json
  packages/sdk/wallets/wallet-ledger/package.json
  yarn.lock
Labels: automerge

#6465 [Wallet] Fix navigation init
  packages/mobile/src/navigator/NavigationService.ts
  packages/mobile/src/navigator/NavigatorWrapper.tsx
Labels: automerge, wallet

#6498 [Wallet] Apply WebView opacity hack fix globally
  packages/mobile/src/account/Licenses.tsx
  packages/mobile/src/account/__snapshots__/Licenses.test.tsx.snap
  packages/mobile/src/app/WebViewScreen.tsx
  packages/mobile/src/components/WebView.tsx
  packages/mobile/src/fiatExchanges/LocalProviderCashOut.tsx
  packages/mobile/src/fiatExchanges/MoonPay.tsx
  packages/mobile/src/verify/safety/GoogleReCaptcha.tsx
Labels: automerge, wallet

#6455 Add Celo Signal form and calendar links
  packages/docs/celo-holder-guide/voting-governance.md
  packages/docs/celo-holder-guide/voting-validators.md
  packages/docs/getting-started/running-a-full-node-in-alfajores.md
  packages/docs/getting-started/running-a-full-node-in-baklava.md
  packages/docs/getting-started/running-a-full-node-in-mainnet.md
  packages/docs/getting-started/running-a-validator-in-baklava.md
  packages/docs/getting-started/running-a-validator-in-mainnet.md
  packages/docs/validator-guide/celo-foundation-voting-policy.md
Labels: automerge

#6447 [Wallet] Add tests for CELO rewards recent changes
  packages/mobile/src/app/saga.test.ts
  packages/mobile/src/firebase/notifications.test.ts
  packages/mobile/src/home/NotificationBox.test.tsx
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/home/__snapshots__/NotificationBox.test.tsx.snap
  packages/mobile/src/home/reducers.test.ts
  packages/mobile/src/home/reducers.ts
  packages/mobile/src/transactions/TransferConfirmationCard.test.tsx
  packages/mobile/src/transactions/TransferConfirmationCard.tsx
  packages/mobile/src/transactions/__snapshots__/TransferConfirmationCard.test.tsx.snap
Labels: automerge, wallet

#6502 Adjust getProposalStage behavior
  packages/protocol/contracts/governance/Governance.sol
Labels: automerge

#6507 Update Wallet Exchanges page with new listings
  packages/mobile/src/config.ts
Labels: automerge, wallet

#6299 Reserve supports multiple exchanges
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/contracts/stability/interfaces/IReserve.sol
  packages/protocol/test/stability/reserve.ts
Labels: automerge

#6515 Handle revert flag from web3 for contract calls
  packages/sdk/connect/src/connection.ts
Labels: automerge

#6505 Fix call to set gas currency in CLI base
  packages/cli/src/base.ts
Labels: automerge

#6516 Modified version of #6474: Fix dependencies to work on standalone installations and in environments without Git
  dependency-graph.json
  packages/sdk/connect/package.json
  packages/sdk/contractkit/package.json
  packages/sdk/explorer/package.json
  packages/sdk/governance/package.json
  packages/sdk/identity/package.json
  packages/sdk/network-utils/package.json
  packages/sdk/transactions-uri/package.json
  packages/sdk/utils/package.json
  packages/sdk/wallets/wallet-base/package.json
  packages/sdk/wallets/wallet-hsm-aws/package.json
  packages/sdk/wallets/wallet-hsm-azure/package.json
  packages/sdk/wallets/wallet-hsm/package.json
  packages/sdk/wallets/wallet-ledger/package.json
  packages/sdk/wallets/wallet-local/package.json
  packages/sdk/wallets/wallet-remote/package.json
  packages/sdk/wallets/wallet-rpc/package.json
  yarn.lock
Labels: automerge

#6506 [Wallet] Add loading indicator to WebViewScreen
  packages/mobile/src/app/WebViewScreen.tsx
Labels: automerge, wallet

#6524 Fix initializationData and verify-deployed
  packages/protocol/releaseData/initializationData/release2.json
  packages/protocol/scripts/bash/verify-deployed.sh
  packages/protocol/scripts/truffle/make-release.ts
Labels: automerge

#6469 update Hello Celo (sending CELO) docs code example
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/walkthroughs/hellocelo.md
Labels: automerge, contractkit, devX, docs

#6489 Create migrating-to-contract-v1
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/contractkit/migrating-to-contractkit-v1.md
Labels: automerge, contractkit, devX, docs

#6543 Build all of protocol during make-release
  packages/protocol/scripts/bash/make-release.sh
Labels: automerge

#6431 Bundle approve and request in a single action
  packages/komencikit/examples/attestation-flow.ts
  packages/komencikit/src/actions.ts
  packages/komencikit/src/kit.ts
Labels: automerge

#6549 Added json file for release2 input data
  packages/protocol/releaseData/initializationData/release2.json
Labels: automerge

#6530 [Wallet] UI fix for Expandable component
  packages/mobile/src/exchange/__snapshots__/ExchangeConfirmationCard.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/ExchangeReview.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/WithdrawCeloReviewScreen.test.tsx.snap
  packages/mobile/src/exchange/__snapshots__/WithdrawCeloSummary.test.tsx.snap
  packages/mobile/src/onboarding/registration/__snapshots__/NameAndNumber.test.tsx.snap
  packages/mobile/src/send/__snapshots__/SendConfirmation.test.tsx.snap
  packages/mobile/src/transactions/__snapshots__/TransferConfirmationCard.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
  packages/react-components/components/Expandable.tsx
  packages/react-components/components/PhoneNumberInput.tsx
  packages/react-components/components/__snapshots__/PhoneNumberInput.test.tsx.snap
Labels: automerge, wallet

#6553 Revert "Remove multiproxy guide on mainnet (#5996)"
  packages/docs/getting-started/running-a-validator-in-mainnet.md
Labels: automerge

#4747 CIP-21: Governable LookbackWindow Smart Contract changes
  .circleci/config.yml
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/celotool/src/e2e-tests/validator_order_tests.ts
  packages/celotool/src/lib/geth.ts
  packages/protocol/contracts/governance/BlockchainParameters.sol
  packages/protocol/contracts/governance/test/BlockchainParametersTest.sol
  packages/protocol/migrations/19_blockchainparams.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/test/governance/network/blockchainparams.ts
  packages/sdk/contractkit/src/wrappers/BlockchainParameters.ts
Labels: CAP, Component: Contracts, commit

#6537 Add secret to alfajores env
  .env.mnemonic.alfajores.enc
Labels: automerge

#6503 Update CODEOWNERS with github CAP team
  .github/CODEOWNERS
Labels: automerge

#6540 CLI->1.0.1-dev, SDK->1.0.1-dev
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/CHANGELOG.md
  packages/cli/package.json
  packages/docs/SUMMARY.md
  packages/docs/community/release-process/base-cli-contractkit-dappkit-utils.md
  packages/env-tests/package.json
  packages/komencikit/package.json
  packages/metadata-crawler/package.json
  packages/mobile/package.json
  packages/protocol/package.json
  packages/react-components/package.json
  packages/sdk/CHANGELOG.md
  packages/sdk/base/CHANGELOG.md
  packages/sdk/base/package.json
  packages/sdk/connect/package.json
  packages/sdk/contractkit/CHANGELOG.md
  packages/sdk/contractkit/package.json
  packages/sdk/dappkit/CHANGELOG.md
  packages/sdk/dappkit/package.json
  packages/sdk/explorer/package.json
  packages/sdk/governance/package.json
  packages/sdk/identity/package.json
  packages/sdk/network-utils/package.json
  packages/sdk/transactions-uri/package.json
  packages/sdk/utils/CHANGELOG.md
  packages/sdk/utils/package.json
  packages/sdk/wallets/wallet-base/package.json
  packages/sdk/wallets/wallet-hsm-aws/package.json
  packages/sdk/wallets/wallet-hsm-azure/package.json
  packages/sdk/wallets/wallet-hsm/package.json
  packages/sdk/wallets/wallet-ledger/package.json
  packages/sdk/wallets/wallet-local/package.json
  packages/sdk/wallets/wallet-remote/package.json
  packages/sdk/wallets/wallet-rpc/package.json
Labels: automerge

#6510 [Wallet] Add Bidali integration
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/locales/es-419/fiatExchangeFlow.json
  packages/mobile/locales/pt-BR/fiatExchangeFlow.json
  packages/mobile/secrets.json.enc
  packages/mobile/src/app/saga.test.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/config.ts
  packages/mobile/src/fiatExchanges/BidaliScreen.tsx
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/fiatExchanges/actions.ts
  packages/mobile/src/fiatExchanges/saga.test.ts
  packages/mobile/src/fiatExchanges/saga.ts
  packages/mobile/src/geth/networkConfig.ts
  packages/mobile/src/home/NotificationBox.test.tsx
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/pincode/PincodeEnter.tsx
  packages/mobile/src/recipients/recipient.ts
  packages/mobile/src/redux/sagas.ts
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/actions.ts
  packages/mobile/src/send/saga.test.ts
  packages/mobile/src/send/saga.ts
Labels: automerge, wallet

#6534 Enable Churrito and Donut in genesis for e2e tests' local geth nodes.
  packages/celotool/src/e2e-tests/attestations_tests.ts
  packages/celotool/src/e2e-tests/blockchain_parameters_tests.ts
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/celotool/src/e2e-tests/replica_tests.ts
  packages/celotool/src/e2e-tests/slashing_tests.ts
  packages/celotool/src/e2e-tests/sync_tests.ts
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/celotool/src/e2e-tests/validator_order_tests.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/generate_utils.ts
  packages/celotool/src/lib/interfaces/genesis-config.ts
Labels: automerge

#6512 [Wallet] Support remote images for Firebase controlled notifications
  packages/mobile/branding/celo/src/images/remote-notification.png
  packages/mobile/locales/en-US/inviteFlow11.json
  packages/mobile/locales/en-US/nuxVerification2.json
  packages/mobile/locales/es-419/inviteFlow11.json
  packages/mobile/locales/es-419/nuxVerification2.json
  packages/mobile/locales/pt-BR/inviteFlow11.json
  packages/mobile/locales/pt-BR/nuxVerification2.json
  packages/mobile/scripts/sync_branding.sh
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/home/__snapshots__/NotificationBox.test.tsx.snap
  packages/mobile/src/home/reducers.ts
  packages/mobile/src/images/Images.ts
  packages/react-components/components/SimpleMessagingCard.test.tsx
  packages/react-components/components/SimpleMessagingCard.tsx
Labels: automerge, wallet

#6525 [Wallet] Track send origin
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/analytics/types.ts
  packages/mobile/src/fiatExchanges/saga.test.ts
  packages/mobile/src/fiatExchanges/saga.ts
  packages/mobile/src/firebase/notifications.test.ts
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.test.tsx
  packages/mobile/src/paymentRequest/IncomingPaymentRequestListItem.tsx
  packages/mobile/src/qrcode/utils.ts
  packages/mobile/src/send/Send.tsx
  packages/mobile/src/send/SendAmount.test.tsx
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/SendConfirmation.test.tsx
  packages/mobile/src/send/SendConfirmation.tsx
  packages/mobile/src/send/ValidateRecipientAccount.test.tsx
  packages/mobile/src/send/ValidateRecipientAccount.tsx
  packages/mobile/src/send/ValidateRecipientIntro.test.tsx
  packages/mobile/src/send/ValidateRecipientIntro.tsx
  packages/mobile/src/send/saga.test.ts
  packages/mobile/src/send/utils.test.ts
  packages/mobile/src/send/utils.ts
  packages/mobile/src/transactions/actions.ts
Labels: automerge, wallet

#6520 [Wallet] Allow deep linking into any screen from notifications
  packages/mobile/src/app/actions.ts
  packages/mobile/src/app/saga.test.ts
  packages/mobile/src/app/saga.ts
  packages/mobile/src/firebase/notifications.test.ts
  packages/mobile/src/firebase/notifications.ts
  packages/mobile/src/home/NotificationBox.test.tsx
  packages/mobile/src/home/NotificationBox.tsx
Labels: automerge, wallet

#6559 include info about custom contract interactions
  packages/docs/SUMMARY.md
  packages/docs/developer-resources/contractkit/usage.md
  packages/docs/developer-resources/walkthroughs/hello-contract-remote-node.md
Labels: automerge, contractkit, devX, docs

#6546 [Wallet] Remote notification targeting specific app versions and countries
  packages/mobile/src/firebase/db-rules.json
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/home/reducers.test.ts
  packages/mobile/src/home/reducers.ts
  packages/mobile/src/home/selectors.test.ts
  packages/mobile/src/home/selectors.ts
  packages/mobile/src/utils/versionCheck.test.ts
  packages/mobile/src/utils/versionCheck.ts
Labels: automerge, wallet

#6574 Add more support for Churrito and Donut hard forks in celotool
  .env
  packages/celotool/src/cmds/geth/start.ts
Labels: automerge

#6576 Small Docs Fixes related to CK1 release
  packages/cli/CHANGELOG.md
  packages/docs/developer-resources/contractkit/migrating-to-contractkit-v1.md
  packages/sdk/CHANGELOG.md
Labels: automerge

#6572 Add cEUR to core contracts
  .circleci/config.yml
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/stability/ExchangeEUR.sol
  packages/protocol/contracts/stability/StableTokenEUR.sol
  packages/protocol/contracts/stability/proxies/ExchangeEURProxy.sol
  packages/protocol/contracts/stability/proxies/StableTokenEURProxy.sol
  packages/protocol/lib/registry-utils.ts
  packages/protocol/releaseData/initializationData/release3.json
  packages/protocol/scripts/bash/check-versions.sh
  packages/protocol/scripts/bash/generate-old-devchain-and-build.sh
  packages/protocol/scripts/bash/make-release.sh
  packages/protocol/scripts/bash/release-on-devchain.sh
  packages/protocol/scripts/bash/verify-deployed.sh
  packages/protocol/scripts/bash/verify-release.sh
Labels: automerge

#6586 new year new key
  packages/reserve-site/.env.local.enc
Labels: automerge

#6522 [Wallet] Add native screen for Consumer Incentives
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/locales/en-US/global.json
  packages/mobile/locales/es-419/fiatExchangeFlow.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/pt-BR/fiatExchangeFlow.json
  packages/mobile/locales/pt-BR/global.json
  packages/mobile/scripts/sync_branding.sh
  packages/mobile/src/app/ErrorMessages.ts
  packages/mobile/src/app/saga.test.ts
  packages/mobile/src/consumerIncentives/ConsumerIncentivesHomeScreen.test.tsx
  packages/mobile/src/consumerIncentives/ConsumerIncentivesHomeScreen.tsx
  packages/mobile/src/consumerIncentives/__snapshots__/ConsumerIncentivesHomeScreen.test.tsx.snap
  packages/mobile/src/consumerIncentives/contentFetcher.ts
  packages/mobile/src/firebase/db-rules.json
  packages/mobile/src/home/NotificationBox.tsx
  packages/mobile/src/icons/DefaultAvatar.tsx
  packages/mobile/src/icons/Gift.tsx
  packages/mobile/src/navigator/BackButton.tsx
  packages/mobile/src/navigator/DrawerNavigator.tsx
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/RewardsPill.test.tsx
  packages/mobile/src/navigator/RewardsPill.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/__snapshots__/RewardsPill.test.tsx.snap
  packages/mobile/src/navigator/types.tsx
  packages/mobile/src/transactions/TransferConfirmationCard.test.tsx
  packages/mobile/src/transactions/TransferConfirmationCard.tsx
  packages/mobile/src/utils/contentTranslations.ts
  packages/react-components/styles/colors.tsx
Labels: automerge, wallet

#6575 Add prepublish hook to generate the npm-shrinkwrap
  packages/cli/npm-shrinkwrap.json
  packages/cli/package-lock.json
  packages/cli/package.json
Labels: automerge

#6619 Fixed Global Flag Parsing in CLI
  packages/cli/CHANGELOG.md
  packages/cli/package.json
  packages/cli/src/commands/account/balance.ts
  packages/cli/src/commands/account/lock.ts
  packages/cli/src/commands/config/get.ts
Labels: automerge, devX

#6603 Attestation Service Docs Update
  packages/docs/validator-guide/attestation-service.md
Labels: automerge

#6618 Add proxy docs and recommend upgrade to 1.2.2
  packages/docs/SUMMARY.md
  packages/docs/validator-guide/node-upgrades.md
Labels: automerge

#6584 Update README.md
  README.md
Labels: automerge

#6623 [Wallet] Make providers on providers selection screen clickable
  packages/mobile/locales/es-419/fiatExchangeFlow.json
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.test.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/ProviderOptionsScreen.test.tsx.snap
Labels: automerge, wallet

#6583 Update attestation service expiry defaults
  packages/attestation-service/config/.env.development
Labels: automerge

#6627 [Wallet] Fix crash on Android when opening the Bidali screen
  packages/mobile/src/components/WebView.tsx
  packages/mobile/src/fiatExchanges/BidaliScreen.tsx
Labels: automerge, wallet

#6501 [Wallet]: Update radio button to new design
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeOptions.test.tsx.snap
  packages/mobile/src/icons/RadioIcon.tsx
  packages/mobile/src/localCurrency/__snapshots__/SelectLocalCurrency.test.tsx.snap
  packages/react-components/components/SelectionOption.tsx
  packages/react-components/components/__snapshots__/SelectionOption.test.tsx.snap
  packages/react-components/icons/CheckCircle.tsx
  packages/react-components/icons/RadioButton.tsx
Labels: automerge, wallet

#6216 Batch Feeless Verification Transactions
  packages/mobile/src/escrow/saga.ts
  packages/mobile/src/identity/feelessVerification.ts
  packages/mobile/src/identity/verification.ts
Labels: automerge, wallet

#6671 [cli] Missing dep in the shrinkwrap.json file
  packages/cli/.npmignore
  packages/cli/CHANGELOG.md
  packages/cli/npm-shrinkwrap.json
  packages/cli/package.json
  packages/cli/scripts/check_shrinkwrap_dirty.sh
Labels: automerge

#6550 Update Komenci to the new version
  .env.alfajores
  .env.rc1
Labels: automerge

#6608 Show owner in releasegold:show
  packages/cli/src/commands/releasegold/show.ts
  packages/docs/developer-resources/base/reference/README.md
  packages/docs/developer-resources/connect/reference/README.md
  packages/docs/developer-resources/connect/reference/classes/_connection_.connection.md
  packages/docs/developer-resources/contractkit/reference/README.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_attestations_.attestationswrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_blockchainparameters_.blockchainparameterswrapper.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_releasegold_.releasegoldwrapper.md
  packages/docs/developer-resources/contractkit/reference/enums/_wrappers_attestations_.attestationservicestatusstate.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.actionableattestation.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.attestationservicestatusresponse.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.unselectedrequest.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_releasegold_.releasegoldinfo.md
  packages/docs/developer-resources/contractkit/reference/modules/_wrappers_attestations_.md
  packages/docs/developer-resources/explorer/reference/README.md
  packages/docs/developer-resources/governance/reference/README.md
  packages/docs/developer-resources/identity/reference/README.md
  packages/docs/developer-resources/network-utils/reference/README.md
  packages/docs/developer-resources/transactions-uri/reference/README.md
  packages/docs/developer-resources/utils/reference/README.md
  packages/docs/developer-resources/wallet-base/reference/README.md
  packages/docs/developer-resources/wallet-hsm-aws/reference/README.md
  packages/docs/developer-resources/wallet-hsm-azure/reference/README.md
  packages/docs/developer-resources/wallet-hsm/reference/README.md
  packages/docs/developer-resources/wallet-ledger/reference/README.md
  packages/docs/developer-resources/wallet-local/reference/README.md
  packages/docs/developer-resources/wallet-remote/reference/README.md
  packages/docs/developer-resources/wallet-rpc/reference/README.md
  packages/sdk/contractkit/src/wrappers/ReleaseGold.ts
Labels: automerge

#6628 fix identity:withdraw-attestation-rewards command
  packages/cli/src/commands/identity/withdraw-attestation-rewards.ts
Labels: automerge

#6663 [Wallet] Fix 8 digit codes for mainnet
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/src/identity/verification.ts
  packages/sdk/contractkit/src/wrappers/Attestations.ts
  yarn.lock
Labels: automerge

#6699 Update eth-recovery docs
  packages/cli/src/commands/account/new.ts
  packages/docs/celo-holder-guide/eth-recovery.md
  packages/docs/command-line-interface/account.md
Labels: automerge

#6716 [Wallet] Add translations for 1.9 release
  packages/mobile/ios/celo/es-419.lproj/InfoPlist.strings
  packages/mobile/locales/es-419/accountScreen10.json
  packages/mobile/locales/es-419/fiatExchangeFlow.json
  packages/mobile/locales/es-419/global.json
  packages/mobile/locales/pt-BR/accountScreen10.json
  packages/mobile/locales/pt-BR/backupKeyFlow6.json
  packages/mobile/locales/pt-BR/fiatExchangeFlow.json
  packages/mobile/locales/pt-BR/global.json
  packages/mobile/locales/pt-BR/onboarding.json
  packages/mobile/locales/pt-BR/paymentRequestFlow.json
  packages/mobile/scripts/verify_locales.sh
  packages/mobile/src/navigator/DrawerNavigator.tsx
Labels: automerge, wallet

#6715 feat(plumo docs): point to 1.1.3
  packages/docs/celo-codebase/protocol/plumo.md
Labels: automerge

#6488 [Wallet] Enable Flipper on iOS along with Redux Debugger and Reactotron
  package.json
  packages/mobile/README.md
  packages/mobile/__mocks__/reactotron-react-native.ts
  packages/mobile/android/gradle.properties
  packages/mobile/index.js
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/mobile/src/index.d.ts
  packages/mobile/src/reactotronConfig.ts
  packages/mobile/src/redux/store.ts
  yarn.lock
Labels: automerge, wallet

#6761 [Wallet] Disable 8 digit codes verification
  packages/mobile/src/flags.ts
Labels: automerge

#6387 [docs] Attestation Service nexmo callback is GET not POST
  packages/docs/validator-guide/attestation-service.md
Labels: CAP, automerge

#6700 Updated contractkit version in blockchain API
  packages/blockchain-api/package.json
  yarn.lock
Labels: automerge

#6781 add python and java sdk links
  packages/docs/developer-resources/overview.md
Labels: automerge, docs

#6784 doc: Add ETH recovery guide
  packages/docs/SUMMARY.md
  packages/docs/celo-holder-guide/celo-recovery.md
Labels: automerge

#6782 Remove redundant text in docs Overview page
  packages/docs/overview.md
Labels: automerge, devX, docs

#6789 doc: Add Attestation Service step to prereq
  packages/docs/validator-guide/celo-foundation-voting-policy.md
Labels: automerge, docs

#6799 [Attestation Service] Tweaks to docs and default configs
  packages/attestation-service/config/.env.development
  packages/docs/validator-guide/attestation-service.md
  packages/terraform-modules-public/aws/testnet/modules/startup-scripts/run-attestation-service.sh
Labels: automerge

#6801 metadata should be hosted at http<s> endpoint
  packages/docs/validator-guide/attestation-service.md
Labels: automerge

#6786 [Wallet] I1skn/fix already verified
  packages/mobile/src/verify/VerificationLoadingScreen.tsx
Labels: automerge

#6806 Metadata HTTPS Monitoring
  packages/cli/src/commands/identity/current-attestation-services.ts
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_attestations_.attestationswrapper.md
  packages/docs/developer-resources/contractkit/reference/enums/_wrappers_attestations_.attestationservicestatusstate.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_attestations_.attestationservicestatusresponse.md
  packages/sdk/contractkit/src/wrappers/Attestations.ts
Labels: automerge

#6439 Add non-ReleaseGold flow to Baklava Validator Guide
  packages/docs/getting-started/running-a-validator-in-baklava.md
Labels: automerge
