Repository celo-org/celo-monorepo, pull requests merged in 2021-05, with the labels that each got.

#7791 Update image tag in node upgrade docs
  packages/docs/validator-guide/node-upgrades.md
Labels: automerge

#7814 Updated Celo DApp Gallery to include Infibridge (Celo camp project)
  packages/docs/developer-resources/celo-dapp-gallery.md
Labels: automerge

#7817 Updated web3 docs link
  packages/docs/developer-resources/walkthroughs/hellocelo.md
Labels: automerge, devX, docs

#7808 Update celo-dapp-gallery.md
  packages/docs/developer-resources/celo-dapp-gallery.md
Labels: automerge

#7812 Update celo-dapp-gallery.md
  packages/docs/developer-resources/celo-dapp-gallery.md
Labels: automerge

#7756 Added cEUR to docs integration checklist
  packages/docs/developer-resources/integrations/checklist.md
Labels: automerge

#7661 Smart contract changes to support EIP-1167 in Komenci
  packages/protocol/contracts/common/InitializableProxy.sol
  packages/protocol/contracts/common/Proxy.sol
  packages/protocol/contracts/common/ProxyCloneFactory.sol
  packages/protocol/lib/meta-tx-utils.ts
  packages/protocol/lib/test-utils.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/package.json
  packages/protocol/test/common/metatransactionwallet.ts
  packages/protocol/test/common/onboarding.ts
  packages/protocol/test/identity/attestations.ts
  yarn.lock
Labels: automerge

#7794 Upgrade oracles & their full nodes
  .env.alfajores
  .env.baklava
  .env.rc1
  packages/celotool/src/lib/helm_deploy.ts
  packages/helm-charts/celo-fullnode/templates/statefulset.yaml
  packages/helm-charts/common/templates/_helpers.tpl
Labels: automerge

#7679 Check core contracts against unsafe opcodes
  .circleci/config.yml
  packages/protocol/package.json
  packages/protocol/scripts/check-opcodes.ts
Labels: automerge

#7841 Use non-headless private nodes service
  packages/celotool/src/lib/blockscout.ts
Labels: automerge

#7842 Fix blockscout default ingress yaml and custom env values
  packages/celotool/src/lib/blockscout.ts
Labels: automerge

#7802 Tutorial: Integrating WalletConnect into your DApp
  packages/docs/developer-resources/walkthroughs/wallet-connect.md
  packages/sdk/wallets/wallet-walletconnect/package.json
  packages/sdk/wallets/wallet-walletconnect/src/constants.ts
  packages/sdk/wallets/wallet-walletconnect/src/wc-wallet.ts
  yarn.lock
Labels: automerge

#7858 Add '--stop-timeout 300' to celo-blockchain docker run options and update recomended stop instructions from 60 to 300
  packages/docs/getting-started/running-a-full-node-in-alfajores.md
  packages/docs/getting-started/running-a-full-node-in-baklava.md
  packages/docs/getting-started/running-a-full-node-in-mainnet.md
  packages/docs/getting-started/running-a-validator-in-baklava.md
  packages/docs/getting-started/running-a-validator-in-mainnet.md
  packages/docs/validator-guide/attestation-service.md
  packages/docs/validator-guide/node-upgrades.md
Labels: automerge

#7363 Implement identity proxies
  packages/protocol/contracts/common/Create2.sol
  packages/protocol/contracts/identity/IdentityProxy.sol
  packages/protocol/contracts/identity/IdentityProxyHub.sol
  packages/protocol/contracts/identity/test/IdentityProxyTest.sol
  packages/protocol/contracts/identity/test/MockAttestations.sol
  packages/protocol/test/identity/identityproxy.ts
  packages/protocol/test/identity/identityproxyhub.ts
Labels: automerge

#7878 Add Poof.cash to the Celo Dapp Gallery
  packages/docs/developer-resources/celo-dapp-gallery.md
Labels: automerge

#7880 Upgrade public GCP Terraform code with various improvements
  .gitignore
  packages/terraform-modules-public/gcp/celo-infra/main.tf
  packages/terraform-modules-public/gcp/celo-infra/modules/attestation-service/main.tf
  packages/terraform-modules-public/gcp/celo-infra/modules/attestation-service/startup.sh
  packages/terraform-modules-public/gcp/celo-infra/modules/attestation-service/variables.tf
  packages/terraform-modules-public/gcp/celo-infra/modules/backup_node/main.tf
  packages/terraform-modules-public/gcp/celo-infra/modules/backup_node/startup.sh
  packages/terraform-modules-public/gcp/celo-infra/modules/proxy/startup.sh
  packages/terraform-modules-public/gcp/celo-infra/modules/proxy/variables.tf
  packages/terraform-modules-public/gcp/celo-infra/modules/tx-node/main.tf
  packages/terraform-modules-public/gcp/celo-infra/modules/tx-node/startup.sh
  packages/terraform-modules-public/gcp/celo-infra/modules/validator/startup.sh
  packages/terraform-modules-public/gcp/celo-infra/variables.tf
  packages/terraform-modules-public/gcp/example/bootstrap.sh
  packages/terraform-modules-public/gcp/example/main.tf
  packages/terraform-modules-public/gcp/example/scripts/regen_gcp_creds.sh
  packages/terraform-modules-public/gcp/example/terraform.tfvars.example
  packages/terraform-modules-public/gcp/example/variables.tf
Labels: automerge

#7888 Increase SKU for Alfajores for prod parity
  .env.alfajores
Labels: automerge

#7892 Only deploy changed libraries
  packages/protocol/scripts/truffle/make-release.ts
Labels: automerge

#7894 Update celo-monorepo to include Umoja
  packages/docs/developer-resources/celo-dapp-gallery.md
Labels: automerge

#7599 Updated mainnet docs to include non-releasegold validator flow
  packages/docs/getting-started/running-a-validator-in-mainnet.md
Labels: automerge

#7904 Upgrade geth docker image to 1.3.2
  .env.alfajores
  .env.baklava
  .env.rc1
Labels: automerge

#5913 CIP10 contracts changes
  .circleci/config.yml
  packages/protocol/contracts/common/Accounts.sol
  packages/protocol/lib/signing-utils.ts
  packages/protocol/migrations/11_accounts.ts
  packages/protocol/scripts/bash/backupmigrations.sh
  packages/protocol/specs/harnesses/AccountsHarness.sol
  packages/protocol/test/common/accounts.ts
  packages/protocol/test/common/onboarding.ts
  packages/protocol/test/governance/network/governance.ts
  packages/protocol/test/governance/network/governance_slasher.ts
  packages/protocol/test/governance/validators/doublesigningslasher.ts
  packages/protocol/test/governance/validators/downtimeslasher.ts
  packages/protocol/test/governance/validators/validators.ts
  packages/protocol/test/governance/voting/election.ts
  packages/protocol/test/governance/voting/lockedgold.ts
  packages/protocol/test/governance/voting/release_gold.ts
  packages/protocol/test/identity/attestations.ts
  packages/sdk/contractkit/src/wrappers/Accounts.ts
  packages/sdk/utils/src/typed-data-constructors.ts
Labels: automerge

#7906 Piersy/vulnerability fixes
  package.json
  yarn.lock
Labels: automerge

#7839 Upgrade alfajores, baklava and forno to 1.3.2
  .env.alfajores
  .env.baklava
  .env.rc1
  packages/celotool/src/lib/helm_deploy.ts
  packages/helm-charts/celo-fullnode/values.yaml
  packages/helm-charts/testnet/templates/bootnode.deployment.yaml
  packages/helm-charts/testnet/templates/txnode.statefulset.yaml
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
Labels: automerge

#7919 Update development-chain.md
  packages/docs/developer-resources/walkthroughs/development-chain.md
Labels: automerge

#7936 Donut: metamask guide added
  packages/docs/SUMMARY.md
  packages/docs/getting-started/using-metamask-with-celo/README.md
  packages/docs/getting-started/using-metamask-with-celo/choosing-the-right-gas-price.md
  packages/docs/getting-started/using-metamask-with-celo/manual-setup.md
  packages/docs/getting-started/using-metamask-with-celo/programmatic-setup.md
  packages/docs/getting-started/using-metamask-with-celo/using-a-ledger-with-metamask.md
Labels: automerge

#7928 Fix truffle console script and add notes to readme
  packages/protocol/README.md
  packages/protocol/scripts/bash/console.sh
Labels: automerge

#7895 chore: remove @umpirsky/country-list package to save space
  packages/sdk/utils/data/countries/es/country.json
  packages/sdk/utils/package.json
  packages/sdk/utils/src/countries.ts
  packages/sdk/utils/src/types.d.ts
Labels: Component: ContractKit, automerge, devX

#7942 Move node12 CI docker image to public registry
  .circleci/config.yml
Labels: automerge

#7951 Add script for running + testing eth_signTypedData
  packages/sdk/wallets/wallet-walletconnect/scripts/run-in-memory-client.ts
Labels: automerge

#7963 update for donut
  packages/docs/developer-resources/celo-for-eth-devs.md
Labels: automerge

#7303 Added prometheus remote_write config
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/prometheus.ts
  packages/celotool/src/lib/service-account-utils.ts
  packages/helm-charts/grafana/templates/ingress.yaml
  packages/helm-charts/prometheus-stackdriver/templates/configmap.yaml
  packages/helm-charts/prometheus-stackdriver/values.yaml
Labels: automerge

#7969 update broken link to celocli docs in README
  README.md
Labels: automerge

#7785 chore: update tutorial with latest use-contractkit changes
  packages/docs/developer-resources/walkthroughs/web-dapp.md
Labels: Component: UseContractKit, automerge, devX, docs

#7864 Added GoodGhosting to Celo DApp Gallery
  packages/docs/developer-resources/celo-dapp-gallery.md
Labels: automerge, devX, docs

#7955 upgrade AS and ODIS dockerfiles to node v12
  dockerfiles/attestation-service/Dockerfile
  dockerfiles/metadata-crawler/Dockerfile
  dockerfiles/phone-number-privacy/Dockerfile
Labels: automerge

#7959 Fix local CLI tests: dynamically import TransportNodeHid
  packages/cli/src/base.ts
Labels: automerge

#7920 Update oracle parameters.
  .env.alfajores
  .env.baklava
  .env.rc1
  packages/helm-charts/oracle/CELOBTC.yaml
  packages/helm-charts/oracle/CELOEUR.yaml
  packages/helm-charts/oracle/CELOUSD.yaml
  packages/helm-charts/oracle/templates/statefulset.yaml
  packages/helm-charts/oracle/values.yaml
Labels: automerge

#8020 fix broken link to mobile directory
  SETUP.md
Labels: devX, docs

#7949 Restored blockscout segment key secret
  .env.mnemonic.alfajores.enc
  .env.mnemonic.rc1.enc
Labels: automerge

#8012 Bump WalletConnect version
  packages/sdk/wallets/wallet-walletconnect/package.json
  packages/sdk/wallets/wallet-walletconnect/src/test/in-memory-wallet.ts
  packages/sdk/wallets/wallet-walletconnect/src/wc-wallet.ts
  yarn.lock
Labels: automerge
