Repository celo-org/celo-monorepo, pull requests merged in 2021-04, with the labels that each got.

#7379 Add more info to network:contracts
  packages/cli/src/commands/network/contracts.ts
  packages/cli/src/utils/command.ts
  packages/docs/command-line-interface/network.md
  packages/protocol/scripts/build.ts
Labels: automerge

#7469 Fix type error in Multisig getTransactionDataByContent
  packages/sdk/contractkit/src/wrappers/MultiSig.ts
Labels: automerge

#7590 Update service configurations to reflect April 1st scale up
  .env.rc1
Labels: automerge

#7591 Update alfajores env file with most recent upgrade info
  .env.alfajores
Labels: automerge

#7600 [Docs] Add Wallets page to Getting Started docs
  packages/docs/SUMMARY.md
  packages/docs/getting-started/wallets.md
Labels: automerge

#7596 ODIS Observability improvements
  packages/phone-number-privacy/monitor/.env
  packages/phone-number-privacy/monitor/src/loadTest.ts
  packages/phone-number-privacy/signer/src/common/metrics.ts
  packages/phone-number-privacy/signer/src/config.ts
  packages/phone-number-privacy/signer/src/database/database.ts
  packages/phone-number-privacy/signer/src/database/wrappers/account.ts
  packages/phone-number-privacy/signer/src/signing/query-quota.ts
  packages/phone-number-privacy/signer/src/web3/contracts.ts
Labels: automerge

#7617 Adds timeout functions to sdk/base package
  packages/docs/developer-resources/base/reference/enums/_account_.mnemoniclanguages.md
  packages/docs/developer-resources/base/reference/interfaces/_account_.bip39.md
  packages/docs/developer-resources/base/reference/modules/_account_.md
  packages/docs/developer-resources/base/reference/modules/_async_.md
  packages/sdk/base/src/async.test.ts
  packages/sdk/base/src/async.ts
Labels: automerge

#7594 ODIS Combiner Reliability
  dependency-graph.json
  packages/phone-number-privacy/combiner/package.json
  packages/phone-number-privacy/combiner/src/database/wrappers/account.ts
  packages/phone-number-privacy/combiner/src/database/wrappers/number-pairs.ts
  packages/phone-number-privacy/combiner/src/signing/get-threshold-signature.ts
  packages/phone-number-privacy/common/package.json
  packages/phone-number-privacy/common/src/interfaces/error-utils.ts
  packages/phone-number-privacy/common/src/utils/authentication.ts
  packages/phone-number-privacy/common/src/utils/constants.ts
  yarn.lock
Labels: automerge

#7598 ODIS sessionID
  dependency-graph.json
  packages/docs/developer-resources/base/reference/enums/_account_.mnemoniclanguages.md
  packages/docs/developer-resources/base/reference/interfaces/_account_.bip39.md
  packages/docs/developer-resources/base/reference/modules/_account_.md
  packages/docs/developer-resources/base/reference/modules/_async_.md
  packages/phone-number-privacy/combiner/package.json
  packages/phone-number-privacy/combiner/src/database/wrappers/account.ts
  packages/phone-number-privacy/combiner/src/database/wrappers/number-pairs.ts
  packages/phone-number-privacy/combiner/src/index.ts
  packages/phone-number-privacy/combiner/src/signing/get-threshold-signature.ts
  packages/phone-number-privacy/common/package.json
  packages/phone-number-privacy/common/src/index.ts
  packages/phone-number-privacy/common/src/interfaces/error-utils.ts
  packages/phone-number-privacy/common/src/utils/authentication.ts
  packages/phone-number-privacy/common/src/utils/constants.ts
  packages/phone-number-privacy/common/src/utils/logger.ts
  packages/phone-number-privacy/monitor/package.json
  packages/phone-number-privacy/signer/package.json
  packages/phone-number-privacy/signer/src/common/metrics.ts
  packages/phone-number-privacy/signer/src/signing/get-partial-signature.ts
  packages/phone-number-privacy/signer/src/signing/query-quota.ts
  packages/sdk/base/src/async.test.ts
  packages/sdk/base/src/async.ts
  yarn.lock
Labels: automerge

#7602 ODIS load test
  packages/phone-number-privacy/monitor/package.json
  packages/phone-number-privacy/monitor/src/index.ts
  packages/phone-number-privacy/monitor/src/query.ts
  packages/phone-number-privacy/monitor/src/scripts/runLoadTest.ts
  packages/phone-number-privacy/monitor/src/test.ts
Labels: automerge

#7576 Celotool `geth start` fix
  packages/celotool/src/cmds/geth/start.ts
Labels: automerge

#7583 Clarify usage of DappKit vs useContractKit
  packages/docs/developer-resources/overview.md
Labels: automerge, devX, docs

#7585 Add info box to explain deeplinks in different nets
  packages/docs/developer-resources/dappkit/usage.md
Labels: automerge, devX, docs

#7288 Adjust dequeued expired proposal check
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/governance/test/GovernanceTest.sol
  packages/protocol/test/governance/network/governance.ts
Labels: automerge

#7632 ODIS mainnet eastasia config change
  .env.rc1
Labels: automerge

#7642 Ensure all node modules cached by CI
  .circleci/config.yml
Labels: automerge

#7646 CELOEUR mainnet oracles
  .env.rc1
  packages/celotool/src/lib/env-utils.ts
Labels: automerge

#7637 test: updating input validation tests
  packages/phone-number-privacy/combiner/package.json
  packages/phone-number-privacy/combiner/src/match-making/get-contact-matches.ts
  packages/phone-number-privacy/combiner/test/index.test.ts
  packages/phone-number-privacy/common/package.json
  packages/phone-number-privacy/common/src/utils/constants.ts
  packages/phone-number-privacy/common/src/utils/input-validation.ts
  packages/phone-number-privacy/signer/package.json
  packages/phone-number-privacy/signer/src/signing/get-partial-signature.ts
  packages/phone-number-privacy/signer/src/signing/query-quota.ts
  yarn.lock
Labels: automerge

#7652 Update dappkit setup
  packages/docs/developer-resources/dappkit/setup.md
Labels: Component: Dappkit, automerge, docs

#7452 Upgrade eksportisto suffix 11
  .env.rc1
  packages/helm-charts/eksportisto/templates/_helpers.tpl
  packages/helm-charts/eksportisto/templates/statefulset.yaml
Labels: automerge

#7645 WalletConnect improvements
  packages/sdk/wallets/wallet-walletconnect/package.json
  packages/sdk/wallets/wallet-walletconnect/scripts/run-in-memory-client.ts
  packages/sdk/wallets/wallet-walletconnect/src/constants.ts
  packages/sdk/wallets/wallet-walletconnect/src/index.ts
  packages/sdk/wallets/wallet-walletconnect/src/test/in-memory-wallet.ts
  packages/sdk/wallets/wallet-walletconnect/src/types.ts
  packages/sdk/wallets/wallet-walletconnect/src/wc-signer.test.ts
  packages/sdk/wallets/wallet-walletconnect/src/wc-wallet.ts
  yarn.lock
Labels: automerge

#7658 Fixes bug with >iOS 13 opening app store link
  packages/sdk/dappkit/src/index.ts
Labels: automerge

#7575 Update celotooljs faucet for cEUR + future stables
  packages/celotool/src/cmds/account/faucet-multiple-helper.ts
  packages/celotool/src/cmds/account/faucet-multiple.ts
  packages/celotool/src/cmds/account/faucet.ts
Labels: automerge

#7655 Prevent dangling async calls
  packages/phone-number-privacy/combiner/src/signing/get-threshold-signature.ts
  packages/phone-number-privacy/signer/test/signing/query-quota.test.ts
Labels: automerge

#7676 CLI Bug Fix: invalid gas option
  packages/cli/src/utils/config.ts
Labels: Component: CLI, automerge, bug, devX

#7671 Unify approve and approvehotfix to support multisigs
  packages/cli/src/commands/governance/approve.ts
  packages/cli/src/commands/governance/approvehotfix.ts
  packages/cli/src/utils/checks.ts
Labels: automerge

#7684 Bump web3 from 1.3.4 to 1.3.5
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/dev-utils/package.json
  packages/env-tests/package.json
  packages/faucet/package.json
  packages/metadata-crawler/package.json
  packages/protocol/package.json
  yarn.lock
Labels: automerge

#7626 update old discord links
  packages/docs/README.md
  packages/docs/community/grant-playbook.md
  packages/docs/community/release-process/base-cli-contractkit-dappkit-utils.md
  packages/docs/developer-resources/develop-on-windows.md
  packages/docs/developer-resources/walkthroughs/hello-mobile-dapp.md
  packages/docs/developer-resources/walkthroughs/web-dapp.md
Labels: automerge

#7707 Integration with Sourcify
  .env.alfajores
  .env.baklava
  .env.rc1
  packages/celotool/src/lib/blockscout.ts
  packages/helm-charts/blockscout/templates/blockscout-api.deployment.yaml
  packages/helm-charts/blockscout/templates/blockscout-web.deployment.yaml
  packages/helm-charts/blockscout/values-alfajores.yaml
  packages/helm-charts/blockscout/values-baklava.yaml
  packages/helm-charts/blockscout/values-rc1.yaml
Labels: automerge

#7715 Temporary fix for docker:celotool build error
  packages/celotool/src/e2e-tests/cip35_tests.ts
Labels: automerge, celotool

#7669 Add --globalHelp option to BaseCommand
  packages/cli/src/base.ts
  packages/docs/command-line-interface/account.md
  packages/docs/command-line-interface/config.md
  packages/docs/command-line-interface/dkg.md
  packages/docs/command-line-interface/election.md
  packages/docs/command-line-interface/exchange.md
  packages/docs/command-line-interface/governance.md
  packages/docs/command-line-interface/identity.md
  packages/docs/command-line-interface/lockedgold.md
  packages/docs/command-line-interface/multisig.md
  packages/docs/command-line-interface/network.md
  packages/docs/command-line-interface/node.md
  packages/docs/command-line-interface/oracle.md
  packages/docs/command-line-interface/releasegold.md
  packages/docs/command-line-interface/reserve.md
  packages/docs/command-line-interface/rewards.md
  packages/docs/command-line-interface/transfer.md
  packages/docs/command-line-interface/validator.md
  packages/docs/command-line-interface/validatorgroup.md
Labels: automerge

#7326 fix Governance.getProposalStage
  packages/sdk/contractkit/src/wrappers/Governance.ts
Labels: automerge

#7421 Add initial doc for MTW
  packages/cli/src/commands/identity/get-attestations.ts
  packages/docs/celo-codebase/protocol/identity/valora-accounts.md
  packages/docs/celo-codebase/protocol/transactions/tx-comment-encyption.md
Labels: automerge

#7728 celotool: fix typescript error in cip35_tests.ts
  packages/celotool/package.json
  packages/celotool/src/e2e-tests/cip35_tests.ts
Labels: automerge

#7731 Optics documentation
  packages/docs/SUMMARY.md
  packages/docs/celo-codebase/protocol/README.md
  packages/docs/celo-codebase/protocol/optics.md
Labels: automerge, docs

#7693 doc: Close Cohort 7 application form
  packages/docs/validator-guide/celo-foundation-voting-policy.md
Labels: automerge, docs

#7738 SDK -> 1.2.1-dev, CLI -> 1.2.1-dev
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/CHANGELOG.md
  packages/cli/package.json
  packages/env-tests/package.json
  packages/metadata-crawler/package.json
  packages/protocol/package.json
  packages/sdk/CHANGELOG.md
  packages/sdk/base/package.json
  packages/sdk/connect/package.json
  packages/sdk/contractkit/package.json
  packages/sdk/dappkit/package.json
  packages/sdk/explorer/package.json
  packages/sdk/governance/package.json
  packages/sdk/identity/package.json
  packages/sdk/network-utils/package.json
  packages/sdk/transactions-uri/package.json
  packages/sdk/utils/package.json
  packages/sdk/wallets/wallet-base/package.json
  packages/sdk/wallets/wallet-hsm-aws/package.json
  packages/sdk/wallets/wallet-hsm-azure/package.json
  packages/sdk/wallets/wallet-hsm/package.json
  packages/sdk/wallets/wallet-ledger/package.json
  packages/sdk/wallets/wallet-local/package.json
  packages/sdk/wallets/wallet-remote/package.json
  packages/sdk/wallets/wallet-rpc/package.json
  packages/sdk/wallets/wallet-walletconnect/package.json
Labels: automerge

#7612 Improve validator signer authorization examples
  packages/cli/src/commands/releasegold/authorize.ts
  packages/docs/command-line-interface/releasegold.md
  packages/docs/getting-started/running-a-validator-in-baklava.md
  packages/docs/getting-started/running-a-validator-in-mainnet.md
Labels: automerge

#7748 Fix loss of precision releasegold:withdraw CLI command
  packages/cli/src/commands/releasegold/withdraw.test.ts
  packages/cli/src/commands/releasegold/withdraw.ts
Labels: automerge

#7749 AS base docker image
  dockerfiles/attestation-service/Dockerfile
Labels: automerge

#7763 Update docs
  packages/docs/validator-guide/node-upgrades.md
Labels: automerge

#7727 Reflect general asset management
  packages/docs/celo-holder-guide/cusd.md
Labels: automerge

#7506 Updated docs on how to add a new stable asset on the protocol level
  packages/docs/SUMMARY.md
  packages/docs/celo-codebase/protocol/stability/adding_stable_assets.md
  packages/docs/celo-codebase/protocol/stability/doto.md
Labels: automerge

#7657 Oracle gas price multiplier of 6
  .env.baklava
  .env.rc1
  packages/helm-charts/oracle/templates/statefulset.yaml
  packages/helm-charts/oracle/values.yaml
Labels: automerge

#7754 Added docs for cEUR listing
  packages/docs/developer-resources/integrations/listings.md
Labels: automerge

#7659 Upgrade oracle fullnodes
  .env.alfajores
  .env.baklava
  .env.rc1
  packages/celotool/src/lib/k8s-fullnode/aks.ts
Labels: automerge

#7767 Update gitcoin-bounty-issue.md
  .github/ISSUE_TEMPLATE/gitcoin-bounty-issue.md
Labels: automerge

#7799 Updated the max body size limit for Blockscout ingress
  packages/celotool/src/lib/blockscout.ts
  packages/helm-charts/blockscout/templates/blockscout-web.ingress.yaml
Labels: automerge

#7809 Added Cent mobile wallet and Symmetric
  packages/docs/developer-resources/celo-dapp-gallery.md
Labels: automerge

#7615 ODIS scalability Improvements
  .env.alfajores
  dependency-graph.json
  packages/phone-number-privacy/combiner/package.json
  packages/phone-number-privacy/combiner/src/database/models/account.ts
  packages/phone-number-privacy/combiner/src/database/wrappers/number-pairs.ts
  packages/phone-number-privacy/combiner/src/index.ts
  packages/phone-number-privacy/combiner/src/match-making/get-contact-matches.ts
  packages/phone-number-privacy/combiner/src/signing/get-threshold-signature.ts
  packages/phone-number-privacy/combiner/test/end-to-end/get-blinded-sig.test.ts
  packages/phone-number-privacy/common/src/interfaces/error-utils.ts
  packages/phone-number-privacy/common/src/utils/input-validation.ts
  packages/phone-number-privacy/common/src/utils/logger.ts
  packages/phone-number-privacy/monitor/package.json
  packages/phone-number-privacy/monitor/src/index.ts
  packages/phone-number-privacy/monitor/src/query.ts
  packages/phone-number-privacy/signer/package.json
  packages/phone-number-privacy/signer/src/bls/bls-cryptography-client.ts
  packages/phone-number-privacy/signer/src/common/metrics.ts
  packages/phone-number-privacy/signer/src/config.ts
  packages/phone-number-privacy/signer/src/database/models/account.ts
  packages/phone-number-privacy/signer/src/database/wrappers/account.ts
  packages/phone-number-privacy/signer/src/database/wrappers/request.ts
  packages/phone-number-privacy/signer/src/index.ts
  packages/phone-number-privacy/signer/src/server.ts
  packages/phone-number-privacy/signer/src/signing/get-partial-signature.ts
  packages/phone-number-privacy/signer/src/signing/query-quota.ts
  packages/phone-number-privacy/signer/src/web3/contracts.ts
  packages/phone-number-privacy/signer/test/end-to-end/get-blinded-sig.test.ts
  packages/phone-number-privacy/signer/test/index.test.ts
  packages/phone-number-privacy/signer/test/signing/query-quota.test.ts
  yarn.lock
Labels: automerge

#7807 Release 4 post audit fixes
  packages/protocol/scripts/bash/release-lib.sh
  packages/protocol/scripts/build.ts
Labels: automerge
