Repository celo-org/celo-monorepo, pull requests merged in 2021-02, with the labels that each got.

#6796 Always send push notifications on transfers
  packages/notification-service/config/config.local.env
  packages/notification-service/package.json
  packages/notification-service/src/blockscout/transfers.ts
  packages/notification-service/src/firebase.ts
  packages/notification-service/test/transfers.test.ts
Labels: automerge, consumer incentives, wallet

#6010 Determine signing algorithm based on key type for Azure HSM
  packages/sdk/wallets/wallet-hsm-azure/src/azure-hsm-wallet.ts
  packages/sdk/wallets/wallet-hsm-azure/src/azure-key-vault-client.ts
Labels: automerge

#6819 [Wallet] Disable keyboard suggestion when entering the account key
  packages/mobile/locales/en-US/onboarding.json
  packages/mobile/locales/es-419/onboarding.json
  packages/mobile/locales/pt-BR/onboarding.json
  packages/mobile/src/components/CodeInput.test.tsx
  packages/mobile/src/components/CodeInput.tsx
  packages/mobile/src/components/__snapshots__/CodeInput.test.tsx.snap
  packages/mobile/src/import/ImportWallet.tsx
  packages/mobile/src/import/__snapshots__/ImportWallet.test.tsx.snap
  packages/mobile/src/verify/__snapshots__/VerificationInputScreen.test.tsx.snap
  packages/react-components/components/TextInput.tsx
Labels: automerge, wallet

#6829 Fix Azure HSM Wallet PublicKey to Address conversion
  packages/sdk/utils/src/address.ts
  packages/sdk/wallets/wallet-hsm-azure/src/azure-hsm-wallet.test.ts
Labels: automerge, devX

#6850 Fix verifying the previous release on a network
  packages/protocol/lib/registry-utils.ts
  packages/protocol/scripts/bash/verify-deployed.sh
Labels: automerge

#6857 Fix wallet url to play store in getting started doc.
  packages/docs/getting-started/using-the-wallet.md
Labels: automerge, devX, docs

#6451 added the sentence on initial reserve target
  packages/reserve-site/src/content/home/initial-target.md
Labels: automerge

#6835 [Wallet] Allow updating daily limit from backend
  packages/mobile/src/account/actions.ts
  packages/mobile/src/account/reducer.test.ts
  packages/mobile/src/account/reducer.ts
  packages/mobile/src/account/saga.ts
  packages/mobile/src/account/selectors.ts
  packages/mobile/src/config.ts
  packages/mobile/src/firebase/db-rules.json
  packages/mobile/src/firebase/firebase.ts
  packages/mobile/src/send/SendAmount.tsx
  packages/mobile/src/send/utils.test.ts
  packages/mobile/src/send/utils.ts
  packages/mobile/test/schemas.ts
Labels: automerge, wallet

#6853 [Wallet] Fix Bidali view not loading when phone number is not specified
  packages/mobile/src/fiatExchanges/BidaliScreen.test.tsx
  packages/mobile/src/fiatExchanges/BidaliScreen.tsx
Labels: automerge, wallet

#6889 SDK->1.0.3-dev
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/env-tests/package.json
  packages/komencikit/package.json
  packages/metadata-crawler/package.json
  packages/mobile/package.json
  packages/protocol/package.json
  packages/react-components/package.json
  packages/sdk/CHANGELOG.md
  packages/sdk/base/package.json
  packages/sdk/connect/package.json
  packages/sdk/contractkit/package.json
  packages/sdk/dappkit/package.json
  packages/sdk/explorer/package.json
  packages/sdk/governance/package.json
  packages/sdk/identity/package.json
  packages/sdk/network-utils/package.json
  packages/sdk/transactions-uri/package.json
  packages/sdk/utils/package.json
  packages/sdk/wallets/wallet-base/package.json
  packages/sdk/wallets/wallet-hsm-aws/package.json
  packages/sdk/wallets/wallet-hsm-azure/package.json
  packages/sdk/wallets/wallet-hsm/package.json
  packages/sdk/wallets/wallet-ledger/package.json
  packages/sdk/wallets/wallet-local/package.json
  packages/sdk/wallets/wallet-remote/package.json
  packages/sdk/wallets/wallet-rpc/package.json
Labels: automerge, devX

#6891 [Wallet] Valora 1.9 version change
  packages/mobile/android/app/build.gradle
  packages/mobile/android/gradle.properties
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/package.json
Labels: automerge, wallet

#6665 Add headless service for private tx nodes
  .env
  .env.alfajores
  .env.alfajoresstaging
  .env.baklava
  .env.baklavastaging
  .env.integration
  .env.oracledev
  .env.pilot
  .env.pilotstaging
  .env.rc0
  .env.rc1
  .env.staging
  packages/celotool/src/lib/blockscout.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/helm-charts/testnet/templates/_helpers.tpl
Labels: automerge

#6892 Update mobile package reviewers
  .github/CODEOWNERS
Labels: wallet

#6848 [Wallet] Redesign Consumer Incentives screen
  packages/mobile/branding/celo/src/images/consumerIncentives.png
  packages/mobile/branding/celo/src/images/leaves.png
  packages/mobile/ios/Podfile.lock
  packages/mobile/ios/celo.xcodeproj/project.pbxproj
  packages/mobile/locales/en-US/consumerIncentives.json
  packages/mobile/locales/en-US/fiatExchangeFlow.json
  packages/mobile/locales/en-US/index.ts
  packages/mobile/locales/es-419/consumerIncentives.json
  packages/mobile/locales/es-419/fiatExchangeFlow.json
  packages/mobile/locales/es-419/index.ts
  packages/mobile/locales/pt-BR/consumerIncentives.json
  packages/mobile/locales/pt-BR/fiatExchangeFlow.json
  packages/mobile/locales/pt-BR/index.ts
  packages/mobile/package.json
  packages/mobile/scripts/sync_branding.sh
  packages/mobile/src/consumerIncentives/ConsumerIncentivesHomeScreen.test.tsx
  packages/mobile/src/consumerIncentives/ConsumerIncentivesHomeScreen.tsx
  packages/mobile/src/consumerIncentives/__snapshots__/ConsumerIncentivesHomeScreen.test.tsx.snap
  packages/mobile/src/consumerIncentives/contentFetcher.ts
  packages/mobile/src/i18n.ts
  packages/mobile/src/images/Images.ts
  yarn.lock
Labels: automerge, wallet

#6899 Verify-release from release tag
  packages/protocol/scripts/bash/verify-release.sh
Labels: automerge

#6420 [docs] updates instructions on building wallet
  packages/mobile/README.md
Labels: automerge, wallet

#6927 Fix deploy:update-disclaimer command
  packages/mobile/package.json
Labels: automerge, wallet

#6898 Simplify SortedOracles API by allowing consumers to report to arbitrary Addresses
  packages/sdk/contractkit/src/wrappers/SortedOracles.test.ts
  packages/sdk/contractkit/src/wrappers/SortedOracles.ts
Labels: automerge, cEUR, economics, sdk

#5973 Add plugins to CLI
  packages/cli/README.md
  packages/cli/package.json
  packages/cli/src/hooks/prerun/plugin-warning.ts
  packages/docs/command-line-interface/introduction.md
  packages/docs/command-line-interface/plugins.md
  yarn.lock
Labels: automerge

#6957 import `toTxResult` from @celo/connect
  packages/docs/developer-resources/dappkit/usage.md
  packages/sdk/dappkit/README.md
Labels: Component: Dappkit, automerge, devX, docs

#6973 Added blockscout environment variable segment_key
  .env.mnemonic.alfajores.enc
  .env.mnemonic.baklava.enc
  .env.mnemonic.rc1.enc
  packages/celotool/src/lib/blockscout.ts
  packages/celotool/src/lib/env-utils.ts
  packages/helm-charts/blockscout/templates/_helpers.tpl
Labels: blockscout

#6972 initialize and transfer ownership of RG implementation contracts on deploy
  .circleci/config.yml
  packages/dev-utils/src/ganache-test.ts
  packages/protocol/lib/proxy-utils.ts
  packages/protocol/lib/recover-funds.ts
  packages/protocol/lib/web3-utils.ts
  packages/protocol/scripts/truffle/deploy_multisig.ts
  packages/protocol/scripts/truffle/deploy_release_contracts.ts
Labels: automerge

#6788 Celotool --helmdryrun cmd line option
  .env
  .env.alfajores
  .env.alfajoresstaging
  .env.baklava
  .env.baklavastaging
  .env.integration
  .env.oracledev
  .env.pilot
  .env.pilotstaging
  .env.rc0
  .env.rc1
  .env.staging
  packages/celotool/package.json
  packages/celotool/src/cli.ts
  packages/celotool/src/cmds/deploy/initial/testnet.ts
  packages/celotool/src/cmds/deploy/upgrade/testnet.ts
  packages/celotool/src/lib/cmd-utils.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/helm-charts/load-test/charts/common-0.0.1.tgz
  packages/terraform-modules-public/gcp/example/variables.tf
  yarn.lock
Labels: blockchain

#6831 Baklava migration from VMs to Kubernetes
  .env
  .env.alfajores
  .env.alfajoresstaging
  .env.baklava
  .env.baklavastaging
  .env.integration
  .env.mnemonic.alfajoresstaging.enc
  .env.mnemonic.baklava.enc
  .env.mnemonic.baklavastaging.enc
  .env.mnemonic.integration.enc
  .env.mnemonic.pilot.enc
  .env.mnemonic.pilotstaging.enc
  .env.mnemonic.rc0.enc
  .env.mnemonic.staging.enc
  .env.oracledev
  .env.pilot
  .env.pilotstaging
  .env.rc0
  .env.rc1
  .env.staging
  packages/blockchain-api/src/secrets.json.enc
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/geth.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/celotool/src/lib/k8s-fullnode/base.ts
  packages/celotool/src/lib/testnet-utils.ts
  packages/celotool/src/lib/vm-testnet-utils.ts
  packages/helm-charts/.gitignore
  packages/helm-charts/attestation-service/requirements.lock
  packages/helm-charts/celo-fullnode/Chart.yaml
  packages/helm-charts/celo-fullnode/requirements.lock
  packages/helm-charts/cert-manager-cluster-issuers/requirements.lock
  packages/helm-charts/common/Chart.yaml
  packages/helm-charts/common/templates/_helpers.tpl
  packages/helm-charts/komenci/requirements.lock
  packages/helm-charts/oracle/requirements.lock
  packages/helm-charts/testnet/Chart.yaml
  packages/helm-charts/testnet/requirements.lock
  packages/helm-charts/testnet/ssdstorageclass.yaml
  packages/helm-charts/testnet/templates/_helpers.tpl
  packages/helm-charts/testnet/templates/bootnode.deployment.yaml
  packages/helm-charts/testnet/templates/geth-account.secret.yaml
  packages/helm-charts/testnet/templates/secondaries.statefulset.yaml
  packages/helm-charts/testnet/templates/txnode-private.statefulset.yaml
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
  packages/terraform-modules/testnet/main.tf
  packages/terraform-modules/testnet/variables.tf
  scripts/key_placer.sh
Labels: blockchain

#6994 [Wallet] Use esm version of date-fns
  packages/mobile/src/set-clock/SetClock.tsx
Labels: automerge, wallet

#6870 Updates Celo project status
  packages/docs/README.md
Labels: automerge, devX, docs

#6869 Update ERC20 wording
  packages/docs/overview.md
Labels: automerge, devX, docs

#6929 Send push notifications for native CELO transfers
  packages/notification-service/src/blockscout/blockscout.d.ts
  packages/notification-service/src/blockscout/nativeTransfersFormatter.ts
  packages/notification-service/src/blockscout/transfers.ts
  packages/notification-service/test/nativeTransfersFormatter.test.ts
  packages/notification-service/test/transfers.test.ts
Labels: automerge, wallet

#7004 [Wallet] Add app language on start analytics event
  packages/mobile/src/analytics/Properties.tsx
  packages/mobile/src/app/App.tsx
Labels: automerge, wallet

#6886 Send custom notification title for CELO rewards
  packages/notification-service/locales/en.json
  packages/notification-service/locales/es.json
  packages/notification-service/locales/pt.json
  packages/notification-service/src/blockscout/transfers.ts
  packages/notification-service/src/firebase.ts
  packages/notification-service/test/firebase.test.ts
  packages/notification-service/test/transfers.test.ts
Labels: automerge, consumer incentives, wallet

#6982 Clarify Docs for `multisig:transfer` in celocli
  packages/cli/src/commands/multisig/transfer.ts
  packages/docs/command-line-interface/multisig.md
Labels: automerge

#6494 Update docs: troubleshooting with running postinstall
  packages/mobile/README.md
Labels: automerge, wallet

#6951 [Wallet] Addresses UI issue when user enters send amount larger than 100,000
  packages/mobile/src/send/SendAmount.tsx
Labels: automerge, wallet

#6942 Add script to wallet repo to send native CELO transactions
  packages/mobile/scripts/sendNativeTx.js
Labels: automerge, wallet

#7029 Increase block wait time to 600 on notification-service
  packages/notification-service/src/blockscout/transfers.ts
Labels: automerge

#6470 [docs] Updates docs to use contractkit 1.0.0
  packages/docs/developer-resources/walkthroughs/hello-contract-remote-node.md
Labels: Priority: P2, automerge, devX, docs

#7024 nit: specify inflationFactorUpdatePeriod is in seconds on StableToken.sol
  packages/protocol/contracts/stability/StableToken.sol
Labels: automerge

#7027 [Wallet] Enable multidex
  packages/mobile/android/app/build.gradle
Labels: automerge, wallet

#6920 Ramp integration on Valora
  packages/mobile/src/config.ts
  packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
  packages/mobile/src/fiatExchanges/MoonPay.test.tsx
  packages/mobile/src/fiatExchanges/MoonPayScreen.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.test.tsx
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/fiatExchanges/RampScreen.tsx
  packages/mobile/src/fiatExchanges/__snapshots__/ProviderOptionsScreen.test.tsx.snap
  packages/mobile/src/fiatExchanges/utils.tsx
  packages/mobile/src/geth/networkConfig.ts
  packages/mobile/src/navigator/Navigator.tsx
  packages/mobile/src/navigator/Screens.tsx
  packages/mobile/src/navigator/types.tsx
Labels: automerge, wallet

#7073 Shouldn't import from src folder in peer package
  packages/sdk/contractkit/src/wrappers/SortedOracles.ts
Labels: automerge

#6986 Design updates on Valora
  packages/mobile/src/components/AccountNumber.tsx
  packages/mobile/src/components/ClipboardAwarePasteIcon.tsx
  packages/mobile/src/send/__snapshots__/ValidateRecipientAccount.test.tsx.snap
Labels: automerge, wallet

#7087 Disable Ramp CICO for US users
  packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
  packages/mobile/src/flags.ts
  packages/mobile/src/utils/countryFeatures.test.ts
Labels: automerge, wallet

#7092 celocli releasegold:show should succeed w/o account registration
  packages/cli/src/commands/releasegold/show.ts
Labels: automerge

#7074 Update the condition for detect non-proxied validators
  packages/helm-charts/testnet/templates/validators.service.yaml
Labels: automerge

#7098 Add check for signer or registered account
  packages/cli/src/commands/account/show.ts
  packages/cli/src/utils/checks.ts
Labels: automerge

#7094 Fix wallets-test
  packages/sdk/wallets/wallet-hsm-aws/package.json
Labels: automerge

#6472 Validator DevOps best practices
  packages/docs/SUMMARY.md
  packages/docs/validator-guide/devops-best-practices.md
Labels: automerge

#7099 Bump resource_class for general-test from M->L
  .circleci/config.yml
Labels: automerge

#7112 Bump StableToken transfer gas cost
  packages/celotool/src/e2e-tests/transfer_tests.ts
Labels: automerge

#6998 Throw error when handling unknown transaction types
  packages/blockchain-api/src/blockscout.ts
  packages/blockchain-api/src/events/Any.ts
  packages/blockchain-api/src/transaction/TransactionAggregator.ts
Labels: automerge

#6955 Add recommended unsupported SMS regions to AS docs
  packages/docs/validator-guide/attestation-service.md
Labels: automerge

#6933 Update Release data for CR3
  packages/protocol/releaseData/initializationData/release3.json
Labels: automerge

#7049 [N03] Inconsistent style
  packages/protocol/contracts/stability/Reserve.sol
Labels: automerge

#6989 [N01] Lack of input validation
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/test/stability/reserve.ts
Labels: automerge

#6988 [N02] Function behaves as modifier
  packages/protocol/contracts/stability/Reserve.sol
Labels: automerge

#6987 [L01] Grace period is hardcoded
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/migrations/13_validators.ts
  packages/protocol/migrationsConfig.js
  packages/protocol/test/governance/validators/validators.ts
  packages/sdk/contractkit/src/wrappers/Validators.ts
Labels: automerge

#5974 CeloCLI query attestations
  packages/cli/src/commands/identity/get-attestations.test.ts
  packages/cli/src/commands/identity/get-attestations.ts
  packages/docs/command-line-interface/identity.md
Labels: automerge

#7120 Add README.me for env-tests
  packages/env-tests/README.md
Labels: automerge

#7162 Spelling error
  packages/docs/developer-resources/walkthroughs/hellocelo.md
Labels: automerge, devX, docs

#7160 fix tiny typo
  packages/docs/getting-started/running-a-full-node-in-mainnet.md
Labels: automerge, devX, docs

#7156 CLI --> 1.1.1-dev
  packages/cli/CHANGELOG.md
  packages/cli/npm-shrinkwrap.json
  packages/cli/package.json
  packages/docs/developer-resources/base/reference/README.md
  packages/docs/developer-resources/connect/reference/README.md
  packages/docs/developer-resources/contractkit/reference/classes/_wrappers_sortedoracles_.sortedoracleswrapper.md
  packages/docs/developer-resources/contractkit/reference/enums/_wrappers_sortedoracles_.medianrelation.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_sortedoracles_.medianrate.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_sortedoracles_.oraclerate.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_sortedoracles_.oraclereport.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_sortedoracles_.oracletimestamp.md
  packages/docs/developer-resources/contractkit/reference/interfaces/_wrappers_sortedoracles_.sortedoraclesconfig.md
  packages/docs/developer-resources/contractkit/reference/modules/_wrappers_sortedoracles_.md
  packages/docs/developer-resources/explorer/reference/README.md
  packages/docs/developer-resources/governance/reference/README.md
  packages/docs/developer-resources/identity/reference/README.md
  packages/docs/developer-resources/network-utils/reference/README.md
  packages/docs/developer-resources/transactions-uri/reference/README.md
  packages/docs/developer-resources/utils/reference/README.md
  packages/docs/developer-resources/wallet-base/reference/README.md
  packages/docs/developer-resources/wallet-hsm-aws/reference/README.md
  packages/docs/developer-resources/wallet-hsm-azure/reference/README.md
  packages/docs/developer-resources/wallet-hsm-azure/reference/classes/_azure_hsm_wallet_.azurehsmwallet.md
  packages/docs/developer-resources/wallet-hsm-azure/reference/classes/_azure_key_vault_client_.azurekeyvaultclient.md
  packages/docs/developer-resources/wallet-hsm/reference/README.md
  packages/docs/developer-resources/wallet-ledger/reference/README.md
  packages/docs/developer-resources/wallet-local/reference/README.md
  packages/docs/developer-resources/wallet-remote/reference/README.md
  packages/docs/developer-resources/wallet-rpc/reference/README.md
  packages/sdk/CHANGELOG.md
Labels: automerge, devX

#7064 Move CeloReserve.org out of monorepo
  .circleci/config.yml
  .github/CODEOWNERS
  .gitignore
  codecov.yml
  dependency-graph.json
  packages/reserve-site/.env.local.enc
  packages/reserve-site/.gcloudignore
  packages/reserve-site/README.md
  packages/reserve-site/RELEASE.MD
  packages/reserve-site/dispatch.yaml
  packages/reserve-site/next-env.d.ts
  packages/reserve-site/next.config.js
  packages/reserve-site/package.json
  packages/reserve-site/production.yaml
  packages/reserve-site/public/assets/CELO.png
  packages/reserve-site/public/assets/CUSD.png
  packages/reserve-site/public/assets/NCCExecutiveSummary.pdf
  packages/reserve-site/public/assets/open-graph.png
  packages/reserve-site/public/assets/stability-mech-illo.svg
  packages/reserve-site/public/assets/unique.png
  packages/reserve-site/public/assets/world-spin.gif
  packages/reserve-site/public/favicon.ico
  packages/reserve-site/src/components/Amount.tsx
  packages/reserve-site/src/components/Button.tsx
  packages/reserve-site/src/components/ChangeStory.tsx
  packages/reserve-site/src/components/Chevron.tsx
  packages/reserve-site/src/components/CopyIcon.tsx
  packages/reserve-site/src/components/Footer.tsx
  packages/reserve-site/src/components/Head.tsx
  packages/reserve-site/src/components/Heading.tsx
  packages/reserve-site/src/components/Holdings.tsx
  packages/reserve-site/src/components/Markdown.tsx
  packages/reserve-site/src/components/Navbar.tsx
  packages/reserve-site/src/components/ReserveAddresses.tsx
  packages/reserve-site/src/components/Section.tsx
  packages/reserve-site/src/components/TargetGraph.tsx
  packages/reserve-site/src/components/Updated.tsx
  packages/reserve-site/src/components/colors.ts
  packages/reserve-site/src/components/styles.tsx
  packages/reserve-site/src/content/home/about.md
  packages/reserve-site/src/content/home/attestations.md
  packages/reserve-site/src/content/home/initial-target.md
  packages/reserve-site/src/content/home/intro.md
  packages/reserve-site/src/content/legal/privacy.md
  packages/reserve-site/src/content/legal/terms.md
  packages/reserve-site/src/content/meta-description.md
  packages/reserve-site/src/interfaces.d.ts
  packages/reserve-site/src/next-env.d.ts
  packages/reserve-site/src/pages/404.tsx
  packages/reserve-site/src/pages/_app.tsx
  packages/reserve-site/src/pages/index.tsx
  packages/reserve-site/src/pages/legal/[doc].tsx
  packages/reserve-site/src/service/Data.ts
  packages/reserve-site/src/service/addresses.ts
  packages/reserve-site/src/service/airtable.ts
  packages/reserve-site/src/service/holdings.ts
  packages/reserve-site/stage.yaml
  packages/reserve-site/tsconfig.json
  yarn.lock
Labels: automerge

#7180 Typo in env-test README
  packages/env-tests/README.md
Labels: automerge

#7189 Update README.md
  packages/sdk/contractkit/README.md
Labels: automerge

#7182 Add staging to truffle config
  packages/protocol/truffle-config.js
Labels: automerge

#7165 Added warning to Release Gold docs
  packages/docs/celo-holder-guide/release-gold.md
Labels: automerge, docs

#7175 Update notes-web3-with-contractkit.md
  packages/docs/developer-resources/contractkit/notes-web3-with-contractkit.md
Labels: automerge, devX, docs

#7028 Parameterise Oracle deployments by CurrencyPair
  .env.alfajores
  .env.baklava
  .env.oracledev
  .env.rc1
  packages/celotool/src/cmds/deploy/destroy/oracle.ts
  packages/celotool/src/cmds/deploy/initial/oracle.ts
  packages/celotool/src/cmds/deploy/upgrade/oracle.ts
  packages/celotool/src/lib/context-utils.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/celotool/src/lib/k8s-oracle/aks-hsm.ts
  packages/celotool/src/lib/k8s-oracle/aws-hsm.ts
  packages/celotool/src/lib/k8s-oracle/base.ts
  packages/celotool/src/lib/k8s-oracle/rbac.ts
  packages/celotool/src/lib/oracle.ts
  packages/helm-charts/oracle-rbac/Chart.yaml
  packages/helm-charts/oracle-rbac/templates/_helper.tpl
  packages/helm-charts/oracle-rbac/values.yaml
  packages/helm-charts/oracle/CELOBTC.yaml
  packages/helm-charts/oracle/CELOEUR.yaml
  packages/helm-charts/oracle/CELOUSD.yaml
  packages/helm-charts/oracle/Chart.yaml
  packages/helm-charts/oracle/templates/_helper.tpl
  packages/helm-charts/oracle/templates/pkey-secret.yaml
  packages/helm-charts/oracle/templates/statefulset.yaml
  packages/helm-charts/oracle/values.yaml
Labels: cEUR, economics

#7128 Alfajores Upgrade
  .env.alfajores
  packages/celotool/package.json
  packages/celotool/src/lib/helm_deploy.ts
  packages/helm-charts/testnet/templates/_helpers.tpl
  packages/helm-charts/testnet/templates/proxy.statefulset.yaml
Labels: automerge, blockchain, infrastructure

#7205 added cleaning script in dappkit
  packages/sdk/dappkit/package.json
Labels: automerge

#7019 Scaled up forno nodes
  .env.rc1
  packages/helm-charts/celo-fullnode/values.yaml
Labels: automerge

#7220 Support Portuguese mnemonics
  packages/celotool/package.json
  packages/cli/package.json
  packages/protocol/package.json
  packages/sdk/base/src/account.ts
  packages/sdk/utils/package.json
  packages/sdk/utils/src/account.test.ts
  packages/sdk/utils/src/account.ts
  yarn.lock
Labels: automerge

#7210 Increase epoch duration readiness check to 5 minutes
  packages/celotool/src/lib/attestation-service.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/celotool/src/lib/k8s-fullnode/base.ts
  packages/helm-charts/celo-fullnode/templates/statefulset.yaml
  packages/helm-charts/celo-fullnode/values.yaml
  packages/helm-charts/common/templates/_helpers.tpl
Labels: automerge, blockchain, infrastructure

#7256 Bump Alfajores Oracles deployment image
  .env.alfajores
Labels: automerge

#7132 Added RollingUpdate partition logic (canary deployments)
  .env
  .env.baklava
  .env.rc1
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/fullnodes.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/celotool/src/lib/k8s-fullnode/base.ts
  packages/helm-charts/celo-fullnode/values.yaml
  packages/helm-charts/common/values.yaml
  packages/helm-charts/testnet/templates/_helpers.tpl
  packages/helm-charts/testnet/templates/secondaries.statefulset.yaml
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
  packages/helm-charts/testnet/values.yaml
Labels: automerge

#7269 Upgrade dependencies of axios
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/env-tests/package.json
  packages/faucet/package.json
  packages/phone-number-privacy/signer/package.json
  packages/protocol/package.json
  yarn.lock
Labels: automerge

#6475 Improve granularity of governance tooling information
  packages/cli/src/commands/governance/approve.test.ts
  packages/cli/src/commands/governance/approve.ts
  packages/cli/src/commands/governance/show.ts
  packages/cli/src/commands/governance/view.ts
  packages/cli/src/commands/governance/viewhotfix.ts
  packages/cli/src/commands/multisig/show.ts
  packages/cli/src/utils/checks.ts
  packages/docs/command-line-interface/governance.md
  packages/sdk/contractkit/src/wrappers/BaseWrapper.ts
  packages/sdk/contractkit/src/wrappers/Governance.ts
  packages/sdk/contractkit/src/wrappers/MultiSig.ts
  packages/sdk/governance/src/proposals.ts
Labels: automerge

#6937 Properly deploy newly added Core Contracts
  packages/protocol/scripts/bash/release-on-devchain.sh
  packages/protocol/scripts/truffle/make-release.ts
Labels: automerge

#7275 Update proposals.ts
  packages/sdk/governance/src/proposals.ts
Labels: automerge

#5942 Added headers to allow cors requests in forno backend
  packages/terraform-modules/forno/main.tf
  packages/terraform-modules/forno/modules/backends/main.tf
  packages/terraform-modules/forno/modules/backends/variables.tf
  packages/terraform-modules/forno/variables.tf
Labels: automerge

#6604 Upload/Download Profile Data with CIP8
  packages/cli/src/commands/account/offchain-read.ts
  packages/cli/src/utils/off-chain-data.ts
  packages/sdk/contractkit/package.json
  packages/sdk/identity/src/offchain-data-wrapper.test.ts
  packages/sdk/identity/src/offchain-data-wrapper.ts
  packages/sdk/identity/src/offchain/accessors/authorized-signer.ts
  packages/sdk/identity/src/offchain/accessors/binary.ts
  packages/sdk/identity/src/offchain/accessors/name.ts
  packages/sdk/identity/src/offchain/accessors/pictures.ts
  packages/sdk/identity/src/offchain/accessors/simple.ts
  packages/sdk/identity/src/offchain/storage-writers.ts
  packages/sdk/identity/src/offchain/utils.ts
  packages/sdk/utils/src/ecies.ts
Labels: automerge, wallet

#7287 Clarify that the Celo protocol is not just at the level of the blockchain client
  packages/docs/celo-codebase/protocol/README.md
Labels: automerge, docs

#7203 Functions to invalidate the contracts cache
  packages/sdk/contractkit/src/contract-cache.ts
  packages/sdk/contractkit/src/web3-contract-cache.ts
Labels: Component: ContractKit, devX
