Repository celo-org/celo-monorepo, pull requests merged in 2021-06, with the labels that each got.

#7803 Using mycelo for deploying testnets
  .env
  packages/celotool/src/cmds/deploy/initial/testnet.ts
  packages/celotool/src/cmds/deploy/upgrade/testnet.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/celotool/src/lib/testnet-utils.ts
  packages/celotool/src/lib/utils.ts
  packages/celotool/src/lib/vm-testnet-utils.ts
  packages/helm-charts/common/templates/_helpers.tpl
Labels: automerge

#8028 Fix governance:build-proposal bigNumber bug
  packages/sdk/governance/src/proposals.ts
Labels: automerge

#8036 E2E Test Improvements
  packages/celotool/src/e2e-tests/sync_tests.ts
  packages/celotool/src/e2e-tests/utils.ts
  packages/celotool/src/lib/geth.ts
Labels: automerge

#8008 [L07] Unnecessary Access Control
  packages/protocol/contracts/common/Accounts.sol
Labels: automerge

#8007 [L03] Misleading comments
  packages/protocol/contracts/common/Accounts.sol
Labels: automerge

#8033 Add additional dev docs to ProxyCloneFactory.deploy
  packages/protocol/contracts/common/ProxyCloneFactory.sol
Labels: automerge

#8009 [L05] Missing Event
  packages/protocol/contracts/common/Accounts.sol
  packages/protocol/test/common/accounts.ts
Labels: automerge

#8051 Fixed nginx ip address for contexted and regional clusters
  packages/celotool/src/lib/helm_deploy.ts
Labels: automerge

#8037 Add manual personal_decrypt flow to WalletConnect CLI client
  packages/sdk/wallets/wallet-walletconnect/scripts/run-in-memory-client.ts
Labels: automerge

#8059 tobikuhlmann/update locked gold rewards docs
  packages/docs/celo-codebase/protocol/proof-of-stake/locked-gold-rewards.md
Labels: automerge

#8060 Make updateMembershipHistory in Validators.sol correct if epoch number is 0
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/contracts/governance/test/ValidatorsTest.sol
Labels: automerge

#8029 Migrate Forno instances to Kubernetes.
  .env.alfajores
  .env.baklava
  .env.rc1
  dockerfiles/celotool/Dockerfile
  dockerfiles/cloudbuild/Dockerfile
  dockerfiles/leaderboard/Dockerfile
  packages/celotool/src/cmds/deploy/destroy/fullnodes.ts
  packages/celotool/src/cmds/deploy/initial/fullnodes.ts
  packages/celotool/src/cmds/deploy/upgrade/fullnodes.ts
  packages/celotool/src/lib/blockscout.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/forno.ts
  packages/celotool/src/lib/fullnodes.ts
  packages/celotool/src/lib/gcloud_utils.ts
  packages/celotool/src/lib/k8s-fullnode/base.ts
  packages/celotool/src/lib/prometheus.ts
  packages/helm-charts/celo-fullnode/templates/service.yaml
  packages/helm-charts/celo-fullnode/templates/statefulset.yaml
  packages/helm-charts/common/templates/_helpers.tpl
  packages/helm-charts/prometheus-stackdriver/templates/service.yaml
  packages/terraform-modules/forno/main.tf
  packages/terraform-modules/forno/modules/backends/main.tf
  packages/terraform-modules/forno/modules/backends/security_policy.tf
  packages/terraform-modules/forno/modules/backends/variables.tf
  packages/terraform-modules/forno/variables.tf
  packages/terraform-modules/forno/versions.tf
Labels: automerge

#8095 Added prestop hook to fullnode template. Increased baklava memory
  .env.baklava
  packages/helm-charts/common/templates/_helpers.tpl
  packages/helm-charts/testnet/values.yaml
Labels: automerge

#8094 WalletConnect tutorial to docs sidebar
  packages/docs/SUMMARY.md
Labels: automerge

#8097 WalletConnect documentation type
  packages/docs/developer-resources/walkthroughs/wallet-connect.md
Labels: automerge

#8093 doc: Update Cohort 7 info
  packages/docs/validator-guide/celo-foundation-voting-policy.md
Labels: automerge

#8103 Remove gas price sections from docs for using Metamask.
  packages/docs/SUMMARY.md
  packages/docs/getting-started/using-metamask-with-celo/README.md
  packages/docs/getting-started/using-metamask-with-celo/choosing-the-right-gas-price.md
  packages/docs/getting-started/using-metamask-with-celo/manual-setup.md
  packages/docs/getting-started/using-metamask-with-celo/programmatic-setup.md
Labels: automerge, docs, documentation

#7179 Integration test for adding a new StableToken
  packages/protocol/test/common/integration.ts
  packages/protocol/test/constants.ts
  packages/protocol/test/stability/exchange.ts
  packages/protocol/test/stability/stabletoken.ts
Labels: automerge

#8034 Account utilities for normalization and heuristic based correction of mnemonic phrases
  packages/cli/src/commands/account/new.ts
  packages/cli/src/commands/account/recover-old.ts
  packages/sdk/utils/src/account.test.ts
  packages/sdk/utils/src/account.ts
  packages/sdk/utils/src/levenshtein.test.ts
  packages/sdk/utils/src/levenshtein.ts
  packages/sdk/utils/tsconfig.json
Labels: automerge

#8119 Add Valora-Accounts to nav page
  packages/docs/SUMMARY.md
Labels: automerge

#8067 Use non-US for Nexmo default
  packages/attestation-service/package.json
  packages/attestation-service/src/sms/nexmo.ts
Labels: automerge

#8141 Fix docs for CP-DOTO
  packages/docs/SUMMARY.md
  packages/docs/celo-codebase/protocol/stability/README.md
  packages/docs/celo-codebase/protocol/stability/adding_stable_assets.md
Labels: automerge

#8006 Update celo-for-eth-devs.md
  packages/docs/developer-resources/celo-for-eth-devs.md
Labels: automerge, docs

#8143 Changes for blockscout v.3.5.1
  packages/helm-charts/blockscout/templates/_helpers.tpl
  packages/helm-charts/blockscout/templates/blockscout-api.deployment.yaml
  packages/helm-charts/blockscout/templates/blockscout-indexer.deployment.yaml
  packages/helm-charts/blockscout/values-alfajores.yaml
  packages/helm-charts/blockscout/values-baklava.yaml
  packages/helm-charts/blockscout/values.yaml
Labels: automerge

#8140 update local signing to align w/ donut upgrade
  packages/docs/developer-resources/contractkit/notes-web3-with-contractkit.md
Labels: automerge, docs

#8104 Speed up BLS combination
  packages/phone-number-privacy/combiner/src/bls/bls-cryptography-client.ts
  packages/phone-number-privacy/combiner/src/signing/get-threshold-signature.ts
  packages/phone-number-privacy/combiner/test/index.test.ts
  packages/phone-number-privacy/combiner/test/signing/bls-signature.test.ts
Labels: automerge

#8135 Small kubernetes geth config improvements
  .env.alfajores
  .env.baklava
  packages/helm-charts/celo-fullnode/templates/statefulset.yaml
  packages/helm-charts/common/templates/_helpers.tpl
  packages/helm-charts/testnet/templates/_helpers.tpl
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
Labels: automerge

#8096 JS keystore support
  dependency-graph.json
  packages/sdk/keystores/.gitignore
  packages/sdk/keystores/.npmignore
  packages/sdk/keystores/jest.config.js
  packages/sdk/keystores/package.json
  packages/sdk/keystores/src/file-keystore.test.ts
  packages/sdk/keystores/src/file-keystore.ts
  packages/sdk/keystores/src/index.ts
  packages/sdk/keystores/src/inmemory-keystore.ts
  packages/sdk/keystores/src/keystore-base.test.ts
  packages/sdk/keystores/src/keystore-base.ts
  packages/sdk/keystores/src/keystore-wallet-wrapper.test.ts
  packages/sdk/keystores/src/keystore-wallet-wrapper.ts
  packages/sdk/keystores/src/test-constants.ts
  packages/sdk/keystores/tsconfig.json
  packages/sdk/keystores/tslint.json
  packages/sdk/keystores/typedoc.json
  yarn.lock
Labels: automerge

#8194 ODIS: Reduce error noise by not calling combine when insufficient sigs
  packages/phone-number-privacy/combiner/package.json
  packages/phone-number-privacy/combiner/src/signing/get-threshold-signature.ts
Labels: automerge

#8190 Replace Wallet with Contract Kit in readme
  README.md
Labels: automerge

#8146 Add check for phrase length in mnemonic phrase correction
  packages/sdk/utils/src/account.ts
Labels: automerge

#8203 adds AS error code documentation to README
  packages/attestation-service/README.md
Labels: automerge
