Repository celo-org/celo-monorepo, pull requests merged in 2021-03, with the labels that each got.

#7184 Small fixes in the proposal process for cEUR/Release 3
  packages/cli/src/commands/governance/propose.ts
  packages/cli/src/utils/cli.ts
  packages/sdk/contractkit/src/proxy.ts
  packages/sdk/governance/src/proposals.ts
Labels: automerge

#7291 Enable prettier for packages/celotool/src/lib and run it
  .prettierignore
  packages/celotool/src/lib/attestation-bot.ts
  packages/celotool/src/lib/attestation-service.ts
  packages/celotool/src/lib/attestation.ts
  packages/celotool/src/lib/aws.ts
  packages/celotool/src/lib/azure.ts
  packages/celotool/src/lib/blockscout.ts
  packages/celotool/src/lib/celostats.ts
  packages/celotool/src/lib/cluster.ts
  packages/celotool/src/lib/context-utils.ts
  packages/celotool/src/lib/eksportisto.ts
  packages/celotool/src/lib/endpoints.ts
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/forno.ts
  packages/celotool/src/lib/fullnodes.ts
  packages/celotool/src/lib/gcloud_utils.ts
  packages/celotool/src/lib/generate_utils.ts
  packages/celotool/src/lib/geth.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/celotool/src/lib/interfaces/geth-instance-config.ts
  packages/celotool/src/lib/k8s-cluster/aks.ts
  packages/celotool/src/lib/k8s-cluster/aws.ts
  packages/celotool/src/lib/k8s-cluster/base.ts
  packages/celotool/src/lib/k8s-cluster/gcp.ts
  packages/celotool/src/lib/k8s-cluster/utils.ts
  packages/celotool/src/lib/k8s-fullnode/aks.ts
  packages/celotool/src/lib/k8s-fullnode/aws.ts
  packages/celotool/src/lib/k8s-fullnode/base-nodeport.ts
  packages/celotool/src/lib/k8s-fullnode/base.ts
  packages/celotool/src/lib/k8s-fullnode/gcp.ts
  packages/celotool/src/lib/k8s-fullnode/utils.ts
  packages/celotool/src/lib/k8s-oracle/aks-hsm.ts
  packages/celotool/src/lib/k8s-oracle/aws-hsm.ts
  packages/celotool/src/lib/k8s-oracle/base.ts
  packages/celotool/src/lib/k8s-oracle/pkey.ts
  packages/celotool/src/lib/k8s-oracle/rbac.ts
  packages/celotool/src/lib/komenci.ts
  packages/celotool/src/lib/kubernetes.ts
  packages/celotool/src/lib/leaderboard.ts
  packages/celotool/src/lib/load-test.ts
  packages/celotool/src/lib/migration-utils.ts
  packages/celotool/src/lib/oracle.ts
  packages/celotool/src/lib/prometheus.ts
  packages/celotool/src/lib/testnet-utils.ts
  packages/celotool/src/lib/tracer-tool.ts
  packages/celotool/src/lib/transaction-metrics-exporter.ts
  packages/celotool/src/lib/vm-testnet-utils.ts
Labels: automerge, quality

#7251 doc: Add node incentive info banner
  packages/docs/celo-codebase/protocol/transactions/full-node-incentives.md
Labels: automerge, devX, docs

#7255 doc: Remove dev mode, add guide on celowallet.app
  packages/docs/celo-holder-guide/ledger.md
Labels: automerge

#7267 Add make-release-3-changes script
  packages/protocol/lib/compatibility/verify-bytecode.ts
  packages/protocol/scripts/make-release-3-changes.ts
Labels: automerge

#7311 Fix to verify release 3 modified proposals
  packages/protocol/lib/compatibility/verify-bytecode.ts
Labels: automerge

#4919 Celo blockchain machine images
  packages/docs/getting-started/hosted-nodes.md
  packages/docs/getting-started/running-a-full-node-in-alfajores.md
  packages/docs/getting-started/running-a-full-node-in-mainnet.md
  packages/terraform-modules-public/images/Makefile
  packages/terraform-modules-public/images/node.json
  packages/terraform-modules-public/images/readme.md
  packages/terraform-modules-public/images/scripts/init.sh
  packages/terraform-modules-public/images/scripts/start.sh
Labels: automerge

#7279 Update yarn.lock to remove old dependencies
  yarn.lock
Labels: automerge

#3954 Add celotool local-testnet command as an easy way to create local testnets
  .gitignore
  README-dev.md
  packages/celotool/src/cmds/geth/run.ts
  packages/celotool/src/cmds/geth/start.ts
  packages/celotool/src/cmds/local_testnet.ts
  packages/celotool/src/e2e-tests/governance_tests.ts
  packages/celotool/src/e2e-tests/replica_tests.ts
  packages/celotool/src/e2e-tests/sync_tests.ts
  packages/celotool/src/e2e-tests/utils.ts
  packages/celotool/src/lib/geth.ts
  packages/celotool/src/lib/interfaces/geth-instance-config.ts
  packages/celotool/src/lib/interfaces/geth-repository.ts
  packages/celotool/src/lib/interfaces/geth-run-config.ts
  packages/protocol/migrationsConfig.js
Labels: automerge

#6770 Configuring attestation service on Alfajores to use the Telekom provider
  .env.alfajores
  .env.baklava
  packages/celotool/src/lib/attestation-service.ts
  packages/celotool/src/lib/env-utils.ts
  packages/helm-charts/attestation-service/templates/attestation.secret.yaml
  packages/helm-charts/attestation-service/templates/attestation.statefulset.yaml
Labels: automerge

#7285 Small docs improvements
  packages/docs/developer-resources/celo-dapp-gallery.md
  packages/docs/developer-resources/overview.md
  packages/docs/developer-resources/start.md
Labels: automerge, devX, docs

#6855 CIP8 name access via the CLI
  packages/cli/src/commands/account/offchain-read.ts
  packages/cli/src/commands/account/offchain-write.ts
  packages/cli/src/commands/account/register-data-encryption-key.ts
  packages/cli/src/utils/off-chain-data.ts
  packages/docs/command-line-interface/account.md
  packages/docs/developer-resources/identity/reference/classes/_offchain_storage_writers_.awsstoragewriter.md
  packages/sdk/identity/src/offchain/storage-writers.ts
Labels: automerge

#5930 Update celo-blockchain to v1.1.1, attestation service to v1.1.0, add backup_node for chaindata backups
  packages/terraform-modules-public/gcp/celo-infra/main.tf
  packages/terraform-modules-public/gcp/celo-infra/modules/attestation-service/main.tf
  packages/terraform-modules-public/gcp/celo-infra/modules/attestation-service/startup.sh
  packages/terraform-modules-public/gcp/celo-infra/modules/attestation-service/variables.tf
  packages/terraform-modules-public/gcp/celo-infra/modules/backup_node/main.tf
  packages/terraform-modules-public/gcp/celo-infra/modules/backup_node/outputs.tf
  packages/terraform-modules-public/gcp/celo-infra/modules/backup_node/startup.sh
  packages/terraform-modules-public/gcp/celo-infra/modules/backup_node/variables.tf
  packages/terraform-modules-public/gcp/celo-infra/modules/proxy/main.tf
  packages/terraform-modules-public/gcp/celo-infra/modules/proxy/outputs.tf
  packages/terraform-modules-public/gcp/celo-infra/modules/proxy/startup.sh
  packages/terraform-modules-public/gcp/celo-infra/modules/proxy/variables.tf
  packages/terraform-modules-public/gcp/celo-infra/modules/tx-node/main.tf
  packages/terraform-modules-public/gcp/celo-infra/modules/tx-node/outputs.tf
  packages/terraform-modules-public/gcp/celo-infra/modules/tx-node/startup.sh
  packages/terraform-modules-public/gcp/celo-infra/modules/tx-node/variables.tf
  packages/terraform-modules-public/gcp/celo-infra/modules/validator/main.tf
  packages/terraform-modules-public/gcp/celo-infra/modules/validator/outputs.tf
  packages/terraform-modules-public/gcp/celo-infra/modules/validator/startup.sh
  packages/terraform-modules-public/gcp/celo-infra/modules/validator/variables.tf
  packages/terraform-modules-public/gcp/celo-infra/outputs.tf
  packages/terraform-modules-public/gcp/celo-infra/variables.tf
  packages/terraform-modules-public/gcp/example/README.md
  packages/terraform-modules-public/gcp/example/bootstrap.sh
  packages/terraform-modules-public/gcp/example/dashboards/readme.md
  packages/terraform-modules-public/gcp/example/main.tf
  packages/terraform-modules-public/gcp/example/scripts/authorize_attestation_signer.sh
  packages/terraform-modules-public/gcp/example/scripts/authorize_signer.sh
  packages/terraform-modules-public/gcp/example/scripts/cUSD_mgt/activate.sh
  packages/terraform-modules-public/gcp/example/scripts/cUSD_mgt/cold_to_hot.sh
  packages/terraform-modules-public/gcp/example/scripts/cUSD_mgt/hot_exchange.sh
  packages/terraform-modules-public/gcp/example/scripts/cUSD_mgt/hot_to_cold.sh
  packages/terraform-modules-public/gcp/example/scripts/cUSD_mgt/reamde.md
  packages/terraform-modules-public/gcp/example/scripts/cUSD_mgt/sweep_cusd.sh
  packages/terraform-modules-public/gcp/example/scripts/cUSD_mgt/vote_cold.sh
  packages/terraform-modules-public/gcp/example/scripts/generate_attestation_pop.sh
  packages/terraform-modules-public/gcp/example/scripts/generate_pop.sh
  packages/terraform-modules-public/gcp/example/scripts/metadata.sh
  packages/terraform-modules-public/gcp/example/scripts/validator transfer.txt
  packages/terraform-modules-public/gcp/example/variables.tf
Labels: automerge

#7301 Optional ReadinessProbe age check. Disable by default in testnets
  packages/celotool/src/lib/env-utils.ts
  packages/celotool/src/lib/helm_deploy.ts
  packages/celotool/src/lib/k8s-fullnode/base.ts
  packages/helm-charts/celo-fullnode/values.yaml
  packages/helm-charts/common/templates/_helpers.tpl
  packages/helm-charts/common/values.yaml
  packages/helm-charts/testnet/values.yaml
Labels: automerge

#7214 Update hello-contract-remote-node.md
  packages/docs/developer-resources/walkthroughs/hello-contract-remote-node.md
Labels: automerge

#7206 Remove `$` for command prefix
  packages/docs/developer-resources/walkthroughs/hello-contract-remote-node.md
Labels: automerge

#7302 Documentation updates
  SETUP.md
  packages/docs/developer-resources/dappkit/setup.md
  packages/docs/developer-resources/walkthroughs/hellocelo.md
Labels: automerge

#7324 Fix helm diff plugin install if not installed
  packages/celotool/src/lib/helm_deploy.ts
Labels: automerge

#7320 updates protocol-test-release branch in CI
  .circleci/config.yml
  packages/protocol/releaseData/initializationData/release4.json
Labels: automerge

#7327 Web based DApp tutorial
  packages/docs/developer-resources/start.md
  packages/docs/developer-resources/walkthroughs/web-dapp.md
Labels: Component: Dappkit, automerge, devX, docs

#7270 Make env-tests owned by CAP
  .github/CODEOWNERS
Labels: automerge

#7271 Add currency specific oracle private key derivation
  .env.alfajores
  packages/celotool/src/lib/generate_utils.ts
  packages/celotool/src/lib/oracle.ts
Labels: automerge, cEUR, economics

#7325 fix: rewards:show
  packages/sdk/contractkit/src/wrappers/Election.ts
Labels: automerge

#7235 Add ExchangeEUR and StableTokenEUR to governanceConstitution.js
  packages/protocol/governanceConstitution.js
Labels: automerge

#7336 chore: add new pages to summary.md
  packages/docs/SUMMARY.md
Labels: automerge, devX, docs

#7334 dont alias itself
  packages/sdk/contractkit/src/wrappers/Reserve.ts
Labels: Component: ContractKit, automerge, devX

#7122 WalletConnectWallet
  dependency-graph.json
  packages/sdk/wallets/wallet-walletconnect/.gitignore
  packages/sdk/wallets/wallet-walletconnect/.npmignore
  packages/sdk/wallets/wallet-walletconnect/jest.config.js
  packages/sdk/wallets/wallet-walletconnect/package.json
  packages/sdk/wallets/wallet-walletconnect/src/index.ts
  packages/sdk/wallets/wallet-walletconnect/src/test/common.ts
  packages/sdk/wallets/wallet-walletconnect/src/test/in-memory-wallet.ts
  packages/sdk/wallets/wallet-walletconnect/src/test/mock-client.ts
  packages/sdk/wallets/wallet-walletconnect/src/types.ts
  packages/sdk/wallets/wallet-walletconnect/src/wc-signer.test.ts
  packages/sdk/wallets/wallet-walletconnect/src/wc-signer.ts
  packages/sdk/wallets/wallet-walletconnect/src/wc-wallet.ts
  packages/sdk/wallets/wallet-walletconnect/tsconfig.json
  packages/sdk/wallets/wallet-walletconnect/tslint.json
  packages/sdk/wallets/wallet-walletconnect/typedoc.json
  yarn.lock
Labels: automerge, devX

#7257 cEUR ContractKit support
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/dev-utils/src/migration-override.json
  packages/protocol/package.json
  packages/protocol/scripts/build.ts
  packages/sdk/contractkit/src/base.ts
  packages/sdk/contractkit/src/celo-tokens.test.ts
  packages/sdk/contractkit/src/celo-tokens.ts
  packages/sdk/contractkit/src/contract-cache.test.ts
  packages/sdk/contractkit/src/contract-cache.ts
  packages/sdk/contractkit/src/index.ts
  packages/sdk/contractkit/src/kit.ts
  packages/sdk/contractkit/src/web3-contract-cache.ts
  packages/sdk/contractkit/src/wrappers/CeloTokenWrapper.ts
  packages/sdk/contractkit/src/wrappers/Erc20Wrapper.ts
  packages/sdk/contractkit/src/wrappers/Exchange.test.ts
  packages/sdk/contractkit/src/wrappers/Exchange.ts
  packages/sdk/contractkit/src/wrappers/GoldTokenWrapper.ts
  packages/sdk/contractkit/src/wrappers/SortedOracles.test.ts
  packages/sdk/contractkit/src/wrappers/SortedOracles.ts
  packages/sdk/contractkit/src/wrappers/StableToken.test.ts
  packages/sdk/contractkit/src/wrappers/StableTokenWrapper.ts
  yarn.lock
Labels: automerge

#6301 Add additional redirect
  .gitbook.yaml
Labels: Priority: P3, automerge, devX, docs

#7300 Deploy CELOEUR Oracles to baklava
  .env.baklava
Labels: cEUR, economics

#7316 Setup CELOBTC Oracle deployment on baklava
  .env.baklava
Labels: automerge, economics, tbtc

#7229 Split libraries from contracts in report
  packages/protocol/lib/compatibility/report.ts
  packages/protocol/lib/compatibility/utils.ts
  packages/protocol/scripts/bash/check-versions.sh
Labels: automerge

#7346 Improve dappkit example
  packages/sdk/dappkit/README.md
Labels: automerge

#7193 Extending Env-tests package to cover cEUR
  packages/env-tests/README.md
  packages/env-tests/src/monorepoRun.ts
  packages/env-tests/src/scaffold.ts
  packages/env-tests/src/tests/exchange.ts
  packages/env-tests/src/tests/oracle.ts
  packages/env-tests/src/tests/reserve.ts
  packages/env-tests/src/tests/transfer.ts
Labels: automerge

#7333 Fix ODIS input validation checks
  packages/phone-number-privacy/combiner/package.json
  packages/phone-number-privacy/combiner/src/match-making/get-contact-matches.ts
  packages/phone-number-privacy/combiner/src/signing/get-threshold-signature.ts
  packages/phone-number-privacy/combiner/test/end-to-end/resources.ts
  packages/phone-number-privacy/combiner/test/index.test.ts
  packages/phone-number-privacy/common/package.json
  packages/phone-number-privacy/common/src/index.ts
  packages/phone-number-privacy/common/src/interfaces/index.ts
  packages/phone-number-privacy/common/src/interfaces/requests.ts
  packages/phone-number-privacy/common/src/interfaces/responses.ts
  packages/phone-number-privacy/common/src/test/values.ts
  packages/phone-number-privacy/common/src/utils/input-validation.ts
  packages/phone-number-privacy/signer/package.json
  packages/phone-number-privacy/signer/src/server.ts
  packages/phone-number-privacy/signer/src/signing/query-quota.ts
  packages/phone-number-privacy/signer/test/end-to-end/get-blinded-sig.test.ts
  packages/phone-number-privacy/signer/test/index.test.ts
  yarn.lock
Labels: automerge

#7328 Add dappkit-web functionality
  packages/sdk/dappkit/package.json
  packages/sdk/dappkit/src/index.ts
  packages/sdk/dappkit/src/web.ts
  yarn.lock
Labels: automerge

#7354 use web3 from contractkit
  packages/docs/developer-resources/contractkit/usage.md
  packages/docs/developer-resources/walkthroughs/hello-contract-remote-node.md
Labels: devX, docs

#7338 View tags
  packages/docs/community/release-process/smart-contracts.md
  packages/protocol/package.json
Labels: automerge

#7359 Update using-the-mobile-wallet.md
  packages/docs/getting-started/using-the-mobile-wallet.md
Labels: automerge, docs

#7319 Fix check for unregistered contracts
  packages/sdk/contractkit/src/address-registry.ts
  packages/sdk/contractkit/src/base.ts
  packages/sdk/explorer/src/block-explorer.ts
  packages/sdk/governance/src/proposals.ts
Labels: automerge

#7350 Add instructions for Eth recovery with celowallet.app
  packages/docs/celo-holder-guide/eth-recovery.md
  packages/docs/developer-resources/contractkit/reference/README.md
  packages/sdk/contractkit/src/wrappers/Governance.ts
  packages/sdk/wallets/wallet-ledger/src/ledger-signer.ts
Labels: automerge

#7349 Update usage.md to include dappkit-web and remove outdated links
  packages/docs/developer-resources/dappkit/usage.md
Labels: automerge

#7362 Remove cEUR from contractkit
  packages/protocol/scripts/build.ts
  packages/sdk/contractkit/src/base.ts
  packages/sdk/contractkit/src/celo-tokens.ts
  packages/sdk/contractkit/src/contract-cache.test.ts
  packages/sdk/contractkit/src/contract-cache.ts
  packages/sdk/contractkit/src/kit.ts
  packages/sdk/contractkit/src/proxy.ts
  packages/sdk/contractkit/src/web3-contract-cache.ts
  packages/sdk/contractkit/src/wrappers/SortedOracles.ts
  packages/sdk/contractkit/src/wrappers/StableToken.test.ts
Labels: Component: ContractKit, automerge

#7374 doc: Update slashing block downtime number
  packages/docs/celo-codebase/protocol/proof-of-stake/penalties.md
Labels: automerge

#7372 Update usage.md to include dappkit-web and remove outdated links (#7349)
  packages/docs/developer-resources/dappkit/usage.md
Labels: automerge

#7386 Update for Cohort 7
  packages/docs/validator-guide/celo-foundation-voting-policy.md
Labels: automerge

#7423 Fix bootnode flag geth argument in testnets
  packages/helm-charts/common/templates/_helpers.tpl
Labels: automerge

#7420 Only verify deployed bytecode of contracts which have known compiled bytecode
  packages/protocol/lib/compatibility/verify-bytecode.ts
  packages/protocol/scripts/bash/release-lib.sh
Labels: automerge

#7434 Fix broken link in Celo Docs homepage
  packages/docs/README.md
Labels: automerge, bug, docs

#7443 Use smaller amounts on exchange and transfer env-tests
  packages/env-tests/src/scaffold.ts
  packages/env-tests/src/tests/exchange.ts
  packages/env-tests/src/tests/transfer.ts
Labels: automerge

#7446 Create config.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: devX

#7447 Created an issue-template.md
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: automerge, devX

#7448 Create gitcoin-bounty-issue.md
  .github/ISSUE_TEMPLATE/gitcoin-bounty-issue.md
Labels: automerge, community, devX

#7441 Update final list of cohort 6
  packages/docs/validator-guide/celo-foundation-voting-policy.md
Labels: automerge, docs

#7468 Added env-specific values files for blockscout
  .env.alfajores
  .env.baklava
  .env.rc1
  packages/celotool/src/lib/blockscout.ts
  packages/helm-charts/blockscout/templates/_helpers.tpl
  packages/helm-charts/blockscout/templates/blockscout-api.deployment.yaml
  packages/helm-charts/blockscout/templates/blockscout-indexer.deployment.yaml
  packages/helm-charts/blockscout/templates/blockscout-web.deployment.yaml
  packages/helm-charts/blockscout/values-alfajores.yaml
  packages/helm-charts/blockscout/values-baklava.yaml
  packages/helm-charts/blockscout/values-rc1.yaml
  packages/helm-charts/blockscout/values.yaml
Labels: automerge

#4062 fix(dkg): improve naming in the DKG
  packages/cli/src/commands/dkg/DKG.json
  packages/cli/src/commands/dkg/allowlist.ts
  packages/docs/command-line-interface/dkg.md
Labels: automerge, docs

#7478 Fix no approval case for governance:approver information
  packages/sdk/contractkit/src/wrappers/Governance.ts
Labels: automerge

#7462 Update issue-template.md
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: automerge

#7463 Deleting legacy issue-template.md
  .github/issue_template.md
Labels: automerge

#7476 Fix packages vulnerabilities
  dependency-graph.json
  package.json
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/dev-utils/package.json
  packages/env-tests/package.json
  packages/faucet/package.json
  packages/faucet/src/celo-adapter.ts
  packages/metadata-crawler/package.json
  packages/phone-number-privacy/combiner/package.json
  packages/phone-number-privacy/combiner/src/web3/contracts.ts
  packages/phone-number-privacy/common/package.json
  packages/phone-number-privacy/monitor/package.json
  packages/phone-number-privacy/monitor/src/query.ts
  packages/phone-number-privacy/signer/package.json
  packages/phone-number-privacy/signer/src/web3/contracts.ts
  packages/protocol/package.json
  packages/sdk/base/package.json
  packages/sdk/connect/package.json
  packages/sdk/contractkit/package.json
  packages/sdk/explorer/package.json
  packages/sdk/identity/package.json
  packages/sdk/transactions-uri/package.json
  packages/sdk/utils/package.json
  packages/sdk/wallets/wallet-hsm-aws/package.json
  packages/sdk/wallets/wallet-hsm-azure/package.json
  packages/sdk/wallets/wallet-hsm/package.json
  packages/sdk/wallets/wallet-local/package.json
  scripts/ci_check_vulnerabilities.sh
  yarn.lock
Labels: Component: ContractKit, devX, sdk

#7467 Allow DEK to be a CIP8 signer
  package.json
  packages/sdk/identity/src/offchain-data-wrapper.test.ts
  packages/sdk/identity/src/offchain-data-wrapper.ts
  yarn.lock
Labels: automerge

#7347 Amend hosted node GCP documentation
  packages/docs/getting-started/hosted-nodes.md
  packages/docs/getting-started/running-a-full-node-in-alfajores.md
  packages/docs/getting-started/running-a-full-node-in-mainnet.md
Labels: automerge

#7493 Intermediate PR to merge "Inherit Ownable directly from GoldToken and…
  packages/protocol/contracts/common/GoldToken.sol
Labels: automerge

#7489 [docs] Add link to Attestation Service 1.2.0 release
  packages/docs/validator-guide/attestation-service.md
Labels: automerge

#7418 Add e2e tests for CIP35 (eth-compatible transactions)
  .circleci/config.yml
  packages/celotool/ci_test_cip35.sh
  packages/celotool/src/e2e-tests/cip35_tests.ts
  packages/celotool/src/e2e-tests/utils.ts
  packages/celotool/src/lib/generate_utils.ts
  packages/celotool/src/lib/geth.ts
  packages/celotool/src/lib/interfaces/genesis-config.ts
  packages/celotool/src/lib/interfaces/mycelo-genesis-config.ts
Labels: automerge, blockchain, e2e testing

#7254 Adds initializableV2 contract to ensure implementation contracts are initialized
  .circleci/config.yml
  packages/dev-utils/src/ganache-test.ts
  packages/protocol/contracts/common/GoldToken.sol
  packages/protocol/contracts/common/InitializableV2.sol
  packages/protocol/contracts/common/MetaTransactionWallet.sol
  packages/protocol/contracts/governance/ReleaseGold.sol
  packages/protocol/lib/compatibility/version.ts
  packages/protocol/lib/web3-utils.ts
  packages/protocol/scripts/bash/generate-old-devchain-and-build.sh
  packages/protocol/scripts/check-backward.ts
  packages/protocol/scripts/devchain.ts
  packages/protocol/scripts/truffle/deploy_release_contracts.ts
  packages/protocol/scripts/truffle/make-release.ts
  packages/protocol/test/common/goldtoken.ts
  packages/protocol/test/common/metatransactionwallet.ts
  packages/protocol/test/common/metatransactionwalletdeployer.ts
  packages/protocol/test/common/proxy.ts
  packages/protocol/test/governance/voting/release_gold.ts
  packages/protocol/test/stability/exchange.ts
  packages/sdk/contractkit/src/wrappers/MetaTransactionWallet.test.ts
  packages/sdk/contractkit/src/wrappers/MetaTransactionWalletDeployer.test.ts
Labels: automerge

#7437 CeloCLI Staking Rewards Command should show whole Wei-
  packages/cli/src/commands/rewards/show.ts
Labels: automerge

#7484 Dappkit: remove react-native dep from dappkit-web and prompt valora download for native apps
  packages/sdk/dappkit/src/common.ts
  packages/sdk/dappkit/src/index.ts
  packages/sdk/dappkit/src/web.ts
Labels: automerge

#7508 SDK --> 1.1.1-dev & CLI --> 1.1.2-dev
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/CHANGELOG.md
  packages/cli/npm-shrinkwrap.json
  packages/cli/package.json
  packages/env-tests/package.json
  packages/metadata-crawler/package.json
  packages/protocol/package.json
  packages/sdk/CHANGELOG.md
  packages/sdk/base/package.json
  packages/sdk/connect/package.json
  packages/sdk/contractkit/package.json
  packages/sdk/dappkit/package.json
  packages/sdk/explorer/package.json
  packages/sdk/governance/package.json
  packages/sdk/identity/package.json
  packages/sdk/network-utils/package.json
  packages/sdk/transactions-uri/package.json
  packages/sdk/utils/package.json
  packages/sdk/wallets/wallet-base/package.json
  packages/sdk/wallets/wallet-hsm-aws/package.json
  packages/sdk/wallets/wallet-hsm-azure/package.json
  packages/sdk/wallets/wallet-hsm/package.json
  packages/sdk/wallets/wallet-ledger/package.json
  packages/sdk/wallets/wallet-local/package.json
  packages/sdk/wallets/wallet-remote/package.json
  packages/sdk/wallets/wallet-rpc/package.json
  packages/sdk/wallets/wallet-walletconnect/package.json
Labels: automerge

#7385 Condense, organize, fix dappkit usage docs
  packages/docs/developer-resources/dappkit/README.md
  packages/docs/developer-resources/dappkit/usage.md
  packages/sdk/dappkit/README.md
Labels: automerge

#7507 fix: small fixes for WalletConnect alpha.32
  packages/sdk/wallets/wallet-walletconnect/package.json
  packages/sdk/wallets/wallet-walletconnect/scripts/run-in-memory-client.ts
  packages/sdk/wallets/wallet-walletconnect/scripts/run-in-memory-wallet.ts
  packages/sdk/wallets/wallet-walletconnect/src/test/common.ts
  packages/sdk/wallets/wallet-walletconnect/src/test/in-memory-wallet.ts
  packages/sdk/wallets/wallet-walletconnect/src/test/mock-client.ts
  packages/sdk/wallets/wallet-walletconnect/src/types.ts
  packages/sdk/wallets/wallet-walletconnect/src/wc-signer.test.ts
  packages/sdk/wallets/wallet-walletconnect/src/wc-signer.ts
  packages/sdk/wallets/wallet-walletconnect/src/wc-wallet.ts
  yarn.lock
Labels: automerge

#7524 [CK/cli] cEUR support. CK works with StableTokens not yet deployed
  packages/celotool/src/e2e-tests/transfer_tests.ts
  packages/cli/src/base.ts
  packages/cli/src/commands/config/set.ts
  packages/cli/src/commands/exchange/celo.ts
  packages/cli/src/commands/exchange/dollars.ts
  packages/cli/src/commands/exchange/euros.ts
  packages/cli/src/commands/exchange/gold.ts
  packages/cli/src/commands/exchange/show.ts
  packages/cli/src/commands/exchange/stable.ts
  packages/cli/src/commands/network/contracts.ts
  packages/cli/src/commands/oracle/list.ts
  packages/cli/src/commands/oracle/remove-expired-reports.ts
  packages/cli/src/commands/oracle/report.ts
  packages/cli/src/commands/oracle/reports.ts
  packages/cli/src/commands/releasegold/refund-and-finalize.test.ts
  packages/cli/src/commands/releasegold/transfer-dollars.test.ts
  packages/cli/src/commands/releasegold/withdraw.test.ts
  packages/cli/src/commands/transfer/dollars.ts
  packages/cli/src/commands/transfer/euros.ts
  packages/cli/src/commands/transfer/stable.ts
  packages/cli/src/exchange-stable-base.ts
  packages/cli/src/transfer-stable-base.ts
  packages/cli/src/utils/checks.ts
  packages/cli/src/utils/config.ts
  packages/cli/src/utils/exchange.ts
  packages/cli/src/utils/helpers.ts
  packages/docs/command-line-interface/config.md
  packages/docs/command-line-interface/exchange.md
  packages/docs/command-line-interface/oracle.md
  packages/docs/command-line-interface/transfer.md
  packages/protocol/scripts/build.ts
  packages/sdk/contractkit/src/address-registry.ts
  packages/sdk/contractkit/src/base.ts
  packages/sdk/contractkit/src/celo-tokens.ts
  packages/sdk/contractkit/src/contract-cache.test.ts
  packages/sdk/contractkit/src/contract-cache.ts
  packages/sdk/contractkit/src/kit.ts
  packages/sdk/contractkit/src/proxy.ts
  packages/sdk/contractkit/src/web3-contract-cache.ts
  packages/sdk/contractkit/src/wrappers/SortedOracles.ts
  packages/sdk/contractkit/src/wrappers/StableToken.test.ts
Labels: automerge

#7544 [Docs] MessageBird needs numbers configured for both US and Canada
  packages/docs/validator-guide/attestation-service.md
Labels: automerge

#7208 Update hellocelo.md
  packages/docs/developer-resources/walkthroughs/hellocelo.md
Labels: automerge, docs

#7496 doc: Update docs to comply with Ledger guidelines
  packages/docs/celo-holder-guide/ledger.md
Labels: automerge

#7552 Add PR reminder to add/update docs
  .github/pull_request_template.md
Labels: automerge

#7542 Set name and symbol of the native ERC-20 currency to CELO
  packages/protocol/contracts/common/GoldToken.sol
  packages/protocol/contracts/governance/Election.sol
  packages/protocol/contracts/governance/Governance.sol
  packages/protocol/contracts/governance/Proposals.sol
  packages/protocol/contracts/governance/ReleaseGold.sol
  packages/protocol/contracts/stability/Reserve.sol
  packages/protocol/contracts/stability/SortedOracles.sol
  packages/protocol/scripts/truffle/deploy_release_contracts.ts
  packages/protocol/test/common/goldtoken.ts
  packages/protocol/test/governance/voting/release_gold.ts
  packages/sdk/contractkit/src/wrappers/GoldToken.test.ts
Labels: automerge

#7511 Included new accountTypes and feeRecipient for validators
  packages/celotool/src/cmds/generate/account-address.ts
  packages/celotool/src/cmds/generate/address-from-env.ts
  packages/celotool/src/lib/generate_utils.ts
  packages/helm-charts/common/templates/_helpers.tpl
  packages/helm-charts/testnet/templates/secondaries.statefulset.yaml
  packages/helm-charts/testnet/templates/validators.statefulset.yaml
  packages/terraform-modules/testnet/modules/validator/startup.sh
Labels: automerge

#7564 Remove commented out code
  packages/protocol/scripts/build.ts
Labels: automerge

#7567 Rename variables
  packages/protocol/scripts/bash/check-versions.sh
Labels: automerge

#7566 Remove unnecessary comma
  packages/protocol/lib/compatibility/report.ts
Labels: automerge

#7559 Certora specs: missing constructor in harness
  packages/protocol/specs/harnesses/GoldTokenHarness.sol
Labels: automerge

#7572 Resolution on y18n version
  package.json
  yarn.lock
Labels: automerge

#7546 Update @celo/utils to allow AccountAuthResponseSuccess to include pepper
  packages/docs/developer-resources/dappkit/usage.md
  packages/sdk/utils/src/dappkit.ts
Labels: automerge

#7565 Make bash script variables local
  packages/protocol/scripts/bash/release-lib.sh
Labels: automerge
