Repository celo-org/celo-monorepo, pull requests merged in 2022-01, with the labels that each got.

#9106 Add ability to specify API key to contract kit
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/env-tests/package.json
  packages/metadata-crawler/package.json
  packages/sdk/contractkit/package.json
  packages/sdk/contractkit/src/kit.test.ts
  packages/sdk/contractkit/src/kit.ts
  packages/sdk/dappkit/package.json
  packages/sdk/explorer/package.json
  packages/sdk/governance/package.json
  packages/sdk/identity/package.json
  packages/sdk/transactions-uri/package.json
  packages/sdk/wallets/wallet-rpc/package.json
  packages/sdk/wallets/wallet-walletconnect/package.json
Labels: automerge

#8993 Allow validators to delegate part of their epoch payment
  packages/protocol/contracts/common/Accounts.sol
  packages/protocol/contracts/common/interfaces/IAccounts.sol
  packages/protocol/contracts/governance/Validators.sol
  packages/protocol/contracts/stability/test/MockStableToken.sol
  packages/protocol/specs/accountsPrivileged.spec
  packages/protocol/test/common/accounts.ts
  packages/protocol/test/governance/validators/validators.ts
Labels: automerge

#9126 Grafana hook
  .env
  .env.alfajores
  .env.baklava
  .env.rc1
  .env.rc1staging
  packages/celotool/src/cmds/deploy/initial/blockscout.ts
  packages/celotool/src/cmds/deploy/upgrade/blockscout.ts
  packages/celotool/src/lib/blockscout.ts
  packages/helm-charts/blockscout/scripts/grafana-hook.sh
  packages/helm-charts/blockscout/templates/grafana-configmap.yaml
  packages/helm-charts/blockscout/templates/grafana-hook.yaml
  packages/helm-charts/blockscout/values-alfajores-blockscout2.yaml
  packages/helm-charts/blockscout/values-alfajores-blockscout3.yaml
  packages/helm-charts/blockscout/values-baklava-blockscout2.yaml
  packages/helm-charts/blockscout/values-baklava-blockscout3.yaml
  packages/helm-charts/blockscout/values-blockscoutstagingrc1-blockscout3.yaml
  packages/helm-charts/blockscout/values-rc1-blockscout1.yaml
  packages/helm-charts/blockscout/values-rc1-blockscout3.yaml
  packages/helm-charts/blockscout/values-rc1staging-blockscout.yaml
  packages/helm-charts/blockscout/values.yaml
Labels: don't merge

#8334 Fixed Exchanges.sol reverting on deployment due to expecting sortedOracles report on Empty Address
  packages/protocol/contracts/stability/Exchange.sol
  packages/protocol/contracts/stability/ExchangeEUR.sol
  packages/protocol/migrations/10_0_exchange_USD.ts
  packages/protocol/migrations/10_1_exchange_EUR.ts
  packages/protocol/migrations/10_2_exchange_BRL.ts
  packages/protocol/test/common/integration.ts
  packages/protocol/test/stability/exchange.ts
Labels: automerge

#7299 CELOEUR Oracle Staging deployment
  .env.staging
  packages/celotool/src/lib/endpoints.ts
Labels: automerge, economics, cEUR

#9153 Bump to v1.5.2
  .mergify.yml
  cloudbuild.yaml
  package.json
  packages/attestation-service/package.json
  packages/celotool/package.json
  packages/cli/package.json
  packages/env-tests/package.json
  packages/faucet/package.json
  packages/metadata-crawler/package.json
  packages/phone-number-privacy/combiner/package.json
  packages/phone-number-privacy/common/package.json
  packages/phone-number-privacy/monitor/package.json
  packages/phone-number-privacy/signer/package.json
  packages/protocol/package-lock.json
  packages/protocol/package.json
  packages/sdk/base/package.json
  packages/sdk/connect/package.json
  packages/sdk/contractkit/package.json
  packages/sdk/dappkit/package.json
  packages/sdk/explorer/package.json
  packages/sdk/governance/package.json
  packages/sdk/identity/package.json
  packages/sdk/identity/src/odis/matchmaking.ts
  packages/sdk/identity/src/odis/phone-number-identifier.ts
  packages/sdk/identity/src/odis/query.ts
  packages/sdk/identity/tsconfig.json
  packages/sdk/keystores/package.json
  packages/sdk/network-utils/package.json
  packages/sdk/phone-utils/package.json
  packages/sdk/transactions-uri/package.json
  packages/sdk/utils/package.json
  packages/sdk/wallets/wallet-base/package.json
  packages/sdk/wallets/wallet-hsm-aws/package.json
  packages/sdk/wallets/wallet-hsm-azure/package.json
  packages/sdk/wallets/wallet-hsm/package.json
  packages/sdk/wallets/wallet-ledger/package.json
  packages/sdk/wallets/wallet-local/package.json
  packages/sdk/wallets/wallet-remote/package.json
  packages/sdk/wallets/wallet-rpc/package.json
  yarn.lock
Labels: automerge
